### ISSUE TITLE
Ruby's make install fails due to updated RubyGems

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#1013]
Testing with ruby 2.2.0dev (2014-09-15 trunk 47594) [x86_64-linux], ```make install``` fails during build of Fedora package.

```
$ make install DESTDIR=/builddir/build/BUILDROOT/ruby-2.2.0-0.24.r47594.fc22.x86_64
...
snip
...
installing bundle gems:       /usr/share/ruby/gems/ (build_info, cache, doc, extensions, gems, specifications)
/builddir/build/BUILD/ruby-2.2.0-r47594/lib/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /usr/share/ruby (Errno::EACCES)
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/fileutils.rb:252:in `fu_mkdir'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/fileutils.rb:226:in `block (2 levels) in mkdir_p'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/fileutils.rb:224:in `reverse_each'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/fileutils.rb:224:in `block in mkdir_p'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/fileutils.rb:210:in `each'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/fileutils.rb:210:in `mkdir_p'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems/installer.rb:644:in `verify_gem_home'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems/installer.rb:765:in `pre_install_checks'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems/installer.rb:231:in `install'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems/request_set.rb:166:in `block in install'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems/request_set.rb:150:in `each'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems/request_set.rb:150:in `install'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems/dependency_installer.rb:394:in `install'
	from /builddir/build/BUILD/ruby-2.2.0-r47594/lib/rubygems.rb:552:in `install'
	from ./tool/rbinstall.rb:726:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:725:in `each'
	from ./tool/rbinstall.rb:725:in `block in <main>'
	from ./tool/rbinstall.rb:756:in `call'
	from ./tool/rbinstall.rb:756:in `block in <main>'
	from ./tool/rbinstall.rb:753:in `each'
	from ./tool/rbinstall.rb:753:in `<main>'
uncommon.mk:241: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```

This seems to be cause by 1a7a043e242374 and the change in method signature. I thrown in this simple debug output:

```
$ git diff
diff --git a/lib/rubygems.rb b/lib/rubygems.rb
index 4535206..0e20191 100644
--- a/lib/rubygems.rb
+++ b/lib/rubygems.rb
@@ -547,6 +547,7 @@ module Gem
   #   => [#<Gem::Specification:0x1013b4528 @name="minitest", ...>]
 
   def self.install name, version = Gem::Requirement.default, *options
+puts "*** version: #{version}, options: #{options}"
     require "rubygems/dependency_installer"
     inst = Gem::DependencyInstaller.new(*options)
     inst.install name, version
```

The latest code output is:
```
*** version: {:install_dir=>"/builddir/build/BUILDROOT/ruby-2.2.0-0.24.r47594.fc22.x86_64/usr/share/ruby/gems/", :domain=>:local, :ignore_dependencies=>true}, options: []
```

While previously, it used to be:

```
*** version: >= 0, options: {:install_dir=>"/builddir/build/BUILDROOT/ruby-2.2.0-0.24.r47594.fc22.x86_64/usr/share/ruby/gems/", :domain=>:local, :ignore_dependencies=>true}
```

The former (current) is obviously wrong.

I hope this is not due to some regression in Ruby. I tested previosuly with r47551 and everything worked at that time.

**Comment by copiousfreetime** [comment]
Checking in to see if this issue still needs some sort of resolution or is it a moot issue now.

**Comment by voxik** [comment]
Don't remember any issues recently. Either all packages on Fedora's side have applied patches or it works. But I think the latter is the case.

**Comment by copiousfreetime** [comment]
alright, I'll call it abandoned for a week and then close

**Comment by duckinator** [comment]
Closing since this has been marked as abandoned for nearly a month.
