### ISSUE TITLE
rubygems 2.2.2 Windows : Cannot install gem on windows through proxy

### ISSUE THREAD

**Issue by GPif** [rubygems/rubygems#1068]
I could not set my gem to download my gems througs proxy.
When I tried to install or update any gems I had :
getaddrinfo: Unknown Host

My proxy was set as an environement with 
set http_proxy=http://user:password@proxy_ip

I made it works by altering the remote_fetcher.rb file with the following (ugly) patch:
```
231c231,238
<     response   = request uri, fetch_type, last_modified
---
>     #response   = request uri, fetch_type, last_modified
> 	
> 	proxy_addr = 'proxy_ip'
> 	proxy_port = 8080
> 	proxy_user = 'user'
> 	proxy_pass = 'password'
> 	
> 	Net::HTTP.start(uri.host, uri.port, proxy_addr, proxy_port, proxy_user, proxy_pass) do |http|
233,238c240,248
<     case response
<     when Net::HTTPOK, Net::HTTPNotModified then
<       head ? response : response.body
<     when Net::HTTPMovedPermanently, Net::HTTPFound, Net::HTTPSeeOther,
<          Net::HTTPTemporaryRedirect then
<       raise FetchError.new('too many redirects', uri) if depth > 10
---
> 		request = Net::HTTP::Get.new uri
> 		response = http.request request
> 		
> 		case response
> 		when Net::HTTPOK, Net::HTTPNotModified then
> 		  head ? response : response.body
> 		when Net::HTTPMovedPermanently, Net::HTTPFound, Net::HTTPSeeOther,
> 			 Net::HTTPTemporaryRedirect then
> 		  raise FetchError.new('too many redirects', uri) if depth > 10
240c250
<       location = URI.parse response['Location']
---
> 		  location = URI.parse response['Location']
242,244c252,254
<       if https?(uri) && !https?(location)
<         raise FetchError.new("redirecting to non-https resource: #{location}", uri)
<       end
---
> 		  if https?(uri) && !https?(location)
> 			raise FetchError.new("redirecting to non-https resource: #{location}", uri)
> 		  end
246,249c256,260
<       fetch_http(location, last_modified, head, depth + 1)
<     else
<       raise FetchError.new("bad response #{response.message} #{response.code}", uri)
<     end
---
> 		  fetch_http(location, last_modified, head, depth + 1)
> 		else
> 		  raise FetchError.new("bad response #{response.message} #{response.code}", uri)
> 		end
> 	end

```

**Comment by djberg96** [comment]
I see this in gem help env:

    If you are behind a proxy server, RubyGems uses the HTTP_PROXY,
    HTTP_PROXY_USER and HTTP_PROXY_PASS environment variables to discover the
    proxy server.

Unless I've misunderstood, I believe this addresses the OP's complaint.

**Comment by davestephens** [comment]
For those coming across this a couple of years later like I have, it's worth noting that `gem install -P <proxy_url>` also works nicely.

**Comment by NormanDunbar** [comment]
Or, sadly not! :( At least, on WIndows 7:

Setting the environment variables, which work for other utilities:

````
HTTPS_PROXY=http://proxy.mydomain.com:8080
HTTPS_PROXY_PASS=my current password
HTTPS_PROXY_USER=my current login name
HTTP_PROXY=%HTTPS_PROXY%
HTTP_PROXY_PASS=%HTTP_PROXY_PASS%
HTTP_PROXY_USER=%HTTP_PROXY_USER%
````
It also fails if I set the HTTP_PROXY with the username and password 'inline' and delete the other environment variables.

Attempting a `gem update` with `--debug --verbose`:

````
C:\Users\hisg494\Downloads\temp>gem update asciidoctor asciidoctor-pdf asciidoctor-latex --verbose --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `NameError' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/fiddle/import.rb:157 - uninitialized constant Fiddle::Function::STDCALL
Updating installed gems
Exception `Win32::Registry::Error' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:250 - No more data is available.
Exception `Errno::EEXIST' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:230 - File exists @ dir_s_mkdir - C:/Users/hisg494/.gem/specs/api.rubygems.org%443
Exception `Errno::ENOENT' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:325 - No such file or directory @ rb_file_s_stat - :/Users/hisg494/.gem/specs/api.rubygems.org%443/specs.4.8
Exception `Net::HTTPServerException' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:122 - 407 "Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )"
Exception `Net::HTTPServerException' at C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:964 - 407 "Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )"
ERROR:  While executing gem ... (Net::HTTPServerException)
    407 "Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )"
    
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:122:in ` error!'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:131:in ` value'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:925:in `connect'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:887:in `do_start' 
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:882:in `start'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/request/http_pool.rb:43:in `setup_connection'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/request/https_pool.rb:7:in `setup_connection'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/request/http_pool.rb:39:in `make_connection'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/request/http_pool.rb:20:in `checkout'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/request.rb:132:in `connection_for'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/request.rb:187:in `perform_request'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/request.rb:156:in `fetch'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:368:in `request'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:251:in `fetch_http'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:292:in `fetch_path'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:327:in `cache_update_path'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/source.rb:190:in `load_specs'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/spec_fetcher.rb:263:in `tuples_for'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/spec_fetcher.rb:229:in `block in available_specs'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/spec_fetcher.rb:223:in `available_specs'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/spec_fetcher.rb:103:in `search_for_dependency'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/update_command.rb:119:in `fetch_remote_gems'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/update_command.rb:141:in `highest_remote_version'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/update_command.rb:269:in `block in which_to_update'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/update_command.rb:265:in `each'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/update_command.rb:265:in `which_to_update'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/update_command.rb:98:in `execute'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/command.rb:310:in `invoke_with_build_args'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/command_manager.rb:169:in `process_args'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/command_manager.rb:139:in `run'
        C:/Users/hisg494/Ruby24-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:55:in`run'
        C:/Users/hisg494/Ruby24-x64/bin/gem.cmd:29:in `<main>'
````

Strangely, I was able to install the asciidoctor stuff with these settings. I also have local administrator rights on this box.

Cheers,
Norm.

**Comment by drbrain** [comment]
> `407 "Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )"`

What is the `Proxy-Authenticate` challenge?

**Comment by NormanDunbar** [comment]
Good Evening drbrain.

I'm afraid I have no idea what the proxy-authenticate challenge is (or was). There are no prompts at all.

If I do not set any of the HTTP_PROXY_* environment variables, attempting a `gem install` or `gem update` simply hangs.

Once I set the proxy details, and I use them for git too without any problems, then I get a response when I try  running `gem` but it fails with the errors shown previously. 

With other programs, SubVersion, Git and Pip (for Python) I seem to have no problems with just setting HTTP_PROXY=username:password@proxy_server:port, and with HTTPS_PROXY the same, however, from what I have read in attempting to resolve this problem, it seems that I need to keep the user and password separate from the proxy itself, and user three variables each for HTTP and HTTPS.

Sorry, I realise that this is not much help, probably. as mentioned, there were no prompts or challenges at all. Just the errors.

Cheers,
Norm.

**Comment by drbrain** [comment]
I'm sorry, I didn't provide enough detail.  The `Proxy-Authenticate` challenge comes from the header with that name on the 407 Proxy Authentication Required response.

I believe `curl -v https://api.rubygems.org/api/v1/dependencies` along with the correct proxy settings will allow you to determine the value of the challenge.  Not having an authenticating proxy I'm unsure.

We need this to determine what authentication mechanism is expected by your proxy server so we can see if that is the problem from this bug, which may need to be re-opened, or if it is unsupported and you need to file a feature request.

**Comment by drbrain** [comment]
It's looking for NTLM or Kerberos which we don't currently support.  #285 was opened, but interest was not consistent so it was closed.  Work to integrate one of the NTLM gems needs to be re-done for NTLM proxy authentication work.

PS: Change your password too

**Comment by NormanDunbar** [comment]
Hello again. 

Many thanks for your help on this matter, and I see that you beat me to the edit! I received a "the content you are editing has changed" message when I tried. Appreciate that, thanks.

I have see #285 in amongst my many seaarches and also https://stackoverflow.com/questions/4418/how-do-i-update-ruby-gems-from-behind-a-proxy-isa-ntlm etc.

So, it seems I'm somehow able to install a gem but not update from behind this NTLM proxy. I suspect I'll have to live with that then.

Thanks again. Appreciate the help.

Best regards,
Norm.
