### ISSUE TITLE
BadRequirementError when dependency in gemspec has both lower and upper version boundary

### ISSUE THREAD

**Issue by jirutka** [rubygems/rubygems#1141]
RubyGems fails to install dependencies from gemspec (or run anything when `RUBYGEMS_GEMDEPS=-` is present) when some dependency specifies a version with both lower and upper boundary, for example:

```ruby
Gem::Specification.new do |s|
  s.name = 'foo'
  s.version = '1.0'
  s.add_runtime_dependency 'nokogiri', '>= 1.6.0', '< 1.6.4'
end
```

**Steps to reproduce:**
```sh
echo "Gem::Specification.new do |s|\n  s.name = 'foo'\n  s.version = '1.0'\n  s.add_runtime_dependency 'nokogiri', '>= 1.6.0', '< 1.6.4'\nend" > foo.gemspec
echo "gemspec" > Gemfile

gem install --file Gemfile
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement [#<Gem::Requirement:0x007fd1b2a21710 @requirements=[[">=", #<Gem::Version "1.6.0">], ["<", #<Gem::Version "1.6.4">]]>]
```

(There’s no problem when this range is specified directly in Gemfile, instead of gemspec.)

Tested with RubyGems 2.4.5 on MRI 2.2.0p0.

**Comment by tenderlove** [comment]
I fixed **this one error** in 1353358, but I'm not sure that it actually fixes the feature.  It seems like when you do `gem install`, in this example, would try to install the `foo` gem, and I'm not sure that that behavior is correct.  I *think* it's supposed to just install the dependencies, and not the gem that's defined in the gemspec.

I didn't fix that because I'm unclear how the feature is suppose to work.  @jirutka does my description make sense?  I think the feature is still broken, but I'm not sure.

**Comment by jirutka** [comment]
>  I _think_ it's supposed to just install the dependencies, and not the gem that's defined in the gemspec.

Me too, but I’m not the RubyGems developer… Maybe @drbrain will know?

There’s certainly some problem with installing the gem itself:

```sh
gem install --file Gemfile
ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: user requested 'foo (= 1.0)'
```

**Comment by jirutka** [comment]
@tenderlove It seems that there’s the same problem, as you’ve fixed, also in another class. It fails when writing a Gemfile.lock.

```
git clone --branch v1.5.1.2 https://github.com/asciidoctor/asciidoctor-doctest.git
cd asciidoctor-doctest

gem install --file Gemfile --debug
NOTE:  Debugging mode prints all exceptions even when rescued
... some exceptions (mainly OpenSSL) ...
Using mini_portile (0.6.0)
Using nokogiri (1.6.3.1)
>>> NOTE: nokogiri has been installed now! <<<
... using another gems ...
Using rake (10.4.2)
Using bundler (1.7.12)
... some OpenSSL exceptions again ...
Exception `Gem::Requirement::BadRequirementError' at /Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:89 - Illformed requirement [#<Gem::Requirement:0x007f939a816cc8 @requirements=[["~>", #<Gem::Version "1.6.3">], ["<", #<Gem::Version "1.6.4">]]>]
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement [#<Gem::Requirement:0x007f939a816cc8 @requirements=[["~>", #<Gem::Version "1.6.3">], ["<", #<Gem::Version "1.6.4">]]>]
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:89:in `parse'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:119:in `block in initialize'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:119:in `map!'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:119:in `initialize'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:77:in `new'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:77:in `block in add_DEPENDENCIES'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:72:in `map'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:72:in `add_DEPENDENCIES'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:549:in `to_s'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:642:in `write'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:227:in `install_from_gemdeps'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:213:in `install_from_gemdeps'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:189:in `execute'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
	/Users/jimmy/.rbenv/versions/2.2.0/bin/gem:21:in `<main>'
```

Note: I can’t get to that stage with the dummy `foo` gem because of the error mentioned in the previous comment.

**Comment by tenderlove** [comment]
@jirutka ya, I'm able to get that error too.  Just a guess, but I'll bet if we fix this exception, even the `asciidoctor-doctest` repo will get an error similar to the `foo` one above.  Can you open a new ticket with the repro steps you've listed here?  I can probably fix it, but I just want a ticket to keep track of it.

**Comment by jirutka** [comment]
No problem, I’ve opened #1149.

**Comment by tenderlove** [comment]
@jirutka thanks!  Just an update on the `foo` gem thing.  I tried with the `asciidoctor-doctest` you gave, and it seems like RubyGems installs `asciidoctor-doctest` as a gem (even though that's the project we're working on).  That *must* be a bug.

I'll try to fix the lockfile thing first, then fix the install problems.  What a pain. :(
