### ISSUE TITLE
BadRequirementError in writing Gemfile.lock when dependency in gemspec has both lower and upper version boundary

### ISSUE THREAD

**Issue by jirutka** [rubygems/rubygems#1149]
It seems that there’s the same problem as @tenderlove fixed in #1141 also in another class. It fails when writing a Gemfile.lock.

When running the current `master` version of rubygems:

```
git clone --branch v1.5.1.2 https://github.com/asciidoctor/asciidoctor-doctest.git
cd asciidoctor-doctest

gem install --file Gemfile --debug
NOTE:  Debugging mode prints all exceptions even when rescued
... some exceptions (mainly OpenSSL) ...
Using mini_portile (0.6.0)
Using nokogiri (1.6.3.1)
>>> NOTE: nokogiri has been installed now! <<<
... using another gems ...
Using rake (10.4.2)
Using bundler (1.7.12)
... some OpenSSL exceptions again ...
Exception `Gem::Requirement::BadRequirementError' at /Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:89 - Illformed requirement [#<Gem::Requirement:0x007f939a816cc8 @requirements=[["~>", #<Gem::Version "1.6.3">], ["<", #<Gem::Version "1.6.4">]]>]
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement [#<Gem::Requirement:0x007f939a816cc8 @requirements=[["~>", #<Gem::Version "1.6.3">], ["<", #<Gem::Version "1.6.4">]]>]
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:89:in `parse'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:119:in `block in initialize'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:119:in `map!'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:119:in `initialize'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:77:in `new'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:77:in `block in add_DEPENDENCIES'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:72:in `map'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:72:in `add_DEPENDENCIES'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:549:in `to_s'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set/lockfile.rb:642:in `write'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:227:in `install_from_gemdeps'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:213:in `install_from_gemdeps'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:189:in `execute'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
	/Users/jimmy/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
	/Users/jimmy/.rbenv/versions/2.2.0/bin/gem:21:in `<main>'
```

**Comment by pabloh** [comment]
Any news on this?

**Comment by copiousfreetime** [comment]
I just tested this out with rubygems 2.5.1 and it installs just fine, so this is probably fixed. Closing for now. @tenderlove you reopened this ticket, please correct me if I am wrong.
