### ISSUE TITLE
`ruby-head` cannot install certain gems: "NoMethodError: undefined method spec for NilClass"

### ISSUE THREAD

**Issue by digitalextremist** [rubygems/rubygems#1220]
This is happening *only* on `ruby-head` ... using `ruby-head`:

```
ruby -v
ruby 2.3.0dev (2015-04-11 trunk 50230) [x86_64-linux]
```

Trying to run `bundle install` will fail for certain gems:
```
$ bundle install
Your Gemfile lists the gem rspec (~> 3.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem rspec-log_split (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching git://github.com/abstractive/rspec-log_split.git
Fetching git://github.com/celluloid/timers.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Installing ast 2.0.0
Installing parser 2.2.0.3
Installing astrolabe 1.3.0
Installing benchmark-ips 1.2.0
Installing benchmark_suite 1.0.0
Using bundler 1.9.2
Installing hitimes 1.2.2

NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing timers (4.0.1), and Bundler cannot continue.
Make sure that `gem install timers -v '4.0.1'` succeeds before bundling.
```

Running this with `--verbose` we get:

```
NoMethodError: undefined method `spec' for nil:NilClass
/home/de/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:232:in `spec'
/home/de/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:717:in `build_extensions'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/source/path.rb:192:in `block in generate_bin'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:53:in `chdir'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/monitor.rb:211:in `mon_synchronize'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:52:in `chdir'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/source/path.rb:189:in `generate_bin'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/source/git.rb:170:in `install'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:107:in `install_gem_from_spec'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:269:in `block in install_sequentially'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/forwardable.rb:183:in `each'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/forwardable.rb:183:in `each'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:268:in `install_sequentially'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:90:in `run'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:18:in `install'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/cli/install.rb:80:in `run'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/cli.rb:157:in `install'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/cli.rb:10:in `start'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/bin/bundle:20:in `block in <top (required)>'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/bin/bundle:18:in `<top (required)>'
/home/de/.rvm/gems/ruby-head@global/bin/bundle:23:in `load'
/home/de/.rvm/gems/ruby-head@global/bin/bundle:23:in `<main>'
/home/de/.rvm/gems/ruby-head@global/bin/ruby_executable_hooks:15:in `eval'
/home/de/.rvm/gems/ruby-head@global/bin/ruby_executable_hooks:15:in `<main>'
An error occurred while installing timers (4.0.1), and Bundler cannot continue.
Make sure that `gem install timers -v '4.0.1'` succeeds before bundling.
```

Strangely, `gem install <gem> -v <version>` does work:

```
$ gem install timers -v '4.0.1'
Fetching: timers-4.0.1.gem (100%)
Successfully installed timers-4.0.1
Parsing documentation for timers-4.0.1
Installing ri documentation for timers-4.0.1
Done installing documentation for timers after 0 seconds
1 gem installed
```

But that doesn't affect the outcome of `bundle install` in the least. Same error again.

Then, if one clones the gem that's failing and tries to run `bundle install` within the scope of that gemspec, the exact same error there. *It cannot build itself.*

---

At the closest inspection I can perform at this moment without submitting a patch that breaks all the tests like last time, not knowing `bundler` or `rubygems` as well as other library's internals:

The issue does ultimately happen here, in the `rubygems/installer.rb` for `2.3.0` ( ruby-head ):

```ruby
def spec
  @package.spec
rescue Gem::Package::Error => e
  raise Gem::InstallError, "invalid gem: #{e.message}"
end
```

Like the exception raised says, `@package` is `nil` at that moment.

Here is an example `gemspec` that fails right now:

```ruby
# -*- encoding: utf-8 -*-
require File.expand_path('../lib/rspec/log_split/version', __FILE__)

Gem::Specification.new do |gem|
  gem.name          = "rspec-log_split"
  gem.version       = RSpec::LogSplit::VERSION
  gem.authors       = ["Tim Carey-Smith","digitalextremist //"]
  gem.email         = ["tim@spork.in","de@freed.network"]
  gem.description   = %q{A new logger for each example}
  gem.summary       = %q{Separate the logs between examples to allow for easier understanding}
  gem.homepage      = "https://github.com/halorgium/rspec-log_split"
  gem.license       = "MIT"

  gem.required_ruby_version     = '>= 1.9.3'

  gem.files         = `git ls-files`.split("\n")
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.require_paths = ["lib"]
  # gem.executables   = [] # tried setting this, but it doesn't matter either way.

  gem.add_development_dependency 'rake'
  gem.add_development_dependency 'bundler'
end
```

And here is the `Gemfile` for that same gem:

```ruby
source "https://rubygems.org"

gem 'bundler'
gem 'rake'

gem 'rspec', '~> 3.2'

gemspec

group :development do
  gem 'pry'
end
```

---

Last time I tried to frame this, it was believed this change broke this:

* rubygems/rubygems@620910a

But putting `attr_writer :spec` back helps nothing, since it's looking for `@package.spec` and not `#spec` ...

#### This however does fix the issue:

```ruby
def spec
  @spec || @package.spec
rescue Gem::Package::Error => e
  raise Gem::InstallError, "invalid gem: #{e.message}"
end
```

But I am not sure. So as this is preventing many, many gems from building properly from `gemspec` I am posting this in both `bundler` and `rubygems` -- whichever it doesn't apply to, I am sorry. But it seems important enough to double post. And I will post a Pull Request with the above change, but I am not confident that it is the right solution.

**Comment by tenderlove** [comment]
Can you tell me which version of rubygems you're using?  Also, can you give me a git repo I can check out and run `bundle` on to test this out (sorry I'm being lazy, I'm very sick right now :frown:).  Are you also running against rubygems/master?  The commit you referenced is not released, so I don't think that is the cause.

**Comment by digitalextremist** [comment]
@tenderlove you can try this on several repositories, such as [celluloid/timers](/celluloid/timers) the specific one that showed me this issue was [rspec-log_split](/abstractive/rspec-log_split).

I'm using `2.4.6` of rubygems. Not using rubygems/master. The strange thing to me is that it only fails under `ruby-head` so it makes me wonder if there is a special change to how instance variables can be referenced in `2.3.0` ... or what causes `@package` to be `nil` with that ruby, and not all others.

Get well man!

**Comment by digitalextremist** [comment]
Here is an example of it failing, in CI: https://travis-ci.org/celluloid/celluloid/jobs/58201750

**Comment by tenderlove** [comment]
Does it still fail on Ruby at r50302?  It's not failing for me, so maybe it's fixed in Ruby?  Here's what I'm doing:

```
[aaron@TC rspec-log_split (master)]$ ruby -v
ruby 2.3.0dev (2015-04-14 trunk 50302) [x86_64-darwin14]
[aaron@TC rspec-log_split (master)]$ gem -v
2.4.6
[aaron@TC rspec-log_split (master)]$ bundler -v
Bundler version 1.9.2
[aaron@TC rspec-log_split (master)]$ bundle install
Your Gemfile lists the gem rake (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem bundler (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Resolving dependencies...
Using rake 10.4.2
Using bundler 1.9.2
Using coderay 1.1.0
Using diff-lcs 1.2.5
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using rspec-support 3.2.2
Using rspec-core 3.2.3
Using rspec-expectations 3.2.1
Using rspec-mocks 3.2.1
Using rspec 3.2.0
Using rspec-log_split 0.1.2 from source at .
Bundle complete! 7 Gemfile dependencies, 13 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
[aaron@TC rspec-log_split (master)]$
```

**Comment by indirect** [comment]
I also couldn't get this to fail in the Bundler version of this ticket. Seems like it has been fixed by some combination of ruby, rubygems, and bundler.

**Comment by digitalextremist** [comment]
@tenderlove, @indirect, yes; I also see this issue has been resolved silently, by some unknown fix -- possibly on a `ruby-head` level. Thanks for your help.

**Comment by bogdanRada** [comment]
this seems to be happening again

**Comment by bogdanRada** [comment]
it works though with gem --version 2.4.8 but fails with 2.5.1
