### ISSUE TITLE
Master raises exception when calling `gem` method

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#1236]
The Bundler specs call the `gem` method in [spec_helper.rb](https://github.com/bundler/bundler/blob/master/spec/spec_helper.rb#L12), and apparently just calling that method is enough to cause an exception. This is the backtrace:

```
/home/travis/build/bundler/bundler/tmp/rubygems/lib/rubygems/specification.rb:804:in `stubs_for': undefined method `sort_by!' for #<Array:0x7fe7d7eeae28> (NoMethodError)
	from /home/travis/build/bundler/bundler/tmp/rubygems/lib/rubygems/specification.rb:804:in `each_value'
	from /home/travis/build/bundler/bundler/tmp/rubygems/lib/rubygems/specification.rb:804:in `stubs_for'
	from /home/travis/build/bundler/bundler/tmp/rubygems/lib/rubygems/dependency.rb:277:in `matching_specs'
	from /home/travis/build/bundler/bundler/tmp/rubygems/lib/rubygems/dependency.rb:298:in `to_specs'
	from /home/travis/build/bundler/bundler/tmp/rubygems/lib/rubygems/dependency.rb:327:in `to_spec'
	from /home/travis/build/bundler/bundler/tmp/rubygems/lib/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/travis/build/bundler/bundler/spec/spec_helper.rb:12
	from /home/travis/build/bundler/bundler/spec/bundler/bundler_spec.rb:2:in `require'
	from /home/travis/build/bundler/bundler/spec/bundler/bundler_spec.rb:2
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.3/exe/rspec:4
```

**Comment by segiddins** [comment]
Is this only happening on 1.8.7? I believe 1.9.x introduced `sort_by!`.

**Comment by indirect** [comment]
Nope, it's failing on 1.8.7, 1.9.3, 2.0.0, 2.1, and 2.2: https://travis-ci.org/bundler/bundler/builds/60471303

**Comment by tenderlove** [comment]
@indirect looks like the exception is different between the different versions.  b39d3da3bd3170b64ae95a4954f30b9e9a5be687 should fix the 1.8 support.  I'm running the bundler tests to find the other issues, but it will take a while to fix. :frowning:

**Comment by indirect** [comment]
@tenderlove ugh :( that's frustrating. If there's anything I can do to help, let me know!

**Comment by tenderlove** [comment]
I think we can close this now. If not, please reopen (or bump the ticket)
