### ISSUE TITLE
A signing_key without a valid cert gives unfriendly error

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#1413]
Minor issue, but thought I would mention it. I tried adding a signing key before I had actually added the cert. Or, in one case, before I made the cert readable. This is the result:

    NoMethodError: undefined method `extensions' for nil:NilClass

A more informative error message would be better here.

**Comment by djberg96** [comment]
Full backtrace:
```
NoMethodError: undefined method `extensions' for nil:NilClass
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:71:in `extract_name'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:109:in `sign'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_writer.rb:200:in `add_file_signed'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:231:in `add_metadata'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:254:in `block (2 levels) in build'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_writer.rb:86:in `new'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:253:in `block in build'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:26:in `open'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:26:in `with_write_io'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:252:in `build'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:115:in `build'
	from (irb):4
	from /Users/dberger/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```
