### ISSUE TITLE
GEM_PATH being reset on extconf.rb extensions

### ISSUE THREAD

**Issue by aespinosa** [rubygems/rubygems#1422]
I'm installing the dep_selector-1.0.3 gem with one of its dependencies dep-selector-libgecode-1.0.2 in a separate GEM_PATH.

I get the following error:

```
GEM_PATH=/directory-b-with-dep-selector-libgecode GEM_HOME=/directory-a gem install dep_selector
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/2jxdlb28kglj4kmi4q27pfzp6n666ni4-ruby-2.2.3-p0/bin/$(RUBY_BASE_NAME)
/nix/store/2jxdlb28kglj4kmi4q27pfzp6n666ni4-ruby-2.2.3-p0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:58:in `require': cannot load such file -- dep-selector-libgecode (LoadError)
        from /nix/store/2jxdlb28kglj4kmi4q27pfzp6n666ni4-ruby-2.2.3-p0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:58:in `require'
        from extconf.rb:27:in `<main>'
```

I added some debugging `rubygems/core_ext/kernel_require.rb` and found that my GEM_PATH is being set to null. I print out `Gem.path` as well and it doesn't contain the path for dep-selector-libgecode.

**Comment by krainboltgreene** [comment]
Very interesting. Can I get some platform details?

**Comment by aespinosa** [comment]
Hi,

I pasted my `gem env` here: https://gist.github.com/aespinosa/cb209e0c0b69434d7b80

**Comment by aespinosa** [comment]
I haven't worked on this since then and have lost my own context for this. closing.
