### ISSUE TITLE
Building Ruby 2.3.0 from Source fails

### ISSUE THREAD

**Issue by dariusgm** [rubygems/rubygems#1456]
OS: Debian x64
gcc: version 4.7.2 (Debian 4.7.2-5)

I wanted to try out the new feature of ruby 2.3.0. After doing `./configure --prefix=/tmp/ruby-2.2.3/2.2.3 --enable-load-relative --with-static-linked-ext --disable-install-doc --disable-install-rdoc` I tried `make` and get the following output:

```
make[1]: Leaving directory `/tmp/ruby-2.3.0/ruby-2.3.0'
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
/tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/security.rb:344:in `<module:Security>': uninitialized constant OpenSSL::Digest::SHA1 (NameError)
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/security.rb:332:in `<top (required)>'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/package.rb:44:in `<top (required)>'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/installer.rb:10:in `<top (required)>'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-2.3.0/ruby-2.3.0/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./tool/rbinstall.rb:657:in `<module:RbInstall>'
	from ./tool/rbinstall.rb:585:in `<main>'
```

I will post a snipped of this file here:
```
  # Digest algorithm used to sign gems

  DIGEST_ALGORITHM =
    if defined?(OpenSSL::Digest) then
      OpenSSL::Digest::SHA1
    end
```

changing this to
```
  DIGEST_ALGORITHM =
    if defined?(OpenSSL::Digest) && defined?(OpenSSL::Digest::SHA1) then
      OpenSSL::Digest::SHA1
    end
```
at least "skipped" the error, but I don't now if this is a good approach. What am I doing wrong?

**Comment by Nghi93** [comment]
https://bugs.ruby-lang.org/issues/11940

**Comment by segiddins** [comment]
This is fixed on RubyGems master.
