### ISSUE TITLE
gem update fails:

### ISSUE THREAD

**Issue by BradWalker** [rubygems/rubygems#1528]
I'm having a problem.

My current problem is "gem update" fails for me. This is running under Cygwin64. Historically this has been rock solid, at least for me.

```
$ gem update
ERROR:  Loading command: update (LoadError)
        No such process - /usr/lib/ruby/2.2.0/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
$ ls /usr/lib/ruby/2.2.0/
bigdecimal.so    dbm.so     etc.so     gdbm.so  objspace.so  pty.so       readline.so  stringio.so  win32ole.so
continuation.so  digest     fcntl.so   io       openssl.so   racc         ripper.so    strscan.so   zlib.so
coverage.so      digest.so  fiber.so   mathn    pathname.so  rbconfig     sdbm.so      syslog.so
date_core.so     enc        fiddle.so  nkf.so   psych.so     rbconfig.rb  socket.so    thread.so

Brad@work-computer ~
$

```

Here are my current envrionment details:

```
$ gem env version
2.4.8

$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [x86_64-cygwin]
  - INSTALLATION DIRECTORY: /home/Brad/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby.exe
  - EXECUTABLE DIRECTORY: /home/Brad/bin
  - SPEC CACHE DIRECTORY: /home/Brad/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-cygwin
  - GEM PATHS:
     - /home/Brad/.gem/ruby
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /cygdrive/c/ProgramData/Oracle/Java/javapath
     - /cygdrive/c/Program Files (x86)/AMD APP/bin/x86_64
     - /cygdrive/c/Program Files (x86)/AMD APP/bin/x86
     - /cygdrive/c/WINDOWS/system32
     - /cygdrive/c/WINDOWS
     - /cygdrive/c/WINDOWS/System32/Wbem
     - /cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0
     - /cygdrive/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static
     - /cygdrive/c/Program Files (x86)/AMD/ATI.ACE/Core-Static
     - /cygdrive/c/Program Files/Intel/WiFi/bin
     - /cygdrive/c/Program Files/Common Files/Intel/WirelessCommon
     - /cygdrive/c/Program Files (x86)/Common Files/Acronis/SnapAPI
     - /cygdrive/c/Program Files (x86)/QuickTime/QTSystem
     - /cygdrive/c/Program Files (x86)/Windows Live/Shared
     - /cygdrive/c/Program Files (x86)/Skype/Phone
     - /cygdrive/c/Program Files/Intel/WiFi/bin
     - /cygdrive/c/Program Files/Common Files/Intel/WirelessCommon
     - /usr/bin

Brad@work-computer ~

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by BradWalker** [comment]
Any suggestion on where to look or what to provide to help determine this bug are most appreciated.

**Comment by copiousfreetime** [comment]
@BradWalker best bet would be to execute `gem update --verbose --backtrace --debug`. It will be quite verbose. put that output here or in a gist and we can go from there. If there is a particular gem you want to update, that will probably cut down on the output so you can do `gem update GEMNAME --verbose --backtrace --debug`.

**Comment by BradWalker** [comment]
Here is the output..

```

Brad@work-computer ~
$ gem update GEMNAME --verbose --backtrace --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /usr/lib/ruby/2.2.0/openssl.so - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/security.rb:13 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:133 - No such process - /usr/lib/ruby/2.2.0/openssl.so
Exception `NameError' at /usr/share/rubygems/rubygems/command_manager.rb:208 - uninitialized constant Gem::Commands::UpdateCommand
ERROR:  Loading command: update (LoadError)
        No such process - /usr/lib/ruby/2.2.0/openssl.so
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/ruby/2.2.0/openssl.rb:17:in `<top (required)>'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/security.rb:11:in `<top (required)>'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/package.rb:43:in `<top (required)>'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/dependency_installer.rb:3:in `<top (required)>'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/commands/update_command.rb:3:in `<top (required)>'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        /usr/share/rubygems/rubygems/command_manager.rb:204:in `load_and_instantiate'
        /usr/share/rubygems/rubygems/command_manager.rb:124:in `[]'
        /usr/share/rubygems/rubygems/command_manager.rb:182:in `find_command'
        /usr/share/rubygems/rubygems/command_manager.rb:167:in `process_args'
        /usr/share/rubygems/rubygems/command_manager.rb:138:in `run'
        /usr/share/rubygems/rubygems/gem_runner.rb:54:in `run'
        /usr/bin/gem:21:in `<main>'
Exception `NoMethodError' at /usr/share/rubygems/rubygems/command_manager.rb:168 - undefined method `invoke_with_build_args' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
        /usr/share/rubygems/rubygems/command_manager.rb:168:in `process_args'
        /usr/share/rubygems/rubygems/command_manager.rb:138:in `run'
        /usr/share/rubygems/rubygems/gem_runner.rb:54:in `run'
        /usr/bin/gem:21:in `<main>'

Brad@work-computer ~
$
```

**Comment by copiousfreetime** [comment]
Can you try the following:
`ruby -e "puts $:" -e "require 'openssl'" -e "puts OpenSSL::OPENSSL_LIBRARY_VERSION"`

**Comment by BradWalker** [comment]
```
Brad@work-computer ~
$ ruby -e "puts $:" -e "require 'openssl'" -e "puts OpenSSL::OPENSSL_LIBRARY_VERSION"
/usr/local/share/ruby/site_ruby
/usr/local/lib/ruby/site_ruby/2.2.0
/usr/share/ruby/vendor_ruby
/usr/lib/ruby/vendor_ruby/2.2.0
/usr/share/rubygems
/usr/share/ruby/2.2.0
/usr/lib/ruby/2.2.0
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': No such process - /usr/lib/ruby/2.2.0/openssl.so (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/ruby/2.2.0/openssl.rb:17:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:2:in `<main>'

Brad@work-computer ~
$

```

**Comment by copiousfreetime** [comment]
Unfortunately it looks like your ruby installation is the problem. For some reason in your `openssl.rb` when it attempts to load the binary OpenSSL extension, it is unable to find/load the actual file. Or it might have to do with symbol exporting of the library, unsure.

This may lend some additional insight:

`ruby -e "require '/usr/lib/ruby/2.2.0/openssl.so" -e "puts OpenSSL::VERSION" -e "puts OpenSSL::OPENSSL_LIBRARY_VERSION"`

In all likelihood I think you need to reinstall/rebuild your ruby installation.

**Comment by copiousfreetime** [comment]
I'm going to close this as it appears to be an issue with your ruby installation and not with rubygems.
