### ISSUE TITLE
File::flock method breaks rubygems

### ISSUE THREAD

**Issue by sploadie** [rubygems/rubygems#1535]
I'm found a problem in rubygems 2.4.8

My current problem is that ruby's flock can fail if the user is not a superuser.

This issue is related to:

  - [x] Installing a library
  - [X] The command line `gem`

Here are my current envrionment details:

```
$ gem env version
2.4.8

$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: USER_HOME/.rvm/gems/ruby-2.2.1
  - RUBY EXECUTABLE: USER_HOME/.rvm/rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: USER_HOME/.rvm/gems/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: USER_HOME/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - USER_HOME/.rvm/gems/ruby-2.2.1
     - USER_HOME/.rvm/gems/ruby-2.2.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => :really
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - USER_HOME/.rvm/gems/ruby-2.2.1/bin
     - USER_HOME/.rvm/gems/ruby-2.2.1@global/bin
     - USER_HOME/.rvm/rubies/ruby-2.2.1/bin
     - USER_HOME/.rvm/bin
     - USER_HOME/.brew/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/texbin
```

The confounding error I found started at:
```
$ gem install bundler -V --backtrace
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=bundler
200 OK
Downloading gem bundler-1.11.2.gem
GET https://api.rubygems.org/gems/bundler-1.11.2.gem
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/gems/bundler-1.11.2.gem
Fetching: bundler-1.11.2.gem (100%)
200 OK
ERROR:  While executing gem ... (Errno::ENOTSUP)
    Operation not supported @ rb_file_flock - USER_HOME/.rvm/gems/ruby-2.2.1/cache/bundler-1.11.2.gem
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:316:in `flock'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:316:in `block in cache_update_path'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:315:in `open'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:315:in `cache_update_path'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:174:in `download'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/source.rb:210:in `download'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/resolver/activation_request.rb:60:in `download'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:160:in `block in install'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `each'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `install'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:249:in `install_gem'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `each'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `install_gems'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:202:in `execute'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
  USER_HOME/.rvm/rubies/ruby-2.2.1/bin/gem:21:in `<main>'
```

The error ENOTSUP could not be found in the documentation, and was not caught by rubygems. To fix this, I edited the lines around `USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:773` to the following:

```
  def self.read_binary(path)
    open path, 'rb+' do |f|
      f.flock(File::LOCK_EX)
      f.read
    end
  rescue Errno::EACCES, Errno::ENOTSUP
    open path, 'rb' do |f|
      f.read
    end
  end
```

The problem was effectively muted by adding `Errno::ENOTSUP` to the `rescue` originally intended for file rights.
However, then the following error occured:

```
$ gem install bundler -V --backtrace
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=bundler
200 OK
Downloading gem bundler-1.11.2.gem
GET https://api.rubygems.org/gems/bundler-1.11.2.gem
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/gems/bundler-1.11.2.gem
Fetching: bundler-1.11.2.gem (100%)
200 OK
ERROR:  While executing gem ... (Errno::ENOTSUP)
    Operation not supported @ rb_file_flock - USER_HOME/.rvm/gems/ruby-2.2.1/cache/bundler-1.11.2.gem
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:316:in `flock'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:316:in `block in cache_update_path'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:315:in `open'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:315:in `cache_update_path'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:174:in `download'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/source.rb:210:in `download'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/resolver/activation_request.rb:60:in `download'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:160:in `block in install'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `each'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `install'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:249:in `install_gem'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `each'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `install_gems'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:202:in `execute'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
  USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
  USER_HOME/.rvm/rubies/ruby-2.2.1/bin/gem:21:in `<main>'
```

The code at `USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:316` also needed to be edited to bypass the ENOTSUP error, and I used the following crude method (I'm sure there is a better way):

```
  def cache_update_path uri, path = nil, update = true
    mtime = path && File.stat(path).mtime rescue nil

    data = fetch_path(uri, mtime)

    if data == nil # indicates the server returned 304 Not Modified
      return Gem.read_binary(path)
    end

    if update and path
      open(path, 'wb') do |io|
        begin
          io.flock(File::LOCK_EX)
        rescue Errno::ENOTSUP
        end
        io.write data
      end
    end

    data
  end
```

Following these edits, the gem installed without a hitch.
Thank you for your time.

**Comment by segiddins** [comment]
Can you check if 2.6.1 still exhibits this issue?

**Comment by sploadie** [comment]
It seems that 2.6.1 also gives the same errors.

```
$ gem install bundler --backtrace
ERROR:  While executing gem ... (Errno::ENOTSUP)
    Operation not supported @ rb_file_flock - USER_HOME/.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/bundler-1.11.2.gemspec
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:814:in `flock'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:814:in `block in read_binary'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:813:in `open'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:813:in `read_binary'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/source.rb:146:in `fetch_spec'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/resolver/api_specification.rb:77:in `spec'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/resolver/activation_request.rb:89:in `full_spec'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/resolver/activation_request.rb:119:in `installed?'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:157:in `block in install'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `each'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `install'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:251:in `install_gem'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:301:in `block in install_gems'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:297:in `each'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:297:in `install_gems'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:204:in `execute'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:310:in `invoke_with_build_args'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:169:in `process_args'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:139:in `run'
	USER_HOME/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:55:in `run'
	USER_HOME/.rvm/rubies/ruby-2.2.1/bin/gem:21:in `<main>'

$ gem -v
2.6.1
```

After checking the files I edited earlier, it seems the relevant code hasn't changed.
Thank you for your fast response!

**Comment by segiddins** [comment]
Adding `ENOTSUP` to https://github.com/rubygems/rubygems/pull/1417/files would presumably fix the issue

**Comment by sploadie** [comment]
Yes, as stated in the original post, that edit is part of the solution. However `remote_fetcher.rb` needs to be modified as well.

**Comment by sploadie** [comment]
Would it be helpful for me to create a pull request?

**Comment by segiddins** [comment]
Yes, a PR with tests would be much appreciated.
