### ISSUE TITLE
Rake installed gem without version

### ISSUE THREAD

**Issue by BjornMelgaard** [rubygems/rubygems#1628]
This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [x] The command line `gem`
- [ ] Other

I generated gem using `juwelier` and didn't point version, so rake install it with name like "slim-angular-"

```
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: slim-angular
  Version: 
  File: slim-angular-.gem
Executing "ruby -S gem install ./pkg/slim-angular-.gem":
ruby -S gem install ./pkg/slim-angular-.gem
Successfully installed slim-angular-
Installing ri documentation for slim-angular-
```

This couse to 

```
/usr/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:207:in `initialize': Malformed version number string ruby (ArgumentError)
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:199:in `new'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:199:in `new'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:42:in `initialize'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:122:in `new'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:122:in `block in data'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `open'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `data'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:202:in `valid?'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:749:in `select'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:749:in `gemspec_stubs_in'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:774:in `block in map_stubs'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `each'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `flat_map'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `map_stubs'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:763:in `installed_stubs'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:831:in `stubs'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1036:in `find_by_path'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems.rb:189:in `try_activate'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /usr/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from <internal:gem_prelude>:6:in `<internal:gem_prelude>'
```

```
$ gem env version
2.6.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Can you please share the gemspec?

**Comment by BjornMelgaard** [comment]
```
# -*- encoding: utf-8 -*-
# stub: slim-angular  ruby lib

Gem::Specification.new do |s|
  s.name = "slim-angular".freeze
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["bjornmelgaard".freeze]
  s.date = "2016-05-25"
  s.description = "use a ~tilde to generate {{angular}} syntax and other".freeze
  s.email = "bjornmelgaard@gmail.com".freeze
  s.extra_rdoc_files = ["LICENSE.txt".freeze, "README.rdoc".freeze]
  s.files = ["LICENSE.txt".freeze, "README.rdoc".freeze]
  s.homepage = "http://github.com/BjornMelgaard/slim-angular".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.3".freeze
  s.summary = "angular/handlebars support for slim".freeze

  s.installed_by_version = "2.6.3" if s.respond_to? :installed_by_version

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<slim>.freeze, ["~> 3.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
    else
      s.add_dependency(%q<slim>.freeze, ["~> 3.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<slim>.freeze, ["~> 3.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
  end
end

```

**Comment by djberg96** [comment]
```
if s.respond_to? :specification_version then
    s.specification_version = 4
```
Can someone remind me again why people do this? I've forgotten.

**Comment by segiddins** [comment]
@djberg96 pretty sure this is actually output from `Specification#to_ruby`

**Comment by bronzdoc** [comment]
I can reproduce this, this bug actually makes rubygems unusable, every command will trigger that error once the gem is installed.
