### ISSUE TITLE
'Require' method malfunctioning via rubygems/core_ext/kernel_require

### ISSUE THREAD

**Issue by geoffdavis92** [rubygems/rubygems#1649]
I'm having a problem or would like to suggest a feature.

My current problem is 'Require' cannot load files for various Ruby-based CLI programs, tracing to the `/rubygems/core_ext/kernel_require` file. Full message after trying to run `$ sass --watch main.sass:main.css`: 
<pre>
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- listen (LoadError)
</pre>

Full trace here:
<pre>
$ sass --watch main.sass:main.css --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- listen (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/util.rb:1253:in `load_listen!'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:391:in `create_listener'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:330:in `watch'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/plugin.rb:109:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/exec/sass_scss.rb:360:in `watch_or_update'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/exec/sass_scss.rb:51:in `process_result'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/exec/base.rb:52:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/lib/sass/exec/base.rb:19:in `parse!'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.22/bin/sass:13:in `<top (required)>'
	from /usr/bin/sass:22:in 'load'
	from /usr/bin/sass:22:in '&lt;main>'
</pre>

The same loading issue happens with Sass, Compass, Jekyll, and Middleman.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.4
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Can you please provide full steps to reproduce the issue? Thanks!

**Comment by geoffdavis92** [comment]
@segiddins: I'm not sure what the exact root of the issue is, mostly because I started seeing this issue after working on a team project.

However, when I started debugging today, here are the steps:

1. Remove all gems, related binaries
2. Reinstall Sass, Jekyll, Middleman, Compass via `gem install`
3. When running any one of these commands, I will get an issue notifying me that 'require' cannot load the a specific file, different for each CLI program. (Based on the Sass message, I'm guessing it's the file/module that watches files, since I can still use the `sass` command, but get the error when running `sass --watch`)

I have not yet reinstalled Ruby, but I'll try that if there are no other options to consider.

Thanks!

**Comment by segiddins** [comment]
I can't reproduce the issue with the given steps

**Comment by geoffdavis92** [comment]
Do you recommend I reinstall Ruby then?

**Comment by segiddins** [comment]
No, the first step would be to try using a different GEM_PATH & GEM_HOME and creating a script that does what you're doing

**Comment by drbrain** [comment]
What does `gem env` say?

What does ``head -n1 `which sass` `` say?

**Comment by bronzdoc** [comment]
Closing for inactivity, please re-open with the information @drbrain asked, thanks.
