### ISSUE TITLE
Installing pre release gems is giving conflicting dependency errors

### ISSUE THREAD

**Issue by rafaelfranca** [rubygems/rubygems#1653]
When I try to install rails 5.0.0.rc2 I'm getting the following error:

```
$ gem install rails -v 5.0.0.rc2
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies activesupport (= 3.0.0) and activesupport (= 5.0.0.rc2)
  Activated activesupport-5.0.0.rc2
  which does not match conflicting dependency (= 3.0.0)

  Conflicting dependency chains:
    rails (= 5.0.0.rc2), 5.0.0.rc2 activated, depends on
    activesupport (= 5.0.0.rc2), 5.0.0.rc2 activated

  versus:
    rails (= 5.0.0.rc2), 5.0.0.rc2 activated, depends on
    sprockets-rails (>= 2.0.0), 2.0.0 activated, depends on
    actionpack (>= 3.0), 3.0.0 activated, depends on
    activesupport (= 3.0.0)
```

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.6
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/rafaelfranca/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/rafaelfranca/.rbenv/versions/2.3.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/rafaelfranca/.rbenv/versions/2.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/rafaelfranca/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/rafaelfranca/.rbenv/versions/2.3.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
     - /Users/rafaelfranca/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc"
     - :benchmark => false
     - :sources => ["https://rubygems.org"]
```

**Comment by helsus** [comment]
Also tried to install rails 5.0.0.rc2.
My circular dependency error: (camping & rack 😮)
```
$ gem install rails -v 5.0.0.rc2 --verbose                                                    ⏎
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rails
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=actioncable,actionmailer,actionpack,actionview,activejob,activemodel,activerecord,activesupport,bundler,railties,sprockets-rails
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=sprockets
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=concurrent-ruby,rack
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=i18n,minitest,nio4r,tzinfo,websocket-driver
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=websocket-extensions
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=camping,fcgi,memcache-client,mongrel,rack-test,rails-dom-testing,rails-html-sanitizer,ruby-openid,test-spec,thin
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=arel
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=globalid
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=cgi_multipart_eof_fix,daemons,fastthread,gem_plugin,json,thread_safe
200 OK
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between camping and rack
```

My env:
```
 gem env                                                                                     ⏎
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.6
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/helsus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/helsus/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/helsus/.rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/helsus/.rbenv/versions/2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/helsus/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/helsus/.rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/helsus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
     - /Users/helsus/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
```

**Comment by segiddins** [comment]
For now, a workaround could be `ruby -rbundler/inline -e "gemfile(true) do; source 'https://rubygems.org/'; gem 'rails', '5.0.0.rc2'; end"` but that's obviously a hack and we will fix this in rubygems

**Comment by etcook** [comment]
@segiddins I tried that command and got this. 

> /Users/ecook/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/inline (LoadError)
> 	from /Users/ecook/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 

Any way to force the gem's installation?

**Comment by segiddins** [comment]
@etcook well that'd only work if you have bundler 1.10+ installed, sorry I should've mentioned that

**Comment by etcook** [comment]
@segiddins You're officially the man. If anyone asks, tell them @etcook said so.

**Comment by olleolleolle** [comment]
Another Rails rc is out, and people try this, again.

So I had the activating-a-too-early-version of sprockets-rails, like this bug is about.

Then I tried to use the listed workaround:

```shell
ruby -rbundler/inline -e "gemfile(true) do; source 'https://rubygems.org/'; gem 'rails', '5.0.1.rc1'; end"
```

This gave me:

```
/Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:366:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'rails (= 5.0.1.rc1)' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:341:in `each'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:341:in `verify_gemfile_dependencies_are_found!'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:199:in `start'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:181:in `resolve'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/installer.rb:171:in `ensure_specs_are_compatible!'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/installer.rb:79:in `run'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/inline.rb:63:in `gemfile'
	from -e:1:in `<main>'
```

<details>

`gem env` gave me:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/olle/.gem/ruby/2.3.3
  - USER INSTALLATION DIRECTORY: /Users/olle/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/olle/.rubies/ruby-2.3.3/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/olle/.gem/ruby/2.3.3/bin
  - SPEC CACHE DIRECTORY: /Users/olle/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/olle/.rubies/ruby-2.3.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/olle/.gem/ruby/2.3.3
     - /Users/olle/.rubies/ruby-2.3.3/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/", "http://gems.github.com"]
     - "install" => "--no-rdoc"
     - "update" => "--no-rdoc"
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
     - http://gems.github.com
  - SHELL PATH:
     - /Users/olle/.gem/ruby/2.3.3/bin
     - /Users/olle/.rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/bin
     - /Users/olle/.rubies/ruby-2.3.3/bin
```
</details>

**Comment by hsbt** [comment]
I can install `gem i rails -v 5.0.0.rc2` with RG 2.7.3. And This issue seems to steal status.

**Comment by rafaelfranca** [comment]
❤️
