### ISSUE TITLE
Error gem install and saying No route to host

### ISSUE THREAD

**Issue by mardinw** [rubygems/rubygems#1698]
I'm having a problem or would like to suggest a feature.

My current problem is  Error gem install and saying "No route to host"
This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.6
$ sudo gem install jekyll rdoc --debug -V
Password: 
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /usr/lib64/ruby/2.2.0/resolv.rb:168 - LoadError
Exception `Errno::EHOSTUNREACH' at /usr/lib64/ruby/2.2.0/resolv.rb:810 - No route to host - recvfrom(2)
ERROR:  While executing gem ... (Errno::EHOSTUNREACH)
    No route to host - recvfrom(2)
        /usr/lib64/ruby/2.2.0/resolv.rb:810:in `recv'
        /usr/lib64/ruby/2.2.0/resolv.rb:810:in `recv_reply'
        /usr/lib64/ruby/2.2.0/resolv.rb:690:in `request'
        /usr/lib64/ruby/2.2.0/resolv.rb:528:in `block in fetch_resource'
        /usr/lib64/ruby/2.2.0/resolv.rb:1096:in `block (3 levels) in resolv'
        /usr/lib64/ruby/2.2.0/resolv.rb:1094:in `each'
        /usr/lib64/ruby/2.2.0/resolv.rb:1094:in `block (2 levels) in resolv'
        /usr/lib64/ruby/2.2.0/resolv.rb:1093:in `each'
        /usr/lib64/ruby/2.2.0/resolv.rb:1093:in `block in resolv'
        /usr/lib64/ruby/2.2.0/resolv.rb:1091:in `each'
        /usr/lib64/ruby/2.2.0/resolv.rb:1091:in `resolv'
        /usr/lib64/ruby/2.2.0/resolv.rb:519:in `fetch_resource'
        /usr/lib64/ruby/2.2.0/resolv.rb:509:in `each_resource'
        /usr/lib64/ruby/2.2.0/resolv.rb:490:in `getresource'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/source.rb:47:in `api_uri'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/source.rb:86:in `dependency_resolver_set'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/resolver/best_set.rb:24:in `block in pick_sets'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/source_list.rb:98:in `each'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/source_list.rb:98:in `each_source'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/resolver/best_set.rb:23:in `pick_sets'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/resolver/best_set.rb:29:in `find_all'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/resolver/installer_set.rb:156:in `find_all'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/resolver/installer_set.rb:55:in `add_always_install'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:194:in `install_gem'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:255:in `block in install_gems'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:251:in `each'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:251:in `install_gems'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:158:in `execute'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/command.rb:310:in `invoke_with_build_args'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:169:in `process_args'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:139:in `run'
        /usr/lib64/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:55:in `run'
        /usr/bin/gem:21:in `<main>'

```
Before it's work for installing, but while upgrade to current is saying error...

Note: Im using Slackware64-current
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by mardinw** [comment]
Solved... my slackware reinstall again. Because packet for openssl is broken.
