### ISSUE TITLE
'gem install' fails and I'm unable to continue installing any gems

### ISSUE THREAD

**Issue by lisamschachtschneider** [rubygems/rubygems#1735]
My current problem is `gem install` fails with `ERROR:  While executing gem ... (TypeError)     no implicit conversion of nil into String`

The output of `gem install rails --debug` or `gem install jekyll --debug` for instance is the same:
```
Exception `TypeError' at /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/installer.rb:227 - no implicit conversion of nil into String
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/installer.rb:227:in `check_executable_overwrite'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/installer.rb:468:in `block in generate_bin'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/installer.rb:455:in `each'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/installer.rb:455:in `generate_bin'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/installer.rb:295:in `install'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/request_set.rb:167:in `block in install'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/request_set.rb:151:in `each'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/request_set.rb:151:in `install'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/commands/install_command.rb:250:in `install_gem'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
	/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
	/usr/local/bin/gem:21:in `<main>'
```

When I try to run `bundle update` I also receive an error pointing to the` Gem:Module`: 
```
$ bundle update
/usr/local/bin/bundle:22:in `<main>': undefined method `activate_bin_path' for Gem:Module (NoMethodError)
```

This issue is related to:
  - [X] Installing a library

Here are my current environment details:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/LMS/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/LMS/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.3.1_2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```

Any help would be most appreciated! Please let me know if you need additional information. I greatly appreciate your time.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
do `gem update --system` and try again

**Comment by lisamschachtschneider** [comment]
That didn't work at first but after I ran `xcode-select --install` then it went through. I must have missed something after I upgraded to Sierra. Thanks for your help!

**Comment by TorvaldsDB** [comment]
gem update --system
I tried and worked successly

**Comment by TorvaldsDB** [comment]
`gem update --system`
I tried and worked successly`

**Comment by ziggyjosh16** [comment]
even running gem update --system returns the same error

**Comment by JoakimLiu** [comment]
`sudo gem update --system` not work,  still show `ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String`

**Comment by ksredd** [comment]
Hello facing issue with gem update --system
error:
ssl verification error at depth2: self signed certificate in certificate chain(19)
root certificate is not trusted (/CN=corporate CA 1)
while executing gem........(Gem::remotefetcher::fetcher)
ssl_connect returned=1 error =1 state=error certificate error failed self signed certificate in certificate chain https://rubygems.org/specs.4.8.gz)

**Comment by ksredd** [comment]
highly appreciated someones help here
