### ISSUE TITLE
Can't execute a prerelease gem

### ISSUE THREAD

**Issue by artemshein** [rubygems/rubygems#1839]
I'm having a problem or would like to suggest a feature.

My current problem is: I have a prerelease gem product-1.6.0.L20170213.c8b36b6a.0ca72e72, I have installed it with `gem install`, when I try to run an executable from it get this:

     C:/Ruby233-x64/lib/ruby/2.3.0/rubygems.rb:197:in` `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)

        from C:/Ruby233-x64/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'

        from C:/Ruby233-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'

        from C:/Ruby233-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'

        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/product-1.6.0.L20170213.c8b36b6a.0ca72e72/bin/product:2:in `<top (required)>'

        from C:/Ruby233-x64/bin/product:22:in `load'

        from C:/Ruby233-x64/bin/product:22:in `<main>'

Can't find correct way to do it.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by artemshein** [comment]
Reinstalled it and it works now.
