### ISSUE TITLE
RubyGems test suite occasionally changes working directory and breaks the rest of test suite

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#1991]
Originally, I reported this in Ruby tracker [[1]], but here might be more versed audience.

From time to time, RubyGems test suite changes working directory, which breaks rest of Ruby tests suite. It all starts like this:

~~~
[ 7096/17125] TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection = 0.01 sLeaked file descriptor: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection: 21 : #<TCPServer:fd 21, AF_INET, 0.0.0.0, 45301>
Leaked file descriptor: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection: 22 : #<TCPServer:fd 22, AF_INET6, ::, 45301>
Leaked file descriptor: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection: 23 : #<IO:fd 23>
Leaked file descriptor: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection: 24 : #<IO:fd 24>
Leaked thread: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection: #<Thread:0x000056191465fe40@/home/hsbt/chkbuild/tmp/build/20170818T003002Z/ruby/test/rubygems/test_gem_remote_fetcher.rb:1025 sleep>
Environment variable changed: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection : "GEM_PRIVATE_KEY_PASSPHRASE" added
Environment variable changed: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection : "GEM_SPEC_CACHE" added
Environment variable changed: TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection : "HOME" changed : "/home/hsbt" -> "/home/hsbt/chkbuild/tmp/build/20170818T003002Z/tmp/test_rubygems_29019/userhome"
~~~

and results in errors such as:

~~~
  2) Failure:
TestMkmf::TestConfig#test_dir_config [/home/hsbt/chkbuild/tmp/build/20170818T003002Z/ruby/test/mkmf/test_config.rb:12]:
assert_separately failed with error message
pid 2383 exit 1
| /home/hsbt/chkbuild/tmp/build/20170818T003002Z/ruby/lib/mkmf.rb:228:in `expand_path': No such file or directory - getcwd (Errno::ENOENT)
|   from /home/hsbt/chkbuild/tmp/build/20170818T003002Z/ruby/lib/mkmf.rb:228:in `<module:MakeMakefile>'
|   from /home/hsbt/chkbuild/tmp/build/20170818T003002Z/ruby/lib/mkmf.rb:48:in `<top (required)>'
|   from -:1:in `require'
~~~

You can find the full log at rubyci.org [[2]].

[1]: https://bugs.ruby-lang.org/issues/13834
[2]: http://rubyci.s3.amazonaws.com/fedora26/ruby-trunk/log/20170818T003002Z.log.html.gz

**Comment by voxik** [comment]
The shorter reproducer is just `make check 'TESTS=-v test/rubygems/test_gem_remote_fetcher.rb'`

**Comment by segiddins** [comment]
Can you reproduce this just using this repo?

**Comment by voxik** [comment]
~~~
$ git checkout 2.6

$ gem list

*** LOCAL GEMS ***

minitest (4.7.0)
openssl (2.0.3)
psych (2.2.2)

$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

$ for i in {1..1000}; do echo "*** $i"; GEM_PATH=/usr/share/gems/ RUBYOPT="--disable-gems -Ilib:test" ruby -e 'Dir.glob "./test/rubygems/test_gem_remote_fetcher.rb", &method(:require)'; done
*** 1
Run options: --seed 6748

# Running tests:

....................................................

Finished tests in 3.126873s, 16.6300 tests/s, 28.7827 assertions/s.

52 tests, 90 assertions, 0 failures, 0 errors, 0 skips
*** 2

... snip ...

*** 44
Run options: --seed 9150

# Running tests:

..........E.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Finished tests in 0.541589s, 96.0138 tests/s, 35.0820 assertions/s.

  1) Error:
TestGemRemoteFetcher#test_implicit_upper_case_proxy:
Errno::EADDRINUSE: Address already in use - listen(2)
    /usr/share/ruby/socket.rb:695:in `listen'
    /usr/share/ruby/socket.rb:695:in `block in tcp_server_sockets_port0'
    /usr/share/ruby/socket.rb:694:in `each'
    /usr/share/ruby/socket.rb:694:in `tcp_server_sockets_port0'
    /usr/share/ruby/socket.rb:743:in `tcp_server_sockets'
    /usr/share/ruby/webrick/utils.rb:65:in `create_listeners'
    /usr/share/ruby/webrick/ssl.rb:157:in `listen'
    /usr/share/ruby/webrick/server.rb:109:in `initialize'
    /usr/share/ruby/webrick/httpserver.rb:47:in `initialize'
    /mnt/test/rubygems/test_gem_remote_fetcher.rb:995:in `new'
    /mnt/test/rubygems/test_gem_remote_fetcher.rb:995:in `start_server'
    /mnt/test/rubygems/test_gem_remote_fetcher.rb:907:in `start_servers'
    /mnt/test/rubygems/test_gem_remote_fetcher.rb:101:in `setup'

  2) Error:
TestGemRemoteFetcher#test_implicit_upper_case_proxy:
NoMethodError: undefined method `close_all' for nil:NilClass
    /mnt/test/rubygems/test_gem_remote_fetcher.rb:126:in `teardown'

  3) Error:
TestGemRemoteFetcher#test_download_with_auth:
Errno::ENOENT: No such file or directory - getcwd
    /mnt/lib/rubygems/test_case.rb:233:in `pwd'
    /mnt/lib/rubygems/test_case.rb:233:in `setup'
    /mnt/test/rubygems/test_gem_remote_fetcher.rb:100:in `setup'

... snip ...
~~~

**Comment by segiddins** [comment]
I cannot reproduce this on my machine

**Comment by voxik** [comment]
I am testing this on Fedora Rawhide, but apparently, the test fails also on rubyci.org using Fedora 26, so that is not specific to my setup, but might be specific to Fedora.

**Comment by segiddins** [comment]
I only have a macOS machine, so someone else will have to look into this if it's Fedora specific

**Comment by pvalena** [comment]
I can confirm the issue still occurs in Fedora Rawhide (2017-09-18) with Ruby 2.4.2:
```
 . . . 
DEBUG: [ 7130/16940] TestGemRemoteFetcher#test_download_local = 0.00 sEnvironment variable changed: TestGemRemoteFetcher#test_download_local : "GEM_PRIVATE_KEY_PASSPHRASE" added
DEBUG: Environment variable changed: TestGemRemoteFetcher#test_download_local : "GEM_SPEC_CACHE" added
DEBUG: Environment variable changed: TestGemRemoteFetcher#test_download_local : "HOME" changed : "/builddir" -> "/tmp/test_rubygems_4367/userhome"
 . . .
```

And then later on, multiple errors, like: 
```
DEBUG: [ 8416/16940] TestIO#test_foreachshell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
DEBUG:  = 0.03 s
```

Which results in numerous test Errors and Failures.

**Comment by hsbt** [comment]
This issue is Ruby core specific issue. We move to https://bugs.ruby-lang.org/issues/13834 .

**Comment by voxik** [comment]
@hsbt I don't understand it. The last reproducer I sent here was just RubyGems test suite ...
