### ISSUE TITLE
bundler.bat is not working after Rubygems update

### ISSUE THREAD

**Issue by FeodorFitsner** [rubygems/rubygems#2083]
The problem: running `bundler.bat` gives the following error:

```
C:\>bundler --version
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:291:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:310:in `activate_bin_path'
        from C:/Ruby24-x64/bin/bundler:23:in `<main>'
```

Platform: Windows

Steps to reproduce:

Install clean [Ruby 2.4.2-2 x64](https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.4.2-2/rubyinstaller-2.4.2-2-x64.exe)

Then do Rubygems update and install Bundler with `--force` option (otherwise it [complains about conflict with "bundle" executable](https://github.com/rubygems/rubygems/issues/2058)). After that `bundle` runs just fine and running `bundler` gives an error above:

```
C:\>ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
```

```
C:\>gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.7.2.gem (100%)
Successfully installed rubygems-update-2.7.2
Parsing documentation for rubygems-update-2.7.2
Installing ri documentation for rubygems-update-2.7.2
Installing darkfish documentation for rubygems-update-2.7.2
Done installing documentation for rubygems-update after 41 seconds
Parsing documentation for rubygems-update-2.7.2
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.2
Bundler 1.16.0 installed
RubyGems 2.7.2 installed
Regenerating binstubs
RubyGems system software updated
```

```
C:\>gem install bundler --force
Fetching: bundler-1.16.0.gem (100%)
Successfully installed bundler-1.16.0
Parsing documentation for bundler-1.16.0
Installing ri documentation for bundler-1.16.0
Done installing documentation for bundler after 7 seconds
1 gem installed
```

```
C:\>bundle --version
Bundler version 1.16.0
```

```
C:\>bundler --version
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:291:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:310:in `activate_bin_path'
        from C:/Ruby24-x64/bin/bundler:23:in `<main>'
```

It yields the same results if bundler is installed *before* Rubygems update.

**Comment by hsbt** [comment]
It's inconsistency specification between "default gems" and normal gem installation. default gems didn't provide platform-specific executables like `.bat`.

But your result of reinstallation with `gem i --force bundler` seems to be strange behavior. I try to investigate this.

**Comment by FeodorFitsner** [comment]
Thanks for looking into that! Let me know about your findings.

**Comment by FeodorFitsner** [comment]
I've noticed you did a fix, thank you! Is it coming in the next Rubygems release?

**Comment by segiddins** [comment]
Yup

**Comment by FeodorFitsner** [comment]
Awesome, thank you!

**Comment by FeodorFitsner** [comment]
@segiddins The problem came back with the latest Rubygems update. Could you please take a look?

```
ruby --version: ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
gem --version: 2.7.6
```

Error:

```
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:308:in `activate_bin_path'
        from C:/Ruby24-x64/bin/bundler:23:in `<main>'
```
