### ISSUE TITLE
error on execute "ruby setup.rb"

### ISSUE THREAD

**Issue by wilsonp** [rubygems/rubygems#2108]
I'm having a problem or would like to suggest a feature.

My current problem is error on execute "Invalid keystore format"

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

I installed the jruby 
```
rvm list

rvm rubies

=* jruby-9.1.13.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

the error message is 
```
~/tools/rubygems-2.7.3$ruby setup.rb
Bundler 1.16.0 installed
RubyGems 2.7.3 installed
java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.util.AnchorCertificates$1.run(AnchorCertificates.java:61)
	at sun.security.util.AnchorCertificates$1.run(AnchorCertificates.java:52)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.util.AnchorCertificates.<clinit>(AnchorCertificates.java:52)
	at sun.security.provider.certpath.AlgorithmChecker.checkFingerprint(AlgorithmChecker.java:214)
	at sun.security.provider.certpath.AlgorithmChecker.<init>(AlgorithmChecker.java:164)
	at sun.security.provider.certpath.AlgorithmChecker.<init>(AlgorithmChecker.java:118)
	at sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:157)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.validator.Validator.validate(Validator.java:236)
	at sun.security.validator.Validator.validate(Validator.java:205)
	at javax.crypto.JarVerifier.isTrusted(JarVerifier.java:608)
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:528)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:361)
```

and I execute "gem install" under the project also
```
gem install
java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.util.AnchorCertificates$1.run(AnchorCertificates.java:61)
	at sun.security.util.AnchorCertificates$1.run(AnchorCertificates.java:52)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.util.AnchorCertificates.<clinit>(AnchorCertificates.java:52)
at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.util.AnchorCertificates.<clinit>(AnchorCertificates.java:52)
        at sun.security.provider.certpath.AlgorithmChecker.checkFingerprint(AlgorithmChecker.java:214)
        at sun.security.provider.certpath.AlgorithmChecker.<init>(AlgorithmChecker.java:164)
        at sun.security.provider.certpath.AlgorithmChecker.<init>(AlgorithmChecker.java:118)
        at sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:157)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.validator.Validator.validate(Validator.java:236)
        at sun.security.validator.Validator.validate(Validator.java:205)
        at javax.crypto.JarVerifier.isTrusted(JarVerifier.java:608)
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:528)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:361)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:159)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:185)
        at javax.crypto.Cipher.getInstance(Cipher.java:653)
        at org.jruby.ext.openssl.SecurityHelper.getCipher(SecurityHelper.java:450)
        at org.jruby.ext.openssl.SecurityHelper.getCipher(SecurityHelper.java:419)
        at org.jruby.ext.openssl.Cipher.getCipherInstance(Cipher.java:696)
        at org.jruby.ext.openssl.Cipher.getCipherInstance(Cipher.java:975)
        at org.jruby.ext.openssl.Cipher.updateCipher(Cipher.java:970)
        at org.jruby.ext.openssl.Cipher.initializeImpl(Cipher.java:763)
        at org.jruby.ext.openssl.Cipher.initialize(Cipher.java:752)
```

**Comment by segiddins** [comment]
Hmm this is odd, there doesn't seem to be any rubygems code in the backtrace...

**Comment by wilsonp** [comment]
The error happened when I install the rubygems,but I can not to determine the problem .
Is there someone encounter this problem?

**Comment by segiddins** [comment]
I just don't see how this can be a RubyGems error, as the whole backtrace seems to just contain ruby/java core code.

**Comment by colby-swandale** [comment]
ping @wilsonp. Were you able to solve your problem? I doubt we would be able to help as we can't identify what the issue exactly is from the stack trace.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
