### ISSUE TITLE
Could not find 'addressable' (~> 2.4.0) - did find: [addressable-2.3.8]

### ISSUE THREAD

**Issue by cmhughes** [rubygems/rubygems#2185]
I'm having a problem or would like to suggest a feature.

My current problem is Could not find 'addressable' (~> 2.4.0) - did find: [addressable-2.3.8]

This issue is related to:

  - [ ] The command line `gem`

Here are my current environment details:

```
$ gem env version
2.5.2.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

I'm attempting to deploy a file from `travis-ci` back to my github repository. I'm following the instructions here https://gist.github.com/willprice/e07efd73fb7f13f917ea. When I run the command
```
echo GH_TOKEN=<my token details here> |travis encrypt --add 
```
I receive the following output:
```
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'addressable' (~> 2.4.0) - did find: [addressable-2.3.8] (Gem::LoadError)
Checked in 'GEM_PATH=/home/cmhughes/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/i386-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1440:in `block in activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1429:in `each'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1429:in `activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1411:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1443:in `block in activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1429:in `each'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1429:in `activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1411:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /usr/local/bin/travis:22:in `<main>'
```
Is this to be expected? I suspect not, and that something is wrong. Would you be able to provide some guidance, please? Many thanks for your time.

**Comment by cmhughes** [comment]
When I run 
```
gem list addressable --local``` 
```
I get
```
*** LOCAL GEMS ***

addressable (2.3.8)
```

Then, when I run 
```sudo gem install "addressable:~> 2.4.0"
gem list addressable --local
```
I get
```

*** LOCAL GEMS ***

addressable (2.4.0, 2.3.8)
```
Then, when I run 
```
echo GH_TOKEN=<my token details here> |travis encrypt --add 
```
I get
```
Detected repository as cmhughes/ci-test, is this correct? |yes| Please enter "yes" or "no".
Detected repository as cmhughes/ci-test, is this correct? |yes| The input stream is exhausted.
for a full error report, run travis report
```
So I run 
```
travis report
```
and receive
```
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-02-12 18:53:06 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis encrypt`:
    EOFError: The input stream is exhausted.
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:868:in `get_line'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/repo_command.rb:73:in `detect_slug'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/repo_command.rb:59:in `find_slug'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/repo_command.rb:20:in `setup'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:197:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```
Not sure if this helps?

**Comment by cmhughes** [comment]
Is this a `ruby` issue, or would it be more appropriate for me to migrate this to `https://github.com/travis-ci/travis.rb/issues`?

**Comment by segiddins** [comment]
It seems to me a normal error, unrelated to RubyGems at this point
