### ISSUE TITLE
Error when executing installation or update: undefined method `unpack' for nil:NilClass

### ISSUE THREAD

**Issue by LisonFan** [rubygems/rubygems#2232]
My current problem is I get an error when I update or install

![image](https://user-images.githubusercontent.com/9424775/37263872-2f4af8e8-25e5-11e8-855a-397ca0ecb6ce.png)

This issue is related to:

  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] Network problems
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by LisonFan** [comment]
@colby-swandale I solved this problem by switching sources

**Comment by LisonFan** [comment]
@colby-swandale :(
`➜  ~ git:(master) ✗ sudo gem update --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:170 - LoadError
Updating installed gems
Exception `Resolv::ResolvTimeout' at /Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:691 - Resolv::ResolvTimeout
Exception `NoMethodError' at /Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:868 - undefined method `unpack' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `unpack' for nil:NilClass
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:868:in `recv_reply'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:694:in `request'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:528:in `block in fetch_resource'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:1096:in `block (3 levels) in resolv'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:1094:in `each'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:1094:in `block (2 levels) in resolv'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:1093:in `each'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:1093:in `block in resolv'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:1091:in `each'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:1091:in `resolv'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:519:in `fetch_resource'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:509:in `each_resource'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/resolv.rb:490:in `getresource'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/source.rb:47:in `api_uri'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/source.rb:187:in `load_specs'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/spec_fetcher.rb:267:in `tuples_for'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/spec_fetcher.rb:233:in `block in available_specs'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/source_list.rb:98:in `each'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/source_list.rb:98:in `each_source'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/spec_fetcher.rb:227:in `available_specs'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/spec_fetcher.rb:103:in `search_for_dependency'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/update_command.rb:119:in `fetch_remote_gems'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/update_command.rb:141:in `highest_remote_version'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/update_command.rb:269:in `block in which_to_update'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/update_command.rb:265:in `each'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/update_command.rb:265:in `which_to_update'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/update_command.rb:98:in `execute'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/command.rb:313:in `invoke_with_build_args'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/command_manager.rb:171:in `process_args'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/command_manager.rb:141:in `run'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/gem_runner.rb:59:in `run'
	/Users/lisonfan/.rvm/rubies/ruby-2.5.0/bin/gem:21:in `<main>'`
