### ISSUE TITLE
bundler is not working after Rubygems update

### ISSUE THREAD

**Issue by arunabhdas** [rubygems/rubygems#2236]
Issue : running bundler gives the following error:

```
==> bundler --version
Traceback (most recent call last):
	2: from ~/.rbenv/versions/2.5.0/bin/bundler:23:in `<main>'
	1: from ~/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/das/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)

```

Here are my current environment details:

Platform: Mac OS X (HighSierra) 10.13.3 

Steps to reproduce:
Install Ruby as follows 
```
brew install rbenv ruby-build

# Add rbenv to bash so that it loads every time you open a terminal
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
source ~/.bash_profile

# Install Ruby

https://github.com/postmodern/ruby-install

brew install ruby-install
ruby-install ruby
```

Run ruby --version

```
==> ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

==> sudo gem update --system
Password:
Latest version already installed. Done.

==> sudo gem install bundler --force
Successfully installed bundler-1.16.1
1 gem installed

==> bundle --version
Bundler version 1.16.1

==> bundler --version
Traceback (most recent call last):
	2: from ~/.rbenv/versions/2.5.0/bin/bundler:23:in `<main>'
	1: from ~/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
~/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Does it work if you don't run `gem install bundler --force`? I believe this might be fixed by https://github.com/rubygems/rubygems/pull/2112

**Comment by bronzdoc** [comment]
ping @arunabhdas

**Comment by dcmorse** [comment]
We're having the same error and backtrace. We tried `--force` but it didn't help.
