### ISSUE TITLE
Timeout while trying to do gem install

### ISSUE THREAD

**Issue by MahadevanSrinivasan** [rubygems/rubygems#2288]
I am trying to run `gem install jekyll bundler` and run into timeout issues. This is the output I get while I run this command:

```
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
```

I can download the same specs.4.8.gz from https://api.rubygems.org/specs.4.8.gz but it takes quite some time and below is the wget output. I think gem time out is smaller than the time taken to download the file. Not sure why. When I download it from chrome, it is downloaded instantaneously. 

```
--2018-05-11 10:05:34--  https://api.rubygems.org/specs.4.8.gz
Resolving api.rubygems.org (api.rubygems.org)... 2a04:4e42:200::514, 2a04:4e42::514, 2a04:4e42:400::514, ...
Connecting to api.rubygems.org (api.rubygems.org)|2a04:4e42:200::514|:443... failed: Connection timed out.
Connecting to api.rubygems.org (api.rubygems.org)|2a04:4e42::514|:443... failed: Connection timed out.
Connecting to api.rubygems.org (api.rubygems.org)|2a04:4e42:400::514|:443... failed: Connection timed out.
Connecting to api.rubygems.org (api.rubygems.org)|2a04:4e42:600::514|:443... failed: Connection timed out.
Connecting to api.rubygems.org (api.rubygems.org)|151.101.130.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3567028 (3.4M) [application/octet-stream]
Saving to: 'specs.4.8.gz'

specs.4.8.gz            100%[============================>]   3.40M  3.44MB/s    in 1.0s    

2018-05-11 10:14:05 (3.44 MB/s) - 'specs.4.8.gz' saved [3567028/3567028]
```

So, It is not due to any SSL errors. In fact I ran this script to check if it was SSL: `ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'`

And it produces the following output: 

```
Here's your Ruby and OpenSSL environment:

Ruby:           2.3.1p112 (2016-04-26 revision 0) [arm-linux-gnueabihf]
RubyGems:       2.7.6
Bundler:        1.16.1
Compiled with:  OpenSSL 1.0.2g  1 Mar 2016
Loaded version: OpenSSL 1.0.2g  1 Mar 2016
SSL_CERT_FILE:  /usr/lib/ssl/cert.pem
SSL_CERT_DIR:   /usr/lib/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (execution expired)
RubyGems connection to rubygems.org:      failed  ❌  (timed out (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
Net::OpenTimeout: execution expired
  /usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
  /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
  /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
  /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
  /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
  /usr/lib/ruby/2.3.0/net/http.rb:858:in `start'
  (eval):88:in `<main>'
  -e:1:in `eval'
  -e:1:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/
```

Here are my current environment details:

```
$ gem env version
2.7.6
```

**Comment by MahadevanSrinivasan** [comment]
Follow-up: It worked after I disabled IPv6 on my Ubuntu machine

**Comment by duckinator** [comment]
hi! It looks like this was a local network problem, so I'm going to close the issue. Glad you figured it out. :slightly_smiling_face:
