### ISSUE TITLE
 Cannot load such file -- ubygems (LoadError).

### ISSUE THREAD

**Issue by TheRandomTroll** [rubygems/rubygems#2393]
So, I have Ubuntu 18.04 installed. After having to reinstall the desktop, due to accidentally deleting it, I was greeted by the following message:
```
Error found when loading /home/$USER/.profile:
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems 
(LoadError)
    from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```
Here are my current environment details:

```
$ gem env version
2.7.6
```

**Comment by bronzdoc** [comment]
@TheRandomTroll can you provide the content of your `.profile` file?

**Comment by TheRandomTroll** [comment]
```
$ cat .profile
# ~/.profile: executed by the command interpreter for login shells. 
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login 
# exists. 
# see /usr/share/doc/bash/examples/startup-files for examples. 
# the files are located in the bash-doc package. 

# the default umask is set in /etc/profile; for setting the umask 
# for ssh logins, install and configure the libpam-umask package. 
#umask 022 

# if running bash 
if [ -n "$BASH_VERSION" ]; then 
    # include .bashrc if it exists 
    if [ -f "$HOME/.bashrc" ]; then 
        . "$HOME/.bashrc" 
    fi 
fi 

# set PATH so it includes user's private bin if it exists 
if [ -d "$HOME/bin" ] ; then 
    PATH="$HOME/bin:$PATH" 
fi
```

**Comment by segiddins** [comment]
I believe @hsbt removed `ubygems.rb` from Ruby's vendored copy of RubyGems, my guess is that is the issue you're hitting.

**Comment by hsbt** [comment]
`ubygems.rb` was removed at Ruby 2.5. You should remove `ubygems.rb` on your code.

**Comment by duckinator** [comment]
As a note, this is usually encountered when a script is ran as `ruby -rubygems ...`. If you know what script is doing that, you can just change that to `ruby -rrubygems ...` and it should work just fine.

**Comment by bronzdoc** [comment]
Please do what @hsbt and @duckinator suggested

**Comment by bipashant** [comment]
Getting the same issue

`Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]`

```
2019/01/07 09:08:29.861160 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] test_environment/(no PID) entering state SUnbooted
2019/01/07 09:08:29.861187 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] development_environment/(no PID) entering state SUnbooted
2019/01/07 09:08:58.718903 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] boot/(no PID) entering state SUnbooted
2019/01/07 09:08:58.719171 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:391] boot/(no PID) running the root command now
2019/01/07 09:08:58.721426 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] prerake/(no PID) entering state SUnbooted
2019/01/07 09:08:58.721565 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] cucumber_environment/(no PID) entering state SUnbooted
2019/01/07 09:08:58.721599 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] development_environment/(no PID) entering state SUnbooted
2019/01/07 09:08:58.721621 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] test_environment/(no PID) entering state SUnbooted
2019/01/07 09:08:58.721671 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] test_helper/(no PID) entering state SUnbooted
2019/01/07 09:08:58.721767 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] default_bundle/(no PID) entering state SUnbooted
2019/01/07 09:08:58.847933 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:402] boot/(no PID) root process exited with an error before it could boot: exit status 1; output was: /Users/bishant/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems (LoadError)
	from /Users/bishant/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2019/01/07 09:16:50.143104 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] boot/(no PID) entering state SUnbooted
2019/01/07 09:16:50.166556 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:391] boot/(no PID) running the root command now
2019/01/07 09:16:50.143168 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] development_environment/(no PID) entering state SUnbooted
2019/01/07 09:16:50.143184 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] cucumber_environment/(no PID) entering state SUnbooted
2019/01/07 09:16:50.143194 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] default_bundle/(no PID) entering state SUnbooted
2019/01/07 09:16:50.143204 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] prerake/(no PID) entering state SUnbooted
2019/01/07 09:16:50.143249 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:149] test_environment/(no PID) entering state SUnbooted

```

**Comment by bipashant** [comment]
in my case, I was running `zeus start`

**Comment by duckinator** [comment]
@bipashant You should have a `zeus.json` somewhere. It contains a command that can be fixed as described above.

Zeus also appears to have a PR that would fix the examples that's been open since May of last year. https://github.com/burke/zeus/pull/658

**Comment by bipashant** [comment]
@duckinator Thanks, I will give a try.
