### ISSUE TITLE
gem outdated - uninitialized constant Gem::Request::OpenSSL

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2526]
1. When running `gem outdated`, an `uninitialized constant Gem::Request::OpenSSL` is thrown.

2. When then adding the `--debug` option, I see three `Errno::EEXIST` exceptions raised.  Personally, I'd rather see real exceptions, rather than ones raised by `FileUtils` when a SPEC CACHE directory exists...

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
RG: 3.0.0.beta3
RUBY: ruby 2.6.0dev (2018-12-14 trunk 66392) [x64-mingw32]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
Call stack for OpenSSL error listed below.  Not sure where the best place for the require would be...
```
uninitialized constant Gem::RemoteFetcher::OpenSSL
Ruby99-x64/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:277:in `rescue in fetch_path'
Ruby99-x64/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:253:in `fetch_path'
Ruby99-x64/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:297:in `cache_update_path'
Ruby99-x64/lib/ruby/2.6.0/rubygems/source.rb:185:in `load_specs'
Ruby99-x64/lib/ruby/2.6.0/rubygems/spec_fetcher.rb:267:in `tuples_for'
Ruby99-x64/lib/ruby/2.6.0/rubygems/spec_fetcher.rb:233:in `block in available_specs'
Ruby99-x64/lib/ruby/2.6.0/rubygems/source_list.rb:98:in `each'
Ruby99-x64/lib/ruby/2.6.0/rubygems/source_list.rb:98:in `each_source'
Ruby99-x64/lib/ruby/2.6.0/rubygems/spec_fetcher.rb:227:in `available_specs'
Ruby99-x64/lib/ruby/2.6.0/rubygems/spec_fetcher.rb:103:in `search_for_dependency'
Ruby99-x64/lib/ruby/2.6.0/rubygems/specification.rb:1235:in `block in outdated_and_latest_version'
Ruby99-x64/lib/ruby/2.6.0/rubygems/specification.rb:1231:in `each'
Ruby99-x64/lib/ruby/2.6.0/rubygems/specification.rb:1231:in `outdated_and_latest_version'
Ruby99-x64/lib/ruby/2.6.0/rubygems/commands/outdated_command.rb:29:in `each'
Ruby99-x64/lib/ruby/2.6.0/rubygems/commands/outdated_command.rb:29:in `execute'
Ruby99-x64/lib/ruby/2.6.0/rubygems/command.rb:321:in `invoke_with_build_args'
Ruby99-x64/lib/ruby/2.6.0/rubygems/command_manager.rb:176:in `process_args'
Ruby99-x64/lib/ruby/2.6.0/rubygems/command_manager.rb:146:in `run'
Ruby99-x64/lib/ruby/2.6.0/rubygems/gem_runner.rb:59:in `run'
Ruby99-x64/bin/gem.cmd:29:in `<main>'
```

**Comment by MSP-Greg** [comment]
See @nurse's [comment](https://github.com/rubygems/rubygems/commit/676a54b3205f3b4dfea0f42cebbdc70318b0a6f5#r31680298).  Ok to close...

**Comment by nurse** [comment]
I think HEAD of rubygems with other than ruby-head still reproduces the issue. It's still need to fix.

**Comment by MSP-Greg** [comment]
HEAD of rubygems does raise the error with Ruby 2.5.3

**Comment by nurse** [comment]
I reproduced it as follows.
Note that there's a confusion beta2 and beta3, it's because current master's rubygems-update.gemspec says beta2, but lib/rubygems.rb says beta3.
```sh
% git clone https://github.com/rubygems/rubygems.git
...
% cd rubygems
% rake package
...
cd pkg
tar -czf rubygems-3.0.0.beta2.tgz rubygems-3.0.0.beta2
cd -
cd pkg
zip -q -r rubygems-3.0.0.beta2.zip rubygems-3.0.0.beta2
cd -
% gem i pkg/rubygems-update-3.0.0.beta2.gem
Successfully installed rubygems-update-3.0.0.beta2
Parsing documentation for rubygems-update-3.0.0.beta2
Installing ri documentation for rubygems-update-3.0.0.beta2
Done installing documentation for rubygems-update after 40 seconds
1 gem installed
% gem update --system 3.0.0.beta2
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	Unable to resolve dependency: user requested 'rubygems-update (= 3.0.0.beta2)'
Installing RubyGems 3.0.0.beta2
Bundler 1.17.2 installed
RubyGems 3.0.0.beta3 installed
Regenerating binstubs
Parsing documentation for rubygems-3.0.0.beta3
Installing ri documentation for rubygems-3.0.0.beta3



------------------------------------------------------------------------------

RubyGems installed the following executables:
	/Users/naruse/.rbenv/versions/2.5.3/bin/gem
	/Users/naruse/.rbenv/versions/2.5.3/bin/bundle

Ruby Interactive (ri) documentation was installed. ri is kind of like man
pages for Ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.

RubyGems system software updated
% gem --version
3.0.0.beta3
% gem outdated
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::RemoteFetcher::OpenSSL
```

**Comment by hsbt** [comment]
@nurse It's my mistake. https://github.com/rubygems/rubygems/blob/master/rubygems-update.gemspec#L5

**Comment by MSP-Greg** [comment]
Still having this problem, but at `request.rb:50`.  As a workaround, I added a conditional require in the method...

https://github.com/rubygems/rubygems/blob/c90b7c437b809f81baddef118ab2b92450ce6054/lib/rubygems/request.rb#L47-L57

**Comment by hsbt** [comment]
This issue was fixed at https://github.com/rubygems/rubygems/pull/2530
