### ISSUE TITLE
Unable to sign gem with JRuby

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#2550]
If I try to sign my gem using JRuby I get `OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key` before it ever asks for my password. It works fine with C Ruby. The rake task in question just sets the signing key, then tries to build the gem:
```
>rake gem:create --trace
** Invoke gem:create (first_time)
** Invoke clean (first_time)
** Execute clean
** Execute gem:create
Enter PEM pass phrase:rake aborted!
OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key:
org/jruby/ext/openssl/PKeyRSA.java:308:in `initialize'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/stdlib/rubygems/security/signer.rb:50:in `initialize'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/stdlib/rubygems/package.rb:498:in `setup_signer'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/stdlib/rubygems/package.rb:252:in `build'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/stdlib/rubygems/package.rb:115:in `build'
/home/dberger/Dev/file-find/Rakefile:13:in `block in <main>'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
org/jruby/RubyArray.java:1789:in `each'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
org/jruby/RubyArray.java:1789:in `each'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared/gems/rake-12.3.0/exe/rake:27:in `<main>'
org/jruby/RubyKernel.java:1000:in `load'
/home/dberger/.rbenv/versions/jruby-9.2.4.0/bin/rake:23:in `<main>'
Tasks: TOP => gem:create
```
The jgem env:

```
>jgem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.0 (2018-11-13 patchlevel 0) [java]
  - INSTALLATION DIRECTORY: /home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared
  - USER INSTALLATION DIRECTORY: /home/dberger/.gem/jruby/2.5.0
  - RUBY EXECUTABLE: /home/dberger/.rbenv/versions/jruby-9.2.4.0/bin/jruby
  - EXECUTABLE DIRECTORY: /home/dberger/.rbenv/versions/jruby-9.2.4.0/bin
  - SPEC CACHE DIRECTORY: /home/dberger/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/dberger/.rbenv/versions/jruby-9.2.4.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-java-1.8
  - GEM PATHS:
     - /home/dberger/.rbenv/versions/jruby-9.2.4.0/lib/ruby/gems/shared
     - /home/dberger/.gem/jruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-rdoc --no-ri"
     - "update" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/dberger/.rbenv/versions/jruby-9.2.4.0/bin
     - /home/dberger/.rbenv/libexec
     - /home/dberger/.rbenv/plugins/ruby-build/bin
     - /home/dberger/.rbenv/shims
     - /home/dberger/.rbenv/bin
     - /home/dberger/.rbenv/shims
     - /home/dberger/.rbenv/bin
     - /home/dberger/.rbenv/shims
     - /home/dberger/.rbenv/bin
     - /usr/lib64/qt-3.3/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /usr/sbin
     - /bin
     - /sbin
     - /usr/pgsql-9.5/bin
     - /home/dberger/.local/bin
     - /home/dberger/bin
     - /usr/pgsql-9.5/bin
```

**Comment by bronzdoc** [comment]
I'll give it a look @djberg96

**Comment by bronzdoc** [comment]
@djberg96 i can't reproduce your error:

```shell
rake create
Enter PEM pass phrase:
  Successfully built RubyGem
  Name: jruby_gem
  Version: 0.1.0
  File: jruby_gem-0.1.0.gem
```
i supose your `create` tasks is something like:
```ruby
require 'rake'
require 'rake/clean'

task :create => [:clean] do
  require 'rubygems/package'
  spec = eval(IO.read('jruby_gem.gemspec'))
  spec.signing_key = File.join(Dir.home, '.ssh', 'gem-private_key.pem')
  Gem::Package.build(spec, true)¬
end
```

and in your gemspec you have the certs as:
```
....
  spec.cert_chain = ['certs/djberg96_pub.pem']
```

i'm trying with the default keys `gem cert --build you@example` generates, so i have as my 
`spec.signing_key = File.join(Dir.home, '.ssh', 'gem-private_key.pem')` and in my `spec.cert_chain = ['certs/gem-public_cert.pem']`


how `certs/djberg96_pub.pem'` was generated?

**Comment by djberg96** [comment]
@bronzdoc Pretty sure I just did `gem cert --build`, though I did set the `--days` option to something like 3650 (approx 10 years).

**Comment by bronzdoc** [comment]
@djberg96 i tried  using the `--days` option but can't reproduce the error :/

**Comment by djberg96** [comment]
@bronzdoc Total stab in the dark, what happens if you rename the public cert to something else? I just want to eliminate the possibility that JRuby is dependent on a literal "gem-public_cert.pem" or some such.

**Comment by bronzdoc** [comment]
ok i'll try that @djberg96

**Comment by bronzdoc** [comment]
I tried what you suggest @djberg96 but still can build the gem:
```
Enter PEM pass phrase:
  Successfully built RubyGem
  Name: jruby_gem
  Version: 0.1.0
  File: jruby_gem-0.1.0.gem
```

i renamed `cert/gem-public_cert.pem` to `cert/doc_cert.pem`

and in the gemspec `pec.cert_chain = ['certs/doc_cert.pem']`

**Comment by djberg96** [comment]
@bronzdoc Are you trying with JRuby 9.2.4? Just want to make sure the versions are the same.

**Comment by djberg96** [comment]
@bronzdoc Interesting, guess we'll have to comb the changelogs to see what happened. I'm guessing this is an issue with JRuby, but perhaps they added stricter checking of some sort on their end that we need to follow (?). Just guessing for now, though.

**Comment by bronzdoc** [comment]
@djberg96 yup, will investigate further

**Comment by djberg96** [comment]
Hm, I see it even with JRuby 9.2.0.0.

**Comment by djberg96** [comment]
> @djberg96 i was testing with `jruby-9.2.0.0` grimacing
> 
> i can reproduce the error with `jruby-9.2.4.0` !
> 
> ```shell
> rake create
> 
> Enter PEM pass phrase:rake aborted!
> OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key:
> org/jruby/ext/openssl/PKeyRSA.java:308:in `initialize'
> /Users/bronzdoc/projects/ruby/test/test_rubygems_2550/jruby_gem/Rakefile:8:in `block in <main>'
> Tasks: TOP => create
> (See full trace by running task with --trace)
> ```
> 
> it doesn't even let me type the pem passphrase

That gave me an idea. It works if I explicitly send the passphrase:

```
key = "/home/dberger/.ssh/gem-private_key.pem"
pass = 'mypass'
OpenSSL::PKey::RSA.new(File.read(key), pass)
```

But, if you omit the passphrase and try to enter it, that's when things get wonky:

```
OpenSSL::PKey::RSA.new(File.read(key))
Enter PEM pass phrase:
```
I have trouble getting it to accept the password, as pressing enter just generates `^M` characters on the console. If I hit ctrl-c, I get the original error.

Which leads me to believe there's some sort of interactive bug with `ask_for_password` in signer.rb, which is probably sending it a blank string somehow.

**Comment by djberg96** [comment]
Actually, I think this falls squarely on JRuby. I'm guessing it's some sort of terminal/readline issue.

**Comment by djberg96** [comment]
@bronzdoc I should also mention that I'm using openjdk version "1.8.0_161".

**Comment by djberg96** [comment]
https://github.com/jruby/jruby/issues/5588

**Comment by djberg96** [comment]
Going to close this since it's a JRuby issue.
