### ISSUE TITLE
undefined method `payload' for nil:NilClass

### ISSUE THREAD

**Issue by jackorp** [rubygems/rubygems#2665]
My current problem is ``undefined method `payload' for nil:NilClass``.

When attempting local install of 6.0.0.beta1 version of railties gem with the (same version) actionpack library installed. Without actionpack available, the railties gem installs just fine.

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

How to reproduce the behavior:
```
# Install clean ruby from source
$ curl -OL https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.1.tar.gz && tar -xvf ruby-2.6.1.tar.gz && cd ruby-2.6.1
$ autoconf && ./configure
$ make && make install
$ gem fetch railties --version 6.0.0.beta1
$ gem install actionpack --version 6.0.0.beta1
$ gem install -V --local --build-root . --force --document=ri,rdoc ./railties-6.0.0.beta1.gem --debug 
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /usr/local/lib/ruby/2.6.0/resolv.rb:170 - LoadError
Exception `NoMethodError' at /usr/local/lib/ruby/2.6.0/rubygems/resolver.rb:280 - undefined method `payload' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `payload' for nil:NilClass
	/usr/local/lib/ruby/2.6.0/rubygems/resolver.rb:280:in `block in sort_dependencies'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `each'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `sort_by'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `with_index'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `sort_dependencies'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:466:in `push_state_for_requirements'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:458:in `require_nested_dependencies_for'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:441:in `activate_spec'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:402:in `attempt_to_activate_new_spec'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:319:in `attempt_to_activate'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:137:in `process_topmost_state'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:78:in `resolve'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
	/usr/local/lib/ruby/2.6.0/rubygems/resolver.rb:188:in `resolve'
	/usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:423:in `resolve'
	/usr/local/lib/ruby/2.6.0/rubygems/dependency_installer.rb:488:in `resolve_dependencies'
	/usr/local/lib/ruby/2.6.0/rubygems/commands/install_command.rb:201:in `install_gem'
	/usr/local/lib/ruby/2.6.0/rubygems/commands/install_command.rb:264:in `block in install_gems'
	/usr/local/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `each'
	/usr/local/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `install_gems'
	/usr/local/lib/ruby/2.6.0/rubygems/commands/install_command.rb:165:in `execute'
	/usr/local/lib/ruby/2.6.0/rubygems/command.rb:321:in `invoke_with_build_args'
	/usr/local/lib/ruby/2.6.0/rubygems/command_manager.rb:176:in `process_args'
	/usr/local/lib/ruby/2.6.0/rubygems/command_manager.rb:146:in `run'
	/usr/local/lib/ruby/2.6.0/rubygems/gem_runner.rb:59:in `run'
	/usr/local/bin/gem:21:in `<main>'
```
After you remove actionpack the installation is successfull.
```
$ gem uninstall actionpack --version 6.0.0.beta1
$ gem install -V --local --build-root . --force --document=ri,rdoc ./railties-6.0.0.beta1.gem
WARNING:  You build with buildroot.
  Build root: /home/vagrant
  Bin dir: /home/vagrant/usr/local/bin
  Gem home: /home/vagrant/usr/local/lib/ruby/gems/2.6.0
**shortened**
Successfully installed railties-6.0.0.beta1
Parsing documentation for railties-6.0.0.beta1
Done installing documentation for railties after 0 seconds
1 gem installed
```

Here are my current environment details:
```
$ gem env version
3.0.1
```
```
$ ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@jackorp i can't reproduce your error

After i execute 
```
gem fetch railties --version 6.0.0.beta1
gem install actionpack --version 6.0.0.beta1
gem install -V --local --build-root . --force --document=ri,rdoc ./railties-6.0.0.beta1.gem
```
i'm getting:

```
Successfully installed railties-6.0.0.beta1
Parsing documentation for railties-6.0.0.beta1
Done installing documentation for railties after 0 seconds
1 gem installed
```

please let me know if you still experience this and i'll reopen this issue.
