### ISSUE TITLE
Order dependent test failure

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#2717]
My current problem is that I have found an order dependent test failure. It is reproducible with

    rake TESTOPTS="--name=/TestGemCommandsSourcesCommand#test_initialize_proxy\|test_no_proxy/ --seed=5961"

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Here is the error, in case it rings any bells:

```
$ rake TESTOPTS="--name=/TestGemCommandsSourcesCommand#test_initialize_proxy\|test_no_proxy/ --seed=5961"

Run options: "--name=/TestGemCommandsSourcesCommand#test_initialize_proxy|test_no_proxy/" --seed=5961

# Running:

.E

Finished in 0.195876s, 10.2106 runs/s, 5.1053 assertions/s.

  1) Error:
TestGemRemoteFetcher#test_no_proxy:
Gem::RemoteFetcher::UnknownHostError: no such name (http://localhost:44661/yaml)
    /home/deivid/Code/rubygems/lib/rubygems/remote_fetcher.rb:280:in `rescue in fetch_path'
    /home/deivid/Code/rubygems/lib/rubygems/remote_fetcher.rb:253:in `fetch_path'
    /home/deivid/Code/rubygems/test/rubygems/test_gem_remote_fetcher.rb:184:in `block in test_no_proxy'
    /home/deivid/Code/rubygems/lib/rubygems/user_interaction.rb:47:in `use_ui'
    /home/deivid/Code/rubygems/lib/rubygems/user_interaction.rb:70:in `use_ui'
    /home/deivid/Code/rubygems/test/rubygems/test_gem_remote_fetcher.rb:183:in `test_no_proxy'

2 runs, 1 assertions, 0 failures, 1 errors, 0 skips
Coverage report generated for Unit Tests to /home/deivid/Code/rubygems/coverage. 2818 / 9060 LOC (31.1%) covered.
rake aborted!
Command failed with status (1)

Tasks: TOP => default => test
(See full trace by running task with --trace)
```
