### ISSUE TITLE
Cannot run any gem command 

### ISSUE THREAD

**Issue by jadebermas** [rubygems/rubygems#2760]
I have been working with SASS and I am suddenly getting an issue when I tried to run `compass watch`. I tried searching for related issues and realized that I can't even run any gem command as well.

For example, if I run:

```
$ gem env version
```

I get:

```
Traceback (most recent call last):                                                                                                
        4: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'                                                              
        3: from <internal:gem_prelude>:2:in `require'                                                                             
        2: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:1395:in `<top (required)>'                                        
        1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'                           
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubygems/core_ex
t/kernel_warn (LoadError)   
```
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Ugh, I'm sorry you're having issues @jadebermas.

Some questions:

* I assume you have a `/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb` file in there, right?

* What's the output of `ruby --disable-gems -e 'puts $LOAD_PATH'`?

**Comment by jadebermas** [comment]
Hi @deivid-rodriguez 

Thanks for responding! 

I got `kernel_gem.rb `and `kernel_require.rb` in `/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext`

Output for `ruby --disable-gems -e 'puts $LOAD_PATH'`:

```
/usr/local/lib/ruby/site_ruby/2.5.0                                                                                               
/usr/local/lib/ruby/site_ruby/2.5.0/x86_64-darwin17                                                                               
/usr/local/lib/ruby/site_ruby                                                                                                     
/usr/local/lib/ruby/vendor_ruby/2.5.0                                                                                             
/usr/local/lib/ruby/vendor_ruby/2.5.0/x86_64-darwin17                                                                             
/usr/local/lib/ruby/vendor_ruby                                                                                                   
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0                                                                                       
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/x86_64-darwin17 
```

**Comment by deivid-rodriguez** [comment]
Ugh, it sounds like your rubygems installation is missing files! Not sure how that would happen :grimacing:. You can try reinstalling rubygems manually:

```
git clone https://github.com/rubygems/rubygems
git checkout v3.0.3
ruby setup.rb
```

**Comment by jadebermas** [comment]
I get the same error :(

```
ls
CODE_OF_CONDUCT.md      MAINTAINERS.txt         README.md               bin                     rubygems-update.gemspec           
CONTRIBUTING.md         MIT.txt                 Rakefile                bundler                 setup.rb                          
History.txt             Manifest.txt            UPGRADING.md            hide_lib_for_update     test                              
LICENSE.txt             POLICIES.md             appveyor.yml            lib                     util
```

```
ruby setup.rb
Traceback (most recent call last):                                                                                                
        4: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'                                                              
        3: from <internal:gem_prelude>:2:in `require'                                                                             
        2: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:1395:in `<top (required)>'                                        
        1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'                           
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubygems/core_ex
t/kernel_warn (LoadError)
```

**Comment by deivid-rodriguez** [comment]
Oh, right, sorry. Try `ruby --disable-gems -Ilib setup.rb`.

**Comment by jadebermas** [comment]
Hi @deivid-rodriguez,   

Thank you. This is what I am getting now:

```
sudo ruby --disable-gems -Ilib setup.rb
Password:                                                                                                                         
ERROR:  While executing gem ... (Errno::ENOENT)                                                                                   
    No such file or directory @ dir_chdir - bundler/lib  
```

**Comment by deivid-rodriguez** [comment]
Oh right, sorry, I'm writing the instructions off the top of my head. Run `git submodule update --init --recursive` and rerun the command again.

**Comment by jadebermas** [comment]
All good now! Thank you so much for your help David. <3

**Comment by deivid-rodriguez** [comment]
You're welcome! If you ever get into the same situation again, let us know, it'd be good to figure out how your installation got messed up. :+1:

Closing this!
