### ISSUE TITLE
gem install fails with Gemfile.lock and complex version requirements

### ISSUE THREAD

**Issue by pointlessone** [rubygems/rubygems#2997]
I'm having a problem or would like to suggest a feature.

My current problem is `gem install -g` fails when gemspec has complex version requirements and Gemfile.lock is present.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.6
```

## Reproduction

This issue is related to Gemfiles for gemspecs.

test.gemspec:
```ruby
Gem::Specification.new do |spec|
  spec.name = 'test'
  spec.version = '1.0.0'

  spec.add_dependency('rspec', '~> 2.14', '>= 2.14.1')
end
```

Gemfile:
```ruby
source 'https://rubygems.org/'

gemspec
```

Run the following command _twice_:
```
gem install -g
```

On first run it will produce a Gemfile.lock (for reference):
```
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.3)
    rspec (2.99.0)
      rspec-core (~> 2.99.0)
      rspec-expectations (~> 2.99.0)
      rspec-mocks (~> 2.99.0)
    rspec-core (2.99.2)
    rspec-expectations (2.99.2)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.99.4)

PLATFORMS
  ruby

DEPENDENCIES
  rspec (~> 2.14, >= 2.14.1)
```

On the second run, when the lockfile is in place it results in the following error:
```
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement [#<Gem::Requirement:0x00007fbb6c8e2478 @requirements=[["~>", #<Gem::Version "2.14">], [">=", #<Gem::Version "2.14.1">]]>]
```

And with `--debug` for completeness (slightly edited):
```
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at […]/ruby-2.6.5/lib/ruby/2.6.0/resolv.rb:170 - LoadError
Exception `Gem::Requirement::BadRequirementError' at […]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/requirement.rb:101 - Illformed requirement [#<Gem::Requirement:0x00007f9f9d142c58 @requirements=[["~>", #<Gem::Version "2.14">], [">=", #<Gem::Version "2.14.1">]]>]
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement [#<Gem::Requirement:0x00007f9f9d142c58 @requirements=[["~>", #<Gem::Version "2.14">], [">=", #<Gem::Version "2.14.1">]]>]
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/requirement.rb:101:in `parse'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/requirement.rb:143:in `block in concat'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/requirement.rb:143:in `map'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/requirement.rb:143:in `concat'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:124:in `gem'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set/gem_dependency_api.rb:238:in `block in add_dependencies'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set/gem_dependency_api.rb:237:in `each'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set/gem_dependency_api.rb:237:in `add_dependencies'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set/gem_dependency_api.rb:652:in `gemspec'
	Gemfile:3:in `load'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set/gem_dependency_api.rb:283:in `instance_eval'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set/gem_dependency_api.rb:283:in `load'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:348:in `load_gemdeps'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:241:in `install_from_gemdeps'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/commands/install_command.rb:176:in `install_from_gemdeps'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/commands/install_command.rb:152:in `execute'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/command.rb:321:in `invoke_with_build_args'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/command_manager.rb:184:in `process_args'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/command_manager.rb:148:in `run'
	[…]/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/gem_runner.rb:59:in `run'
	[…]/ruby-2.6.5/bin/gem:21:in `<main>'
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@pointlessone Thanks for the steps to reproduce and the `test.gemspec`. I was able to reproduce it and i'm looking into it.
