### ISSUE TITLE
Can't use gem install or gem update on new Ubuntu 19.10

### ISSUE THREAD

**Issue by powerriegel** [rubygems/rubygems#3006]
I'm having a problem or would like to suggest a feature.

My current problem is https://rubsgems.org seems not to respons (but works in browser)

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here is the original call which did not work:
```
$ sudo gem install fusuma 
Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)
```

```
sudo gem sources -a https://rubygems.org/
Error fetching https://rubygems.org/:
	timed out (https://rubygems.org/specs.4.8.gz)
```

Then, I tried the SSL cert test script. No luck. I invested 2 hourse but still can't install fusuma. 
```

$ sudo ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'
Here's your Ruby and OpenSSL environment:

Ruby:           2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
RubyGems:       3.0.6
Bundler:        1.17.3
Compiled with:  OpenSSL 1.1.1c  28 May 2019
Loaded version: OpenSSL 1.1.1c  28 May 2019
SSL_CERT_FILE:  /usr/lib/ssl/cert.pem
SSL_CERT_DIR:   /usr/lib/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (execution expired)
RubyGems connection to rubygems.org:      failed  ❌  (timed out (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
Net::OpenTimeout: execution expired
  /usr/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
  /usr/lib/ruby/2.5.0/net/http.rb:937:in `open'
  /usr/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
  /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  /usr/lib/ruby/2.5.0/net/http.rb:915:in `start'
  (eval):90:in `<main>'
  -e:1:in `eval'
  -e:1:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/


```

**Comment by MSP-Greg** [comment]
Try:
```
ruby -ropen-uri -e "ARGV = %w[google.com TLSv1_2 VERIFY_PEER]; eval URI.open('https://git.io/vQhWq').read"
```

That will use google.com & TLSv1.2 for the net/http connection.  Right now, it's not clear if it's a Ruby issue or a Rubygems issue.

JFYI, I've used OpenSSL 1.1.1 since before its release, and I've never had any issues with RubyGems.  But, in checking this, I don't think RubyGems supports TLSv1.3 yet...

**Comment by powerriegel** [comment]
Issue solved. It seems my router (partially) hung up. I could not `ping google.com`, `ping -4 google.com` worked, but `ping -6 google.com` did not work. So it was IPv6 related.
