### ISSUE TITLE
Can't call command `rails` after update rubygem

### ISSUE THREAD

**Issue by phuwanart** [rubygems/rubygems#3032]
I'm having a problem after update rubygem `gem update --system`. I call command `rails -v` it error like this:

```
$ rails -v
Traceback (most recent call last):
	6: from /Users/phuwanart/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:10:in `<main>'
	5: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	4: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	3: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	2: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	1: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rubygems-bundler/noexec (LoadError)
	10: from /Users/phuwanart/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:10:in `<main>'
	 9: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	 8: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	 7: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	 6: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	 5: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	 4: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	 3: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	 2: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	 1: from /Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
/Users/phuwanart/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fd04e203ca0> (NoMethodError)
```

Here are my current environment details:

```
$ gem env version
3.1.1
```

**Comment by deivid-rodriguez** [comment]
Can you `gem uninstall rubygems-bundler`? I think we should request the `rvm` team to stop installing this gem by default because I don't think anybody is maintaining it... :grimacing:

**Comment by phuwanart** [comment]
> Can you `gem uninstall rubygems-bundler`? I think we should request the `rvm` team to stop installing this gem by default because I don't think anybody is maintaining it... 😬

OK I will move this issue to rvm team .

**Comment by deivid-rodriguez** [comment]
Did you try it and it worked though?

**Comment by phuwanart** [comment]
> Did you try it and it worked though?

It works. Thank you very much. 😆
