### ISSUE TITLE
Executing `ruby setup.rb` fails with force error

### ISSUE THREAD

**Issue by Zanadar** [rubygems/rubygems#3037]
I'm having a problem or would like to suggest a feature.

My current problem is upgrading rubygems via execution of `ruby setup.rb` fails with 
```
ERROR:  While executing gem ... (Gem::InstallError)
               "bundle" from bundler conflicts with /tmp/contents516822199/deps/0/ruby/bin/bundle
```
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

```
           -----> Installing rubygems 3.1.1
                  Copy [/tmp/buildpacks/27feb989d82cab9530c95fba45de142e/dependencies/e9560e077aa58553ba6aaad32666d6de/rubygems-3.1.1-any-stack-227d52ca.tgz]
           mkdir -p -m 755 /tmp/contents389131040/deps/0/ruby/lib/ruby/site_ruby/2.6.0
           mkdir -p -m 755 /tmp/contents389131040/deps/0/ruby/bin
           (snip)
/tmp/contents389131040/deps/0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.0/exe/bundle
           ERROR:  While executing gem ... (Gem::InstallError)
               "bundle" from bundler conflicts with /tmp/contents389131040/deps/0/ruby/bin/bundle
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/installer.rb:269:in `check_executable_overwrite'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/installer.rb:516:in `block in generate_bin'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/installer.rb:502:in `each'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/installer.rb:502:in `generate_bin'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/installer.rb:332:in `install'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/commands/setup_command.rb:433:in `block in install_default_bundler_gem'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/commands/setup_command.rb:429:in `chdir'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/commands/setup_command.rb:429:in `install_default_bundler_gem'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/commands/setup_command.rb:168:in `execute'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/command.rb:325:in `invoke_with_build_args'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/command_manager.rb:178:in `process_args'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/command_manager.rb:148:in `run'
           	/tmp/rubygems893051954/rubygems-3.1.1/lib/rubygems/gem_runner.rb:59:in `run'
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by Zanadar** [comment]
From the looks of it, this is related to https://github.com/rubygems/rubygems/issues/3030

**Comment by deivid-rodriguez** [comment]
I think #3035 should also fix this. Can you confirm?

**Comment by Zanadar** [comment]
I'm happy to say that it does!
