### ISSUE TITLE
bundler's executable "bundle" conflicts with /usr/share/rvm/rubies/ruby-2.6.3/bin/bundle

### ISSUE THREAD

**Issue by o7n** [rubygems/rubygems#3044]
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

My current problem is a poblem when running `gem update --system --no-document` there is an apparent conflict:
```
  Successfully built RubyGem
  Name: bundler
  Version: 2.1.0
  File: bundler-2.1.0.gem
bundler's executable "bundle" conflicts with /usr/share/rvm/rubies/ruby-2.6.3/bin/bundle
```

Subsequently we have all kinds of issues running bundler, most important one is that it fails to switch back to 1.x when started from an init.d script, even if we manually install 1.17.3:
```
/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:275:
in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /var/ww
```

When we revert to 3.0.6 everything is fine and dandy:

```
gem update --system 3.0.6 --no-document
Updating rubygems-update
Successfully installed rubygems-update-3.0.6
Installing RubyGems 3.0.6
Bundler 1.17.3 installed
RubyGems 3.0.6 installed
Regenerating binstubs
```
(note that RubyGems 3.0.6 apparently installs 1.17.3 ?)

Here are my current environment details:

```
$ gem env version
3.1.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
This should've been fixed by rubygems 3.1.2. Please upgrade and close the ticket if it fixes things for you.

Thanks and sorry for the trouble!!

**Comment by o7n** [comment]
I don't get that far. 3.1.2 gives me this
```
Error loading RubyGems plugin "/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/rubygems_plugin.rb": undefined method `remove_unresolved_default_spec' for Gem:Module (NoMethodError)
Error loading RubyGems plugin "/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb": undefined method `remove_unresolved_default_spec' for Gem:Module (NoMethodError)
/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:40:in `require': undefined method `remove_unresolved_default_spec' for Gem:Module (NoMethodError)
```

which is maybe a new / separate issue?

**Comment by deivid-rodriguez** [comment]
Yes, please open a separate issue. Thanks!

**Comment by o7n** [comment]
I cannot reproduce the above issue any more.
But the issue is not solved by RubyGems 3.1.2 either.

```
Dec 20 17:08:16 prof801 discourse[30993]: /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /var/ww
Dec 20 17:08:16 prof801 discourse[30993]: To update to the latest version installed on your system, run `bundle update --bundler`.
Dec 20 17:08:16 prof801 discourse[30993]: To install the missing version, run `gem install bundler:1.17.3`
Dec 20 17:08:16 prof801 discourse[30993]: #011from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:294:in `activate_bin_path'
Dec 20 17:08:16 prof801 discourse[30993]: #011from /usr/share/rvm/gems/ruby-2.6.3/bin/bundle:23:in `<main>'
Dec 20 17:08:16 prof801 discourse[30993]: #011from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
Dec 20 17:08:16 prof801 discourse[30993]: #011from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```

```
root@prof801:/var/log# gem list bundler

*** LOCAL GEMS ***

bundler (2.1.2, 1.17.3)
bundler-unload (1.0.2)
rubygems-bundler (1.4.5)
root@prof801:/var/log# gem list rubygems

*** LOCAL GEMS ***

rubygems-bundler (1.4.5)
rubygems-update (3.1.2)
```

**Comment by deivid-rodriguez** [comment]
Ok, I'll have a look at it.

**Comment by deivid-rodriguez** [comment]
I think this is due to #2671 and I plan to fix it in the next days.

**Comment by deivid-rodriguez** [comment]
Closing since the original issue was fixed, and the new issue is being tracked separately.
