### ISSUE TITLE
Flaky `TestGemSource#test_dependency_resolver_set_file_uri` test failure

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3140]
I'm having a problem or would like to suggest a feature.

My current problem is a flaky test failure. See:

* https://github.com/rubygems/rubygems/runs/453291193.
* https://github.com/rubygems/rubygems/runs/459504331.
* https://github.com/rubygems/rubygems/pull/3165/checks?check_run_id=489809509.
* https://github.com/rubygems/rubygems/pull/3483/checks?check_run_id=561932495.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
An initial clue is that this has happened twice so far, both times under Windows + MRI 2.5.

**Comment by deivid-rodriguez** [comment]
It happened again on Windows + MRI 2.4.

So it does seem Windows specific, but not ruby version specific.

**Comment by deivid-rodriguez** [comment]
One more: https://github.com/rubygems/rubygems/pull/3561/checks?check_run_id=629062286.

**Comment by deivid-rodriguez** [comment]
Once again, https://github.com/rubygems/rubygems/pull/3562/checks?check_run_id=634233669. New failures include some more debugging information:

```
TestGemSource#test_dependency_resolver_set_file_uri:
Zlib::GzipFile::Error: #<Zlib::GzipFile::Error: not in gzip format, input="\x1F\x8B\b\x00\x11">
    D:/a/rubygems/rubygems/lib/rubygems/util.rb:15:in `initialize'
    D:/a/rubygems/rubygems/lib/rubygems/util.rb:15:in `new'
    D:/a/rubygems/rubygems/lib/rubygems/util.rb:15:in `gunzip'
    D:/a/rubygems/rubygems/lib/rubygems/test_utilities.rb:71:in `fetch_path'
    D:/a/rubygems/rubygems/lib/rubygems/test_utilities.rb:78:in `cache_update_path'
    D:/a/rubygems/rubygems/lib/rubygems/source.rb:186:in `load_specs'
    D:/a/rubygems/rubygems/lib/rubygems/spec_fetcher.rb:257:in `tuples_for'
    D:/a/rubygems/rubygems/lib/rubygems/spec_fetcher.rb:226:in `block in available_specs'
    D:/a/rubygems/rubygems/lib/rubygems/source_list.rb:100:in `each'
    D:/a/rubygems/rubygems/lib/rubygems/source_list.rb:100:in `each_source'
    D:/a/rubygems/rubygems/lib/rubygems/spec_fetcher.rb:217:in `available_specs'
    D:/a/rubygems/rubygems/lib/rubygems/resolver/index_set.rb:22:in `initialize'
    D:/a/rubygems/rubygems/lib/rubygems/source.rb:82:in `new'
    D:/a/rubygems/rubygems/lib/rubygems/source.rb:82:in `dependency_resolver_set'
```

I believe "\x1F\x8B\b\x00\x11" is the beginning of a correct gzip header, but the file is somehow getting "cut".

I have now idea why this is happen, and why so randomly.

**Comment by deivid-rodriguez** [comment]
Another one: https://github.com/rubygems/rubygems/runs/777836672.

This one happens very very rarely, and only on Windows, so I think I'll go ahead and skip this test on Windows.
