### ISSUE TITLE
Bundler.require in 1.13 clears load path when it shouldn't (?)

### ISSUE THREAD

**Issue by buehmann** [rubygems/rubygems#3195]
## Background

On our continuous integration server, we test our Rails application with RSpec and the Knapsack gem. When Bundler v1.13 was released (we were automatically installing the most recent version of Bundler), we saw our complete test suite fail with strange errors: Undefined symbols, files could not be loaded.

This was a bit hard to debug because multiple processes running our Rails app are involved and multiple layers of Bundler. It roughly looks like this:
- bundle exec rake knapsack:rspec
  - (in Knapsack gem) system("bundle exec rspec ...")

Both the rake and the rspec process load our Rails app which itself requires Bundler as well.
## Reproducible case

Through a long series of iterations I was able to remove almost all of our application and to boil down the problem to this setup:

https://github.com/buehmann/bundler/tree/4d02f96f3a656c330e9eb0fbadd014f8d138ca3b

Output of `bundle env` is included for both versions used below.

I briefly tried to get `rspec` out of the equation but was not successful.

I added debugging output because the $LOAD_PATH is changed by the call to `Bundler.require` which I didn't expect in this case (and which didn't happen with Bundler v1.12).

After `Bundler.require(:group)` I expect to be able to require other gems not in that group. A direct call to `bundle exec rspec spec/bug_spec.rb` (without additional Bundler layers wrapped around) works like this.

```
➜  banking (bundler-bug) bundle _1.13.1_ exec ./bug
before
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-mocks-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
after
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
bundler: failed to load command: rspec (/Users/buehmann/.rbenv/versions/2.3.1/bin/rspec)
LoadError: cannot load such file -- rake
  /Users/buehmann/dev/banking/spec/bug_spec.rb:9:in `require'
  /Users/buehmann/dev/banking/spec/bug_spec.rb:9:in `<top (required)>'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `load'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `each'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:100:in `setup'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:86:in `run'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/exe/rspec:4:in `<top (required)>'
  /Users/buehmann/.rbenv/versions/2.3.1/bin/rspec:22:in `load'
  /Users/buehmann/.rbenv/versions/2.3.1/bin/rspec:22:in `<top (required)>'
```

In contrast with Bundler 1.12:

```
➜  banking (bundler-bug) bundle _1.12.5_ exec ./bug
before
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-mocks-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
after
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-mocks-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
No examples found.


Finished in 0.00038 seconds (files took 0.35775 seconds to load)
0 examples, 0 failures
```

**Comment by deivid-rodriguez** [comment]
I tried to repro this against latest version of bundler using https://github.com/rubygems/rubygems/issues/3195#issuecomment-251077125, and everything worked as expected. It seems that bundler 2.1.4 is the latest version with this bug so something in the bundler 2.2.0 must have fixed it! :tada:
