### ISSUE TITLE
Git clone is taking too long

### ISSUE THREAD

**Issue by localhostdotdev** [rubygems/rubygems#3332]
Tried using latest version of Rails for a couple of weeks and can't because of this.

```
bundle update --verbose
Running `bundle update --verbose` with bundler 2.0.1
Fetching https://github.com/rails/rails.git
```

Interesting part of my `Gemfile`.

```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", github: "rails/rails"
```

I have other `github:` sources for other gems and they work just fine. I'm guessing this has to do with the size of the Rails repo. Maybe it's doing a full `git clone` instead of `git clone --depth=1`-style commands. (Happened to me a few years ago, maybe CocoaPods though)

Might also be that I already have an older version of repo and it's trying to catch up by fetching intermediate commits but doesn't have the previous commits so it becomes quite an expensive operation.

Stacktrace (when interrupting):

```
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:171:in ``'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:171:in `block (2 levels) in git'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:249:in `block in capture_and_filter_stderr'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/tempfile.rb:295:in `open'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:247:in `capture_and_filter_stderr'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:171:in `block in git'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/shared_helpers.rb:83:in `with_clean_git_env'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:170:in `git'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:162:in `block in git_retry'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/retry.rb:40:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/retry.rb:30:in `attempt'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:161:in `git_retry'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:103:in `checkout'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git.rb:303:in `fetch'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git.rb:161:in `specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:758:in `block in converge_locked_specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:744:in `each'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:744:in `converge_locked_specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:247:in `resolve'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:158:in `resolve_remotely!'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:310:in `resolve_if_needed'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:84:in `block in run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `open'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:73:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:25:in `install'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli/update.rb:61:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli.rb:280:in `update'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli.rb:27:in `dispatch'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli.rb:18:in `start'
.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
.rvm/rubies/ruby-head/bin/bundle:23:in `load'
.rvm/rubies/ruby-head/bin/bundle:23:in `<main>'
.rvm/gems/ruby-head/bin/ruby_executable_hooks:24:in `eval'
.rvm/gems/ruby-head/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by mtsmfm** [comment]
I've created a bundler plugin to remove `--no-hardlinks` and add `--depth=1`.

https://github.com/mtsmfm/bundler-fast_git

I tested it with my hobby app.
Is there any possibility to merge https://github.com/rubygems/bundler/pull/7054?

**Comment by simi** [comment]
just for reference, there's https://github.com/rubygems/rubygems/issues/3378 as well

**Comment by deivid-rodriguez** [comment]
@mtsmfm Yes, I wanted to merge that PR but I forgot about it. Let me rebase it!

**Comment by deivid-rodriguez** [comment]
@mtsmfm I checked the old PR and I saw that I was actually [having some issues with it](https://github.com/rubygems/bundler/pull/7054#issuecomment-483891895). Can you reproduce those issues?

**Comment by mtsmfm** [comment]
@deivid-rodriguez Okay, let me try.

**Comment by mtsmfm** [comment]
I can't find what actually @localhostdotdev did though, I got similar results with the following Gemfile.

```ruby
source "https://rubygems.org"

plugin "bundler-fast_git"

gem "rails", github: "rails/rails", ref: "1da9a7e410f15859939eb4158421846638a41e71"
```

```
$ bundle install --verbose
Running `bundle install --verbose` with bundler 2.1.4
Found changes from the lockfile, re-resolving dependencies because bundler is unlocking HTTP GET https://index.rubygems.org/versions
HTTP 206 Partial Content https://index.rubygems.org/versions
Fetching gem metadata from https://rubygems.org/
Looking up gems ["bundler-fast_git"]
Resolving dependencies...
Using bundler 2.1.4
Using bundler-fast_git 1.0.0
Fetching https://github.com/rails/rails.git
[bundler-fast_git] Running fetch --force --quiet --tags 'https://github.com/rails/rails.git' "refs/heads/*:refs/heads/*"  --depth=1
[bundler-fast_git] Running clone --no-checkout --quiet "/usr/local/bundle/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32" "/usr/local/bundle/bundler/gems/rails-1da9a7e410f1" --depth=1
warning: --depth is ignored in local clones; use file:// instead.
[bundler-fast_git] Running fetch --force --quiet --tags "/usr/local/bundle/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32" --depth=1
fatal: Could not parse object '1da9a7e410f15859939eb4158421846638a41e71'.
Git error: command `git reset --hard 1da9a7e410f15859939eb4158421846638a41e71` in directory /usr/local/bundle/bundler/gems/rails-1da9a7e410f1 has failed.
Revision 1da9a7e410f15859939eb4158421846638a41e71 does not exist in the repository https://github.com/rails/rails.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory '/usr/local/bundle/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32'
Bundler::Source::Git::MissingGitRevisionError: Git error: command `git reset --hard 1da9a7e410f15859939eb4158421846638a41e71` in directory /usr/local/bundle/bundler/gems/rails-1da9a7e410f1 has failed.
```

Previously bundler fetched all reachable refs but currently just fetch the latest branches.
Probably we need to pass git ref to fetch command:
`git fetch --depth=1 origin 1da9a7e410f15859939eb4158421846638a41e71`

**Comment by deivid-rodriguez** [comment]
That seems like a cool idea.
