### ISSUE TITLE
Wrong error message when the corresponding */bin/gem is not in the path

### ISSUE THREAD

**Issue by Cyberbeni** [rubygems/rubygems#3339]
I'm running macOS UI tests on 10.11 for which I needed 2.3 ruby instead of the preinstalled 2.0, I installed it through homebrew then installed bundler with it and added bundler to the path.

When I run bundle install everything works fine. When I run bundle exec after it, I get an error saying that one of the gems is missing and I should run bundle install. The error gets fixed by also adding the 2.3 gem binary to the path.

Please either make it, so we don't need the gem binary in the path or at least update the error message to also warn about this.

This was with 1.17.1 bundler.

[fastlane_output.txt](https://github.com/bundler/bundler/files/2839890/fastlane_output.txt)

```
MacOSX-1011-x64-GUITest-1:testApp jenkins$ bundle install
Using CFPropertyList 3.0.0
Using public_suffix 2.0.5
Using addressable 2.6.0
Using atomos 0.1.3
Using babosa 1.0.2
Using bundler 1.17.1
Using claide 1.0.2
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.10
Using declarative-option 0.1.0
Using digest-crc 0.4.1
Using unf_ext 0.0.7.5
Using unf 0.1.4
Using domain_name 0.5.20180417
Using dotenv 2.6.0
Using emoji_regex 1.0.1
Using excon 0.62.0
Using multipart-post 2.0.0
Using faraday 0.15.4
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 0.13.1
Using fastimage 2.1.5
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using memoist 0.16.0
Using multi_json 1.13.1
Using os 1.0.0
Using signet 0.11.0
Using googleauth 0.6.7
Using httpclient 2.8.3
Using mime-types-data 3.2018.0812
Using mime-types 3.2.2
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.23.9
Using google-cloud-env 1.0.5
Using google-cloud-core 1.3.0
Using google-cloud-storage 1.16.0
Using json 2.1.0
Using mini_magick 4.5.1
Using multi_xml 0.6.0
Using plist 3.5.0
Using rubyzip 1.2.2
Using security 0.1.3
Using naturally 2.2.0
Using simctl 1.6.5
Using slack-notifier 2.3.2
Using terminal-notifier 1.8.0
Using unicode-display_width 1.4.1
Using terminal-table 1.8.0
Using tty-screen 0.6.5
Using tty-cursor 0.6.0
Using tty-spinner 0.9.0
Using word_wrap 1.0.0
Using nanaimo 0.2.6
Using xcodeproj 1.8.0
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.0
Using fastlane 2.115.0
Using xctest_list 1.1.6
Using fastlane-plugin-test_center 3.6.0 from https://github.com/lyndsey-ferguson/fastlane-plugin-test_center.git (at issue-86-no-swift-tests-with-xcode8@a22cc5e)
Bundle complete! 2 Gemfile dependencies, 67 gems now installed.
Bundled gems are installed into `./gems`
MacOSX-1011-x64-GUITest-1:testApp jenkins$ bundle exec fastlane custom_lane --verbose
[✔] 🚀 
DEBUG [2019-02-06 16:13:58.41]: Checking if there are any plugins that should be loaded...
DEBUG [2019-02-06 16:13:58.41]: Loading 'fastlane-plugin-test_center' plugin
INFO [2019-02-06 16:13:58.41]: gem 'fastlane-plugin-test_center' is already installed
+-----------------------------+---------+----------------------------------------------------+
|                                        Used plugins                                        |
+-----------------------------+---------+----------------------------------------------------+
| Plugin                      | Version | Action                                             |
+-----------------------------+---------+----------------------------------------------------+
| fastlane-plugin-test_center | 3.6.0   | collate_html_reports collate_json_reports          |
|                             |         | collate_junit_reports collate_test_result_bundles  |
|                             |         | multi_scan suppress_tests                          |
|                             |         | suppress_tests_from_junit suppressed_tests         |
|                             |         | tests_from_junit tests_from_xctestrun              |
+-----------------------------+---------+----------------------------------------------------+

Successfully loaded Appfile at path '/Users/jenkins/Desktop/test workspace/testApp/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/jenkins/Desktop/test workspace/testApp/fastlane/Appfile'
-------
INFO [2019-02-06 16:13:58.53]: ------------------------------
INFO [2019-02-06 16:13:58.53]: --- Step: default_platform ---
INFO [2019-02-06 16:13:58.53]: ------------------------------
INFO [2019-02-06 16:13:58.54]: Driving the lane 'custom_lane' 🚀
INFO [2019-02-06 16:13:58.54]: ------------------------
INFO [2019-02-06 16:13:58.54]: --- Step: multi_scan ---
INFO [2019-02-06 16:13:58.54]: ------------------------
Successfully loaded Appfile at path '/Users/jenkins/Desktop/test workspace/testApp/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/jenkins/Desktop/test workspace/testApp/fastlane/Appfile'
-------

++
| Summary for multi_scan (test_center v3.6.0) |
++
++

Successfully loaded Appfile at path '/Users/jenkins/Desktop/test workspace/testApp/fastlane/Appfile'
-------
INFO [2019-02-06 16:13:58.61]: $ xcodebuild clean -showBuildSettings -scheme testApp -project ./testApp.xcodeproj
INFO [2019-02-06 16:13:59.25]: $ xcodebuild clean -showBuildSettings -scheme testApp -project ./testApp.xcodeproj

+------------------------------------------------+----------------------------------------------------------------+
|                                            Summary for scan 2.115.0                                             |
+------------------------------------------------+----------------------------------------------------------------+
| derived_data_path                              | dd                                                             |
| build_for_testing                              | true                                                           |
| project                                        | ./testApp.xcodeproj                                            |
| scheme                                         | testApp                                                        |
| skip_detect_devices                            | false                                                          |
| reset_simulator                                | false                                                          |
| reinstall_app                                  | false                                                          |
| clean                                          | false                                                          |
| open_report                                    | false                                                          |
| output_directory                               | ./fastlane/test_output                                         |
| output_types                                   | html,junit                                                     |
| buildlog_path                                  | ~/Library/Logs/scan                                            |
| include_simulator_logs                         | false                                                          |
| should_zip_build_products                      | false                                                          |
| result_bundle                                  | false                                                          |
| use_clang_report_name                          | false                                                          |
| disable_concurrent_testing                     | false                                                          |
| skip_build                                     | false                                                          |
| slack_use_webhook_configured_username_and_icon | false                                                          |
| slack_username                                 | fastlane                                                       |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png |
| skip_slack                                     | false                                                          |
| slack_only_on_failure                          | false                                                          |
| fail_build                                     | true                                                           |
| xcode_path                                     | /Applications/Xcode.app                                        |
+------------------------------------------------+----------------------------------------------------------------+

INFO [2019-02-06 16:13:59.87]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme testApp -project ./testApp.xcodeproj -destination 'platform=macOS' -derivedDataPath 'dd' build-for-testing | tee '/Users/jenkins/Library/Logs/scan/testApp-testApp.log' | xcpretty  --report html --output '/Users/jenkins/Desktop/test workspace/testApp/fastlane/test_output/report.html' --report junit --output '/Users/jenkins/Desktop/test workspace/testApp/fastlane/test_output/report.junit' --report junit --output '/var/folders/31/lx_rvf757kbfj145_4t8nl9w0000gp/T/junit_report20190206-58081-1t56fiu' 
INFO [2019-02-06 16:13:59.87]: ▸ Loading...
INFO [2019-02-06 16:14:00.03]: ▸ Could not find CFPropertyList-3.0.0 in any of the sources
INFO [2019-02-06 16:14:00.03]: ▸ Run `bundle install` to install missing gems.
Could not find CFPropertyList-3.0.0 in any of the sources
Run `bundle install` to install missing gems.
ERROR [2019-02-06 16:14:00.58]: Exit status: 7
WARN [2019-02-06 16:14:00.59]: Lane Context:
INFO [2019-02-06 16:14:00.59]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"custom_lane", :SCAN_DERIVED_DATA_PATH=>"dd", :SCAN_GENERATED_PLIST_FILES=>[], :SCAN_GENERATED_PLIST_FILE=>nil}
ERROR [2019-02-06 16:14:00.59]: Error building/testing the application - see the log above
INFO [2019-02-06 16:14:00.59]: Successfully generated documentation at path '/Users/jenkins/Desktop/test workspace/testApp/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | multi_scan       | 2           |
+------+------------------+-------------+

DEBUG [2019-02-06 16:14:00.59]: All plugins are up to date
ERROR [2019-02-06 16:14:00.59]: fastlane finished with errors
DEBUG [2019-02-06 16:14:00.59]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneBuildFailure: [!] Error building/testing the application - see the log above
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/scan/lib/scan/error_handler.rb:41:in `handle_build_error'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/scan/lib/scan/runner.rb:65:in `block in test_app'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/scan/lib/scan/runner.rb:56:in `test_app'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/scan/lib/scan/runner.rb:22:in `run'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/scan/lib/scan/manager.rb:18:in `work'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/actions/run_tests.rb:23:in `run'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/bundler/gems/fastlane-plugin-test_center-a22cc5eee20a/lib/fastlane/plugin/test_center/actions/multi_scan.rb:97:in `build_for_testing'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/bundler/gems/fastlane-plugin-test_center-a22cc5eee20a/lib/fastlane/plugin/test_center/actions/multi_scan.rb:18:in `run'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:19:in `block in parsing_binding'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/gems/fastlane-2.115.0/bin/fastlane:23:in `<top (required)>'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/bin/fastlane:22:in `load'
  /Users/jenkins/Desktop/test workspace/testApp/gems/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'
MacOSX-1011-x64-GUITest-1:testApp jenkins$ 
```

**Comment by deivid-rodriguez** [comment]
I guess we could warn when running the `gem` executable directly, without its containing folder being in `PATH`, yeah.

**Comment by deivid-rodriguez** [comment]
I'm going to close this issue because it's quite old and we don't support Ruby 2.3 anymore. If this can be reproduce with newer rubies, please reopen with reproducible steps, and I will have a look soon.
