### ISSUE TITLE
How to use Bundler 2.0 on MRI 2.6.0?

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#3346]
I can install the gem with `gem install bundler`, but it's not used:
```
$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (2.0.1, default: 1.17.3)
...

$ bundle --version
Bundler version 1.17.3

$ bundle _2.0.1_ --version
Traceback (most recent call last):
	2: from /home/eregon/.gem/ruby/2.6.0/bin/bundle:23:in `<main>'
	1: from /home/eregon/.rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/home/eregon/.rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /home/eregon/code/mspec/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
```

And running that (or `bundle _2.0.1_ update --bundler`) doesn't change the Gemfile.lock.

I also tried to update RubyGems with `gem update --system`, but that doesn't help either.

**Comment by deivid-rodriguez** [comment]
This is related to the ongoing discussion about the version switcher, so I'll close this ticket in favor of those.
