### ISSUE TITLE
Adding a way to disable friendly errors

### ISSUE THREAD

**Issue by martinos** [rubygems/rubygems#3368]
All my scripts have `at_exit` handle that logs all the uncaught exception to a file. This is very useful for diagnosing issues. This was working very well for a while but now all programs that are executed with `bundle exec` are run insides the `FriendlyErrors.with_friendly_errors` method which changes the raised exception.

I think that it should have a way to disable that filtering because it changes the behaviour the original program. I would expect that program to have exactly the same output either it's run inside bundler or not.

**Comment by deivid-rodriguez** [comment]
If I understood this issue correctly, I'm guessing something like this should do the trick?

```diff
diff --git a/bundler/lib/bundler/friendly_errors.rb b/bundler/lib/bundler/friendly_errors.rb
index 8273064699..3d40073a7b 100644
--- a/bundler/lib/bundler/friendly_errors.rb
+++ b/bundler/lib/bundler/friendly_errors.rb
@@ -46,7 +46,7 @@ def exit_status(error)
       when BundlerError then error.status_code
       when Thor::Error then 15
       when SystemExit then error.status
-      else 1
+      else nil
       end
     end
 
@@ -119,6 +119,7 @@ def self.with_friendly_errors
     raise
   rescue Exception => e # rubocop:disable Lint/RescueException
     FriendlyErrors.log_error(e)
-    exit FriendlyErrors.exit_status(e)
+    exit_status = FriendlyErrors.exit_status(e)
+    exit_status ? exit(exit_status) : raise
   end
 end
```

Could someone try it?

**Comment by deivid-rodriguez** [comment]
Actually I just tried https://github.com/rubygems/rubygems/issues/3368#issuecomment-516546765, it doesn't work. I'll iterate on this.

**Comment by deivid-rodriguez** [comment]
I think something like this would work:

```diff
diff --git a/bundler/lib/bundler/cli/exec.rb b/bundler/lib/bundler/cli/exec.rb
index 0412d3adb0..2ee1022615 100644
--- a/bundler/lib/bundler/cli/exec.rb
+++ b/bundler/lib/bundler/cli/exec.rb
@@ -63,10 +63,9 @@ def kernel_load(file, *args)
       Kernel.load(file)
     rescue SystemExit, SignalException
       raise
-    rescue Exception => e # rubocop:disable Lint/RescueException
+    rescue Exception # rubocop:disable Lint/RescueException
       Bundler.ui.error "bundler: failed to load command: #{cmd} (#{file})"
-      backtrace = e.backtrace ? e.backtrace.take_while {|bt| !bt.start_with?(__FILE__) } : []
-      abort "#{e.class}: #{e.message}\n  #{backtrace.join("\n  ")}"
+      raise
     end
 
     def process_title(file, args)
diff --git a/bundler/lib/bundler/friendly_errors.rb b/bundler/lib/bundler/friendly_errors.rb
index 8273064699..71f3fac6b0 100644
--- a/bundler/lib/bundler/friendly_errors.rb
+++ b/bundler/lib/bundler/friendly_errors.rb
@@ -46,11 +46,20 @@ def exit_status(error)
       when BundlerError then error.status_code
       when Thor::Error then 15
       when SystemExit then error.status
-      else 1
       end
     end
 
+    def internal_error?(e)
+      bundler_files = Dir.glob("#{File.dirname(__dir__)}/bundler{,/**/*}.rb")
+      backtrace_locations = e.backtrace_locations
+      return false unless backtrace_locations
+      crash_location = backtrace_locations.first.path
+      bundler_files.include?(crash_location)
+    end
+
     def request_issue_report_for(e)
+      return unless internal_error?(e)
+
       Bundler.ui.error <<-EOS.gsub(/^ {8}/, ""), nil, nil
         --- ERROR REPORT TEMPLATE -------------------------------------------------------
         # Error Report
@@ -119,6 +128,7 @@ def self.with_friendly_errors
     raise
   rescue Exception => e # rubocop:disable Lint/RescueException
     FriendlyErrors.log_error(e)
-    exit FriendlyErrors.exit_status(e)
+    exit_status = FriendlyErrors.exit_status(e)
+    exit_status ? exit(exit_status) : raise
   end
 end
```

**Comment by deivid-rodriguez** [comment]
A simpler attempt after revisiting

```diff
diff --git a/bundler/lib/bundler/cli/exec.rb b/bundler/lib/bundler/cli/exec.rb
index 0412d3adb0..3effcf0b39 100644
--- a/bundler/lib/bundler/cli/exec.rb
+++ b/bundler/lib/bundler/cli/exec.rb
@@ -63,10 +63,9 @@ def kernel_load(file, *args)
       Kernel.load(file)
     rescue SystemExit, SignalException
       raise
-    rescue Exception => e # rubocop:disable Lint/RescueException
-      Bundler.ui.error "bundler: failed to load command: #{cmd} (#{file})"
-      backtrace = e.backtrace ? e.backtrace.take_while {|bt| !bt.start_with?(__FILE__) } : []
-      abort "#{e.class}: #{e.message}\n  #{backtrace.join("\n  ")}"
+    rescue Exception # rubocop:disable Lint/RescueException
+      Bundler::FriendlyErrors.bundle_exec_error = true
+      raise
     end
 
     def process_title(file, args)
diff --git a/bundler/lib/bundler/friendly_errors.rb b/bundler/lib/bundler/friendly_errors.rb
index 8273064699..825ac896d2 100644
--- a/bundler/lib/bundler/friendly_errors.rb
+++ b/bundler/lib/bundler/friendly_errors.rb
@@ -6,6 +6,14 @@ module Bundler
   module FriendlyErrors
     module_function
 
+    def bundle_exec_error
+      @bundle_exec_error
+    end
+
+    def bundle_exec_error=(flag)
+      @bundle_exec_error = flag
+    end
+
     def log_error(error)
       case error
       when YamlSyntaxError
@@ -118,6 +126,8 @@ def self.with_friendly_errors
   rescue SignalException
     raise
   rescue Exception => e # rubocop:disable Lint/RescueException
+    raise if FriendlyErrors.bundle_exec_error
+
     FriendlyErrors.log_error(e)
     exit
```

With that patch, the result of running

```ruby
#!/usr/bin/env ruby

at_exit do
  puts "in at_exit: #{$!.class.to_s}"
end

1/0
```

with and without `bundle exec` is

```
$ ./foo.rb
in at_exit: ZeroDivisionError
Traceback (most recent call last):
	1: from foo.rb:7:in `<main>'
foo.rb:7:in `/': divided by 0 (ZeroDivisionError)

$ bundle exec foo.rb
in at_exit: ZeroDivisionError
Traceback (most recent call last):
	16: from /home/deivid/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
	15: from /home/deivid/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	14: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0.rc.2/exe/bundle:37:in `<top (required)>'
	13: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:125:in `with_friendly_errors'
	12: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0.rc.2/exe/bundle:49:in `block in <top (required)>'
	11: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
	10: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	 9: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	 8: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	 7: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	 6: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	 5: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:497:in `exec'
	 4: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	 3: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	 2: from /home/deivid/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	 1: from foo.rb:7:in `<top (required)>'
foo.rb:7:in `/': divided by 0 (ZeroDivisionError)
```

Which seems like the correct thing to me.
