### ISSUE TITLE
Bundler cannot run on Windows when username contains non-ASCII characters

### ISSUE THREAD

**Issue by galopin** [rubygems/rubygems#3373]
I have the following issue on my Windows set-up:

```
$ echo $HOME
/c/Documents and Settings/Michaël

$ bundle -v
C:/Ruby200/lib/ruby/site_ruby/2.0.0/rbreadline.rb:1097:in `<module:RbReadline>': HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory (RuntimeError)
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rbreadline.rb:17:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/readline.rb:10:in `<module:Readline>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/readline.rb:8:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/line_editor/readline.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/line_editor.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:8:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendored_thor.rb:3:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:4:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/exe/bundle:23:in `<top (required)>'
        from C:/Ruby200/bin/bundle:22:in `load'
        from C:/Ruby200/bin/bundle:22:in `<main>'
```

The problem comes from a patch that was applied years ago to the [Pure-Ruby Readline](https://github.com/ConnorAtherton/rb-readline) implementation — the original issue (https://github.com/ConnorAtherton/rb-readline/issues/8) was fixed by this pull request (https://github.com/ConnorAtherton/rb-readline/pull/89).

My `HOME` environment variable is _properly set_ and points to a _valid directory_ but I strongly suspect that `ENV['HOME']` string encoding gets somehow corrupted. And that Bundler cannot handle, as a consequence, such things as diacritic marks in Windows username — see [`user_home()`](https://github.com/bundler/bundler/blob/6e14ebe9f75506bddf623fb83d275deaaca8d8b8/lib/bundler.rb#L147-L167)  and [`tmp_home_path()`](https://github.com/bundler/bundler/blob/6e14ebe9f75506bddf623fb83d275deaaca8d8b8/lib/bundler.rb#L169-L181).

BTW, I found [another issue](https://bugs.ruby-lang.org/issues/9715) on the Ruby trunk which might be related .

Is there anything you can do to improve this situation?

**Comment by deivid-rodriguez** [comment]
Hi!

We now vendor a version of `thor` that [no longer requires `readline` eagerly](https://github.com/erikhuda/thor/pull/689). Plus, I think ruby on Windows now includes `reline` instead of `rbreline` by default.

So I will close this issue, since this should no longer be a problem.
