### ISSUE TITLE
Random test failure on Windows (output syncronization issue?)

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3448]
Sometimes, we get the following spec failure under Windows:

```
Failures:

  1) bundle install with git sources with an extension does reinstall the extension when changing refs

     Failure/Error: raise "Invoking #{method}!(#{args.map(&:inspect).join(", ")}) failed:\n#{last_command.stdboth}"

     RuntimeError:
       Invoking run!("        require 'foo'\n        puts FOO\n") failed:
       d:/a/rubygems/rubygems/bundler/lib/bundler/source/git/git_proxy.rb:241:in `allowed_in_path': The git source d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0 is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git/git_proxy.rb:198:in `find_local_revision'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git/git_proxy.rb:68:in `revision'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:226:in `revision'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:93:in `install_path'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/path.rb:131:in `expanded_path'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/path.rb:172:in `load_spec_files'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:201:in `load_spec_files'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/path.rb:105:in `local_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:168:in `specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:768:in `block in converge_locked_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:754:in `each'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:754:in `converge_locked_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:252:in `resolve'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:174:in `specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:242:in `specs_for'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:230:in `requested_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/runtime.rb:101:in `block in definition_method'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/runtime.rb:20:in `setup'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler.rb:149:in `setup'
       	from -e:1:in `block in <main>'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/ui/shell.rb:136:in `with_level'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/ui/shell.rb:88:in `silence'
       	from -e:1:in `<main>'

       Commands:
       $  D:/rubyinstaller-2.6.5-1-x64/bin/ruby.exe -Id:/a/rubygems/rubygems/bundler/lib;d:/a/rubygems/rubygems/bundler/spec -rsupport/hax -rsupport/artifice/fail d:/a/rubygems/rubygems/bundler/exe/bundle install --retry 0
       Fetching d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0
       Fetching source index from file:///d:/a/rubygems/rubygems/bundler/tmp/1/gems/remote1/
       Resolving dependencies...
       Fetching rake 13.0.1
       Installing rake 13.0.1
       Using bundler 2.2.0.dev
       Using foo 1.0 from d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0 (at master@348ba56)
       Bundle complete! 1 Gemfile dependency, 3 gems now installed.
       Use `bundle info [gemname]` to see where a bundled gem is installed.
       D:/rubyinstaller-2.6.5-1-x64/lib/ruby/2.6.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
       D:/rubyinstaller-2.6.5-1-x64/lib/ruby/2.6.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block
       # $? => 0

       $ D:/rubyinstaller-2.6.5-1-x64/bin/ruby.exe -Id:/a/rubygems/rubygems/bundler/lib -w -e require\ \'d:/a/rubygems/rubygems/bundler/lib/bundler\'\ \;\ Bundler.ui.silence\ \{\ Bundler.setup\(\)\ \}'
       '\ \ \ \ \ \ \ \ require\ \'foo\''
       '\ \ \ \ \ \ \ \ puts\ FOO'
       '
       1585313080.7040782
       # $? => 0

       $  D:/rubyinstaller-2.6.5-1-x64/bin/ruby.exe -Id:/a/rubygems/rubygems/bundler/lib;d:/a/rubygems/rubygems/bundler/spec -rsupport/hax -rsupport/artifice/fail d:/a/rubygems/rubygems/bundler/exe/bundle install --retry 0
       Fetching d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0
       Fetching source index from file:///d:/a/rubygems/rubygems/bundler/tmp/1/gems/remote1/
       Resolving dependencies...
       Using rake 13.0.1
       Using foo 1.0 from d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0 (at branch2@Using b)
       Bundle complete! 1 Gemfile dependency, 3 gems now installed.
       Use `bundle info [gemname]` to see where a bundled gem is installed.
       D:/rubyinstaller-2.6.5-1-x64/lib/ruby/2.6.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
       D:/rubyinstaller-2.6.5-1-x64/lib/ruby/2.6.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block
       # $? => 0

       $ D:/rubyinstaller-2.6.5-1-x64/bin/ruby.exe -Id:/a/rubygems/rubygems/bundler/lib -w -e require\ \'d:/a/rubygems/rubygems/bundler/lib/bundler\'\ \;\ Bundler.ui.silence\ \{\ Bundler.setup\(\)\ \}'
       '\ \ \ \ \ \ \ \ require\ \'foo\''
       '\ \ \ \ \ \ \ \ puts\ FOO'
       '
       d:/a/rubygems/rubygems/bundler/lib/bundler/source/git/git_proxy.rb:241:in `allowed_in_path': The git source d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0 is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git/git_proxy.rb:198:in `find_local_revision'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git/git_proxy.rb:68:in `revision'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:226:in `revision'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:93:in `install_path'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/path.rb:131:in `expanded_path'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/path.rb:172:in `load_spec_files'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:201:in `load_spec_files'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/path.rb:105:in `local_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/source/git.rb:168:in `specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:768:in `block in converge_locked_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:754:in `each'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:754:in `converge_locked_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:252:in `resolve'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:174:in `specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:242:in `specs_for'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/definition.rb:230:in `requested_specs'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/runtime.rb:101:in `block in definition_method'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/runtime.rb:20:in `setup'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler.rb:149:in `setup'
       	from -e:1:in `block in <main>'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/ui/shell.rb:136:in `with_level'
       	from d:/a/rubygems/rubygems/bundler/lib/bundler/ui/shell.rb:88:in `silence'
       	from -e:1:in `<main>'
       # $? => 1
     # ./spec/support/helpers.rb:26:in `block (2 levels) in bang'
     # ./spec/support/helpers.rb:24:in `tap'
     # ./spec/support/helpers.rb:24:in `block in bang'
     # ./spec/install/gemfile/git_spec.rb:1323:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:109:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:109:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:76:in `block (2 levels) in <top (required)>'
     # ./spec/support/rubygems_ext.rb:96:in `load'
     # ./spec/support/rubygems_ext.rb:96:in `gem_load_and_activate'
     # ./spec/support/rubygems_ext.rb:43:in `gem_load'

Finished in 34 minutes 59 seconds (files took 1.03 seconds to load)
1325 examples, 1 failure, 87 pending

Failed examples:

rspec ./spec/install/gemfile/git_spec.rb:1287 # bundle install with git sources with an extension does reinstall the extension when changing refs
```

See for example: https://github.com/rubygems/rubygems/pull/3446/checks?check_run_id=539299927.

Same like a thread safety issue. See the warnings in the `bundle install` command:

>  D:/rubyinstaller-2.6.5-1-x64/lib/ruby/2.6.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
>  D:/rubyinstaller-2.6.5-1-x64/lib/ruby/2.6.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block

And how the git reference in that same command (`Using foo 1.0 from d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0 (at branch2@Using b)`). The git reference is computed by capturing the output of a `git` command through `Open3`, but it seems to be capturing the output of the wrong thread for some reason :grimacing:.

**Comment by deivid-rodriguez** [comment]
Another one: https://github.com/rubygems/rubygems/pull/3476/checks?check_run_id=562391869.

**Comment by deivid-rodriguez** [comment]
Another one: https://github.com/rubygems/rubygems/pull/3483/checks?check_run_id=564859701

**Comment by deivid-rodriguez** [comment]
This is is slightly different, but looks like the same underlying cause: https://github.com/rubygems/rubygems/runs/569859528.

**Comment by deivid-rodriguez** [comment]
It happened again: https://github.com/rubygems/rubygems/runs/599534032. So not switching folders during git operations didn't fix it :(

The thread safety issue seems related to extension compilation, so https://github.com/rubygems/rubygems/pull/3498 might fix it.

**Comment by deivid-rodriguez** [comment]
It happened again in https://github.com/rubygems/rubygems/runs/634190749. One of the failure there doesn't involve extensions, so it there must be at least something else.

The output synchronization thing is really weird:

``` 
$  D:/rubyinstaller-2.6.6-1-x64/bin/ruby.exe -Id:/a/rubygems/rubygems/bundler/lib;d:/a/rubygems/rubygems/bundler/spec -rsupport/hax -rsupport/artifice/fail d:/a/rubygems/rubygems/bundler/exe/bundle install --retry 0
Fetching d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0
Fetching source index from file:///d:/a/rubygems/rubygems/bundler/tmp/1/gems/remote1/
Resolving dependencies...
Using rake 13.0.1
Using foo 1.0 from d:/a/rubygems/rubygems/bundler/tmp/1/libs/foo-1.0 (at branch2@Using b)
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Note how the "Using bundler 2.2.0.dev" line is missing, but instead we get those "Using b" strings at the place where there's should be a git reference.

Really weird.

**Comment by deivid-rodriguez** [comment]
This issue keeps happening, and I'm not sure what to do about it. It seems like a race condition on `STDOUT`, specific to Windows. And it happens somewhat frequently on `bundle install`'s using `GIT` sources. I'm wondering if we should switch back the default of `bundle install` to a single thread on Windows.
