### ISSUE TITLE
Please improve `Gem::MissingSpecError` error message

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#3521]
Consider this backtrace:

~~~
/usr/share/rubygems/rubygems/dependency.rb:311:in `to_specs': Could not find 'ipaddr' (>= 0) among 12 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/builddir/.gem/ruby:/usr/share/gems:/usr/local/share/gems', execute `gem env` for more information
	from /usr/share/rubygems/rubygems/specification.rb:1402:in `block in activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1391:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:1391:in `activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1373:in `activate'
	from /usr/share/rubygems/rubygems/specification.rb:1405:in `block in activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1391:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:1391:in `activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1373:in `activate'
	from /usr/share/rubygems/rubygems.rb:209:in `try_activate'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:156:in `require'
	from /builddir/build/BUILD/rubygem-net-ssh-gateway-1.2.0/usr/share/gems/gems/net-ssh-gateway-1.2.0/lib/net/ssh/gateway.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /builddir/build/BUILD/rubygem-net-ssh-gateway-1.2.0/usr/share/gems/gems/net-ssh-gateway-1.2.0/test/gateway_test.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
	from -e:1:in `glob'
	from -e:1:in `<main>'
~~~

The most annoying thing about this backtrace is that it is actually not helpful, because while it says there is issue and there is something missing, it does not report where the error actually comes from. Specifically in this case, there is somewhere .gemspec file declaring this dependency, but there is no way to back track which .gemspec. There is not even reported which file was originally required to provide at leas a bit of help. I would really appreciate if this could be improved.

**Comment by deivid-rodriguez** [comment]
Agreed! PRs welcome!
