### ISSUE TITLE
Gem::GemNotFoundException: Could not find 'bundler' (2.1.4)

### ISSUE THREAD

**Issue by scalp42** [rubygems/rubygems#3549]
## Issue

I can't run any `bundle exec *` command with `2.1.4`.

I can confirm that Bundler is installed:

```
$> bundle --version
Bundler version 2.1.4

$> which bundle
/usr/local/opt/ruby/bin/bundle
```

The following commands work fine:

```
$> bundle
Using bundler 2.1.4
Using coderay 1.1.2
Using method_source 1.0.0
Using pry 0.13.1
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$> bundle update --bundler
Using bundler 2.1.4
Using coderay 1.1.2
Using method_source 1.0.0
Using pry 0.13.1
Bundle updated!

$> bundle exec
bundler: exec needs a command to run
```

## Bundler Build Metadata

```
Built At          2020-04-24
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'pry'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    coderay (1.1.2)
    method_source (1.0.0)
    pry (0.13.1)
      coderay (~> 1.1)
      method_source (~> 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  pry

BUNDLED WITH
   2.1.4
```

## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-18
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-darwin18]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/2.7.1/etc
RubyGems      3.1.2
  Gem Home    /usr/local/lib/ruby/gems/2.7.0
  Gem Path    /Users/scalp/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/Cellar/ruby/2.7.1/lib/ruby/gems/2.7.0
  User Home   /Users/scalp
  User Path   /Users/scalp/.gem/ruby/2.7.0
  Bin Dir     /usr/local/lib/ruby/gems/2.7.0/bin
Tools
  Git         2.20.1 (Apple Git-117)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      /usr/local/opt/ruby/bin/ruby
bundle #!     /usr/local/Cellar/ruby/2.7.1/bin/ruby
```

## Backtrace

```
Gem::GemNotFoundException: Could not find 'bundler' (2.1.4) required by your /private/tmp/Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`

  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/rubygems_integration.rb:223:in `bin_path'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:25:in `run'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
  /usr/local/Cellar/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
  /usr/local/opt/ruby/bin/bundle:23:in `load'
  /usr/local/opt/ruby/bin/bundle:23:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
I fixed a somewhat similar issue recently. Just to double check it's not the same thing. Could you downgrade rubygems and upgrade it back (`gem update --system 3.0.8 && gem update --system`), and try again?

**Comment by scalp42** [comment]
@deivid-rodriguez thanks for the help, looks like it blew up:

```
$> gem update --system 3.0.8 --no-doc && gem update --system --no-doc
Updating rubygems-update
Successfully installed rubygems-update-3.0.8
Installing RubyGems 3.0.8
Traceback (most recent call last):
	6: from setup.rb:28:in `<main>'
	5: from setup.rb:28:in `require'
	4: from /usr/local/lib/ruby/gems/2.7.0/gems/rubygems-update-3.0.8/lib/rubygems.rb:1372:in `<top (required)>'
	3: from /usr/local/lib/ruby/gems/2.7.0/gems/rubygems-update-3.0.8/lib/rubygems.rb:1372:in `require'
	2: from /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/rubygems/defaults/operating_system.rb:1:in `<top (required)>'
	1: from /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/rubygems/defaults/operating_system.rb:2:in `<module:Gem>'
/usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/rubygems/defaults/operating_system.rb:7:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)
Latest version already installed. Done.
```

**Comment by scalp42** [comment]
I somehow fixed it by running the following command:

```
$> gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
```

I'm still confused as it's exact same version:

```
$> bundle --version
Bundler version 2.1.4
```

Same path as well:

```
$> which bundle
/usr/local/opt/ruby/bin/bundle
```

**Comment by deivid-rodriguez** [comment]
@scalp42 I believe the workaround was not properly applied because your brew ruby formula doesn't include https://github.com/Homebrew/homebrew-core/commit/86f2387f4ae095f08804d38efdfd9adf91d447d9. Could you upgrade the formula and then try to apply the workaround again?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by iamunadike** [comment]
What you need to do is to know that a gem lock existing for a rails repo created and that ties a bond or say a connection between the active gems and the project at the time of creation.
to stop this error, 
1. simply remove the former gemfile.lock
2. update the gemfile. this file contains your active gems to be used for your system including the ruby version for the case of compatability
3. finally run bundle install with superuser privileges or bundle install --path vendor/bundle for a normal user
that should fix all the issues

**Comment by iamunadike** [comment]
the above is a typical solution for a rails project

**Comment by heathdevelopment** [comment]
I solved this problem by restarting my terminal. I received the same error above "Could not find 'bundler' (2.1.4) required"  after install rails 6.1.1 then attempting to check rails version.  After adding rails using "rbenv rehash" to add rails to the terminal, I figured it need to be restarted to fetch the path in memory. Hope this helps someone.

**Comment by daBee** [comment]
I'm having this issue now, later on.  

https://github.com/rubygems/rubygems/issues/5244

**Comment by Mahmoud4m** [comment]
Traceback (most recent call last):
        2: from /data/data/com.termux/files/usr/bin/lolcat:25:in `<main>'
        1: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem lolcat (>= 0.a) with executable lolcat (Gem::GemNotFoundException)
