### ISSUE TITLE
Having a repository called bundler causes bundler to break

### ISSUE THREAD

**Issue by chrisseaton** [rubygems/rubygems#3744]
Thank you for contributing to the [rubygems](https://github.com/rubygems/rubygems) repository, and specifically to the [Bundler](https://bundler.io/) gem.

Before processing your issue please confirm that:

- [X] You checked all the following documents and couldn't find a solution for your issue:

- [Troubleshooting common issues](https://github.com/rubygems/rubygems/blob/master/bundler/doc/TROUBLESHOOTING.md)
- [Bundler documentation site](https://bundler.io/)
- [Bundler man pages](https://bundler.io/man/bundle.1.html)
- [Bundler command line reference](https://bundler.io/v2.0/commands.html)

If you haven't done that, please do it before creating a new issue.

Please answer the following questions so we can process your issue as fast as possible:

1. Do you have a reproduction script? It would be really helpful for us if you provide one. Examples: [Sample repro script for Bundler issues](https://gist.github.com/xaviershay/6207550), [Another sample repro script for Bundler issues](https://gist.github.com/xaviershay/6295889).

```
chrisseaton@Chris-Seatons-MacBook-Pro Documents % git clone git@github.com:chrisseaton/bundler-failure.git
Cloning into 'bundler-failure'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (7/7), done.
Receiving objects: 100% (12/12), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
chrisseaton@Chris-Seatons-MacBook-Pro Documents % cd bundler-failure 
chrisseaton@Chris-Seatons-MacBook-Pro bundler-failure % bundle install
Using bundler 2.1.4
Using test 0.1 from source at `.`
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
chrisseaton@Chris-Seatons-MacBook-Pro bundler-failure % bundle exec bin/test foo bar baz
["foo", "bar", "baz"]
chrisseaton@Chris-Seatons-MacBook-Pro bundler-failure % git clone https://github.com/bundler/bundler.git                    
Cloning into 'bundler'...
remote: Enumerating objects: 480613, done.
remote: Total 480613 (delta 0), reused 0 (delta 0), pack-reused 480613
Receiving objects: 100% (480613/480613), 221.60 MiB | 5.84 MiB/s, done.
Resolving deltas: 100% (354194/354194), done.
chrisseaton@Chris-Seatons-MacBook-Pro bundler-failure % bundle exec bin/test foo bar baz                        
/Users/chrisseaton/Documents/bundler-failure/bundler/lib/bundler/version.rb:4: warning: already initialized constant Bundler::VERSION
/Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/version.rb:4: warning: previous definition of VERSION was here
bundler: failed to load command: bin/test (bin/test)
Gem::GemNotFoundException: Could not find 'bundler' (2.1.4) required by `$BUNDLER_VERSION`.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`

  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/rubygems_integration.rb:223:in `bin_path'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:22:in `setup'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler.rb:149:in `setup'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
  /Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
```

2. What are you trying to accomplish?

I have a gem that clones repositories. It cloned `bundler`, and then it broke.

3. What command did you run?

As in the reproduction script.

4. What were you expecting to happen?

I wasn't expecting having an extra directory in my gem to break bundler. Nothing requires anything in this directory. Why does it matter?

5. What actually happened?

As in the reproduction script.

6. Is there an exception backtrace? If so, please copy it below.

As in the reproduction script.

7. Please run `bundle env` and paste the output below:

```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-19
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-darwin19]
  Full Path   /Users/chrisseaton/.rubies/ruby-2.7.1/bin/ruby
  Config Dir  /Users/chrisseaton/.rubies/ruby-2.7.1/etc
RubyGems      3.1.2
  Gem Home    /Users/chrisseaton/.gem/ruby/2.7.1
  Gem Path    /Users/chrisseaton/.gem/ruby/2.7.1:/Users/chrisseaton/.rubies/ruby-2.7.1/lib/ruby/gems/2.7.0
  User Home   /Users/chrisseaton
  User Path   /Users/chrisseaton/.gem/ruby/2.7.0
  Bin Dir     /Users/chrisseaton/.gem/ruby/2.7.1/bin
Tools         
  Git         2.26.2
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2020-06-20
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
packages.shopify.io
  Set for the current user (/Users/chrisseaton/.bundle/config): "c93d64a08aa937f5e59a83fd4307c234e446a0a17b661fdc"
gem.test
  Set for the current user (/Users/chrisseaton/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/chrisseaton/.bundle/config): false
gem.coc
  Set for the current user (/Users/chrisseaton/.bundle/config): false
```

### Gemfile

```ruby
source 'https://rubygems.org'
gemspec
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    test (0.1)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  test!

BUNDLED WITH
   2.1.4
```

### test.gemspec

```ruby
require_relative 'lib/test/version'

Gem::Specification.new do |spec|
  spec.name     = 'test'
  spec.version  = Test::VERSION
  spec.summary  = 'test'
  spec.authors  = ['Chris Seaton']
  spec.bindir   = 'bin'
end
```

For more information please check [Filing Issues: a guide](https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md).

Thank you!

**Comment by deivid-rodriguez** [comment]
Hi @chrisseaton!

I had a look at this, and I'm not sure what to do about it. In my case, the repro steps led to a different error, namely:

```
bundler: failed to load command: bin/test (bin/test)
Gem::LoadError: You have already activated bundler 2.1.4, but your Gemfile requires bundler 2.2.0.dev. Prepending `bundle exec` to your command may solve this.
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:312:in `check_for_activated_spec!'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:31:in `block in setup'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:147:in `each'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:147:in `each'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:26:in `map'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:26:in `setup'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `block in <top (required)>'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `<top (required)>'
```

The explanation for this error is the following:

The `Gemfile` we have reads:

```ruby
source 'https://rubygems.org'
gemspec
```

The `gemspec` DSL by default means: consider any gemspecs in the current directory or any subdirectories of it. So, when you clone `bundler` in a subfolder, the `bundler.gemspec` file in the clone starts being considered. So, the bundler version you have installed globally is initially activated, but then when the `gemspec` DSL is evaluated `bundler` thinks it needs to load the version of itself specified in the cloned `bundler.gemspec` file. Since the two versions are incompatible, `bundler` raises a conflict.

A workaround could be to change the `Gemfile` to:

```ruby
source 'https://rubygems.org'
gemspec glob: "test.gemspec"
```

Does modifying the `Gemfile` like that fix the issue for you?

And honestly, only loading the gemspec in the cwd is the behaviour I expected from the `gemspec` DSL before reading its code. But I'm afraid monorepos might be relying on the current behaviour, so changing it could get tricky.

**Comment by chrisseaton** [comment]
Maybe I should just not clone Bundler into my repos.

**Comment by deivid-rodriguez** [comment]
Does modifying the `Gemfile` as suggested fix the issue for you though?

**Comment by chrisseaton** [comment]
That works.

**Comment by deivid-rodriguez** [comment]
Ok, so to "resolve" this issue I would propose to deprecate `gemspec` loading multiple gemspecs and instead make it load only the gemspec in the same folder as the `Gemfile`. As an alternative for the current behavior we could:

* Require an explicit glob if you want to load multiple gemspecs.
* Introduce a new `gemspecs` DSL method to load multiple gemspecs.
