### ISSUE TITLE
bundle - user . does not exist

### ISSUE THREAD

**Issue by fcbarnard** [rubygems/rubygems#3875]
### Describe the problem as clearly as you can

When I execute the bundle command, everything goes well until I run into the following error:
```
/usr/local/lib/ruby/site_ruby/2.7.0/bundler.rb:513:in `expand_path': user . doesn't exist (ArgumentError)
```
### Post system independent steps to reproduce the problem

I just execute the 'bundle command'

### Which command did you run?

bundle

### What were you expecting to happen?

The necessary gem files to be created I suppose

### What actually happened?

I received this error

### If not included with the output of your command, run `bundle env` and paste the output below
```
Traceback (most recent call last):
	23: from /Users/z0021lt/.gem/ruby/2.7.0/bin/bundle:23:in `<main>'
	22: from /Users/z0021lt/.gem/ruby/2.7.0/bin/bundle:23:in `load'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/cli.rb:650:in `env'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/env.rb:9:in `write'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/env.rb:17:in `report'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/env.rb:115:in `environment'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/env.rb:78:in `git_version'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/env.rb:78:in `new'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler/source/git/git_proxy.rb:57:in `initialize'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler.rb:474:in `git_present?'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler.rb:397:in `which'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler.rb:397:in `find'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler.rb:397:in `each'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler.rb:399:in `block in which'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.0.2/lib/bundler.rb:399:in `expand_path': user . doesn't exist (ArgumentError)
```

**Comment by colby-swandale** [comment]
Can you please share the output of `bundle env`?

**Comment by deivid-rodriguez** [comment]
Also, could you try with bundler 2.1.4?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
