### ISSUE TITLE
Executing any bundler command fails

### ISSUE THREAD

**Issue by mehagar** [rubygems/rubygems#3880]
### Describe the problem as clearly as you can

I cannot run any bundler commands. I get the same stack trace every time I run any bundler command. [Here](https://gist.github.com/mehagar/3a073bfc4d511389b40b2f8bd10a486f) is a gist that shows my Gemfile, and ruby, rvm, and RubyGems versions.

### Post system independent steps to reproduce the problem

1. Create a new Rails app. 
2. Use `gem install bundler` to install bundler.
2. Run `bundle install`.

### Which command did you run?

`bundle --version`

### What were you expecting to happen?

The bundler version to be reported.

### What actually happened?

```
Traceback (most recent call last):
	12: from /Users/michaelhagar/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
	11: from /Users/michaelhagar/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
	10: from /Users/michaelhagar/.rvm/gems/ruby-2.7.1/bin/bundle:23:in `<main>'
	 9: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `activate_bin_path'
	 8: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `synchronize'
	 7: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems.rb:306:in `block in activate_bin_path'
	 6: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems.rb:243:in `finish_resolve'
	 5: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:435:in `resolve_current'
	 4: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:435:in `new'
	 3: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/resolver/set.rb:24:in `initialize'
	 2: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:42:in `require'
	 1: from /Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
/Users/michaelhagar/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize': deadlock; recursive locking (ThreadError)
```

### If not included with the output of your command, run `bundle env` and paste the output below

`bundle env` produces the same output as above.

**Comment by hsbt** [comment]
@mehagar Can you reproduce it without RVM?

**Comment by mehagar** [comment]
I reinstalled 2.7.1 through RVM and it works now. I will close this.
