### ISSUE TITLE
Latest RC bundled with ruby3.0 (trunk) raises exception on `gem outdated`

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#3920]
probably just missing the `require "fileutils"`

```
9960 % gem30 --version
3.2.0.rc.1
```
```
9961 % gem30 --debug outdated
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `NameError' at /Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/source.rb:182 - uninitialized constant Gem::Source::FileUtils
Did you mean?  FileTest
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Source::FileUtils
Did you mean?  FileTest
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/source.rb:182:in `load_specs'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/spec_fetcher.rb:256:in `tuples_for'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/spec_fetcher.rb:222:in `block in available_specs'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/source_list.rb:98:in `each'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/source_list.rb:98:in `each_source'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/spec_fetcher.rb:216:in `available_specs'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/spec_fetcher.rb:90:in `search_for_dependency'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/specification.rb:1190:in `block in outdated_and_latest_version'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/specification.rb:1186:in `each'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/specification.rb:1186:in `outdated_and_latest_version'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/commands/outdated_command.rb:28:in `each'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/commands/outdated_command.rb:28:in `execute'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/command_manager.rb:177:in `process_args'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/command_manager.rb:147:in `run'
	/Users/ryan/.rubies/ruby-3.0/lib/ruby/3.0.0/rubygems/gem_runner.rb:53:in `run'
	/Users/ryan/.rubies/ruby-3.0/bin/gem:21:in `<main>'
```

**Comment by hsbt** [comment]
It was fixed at https://github.com/rubygems/rubygems/pull/3911
