### ISSUE TITLE
bundle exec rspec error...  expand_path': can't find user 22% (ArgumentError)

### ISSUE THREAD

**Issue by garymdurante** [rubygems/rubygems#3941]
Hi there, don't know if this is the right place to ask help, but I hope someone will.

For a few months whenever I type 'bundle exec rspec' all goes well, until recent days... though there are times it just works, but mostly I got errors. Haven't figure out what to do, so pls help.

```
$ bundle exec rspec
Traceback (most recent call last):
        17: from C:/Ruby26-x64/bin/bundle:23:in `<main>'
        16: from C:/Ruby26-x64/bin/bundle:23:in `load'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_n `with_friendly_errors'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'46:in `block in <top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'          76:in `star/cli.rb:24:in `start'                                                            /vendor/thor/lib/thor/base.rb:4
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'                                     /cli.rb:30:in `dispatch'        `dispatch'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:inr/cli.rb:30:in `dispatch'                                                                                       n.rb:127:in
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocatior/vendor/thor/lib/thor.rb:399:in `dispatch'                                                                     b:27:in `ru
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rr/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'r/vendor/thor/lib/thor/command.rb:27:in `run'                                    /cli/exec.rb:26:in `run'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:501:in `which'r/cli.rb:476:in `exec'                                                           .rb:501:in `find'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:501:in `each'r/cli/exec.rb:26:in `run'                                                        .rb:503:in `block in which'    rgumentErro
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler                         22% (Ar.rb:501:in `which'                                                              d_path': can't find user
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundlerr.rb:501:in `find'                                                                                        e_1>
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundlertions Recap\recap_exercisr.rb:501:in `each'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundlerr.rb:503:in `block in which'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:503:in `expannd_path': can't find user 22% (ArgumentError)
```

**Comment by deivid-rodriguez** [comment]
Ugg, that seems like an issue, but quite hard to reproduce since it seems like a change in your environment that trigerred it. It would be helpful for us if you could isolate the error a bit more. Can you reproduce it on a fresh machine? Also, could you copy the error again, it sounds like there's some bad copy-pasting in there (please surround it with triple backquotes lines before and after so it's more readable).

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback, feel free to reopen if you're still running into this issue and want to help us out reproducing it!
