### ISSUE TITLE
rubygems buildroot feature not working correctly anymore.

### ISSUE THREAD

**Issue by darix** [rubygems/rubygems#3971]
The plugin directory should be prefixed with the buildroot directory in this case.

## stack trace

```
/usr/bin/gem.ruby3.0 install \
  --verbose \
  --local \
  --build-root /home/abuild/rpmbuild/BUILDROOT/rubygem-gem2rpm-0.10.1-0.x86_64 -f \
  --no-document gem2rpm-0.10.1/gem2rpm-0.10.1.gem
WARNING:  You build with buildroot.
  Build root: /home/abuild/rpmbuild/BUILDROOT/rubygem-gem2rpm-0.10.1-0.x86_64
  Bin dir: /home/abuild/rpmbuild/BUILDROOT/rubygem-gem2rpm-0.10.1-0.x86_64/usr/bin
  Gem home: /home/abuild/rpmbuild/BUILDROOT/rubygem-gem2rpm-0.10.1-0.x86_64/usr/lib64/ruby/gems/3.0.0
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/lib64/ruby/gems/3.0.0/plugins directory.
/usr/lib64/ruby/3.0.0/rubygems/installer.rb:959:in `ensure_writable_dir'
/usr/lib64/ruby/3.0.0/rubygems/installer.rb:511:in `generate_plugins'
/usr/lib64/ruby/3.0.0/rubygems/installer.rb:319:in `install'
/usr/lib64/ruby/3.0.0/rubygems/resolver/specification.rb:92:in `install'
/usr/lib64/ruby/3.0.0/rubygems/request_set.rb:194:in `block in install'
/usr/lib64/ruby/3.0.0/rubygems/request_set.rb:182:in `each'
/usr/lib64/ruby/3.0.0/rubygems/request_set.rb:182:in `install'
/usr/lib64/ruby/3.0.0/rubygems/commands/install_command.rb:207:in `install_gem'
/usr/lib64/ruby/3.0.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
/usr/lib64/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `each'
/usr/lib64/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `install_gems'
/usr/lib64/ruby/3.0.0/rubygems/commands/install_command.rb:164:in `execute'
/usr/lib64/ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
/usr/lib64/ruby/3.0.0/rubygems/command_manager.rb:177:in `process_args'
/usr/lib64/ruby/3.0.0/rubygems/command_manager.rb:147:in `run'
/usr/lib64/ruby/3.0.0/rubygems/gem_runner.rb:53:in `run'
/usr/bin/gem.ruby3.0:21:in `<main>'
```

```
$ gem env version
/usr/bin/gem.ruby3.0 env 
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.0.rc.1
  - RUBY VERSION: 3.0.0 (2020-09-25 patchlevel -1) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /usr/lib64/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /home/abuild/.local/share/gem/ruby/3.0.0
  - RUBY EXECUTABLE: /usr/bin/ruby.ruby3.0
  - GIT EXECUTABLE: 
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/abuild/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/lib64/ruby/gems/3.0.0
     - /home/abuild/.local/share/gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - :benchmark => false
     - :install => "--format-executable --no-user-install"
     - "install" => "--format-executable --no-user-install"
     - :format_executable => true
     - :update => "--format-executable --no-user-install"
     - "update" => "--format-executable --no-user-install"
     - :sources => ["https://rubygems.org"]
  - REMOTE SOURCES:
     - https://rubygems.org
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thanks, another regression of the introduction of the new plugin layout. I'll fix it now.

**Comment by deivid-rodriguez** [comment]
@darix Could you verify that the changes in #3972 fix your issue?

**Comment by darix** [comment]
confirmed

**Comment by deivid-rodriguez** [comment]
@darix I found another bug which I fixed separately, so the patch diverged a bit from the original one.

I don't really don't think I introduced a regression so re-testing this shouldn't be necessary. but in case you want to try it again just in case, the current diff is the one that I plan to merge.
