### ISSUE TITLE
Some test failures with ruby2.7.2 & ruby3.0~preview1

### ISSUE THREAD

**Issue by utkarsh2102** [rubygems/rubygems#4000]
Hello 👋🏻 

Whilst trying to build ruby2.7.2 in Debian, the autopkgtest fails. The failing tests are as follows:
Autopkgtest is a test suite where the tests are run in isolation (stripping away the `lib` or other parts) so the tests are run againsted the installed packages, i.e., closer to how an end-user would use it than to how a developer working against it.

---

Here are the failing tests with ruby2.7.2:
```
 1) Failure:
TestStubSpecification#test_to_spec_activated [/tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_stub_specification.rb:185]:
Failed assertion, no message given.
  2) Error:
TestGemCommandsBuildCommand#test_execute_rubyforge_project_warning:
Gem::MockGemUi::TermError: 1
    /usr/lib/ruby/2.7.0/rubygems/mock_gem_ui.rb:87:in `terminate_interaction'
    /usr/lib/ruby/2.7.0/rubygems/user_interaction.rb:160:in `terminate_interaction'
    /usr/lib/ruby/2.7.0/rubygems/commands/build_command.rb:94:in `build_gem'
    /usr/lib/ruby/2.7.0/rubygems/commands/build_command.rb:61:in `execute'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_commands_build_command.rb:132:in `block (2 levels) in test_execute_rubyforge_project_warning'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_commands_build_command.rb:131:in `chdir'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_commands_build_command.rb:131:in `block in test_execute_rubyforge_project_warning'
    /usr/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
    /usr/lib/ruby/2.7.0/rubygems/user_interaction.rb:70:in `use_ui'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_commands_build_command.rb:130:in `test_execute_rubyforge_project_warning'
  3) Error:
TestStubSpecification#test_to_spec_with_other_specs_loaded_does_not_warn:
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/lib/ruby/test/rubygems/specifications/foo-0.0.1-x86-mswin32.gemspec
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `initialize'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `open'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `data'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:158:in `name'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_stub_specification.rb:177:in `test_to_spec_with_other_specs_loaded_does_not_warn'
  4) Error:
TestStubSpecification#test_missing_extensions_eh_none:
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/lib/ruby/test/rubygems/specifications/foo-0.0.1-x86-mswin32.gemspec
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `initialize'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `open'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `data'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:172:in `extensions'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:148:in `missing_extensions?'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_stub_specification.rb:163:in `test_missing_extensions_eh_none'
  5) Error:
TestStubSpecification#test_initialize_missing_stubline:
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/lib/ruby/test/rubygems/specifications/bar-0.0.2.gemspec
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `initialize'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `open'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `data'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:158:in `name'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_stub_specification.rb:52:in `test_initialize_missing_stubline'
  6) Error:
TestStubSpecification#test_initialize:
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/lib/ruby/test/rubygems/specifications/foo-0.0.1-x86-mswin32.gemspec
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `initialize'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `open'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `data'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:158:in `name'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_stub_specification.rb:19:in `test_initialize'
  7) Error:
TestStubSpecification#test_to_spec:
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/lib/ruby/test/rubygems/specifications/foo-0.0.1-x86-mswin32.gemspec
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `initialize'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `open'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:116:in `data'
    /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb:158:in `name'
    /tmp/autopkgtest-lxc.hhpb_xn_/downtmp/autopkgtest_tmp/test/rubygems/test_gem_stub_specification.rb:167:in `test_to_spec'
Finished tests in 396.192352s, 48.4260 tests/s, 6778.7957 assertions/s.
19186 tests, 2685707 assertions, 1 failures, 6 errors, 64 skips
```

Full logs for ruby2.7.2 autopkgtest failures can be seen here: https://salsa.debian.org/ruby-team/ruby/-/jobs/1050348

**Comment by deivid-rodriguez** [comment]
I had a quick look at the involved code, and I found the following code, which is the kind of thing you don't like in Debian :sweat_smile: 

https://github.com/rubygems/rubygems/blob/8b50ccfe7b7127ca5811ba37eb2ac5f31ef99657/lib/rubygems/test_case.rb#L110

Maybe it gives you some clues on how to fix it :)

**Comment by deivid-rodriguez** [comment]
I made a "blind guess" at #4001. Can you verify whether it fixes the issue?

**Comment by utkarsh2102** [comment]
Wow, aren't ya amazing? It fixed all these issues! ❤️

**Comment by utkarsh2102** [comment]
Oh hey,

All the issues with 2.7.2 are fixed, but some are still failing with 3.0~preview1. They are:
```
 1) Failure:
TestBundledCA#test_accessing_fastly [/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_bundled_ca.rb:55]:
rubygems.global.ssl.fastly.net is not verifiable using the included certificates. Error was: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
  2) Failure:
TestBundledCA#test_accessing_new_index [/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_bundled_ca.rb:59]:
fastly.rubygems.org is not verifiable using the included certificates. Error was: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
  3) Failure:
TestBundledCA#test_accessing_rubygems [/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_bundled_ca.rb:51]:
rubygems.org is not verifiable using the included certificates. Error was: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
  4) Failure:
TestGemRequire#test_realworld_upgraded_default_gem [/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_require.rb:503]:
--- expected
+++ actual
@@ -1 +1 @@
-["/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/json-999.99.9/lib/json.rb"]
+[]
  5) Error:
TestGemInstaller#test_generate_plugins:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    current directory: /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-2/ext/a
/usr/bin/ruby3.0 mkrf_conf.rb
current directory: /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-2/ext/a
/usr/bin/ruby3.0 /usr/lib/ruby/test/rubygems/good_rake.rb RUBYARCHDIR\=/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/extensions/x86-darwin-8/3.0.0-static/a-2 RUBYLIBDIR\=/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/extensions/x86-darwin-8/3.0.0-static/a-2
/usr/bin/ruby3.0: No such file or directory -- /usr/lib/ruby/test/rubygems/good_rake.rb (LoadError)
rake failed, exit code 1
Gem files will remain installed in /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-2 for inspection.
Results logged to /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/extensions/x86-darwin-8/3.0.0-static/a-2/gem_make.out
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:98:in `run'
    /usr/lib/ruby/3.0.0/rubygems/ext/rake_builder.rb:29:in `build'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:168:in `block in build_extension'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:164:in `synchronize'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:164:in `build_extension'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:209:in `block in build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:206:in `each'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:206:in `build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/installer.rb:839:in `build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/installer.rb:313:in `install'
    /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_gem_installer.rb:748:in `block in test_generate_plugins'
    /usr/lib/ruby/3.0.0/rubygems/test_case.rb:1217:in `build_rake_in'
    /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_gem_installer.rb:747:in `test_generate_plugins'
  6) Error:
TestGemInstaller#test_keeps_plugins_up_to_date:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    current directory: /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-1/ext/a
/usr/bin/ruby3.0 mkrf_conf.rb
current directory: /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-1/ext/a
/usr/bin/ruby3.0 /usr/lib/ruby/test/rubygems/good_rake.rb RUBYARCHDIR\=/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/extensions/x86-darwin-8/3.0.0-static/a-1 RUBYLIBDIR\=/tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/extensions/x86-darwin-8/3.0.0-static/a-1
/usr/bin/ruby3.0: No such file or directory -- /usr/lib/ruby/test/rubygems/good_rake.rb (LoadError)
rake failed, exit code 1
Gem files will remain installed in /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-1 for inspection.
Results logged to /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/extensions/x86-darwin-8/3.0.0-static/a-1/gem_make.out
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:98:in `run'
    /usr/lib/ruby/3.0.0/rubygems/ext/rake_builder.rb:29:in `build'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:168:in `block in build_extension'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:164:in `synchronize'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:164:in `build_extension'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:209:in `block in build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:206:in `each'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:206:in `build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/installer.rb:839:in `build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/installer.rb:313:in `install'
    /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_gem_installer.rb:812:in `block in test_keeps_plugins_up_to_date'
    /usr/lib/ruby/3.0.0/rubygems/test_case.rb:1217:in `build_rake_in'
    /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_gem_installer.rb:808:in `test_keeps_plugins_up_to_date'
  7) Error:
TestGemRequire#test_dash_i_respects_default_library_extension_priority:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    current directory: /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-2
/usr/bin/ruby3.0 -I /usr/lib/ruby/3.0.0 -r ./siteconf20201006-4073-me2s7s.rb extconf.rb
creating Makefile
current directory: /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-2
make "DESTDIR=" clean
current directory: /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-2
make "DESTDIR="
compiling a.c
make: gcc: No such file or directory
make: *** [Makefile:245: a.o] Error 127
make failed, exit code 2
Gem files will remain installed in /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/gems/a-2 for inspection.
Results logged to /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/tmp/test_rubygems_4073/gemhome/extensions/x86-darwin-8/3.0.0-static/a-2/gem_make.out
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:98:in `run'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:50:in `block in make'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:42:in `each'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:42:in `make'
    /usr/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:61:in `block in build'
    /usr/lib/ruby/3.0.0/tempfile.rb:298:in `open'
    /usr/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:168:in `block in build_extension'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:164:in `synchronize'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:164:in `build_extension'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:209:in `block in build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:206:in `each'
    /usr/lib/ruby/3.0.0/rubygems/ext/builder.rb:206:in `build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/installer.rb:839:in `build_extensions'
    /usr/lib/ruby/3.0.0/rubygems/installer.rb:313:in `install'
    /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_require.rb:719:in `util_install_extension_file'
    /tmp/autopkgtest-lxc.l6ds2ra7/downtmp/autopkgtest_tmp/test/rubygems/test_require.rb:153:in `test_dash_i_respects_default_library_extension_priority'
Finished tests in 451.020782s, 41.3041 tests/s, 5798.7838 assertions/s.
18629 tests, 2615372 assertions, 4 failures, 3 errors, 63 skips
```

Full logs here: https://salsa.debian.org/ruby-team/ruby/-/jobs/1053643#L8136

**Comment by utkarsh2102** [comment]
Aah, I know a fix for some of them. That is Debian specific. Edited the failures above to remove the first 3. Only the final 4 remain now.

**Comment by utkarsh2102** [comment]
Just found out that there are 3 more Debian specific, the ones that involve building gem native extension. So only 1 remians. Edited the issue again 😅

**Comment by deivid-rodriguez** [comment]
That one sounds like a test assertion being too specific. Can you try this diff to debug and see the actual output:

```diff
diff --git a/test/rubygems/test_require.rb b/test/rubygems/test_require.rb
index 70242a1f3c..2e1add40de 100644
--- a/test/rubygems/test_require.rb
+++ b/test/rubygems/test_require.rb
@@ -500,7 +500,7 @@ def test_realworld_upgraded_default_gem
     refute_empty output
     assert_equal "999.99.9", output.lines[0].chomp
     # Make sure only files from the newer json gem are loaded, and no files from the default json gem
-    assert_equal ["#{@gemhome}/gems/json-999.99.9/lib/json.rb"], output.lines.grep(%r{/gems/json-}).map(&:chomp)
+    assert_equal ["#{@gemhome}/gems/json-999.99.9/lib/json.rb"], output.lines
   end
 
   def test_default_gem_and_normal_gem
```

It will fail for sure, but it will give us useful debug output.

**Comment by deivid-rodriguez** [comment]
Accidental autoclose, let's keep this open until we figure out all the remaining failures.

**Comment by utkarsh2102** [comment]
> That one sounds like a test assertion being too specific. Can you try this diff to debug and see the actual output.

Sure, pushed this diff. I'll let you know the CI output in the next ~30 minutes.

Thanks so much for your help! ❤️

**Comment by utkarsh2102** [comment]
Hey,

> It will fail for sure, but it will give us useful debug output.

Here:
```
 1) Failure:
TestGemRequire#test_realworld_upgraded_default_gem [/tmp/autopkgtest-lxc.u5eyopff/downtmp/autopkgtest_tmp/test/rubygems/test_require.rb:503]:
--- expected
+++ actual
@@ -1 +1,113 @@
-["/tmp/autopkgtest-lxc.u5eyopff/downtmp/autopkgtest_tmp/tmp/test_rubygems_4074/gemhome/gems/json-999.99.9/lib/json.rb"]
+["999.99.9
+",
+ "enumerator.so
+",
+ "thread.rb
+",
+ "rational.so
+",
+ "complex.so
+",
+ "ruby2_keywords.rb
+",
+ "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/enc/encdb.so
+",
+ "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/enc/trans/transdb.so
+",
+ "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/rbconfig.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/compatibility.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/defaults.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/deprecate.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/errors.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/exceptions.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/basic_specification.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/stub_specification.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/text.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/user_interaction.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/specification_policy.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/util/list.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/platform.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/version.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/requirement.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/specification.rb
+",
+ "/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/util.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/dependency.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_gem.rb
+",
+ "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/monitor.so
+",
+ "/usr/lib/ruby/3.0.0/monitor.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_warn.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/version.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/core_ext/name_error.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/levenshtein.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/jaro_winkler.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/method_name_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/key_error_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/null_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/tree_spell_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/require_path_checker.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean/formatters/plain_formatter.rb
+",
+ "/usr/lib/ruby/3.0.0/did_you_mean.rb
+",
+ "/usr/lib/ruby/3.0.0/json/version.rb
+",
+ "/usr/lib/ruby/3.0.0/ostruct.rb
+",
+ "/usr/lib/ruby/3.0.0/json/generic_object.rb
+",
+ "/usr/lib/ruby/3.0.0/json/common.rb
+",
+ "/usr/lib/ruby/3.0.0/rubygems/path_support.rb
+",
+ "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/json/ext/parser.so
+",
+ "/usr/lib/x86_64-linux-gnu/ruby/3.0.0/json/ext/generator.so
+",
+ "/usr/lib/ruby/3.0.0/json/ext.rb
+",
+ "/usr/lib/ruby/3.0.0/json.rb"]
```

**Comment by deivid-rodriguez** [comment]
The failure looks legit, the default version of the json gem gets used instead of the higher version. One situation where this could happen is if `json` is not a default gem in the environment you're running this test (there's no `json-*.gemspec` file in the `specifications/default` folder). `json` _should_ be a default gem, so this might signal an issue with your `autopkgtest` environemnt.

**Comment by deivid-rodriguez** [comment]
@utkarsh2102 In principle I don't think the last failure is a problem in rubygems, so I'd lean towards closing this. If you want to dig in further as per why json is not a default gem in your environment, I'm happy to help though.

**Comment by utkarsh2102** [comment]
Hello,

> In principle I don't think the last failure is a problem in rubygems, so I'd lean towards closing this.

Indeed! I'll close it right away! 

> If you want to dig in further as per why json is not a default gem in your environment, I'm happy to help though.

That'd be great, thanks!
However, I suspect that there's something wrong **just** with the `autopkgtest` way of running this test. So I'll keep this test disabled just for autopkgtest and run this at other places and architectures to see if it fails there the same way or not.

In case I do, I'll be happy to come back here with hopefully some more details and some sane way of reproducing on Debian machines.


Thank you so much for your help! 🛐
