### ISSUE TITLE
No such file or directory error while installing dependencies in Docker

### ISSUE THREAD

**Issue by glebsonik** [rubygems/rubygems#4187]
I tried to install gems with Bundler in Docker container using a bash script inside of CircleCI configuration file. Usually it works perfectly fine, but since yesterday in about 5% of containers installation fails (average number of concurrent containers is 60). I tried to use previous release (2.1.4), and it worked just as expected.
## Backtrace

```
Errno::ENOENT: No such file or directory @ realpath_rec - /usr/local/bundle/gems/debase-ruby_core_source-0.10.11/lib
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:485:in `realpath'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:485:in `block in mkdir_p_safe'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:484:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:484:in `reduce'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:484:in `mkdir_p_safe'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:406:in `block (2 levels) in extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:389:in `block in extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:522:in `block in open_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:519:in `wrap'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:519:in `open_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:388:in `extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:368:in `block (2 levels) in extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:365:in `block in extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `open'
  /usr/local/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:362:in `extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/installer.rb:851:in `extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/installer.rb:318:in `install'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/source/rubygems.rb:158:in `install'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/installer/gem_installer.rb:67:in `install'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/installer/parallel_installer.rb:163:in `do_install'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/installer/parallel_installer.rb:154:in `block in worker_pool'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/worker.rb:54:in `loop'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/bundle/gems/bundler-2.2.2/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.2
  Platforms   ruby, x86_64-linux
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.0.3
  Gem Home    /usr/local/bundle
  Gem Path    /home/circleci/.gem/ruby/2.6.0:/usr/local/lib/ruby/gems/2.6.0:/usr/local/bundle
  User Home   /home/circleci
  User Path   /home/circleci/.gem/ruby/2.6.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1d  10 Sep 2019
  Loaded      OpenSSL 1.1.1d  10 Sep 2019
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.20.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-17
Git SHA           d85cd5b7c3
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake'

group :test do
  gem 'bundler'
  gem 'allure-cucumber', '~> 2.13.4'
  gem 'allure-ruby-commons'
  gem 'allure-rspec'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber', '~> 3.1', '>= 3.1.2'
  gem 'gherkin', '5.1.0'
  gem 'debase'
  gem 'httparty'
  gem 'parallel_tests'
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'rspec-steps'
  gem 'rubocop'
  gem 'ruby-debug-ide'
  gem 'selenium-webdriver'
  gem 'single_test'
  gem 'syntax'
  gem 'true_automation'
  gem 'webdrivers', '~> 3.0'
  gem 'mail'
  gem 'nokogiri'
  gem 'testrail-ruby'
end
```

### Gemfile.lock

```
<No /home/circleci/mw-automation-framework/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
@glebsonik I think the reason for this is that on bundler 2.2 we enabled parallel installation by default, but old rubygems installer versions used to not be thread safe. If this is the culprit, you should be able to fix it by upgrading rubygems `gem update --system`, or by running bundle install with a single job (`bundle install --jobs 1`).

**Comment by glebsonik** [comment]
@deivid-rodriguez This was totally the case, thanks. Several hundred of installations performed without any issues.

**Comment by deivid-rodriguez** [comment]
Great! I'll look into restoring the old default for installations running old rubygems. Just curious, which workaround did you use?

**Comment by glebsonik** [comment]
Actually, we didn't use any workarounds for current version. As a part of our investigation, we added random wait for every container, so threads did not conflict with each other and it worked! Then we switched to a previous version to see if it is exactly a Bundler issue and it helped as well

**Comment by deivid-rodriguez** [comment]
Aaaah I see.

**Comment by deivid-rodriguez** [comment]
Would you be able to verify if upgrading rubygems also fixes the issue? I'd like to make sure that the culprit lies in rubygems, not bundler.

**Comment by glebsonik** [comment]
Unfortunately, updating rubygems did not resolve the issue.

**Comment by deivid-rodriguez** [comment]
That's too bad, thanks for trying.

Could you post an updated backtrace of the error?

**Comment by glebsonik** [comment]
Of course, here you go

## Backtrace

```
Errno::ENOENT: No such file or directory @ realpath_rec - /usr/local/bundle/gems/debase-ruby_core_source-0.10.11/lib/debase
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:485:in `realpath'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:485:in `block in mkdir_p_safe'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:484:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:484:in `reduce'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:484:in `mkdir_p_safe'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:406:in `block (2 levels) in extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:389:in `block in extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:522:in `block in open_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:519:in `wrap'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:519:in `open_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:388:in `extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:368:in `block (2 levels) in extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:365:in `block in extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `open'
  /usr/local/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:362:in `extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/installer.rb:851:in `extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/installer.rb:318:in `install'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/source/rubygems.rb:158:in `install'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/installer/gem_installer.rb:67:in `install'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/installer/parallel_installer.rb:163:in `do_install'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/installer/parallel_installer.rb:154:in `block in worker_pool'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/worker.rb:54:in `loop'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/bundle/gems/bundler-2.2.3/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.3
  Platforms   ruby, x86_64-linux
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.0.3
  Gem Home    /usr/local/bundle
  Gem Path    /home/circleci/.gem/ruby/2.6.0:/usr/local/lib/ruby/gems/2.6.0:/usr/local/bundle
  User Home   /home/circleci
  User Path   /home/circleci/.gem/ruby/2.6.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1d  10 Sep 2019
  Loaded      OpenSSL 1.1.1d  10 Sep 2019
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.20.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-22
Git SHA           29dc3c8398
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

## Gemfile

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake'

group :test do
  gem 'bundler'
  gem 'allure-cucumber', '~> 2.13.4'
  gem 'allure-ruby-commons'
  gem 'allure-rspec'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber', '~> 3.1', '>= 3.1.2'
  gem 'gherkin', '5.1.0'
  gem 'debase'
  gem 'httparty'
  gem 'parallel_tests'
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'rspec-steps'
  gem 'rubocop'
  gem 'ruby-debug-ide'
  gem 'selenium-webdriver'
  gem 'single_test'
  gem 'syntax'
  gem 'true_automation'
  gem 'webdrivers', '~> 3.0'
  gem 'mail'
  gem 'nokogiri'
  gem 'testrail-ruby'
end
```

### Gemfile.lock

```
<No /home/circleci/mw-automation-framework/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
It says rubygems 3.0.3, but it should say 3.2.3, is it correct?

**Comment by Syntaf** [comment]
👋 dropping in to note that I also ran into this same issue though my specific error was

```
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /usr/local/bundle/gems/debase-0.2.4.1/test/example
```

Full backtrace output (formatted as markdown): https://gist.github.com/Syntaf/7dc04f1b58f73188c58907aedb389089

Changing my Dockerfile to use a single job fixed this issue, but it was quite confusing debugging this issue I'll say lol.

```
RUN bundle install --jobs 1
```

**Comment by deivid-rodriguez** [comment]
Thanks for the confirmation @Syntaf!

Sin I can't repro this error, can you help me out figure it out? Do you get the issue all the time or just randomly? Does the issue get also fixed if you upgrade rubygems? Finally, could you edit bundler's code at the exact line that it's causing the error and add a debug print that shows the CWD when the error happens? Something like `puts "CWD: #{Dir.pwd}"` would do the trick.

Thanks!

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by kjg** [comment]
I'm running into this same issue. Only within docker as well, and it seems to happen randomly. Sometimes installs work, sometimes they fail with this error.

**Comment by kjg** [comment]
If I'm reading this right

https://github.com/ruby-debug/debase/blob/5780803819f16190ce50ddfdad5775acf8f95fd1/ext/extconf.rb#L28

It looks like the debase gem install process is needing debase-ruby_core_source to be fully installed before it can build itself, so maybe the parallelism is not accounting for that, or the debase install process is not accounting for it.
