### ISSUE TITLE
Flaky test failure

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4258]
### Describe the problem as clearly as you can

We have this recurring [flaky failure](https://github.com/rubygems/rubygems/pull/4257/checks?check_run_id=1665069101):

```
1) [TEST_ENV_NUMBER=1] bundle install with install-time dependencies with crazy rubygem plugin stuff with ENV['DEBUG_RESOLVER_TREE'] set produces debug output
   Failure/Error:
             raise <<~ERROR
     
               Invoking `#{cmd}` failed with output:
               ----------------------------------------------------------------------
               #{command_execution.stdboth}
               ----------------------------------------------------------------------
             ERROR

   RuntimeError:

     Invoking `/opt/hostedtoolcache/Ruby/2.7.2/x64/bin/ruby -I/home/runner/work/rubygems/rubygems/bundler/spec -r/home/runner/work/rubygems/rubygems/bundler/spec/support/artifice/fail.rb -r/home/runner/work/rubygems/rubygems/bundler/spec/support/hax.rb /home/runner/work/rubygems/rubygems/bundler/tmp/1/gems/system/bin/bundle install` failed with output:
     ----------------------------------------------------------------------
     Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

         current directory: /home/runner/work/rubygems/rubygems/bundler/tmp/1/bundled_app/.bundle/ruby/2.7.0/gems/net_build_extensions-1.0
     /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/ruby -I/home/runner/work/rubygems/rubygems/lib -rrubygems /home/runner/work/rubygems/rubygems/bundler/tmp/1/bundled_app/.bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake RUBYARCHDIR\=/home/runner/work/rubygems/rubygems/bundler/tmp/1/bundled_app/.bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/net_build_extensions-1.0 RUBYLIBDIR\=/home/runner/work/rubygems/rubygems/bundler/tmp/1/bundled_app/.bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/net_build_extensions-1.0
     can't add a new key into hash during iteration

     Gem files will remain installed in /home/runner/work/rubygems/rubygems/bundler/tmp/1/bundled_app/.bundle/ruby/2.7.0/gems/net_build_extensions-1.0 for inspection.
     Results logged to /home/runner/work/rubygems/rubygems/bundler/tmp/1/bundled_app/.bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/net_build_extensions-1.0/gem_make.out

     An error occurred while installing net_build_extensions (1.0), and Bundler cannot continue.
     Make sure that `gem install net_build_extensions -v '1.0' --source 'file:///home/runner/work/rubygems/rubygems/bundler/tmp/1/gems/remote2/'` succeeds before bundling.

     In Gemfile:
       net_c was resolved to 1.0, which depends on
         net_a was resolved to 1.0, which depends on
           net_build_extensions
     Fetching source index from file:///home/runner/work/rubygems/rubygems/bundler/tmp/1/gems/remote2/
     BUNDLER: Starting resolution (2021-01-07 21:09:58 +0000)
     BUNDLER: User-requested dependencies: [#<Bundler::DepProxy:0x000055ae7bf56db8 @dep=<Bundler::Dependency type=:runtime name="net_c" requirements=">= 0">, @__platform=#<Gem::Platform:0x000055ae7b092700 @cpu="x86_64", @os="linux", @version=nil @cpu="x86_64", @os="linux", @version=nil>, @hash=622734959398048831>, #<Bundler::DepProxy:0x000055ae7bf56c00 @dep=<Bundler::Dependency type=:runtime name="net_e" requirements=">= 0">, @__platform=#<Gem::Platform:0x000055ae7b092700 @cpu="x86_64", @os="linux", @version=nil @cpu="x86_64", @os="linux", @version=nil>, @hash=-3477165953896721376>, #<Bundler::DepProxy:0x000055ae7bf56a48 @dep=<Bundler::Dependency type=:runtime name="Ruby\u0000" requirements=">= 0">, @__platform=#<Gem::Platform:0x000055ae7b092700 @cpu="x86_64", @os="linux", @version=nil @cpu="x86_64", @os="linux", @version=nil>, @hash=4108630079242120293>, #<Bundler::DepProxy:0x000055ae7bf56890 @dep=<Bundler::Dependency type=:runtime name="RubyGems\u0000" requirements="= 3.3.0.dev" prerelease=ok>, @__platform=#<Gem::Platform:0x000055ae7b092700 @cpu="x86_64", @os="linux", @version=nil @cpu="x86_64", @os="linux", @version=nil>, @hash=2285693375703755291>]
     Resolving dependencies...
     BUNDLER: Creating possibility state for net_c x86_64-linux (1 remaining)
     BUNDLER:   Attempting to activate [net_c (1.0) (x86_64-linux)]
     BUNDLER:   Activated net_c at [net_c (1.0) (x86_64-linux)]
     BUNDLER:   Requiring nested dependencies (net_a x86_64-linux, net_d x86_64-linux)
     BUNDLER:   Creating possibility state for net_e x86_64-linux (1 remaining)
     BUNDLER:     Attempting to activate [net_e (1.0) (x86_64-linux)]
     BUNDLER:     Activated net_e at [net_e (1.0) (x86_64-linux)]
     BUNDLER:     Requiring nested dependencies (net_d x86_64-linux)
     BUNDLER:     Creating possibility state for Ruby� x86_64-linux (1 remaining)
     BUNDLER:       Attempting to activate [Ruby� (2.7.2.137) (x86_64-linux)]
     BUNDLER:       Activated Ruby� at [Ruby� (2.7.2.137) (x86_64-linux)]
     BUNDLER:       Requiring nested dependencies ()
     BUNDLER:       Creating possibility state for RubyGems� (= 3.3.0.dev) x86_64-linux (1 remaining)
     BUNDLER:         Attempting to activate [RubyGems� (3.3.0.dev) (x86_64-linux)]
     BUNDLER:         Activated RubyGems� at [RubyGems� (3.3.0.dev) (x86_64-linux)]
     BUNDLER:         Requiring nested dependencies ()
     BUNDLER:         Creating possibility state for net_a x86_64-linux (1 remaining)
     BUNDLER:           Attempting to activate [net_a (1.0) (x86_64-linux)]
     BUNDLER:           Activated net_a at [net_a (1.0) (x86_64-linux)]
     BUNDLER:           Requiring nested dependencies (net_b x86_64-linux, net_build_extensions x86_64-linux)
     BUNDLER:           Creating possibility state for net_d x86_64-linux (1 remaining)
     BUNDLER:             Attempting to activate [net_d (1.0) (x86_64-linux)]
     BUNDLER:             Activated net_d at [net_d (1.0) (x86_64-linux)]
     BUNDLER:             Requiring nested dependencies ()
     BUNDLER:             Creating possibility state for net_b x86_64-linux (1 remaining)
     BUNDLER:               Attempting to activate [net_b (1.0) (x86_64-linux)]
     BUNDLER:               Activated net_b at [net_b (1.0) (x86_64-linux)]
     BUNDLER:               Requiring nested dependencies ()
     BUNDLER:               Creating possibility state for net_build_extensions x86_64-linux (1 remaining)
     BUNDLER:                 Attempting to activate [net_build_extensions (1.0) (x86_64-linux)]
     BUNDLER:                 Activated net_build_extensions at [net_build_extensions (1.0) (x86_64-linux)]
     BUNDLER:                 Requiring nested dependencies (rake x86_64-linux)
     BUNDLER:                 Creating possibility state for rake x86_64-linux (1 remaining)
     BUNDLER:                   Attempting to activate [rake (13.0.1) (x86_64-linux)]
     BUNDLER:                   Activated rake at [rake (13.0.1) (x86_64-linux)]
     BUNDLER:                   Requiring nested dependencies ()

     BUNDLER: Finished resolution (9 steps) (Took 0.004165305 seconds) (2021-01-07 21:09:58 +0000)
     BUNDLER: Unactivated: 
     BUNDLER: Activated: net_c, net_e, Ruby�, RubyGems�, net_a, net_d, net_b, net_build_extensions, rake
     Fetching rake 13.0.1
     Installing rake 13.0.1
     Fetching net_b 1.0
     Installing net_b 1.0
     Fetching net_build_extensions 1.0
     Installing net_build_extensions 1.0 with native extensions
     Fetching net_d 1.0
     Installing net_d 1.0
     ----------------------------------------------------------------------


     Commands:
     $ gem build net_a
     Successfully built RubyGem
       Name: net_a
       Version: 1.0
       File: net_a-1.0.gem
     WARNING:  open-ended dependency on net_b (>= 0) is not recommended
       use a bounded requirement, such as '~> x.y'
     WARNING:  open-ended dependency on net_build_extensions (>= 0) is not recommended
       use a bounded requirement, such as '~> x.y'
     WARNING:  See https://guides.rubygems.org/specification-reference/ for help
     # $? => 0

     $ gem build net_b
     Successfully built RubyGem
       Name: net_b
       Version: 1.0
       File: net_b-1.0.gem
     # $? => 0

     $ gem build net_build_extensions
     Successfully built RubyGem
       Name: net_build_extensions
       Version: 1.0
       File: net_build_extensions-1.0.gem
     WARNING:  open-ended dependency on rake (>= 0) is not recommended
       use a bounded requirement, such as '~> x.y'
     WARNING:  See https://guides.rubygems.org/specification-reference/ for help
     # $? => 0

     $ gem build net_c
     Successfully built RubyGem
       Name: net_c
       Version: 1.0
       File: net_c-1.0.gem
     WARNING:  open-ended dependency on net_a (>= 0) is not recommended
       use a bounded requirement, such as '~> x.y'
     WARNING:  open-ended dependency on net_d (>= 0) is not recommended
       use a bounded requirement, such as '~> x.y'
     WARNING:  See https://guides.rubygems.org/specification-reference/ for help
     # $? => 0

     $ gem build net_d
     Successfully built RubyGem
       Name: net_d
       Version: 1.0
       File: net_d-1.0.gem
     # $? => 0

     $ gem build net_e
     Successfully built RubyGem
       Name: net_e
       Version: 1.0
       File: net_e-1.0.gem
     WARNING:  open-ended dependency on net_d (>= 0) is not recommended
       use a bounded requirement, such as '~> x.y'
     WARNING:  See https://guides.rubygems.org/specification-reference/ for help
     # $? => 0

     $ gem generate_index
     Generating Marshal quick index gemspecs for 51 gems
     ...................................................
     Complete
     Generated Marshal quick index gemspecs: 0.011s
     Generating specs index
     Generated specs index: 0.001s
     Generating latest specs index
     Generated latest specs index: 0.000s
     Generating prerelease specs index
     Generated prerelease specs index: 0.000s
     Compressing indices
     Compressed indices: 0.000s
     # $? => 0
   # ./spec/support/helpers.rb:206:in `sys_exec'
   # ./spec/support/helpers.rb:123:in `bundle'
   # ./spec/install/gems/resolving_spec.rb:145:in `block (4 levels) in <top (required)>'
   # ./spec/spec_helper.rb:104:in `block (4 levels) in <top (required)>'
   # ./spec/spec_helper.rb:104:in `block (3 levels) in <top (required)>'
   # ./spec/support/helpers.rb:352:in `block in with_gem_path_as'
   # ./spec/support/helpers.rb:366:in `without_env_side_effects'
   # ./spec/support/helpers.rb:348:in `with_gem_path_as'
   # ./spec/spec_helper.rb:103:in `block (2 levels) in <top (required)>'
   # ./spec/spec_helper.rb:75:in `block (2 levels) in <top (required)>'
   # ./spec/support/rubygems_ext.rb:110:in `load'
   # ./spec/support/rubygems_ext.rb:110:in `gem_load_and_activate'
   # ./spec/support/rubygems_ext.rb:18:in `gem_load'
```

It seems some race condition during `bundle install`.
 
### Post steps to reproduce the problem

No steps, it's flaky!

### Which command did you run?

CI.

### What were you expecting to happen?

Green.

### What actually happened?

Red.

**Comment by deivid-rodriguez** [comment]
It happened again: https://github.com/rubygems/rubygems/runs/1680778781.

I have a theory, I'll research on it later today.

**Comment by deivid-rodriguez** [comment]
It hasn't reappeared in almost two months, so closing. I'll reopen if it reappears.
