### ISSUE TITLE
Sometimes `rake release` misdetects the current branch

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4307]
Sorry for the radio silence here. I'm still seeing the error with bundler 2.2.6:

```
$ bundle --version
Bundler version 2.2.6
$ bundle exec rake release
dead_end 1.1.3 built to pkg/dead_end-1.1.3.gem.
Tagged v1.1.3.
Untagging v1.1.3 due to error.
rake aborted!
Running `git config --get branch.module_function.remote` failed. Run this command directly for more detailed output.
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:204:in `sh'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:128:in `default_remote'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:118:in `git_push'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:71:in `block (2 levels) in install'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:174:in `tag_version'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/gem_helper.rb:71:in `block in install'
/Users/rschneeman/.gem/ruby/3.0.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli/exec.rb:63:in `load'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli/exec.rb:28:in `run'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli.rb:494:in `exec'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli.rb:30:in `dispatch'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/cli.rb:24:in `start'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/exe/bundle:49:in `block in <top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/rschneeman/.gem/ruby/3.0.0/gems/bundler-2.2.6/exe/bundle:37:in `<top (required)>'
/Users/rschneeman/.gem/ruby/3.0.0/bin/bundle:23:in `load'
/Users/rschneeman/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => release => release:source_control_push
(See full trace by running task with --trace)
$ git config --get branch.module_function.remote
$ echo $?
1
```

Can we re-open or you want me to make another issue? It's slightly different as it's not the same branch name as the version number.

_Originally posted by @schneems in https://github.com/rubygems/rubygems/issues/4218#issuecomment-764958526_

**Comment by deivid-rodriguez** [comment]
Sorry @schneems :disappointed:.

I'm guessing we're misdetecting your current branch for some reason. What's your current branch, I assume it's not "module_function"?

**Comment by schneems** [comment]
It is named `module_function` in this case as it's a one line fix (https://github.com/zombocom/dead_end/tree/module_function). Note that I updated my bundler version and did a rebase of main but didn't push to github:

```
$ git log
commit cbb8ae8ebe86c08914865d5d768b7e00b70848b5 (HEAD -> module_function, tag: v1.1.3, origin/module_function)
Author: schneems <muhemail@example.com>
Date:   Thu Jan 21 15:38:17 2021 -0600

    Gemfile.lock

commit f64b5784d20d404df2553bd9a7a189bf5f6294b1 (origin/main)
Merge: 320dcfa 61cfa36
Author: Richard Schneeman <muhemail@example.com>
Date:   Thu Jan 21 15:36:05 2021 -0600

    Merge pull request #52 from zombocom/module_function

    Add compatibility with zeitwerk

commit 61cfa36dd802ec62928607575f8150483e507f53
```

Maybe that was weird and is causing the issues. I'm going to see if I can repro the problem with a new gem (with a random name)

**Comment by deivid-rodriguez** [comment]
Oh I get it now. The problem is actually what I suspected initially: https://github.com/rubygems/rubygems/issues/4218#issuecomment-752688856.

Your current branch doesn't have a remote. In that case, I was expecting `git config --get branch.<branch_name>.remote` to return a succesful status and empty output. Instead, it has a failure status.

I'll fix this tommorrow.

**Comment by schneems** [comment]
It might be git config related if it's only on my machine:

```
$ git --version
git version 2.30.0
$ git config --list
credential.helper=osxkeychain
alias.co=checkout
alias.br=branch
alias.ci=commit
alias.st=status
alias.pushf=push --force-with-lease
alias.a=add -p
alias.r=pull --rebase
alias.ro=acab
alias.ru=pull --rebase upstream master
alias.p=push
alias.cam=commit --amend --reuse-message=@
alias.branchd=branch remove
alias.rr=remote remove
push.default=current
credential.helper=osxkeychain
commit.cleanup=scissors
hub.protocol=https
user.email=<email@example.com>
user.name=<schneems>
init.defaultbranch=main
advice.detachedhead=false
includeif.gitdir:~/Documents/projects/work/.path=~/.heroku.gitconfig
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=https://github.com/schneems/c9fb36f7a709d9ddba4bf7da866e2a1-.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
```

**Comment by schneems** [comment]
Oh, great. Thanks for checking!

**Comment by deivid-rodriguez** [comment]
@schneems #4309 should fix this. Give it a try if you can.
