### ISSUE TITLE
Gem::Package::FormatError rake-13.0.3.gem

### ISSUE THREAD

**Issue by jvelez1** [rubygems/rubygems#4361]
### Describe the problem as clearly as you can
 When deploying I'm getting this error on `bundle install` step: 

```
Gem::Package::FormatError: package is corrupt, exception while verifying: wrong number of arguments (given 2, expected 1) (ArgumentError) in /var/www/app_deploy/vendor/bundle/ruby/3.0.0/cache/rake-13.0.3.gem
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:587:in `rescue in verify_entry'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:566:in `verify_entry'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:595:in `block in verify_files'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:594:in `verify_files'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:524:in `block (2 levels) in verify'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/tar_reader.rb:29:in `new'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:521:in `block in verify'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:30:in `open'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:30:in `with_read_io'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:520:in `verify'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:501:in `spec'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/rubygems_integration.rb:252:in `spec_from_gem'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/source/rubygems.rb:124:in `install'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:67:in `install'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:18:in `install_from_spec'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:163:in `do_install'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:148:in `install_serially'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:99:in `call'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:78:in `call'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer.rb:285:in `install_in_parallel'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer.rb:209:in `install'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer.rb:91:in `block in run'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/process_lock.rb:12:in `block in lock'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `open'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `lock'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer.rb:72:in `run'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/installer.rb:24:in `install'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/cli/install.rb:64:in `run'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/cli.rb:262:in `block in install'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/settings.rb:115:in `temporary'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/cli.rb:261:in `install'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/libexec/bundle:49:in `block in <top (required)>'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/libexec/bundle:37:in `<top (required)>'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/bin/bundle:23:in `load'
2021-02-08 11:30:50 [stderr]  /usr/local/rbenv/versions/3.0.0/bin/bundle:23:in `<main>'

```

## Environment
```

2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]```
2021-02-08 11:30:50 [stderr]Bundler       2.2.3
2021-02-08 11:30:50 [stderr]  Platforms   ruby, x86_64-linux
2021-02-08 11:30:50 [stderr]Ruby          3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-linux]
2021-02-08 11:30:50 [stderr]  Full Path   /usr/local/rbenv/versions/3.0.0/bin/ruby
2021-02-08 11:30:50 [stderr]  Config Dir  /usr/local/rbenv/versions/3.0.0/etc
2021-02-08 11:30:50 [stderr]RubyGems      2.6.13
2021-02-08 11:30:50 [stderr]  Gem Home    /var/www/app_deploy/vendor/bundle/ruby/3.0.0
2021-02-08 11:30:50 [stderr]  Gem Path    /var/www/app_deploy/vendor/bundle/ruby/3.0.0
2021-02-08 11:30:50 [stderr]  User Home   /home/deploy
2021-02-08 11:30:50 [stderr]  User Path   /home/deploy/.gem/ruby/3.0.0
2021-02-08 11:30:50 [stderr]  Bin Dir     /var/www/app_deploy/vendor/bundle/ruby/3.0.0/bin
2021-02-08 11:30:50 [stderr]OpenSSL       
2021-02-08 11:30:50 [stderr]  Compiled    OpenSSL 1.1.1d  10 Sep 2019
2021-02-08 11:30:50 [stderr]  Loaded      OpenSSL 1.1.1d  10 Sep 2019
2021-02-08 11:30:50 [stderr]  Cert File   /usr/lib/ssl/cert.pem
2021-02-08 11:30:50 [stderr]  Cert Dir    /usr/lib/ssl/certs
2021-02-08 11:30:50 [stderr]Tools         
2021-02-08 11:30:50 [stderr]  Git         2.20.1
2021-02-08 11:30:50 [stderr]  RVM         not installed
2021-02-08 11:30:50 [stderr]  rbenv       rbenv 1.1.2-40-g62d7798
2021-02-08 11:30:50 [stderr]  chruby      not installed
2021-02-08 11:30:50 [stderr]```
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]## Bundler Build Metadata
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]```
2021-02-08 11:30:50 [stderr]Built At          2021-02-08
2021-02-08 11:30:50 [stderr]Git SHA           unknown
2021-02-08 11:30:50 [stderr]Released Version  false
2021-02-08 11:30:50 [stderr]```
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]## Bundler settings
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]```
2021-02-08 11:30:50 [stderr]path
2021-02-08 11:30:50 [stderr]  Set for your local app (/var/www/app_deploy/.bundle/config): "vendor/bundle"
2021-02-08 11:30:50 [stderr]without
2021-02-08 11:30:50 [stderr]  Set for your local app (/var/www/app_deploy/.bundle/config): [:development, :test]
2021-02-08 11:30:50 [stderr]```
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]## Gemfile
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]### Gemfile
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]```ruby
2021-02-08 11:30:50 [stderr]# frozen_string_literal: true
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]source 'https://rubygems.org'
2021-02-08 11:30:50 [stderr]git_source(:github) { |repo| "https://github.com/#{repo}.git" }
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]ruby '3.0.0'
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]gem 'active_storage_validations', '~> 0.9.2'
2021-02-08 11:30:50 [stderr]gem 'bcrypt', '~> 3.1.7'
2021-02-08 11:30:50 [stderr]gem 'bootsnap', '>= 1.4.4', require: false
2021-02-08 11:30:50 [stderr]gem 'devise', '~> 4.7', '>= 4.7.3'
2021-02-08 11:30:50 [stderr]gem 'devise-jwt', '~> 0.8.0'
2021-02-08 11:30:50 [stderr]gem 'dotenv-rails', '~> 2.7', '>= 2.7.6'
2021-02-08 11:30:50 [stderr]gem 'jbuilder', '~> 2.7'
2021-02-08 11:30:50 [stderr]gem 'mini_magick', '~> 4.11'
2021-02-08 11:30:50 [stderr]gem 'mysql2', '~> 0.5'
2021-02-08 11:30:50 [stderr]gem 'newrelic_rpm', '~> 6.15'
2021-02-08 11:30:50 [stderr]gem 'pagy', '~> 3.10'
2021-02-08 11:30:50 [stderr]gem 'puma', '~> 5.0'
2021-02-08 11:30:50 [stderr]gem 'rack-cors', '~> 1.1', '>= 1.1.1'
2021-02-08 11:30:50 [stderr]gem 'rails', '~> 6.1.1'
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]group :development, :test do
2021-02-08 11:30:50 [stderr]  gem 'awesome_print', '~> 1.8'
2021-02-08 11:30:50 [stderr]  gem 'byebug', platforms: %i(mri mingw x64_mingw)
2021-02-08 11:30:50 [stderr]  gem 'database_cleaner', '~> 1.8', '>= 1.8.5'
2021-02-08 11:30:50 [stderr]  gem 'factory_bot_rails', '~> 6.1'
2021-02-08 11:30:50 [stderr]  gem 'ffaker', '~> 2.17'
2021-02-08 11:30:50 [stderr]  gem 'rspec-rails', '~> 4.0', '>= 4.0.2'
2021-02-08 11:30:50 [stderr]  gem 'rubocop', '~> 1.8', '>= 1.8.1'
2021-02-08 11:30:50 [stderr]  gem 'rubocop-performance', '~> 1.9', '>= 1.9.2'
2021-02-08 11:30:50 [stderr]  gem 'rubocop-rails', '~> 2.9', '>= 2.9.1'
2021-02-08 11:30:50 [stderr]  gem 'rubocop-rspec', '~> 2.1'
2021-02-08 11:30:50 [stderr]  gem 'rubocop-thread_safety', '~> 0.4.2'
2021-02-08 11:30:50 [stderr]  gem 'shoulda-matchers', '~> 4.5'
2021-02-08 11:30:50 [stderr]  gem 'simplecov', '~> 0.21.2', require: false
2021-02-08 11:30:50 [stderr]end
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]group :development do
2021-02-08 11:30:50 [stderr]  gem 'listen', '~> 3.3'
2021-02-08 11:30:50 [stderr]  gem 'spring'
2021-02-08 11:30:50 [stderr]end
2021-02-08 11:30:50 [stderr]gem 'tzinfo-data', platforms: %i(mingw mswin x64_mingw jruby)
2021-02-08 11:30:50 [stderr]```
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]RUBY VERSION
2021-02-08 11:30:50 [stderr]   ruby 3.0.0p0
2021-02-08 11:30:50 [stderr]
2021-02-08 11:30:50 [stderr]BUNDLED WITH
2021-02-08 11:30:50 [stderr]   2.2.3
2021-02-08 11:30:50 [stderr]```

```

`vendor/bundle` currently empty (it is a new setup)

# What were you expecting to happen?
- should install the gems

What actually happened?
- returning the error above 

Any idea? 
thanks.

**Comment by simi** [comment]
Seems like old RubyGems (downgraded, Ruby 3.0 is shipped with newer one) are used, can you try with updated RubyGems?

**Comment by jvelez1** [comment]
@simi it looks like that was the reason, was an Incompatibility with the instance, because RubyGems, we decided to use ruby 2.7.2 for now. thank you.
