### ISSUE TITLE
ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered

### ISSUE THREAD

**Issue by rafaelfranca** [rubygems/rubygems#4389]
```
/usr/local/lib/ruby/2.7.0/bundler/version.rb:4: warning: already initialized constant Bundler::VERSION
--
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/version.rb:4: warning: previous definition of VERSION was here
  | /usr/local/lib/ruby/2.7.0/bundler/constants.rb:4: warning: already initialized constant Bundler::WINDOWS
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/constants.rb:4: warning: previous definition of WINDOWS was here
  | /usr/local/lib/ruby/2.7.0/bundler/constants.rb:5: warning: already initialized constant Bundler::FREEBSD
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/constants.rb:5: warning: previous definition of FREEBSD was here
  | /usr/local/lib/ruby/2.7.0/bundler/constants.rb:6: warning: already initialized constant Bundler::NULL
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/constants.rb:6: warning: previous definition of NULL was here
  | /usr/local/lib/ruby/2.7.0/bundler/rubygems_integration.rb:8: warning: already initialized constant Bundler::RubygemsIntegration::EXT_LOCK
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/rubygems_integration.rb:12: warning: previous definition of EXT_LOCK was here
  | /usr/local/lib/ruby/2.7.0/bundler/current_ruby.rb:12: warning: already initialized constant Bundler::CurrentRuby::KNOWN_MINOR_VERSIONS
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/current_ruby.rb:12: warning: previous definition of KNOWN_MINOR_VERSIONS was here
  | /usr/local/lib/ruby/2.7.0/bundler/current_ruby.rb:25: warning: already initialized constant Bundler::CurrentRuby::KNOWN_MAJOR_VERSIONS
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/current_ruby.rb:25: warning: previous definition of KNOWN_MAJOR_VERSIONS was here
  | /usr/local/lib/ruby/2.7.0/bundler/current_ruby.rb:27: warning: already initialized constant Bundler::CurrentRuby::KNOWN_PLATFORMS
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/current_ruby.rb:27: warning: previous definition of KNOWN_PLATFORMS was here
  | /usr/local/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
  | /usr/local/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
  | /usr/local/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
  | /usr/local/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
  | /usr/local/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
  | /usr/local/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
  | /app/.gem/ruby/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
  | rake aborted!
  | ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
  | /app/config/boot.rb:4:in `require'
  | /app/config/boot.rb:4:in `<top (required)>'
  | /app/config/application.rb:2:in `require_relative'
  | /app/config/application.rb:2:in `<top (required)>'
  | /app/Rakefile:6:in `require_relative'
  | /app/Rakefile:6:in `<top (required)>'
```

Rubygems: 3.1.4
Ruby: 2.7.2
Bundler: 2.2.9
Command: `bundler exec rake environment` in a new Rails app

**Comment by deivid-rodriguez** [comment]
I can't repro this @rafaelfranca. Can you provide a repro on docker?

**Comment by rafaelfranca** [comment]
Urgh. True. I also can't reproduce in another linux machine. Let me try to reproduce in the container. Will report back if I can, if not I'll close the issue.

**Comment by deivid-rodriguez** [comment]
@rafaelfranca The same issue was reported at https://github.com/rubygems/rubygems/pull/4403 and upgrading rubygems fixed the issue there, in case that helps you.

**Comment by rafaelfranca** [comment]
Yes it did! Thank you

**Comment by casperisfine** [comment]
> upgrading rubygems fixed the issue there,

Ok, so it fixed it at the time, but now we keep seeing that error even with the most recent bundler / rubygems combo (e.g. `bundler:2.2.13 rubygems:3.2.12 `).

What's even weirder is that we have some apps using the same base image will works and others not. I have no idea wether #4403 was on the good direction, but I think we should re-open this and investigate more.

**Comment by casperisfine** [comment]
I think I figured what's causing this.

For context it's happening as part of our docker image building process, the automated system invoke `bundle exec rake ...`.

On tricky thing though is that `bin/` is in the `PATH`, so in the case of the app I'm currently debugging, `bundle exec rake` actually end up being `bin/bundle exec rake`, because that app somehow has a binstub for `bundler`, and it might be outdated:

```ruby
$ cat bin/bundle 
#!/usr/bin/env ruby
# frozen_string_literal: true
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)
load Gem.bin_path('bundler', 'bundle')
```

If I regenerate a binstub for bundler, I see it now generate a way more complex one with version switching etc.

I'll have to test more to confirm that's it, but this really look like the culprit.

**Comment by deivid-rodriguez** [comment]
Yes, I think that explains things.

The only case that "dummy metadata bundler source" that's causing issues should come into place is when bundler has not been activated as a gem, and the only case I'm aware of that can happen is if you're using a rubygems version that doesn't include https://github.com/rubygems/rubygems/commit/4e306d7bcdee924b8d80ca9db6125aa59ee4e5a3 (2.6.1 or older). Even in that case, we workaround the issue here: https://github.com/rubygems/rubygems/pull/3626.

Since that old rubygems commit precisely introduces `Gem.activate_bin_path` which both finds an executable and activates the corresponding gem as a replacement to `Gem.bin_path` which would only find the executable, the explanation that your binstub is out of date makes sense.

**Comment by deivid-rodriguez** [comment]
I opened https://github.com/rubygems/rubygems/issues/4485 to deprecate `Gem.bin_path`. Closing this!
