### ISSUE TITLE
Flaky test failure on truffleruby

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4415]
I'm having a problem or would like to suggest a feature.

My current problem is that I think we run into a flaky test failure on truffleruby here: https://github.com/rubygems/rubygems/pull/4378/checks?check_run_id=1999614012.

```
  1) Error:
TestGemRequire#test_concurrent_require:
RuntimeError: Index 21 out of bounds for length 21 (ArrayIndexOutOfBoundsException)
	from org.truffleruby.core.array.library.ObjectArrayStore.read(ObjectArrayStore.java:34)
	from org.truffleruby.core.array.library.ObjectArrayStoreGen$ArrayStoreLibraryExports$Cached.read(ObjectArrayStoreGen.java:214)
	from org.truffleruby.core.array.ArrayNodes$MapNode.map(ArrayNodes.java:1462)
	from org.truffleruby.core.array.ArrayNodesFactory$MapNodeFactory$MapNodeGen.execute(ArrayNodesFactory.java:6634)
	from org.truffleruby.builtins.EnumeratorSizeNode.execute(EnumeratorSizeNode.java:57)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:64)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:557)
Translated to internal error
    <internal:core> core/truffle/feature_loader.rb:285:in `map'
    <internal:core> core/truffle/feature_loader.rb:285:in `get_expanded_load_path'
    <internal:core> core/truffle/feature_loader.rb:115:in `find_file'
    <internal:core> core/truffle/feature_loader.rb:115:in `find_feature_or_file'
    <internal:core> core/kernel.rb:229:in `gem_original_require'
    <internal:/home/runner/work/rubygems/rubygems/lib/rubygems/core_ext/kernel_require.rb>:160:in `require'
    /home/runner/work/rubygems/rubygems/test/rubygems/test_require.rb:38:in `assert_require'
    /home/runner/work/rubygems/rubygems/test/rubygems/test_require.rb:177:in `block in test_concurrent_require'
    /home/runner/work/rubygems/rubygems/test/rubygems/test_require.rb:108:in `block in create_sync_thread'
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
It hasn't happened for a long time, so I'm closing this as possibly fixed.
