### ISSUE TITLE
Bundler fails to fetch gems if vendor/cache exists

### ISSUE THREAD

**Issue by jasonkarns** [rubygems/rubygems#4495]
### Describe the problem as clearly as you can

We are attempting to cache a specific version of a gem that has been yanked. In particular, mimemagic (due to the ongoing issues with rails: https://github.com/rails/rails/issues/41750

I ran `bundle cache` to generate and cache the version from my own cache. committed `vendor/cache/mimemagic-0.3.6.gem` and git-cleaned the rest of the gems from vendor/cache. Then on a clean machine (CI), bundle-install failed. Based on my research and digging it appears that bundler behaves as `--local` was passed to `bundle install` based solely on the _presence_ of `vendor/cache`. I find this behavior surprising; as it should be perfectly possible to cache some gems, but not all (ie, in cases where a single gem was yanked, for instance).

### Post steps to reproduce the problem

Bundler 2.2.15 (same behavior with 1.17.3)
Ruby 2.6.6
Rubygems 3.2.15 (was older when first encountered issue; reproduced after upgrading to latest)

1. `bundle cache`
2. git commit `vendor/cache/mimemagic-0.3.6.gem`
3. `git clean -df vendor`
4. (on CI, ie with clean cache) `bundle install --deployment --jobs=4 --retry=3`

### Which command did you run?

`bundle install --deployment --jobs=4 --retry=3`

### What were you expecting to happen?

I expected bundler to install the bundle, while leveraging vendor/cache for the mimemagic gem.

### What actually happened?

```
[DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local deployment 'true'`, and stop using this flag
Some gems seem to be missing from your vendor/cache directory.
Could not find rake-13.0.3 in any of the sources
```

### If not included with the output of your command, run `bundle env` and paste the output below

<details>
<summary>bundle env</summary>
## Environment

```
Bundler       2.2.15
  Platforms   ruby, x86_64-darwin-20
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin20]
  Full Path   /usr/local/var/rbenv/versions/2.6.6/bin/ruby
  Config Dir  /usr/local/var/rbenv/versions/2.6.6/etc
RubyGems      3.2.15
  Gem Home    /usr/local/var/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  Gem Path    /Users/jasonkarns/.gem/ruby/2.6.0:/usr/local/var/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  User Home   /Users/jasonkarns
  User Path   /Users/jasonkarns/.gem/ruby/2.6.0
  Bin Dir     /usr/local/var/rbenv/versions/2.6.6/bin
Tools         
  Git         2.31.0
  RVM         not installed
  rbenv       rbenv 1.1.2-gc2cfbd1
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-03-19
Git SHA           3dbcc68293
Released Version  true
```

## Bundler settings

```
disable_local_branch_check
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): true
disable_multisource
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): true
error_on_stderr
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): "true"
gem.coc
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): true
gem.mit
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): true
gem.test
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): false
init_gems_rb
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): true
suppress_install_using_messages
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): true
local.rake_to_rule_them_all
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): "/Users/jasonkarns/Projects/rake_to_rule_them_all"
build.nokogiri
  Set for the current user (/Users/jasonkarns/.config/bundler/config.yml): ""
cache_all
  Set for your local app (/Users/jasonkarns/Projects/pga/backend/.bundle/config): false
retry
  Set for your local app (/Users/jasonkarns/Projects/pga/backend/.bundle/config): 3
deployment
  Set for your local app (/Users/jasonkarns/Projects/pga/backend/.bundle/config): true
path
  Set for your local app (/Users/jasonkarns/Projects/pga/backend/.bundle/config): "vendor/bundle"
jobs
  Set for your local app (/Users/jasonkarns/Projects/pga/backend/.bundle/config): 4
user_plugin
  Set via BUNDLE_USER_PLUGIN: "/usr/local/share/bundler"
user_home
  Set via BUNDLE_USER_HOME: "/Users/jasonkarns/.config/bundler"
user_config
  Set via BUNDLE_USER_CONFIG: "/Users/jasonkarns/.config/bundler/config.yml"
user_cache
  Set via BUNDLE_USER_CACHE: "/usr/local/cache/bundler"
config
  Set via BUNDLE_CONFIG: "/Users/jasonkarns/.config/bundler/config.yml"
gemfile
  Set via BUNDLE_GEMFILE: "/Users/jasonkarns/Projects/pga/backend/Gemfile"
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.6"

gem "rails", "~> 6.0.0"
gem "puma", "~> 3.11"

gem "pg", "~> 1.1"
gem "httparty", "~> 0.17.3"

gem "composite_primary_keys", "~> 12.0.8"
gem "strong_migrations"

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# JSON Serialization
gem "fast_jsonapi"

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'

# Secure password storage and mobile authentication
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.2.0"

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# Scheduling recurring events
gem "ice_cube"

# Stripe-related gems
gem "stripe", "~> 5.14.0"
gem "stripe_event", "~> 2.3.0"

# GraphQL
gem "graphql", "~> 1.11.6"
gem "graphql-client"
gem "graphql-batch"

gem "graphql-pro", source: "https://XXX@gems.graphql.pro"

# Pundit for authorization
gem "pundit"

# Roles with rolify
gem "rolify"

# Shoryuken for mailers
gem "shoryuken"
gem "aws-sdk-sqs"

# Raygun for error tracking
gem "raygun4ruby"

# Twilio SDK
gem "twilio-ruby"

# Algolia SDK
gem "algoliasearch"

# SendGrid
gem "sendgrid-actionmailer"

# Generate iCal attachments for emails
gem "icalendar"

# Avalara tax calculation
gem "avatax"

# Google API clients
gem "google-api-client", "~> 0.34" # this one is deprecated
gem "google-apis-calendar_v3", "~> 0.1.0"

gem "aws-sdk-signer"

# Loading csv from S3 in rake task
gem "aws-sdk-s3"
gem "csv"

# Views for Google Data Studio
gem "scenic"

group :development, :test do
  gem "bullet"
  gem "dotenv-rails"
  gem "dox", require: false
  gem "factory_bot_rails"
  gem "faker"
  gem "graphiql-rails"
  gem "guard"
  gem "guard-rspec", require: false
  gem "pry-byebug" # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "rspec-rails"
  gem "rspec_junit_formatter"
  gem "standard"
  gem "vcr"
  gem "webmock"
end

group :development do
  gem "listen"
  gem "pry-rails"
  gem "rails-erd"
end

group :test do
  gem "shoulda-matchers"
end

# pin to 0.3.6 until the mimemagic licensing nonsense is sorted
gem "mimemagic", "0.3.6"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  remote: https://XXX@gems.graphql.pro/
  specs:
    actioncable (6.0.3.4)
      actionpack (= 6.0.3.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.3.4)
      actionpack (= 6.0.3.4)
      activejob (= 6.0.3.4)
      activerecord (= 6.0.3.4)
      activestorage (= 6.0.3.4)
      activesupport (= 6.0.3.4)
      mail (>= 2.7.1)
    actionmailer (6.0.3.4)
      actionpack (= 6.0.3.4)
      actionview (= 6.0.3.4)
      activejob (= 6.0.3.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.3.4)
      actionview (= 6.0.3.4)
      activesupport (= 6.0.3.4)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.3.4)
      actionpack (= 6.0.3.4)
      activerecord (= 6.0.3.4)
      activestorage (= 6.0.3.4)
      activesupport (= 6.0.3.4)
      nokogiri (>= 1.8.5)
    actionview (6.0.3.4)
      activesupport (= 6.0.3.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.3.4)
      activesupport (= 6.0.3.4)
      globalid (>= 0.3.6)
    activemodel (6.0.3.4)
      activesupport (= 6.0.3.4)
    activerecord (6.0.3.4)
      activemodel (= 6.0.3.4)
      activesupport (= 6.0.3.4)
    activestorage (6.0.3.4)
      actionpack (= 6.0.3.4)
      activejob (= 6.0.3.4)
      activerecord (= 6.0.3.4)
      marcel (~> 0.3.1)
    activesupport (6.0.3.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    algoliasearch (1.27.4)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    ast (2.4.1)
    avatax (20.9.0)
      faraday (>= 0.10)
      faraday_middleware (>= 0.10)
      multi_json (>= 1.0.3)
    aws-eventstream (1.1.0)
    aws-partitions (1.374.0)
    aws-sdk-core (3.107.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.38.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.81.1)
      aws-sdk-core (~> 3, >= 3.104.3)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sdk-signer (1.25.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-sqs (1.33.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.2)
      aws-eventstream (~> 1, >= 1.0.2)
    bcrypt (3.1.13)
    bootsnap (1.4.5)
      msgpack (~> 1.0)
    builder (3.2.4)
    bullet (6.1.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11)
    byebug (11.0.1)
    choice (0.2.0)
    coderay (1.1.2)
    composite_primary_keys (12.0.8)
      activerecord (~> 6.0.0)
    concurrent-ruby (1.1.8)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    crass (1.0.6)
    csv (3.1.9)
    declarative (0.0.20)
    declarative-option (0.1.0)
    diff-lcs (1.3)
    dotenv (2.7.5)
    dotenv-rails (2.7.5)
      dotenv (= 2.7.5)
      railties (>= 3.2, < 6.1)
    dox (1.2.0)
      rails (>= 4.0)
      rspec-core
    erubi (1.10.0)
    factory_bot (6.1.0)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.1.0)
      factory_bot (~> 6.1.0)
      railties (>= 5.0.0)
    faker (2.17.0)
      i18n (>= 1.6, < 2)
    faraday (1.0.1)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (1.0.0)
      faraday (~> 1.0)
    fast_jsonapi (1.5)
      activesupport (>= 4.2)
    ffi (1.11.2)
    formatador (0.2.5)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    google-api-client (0.50.0)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (~> 0.9)
      httpclient (>= 2.8.1, < 3.0)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      rexml
      signet (~> 0.12)
    google-apis-calendar_v3 (0.1.0)
      google-apis-core (~> 0.1)
    google-apis-core (0.2.0)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (~> 0.14)
      httpclient (>= 2.8.1, < 3.0)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      rexml
      signet (~> 0.14)
    googleauth (0.14.0)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.14)
    graphiql-rails (1.7.0)
      railties
      sprockets-rails
    graphql (1.11.6)
    graphql-batch (0.4.3)
      graphql (>= 1.3, < 2)
      promise.rb (~> 0.7.2)
    graphql-client (0.16.0)
      activesupport (>= 3.0)
      graphql (~> 1.8)
    graphql-pro (1.16.2)
      graphql (>= 1.7.5)
    guard (2.16.2)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (>= 1.0.12, < 2.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    hashdiff (1.0.0)
    httparty (0.17.3)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    httpclient (2.8.3)
    i18n (1.8.9)
      concurrent-ruby (~> 1.0)
    icalendar (2.7.0)
      ice_cube (~> 0.16)
    ice_cube (0.16.3)
    jmespath (1.4.0)
    json (2.3.1)
    jwt (2.2.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.9.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    lumberjack (1.2.8)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    memoist (0.16.2)
    method_source (0.9.2)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2019.1009)
    mimemagic (0.3.6)
    mini_mime (1.0.2)
    mini_portile2 (2.5.0)
    minitest (5.14.4)
    msgpack (1.3.1)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    nenv (0.3.0)
    nio4r (2.5.4)
    nokogiri (1.11.2)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    notiffany (0.1.3)
      nenv (~> 0.1)
      shellany (~> 0.0)
    os (1.1.1)
    parallel (1.20.1)
    parser (3.0.0.0)
      ast (~> 2.4.1)
    pg (1.1.4)
    promise.rb (0.7.4)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.8.0)
      byebug (~> 11.0)
      pry (~> 0.10)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    public_suffix (4.0.3)
    puma (3.12.1)
    pundit (2.1.0)
      activesupport (>= 3.0.0)
    racc (1.5.2)
    rack (2.2.3)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.0.3.4)
      actioncable (= 6.0.3.4)
      actionmailbox (= 6.0.3.4)
      actionmailer (= 6.0.3.4)
      actionpack (= 6.0.3.4)
      actiontext (= 6.0.3.4)
      actionview (= 6.0.3.4)
      activejob (= 6.0.3.4)
      activemodel (= 6.0.3.4)
      activerecord (= 6.0.3.4)
      activestorage (= 6.0.3.4)
      activesupport (= 6.0.3.4)
      bundler (>= 1.3.0)
      railties (= 6.0.3.4)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-erd (1.6.0)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
      choice (~> 0.2.0)
      ruby-graphviz (~> 1.2)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (6.0.3.4)
      actionpack (= 6.0.3.4)
      activesupport (= 6.0.3.4)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rainbow (3.0.0)
    rake (13.0.3)
    raygun4ruby (3.2.3)
      concurrent-ruby
      httparty (> 0.13.7)
      json
      rack
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    regexp_parser (2.0.3)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rexml (3.2.4)
    rolify (5.3.0)
    rspec (3.9.0)
      rspec-core (~> 3.9.0)
      rspec-expectations (~> 3.9.0)
      rspec-mocks (~> 3.9.0)
    rspec-core (3.9.0)
      rspec-support (~> 3.9.0)
    rspec-expectations (3.9.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-mocks (3.9.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-rails (3.9.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.9.0)
      rspec-expectations (~> 3.9.0)
      rspec-mocks (~> 3.9.0)
      rspec-support (~> 3.9.0)
    rspec-support (3.9.0)
    rspec_junit_formatter (0.4.1)
      rspec-core (>= 2, < 4, != 2.12.0)
    rubocop (1.7.0)
      parallel (~> 1.10)
      parser (>= 2.7.1.5)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.2.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 2.0)
    rubocop-ast (1.4.0)
      parser (>= 2.7.1.5)
    rubocop-performance (1.9.2)
      rubocop (>= 0.90.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    ruby-graphviz (1.2.5)
      rexml
    ruby-progressbar (1.11.0)
    ruby_dep (1.5.0)
    ruby_http_client (3.5.1)
    safe_yaml (1.0.5)
    scenic (1.5.4)
      activerecord (>= 4.0.0)
      railties (>= 4.0.0)
    sendgrid-actionmailer (3.1.0)
      mail (~> 2.7)
      sendgrid-ruby (~> 6.0)
    sendgrid-ruby (6.3.6)
      ruby_http_client (~> 3.4)
    shellany (0.0.1)
    shoryuken (5.0.4)
      aws-sdk-core (>= 2)
      concurrent-ruby
      thor
    shoulda-matchers (4.1.2)
      activesupport (>= 4.2.0)
    signet (0.14.0)
      addressable (~> 2.3)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    standard (0.11.0)
      rubocop (= 1.7.0)
      rubocop-performance (= 1.9.2)
    stripe (5.14.0)
    stripe_event (2.3.0)
      activesupport (>= 3.1)
      stripe (>= 2.8, < 6)
    strong_migrations (0.7.6)
      activerecord (>= 5)
    thor (1.1.0)
    thread_safe (0.3.6)
    twilio-ruby (5.40.4)
      faraday (>= 0.9, < 2.0)
      jwt (>= 1.5, <= 2.5)
      nokogiri (>= 1.6, < 2.0)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    uber (0.1.0)
    unicode-display_width (1.7.0)
    uniform_notifier (1.13.0)
    vcr (5.1.0)
    webmock (3.8.2)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)
    websocket-driver (0.7.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    zeitwerk (2.4.2)

PLATFORMS
  ruby

DEPENDENCIES
  algoliasearch
  avatax
  aws-sdk-s3
  aws-sdk-signer
  aws-sdk-sqs
  bcrypt (~> 3.1.7)
  bootsnap (>= 1.4.2)
  bullet
  composite_primary_keys (~> 12.0.8)
  csv
  dotenv-rails
  dox
  factory_bot_rails
  faker
  fast_jsonapi
  google-api-client (~> 0.34)
  google-apis-calendar_v3 (~> 0.1.0)
  graphiql-rails
  graphql (~> 1.11.6)
  graphql-batch
  graphql-client
  graphql-pro!
  guard
  guard-rspec
  httparty (~> 0.17.3)
  icalendar
  ice_cube
  jwt (~> 2.2.0)
  listen
  mimemagic (= 0.3.6)
  pg (~> 1.1)
  pry-byebug
  pry-rails
  puma (~> 3.11)
  pundit
  rack-cors
  rails (~> 6.0.0)
  rails-erd
  raygun4ruby
  rolify
  rspec-rails
  rspec_junit_formatter
  scenic
  sendgrid-actionmailer
  shoryuken
  shoulda-matchers
  standard
  stripe (~> 5.14.0)
  stripe_event (~> 2.3.0)
  strong_migrations
  twilio-ruby
  vcr
  webmock

RUBY VERSION
   ruby 2.6.6p146

BUNDLED WITH
   2.2.15
```
</details>

**Comment by deivid-rodriguez** [comment]
Agreed.

**Comment by blowfishpro** [comment]
I'm running into this too.  It seems like there's no way to install gems with (1) a frozen lockfile (`deployment`/`frozen`) and (2) an present but empty or partially filled `vendor/cache`

**Comment by blowfishpro** [comment]
Well I think I spoke too soon, it appears that running `bundle package` before the install does not implicitly update gems, so I ended up with this:
```
bundle package --no-install
bundle config set --local deployment true
bundle config set --local without development:test
bundle install --local
```
I think I had to get on the latest versions of rubygems/bundler to do this but I didn't bother figuring out exactly which versions matter

**Comment by blowfishpro** [comment]
Okay well I don't know what I was seeing before because I'm definitely still seeing the OP issue and not finding a way to avoid updating the Gemfile.lock with a partial cache.  I tried a couple of scenarios with `bundle cache`:

Scenario 1:
- Gemfile.lock is out of date
- `frozen` is false
- `vendor/cache` state does not matter
Result: `Gemfile.lock` is updated

Scenario 2:
- Gemfile.lock is up to date
- `frozen` is true
- `vendor/cache` exists but is not up to date
Result: Failure

I think it comes down to [this line](https://github.com/rubygems/rubygems/blob/f8c76eae24bbeabb9c9cb5387dbd89df45566eb9/bundler/lib/bundler/cli/install.rb#L36).

**Comment by blowfishpro** [comment]
If one is running `bundle install` you have access to the `--local` or `--prefer-local` options, so it seems odd to force `local` in this case.

If one is running `bundle cache` then forcing `local` makes no sense because you're explicitly trying to update the cache directory.

**Comment by viktorianer** [comment]
I am not sure, if I have the same issue, but in my case I am using GitHub actions, and bundle is not installing all gems I need.

In my workflow, I use `ruby/setup-ruby@v1` action, and it looks like this:

```yml
...
       - name: Install Ruby dependencies
          uses: ruby/[email protected]
          with:
            bundler-cache: true
            cache-version: 1
...
```

This action is installing per default all gems locally, in `vendor/cache`. As you can see in following comments, not all are happy with this https://github.com/ruby/setup-ruby/issues/153. I also normally use `BUNDLE_FROZEN: true`, bun in this case it doesn't matter, because this action is forcing `bundle config set --global deployment true`.

And now back to this issue.  If I check output, I am missing some gems. For example, [bootsnap](https://github.com/Shopify/bootsnap), which is default since [Rails 6.1](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-1-to-rails-5-2-bootsnap).

```bash
Print Ruby version
  /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/ruby --version
  ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
  Took   0.04 seconds
Installing Bundler
  Using Bundler 2.3.22 from Gemfile.lock BUNDLED WITH 2.3.22
  /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/gem install bundler -v 2.3.22
  Successfully installed bundler-2.3.22
  1 gem installed
  Took   0.78 seconds
bundle install
  /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle config --local path /home/runner/work/rails-community-app/rails-community-app/vendor/bundle
  /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v4-ubuntu-22.04-ruby-3.1.2-cachever:2-Gemfile.lock-5ced[23](https://github.com/viktorianer/rails-community-app/actions/runs/3569210898/jobs/5999243336#step:4:25)8a98a169c[24](https://github.com/viktorianer/rails-community-app/actions/runs/3569210898/jobs/5999243336#step:4:26)ab5e10e7ee37d94995fc9c709c[25](https://github.com/viktorianer/rails-community-app/actions/runs/3569210898/jobs/5999243336#step:4:27)0cf4f[26](https://github.com/viktorianer/rails-community-app/actions/runs/3569210898/jobs/5999243336#step:4:29)be3578fe6[33](https://github.com/viktorianer/rails-community-app/actions/runs/3569210898/jobs/5999243336#step:4:37)6
  /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle install --jobs 4
  Fetching gem metadata from https://rubygems.org/.......
  Fetching rake 13.0.6
  Installing rake 13.0.6

  ...

  Saving cache
  /usr/bin/tar --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/rails-community-app/rails-community-app --files-from manifest.txt
  Cache Size: ~43 MB (44794434 B)
  Cache saved successfully
  Took  33.23 seconds
```

And the next workflow step will fail, because it is missing this gem:

```bash
Run bundle exec rails test
/home/runner/work/rails-community-app/rails-community-app/config/boot.rb:6:in `require': cannot load such file -- bootsnap/setup (LoadError)
	from /home/runner/work/rails-community-app/rails-community-app/config/boot.rb:6:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
Error: Process completed with exit code 1.
```

I am in the process of upgrading my app to Rails 7 and added GitHub actions. I had some Rails 7 and Rails 6 apps with the same GitHub actions, and it worked well. My lust successful run (at an available repository) with GitHub actions is 6 months ago:

```bash
Triggered via pull request 6 months ago
...
https://github.com/viktorianer/sample_app/pull/1
..
Status
Success
Total duration
2m 31s
...
```

So now I'm stuck, because some gems are missed.

**Comment by blowfishpro** [comment]
@viktorianer I don't think this has the same cause.  The symptom of this issue is that `bundle install` fails, but in your case it looks like that is successful but the installed gems are not available for some reason at a later point in time.

**Comment by viktorianer** [comment]
> @viktorianer I don't think this has the same cause. The symptom of this issue is that `bundle install` fails, but in your case it looks like that is successful but the installed gems are not available for some reason at a later point in time.

You are right. I was able to narrow down the problem. For documentation, it was this line:

`BUNDLE_WITHOUT: production default doc job cable storage ujs db`

I am not sure, how I got this idea with ignoring `default` group, but for sure, it would not work, as  bootsnap  is in this group 📦 . 

Sorry for the circumstances.

**Comment by deivid-rodriguez** [comment]
This should be fixed by https://github.com/rubygems/rubygems/issues/8925. Turns out @blowfishpro had already identified the culprit line in https://github.com/rubygems/rubygems/issues/4495#issuecomment-1290968499.
