### ISSUE TITLE
Getting error while creating new rails project, 

### ISSUE THREAD

**Issue by prathyushp23** [rubygems/rubygems#4526]
Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/exe/bundle install`

- **What did you expect to happen?**

  I expected Bundler to install the gems properly

- **What happened instead?**

  Instead, what happened was stuck while the process

## Backtrace

```
Gem::RemoteFetcher::UnknownHostError: timed out (https://rubygems.org/gems/spring-2.1.1.gem)
  /home/devopsu/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/remote_fetcher.rb:268:in `rescue in fetch_path'
  /home/devopsu/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/remote_fetcher.rb:249:in `fetch_path'
  /home/devopsu/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/remote_fetcher.rb:299:in `cache_update_path'
  /home/devopsu/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/remote_fetcher.rb:154:in `download'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/rubygems_integration.rb:527:in `block in download_gem'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/retry.rb:40:in `run'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/retry.rb:30:in `attempt'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/rubygems_integration.rb:526:in `download_gem'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/source/rubygems.rb:506:in `download_gem'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/source/rubygems.rb:447:in `fetch_gem'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/source/rubygems.rb:138:in `install'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/installer/gem_installer.rb:67:in `install'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/worker.rb:62:in `apply_func'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/worker.rb:54:in `loop'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/worker.rb:54:in `process_queue'
  /home/devopsu/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.16/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler             2.2.16
  Platforms         ruby, x86_64-linux
Ruby                2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-linux]
  Full Path         /home/devopsu/.rvm/rubies/ruby-2.7.2/bin/ruby
  Config Dir        /home/devopsu/.rvm/rubies/ruby-2.7.2/etc
RubyGems            3.1.4
  Gem Home          /home/devopsu/.rvm/gems/ruby-2.7.2
  Gem Path          /home/devopsu/.rvm/gems/ruby-2.7.2:/home/devopsu/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0
  User Home         /home/devopsu
  User Path         /home/devopsu/.gem/ruby/2.7.0
  Bin Dir           /home/devopsu/.rvm/gems/ruby-2.7.2/bin
OpenSSL
  Compiled          OpenSSL 1.1.1  11 Sep 2018
  Loaded            OpenSSL 1.1.1  11 Sep 2018
  Cert File         /usr/lib/ssl/cert.pem
  Cert Dir          /usr/lib/ssl/certs
Tools
  Git               2.17.1
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2021-04-09
Git SHA           3d7bfaff25
Released Version  true
```

## Bundler settings

```
ignore_messages
  Set via BUNDLE_IGNORE_MESSAGES: true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3', '>= 6.1.3.1'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
<No /mnt/e/CTI/recreate/cti/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Could you upgrade your rubygems version with `gem update --system` and try again?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
