### ISSUE TITLE
Bundler Rake release fails

### ISSUE THREAD

**Issue by bryan-kc** [rubygems/rubygems#4541]
### Describe the problem as clearly as you can

I have a CI pipeline running Ruby 2.5.3 with bundler 2.2.16 . When we try to run `bundle exec rake release` the following happens. The only thing that might collide is the following config step before this `git config --global push.default matching` , but we have found in testing that it doesn't have an effect on resolving this bug.

```[2021-04-16T21:40:49.137Z] XXXX-10.6.1 built to pkg/XXXX-10.6.1.gem.
[2021-04-16T21:40:49.137Z] Tagged 10.6.1.
[2021-04-16T21:40:49.137Z] Untagging 10.6.1 due to error.
[2021-04-16T21:40:49.137Z] rake aborted!
[2021-04-16T21:40:49.137Z] Couldn't git push. `git push origin refs/heads/HEAD' failed with the following output:
[2021-04-16T21:40:49.137Z] 
[2021-04-16T21:40:49.137Z] error: src refspec refs/heads/HEAD does not match any.
[2021-04-16T21:40:49.137Z] error: failed to push some refs to 'git@corporate.com:XXXXX/name-of-my-project.git'
```

I can't find the remote called `refs/heads/HEAD` and don't know where it is being detected from. It appears the command is trying to push to a remote that doesn't exist. when I type `git ls-remote` the remote doesn't appear in the list. 

We recently updated the running version of bundler for our CI runners from 2.0.2 -> 2.2.16.

### Post steps to reproduce the problem

- Running GitHub Enterprise `2.15.4` 
- Ruby 2.5.3
- Bundler 2.2.16

**Comment by bryan-kc** [comment]
the version of git running on the runner is `2.7.4-0ubuntu1.10` built on Ubuntu 16.04

**Comment by deivid-rodriguez** [comment]
Hi @bryan-kc. Are you in a detached HEAD when you try to release? Also, has this ever worked in previous bundler versions?

I _think_ previous bundler versions might've allowed you to release from a detached HEAD, if you use the `git config --global push.default matching` configuration. Previous bundler versions would run `git push` without an explicit remote and branch (which I believe would do nothing if you have `push.default matching` configured, but not fail), whereas now we `git push` with a explicit remote and branch, which fails in this case.

Can you confirm this by trying `bundler 2.1.x` with and without the `push.default matching` git setting?

If this is the culprit, I think we can skip the `git push` if you're in a detached HEAD.

**Comment by bryan-kc** [comment]
Hi @deivid-rodriguez it turns out that we are in a detached head when we try to release. I believe this worked on bundler 2.0.2 . I suspected that a change over the years restricted this ability to push in a detached head state.

**Comment by bryan-kc** [comment]
I've included verbose logs of this command for our reference.

```
$ bundle exec rake --trace release
** Invoke release (first_time)
** Invoke build (first_time)
** Execute build
test-project 0.0.1 built to pkg/test-project-0.0.1.gem.
** Invoke release:guard_clean (first_time)
** Execute release:guard_clean
** Invoke release:source_control_push (first_time)
** Execute release:source_control_push
Tagged 0.0.1.
Untagging 0.0.1 due to error.
rake aborted!
Couldn't git push. `git push origin refs/heads/HEAD' failed with the following output:

error: src refspec refs/heads/HEAD does not match any.
error: failed to push some refs to 'git@corporate.com:XXXXX/test-project.git'

/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/gem_helper.rb:168:in `perform_git_push'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/gem_helper.rb:135:in `git_push'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/gem_helper.rb:76:in `block (2 levels) in install'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/gem_helper.rb:192:in `tag_version'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/gem_helper.rb:76:in `block in install'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/bin/rake:23:in `load'
/var/lib/jenkins/cache_bundle/ruby/3.0.0/bin/rake:23:in `<top (required)>'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
/var/lib/jenkins/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => release => release:source_control_push
```

**Comment by deivid-rodriguez** [comment]
Thanks @bryan-kc.

Normally people release from the default branch or some kind of "stable branch". What bundler does in that case is tag the tip of that branch, and push both the branch and the tag. If you're in a detached state, you don't really want to push any branches, you only want to push the tag generated from that detached state. Due to how bundler 2.1 worked (it simply used `git push --tags`), and due to the git setting you're using (`push.default matching`), I believe this indeed got broken in bundler 2.2. I'll look into fixing this.

**Comment by bryan-kc** [comment]
I dug in deeper and found the cause to be due to the default behaviour of the Jenkins plugin we are using, in which it will checkout the repository in a detached HEAD state. (https://stackoverflow.com/questions/11511390/jenkins-git-plugin-detached-head/23131277). In any case, I was able to repair the checkout behaviour within the pipeline so that I am no longer in a detached head.

I'm not sure if allowing this use case is considered expected behaviour in this scenario, but I trust your intuition on whether or not this is a bug.

Thank you so much for your help!
