### ISSUE TITLE
Errno::EACCES: Permission denied @ dir_s_mkdir -

### ISSUE THREAD

**Issue by achalbi** [rubygems/rubygems#4583]
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/Users/<username>/.rbenv/versions/2.7.2/bin/bundle update`

## Backtrace

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/bcrypt-3.1.16
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:222:in `write_gem_make_out'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:139:in `build_error'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:185:in `rescue in build_extension'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:162:in `build_extension'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in build_extensions'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/rubygems_gem_installer.rb:17:in `build_extensions'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/installer.rb:327:in `install'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/source/rubygems.rb:158:in `install'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/installer/gem_installer.rb:67:in `install'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/installer/parallel_installer.rb:163:in `do_install'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/installer/parallel_installer.rb:154:in `block in worker_pool'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/worker.rb:62:in `apply_func'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/worker.rb:54:in `loop'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/worker.rb:54:in `process_queue'
  /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.3
  Platforms   ruby, x86_64-darwin-20
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-darwin20]
  Full Path   /Users/achalindiresh/.rbenv/versions/2.7.2/bin/ruby
  Config Dir  /Users/achalindiresh/.rbenv/versions/2.7.2/etc
RubyGems      3.1.4
  Gem Home    /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
  Gem Path    /Users/achalindiresh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0:/Users/achalindiresh/.gem/ruby/2.7.0
  User Home   /Users/achalindiresh
  User Path   /Users/achalindiresh/.gem/ruby/2.7.0
  Bin Dir     /Users/achalindiresh/.rbenv/versions/2.7.2/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1k  25 Mar 2021
  Cert File   /Users/achalindiresh/.rbenv/versions/2.7.2/openssl/ssl/cert.pem
  Cert Dir    /Users/achalindiresh/.rbenv/versions/2.7.2/openssl/ssl/certs
Tools         
  Git         2.30.1 (Apple Git-130)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-22
Git SHA           29dc3c8398
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3', '>= 6.1.3.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


gem 'solidus_api', '2.11.8'
gem 'solidus_backend', '2.11.8'
gem 'solidus_core', '2.11.8'
gem 'solidus_frontend', '2.11.8'
# gem 'solidus_starter_frontend'
gem 'solidus_auth_devise'

gem 'razorpay'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.3.1)
      actionpack (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.3.1)
      actionpack (= 6.1.3.1)
      activejob (= 6.1.3.1)
      activerecord (= 6.1.3.1)
      activestorage (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      mail (>= 2.7.1)
    actionmailer (6.1.3.1)
      actionpack (= 6.1.3.1)
      actionview (= 6.1.3.1)
      activejob (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.3.1)
      actionview (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.3.1)
      actionpack (= 6.1.3.1)
      activerecord (= 6.1.3.1)
      activestorage (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      nokogiri (>= 1.8.5)
    actionview (6.1.3.1)
      activesupport (= 6.1.3.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.3.1)
      activesupport (= 6.1.3.1)
      globalid (>= 0.3.6)
    activemerchant (1.119.0)
      activesupport (>= 4.2)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (6.1.3.1)
      activesupport (= 6.1.3.1)
    activerecord (6.1.3.1)
      activemodel (= 6.1.3.1)
      activesupport (= 6.1.3.1)
    activestorage (6.1.3.1)
      actionpack (= 6.1.3.1)
      activejob (= 6.1.3.1)
      activerecord (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      marcel (~> 1.0.0)
      mini_mime (~> 1.0.2)
    activesupport (6.1.3.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    acts_as_list (1.0.4)
      activerecord (>= 4.2)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    autoprefixer-rails (10.2.4.0)
      execjs
    awesome_nested_set (3.4.0)
      activerecord (>= 4.0.0, < 7.0)
    bcrypt (3.1.16)
    bindex (0.8.1)
    bootsnap (1.7.4)
      msgpack (~> 1.0)
    builder (3.2.4)
    byebug (11.1.3)
    cancancan (3.2.1)
    canonical-rails (0.2.11)
      rails (>= 4.1, < 6.2)
    capybara (3.35.3)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    carmen (1.1.3)
      activesupport (>= 3.0.0)
    childprocess (3.0.0)
    climate_control (0.2.0)
    coffee-rails (5.0.0)
      coffee-script (>= 2.2.0)
      railties (>= 5.2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.8)
    crass (1.0.6)
    deface (1.8.1)
      nokogiri (>= 1.6)
      polyglot
      rails (>= 5.2)
      rainbow (>= 2.1.0)
    devise (4.8.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    discard (1.2.0)
      activerecord (>= 4.2, < 7)
    erubi (1.10.0)
    execjs (2.7.0)
    ffi (1.15.0)
    font-awesome-rails (4.7.0.7)
      railties (>= 3.2, < 7)
    friendly_id (5.4.2)
      activerecord (>= 4.0.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    handlebars_assets (0.23.9)
      execjs (~> 2.0)
      sprockets (>= 2.0.0)
      tilt (>= 1.2)
    httparty (0.18.1)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    image_processing (1.12.1)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    jbuilder (2.11.2)
      activesupport (>= 5.0.0)
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    kaminari (1.2.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.1)
      kaminari-activerecord (= 1.2.1)
      kaminari-core (= 1.2.1)
    kaminari-actionview (1.2.1)
      actionview
      kaminari-core (= 1.2.1)
    kaminari-activerecord (1.2.1)
      activerecord
      kaminari-core (= 1.2.1)
    kaminari-core (1.2.1)
    kt-paperclip (6.4.1)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      mime-types
      mimemagic (~> 0.3.0)
      terrapin (~> 0.6.0)
    listen (3.5.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.9.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.1)
    method_source (1.0.0)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2021.0225)
    mimemagic (0.3.10)
      nokogiri (~> 1)
      rake
    mini_magick (4.11.0)
    mini_mime (1.0.3)
    minitest (5.14.4)
    monetize (1.11.0)
      money (~> 6.12)
    money (6.14.1)
      i18n (>= 0.6.4, <= 2)
    msgpack (1.4.2)
    multi_xml (0.6.0)
    nio4r (2.5.7)
    nokogiri (1.11.3-x86_64-darwin)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    paranoia (2.4.3)
      activerecord (>= 4.0, < 6.2)
    pg (1.2.3)
    polyglot (0.3.5)
    public_suffix (4.0.6)
    puma (5.2.2)
      nio4r (~> 2.0)
    racc (1.5.2)
    rack (2.2.3)
    rack-mini-profiler (2.3.2)
      rack (>= 1.2.0)
    rack-proxy (0.6.5)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.1.3.1)
      actioncable (= 6.1.3.1)
      actionmailbox (= 6.1.3.1)
      actionmailer (= 6.1.3.1)
      actionpack (= 6.1.3.1)
      actiontext (= 6.1.3.1)
      actionview (= 6.1.3.1)
      activejob (= 6.1.3.1)
      activemodel (= 6.1.3.1)
      activerecord (= 6.1.3.1)
      activestorage (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      bundler (>= 1.15.0)
      railties (= 6.1.3.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (6.1.3.1)
      actionpack (= 6.1.3.1)
      activesupport (= 6.1.3.1)
      method_source
      rake (>= 0.8.7)
      thor (~> 1.0)
    rainbow (3.0.0)
    rake (13.0.3)
    ransack (2.4.2)
      activerecord (>= 5.2.4)
      activesupport (>= 5.2.4)
      i18n
    razorpay (2.4.1)
      httparty (~> 0.14)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (2.1.1)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    ruby-vips (2.1.0)
      ffi (~> 1.12)
    rubyzip (2.3.0)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.1.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    semantic_range (3.0.0)
    solidus_api (3.0.0)
      jbuilder (~> 2.8)
      kaminari-activerecord (~> 1.1)
      responders
      solidus_core (= 3.0.0)
    solidus_auth_devise (2.5.3)
      deface (~> 1.0)
      devise (~> 4.1)
      devise-encryptable (= 0.2.0)
      paranoia (~> 2.4)
      solidus_core (>= 2.6, < 4)
      solidus_support (~> 0.5)
    solidus_backend (3.0.0)
      autoprefixer-rails
      coffee-rails
      font-awesome-rails (~> 4.0)
      handlebars_assets (~> 0.23)
      jbuilder (~> 2.8)
      jquery-rails
      kaminari (~> 1.1)
      responders
      sassc-rails
      solidus_api (= 3.0.0)
      solidus_core (= 3.0.0)
    solidus_core (3.0.0)
      actionmailer (>= 5.2, < 6.2.x)
      actionpack (>= 5.2, < 6.2.x)
      actionview (>= 5.2, < 6.2.x)
      activejob (>= 5.2, < 6.2.x)
      activemerchant (~> 1.66)
      activemodel (>= 5.2, < 6.2.x)
      activerecord (>= 5.2, < 6.2.x)
      activesupport (>= 5.2, < 6.2.x)
      acts_as_list (< 2.0)
      awesome_nested_set (~> 3.3)
      cancancan (>= 2.2, < 4.0)
      carmen (~> 1.1.0)
      discard (~> 1.0)
      friendly_id (~> 5.0)
      image_processing (~> 1.10)
      kaminari-activerecord (~> 1.1)
      kt-paperclip (~> 6.3)
      mini_magick (~> 4.10)
      monetize (~> 1.8)
      railties (>= 5.2, < 6.2.x)
      ransack (~> 2.0)
      state_machines-activerecord (~> 0.6)
    solidus_frontend (3.0.0)
      canonical-rails (~> 0.2.10)
      font-awesome-rails (~> 4.0)
      jquery-rails
      kaminari (~> 1.1)
      responders
      sassc-rails
      solidus_api (= 3.0.0)
      solidus_core (= 3.0.0)
      truncate_html (~> 0.9, >= 0.9.2)
    solidus_support (0.8.1)
    spring (2.1.1)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    state_machines (0.5.0)
    state_machines-activemodel (0.8.0)
      activemodel (>= 5.1)
      state_machines (>= 0.5.0)
    state_machines-activerecord (0.8.0)
      activerecord (>= 5.1)
      state_machines-activemodel (>= 0.8.0)
    terrapin (0.6.0)
      climate_control (>= 0.0.3, < 1.0)
    thor (1.1.0)
    tilt (2.0.10)
    truncate_html (0.9.3)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.1.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (4.6.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (>= 3.0, < 4.0)
    webpacker (5.3.0)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket-driver (0.7.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.4.2)

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES
  bootsnap (>= 1.4.4)
  byebug
  capybara (>= 3.26)
  jbuilder (~> 2.7)
  listen (~> 3.3)
  pg (~> 1.1)
  puma (~> 5.0)
  rack-mini-profiler (~> 2.0)
  rails (~> 6.1.3, >= 6.1.3.1)
  razorpay
  sass-rails (>= 6)
  selenium-webdriver
  solidus_api
  solidus_auth_devise
  solidus_backend
  solidus_core
  solidus_frontend
  spring
  turbolinks (~> 5)
  tzinfo-data
  web-console (>= 4.1.0)
  webdrivers
  webpacker (~> 5.0)

RUBY VERSION
   ruby 2.7.2p137

BUNDLED WITH
   2.2.3
```

**Comment by deivid-rodriguez** [comment]
Hi. Could you try this again using the latest bundler and rubygems versions. Running `gem update --system` and then `bundle update --bundler` should help with that.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by knittingarch** [comment]
@deivid-rodriguez I am having the same problem, but using `asdf`. I ran `gem update --system` with no perceived trouble, but running `bundle update --bundler` led to this message `Unfortunately, an unexpected error occurred, and Bundler cannot continue.` I can't find much to explain what the actual issue is.

**Comment by tobinharris** [comment]
I'm also having this issue using `asdf` and Ruby 3.0.0. Any updates?

**Comment by tobinharris** [comment]
FIXED: `sudo chown -R $(whoami) ~/.asdf`
