### ISSUE TITLE
Cannot update rubygems

### ISSUE THREAD

**Issue by Axel12321** [rubygems/rubygems#4584]
My current problem is that i cannt upgrade rubygems with the command " gem update --system".

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
- RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.7.0 (2019-12-25 patchlevel 0) [x86_64-linux-gnu]
```

Here are the results when i execute the command "gem update --system": 

Updating rubygems-update
Successfully installed rubygems-update-3.2.17
Parsing documentation for rubygems-update-3.2.17
Done installing documentation for rubygems-update after 0 seconds
Parsing documentation for rubygems-update-3.2.17
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.2.17
Traceback (most recent call last):
	5: from setup.rb:23:in `<main>'
	4: from setup.rb:23:in `require'
	3: from /home/alexandros/gems/gems/rubygems-update-3.2.17/lib/rubygems.rb:1348:in `<top (required)>'
	2: from /home/alexandros/gems/gems/rubygems-update-3.2.17/lib/rubygems.rb:1348:in `require'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:49:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:50:in `<class:Specification>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)

**Comment by Axel12321** [comment]
btw i uninstalled ruby then reinstall and problem still exists
