### ISSUE TITLE
Cannot install ruby gem from rubygems.pkg.github.com without specifying the version.

### ISSUE THREAD

**Issue by andrewmcnamara** [rubygems/rubygems#4603]
I'm having a problem or would like to suggest a feature.

My current problem is I cannot install a gem from Github packages `rubygems.pkg.github.com` without specifying the version.

With version `3.2.17`

```sh
❯ gem --version
3.2.17

❯ gem install REDACTED_GEM_NAME --verbose
HEAD https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/
404 Not Found
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/prerelease_specs.4.8.gz
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/specs.4.8.gz
200 OK
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/REDACTED_GEM_NAME
404 Not Found
GET https://index.rubygems.org/prerelease_specs.4.8.gz
304 Not Modified
GET https://index.rubygems.org/specs.4.8.gz
304 Not Modified
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/quick/Marshal.4.8/REDACTED_GEM_NAME-0.gemspec.rz
404 Not Found
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/quick/Marshal.4.8/REDACTED_GEM_NAME-0.gemspec.rz)
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/remote_fetcher.rb:239:in `fetch_http'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/remote_fetcher.rb:255:in `fetch_path'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/source.rb:151:in `fetch_spec'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/index_specification.rb:96:in `spec'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/index_specification.rb:43:in `required_ruby_version'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:250:in `metadata_satisfied?'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:81:in `block in add_always_install'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:80:in `select'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/installer_set.rb:80:in `add_always_install'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/dependency_installer.rb:322:in `resolve_dependencies'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:198:in `install_gem'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:216:in `each'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:216:in `install_gems'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/commands/install_command.rb:164:in `execute'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:323:in `invoke_with_build_args'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/command_manager.rb:178:in `process_args'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/command_manager.rb:147:in `run'
	.../.asdf/installs/ruby/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/gem_runner.rb:53:in `run'
	.../.asdf/installs/ruby/2.7.2/bin/gem:15:in `<main>'

```

I can install the gem using by specifying the version
```sh 
❯ gem env version
3.2.17

❯ gem install REDACTED_GEM_NAME --version 0.5.2 --verbose
HEAD https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/
404 Not Found
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/prerelease_specs.4.8.gz
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/specs.4.8.gz
200 OK
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/REDACTED_GEM_NAME
404 Not Found
GET https://index.rubygems.org/prerelease_specs.4.8.gz
304 Not Modified
GET https://index.rubygems.org/specs.4.8.gz
304 Not Modified
 ...
Successfully installed REDACTED_GEM_NAME-0.5.2
1 gem installed
```

Note this was working with an earlier version like `3.1.4` 
```sh
❯ gem --version
3.1.4

❯ gem install REDACTED_GEM_NAME --verbose
HEAD https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies
200 OK
HEAD https://rubygems.org/api/v1/dependencies
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=REDACTED_GEM_NAME
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=REDACTED_GEM_NAME
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=activesupport,httparty,thor,tty-command,tty-logger,tty-which,zeitwerk
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=activesupport,httparty,thor,tty-command,tty-logger,tty-which,zeitwerk
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=pastel
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=pastel
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=tty-color
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=tty-color
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=mime-types,multi_xml
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=mime-types,multi_xml
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=mime-types-data
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=mime-types-data
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/api/v1/dependencies?gems=concurrent-ruby,i18n,minitest,tzinfo
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=concurrent-ruby,i18n,minitest,tzinfo
200 OK
GET https://andrewmcnamara:REDACTED@rubygems.pkg.github.com/REDACTED_COMPANY/quick/Marshal.4.8/REDACTED_GEM_NAME.gemspec.rz
200 OK

```

This issue is related to:

  - [ ] Network problems
  - [ X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.17
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by dgholz** [comment]
I've noticed this too, it seems to be caused by the `prerelease_specs.48.gz` that comes from GitHub Packages. It has all our gems (public and private) listed with a single `0` version:
```
require 'open-uri'
require 'pp'

github_org = 'your org'
github_pat = 'your GitHub personal access token'
pp Marshal.load(
  Gem::Util.gunzip(
    URI.open(
      "https://rubygems.pkg.github.com/#{github_org}/prerelease_specs.4.8.gz",
      { http_basic_authentication: [ 'x-access-token', github_pat ]}
    ).read
  )
)
```
gives
```
[["gem1", Gem::Version.new("0"), "ruby"],
 ["gem2", Gem::Version.new("0"), "ruby"],
...
 ["gem99", Gem::Version.new("0"), "ruby"]]
```
It lists all our gems (once each, with `Gem::Version.new("0")`), regardless of whether they have prerelease versions or not.

**Comment by dgholz** [comment]
It looks like this behaviour was changed in `3.2.3`, with
https://github.com/rubygems/rubygems/pull/4110/files#diff-0eab5c1d499ffc9abcb8aebb9974afacfda27b56bf63ac40c1e3a448b65bd134R81

Before: only return the latest version
After: all potential versions get their metadata checked to see if they're installable (including these bogus prerelease versions)

The changed code is wrapped in `unless @force`, so if can be skipped by specifying `gem install --force your_github_hosted_gem`. I tried that, and see that Molinillo also does a similar check, and gets a `404` when attempting to fetch metadata for the bogus `0` version:
```
$ gem -v
3.2.3
$ gem install --backtrace --force MY_GITHUB_HOSTED_GEM 
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://x-access-token:REDACTED@rubygems.pkg.github.com/MY_ORG/quick/Marshal.4.8/MY_GITHUB_HOSTED_GEM-0.gemspec.rz)
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/remote_fetcher.rb:239:in `fetch_http'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/remote_fetcher.rb:255:in `fetch_path'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/source.rb:151:in `fetch_spec'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/index_specification.rb:96:in `spec'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/specification.rb:119:in `installable_platform?'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/platform.rb:45:in `installable?'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:223:in `block in select_local_platforms'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:222:in `select'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:222:in `select_local_platforms'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:213:in `find_possible'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:228:in `search_for'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:313:in `amount_constrained'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:286:in `block in sort_dependencies'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:282:in `each'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:282:in `sort_by'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:282:in `with_index'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:282:in `sort_dependencies'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:288:in `push_initial_state'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:210:in `start_resolution'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:168:in `resolve'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/resolver.rb:190:in `resolve'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/dependency_installer.rb:333:in `resolve_dependencies'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/commands/install_command.rb:198:in `install_gem'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `each'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/commands/install_command.rb:216:in `install_gems'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/commands/install_command.rb:164:in `execute'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/command_manager.rb:178:in `process_args'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/command_manager.rb:147:in `run'
        /Users/danielholz/.rubies/ruby-3.0.1/lib/ruby/3.0.0/rubygems/gem_runner.rb:53:in `run'
        /Users/danielholz/.rubies/ruby-3.0.1/bin/gem:21:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
The issue is most likely due to https://github.com/rubygems/rubygems/pull/4110.

That PR migrated rubygems to start using a new API (we call it the compact index API). This new API is necessary because it provides `required_ruby_version` and `required_rubygems_version` information about gems, which we need to avoid resolution errors in some cases. The problem here seems to be that github private gem sources don't implement this new API, so rubygems instead falls back to the old marshalled index of specs now. And for some reason, which I should investigate, the old index is not working properly.

**Comment by deivid-rodriguez** [comment]
@dgholz I actually missed your first post about those buggy prereleases. Indeed seems like an issue with Github Packages gem server. Not sure what's the best place to report/ask about this :thinking:.

**Comment by dgholz** [comment]
Thanks for looking @deivid-rodriguez! I've opened a support ticket with GitHub & am waiting to hear from them.

I reckon the metadata checking could be made more resilient, if the gemspec for a version `404`s then that's not great (and should warn the user) but if another version can be found and is installable, then I think the user would prefer that it be installed.

**Comment by deivid-rodriguez** [comment]
Yeah, that makes sense. If the full prerelease index includes some `<name>-<version>`, but that gemspec does not exist, we could probably change the current error to a warning, ignore that possibility and move on.

**Comment by dgholz** [comment]
GitHub support say they have an internal issue for this problem already and have pointed the team at this one.

**Comment by esotericpig** [comment]
I have this problem with all of the recent Gems that I pushed to RubyGems.org.

None of the following will work:

```
$ gem install attr_bool
$ gem install nhkore
$ gem install init_copy
```

I have to specify the version:

```
$ gem install nhkore -v 0.3.8
```

This really sucks because no one will be able to use my Gems. They'll think all of my Gems are broken, but instead you need to specify the version.

Here are the errors:

```
$ gem install nhkore
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://esotericpig:REDACTED@rubygems.pkg.github.com/esotericpig/quick/Marshal.4.8/nhkore-0.gemspec.rz)

$ gem install attr_bool
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://esotericpig:REDACTED@rubygems.pkg.github.com/esotericpig/quick/Marshal.4.8/attr_bool-0.gemspec.rz)

$ gem install init_copy
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://esotericpig:REDACTED@rubygems.pkg.github.com/esotericpig/quick/Marshal.4.8/init_copy-0.gemspec.rz)
```

I push all of my library Gems to both RubyGems.org and GitHub Packages. For some reason, `gem` on the command line seems to be grabbing from GitHub Packages first, but why? Shouldn't it be grabbing from RubyGems.org first. So maybe the workaround is to delete all of my GitHub Packages. It just seems weird that it should be affecting RubyGems.org and the `gem` CLI app.

If it's a problem with RubyGems and not my Gemspec, I think this should be made a priority for RubyGems.org to fix! Please use RubyGems.org over GitHub Packages. Previously, it always worked fine.

Version info:

```
$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
$ gem -v
3.2.15
```

**Comment by deivid-rodriguez** [comment]
That sounds like a problem specific to your environment, I guess you need to remove github from your `gem sources` list?

**Comment by esotericpig** [comment]
> That sounds like a problem specific to your environment, I guess you need to remove github from your `gem sources` list?

Oh, you're right. I have that in my sources so that I can push to GitHub Packages, so this will affect everyone that either pushes to GitHub Packages and/or uses it to install Gems.

Interestingly, `gem sources` produces it second:

```
$ gem sources
*** CURRENT SOURCES ***

https://rubygems.org/
https://esotericpig:<secret_key>@rubygems.pkg.github.com/esotericpig/
```

So you would think it'd hit RubyGems.org first, but it doesn't. Is there a way to have it hit RubyGems.org first?

**Comment by esotericpig** [comment]
Note that in my `~/.gemrc` file that it's also listed as second. I guess I'll comment it out for now.

I can easily see people being affected by this though without knowing what to do and probably not finding this comment thread.

**Comment by deivid-rodriguez** [comment]
> So you would think it'd hit RubyGems.org first, but it doesn't. Is there a way to have it hit RubyGems.org first?

I don't know.

There are indeed some issues here other than the one with github packages gem servers misbehaving. Hopefully eventually me or someone else will work on it :)

**Comment by deivid-rodriguez** [comment]
We found a fix that should also make `gem install` perform less network requests in general: https://github.com/rubygems/rubygems/pull/4843.

**Comment by deivid-rodriguez** [comment]
GitHub should fix their prerelease index anyways, but that change luckily avoids the issue :)
