### ISSUE TITLE
Bundler 2.2.18 cannot resolve private dependencies properly for gems

### ISSUE THREAD

**Issue by Domon** [rubygems/rubygems#4632]
### Describe the problem as clearly as you can

Hi, 👋 

We have a gem where it depends on a private gem for development purpose. The private gem is specified in the `Gemfile`. `bundle install` works in Bundler 2.2.17 (or many earlier versions). But it doesn't work in Bundler 2.2.18 with the same setup. I can reproduce it with Ruby 2.6.7 and 3.0.0.

Bundler 2.2.17 installs the gems properly. But Bundler 2.2.18 resolves the private gem to a very old version. And it also tries to find the public gem dependency on our private gem server.

I can reproduce it in a newly created and empty gem. I have attached the example at the bottom of this issue.

### Post steps to reproduce the problem

1. Run `bundle gem GEM_NAME` to create a new gem

2. Add a private gem in `Gemfile`

```
source "https://rubygems.org"

gemspec

source 'https://PRIVATE_GEM_SERVER/' do
  gem 'PRIVATE_GEM'
end
```

3. Run `bundle install` with Bundler 2.2.18
 
### Which command did you run?

`bundle install`

### What were you expecting to happen?

Gems are installed without any error.

### What actually happened?

The command failed with the following errors.

```
Resolving dependencies...
Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    PRIVATE_GEM was resolved to AN_OLD_VERSION, which depends on
      rubocop (~> 0.84.0)

Could not find gem 'rubocop (~> 0.84.0)', which is required by gem 'PRIVATE_GEM', in rubygems repository https://PRIVATE_GEM_SERVER/ or installed locally.
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    PRIVATE_GEM was resolved to AN_OLD_VERSION, which depends on
      rubocop (~> 0.84.0)

Could not find gem 'rubocop (~> 0.84.0)', which is required by gem 'PRIVATE_GEM', in rubygems repository https://PRIVATE_GEM_SERVER/ or installed locally.
...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/resolver.rb:57:in `rescue in start'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/resolver.rb:44:in `start'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/resolver.rb:23:in `resolve'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/definition.rb:279:in `resolve'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/definition.rb:171:in `resolve_remotely!'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/installer.rb:291:in `resolve_if_needed'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/installer.rb:83:in `block in run'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/process_lock.rb:12:in `block in lock'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/process_lock.rb:9:in `open'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/process_lock.rb:9:in `lock'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/installer.rb:72:in `run'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/installer.rb:24:in `install'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/cli/install.rb:64:in `run'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/cli.rb:259:in `block in install'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/settings.rb:133:in `temporary'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/cli.rb:258:in `install'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/cli.rb:30:in `dispatch'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/cli.rb:24:in `start'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/exe/bundle:49:in `block in <top (required)>'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
  ...REDACTED.../lib/ruby/gems/3.0.0/gems/bundler-2.2.18/exe/bundle:37:in `<top (required)>'
  ...REDACTED.../bin/bundle:23:in `load'
  ...REDACTED.../bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.18
  Platforms   ruby, x86_64-darwin-19
Ruby          3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-darwin19]
  Full Path   ...REDACTED.../bin/ruby
  Config Dir  ...REDACTED.../etc
RubyGems      3.2.3
  Gem Home    ...REDACTED.../lib/ruby/gems/3.0.0
  Gem Path    ...REDACTED.../.gem/ruby/3.0.0:...REDACTED.../lib/ruby/gems/3.0.0
  User Home   ...REDACTED...
  User Path   ...REDACTED.../.gem/ruby/3.0.0
  Bin Dir     ...REDACTED.../3.0.0/bin
Tools
  Git         2.31.1
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-05-25
Git SHA           6a9e89bacd
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (...REDACTED.../.bundle/config): false
gem.ci
  Set for the current user (...REDACTED.../.bundle/config): false
gem.coc
  Set for the current user (...REDACTED.../.bundle/config): false
gem.mit
  Set for the current user (...REDACTED.../.bundle/config): false
gem.rubocop
  Set for the current user (...REDACTED.../.bundle/config): false
gem.test
  Set for the current user (...REDACTED.../.bundle/config): false
PRIVATE_GEM_SERVER_1
  Set for the current user (...REDACTED.../.bundle/config): "...REDACTED..."
jobs
  Set for your local app (...REDACTED.../Downloads/bundler-issues/.bundle/config): 8
PRIVATE_GEM_SERVER_2
  Set for the current user (...REDACTED.../.bundle/config): "...REDACTED..."
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in bundler-issues.gemspec
gemspec

gem "rake", "~> 13.0"

source 'PRIVATE_GEM_SERVER' do
  gem 'PRIVATE_GEM'
end
```

### Gemfile.lock

```
<No ...REDACTED.../bundler-issues/Gemfile.lock found>
```

### bundler-issues.gemspec

```ruby
# frozen_string_literal: true

require_relative "lib/bundler/issues/version"

Gem::Specification.new do |spec|
  spec.name          = "bundler-issues"
  spec.version       = Bundler::Issues::VERSION
  spec.authors       = ["Foo"]
  spec.email         = ["foo@example.com"]

  spec.summary       = "..."
  spec.description   = "..."
  spec.homepage      = "https://example.com"
  spec.required_ruby_version = Gem::Requirement.new(">= 2.4.0")

  spec.metadata["allowed_push_host"] = "https://example.com"

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "https://example.com"
  spec.metadata["changelog_uri"] = "https://example.com"

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.chdir(File.expand_path(__dir__)) do
    `git ls-files -z`.split("\x0").reject { |f| f.match(%r{\A(?:test|spec|features)/}) }
  end
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  # Uncomment to register a new dependency of your gem
  # spec.add_dependency "example-gem", "~> 1.0"

  # For more information and examples about making a new gem, checkout our
  # guide at: https://bundler.io/guides/creating_gem.html
end
```

**Comment by deivid-rodriguez** [comment]
Hi @Domon!

Do you have any version of `rubocop` in your private gem server? That's the one case I can think of where this would break. If you have a version of an indirect dependency, `bundler` will now fetch it from there and refuse to fetch it from any global sources at all.

If this is the case, there's a number of ways you can get the behavior you want:

* Remove the `rubocop` gem from your private gem server.
* Add the `rubocop` gem as a direct depedency at the top level of your `Gemfile`.

**Comment by Domon** [comment]
Hi @deivid-rodriguez,

Thanks for your prompt response.

Adding `rubocop` to the top level like the following works for me. 🎉 

```rb
source 'https://rubygems.org'

gemspec

gem 'rubocop'

source 'PRIVATE_GEM_SERVER' do
  gem 'PRIVATE_GEM'
end
```

Just out of curiosity, is there any difference between specifying the gem at the top level and in a block?

I also tried the following `Gemfile`. It looks similar to the file above but doesn't work somehow.

```rb
source 'https://rubygems.org' do
  gemspec

  gem 'rubocop'
end

source 'PRIVATE_GEM_SERVER' do
  gem 'PRIVATE_GEM'
end
```

The error messages are like the following.

```
Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    rubocop

    PRIVATE_GEM was resolved to PRIVATE_GEM_VERSION, which depends on
      rubocop (~> 0.92.0)

Bundler could not find compatible versions for gem "rubocop-rspec":
  In Gemfile:
    PRIVATE_GEM was resolved to PRIVATE_GEM_VERSION, which depends on
      rubocop-rspec

Could not find gem 'rubocop-rspec', which is required by gem 'PRIVATE_GEM', in locally installed gems.
```

I like the block syntax so am surprised that it doesn't work in this case.

**Comment by deivid-rodriguez** [comment]
Hi!

By using scoped sources, you tell bundler "I want the gems specified under this source, and also their dependencies, to be fetched from this source". And by using a global source, you tell bundler "I want the gems specified at the top level, and also any dependencies that can't be found in other sources, to be fetched from the global source".

So, in your case, `bundler` tries to pickup `rubocop-rspec` from your private source, because `rubocop-rspec` is a dependency of your private gem, but can't find it there.

On the other hand, when you use a global source, `rubocop-rspec` is picked up from there because the global source is used as a fallback since it couldn't be found in the scoped source.

**Comment by Domon** [comment]
Thanks @deivid-rodriguez again for the solution and explanation 🙏

**Comment by deivid-rodriguez** [comment]
No problem @Domon!
