### ISSUE TITLE
undefined method '?' for Bundler::CurrentRuby on Windows

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#4655]
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]
Windows 7
One-click installer

I ran `bundle install` in a local project and hit this:

```
Traceback (most recent call last):
        28: from C:/Ruby27-x64/bin/bundle.cmd:31:in `<main>'
        27: from C:/Ruby27-x64/bin/bundle.cmd:31:in `load'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
        25: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
        23: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
        22: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        21: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
        20: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        19: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        18: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        17: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/cli.rb:255:in `install'
        16: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
        15: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/cli.rb:256:in `block in install'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/cli/install.rb:63:in `run'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler.rb:195:in `definition'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:34:in `build'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/dsl.rb:13:in `evaluate'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/dsl.rb:234:in `to_definition'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/dsl.rb:234:in `new'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:130:in `initialize'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:972:in `compute_requires'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:972:in `reduce'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:972:in `each'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:973:in `block in compute_requires'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/dependency.rb:118:in `should_include?'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/dependency.rb:134:in `current_platform?'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/dependency.rb:134:in `any?'
C:/Ruby27-x64/lib/ruby/2.7.0/bundler/dependency.rb:135:in `block in current_platform?': undefined method `?' for #<Bundler::CurrentRuby:0x00
000000068b5820> (NoMethodError)
```
The Gemfile is very basic:
```
source 'https://rubygems.org' do
  gemspec
end
```
Within the gemspec I have this special block of code:
```
if File::ALT_SEPARATOR
    spec.add_dependency('sys-admin')
    spec.add_dependency('win32-file-attributes')
    spec.add_dependency('win32-dir')
    spec.add_dependency('win32-process')
    spec.platform = Gem::Platform::CURRENT
    spec.platform.cpu = 'universal'
  end
```
It seems to be choking on `spec.platform = Gem::Platform::CURRENT`.

**Comment by deivid-rodriguez** [comment]
Can you check what's the behaviour on the latest rubygems + the latest bundler. This could've been fixed already.

**Comment by djberg96** [comment]
@deivid-rodriguez After a `gem update system` which bumped me from rubygems 3.1.x to 3.2.x, everything seems to be ok. Closing.
