### ISSUE TITLE
`ERROR REPORT TEMPLATE` instead of error message on 502 from rubegems.org

### ISSUE THREAD

**Issue by ojab** [rubygems/rubygems#4660]
### Describe the problem as clearly as you can

Right now rubygems.org is mostly down (responding with 50x) and if specs file is fetched successfully, but gem fetch fails, bundler reports unhandled exception.

### Post steps to reproduce the problem

`bundle` when gem source returns specs, but returns 502 instead of gem file.

### Which command did you run?

`bundle` 

### What were you expecting to happen?

Human-readable error without unhandled exceptions.

### What actually happened?

```
…
Fetching tzinfo 1.2.9

Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Gateway Error 502 (https://rubygems.org/gems/tzinfo-1.2.9.gem)

Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Gateway Error 502 (https://rubygems.org/gems/tzinfo-1.2.9.gem)

Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Gateway Error 502 (https://rubygems.org/gems/tzinfo-1.2.9.gem)

…
## Backtrace

Gem::RemoteFetcher::FetchError: bad response Gateway Error 502 (https://rubygems.org/gems/tzinfo-1.2.9.gem)
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:239:in `fetch_http'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:255:in `fetch_path'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:292:in `cache_update_path'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:153:in `download'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/rubygems_integration.rb:527:in `block in download_gem'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/retry.rb:40:in `run'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/retry.rb:30:in `attempt'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/rubygems_integration.rb:526:in `download_gem'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:513:in `download_gem'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:454:in `fetch_gem'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:138:in `install'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/installer/gem_installer.rb:67:in `install'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/worker.rb:62:in `apply_func'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/worker.rb:54:in `loop'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/worker.rb:54:in `process_queue'
  /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'

## Environment

Bundler       2.2.19
  Platforms   ruby, x86_64-linux
Ruby          3.0.1p64 (2021-04-05 revision 0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0) [x86_64-linux]
  Full Path   /home/ojab/.rbenv/versions/3.0.1/bin/ruby
  Config Dir  /home/ojab/.rbenv/versions/3.0.1/etc
RubyGems      3.2.17
  Gem Home    /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  Gem Path    /home/ojab/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0:/home/ojab/.gem/ruby/3.0.0
  User Home   /home/ojab
  User Path   /home/ojab/.gem/ruby/3.0.0
  Bin Dir     /home/ojab/.rbenv/versions/3.0.1/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1c  28 May 2019
  Loaded      OpenSSL 1.1.1c  28 May 2019
  Cert File   /etc/ssl/cert.pem
  Cert Dir    /etc/ssl/certs
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       rbenv 1.1.2-44-gd604acb
  chruby      not installed
…
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
```

**Comment by hsbt** [comment]
see https://github.com/rubygems/rubygems/issues/4659#issuecomment-856643910

**Comment by ojab** [comment]
Well yeah, but I don't see how it's related to the reported issue. It's not `rubygems is down`, it's `bundler does not handling the error gracefully`.

**Comment by deivid-rodriguez** [comment]
I think this issue is reporting that the error in this case should be better/different. It looks ok to me for this kind of situation. How do you expect us to handle the error?

**Comment by deivid-rodriguez** [comment]
In other words, there's a server side issue and bundler is making that quite clear, right?

**Comment by deivid-rodriguez** [comment]
Oh, ok, I get it now, we're printing a bug report template and we shouldn't, it should be a plain error without any extra information to report an issue here. It makes sense to me :+1:.

**Comment by ojab** [comment]
IMHO the error message and `exit whatever` without all the issue reporting boilerplate (just like it happens on spec fetching failure) would be less confusing:
```
$ bundle
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/ due to underlying error <bad response Gateway Error 502 (https://rubygems.org/specs.4.8.gz)>

Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/ due to underlying error <bad response Service Unavailable 503 (https://rubygems.org/specs.4.8.gz)>

Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/ due to underlying error <bad response Service Unavailable 503 (https://rubygems.org/specs.4.8.gz)>

Could not fetch specs from https://rubygems.org/ due to underlying error <bad response Service Not Found 500
(https://rubygems.org/specs.4.8.gz)>
$ 
```
Right now it's needed to scroll all the boilerplate and find the error message in the backtrace, which is not ideal.

**Comment by deivid-rodriguez** [comment]
Yep, agreed.

**Comment by deivid-rodriguez** [comment]
Fixed by https://github.com/rubygems/rubygems/pull/4663.
