### ISSUE TITLE
Possible memory leak, need help diagnosing the issue

### ISSUE THREAD

**Issue by sergio-bobillier** [rubygems/rubygems#4666]
### Describe the problem as clearly as you can

Recently I have been experiencing issues when running `bundle install`

On windows I get:

```
NoMemoryError: failed to allocate memory
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:887:in `rescue in block in request'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:884:in `block in request'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendored_persistent.rb:17:in `block in connection_for'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:608:in `connection_for'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendored_persistent.rb:16:in `connection_for'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:870:in `request'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/fetcher/downloader.rb:63:in `request'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/fetcher/downloader.rb:19:in `fetch'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/fetcher/compact_index.rb:131:in `call'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/compact_index_client/updater.rb:48:in `block in update'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/tmpdir/lib/tmpdir.rb:96:in `mktmpdir'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/compact_index_client/updater.rb:29:in `update'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/compact_index_client.rb:98:in `update'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/compact_index_client.rb:85:in `update_and_parse_checksums!'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/fetcher/compact_index.rb:75:in `available?'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/fetcher/compact_index.rb:16:in `call'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/fetcher.rb:162:in `use_api'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:409:in `block in api_fetchers'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:409:in `select'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:409:in `api_fetchers'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:320:in `dependency_api_available?'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/source/rubygems.rb:287:in `double_check_for'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/spec_set.rb:87:in `block in materialize'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/spec_set.rb:82:in `each'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/spec_set.rb:82:in `materialize'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/definition.rb:183:in `specs'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/installer.rb:254:in `ensure_specs_are_compatible!'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/installer.rb:84:in `block in run'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/process_lock.rb:12:in `block in lock'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/process_lock.rb:9:in `open'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/process_lock.rb:9:in `lock'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/installer.rb:72:in `run'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/installer.rb:24:in `install'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/cli/install.rb:64:in `run'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/cli.rb:259:in `block in install'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/settings.rb:133:in `temporary'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/cli.rb:258:in `install'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/cli.rb:30:in `dispatch'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/cli.rb:24:in `start'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/exe/bundle:49:in `block in <top (required)>'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
 ​C:/Tools/scoop/persist/ruby26/gems/gems/bundler-2.2.19/exe/bundle:37:in `<top (required)>'
 ​C:/Tools/scoop/apps/ruby26/current/gems/bin/bundle:23:in `load'
 ​C:/Tools/scoop/apps/ruby26/current/gems/bin/bundle:23:in `<main>'
```

On linux just:

```
31728 Killed                  bundle install
```

And on the `syslog` file I can see:

```
Jun 10 17:30:12 ubuntu kernel: [1741570.841278] Out of memory: Kill process 31728 (ruby) score 904 or sacrifice child
Jun 10 17:30:12 ubuntu kernel: [1741570.841343] Killed process 31728 (ruby) total-vm:8452784kB, anon-rss:7859152kB, file-rss:0kB, shmem-rss:0kB
```

This happens some second after I type `bundle install` before the line `Fetching gem metadata from https://gemserver.local/..` appears.

### Post steps to reproduce the problem

The issue is very sporadic and I cannot really reproduce it, it just happens from time to time when running `bundle install`

This happens on Windows with:

```
Bundler       2.2.19
 ​Platforms   ruby, x86-mingw32
Ruby          2.6.7p197 (2021-04-05 revision 67941) [i386-mingw32]
 ​Full Path   C:/Tools/scoop/apps/ruby26/2.6.7-1/bin/ruby.exe
 ​Config Dir  C:/ProgramData
RubyGems      3.0.3.1
 ​Gem Home    C:/Tools/scoop/persist/ruby26/gems
 ​Gem Path    C:/Tools/scoop/persist/ruby26/gems
 ​User Home   C:/Users/sergio
 ​User Path   C:/Users/sergio/.gem/ruby/2.6.0
 ​Bin Dir     C:/Tools/scoop/persist/ruby26/gems/bin
Tools         
 ​Git         2.24.0.windows.2
 ​RVM         not installed
 ​rbenv       not installed
 ​chruby      not installed

## Bundler Build Metadata

Built At          2021-05-31
Git SHA           43f80b12c0
Released Version  true
```

And in Linux with:

```
Bundler             2.2.17
  Platforms         ruby, x86_64-linux
Ruby                2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
  Full Path         /home/sergio/.rvm/rubies/ruby-2.6.5/bin/ruby
  Config Dir        /etc
RubyGems            3.0.6
  Gem Home          /home/sergio/.rvm/gems/ruby-2.6.5
  Gem Path          /home/sergio/.rvm/gems/ruby-2.6.5:/home/sergio/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0
  User Home         /home/sergio
  User Path         /home/sergio/.gem/ruby/2.6.0
  Bin Dir           /home/sergio/.rvm/gems/ruby-2.6.5/bin
Tools
  Git               2.17.1
  RVM               1.29.9-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)

## Bundler Build Metadata

Built At          2021-05-05
Git SHA           69cbd6e10e
Released Version  true
```

There is a catch here, I'm not fetching the gems directly from Rubygems but instead from an internal Gem Server set-up with Artifactory. I have the feeling that this might be related to the issue but I don't know how to test that (I cannot simply switch to rubygems.org because the internal gems won't be available there).

I cannot report the issue to DevOps because I have no real proof that the Artifactory Server is at fault.

I have a gut feeling that the index in the Artifactory server is too big. How could I compare it with the one in Rubygems.org?

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Normally gems are fetched and installed successfully.

### What actually happened?

What I reported. `bundler` (or the Ruby process running `bundler`) starts grabbing memory until the operating system kills the process (or it exists because it cannot get more memory).

### If not included with the output of your command, run `bundle env` and paste the output below

Is already up in the "Steps" section.

**Comment by deivid-rodriguez** [comment]
Thanks @sergio-bobillier!

Some things you can try:

* Upgrade ruby.
* Upgrade rubygems.
* Remove the `rubygems-bundler` gem.

Also running with the `--verbose` flag might give us more information.

Let me know if you can still reproduce after that.

**Comment by deivid-rodriguez** [comment]
After a closer look I think this might be the same problem as https://github.com/rubygems/rubygems/issues/4353. If this is the case, creating a more sensible number of threads would fix it. I opened https://github.com/rubygems/rubygems/pull/4670 to do that, and also using `net/http` code including https://github.com/ruby/net-http/pull/10 (not yet released, unfortunately) should cut the number of created threads in half.

**Comment by sergio-bobillier** [comment]
Thanks for the quick answer @deivid-rodriguez

Unfortunately updating Ruby is not possible at the moment because the project has too many dependencies and some of them are incompatible with later versions of Ruby. I'll add the verbose flag and will attach the output the next time I see the issue.

I really hope that the issue you linked is the solution for the problem. I'll also report back on that one.

**Comment by deivid-rodriguez** [comment]
No problem @sergio-bobillier. Yes, please report back. Hopefully this issue is gone in the next release.
