### ISSUE TITLE
Bundler.require: superclass mismatch for class Mark (TypeError)

### ISSUE THREAD

**Issue by Drowze** [rubygems/rubygems#4698]
### Describe the problem as clearly as you can

Considering the script:
```
require 'yaml'
Bundler.require(:default, "test")
```

When I run `parallel_test` gem to execute it in parallel, I got an error I didn't recognize. Strangely enough, it only happens through the `parallel_test -e "bundle exec rspec <script>"` command. If I use `bundle exec ruby <script>` or simply remove the `parallel_test` (i.e. run `bundle exec rspec` directly) the error doesn't happen. The error happens on the `Bundler.require` line.

I also found out that the error only happens if the `reek` gem is on a different group than the `faker` gem on the Gemfile.

### Post steps to reproduce the problem

With this Gemfile:
```
source "https://rubygems.org"
gem "parallel_tests"
gem "rspec"
gem "faker"
group(:development) { gem "reek" }
```

And this script.rb:
```ruby
require 'yaml'
Bundler.require(:default, "test")
```

Run:
```
bundle exec parallel_rspec -n1 -e "bundle exec rspec test.rb"
```

### Which command did you run?

```
$ cat test.rb
require 'yaml'

Bundler.require(:default, "test")

$ bundle exec parallel_rspec -n1 -e "bundle exec rspec test.rb"
TypeError:
  superclass mismatch for class Mark
```

### What were you expecting to happen?

I expected the file to parse out correctly

### What actually happened?

```
/usr/local/lib/ruby/2.7.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::ANY
/usr/local/lib/ruby/2.7.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF8
/usr/local/lib/ruby/2.7.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
/usr/local/lib/ruby/2.7.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:9: warning: previous definition of DATE was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:15: warning: previous definition of RANGE was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:17: warning: previous definition of REGEXP was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:18: warning: previous definition of STRUCT was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here
/usr/local/lib/ruby/2.7.0/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE
/usr/local/bundle/gems/psych-3.3.2/lib/psych/class_loader.rb:67: warning: previous definition of CACHE was here
/usr/local/lib/ruby/2.7.0/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME
/usr/local/bundle/gems/psych-3.3.2/lib/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here
/usr/local/lib/ruby/2.7.0/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT
/usr/local/bundle/gems/psych-3.3.2/lib/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here
/usr/local/lib/ruby/2.7.0/psych/scalar_scanner.rb:17: warning: already initialized constant Psych::ScalarScanner::INTEGER
/usr/local/bundle/gems/psych-3.3.2/lib/psych/scalar_scanner.rb:17: warning: previous definition of INTEGER was here
/usr/local/lib/ruby/2.7.0/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/stream.rb:13: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.7.0/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here
/usr/local/lib/ruby/2.7.0/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here
/usr/local/lib/ruby/2.7.0/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here
/usr/local/lib/ruby/2.7.0/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.7.0/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here
/usr/local/lib/ruby/2.7.0/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here
/usr/local/lib/ruby/2.7.0/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.7.0/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
/usr/local/lib/ruby/2.7.0/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
/usr/local/lib/ruby/2.7.0/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
/usr/local/lib/ruby/2.7.0/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
/usr/local/lib/ruby/2.7.0/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
/usr/local/lib/ruby/2.7.0/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.7.0/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here
/usr/local/lib/ruby/2.7.0/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
/usr/local/bundle/gems/psych-3.3.2/lib/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here
/usr/local/lib/ruby/2.7.0/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH
/usr/local/bundle/gems/psych-3.3.2/lib/psych/visitors/visitor.rb:23: warning: previous definition of DISPATCH was here
/usr/local/lib/ruby/2.7.0/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS
/usr/local/bundle/gems/psych-3.3.2/lib/psych/handler.rb:27: warning: previous definition of OPTIONS was here
/usr/local/lib/ruby/2.7.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/usr/local/bundle/gems/psych-3.3.2/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here

An error occurred while loading ./test.rb.
Failure/Error: class Mark < Struct.new(:index, :line, :column)

TypeError:
  superclass mismatch for class Mark
# /usr/local/bundle/gems/faker-2.17.0/lib/faker.rb:5:in `require'
# /usr/local/bundle/gems/faker-2.17.0/lib/faker.rb:5:in `<top (required)>'
# ./test.rb:3:in `<top (required)>'
No examples found.


Finished in 0.00004 seconds (files took 0.20914 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.7.3p183 (2021-04-05 revision 6847ee089d7655b2a0eea4fee3133aeacd4cc7cc) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.1.6
  Gem Home    /usr/local/bundle
  Gem Path    /home/app/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
  User Home   /home/app
  User Path   /home/app/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.20.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-06-25
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
jobs
  Set for your local app (/usr/local/bundle/config): 4
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "parallel_tests"
gem "rspec"
gem "faker"

group :development do
  gem "reek"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.4.2)
    concurrent-ruby (1.1.8)
    diff-lcs (1.4.4)
    faker (2.17.0)
      i18n (>= 1.6, < 2)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    kwalify (0.7.2)
    parallel (1.20.1)
    parallel_tests (3.7.0)
      parallel
    parser (3.0.1.0)
      ast (~> 2.4.1)
    psych (3.3.2)
    rainbow (3.0.0)
    reek (6.0.4)
      kwalify (~> 0.7.0)
      parser (~> 3.0.0)
      psych (~> 3.1)
      rainbow (>= 2.0, < 4.0)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.1)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-support (3.10.2)

PLATFORMS
  ruby

DEPENDENCIES
  faker
  parallel_tests
  reek
  rspec

BUNDLED WITH
   2.1.4
```

**Comment by deivid-rodriguez** [comment]
Could you try upgrading bundler & rubygems, through `gem update --system`? It should be fixed in the latest versions.

**Comment by Drowze** [comment]
That indeed solved the issue @deivid-rodriguez, I'll close this issue.

Just for record, I found this error while interacting with the latest [official docker image](https://hub.docker.com/_/ruby) for ruby 2.7.3. It was a bit of pain for us as it was breaking our CI when running tests on our setup.

**Comment by deivid-rodriguez** [comment]
That's great to hear. :tada:.

Yeah, the official ruby docker images no longer provide up to date rubygems & bundler versions, they leave the version that's shipped with each ruby and it's up to the end users whether to upgrade rubygems and bundler or not.

I'll add a note to the issue template to try upgrading first thing before reporting issues, that will probably save users and maintainers some time :)
