### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue - `Errno::EACCES: Permission denied @ dir_s_mkdir`

### ISSUE THREAD

**Issue by therohansanap** [rubygems/rubygems#4766]
### Problem
Command `bundle install` fails with permission denied problem.

### Which command did you run?

I ran the command `/Users/rohansanap/.rbenv/versions/2.7.2/bin/bundle install`

### What were you expecting to happen?

Expectation was that bundle installation succeeds.

### What actually happened?
Bundle installation failed with following error - `Errno::EACCES: Permission denied @ dir_s_mkdir`
## Backtrace
```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/json-2.5.1
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `each'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:203:in `write_gem_make_out'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:131:in `build_error'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:165:in `rescue in build_extension'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:154:in `build_extension'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:191:in `block in build_extensions'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:188:in `each'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:188:in `build_extensions'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:828:in `build_extensions'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/rubygems_gem_installer.rb:64:in `build_extensions'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/source/rubygems.rb:182:in `install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer/gem_installer.rb:67:in `install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer/parallel_installer.rb:171:in `install_serially'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer/parallel_installer.rb:97:in `call'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer.rb:263:in `install_in_parallel'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer.rb:210:in `install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer.rb:90:in `block in run'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/process_lock.rb:15:in `lock'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer.rb:72:in `run'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/installer.rb:24:in `install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/cli/install.rb:60:in `run'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/cli.rb:259:in `block in install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/settings.rb:131:in `temporary'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/cli.rb:258:in `install'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/cli.rb:30:in `dispatch'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/cli.rb:24:in `start'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/exe/bundle:49:in `block in <top (required)>'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.23/exe/bundle:37:in `<top (required)>'
  /Users/rohansanap/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
  /Users/rohansanap/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.23
  Platforms   ruby, x86_64-darwin-20
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-darwin20]
  Full Path   /Users/rohansanap/.rbenv/versions/2.7.2/bin/ruby
  Config Dir  /Users/rohansanap/.rbenv/versions/2.7.2/etc
RubyGems      3.2.23
  Gem Home    /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
  Gem Path    /Users/rohansanap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0:/Users/rohansanap/.gem/ruby/2.7.0
  User Home   /Users/rohansanap
  User Path   /Users/rohansanap/.gem/ruby/2.7.0
  Bin Dir     /Users/rohansanap/.rbenv/versions/2.7.2/bin
OpenSSL
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1k  25 Mar 2021
  Cert File   /Users/rohansanap/.rbenv/versions/2.7.2/openssl/ssl/cert.pem
  Cert Dir    /Users/rohansanap/.rbenv/versions/2.7.2/openssl/ssl/certs
Tools
  Git         2.24.3 (Apple Git-128)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-07-09
Git SHA           e863a3905d
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'fastlane', '~>2.179.0'
gem 'cocoapods', '~>1.10.0'
gem 'cocoapods-generate'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.3)
    activesupport (5.2.5)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    artifactory (3.0.15)
    atomos (0.1.3)
    aws-eventstream (1.1.1)
    aws-partitions (1.438.0)
    aws-sdk-core (3.113.1)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.43.0)
      aws-sdk-core (~> 3, >= 3.112.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.93.0)
      aws-sdk-core (~> 3, >= 3.112.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.3)
      aws-eventstream (~> 1, >= 1.0.2)
    babosa (1.0.4)
    claide (1.0.3)
    cocoapods (1.10.1)
      addressable (~> 2.6)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.10.1)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.4.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.4.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.6.6)
      nap (~> 1.0)
      ruby-macho (~> 1.4)
      xcodeproj (>= 1.19.0, < 2.0)
    cocoapods-core (1.10.1)
      activesupport (> 5.0, < 6)
      addressable (~> 2.6)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.4)
    cocoapods-disable-podfile-validations (0.1.1)
    cocoapods-downloader (1.4.0)
    cocoapods-generate (2.2.2)
      cocoapods-disable-podfile-validations (~> 0.1.1)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.0)
    cocoapods-trunk (1.5.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored (1.2)
    colored2 (3.1.2)
    commander-fastlane (4.4.6)
      highline (~> 1.7.2)
    concurrent-ruby (1.1.8)
    declarative (0.0.20)
    declarative-option (0.1.0)
    digest-crc (0.6.3)
      rake (>= 12.0.0, < 14.0.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    emoji_regex (3.2.2)
    escape (0.0.4)
    ethon (0.12.0)
      ffi (>= 1.3.0)
    excon (0.79.0)
    faraday (1.3.0)
      faraday-net_http (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords
    faraday-cookie_jar (0.0.7)
      faraday (>= 0.8.0)
      http-cookie (~> 1.0.0)
    faraday-net_http (1.0.1)
    faraday_middleware (1.0.0)
      faraday (~> 1.0)
    fastimage (2.2.3)
    fastlane (2.179.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.3, < 3.0.0)
      artifactory (~> 3.0)
      aws-sdk-s3 (~> 1.0)
      babosa (>= 1.0.3, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander-fastlane (>= 4.4.6, < 5.0.0)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 4.0)
      excon (>= 0.71.0, < 1.0.0)
      faraday (~> 1.0)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 1.0)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-api-client (>= 0.37.0, < 0.39.0)
      google-cloud-storage (>= 1.15.0, < 2.0.0)
      highline (>= 1.7.2, < 2.0.0)
      json (< 3.0.0)
      jwt (>= 2.1.0, < 3)
      mini_magick (>= 4.9.4, < 5.0.0)
      multipart-post (~> 2.0.0)
      naturally (~> 2.2)
      plist (>= 3.1.0, < 4.0.0)
      rubyzip (>= 2.0.0, < 3.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      slack-notifier (>= 2.0.0, < 3.0.0)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    ffi (1.15.0)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    google-api-client (0.38.0)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (~> 0.9)
      httpclient (>= 2.8.1, < 3.0)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      signet (~> 0.12)
    google-apis-core (0.3.0)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (~> 0.14)
      httpclient (>= 2.8.1, < 3.0)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      rexml
      signet (~> 0.14)
      webrick
    google-apis-iamcredentials_v1 (0.2.0)
      google-apis-core (~> 0.1)
    google-apis-storage_v1 (0.3.0)
      google-apis-core (~> 0.1)
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.5.0)
      faraday (>= 0.17.3, < 2.0)
    google-cloud-errors (1.1.0)
    google-cloud-storage (1.31.0)
      addressable (~> 2.5)
      digest-crc (~> 0.4)
      google-apis-iamcredentials_v1 (~> 0.1)
      google-apis-storage_v1 (~> 0.1)
      google-cloud-core (~> 1.2)
      googleauth (~> 0.9)
      mini_mime (~> 1.0)
    googleauth (0.16.0)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.14)
    highline (1.7.10)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    jmespath (1.4.0)
    json (2.5.1)
    jwt (2.2.2)
    memoist (0.16.2)
    mini_magick (4.11.0)
    mini_mime (1.0.3)
    minitest (5.14.4)
    molinillo (0.6.6)
    multi_json (1.15.0)
    multipart-post (2.0.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    naturally (2.2.1)
    netrc (0.11.0)
    os (1.1.1)
    plist (3.6.0)
    public_suffix (4.0.6)
    rake (13.0.3)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rexml (3.2.4)
    rouge (2.0.7)
    ruby-macho (1.4.0)
    ruby2_keywords (0.0.4)
    rubyzip (2.3.0)
    security (0.1.3)
    signet (0.15.0)
      addressable (~> 2.3)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.8)
      CFPropertyList
      naturally
    slack-notifier (2.3.2)
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thread_safe (0.3.6)
    tty-cursor (0.7.1)
    tty-screen (0.8.1)
    tty-spinner (0.9.3)
      tty-cursor (~> 0.7)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.7)
    unicode-display_width (1.7.0)
    webrick (1.7.0)
    word_wrap (1.0.0)
    xcodeproj (1.19.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.1)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  cocoapods (~> 1.10.0)
  cocoapods-generate
  fastlane (~> 2.179.0)

BUNDLED WITH
   2.1.4
```

**Comment by deivid-rodriguez** [comment]
Most likely a dup of https://github.com/rubygems/rubygems/issues/4678. Will close in favour of that one!

**Comment by therohansanap** [comment]
@deivid-rodriguez Just a heads up - I am on macOS 11.4 Big Sur, while the issue #4678 is on macOS 10.13 High Sierra

**Comment by deivid-rodriguez** [comment]
Yeah, thanks. I still think it's the same underlying issue, but I'll reopen this if it turns out it's not.
