### ISSUE TITLE
bundle exec after 2.2.20 asks for gem repository credentials

### ISSUE THREAD

**Issue by kylev** [rubygems/rubygems#4825]
I use private gem servers for internal packages. `bundle exec` has started asking for credentials during `require "bundler/setup"`. This means Docker images with their gems fully baked in will fail to boot unless we place authentication credentials in our production runtime environment variables.

This can be reproduced using Docker community images.

```Dockerfile
FROM ruby:2.7.4

WORKDIR /app
COPY Gemfile Gemfile.lock ./

ARG BUNDLE_RUBYGEMS__PKG__GITHUB__COM

RUN gem install bundler:2.2.20 bundler:2.2.21

RUN bundle install && rm -rf /usr/local/bundle/cache
COPY . ./
```

Build with `docker build -t bundle-check --build-arg BUNDLE_RUBYGEMS__PKG__GITHUB__COM .`

### Which command did you run?

`docker run --rm -e BUNDLER_VERSION=2.2.21  bundle-check bundle exec ruby -e "require 'bundler/setup'; puts 'hello'"`

### What were you expecting to happen?

Output "hello".

It does this when BUNDLER_VERSION is 2.2.20, but not 2.2.21 or more recent versions (including 2.2.25)

### What actually happened?

```
/usr/local/bundle/gems/bundler-2.2.21/lib/bundler/fetcher/downloader.rb:43:in `fetch': Authentication is required for rubygems.pkg.github.com. (Bundler::Fetcher::AuthenticationRequiredError)
Please supply credentials for this source. You can do this by running:
`bundle config set --global rubygems.pkg.github.com username:password`
or by storing the credentials in the `BUNDLE_RUBYGEMS__PKG__GITHUB__COM` environment variable
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/fetcher/dependency.rb:10:in `available?'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/fetcher.rb:162:in `use_api'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `block in api_fetchers'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `select'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `api_fetchers'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:326:in `dependency_api_available?'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:515:in `all?'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:515:in `precompute_source_requirements_for_indirect_dependencies?'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:867:in `source_requirements'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:287:in `resolve'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:191:in `specs'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:260:in `specs_for'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:242:in `requested_specs'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/runtime.rb:20:in `setup'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler.rb:149:in `setup'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:136:in `with_level'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:88:in `silence'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
```

## Environment

```
Bundler       2.2.21
  Platforms   ruby, x86_64-linux
Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.1.6
  Gem Home    /usr/local/bundle
  Gem Path    /root/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.20.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-06-23
Git SHA           0b5db72094
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
source 'https://rubygems.org'

source 'https://rubygems.pkg.github.com/ELIDED/' do
  gem 'PRIVATE-GEM'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  remote: https://rubygems.pkg.github.com/ELIDED/
  specs:
    PRIVATE-GEM (1.1.20210802182721)
      google-protobuf (~> 3.15)
      twirp (~> 1.7)
    faraday (1.6.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    google-protobuf (3.17.3)
    multipart-post (2.1.1)
    ruby2_keywords (0.0.5)
    twirp (1.7.2)
      faraday (< 2)
      google-protobuf (~> 3.0, >= 3.7.0)

PLATFORMS
  ruby

DEPENDENCIES
  PRIVATE-GEM!

BUNDLED WITH
   2.1.4
```

**Comment by deivid-rodriguez** [comment]
This will most likely get fixed by https://github.com/rubygems/rubygems/pull/4805. If you're able to install `bundler` from the master branch and verify it, I appreciate it.

Also, I strongly suggest that you update your lockfile to the one generated by the latest bundler, because the one you have right now is insecure since it merges gems coming from different sources in a single section, making it vulnerable to dependency confusion issues (a malicious `PRIVATE-GEM` version `1.1.20210802182721` published to `rubygems.org` might end up getting installed).

**Comment by deivid-rodriguez** [comment]
Also another recommendation:

> docker run --rm -e BUNDLER_VERSION=2.2.21 bundle-check bundle exec ruby -e "require 'bundler/setup'; puts 'hello'"

`bundle exec ruby -e "require 'bundler/setup'"` is redundant, since `bundle exec` and `require "bundler/setup"` essentially do the same thing. I recommend you skip `bundle exec` to potentially save an extra process, and stick to `ruby -rbundler/setup -e "puts 'hello'"`.

**Comment by kylev** [comment]
Added this to my Dockerfile to hackishly install the current dev version.

```Dockerfile
RUN git clone https://github.com/rubygems/rubygems.git \
    && (cd rubygems/bundler ; gem build bundler.gemspec; gem install bundler*.gem)
```

The example now works, so it looks like the next version will solve the problem.


```console
$ docker run --rm -e BUNDLER_VERSION=2.3.0.dev bundle-check ruby -rbundler/setup -e "puts 'hello'"
hello

$ docker run --rm -e BUNDLER_VERSION=2.3.0.dev bundle-check bundle version
Bundler version 2.3.0.dev (2021-08-05 commit unknown)

$ docker run --rm -e BUNDLER_VERSION=2.2.21 bundle-check ruby -rbundler/setup -e "puts 'hello'"
/usr/local/bundle/gems/bundler-2.2.21/lib/bundler/fetcher/downloader.rb:43:in `fetch': Authentication is required for rubygems.pkg.github.com. (Bundler::Fetcher::AuthenticationRequiredError)
Please supply credentials for this source. You can do this by running:
`bundle config set --global rubygems.pkg.github.com username:password`
or by storing the credentials in the `BUNDLE_RUBYGEMS__PKG__GITHUB__COM` environment variable
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/fetcher/dependency.rb:10:in `available?'
	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/fetcher.rb:162:in `use_api'
# Trace elided
```
