### ISSUE TITLE
Crash installing dependencies in CI on jruby + Windows

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4836]
### Describe the problem as clearly as you can

Our CI run into the following crash:

```
$ bin/rake spec:parallel_deps[0m
shell: C:\msys64\usr\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
env:
  RGV: ..
  TMPDIR: D:\a\_temp
  HOME: C:\Users\runneradmin
  MSYS2_PATH_TYPE: inherit
  Path: C:\Users\runneradmin\.dotnet\tools;C:\Program Files\MongoDB\Server\5.0\bin;C:\aliyun-cli;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS\;C:\tools\zstd;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\2.7.3\x64;C:\tools\ghc-9.0.1\bin;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\R\R-4.1.0\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Rust\.cargo\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\hostedtoolcache\windows\go\1.15.14\x64\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\hostedtoolcache\windows\Java_Adopt_jdk\8.0.292-10\x64\bin;C:\npm\prefix;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Docker;C:\Program Files\PowerShell\7\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files\OpenSSL\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.1\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GVFS;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files (x86)\Microsoft BizTalk Server\;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
rake aborted!
Error when installing gems in D:/a/rubygems/rubygems/dev_gems.rb: Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies..................
Fetching public_suffix 4.0.6
Fetching ast 2.4.2
Installing public_suffix 4.0.6
Installing ast 2.4.2
Fetching aws-eventstream 1.1.1
Installing aws-eventstream 1.1.1
Fetching aws-partitions 1.453.0
Installing aws-partitions 1.453.0
Fetching jmespath 1.4.0
Using bundler 2.3.0.dev
Fetching diff-lcs 1.4.4
Installing diff-lcs 1.4.4
Installing jmespath 1.4.0
Fetching docile 1.3.5
Fetching multipart-post 2.1.1
Installing docile 1.3.5
Fetching jaro_winkler 1.5.4 (java)
Installing multipart-post 2.1.1
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff89dd5c138, pid=456, tid=0x00000000000017dc
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0xc138]
#
# Core dump written. Default location: D:\a\rubygems\rubygems\bundler\hs_err_pid456.mdmp
#
# An error report file with more information is saved as:
# D:\a\rubygems\rubygems\bundler\hs_err_pid456.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
D:/a/rubygems/rubygems/bundler/spec/support/rubygems_ext.rb:123:in `install_gems'
D:/a/rubygems/rubygems/bundler/spec/support/rubygems_ext.rb:12:in `dev_setup'
D:/a/rubygems/rubygems/bundler/Rakefile:13:in `block in <main>'
D:/a/rubygems/rubygems/bundler/spec/support/rubygems_ext.rb:99:in `gem_load_and_activate'
D:/a/rubygems/rubygems/bundler/spec/support/rubygems_ext.rb:18:in `gem_load'
Tasks: TOP => spec:parallel_deps => dev:deps

```

See https://github.com/rubygems/rubygems/runs/3290772792.

### Post steps to reproduce the problem

It's a flaky, hard repro :sweat:.

Anyways, I guess it's related to #4822, so we might want to partially revert that PR again. I'll wait a bit longer to confirm there's no other issues on other Windows rubies, so that we can still keep parallel installation there.

### Which command did you run?

`bundle install`.

### What were you expecting to happen?

Success.

### What actually happened?

:bomb:.

**Comment by deivid-rodriguez** [comment]
It hasn't reappeared in more than two weeks, so I'll close this.
