### ISSUE TITLE
Fix RUBYGEMS_GEMDEPS with global gem

### ISSUE THREAD

**Issue by bkuhlmann** [rubygems/rubygems#4862]
I'm having a problem or would like to suggest a feature.

My current problem is that I can't use `RUBYGEMS_GEMDEPS` with a globally installed gem for current project. Best I can tell is that this issue is somewhat related to this [earlier issue](https://github.com/rubygems/rubygems/issues/1034).

Steps to Recreate:

- Per the [3.2.26 release notes](https://blog.rubygems.org/2021/08/17/3.2.26-released.html), add `export RUBYGEMS_GEMDEPS=-` to your global shell.
- Clone and change directory to the root of a Ruby project like [Sublime Text Setup](https://www.alchemists.io/projects/sublime_text_setup), for example.
- Install a gem like, [Milestoner](https://www.alchemists.io/projects/milestoner) as a global gem.
- Try running `milestoner --status` from the root of the Sublime Text Setup project, you'll then get the following error:

``` 
/Users/bkuhlmann/.cache/frum/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:362:in `block in replace_bin_path': can't find executable milestoner for gem milestoner. milestoner is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/bkuhlmann/.cache/frum/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:390:in `block in replace_bin_path'
	from /var/folders/j1/szrwbp9d1jg351ghw4f7bcym0000gn/T/frum_77591_1629336054529/bin/milestoner:25:in `<main>'
```

I'm using [Frum](https://github.com/tako8ki/frum) as my Ruby Version Manager. Even though Milestoner is installed as a global gem but not defined in my Sublime Text Project, I don't think the above error should show up, right?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
3.2.26
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Indeed! We'll have to figure something out for global gems. Probably falling back to global gems if the gem is not found in the current bundle could work, or maybe allowing users to whitelist certain gems to allow this fallback to happen for them. Not fully sure.

**Comment by bkuhlmann** [comment]
:bow: David. That'd be great as I'm quite excited to use this feature more! Yeah, much like how I use [Runcom](https://www.alchemists.io/projects/runcom) to provide graceful fallbacks to the [XDG](https://www.alchemists.io/projects/xdg), I think it'd be awesome if RubyGems scanned for local project support first (i.e. `Gemfile` / `gems.rb`), then searched globally, and finally printed a similar error to the above when all of those checks fail. :tada:

**Comment by mockdeep** [comment]
Same issue here. We install `foreman` and `mailcatcher` outside of our Gemfile, but cannot run them when `RUBYGEMS_GEMDEPS=-`. [`rubygems-bundler`](https://github.com/rvm/rubygems-bundler) doesn't have this issue.
