### ISSUE TITLE
Plugin installation is not idempotent

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4863]
First install works

```
bundle plugin install diffend
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.26
Fetching diffend 0.2.49
Installing diffend 0.2.49
Installed plugin diffend
```

But retrying the install procedure after a successful install:

```
bundle plugin install diffend
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.26
Using diffend 0.2.49
Failed to install the following plugins: `diffend`. The underlying error was: plugins.rb was not found in the plugin..
 /home/mencio/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/plugin.rb:263:in `validate_plugin!'
 /home/mencio/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/plugin.rb:249:in `block in save_plugins'
```

_Originally posted by @mensfeld in https://github.com/rubygems/rubygems/issues/4730#issuecomment-901691154_

**Comment by deivid-rodriguez** [comment]
It should be fixed by https://github.com/rubygems/rubygems/pulls/4864!
