### ISSUE TITLE
`bundle exec <foo>` with `BUNDLE_AUTO_INSTALL` enable fails; running `bundle install` separately works

### ISSUE THREAD

**Issue by jklausa** [rubygems/rubygems#4880]
### Describe the problem as clearly as you can

Heyo! 

I've run into a situation, where with local bundle storage blown away, running `bundle install; bundle exec whatever` suceeds, whereas doing `bundle exec whatever` fails to run properly.

At first I thought it was a problem with the project I was using, and I detailed the problem here:

https://github.com/fastlane/fastlane/pull/18760

### Post steps to reproduce the problem

I'm running stock ruby on macOS 11.5.2 and 12 beta.

Here's my Gemfile, and `.bundle/config`:

Gemfile:
```
source "https://rubygems.org"

gem "cocoapods"
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

(`Pluginfile` is as follows:

```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-versioning'
```
)
and my `.bundle/config`:
```
$ more .bundle/config
---
BUNDLE_PATH: "vendor/bundle"
BUNDLE_AUTO_INSTALL: "true"
```

### Which command did you run?

`bundle exec fastlane <name_of_my_fastlane_lane>`

### What were you expecting to happen?

I expected my fastlane lane to execute.

### What actually happened?

```
bundler: failed to load command: fastlane (/Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/bin/fastlane)
Traceback (most recent call last):
	23: from /usr/local/bin/bundle:23:in `<main>'
	22: from /usr/local/bin/bundle:23:in `load'
	21: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/exe/bundle:37:in `<top (required)>'
	20: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	19: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/exe/bundle:49:in `block in <top (required)>'
	18: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/cli.rb:24:in `start'
	17: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	16: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/cli.rb:30:in `dispatch'
	15: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	14: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	12: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/cli.rb:474:in `exec'
	11: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:28:in `run'
	10: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `kernel_load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `load'
	 8: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	 7: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	 6: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/gems/fastlane-2.192.0/bin/fastlane:23:in `<top (required)>'
	 5: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	 4: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	 3: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	 2: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	 1: from /Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/gems/fastlane-2.192.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:91:in `run!'
/Users/klausa/Developer/gorillas-ios-1.0/vendor/bundle/ruby/2.6.0/gems/fastlane-2.192.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:65:in `parse_global_options': undefined method `require_exact=' for #<OptionParser:0x00007fef0e04ed40> (NoMethodError)
```
### If not included with the output of your command, run `bundle env` and paste the output below

`[14:54:22] klausa-g16:klausa:~/Developer/gorillas-ios-1.0 git:(facelift*) $ bundle env`
`## Environment`

```
Bundler       2.2.21
  Platforms   ruby, universal-darwin-21
Ruby          2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin21]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.0.3
  Gem Home    /Library/Ruby/Gems/2.6.0
  Gem Path    /Users/klausa/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/klausa
  User Path   /Users/klausa/.gem/ruby/2.6.0
  Bin Dir     /usr/local/bin
Tools
  Git         2.30.1 (Apple Git-130)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-06-23
Git SHA           0b5db72094
Released Version  true
```

## Bundler settings

```
auto_install
  Set for your local app (/Users/klausa/Developer/gorillas-ios-1.0/.bundle/config): true
  Set for the current user (/Users/klausa/.bundle/config): true
path
  Set for your local app (/Users/klausa/Developer/gorillas-ios-1.0/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "cocoapods"
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

### fastlane/Pluginfile

```ruby
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-versioning'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.3)
    activesupport (5.2.6)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    artifactory (3.0.15)
    atomos (0.1.3)
    aws-eventstream (1.1.1)
    aws-partitions (1.491.0)
    aws-sdk-core (3.119.1)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.46.0)
      aws-sdk-core (~> 3, >= 3.119.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.99.0)
      aws-sdk-core (~> 3, >= 3.119.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.4)
      aws-eventstream (~> 1, >= 1.0.2)
    babosa (1.0.4)
    claide (1.0.3)
    cocoapods (1.10.2)
      addressable (~> 2.6)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.10.2)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.4.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.4.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.6.6)
      nap (~> 1.0)
      ruby-macho (~> 1.4)
      xcodeproj (>= 1.19.0, < 2.0)
    cocoapods-core (1.10.2)
      activesupport (> 5.0, < 6)
      addressable (~> 2.6)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (1.4.0)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.5.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored (1.2)
    colored2 (3.1.2)
    commander (4.6.0)
      highline (~> 2.0.0)
    concurrent-ruby (1.1.9)
    declarative (0.0.20)
    digest-crc (0.6.4)
      rake (>= 12.0.0, < 14.0.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    emoji_regex (3.2.2)
    escape (0.0.4)
    ethon (0.14.0)
      ffi (>= 1.15.0)
    excon (0.85.0)
    faraday (1.7.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-cookie_jar (0.0.7)
      faraday (>= 0.8.0)
      http-cookie (~> 1.0.0)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday_middleware (1.1.0)
      faraday (~> 1.0)
    fastimage (2.2.5)
    fastlane (2.192.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.8, < 3.0.0)
      artifactory (~> 3.0)
      aws-sdk-s3 (~> 1.0)
      babosa (>= 1.0.3, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander (~> 4.6)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 4.0)
      excon (>= 0.71.0, < 1.0.0)
      faraday (~> 1.0)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 1.0)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-apis-androidpublisher_v3 (~> 0.3)
      google-apis-playcustomapp_v1 (~> 0.1)
      google-cloud-storage (~> 1.31)
      highline (~> 2.0)
      json (< 3.0.0)
      jwt (>= 2.1.0, < 3)
      mini_magick (>= 4.9.4, < 5.0.0)
      multipart-post (~> 2.0.0)
      naturally (~> 2.2)
      optparse (~> 0.1.1)
      plist (>= 3.1.0, < 4.0.0)
      rubyzip (>= 2.0.0, < 3.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    fastlane-plugin-versioning (0.5.0)
    ffi (1.15.3)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    google-apis-androidpublisher_v3 (0.10.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-core (0.4.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    google-apis-iamcredentials_v1 (0.7.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-playcustomapp_v1 (0.5.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-storage_v1 (0.6.0)
      google-apis-core (>= 0.4, < 2.a)
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.5.0)
      faraday (>= 0.17.3, < 2.0)
    google-cloud-errors (1.1.0)
    google-cloud-storage (1.34.1)
      addressable (~> 2.5)
      digest-crc (~> 0.4)
      google-apis-iamcredentials_v1 (~> 0.1)
      google-apis-storage_v1 (~> 0.1)
      google-cloud-core (~> 1.6)
      googleauth (>= 0.16.2, < 2.a)
      mini_mime (~> 1.0)
    googleauth (0.17.0)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.14)
    highline (2.0.3)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    jmespath (1.4.0)
    json (2.5.1)
    jwt (2.2.3)
    memoist (0.16.2)
    mini_magick (4.11.0)
    mini_mime (1.1.1)
    minitest (5.14.4)
    molinillo (0.6.6)
    multi_json (1.15.0)
    multipart-post (2.0.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    naturally (2.2.1)
    netrc (0.11.0)
    optparse (0.1.1)
    os (1.1.1)
    plist (3.6.0)
    public_suffix (4.0.6)
    rake (13.0.6)
    representable (3.1.1)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rexml (3.2.5)
    rouge (2.0.7)
    ruby-macho (1.4.0)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    security (0.1.3)
    signet (0.15.0)
      addressable (~> 2.3)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.8)
      CFPropertyList
      naturally
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thread_safe (0.3.6)
    trailblazer-option (0.1.1)
    tty-cursor (0.7.1)
    tty-screen (0.8.1)
    tty-spinner (0.9.3)
      tty-cursor (~> 0.7)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.7)
    unicode-display_width (1.7.0)
    webrick (1.7.0)
    word_wrap (1.0.0)
    xcodeproj (1.21.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.1)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  universal-darwin-19
  universal-darwin-20
  universal-darwin-21

DEPENDENCIES
  cocoapods
  fastlane
  fastlane-plugin-versioning

BUNDLED WITH
   2.2.21
```

**Comment by rowanmulder** [comment]
We've upgraded the build machine to the new Bundler 2.2.31, which should include the optparse patch. However it seems upon building, it shows still the same error:

**bundler: failed to load command: fastlane (/Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/bin/fastlane)
/Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:65:in `parse_global_options': undefined method `require_exact=' for #<OptionParser:0x00007fb0d14e5fa0> (NoMethodError)**
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:91:in `run!'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/bin/bundle:23:in `load'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/bin/bundle:23:in `<main>'

**Comment by deivid-rodriguez** [comment]
Could you open a separate ticket with the information requested by the issue template? Thanks!

**Comment by jnetRepo** [comment]
I solved my issue by adding (bundle install) again before called (bundle exec) as in here: 
cd android && sudo chmod +x gradlew && bundle install && bundle exec fastlane alpha
