### ISSUE TITLE
Permission issue when installing nio4r gem

### ISSUE THREAD

**Issue by cguess** [rubygems/rubygems#4888]
### Describe the problem as clearly as you can

Attempting to install nio4r throws a permission error when trying to access workflows.

### Post steps to reproduce the problem

---
MacOS 12 Beta (latest)
MacBook Pro M1
Ruby 3.0.2 via rbenv
---

`bundle install`  when setting up a Rails system.

### Which command did you run?

I ran the command `/Users/username/.rbenv/versions/3.0.2/bin/bundle install`

### What were you expecting to happen?

Properly install, which works on MacOS 11, Windows 10 Linux subsystem and Raspberry Pi OS (latest)

### What actually happened?

Errno::EACCES: Permission denied @ rb_sysopen - /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nio4r-2.5.8/.github/workflows/workflow.yml
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:424:in `initialize'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:424:in `open'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:424:in `block (2 levels) in extract_tar_gz'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:405:in `block in extract_tar_gz'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:534:in `block in open_tar_gz'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:531:in `wrap'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:531:in `open_tar_gz'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:404:in `extract_tar_gz'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:384:in `block (2 levels) in extract_files'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:381:in `block in extract_files'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `open'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/package.rb:378:in `extract_files'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:837:in `extract_files'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:24:in `install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/source/rubygems.rb:182:in `install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:67:in `install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:171:in `install_serially'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:97:in `call'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer.rb:263:in `install_in_parallel'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer.rb:210:in `install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer.rb:90:in `block in run'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/process_lock.rb:19:in `rescue in lock'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/process_lock.rb:15:in `lock'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer.rb:72:in `run'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/installer.rb:24:in `install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/cli/install.rb:60:in `run'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/cli.rb:259:in `block in install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/settings.rb:131:in `temporary'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/cli.rb:258:in `install'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
  /Users/cwg15/.rbenv/versions/3.0.2/bin/bundle:23:in `load'
  /Users/cwg15/.rbenv/versions/3.0.2/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.22
  Platforms   ruby, arm64-darwin-21
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [arm64-darwin21]
  Full Path   /Users/cwg15/.rbenv/versions/3.0.2/bin/ruby
  Config Dir  /Users/cwg15/.rbenv/versions/3.0.2/etc
RubyGems      3.2.22
  Gem Home    /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  Gem Path    /Users/cwg15/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0:/Users/cwg15/.gem/ruby/3.0.0
  User Home   /Users/cwg15
  User Path   /Users/cwg15/.gem/ruby/3.0.0
  Bin Dir     /Users/cwg15/.rbenv/versions/3.0.2/bin
OpenSSL
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1k  25 Mar 2021
  Cert File   /Users/cwg15/.rbenv/versions/3.0.2/openssl/ssl/cert.pem
  Cert Dir    /Users/cwg15/.rbenv/versions/3.0.2/openssl/ssl/certs
Tools
  Git         2.32.0
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-08-30
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/cwg15/.bundle/config): true
gem.ci
  Set for the current user (/Users/cwg15/.bundle/config): "github"
gem.coc
  Set for the current user (/Users/cwg15/.bundle/config): true
gem.mit
  Set for the current user (/Users/cwg15/.bundle/config): true
gem.rubocop
  Set for the current user (/Users/cwg15/.bundle/config): "true"
gem.test
  Set for the current user (/Users/cwg15/.bundle/config): "minitest"
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 6.1.0"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use Puma as the app server
gem "puma", "~> 5.0"
# Use SCSS for stylesheets
gem "sass-rails", ">= 6"
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem "webpacker", "~> 5.0"
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "turbolinks", "~> 5"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.7"
# Use Redis adapter to run Action Cable in production
gem "redis", "~> 4.0"
# Use PgSearch for Postgres multi-table search
gem "pg_search", "~> 2.3.5"
# Use Scenic to create and maintain a materialized view
gem "scenic", "~> 1.5.4"
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]

  # Bullet is a gem to find and detect N+1 queries in development
  gem "bullet"

  # Add the ability to load `.env` files on launch
  gem "dotenv-rails"

  # Jard is an improvement on Byebug
  gem "ruby_jard"
  gem "pry-byebug"

  # RuboCop is an excellent linter, we keep it in `test` for CI
  gem "rubocop", require: false
  gem "rubocop-rails", require: false # Rails specific styles
  gem "rubocop-rails_config", require: false # More Rails stuff
  gem "rubocop-performance", require: false # Performance checks
  gem "rubocop-sorbet", require: false # Check Sorbet
  gem "rubocop-minitest", require: false # For checking tests
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "web-console", ">= 4.1.0"
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem "rack-mini-profiler", "~> 2.0"
  gem "listen", "~> 3.3"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"

  # Sorbet is a type-checker for Ruby. We prefer statically-defined types when possible
  gem "sorbet"
  # This is required for Ruby 3 from Sorbet
  gem "sorted_set"

  # Tmuxinator lets us set up standard development environments easily
  gem "tmuxinator"

  # We use Yard for all of our documentation
  gem "yard", require: false
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  # Easy installation and use of web drivers to run system tests with browsers
  gem "webdrivers"

  # Code coverage so we can check if our tests actually cover everything
  gem "simplecov", require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# Commenting out because we're not using Windows or JRuby and this throws a warning during bundler.
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# The production runtime for sorbet
gem "sorbet-runtime"

# Rails specific features for Sorbet
gem "sorbet-rails"

# For validating URL, the fork adds array of urls validation as well (yes, the difference in URL
# and gem name is on purpose)
gem "validate_url"

# Figaro lets us configure and require environment variable at boot, instead of getting stuck with a
# bad deployment
gem "figaro"

# Typhoneus handles URL request to outside websites extremely efficiently
gem "typhoeus"

# Hotwire, to make better website without JS
gem "hotwire-rails"

# TailwindCSS
gem "tailwindcss-rails", "~> 0.3.3"

# A headless chrome browser for interacting with website
gem "ferrum", "~> 0.11"

# Some basic OS checks, specifically to check to configure our scrapers for dev/prod
gem "os"

# Shrine is a better alternative to ActiveStorage for handling file attachments and the like
gem "shrine", "~> 3.0"

# A differential-hash library for image perceptual hashing. Surprisingly maintained.
# We don't have it versioned locked because it's been almost a year since one was released, but
# there's been plenty of commits
gem "dhash-vips", git: "https://github.com/Nakilon/dhash-vips.git"

# Stremio-ffmpeg use the ffmpeg library to process our video files
gem "streamio-ffmpeg"

# Scraper gems
# Local testing
# gem "zorki", "0.1.0", path: "~/Repositories/zorki" # instagram
# gem "birdsong", "0.1.0", path: "~/Repositories/birdsong" # twitter

gem "zorki", "0.1.0", git: "https://github.com/cguess/zorki"
gem "birdsong", "0.1.0", git: "https://github.com/cguess/birdsong"

# A progress bar for our Rake tasks
gem "ruby-progressbar"

# For validating JSON input on the API
gem "json_schemer"

# Devise is used for authentication and user management
gem "devise", "~> 4.8.0"
```

### Gemfile.lock

```
GIT
  remote: https://github.com/Nakilon/dhash-vips.git
  revision: 1d03d1021858f1187a46c58a70f4290809e94143
  specs:
    dhash-vips (0.1.1.3)
      ruby-vips (~> 2.0)

GIT
  remote: https://github.com/cguess/birdsong
  revision: d314c04b11376db0f623289a8f24068a72f76c17
  specs:
    birdsong (0.1.0)
      oauth (~> 0.5.6)
      typhoeus (~> 1.4.0)

GIT
  remote: https://github.com/cguess/zorki
  revision: b6aac3c508905aa200fbef1c96c3c4b8b6221e68
  specs:
    zorki (0.1.0)
      apparition
      capybara
      oj
      selenium-webdriver
      typhoeus

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.4.1)
      actionpack (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.4.1)
      actionpack (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activestorage (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      mail (>= 2.7.1)
    actionmailer (6.1.4.1)
      actionpack (= 6.1.4.1)
      actionview (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.4.1)
      actionview (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.4.1)
      actionpack (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activestorage (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      nokogiri (>= 1.8.5)
    actionview (6.1.4.1)
      activesupport (= 6.1.4.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.4.1)
      activesupport (= 6.1.4.1)
      globalid (>= 0.3.6)
    activemodel (6.1.4.1)
      activesupport (= 6.1.4.1)
    activerecord (6.1.4.1)
      activemodel (= 6.1.4.1)
      activesupport (= 6.1.4.1)
    activestorage (6.1.4.1)
      actionpack (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      marcel (~> 1.0.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    apparition (0.6.0)
      capybara (~> 3.13, < 4)
      websocket-driver (>= 0.6.5)
    ast (2.4.2)
    bcrypt (3.1.16)
    bindex (0.8.1)
    bootsnap (1.7.7)
      msgpack (~> 1.0)
    builder (3.2.4)
    bullet (6.1.5)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11)
    byebug (11.1.3)
    capybara (3.35.3)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (3.0.0)
    cliver (0.3.2)
    coderay (1.1.3)
    commander (4.6.0)
      highline (~> 2.0.0)
    concurrent-ruby (1.1.9)
    content_disposition (1.0.0)
    crass (1.0.6)
    devise (4.8.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    docile (1.4.0)
    dotenv (2.7.6)
    dotenv-rails (2.7.6)
      dotenv (= 2.7.6)
      railties (>= 3.2)
    down (5.2.3)
      addressable (~> 2.8)
    ecma-re-validator (0.3.0)
      regexp_parser (~> 2.0)
    erubi (1.10.0)
    erubis (2.7.0)
    ethon (0.14.0)
      ffi (>= 1.15.0)
    ferrum (0.11)
      addressable (~> 2.5)
      cliver (~> 0.3)
      concurrent-ruby (~> 1.1)
      websocket-driver (>= 0.6, < 0.8)
    ffi (1.15.3)
    figaro (1.2.0)
      thor (>= 0.14.0, < 2)
    globalid (0.5.2)
      activesupport (>= 5.0)
    hana (1.3.7)
    highline (2.0.3)
    hotwire-rails (0.1.3)
      rails (>= 6.0.0)
      stimulus-rails
      turbo-rails
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.2)
      activesupport (>= 5.0.0)
    json_schemer (0.2.18)
      ecma-re-validator (~> 0.3)
      hana (~> 1.3)
      regexp_parser (~> 2.0)
      uri_template (~> 0.7)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.12.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.1)
    method_source (1.0.0)
    mini_mime (1.1.1)
    mini_portile2 (2.6.1)
    minitest (5.14.4)
    msgpack (1.4.2)
    multi_json (1.15.0)
    nio4r (2.5.8)
    nokogiri (1.12.3)
      mini_portile2 (~> 2.6.1)
      racc (~> 1.4)
    nokogiri (1.12.3-x86_64-darwin)
      racc (~> 1.4)
    oauth (0.5.6)
    oj (3.13.2)
    orm_adapter (0.5.0)
    os (1.1.1)
    parallel (1.20.1)
    parlour (6.0.1)
      commander (~> 4.5)
      parser
      rainbow (~> 3.0)
      sorbet-runtime (>= 0.5)
    parser (3.0.2.0)
      ast (~> 2.4.1)
    pg (1.2.3)
    pg_search (2.3.5)
      activerecord (>= 5.2)
      activesupport (>= 5.2)
    polyfill (1.9.0)
    pry (0.13.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.9.0)
      byebug (~> 11.0)
      pry (~> 0.13.0)
    public_suffix (4.0.6)
    puma (5.4.0)
      nio4r (~> 2.0)
    racc (1.5.2)
    rack (2.2.3)
    rack-mini-profiler (2.3.2)
      rack (>= 1.2.0)
    rack-proxy (0.7.0)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.1.4.1)
      actioncable (= 6.1.4.1)
      actionmailbox (= 6.1.4.1)
      actionmailer (= 6.1.4.1)
      actionpack (= 6.1.4.1)
      actiontext (= 6.1.4.1)
      actionview (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activemodel (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activestorage (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      bundler (>= 1.15.0)
      railties (= 6.1.4.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (6.1.4.1)
      actionpack (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      method_source
      rake (>= 0.13)
      thor (~> 1.0)
    rainbow (3.0.0)
    rake (13.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rbtree (0.4.4)
    redis (4.4.0)
    regexp_parser (2.1.1)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rexml (3.2.5)
    rubocop (1.19.1)
      parallel (~> 1.10)
      parser (>= 3.0.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.9.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.11.0)
      parser (>= 3.0.1.1)
    rubocop-minitest (0.15.0)
      rubocop (>= 0.90, < 2.0)
    rubocop-packaging (0.5.1)
      rubocop (>= 0.89, < 2.0)
    rubocop-performance (1.11.5)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rails (2.11.3)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.7.0, < 2.0)
    rubocop-rails_config (1.7.0)
      railties (>= 5.0)
      rubocop (>= 1.19)
      rubocop-ast (>= 1.0.1)
      rubocop-minitest (~> 0.15)
      rubocop-packaging (~> 0.5)
      rubocop-performance (~> 1.11)
      rubocop-rails (~> 2.0)
    rubocop-sorbet (0.6.2)
      rubocop
    ruby-progressbar (1.11.0)
    ruby-vips (2.1.3)
      ffi (~> 1.12)
    ruby_jard (0.3.1)
      byebug (>= 9.1, < 12.0)
      pry (~> 0.13.0)
      tty-screen (~> 0.8.1)
    rubyzip (2.3.2)
    safe_type (1.1.1)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    scenic (1.5.4)
      activerecord (>= 4.0.0)
      railties (>= 4.0.0)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    semantic_range (3.0.0)
    set (1.0.1)
    shrine (3.4.0)
      content_disposition (~> 1.0)
      down (~> 5.1)
    simplecov (0.21.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.3)
    sorbet (0.5.9070)
      sorbet-static (= 0.5.9070)
    sorbet-coerce (0.5.0)
      polyfill (~> 1.8)
      safe_type (~> 1.1, >= 1.1.1)
      sorbet-runtime (>= 0.4.4704)
    sorbet-rails (0.7.4)
      method_source (>= 0.9.2)
      parlour (>= 4.0.1)
      parser (>= 2.7)
      sorbet-coerce (>= 0.2.6)
      sorbet-runtime (>= 0.5)
    sorbet-runtime (0.5.9070)
    sorbet-static (0.5.9070-universal-darwin-14)
    sorbet-static (0.5.9070-universal-darwin-15)
    sorbet-static (0.5.9070-universal-darwin-16)
    sorbet-static (0.5.9070-universal-darwin-17)
    sorbet-static (0.5.9070-universal-darwin-18)
    sorbet-static (0.5.9070-universal-darwin-19)
    sorbet-static (0.5.9070-universal-darwin-20)
    sorbet-static (0.5.9070-universal-darwin-21)
    sorbet-static (0.5.9070-x86_64-linux)
    sorted_set (1.0.3)
      rbtree
      set (~> 1.0)
    spring (2.1.1)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    stimulus-rails (0.3.9)
      rails (>= 6.0.0)
    streamio-ffmpeg (3.0.2)
      multi_json (~> 1.8)
    tailwindcss-rails (0.3.3)
      rails (>= 6.0.0)
    thor (1.1.0)
    tilt (2.0.10)
    tmuxinator (3.0.1)
      erubis (~> 2.6)
      thor (~> 1.0)
      xdg (~> 2.2, >= 2.2.5)
    tty-screen (0.8.1)
    turbo-rails (0.7.6)
      rails (>= 6.0.0)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.0.0)
    uniform_notifier (1.14.2)
    uri_template (0.7.0)
    validate_url (1.0.13)
      activemodel (>= 3.0.0)
      public_suffix
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.1.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (4.6.1)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (>= 3.0, < 4.0)
    webpacker (5.4.2)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xdg (2.2.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    yard (0.9.26)
    zeitwerk (2.4.2)

PLATFORMS
  ruby
  x86_64-darwin-20

DEPENDENCIES
  birdsong (= 0.1.0)!
  bootsnap (>= 1.4.4)
  bullet
  byebug
  capybara (>= 3.26)
  devise (~> 4.8.0)
  dhash-vips!
  dotenv-rails
  ferrum (~> 0.11)
  figaro
  hotwire-rails
  jbuilder (~> 2.7)
  json_schemer
  listen (~> 3.3)
  os
  pg (~> 1.1)
  pg_search (~> 2.3.5)
  pry-byebug
  puma (~> 5.0)
  rack-mini-profiler (~> 2.0)
  rails (~> 6.1.0)
  redis (~> 4.0)
  rubocop
  rubocop-minitest
  rubocop-performance
  rubocop-rails
  rubocop-rails_config
  rubocop-sorbet
  ruby-progressbar
  ruby_jard
  sass-rails (>= 6)
  scenic (~> 1.5.4)
  selenium-webdriver
  shrine (~> 3.0)
  simplecov
  sorbet
  sorbet-rails
  sorbet-runtime
  sorted_set
  spring
  streamio-ffmpeg
  tailwindcss-rails (~> 0.3.3)
  tmuxinator
  turbolinks (~> 5)
  typhoeus
  validate_url
  web-console (>= 4.1.0)
  webdrivers
  webpacker (~> 5.0)
  yard
  zorki (= 0.1.0)!

RUBY VERSION
   ruby 3.0.2p107

BUNDLED WITH
   2.2.22
```

**Comment by cguess** [comment]
Thanks so much @deivid-rodriguez! I'd be curious if there's an issue tracker for the `fileutils` bug that I could follow along with or perhaps even assist on?

**Comment by simi** [comment]
@cguess https://github.com/ruby/fileutils

**Comment by deivid-rodriguez** [comment]
Sure!

I created [an issue](https://github.com/ruby/fileutils/issues/57) and [a pull request](https://github.com/ruby/fileutils/pull/58). The backwards compatibility of the fix is quite subject to interpretation, but we don't really need to depend on this fix. The solution to this issue in bundler should be to try fix the permissions of the gem installation folder before trying to remove it, so that the removal doesn't fail and we don't get weird errors later on.

**Comment by deivid-rodriguez** [comment]
I changed the pull request to automatically fix permissions, since it's backwards compatible and it should completely fix this issue :). I'll open a PR porting the `fileutils` patch to our vendored copy and including a regression spec.
