### ISSUE TITLE
bundle install fails with fresh rails 6 project using ruby 3.0.2 on Github

### ISSUE THREAD

**Issue by tjarratt-backmarket** [rubygems/rubygems#4922]
### Describe the problem as clearly as you can

I created [a brand new rails 6.1.4.1 project with CRuby 3.0.2](https://github.com/tjarratt/scrum-didly-testing), and [a minimal github action workflow](https://github.com/tjarratt/scrum-didly-testing/blob/main/.github/workflows/pipeline.yml) and ran head-first into a very strange error. My CI runs consistently result in the same error during the `bundle install` step on x86_64-linux. I am not using self-hosted runners, just github's own linux machines. My CI pipeline is very run of the mill, it's using https://github.com/ruby/setup-ruby and just runs `bundle install` after `setup-ruby` does its job.

You can see an example of the failure in [this test run](https://github.com/tjarratt/scrum-didly-testing/runs/3457587536?check_suite_focus=true).

Stacktrace below :

```
NoMethodError: undefined method `full_name' for nil:NilClass
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:123:in `each'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:122:in `each'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:100:in `call'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:263:in `install_in_parallel'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:210:in `install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:90:in `block in run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/process_lock.rb:12:in `block in lock'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/process_lock.rb:9:in `open'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/process_lock.rb:9:in `lock'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:72:in `run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:24:in `install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/install.rb:60:in `run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:252:in `block in install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/settings.rb:131:in `temporary'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:251:in `install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:31:in `dispatch'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:25:in `start'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:49:in `block in <top (required)>'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
```

### Post steps to reproduce the problem

* Install ruby 3.0.2
* gem install Rails (version 6.1.4.1 as of the time of this writing)
* bundle install
* write a minimal GitHub actions pipeline
* push to GitHub
* observe your CI run fail
* Downgrade `.ruby_version` to 2.7.4
* push to github
* observe your CI run pass

### Which command did you run?

On CI, I run the following steps :

* setup ruby 3.0.2
* gem install bundler -v 2.2.26
* bundle install

### What were you expecting to happen?

Expected the dependencies from my `Gemfile` to be installed on CI, so that tests can be run.

### What actually happened?

An error is raised internally in bundler, preventing my CI run from doing anything useful at all.

**Comment by deivid-rodriguez** [comment]
Thanks for the report. It seems like this should be easy to reproduce so I will try.

**Comment by tvaroglu** [comment]
Following - also having same issue

**Comment by stevepolitodesign** [comment]
I'm running into this issue too. [It happened when I downgraded from 6.1.4 to 6.0.0](https://github.com/stevepolitodesign/unsubscribe/pull/15/files).

https://github.com/stevepolitodesign/unsubscribe/pull/15/checks?check_run_id=3695454827

**Comment by stevepolitodesign** [comment]
I was able to solve this by removing `Gemfile.lock` and running `bundle _2.1.4_ install` locally.

** Here are the diffs in `Gemfile.lock` when the build started failing:**

https://github.com/stevepolitodesign/unsubscribe/pull/15/commits/9f64cb191b88e0cd08e329625107d43f839aeb71#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731f

 **Here's what it looked like when I was able to fix the build**
https://github.com/stevepolitodesign/unsubscribe/pull/15/commits/b73af90d9c10cc9341da70511c667cd57984d2cb#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731f

**Other items to note**

- Somehow `x86_64-darwin-19` was added to `PLATFORMS` when the build failed.

**Comment by deivid-rodriguez** [comment]
I managed to reproduce this, I'll fix it soon. The lockfile here is corrupt, and bundler checks detect that situation are crashing. I still need to investigate why this corrupt lockfile is being generated, but once this issue is fixed it should be automatically corrected by `bundle install` anyways.

**Comment by nghoapc** [comment]
Following - I also having same issue with
Bundle: 2.2.25
Ruby: 3.0.0p0
Rails: 6.1.4.1

**Comment by danger89** [comment]
I actually still have this issue: https://gitlab.melroy.org/melroy/melroy-site/-/jobs/8978#L107
