### ISSUE TITLE
test/rubygems/test_gem.rb: "ArgumentError: Bundler::GemfileError is already registered" by isolated test.

### ISSUE THREAD

**Issue by junaruga** [rubygems/rubygems#4957]
I'm having a problem or would like to suggest a feature.

My current problem is that when running the following test, I see some failures with `ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered`. As a reference, the `rake test` works.

On the latest master branch commit: `3d563e2a3880a64fec27c343bc96d6d8388bb7cf`, on Fedora 34, Ruby 3.0.2.

```
$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

$ rake setup

$ ruby -Ilib:test test/rubygems/test_gem.rb
Loaded suite test/rubygems/test_gem
Started
......../usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/jaruga/var/git/rubygems/bundler/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/jaruga/var/git/rubygems/bundler/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/jaruga/var/git/rubygems/bundler/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/jaruga/var/git/rubygems/bundler/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/jaruga/var/git/rubygems/bundler/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/jaruga/var/git/rubygems/bundler/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
E
=========================================================================================================
Error: test_auto_activation_of_specific_gemdeps_file(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:1677:in `block in test_auto_activation_of_specific_gemdeps_file'
test/rubygems/test_gem.rb:2125:in `with_rubygems_gemdeps'
test/rubygems/test_gem.rb:1676:in `test_auto_activation_of_specific_gemdeps_file'
=========================================================================================================
E
=========================================================================================================
Error: test_auto_activation_of_used_gemdeps_file(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:1701:in `block in test_auto_activation_of_used_gemdeps_file'
test/rubygems/test_gem.rb:2125:in `with_rubygems_gemdeps'
test/rubygems/test_gem.rb:1698:in `test_auto_activation_of_used_gemdeps_file'
=========================================================================================================
....................................................E
=========================================================================================================
Error: test_self_find_files_with_gemfile(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:845:in `test_self_find_files_with_gemfile'
=========================================================================================================
........................................................E
=========================================================================================================
Error: test_self_use_gemdeps(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:674:in `block in test_self_use_gemdeps'
test/rubygems/test_gem.rb:2125:in `with_rubygems_gemdeps'
test/rubygems/test_gem.rb:665:in `test_self_use_gemdeps'
=========================================================================================================
...........E
=========================================================================================================
Error: test_use_gemdeps(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:1872:in `test_use_gemdeps'
=========================================================================================================
...E
=========================================================================================================
Error: test_use_gemdeps_automatic(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:1926:in `block in test_use_gemdeps_automatic'
test/rubygems/test_gem.rb:2125:in `with_rubygems_gemdeps'
test/rubygems/test_gem.rb:1915:in `test_use_gemdeps_automatic'
=========================================================================================================
..E
=========================================================================================================
Error: test_use_gemdeps_missing_gem(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:1970:in `block (3 levels) in test_use_gemdeps_missing_gem'
test/rubygems/test_gem.rb:1969:in `block (2 levels) in test_use_gemdeps_missing_gem'
/home/jaruga/var/git/rubygems/lib/rubygems/deprecate.rb:86:in `skip_during'
test/rubygems/test_gem.rb:1968:in `block in test_use_gemdeps_missing_gem'
test/rubygems/test_gem.rb:2125:in `with_rubygems_gemdeps'
test/rubygems/test_gem.rb:1957:in `test_use_gemdeps_missing_gem'
=========================================================================================================
E
=========================================================================================================
Error: test_use_gemdeps_specific(TestGem): ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:9:in `status_code'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<class:GemfileError>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:20:in `<module:Bundler>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler/errors.rb:3:in `<top (required)>'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `require_relative'
/usr/local/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:7:in `<top (required)>'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/jaruga/var/git/rubygems/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/jaruga/var/git/rubygems/lib/rubygems.rb:1114:in `use_gemdeps'
test/rubygems/test_gem.rb:1990:in `block in test_use_gemdeps_specific'
test/rubygems/test_gem.rb:2125:in `with_rubygems_gemdeps'
test/rubygems/test_gem.rb:1979:in `test_use_gemdeps_specific'
=========================================================================================================

Finished in 3.149945616 seconds.
---------------------------------------------------------------------------------------------------------
140 tests, 239 assertions, 0 failures, 8 errors, 0 pendings, 0 omissions, 0 notifications
94.2857% passed
---------------------------------------------------------------------------------------------------------
44.45 tests/s, 75.87 assertions/s
Coverage report generated for Unit Tests to /home/jaruga/var/git/rubygems/coverage. 2644 / 5433 LOC (48.67%) covered.
```

My suggestion is adding the following isolated test to somewhere on CI to test this kind of case. I saw isolated tests on rails/rails in the past.

```
$ ruby -Ilib:test -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env
PASTE HERE
```

In this case, the `gem` command is not used.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
You need to use `ruby -Ilib:test:bundler/lib test/rubygems/test_gem.rb` so that the proper version of bundler is used

**Comment by junaruga** [comment]
Thanks! The command work!

```
$ ruby -Ilib:test:bundler/lib test/rubygems/test_gem.rb
```

```
$ ruby -Ilib:test:bundler/lib -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
```

Perhaps, we can update the following documents adding the `bundler/lib`?

https://github.com/rubygems/rubygems/blob/master/CONTRIBUTING.md

> ruby -Ilib:test test/rubygems/test_deprecate.rb 

> ruby -Ilib:test test/rubygems/test_deprecate.rb -n /test_default/ 

Like this.

```
ruby -Ilib:test:bundler/lib test/rubygems/test_deprecate.rb 

ruby -Ilib:test:bundler/lib test/rubygems/test_deprecate.rb -n /test_default/ 
```

**Comment by deivid-rodriguez** [comment]
Absolutely, yes!

**Comment by junaruga** [comment]
OK. I will send the PR.

**Comment by junaruga** [comment]
The PR is here, https://github.com/rubygems/rubygems/pull/4958 .
