### ISSUE TITLE
bundle _2.2.28_ unknown keywords: :symbolize_names, :freeze

### ISSUE THREAD

**Issue by marlinpierce** [rubygems/rubygems#4961]
### Describe the problem as clearly as you can

Calling

    bundle _2.2.28_

reports an error: "Unfortunately, an unexpected error occurred, and Bundler cannot continue."

### Post steps to reproduce the problem

Happens from calling

    bundle _2.2.28_

- OS Version: FreeBSD `13.0-RELEASE-p4`
- Ruby version `2.7.4p191` installed by FreeBSD package: `ruby-2.7.4,1`
- Gem version `3.0.8` installed by FreeBSD package: `ruby27-gems-3.0.8`
- Bundler version `2.2.28` installed by FreeBSD package `rubygem-bundler-2.2.28,1`

[Gemfile.txt](https://github.com/rubygems/rubygems/files/7286413/Gemfile.txt)
[Gemfile.lock.txt](https://github.com/rubygems/rubygems/files/7286334/Gemfile.lock.txt)

### Which command did you run?

    bundle _2.2.28_

### What were you expecting to happen?

Successful bundling of gems.

### What actually happened?

Error message

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

```
ArgumentError: unknown keywords: :symbolize_names, :freeze
  /usr/local/lib/ruby/2.7/psych/visitors/to_ruby.rb:23:in `initialize'
  /usr/local/AC-TESTING/marlpier/disgorge/releases/20211005-092406/analyst-console-escalations-1.2.15.1.130/vendor/bundle/ruby/2.7/gems/psych-3.2.0/lib/psych.rb:355:in `new'
  /usr/local/AC-TESTING/marlpier/disgorge/releases/20211005-092406/analyst-console-escalations-1.2.15.1.130/vendor/bundle/ruby/2.7/gems/psych-3.2.0/lib/psych.rb:355:in `safe_load'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/safe_yaml.rb:32:in `safe_load'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:534:in `block (2 levels) in read_checksums'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:533:in `wrap'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:533:in `block in read_checksums'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package/tar_reader.rb:114:in `seek'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:532:in `read_checksums'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:592:in `block (2 levels) in verify'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package/tar_reader.rb:29:in `new'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:591:in `block in verify'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package/file_source.rb:30:in `open'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package/file_source.rb:30:in `with_read_io'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:590:in `verify'
  /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:571:in `spec'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/rubygems_integration.rb:254:in `spec_from_gem'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/runtime.rb:219:in `block in prune_gem_cache'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/runtime.rb:218:in `delete_if'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/runtime.rb:218:in `prune_gem_cache'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/runtime.rb:145:in `prune_cache'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/runtime.rb:137:in `cache'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/cli/install.rb:63:in `block in run'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/cli/install.rb:62:in `run'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/cli.rb:253:in `block in install'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/cli.rb:252:in `install'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/cli.rb:25:in `start'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.7/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

[bundle.err.txt](https://github.com/rubygems/rubygems/files/7286392/bundle.err.txt)

### If not included with the output of your command, run `bundle env` and paste the output below

[bundle.env.txt](https://github.com/rubygems/rubygems/files/7286360/bundle.env.txt)

**Comment by deivid-rodriguez** [comment]
Hi @marlinpierce. This one also seems like a packaging issue.

If I try to downgrade my default rubygems version on 2.7.4, to rubygems 3.0.8 in order to replicate your issue, rubygems tells me that old version is not really supported on ruby 2.7.4

```
$ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]

$ gem env version
3.1.6

$ gem update --system 3.0.8
ERROR:  rubygems 3.0.8 is not supported on 2.7.4. The oldest version supported by this ruby is 3.1.2
```

My guess is that either rubygems of bundler was loading `psych` too early and causing the default version of psych to be mixed up with a regular installation of psych, like in this case. Notice how the backtrace jumps from the regular version (the 2nd and 3d likes in the backtraces) to the default version (the 1st line in the backtrace), which are different versions of the same gem!

I think it's very likely that this has been fixed in newer rubygems version, with changes like https://github.com/rubygems/rubygems/pull/3636, so making sure a newer rubygems version is used should fix the issue.

Thanks for reporting!
