### ISSUE TITLE
RubyGems preloads "fiddle", but reloads a different version on require (Windows)

### ISSUE THREAD

**Issue by thyresias** [rubygems/rubygems#5043]
Demonstration:

```
> gem update --system
Latest version already installed. Done.

> gem list fiddle
*** LOCAL GEMS ***
fiddle (1.1.0, default: 1.0.6)

> ruby -e "p Fiddle::VERSION"
"1.0.6"

> ruby --disable=gems -e "p Fiddle::VERSION"
-e:1:in `<main>': uninitialized constant Fiddle (NameError)

> ruby -e "require 'fiddle'; p Fiddle::VERSION"
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:12: warning: method redefined; discarding old win32_last_error
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:12: warning: previous definition of win32_last_error was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:17: warning: method redefined; discarding old win32_last_error=
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:17: warning: previous definition of win32_last_error= was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:35: warning: method redefined; discarding old last_error
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:23: warning: previous definition of last_error was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:40: warning: method redefined; discarding old last_error=
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:28: warning: previous definition of last_error= was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:67: warning: already initialized constant Fiddle::RTLD_GLOBAL
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:55: warning: previous definition of RTLD_GLOBAL was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:68: warning: already initialized constant Fiddle::RTLD_LAZY
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:56: warning: previous definition of RTLD_LAZY was here
C:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:69: warning: already initialized constant Fiddle::RTLD_NOW
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:57: warning: previous definition of RTLD_NOW was here
"1.0.6"
```

After the reload, the version is wrong.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.30
  - RUBY VERSION: 3.0.2 (2021-07-07 patchlevel 107) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/ruby-3.0.2/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: c:/home/thierry/.gem/ruby/3.0.0
  - RUBY EXECUTABLE: C:/ruby-3.0.2/bin/ruby.exe
  - GIT EXECUTABLE: C:\Programs\Git\cmd/git.EXE
  - EXECUTABLE DIRECTORY: C:/ruby-3.0.2/bin
  - SPEC CACHE DIRECTORY: c:/home/thierry/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86-mingw32
  - GEM PATHS:
     - C:/ruby-3.0.2/lib/ruby/gems/3.0.0
     - c:/home/thierry/.gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
     - "rdoc" => "--format babel"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\WINDOWS\System32\OpenSSH\
     - c:\ruby\bin
     - C:\Programs
```

**Comment by deivid-rodriguez** [comment]
Hello @thyresias, thanks for the report.

I don't think we load `fiddle` directly, so it must be through some sodlib dependency. Can you add some debug prints on top of the involved `fiddle.rb` files to print a backtrace so we can figure out which library is loading it?

**Comment by thyresias** [comment]
Hello @deivid-rodriguez,

Here you go:
```
> ruby -e "p Fiddle::VERSION"

this is file c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/dll_directory.rb:1:in `require'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/dll_directory.rb:1:in `<top (required)>'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/msys2_installation.rb:111:in `require'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/msys2_installation.rb:111:in `enable_dll_search_paths'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
c:/ruby-3.0.2/lib/ruby/3.0.0/rubygems/defaults/operating_system.rb:3:in `<top (required)>'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1332:in `require'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1332:in `<top (required)>'
<internal:gem_prelude>:2:in `require'
<internal:gem_prelude>:2:in `<internal:gem_prelude>'
"1.0.6"

> ruby -e "require 'fiddle'; p Fiddle::VERSION"

this is file c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/dll_directory.rb:1:in `require'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/dll_directory.rb:1:in `<top (required)>'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/msys2_installation.rb:111:in `require'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/msys2_installation.rb:111:in `enable_dll_search_paths'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
c:/ruby-3.0.2/lib/ruby/3.0.0/rubygems/defaults/operating_system.rb:3:in `<top (required)>'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1332:in `require'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1332:in `<top (required)>'
<internal:gem_prelude>:2:in `require'
<internal:gem_prelude>:2:in `<internal:gem_prelude>'

this is file c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb
<internal:c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
-e:1:in `<main>'
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:15: warning: method redefined; discarding old win32_last_error
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:15: warning: previous definition of win32_last_error was here
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:20: warning: method redefined; discarding old win32_last_error=
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:20: warning: previous definition of win32_last_error= was here
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:38: warning: method redefined; discarding old last_error
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:26: warning: previous definition of last_error was here
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:43: warning: method redefined; discarding old last_error=
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:31: warning: previous definition of last_error= was here
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:70: warning: already initialized constant Fiddle::RTLD_GLOBAL
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:58: warning: previous definition of RTLD_GLOBAL was here
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:71: warning: already initialized constant Fiddle::RTLD_LAZY
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:59: warning: previous definition of RTLD_LAZY was here
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:72: warning: already initialized constant Fiddle::RTLD_NOW
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:60: warning: previous definition of RTLD_NOW was here
"1.0.6"
```

**Comment by deivid-rodriguez** [comment]
Aha. This is code provided by the Windows distribution of ruby: https://github.com/oneclick/rubyinstaller2.

I think we need to allow activating gems from `operating_system.rb`, since this is the entry point for rubyinstaller2 customizations, so we need to make sure the monkey patches to `Kernel.require` are in place a bit earlier.

Can you try whether the following patch fixes the issue?

```diff
diff --git a/lib/rubygems.rb b/lib/rubygems.rb
index 80708e2aa0..12b9b80a7d 100644
--- a/lib/rubygems.rb
+++ b/lib/rubygems.rb
@@ -1324,6 +1324,14 @@ def default_gem_load_paths
 
 require_relative 'rubygems/exceptions'
 
+##
+# Loads the default specs.
+Gem::Specification.load_defaults
+
+require_relative 'rubygems/core_ext/kernel_gem'
+require_relative 'rubygems/core_ext/kernel_require'
+require_relative 'rubygems/core_ext/kernel_warn'
+
 # REFACTOR: This should be pulled out into some kind of hacks file.
 begin
   ##
@@ -1348,11 +1356,3 @@ def default_gem_load_paths
   require "rubygems/defaults/#{RUBY_ENGINE}"
 rescue LoadError
 end
-
-##
-# Loads the default specs.
-Gem::Specification.load_defaults
-
-require_relative 'rubygems/core_ext/kernel_gem'
-require_relative 'rubygems/core_ext/kernel_require'
-require_relative 'rubygems/core_ext/kernel_warn'
```

**Comment by thyresias** [comment]
Yep, it solves the problem.

**Comment by deivid-rodriguez** [comment]
Great, thanks for verifying! I'll create a PR to fix this.

**Comment by thyresias** [comment]
Thanks !

**Comment by deivid-rodriguez** [comment]
I was trying to write a test for this fix, but the issue won't even reproduce on my Windows VM nor in CI. Can you show me the full list of gems you have installed?

**Comment by thyresias** [comment]
Here is the list:
```
> gem list
*** LOCAL GEMS ***
abbrev (default: 0.1.0)
addressable (2.8.0)
base64 (0.1.1, default: 0.1.0)
benchmark (0.2.0, default: 0.1.1)
bigdecimal (3.0.2, default: 3.0.0)
bundler (default: 2.2.30)
cgi (0.3.0, default: 0.2.0)
charlock_holmes (0.7.7)
childprocess (4.1.0)
connection_pool (2.2.5)
csv (3.2.1, default: 3.1.9)
date (3.2.0, default: 3.1.0)
dbm (default: 1.1.0)
debug (1.3.4, default: 0.1.0)
delegate (default: 0.2.0)
did_you_mean (default: 1.5.0)
digest (default: 3.0.0)
domain_name (0.5.20190701)
drb (2.1.0, default: 2.0.4)
english (default: 0.7.1)
erb (2.2.3, default: 2.2.0)
etc (1.3.0, default: 1.2.0)
fcntl (1.0.1, default: 1.0.0)
ffi (1.15.4 x86-mingw32)
fiddle (1.1.0, default: 1.0.6)
fileutils (1.6.0, default: 1.5.0)
find (0.1.1, default: 0.1.0)
forwardable (default: 1.3.2)
gdbm (default: 2.1.0)
getoptlong (default: 0.1.1)
http-cookie (1.0.4)
io-console (0.5.9, default: 0.5.7)
io-nonblock (default: 0.1.0)
io-wait (0.2.0, default: 0.1.0)
ipaddr (1.2.3, default: 1.2.2)
irb (1.3.7, default: 1.3.5)
json (2.6.1, default: 2.5.1)
logger (1.4.4, default: 1.4.3)
maruku (0.7.1)
matrix (0.4.2, default: 0.3.1)
mechanize (2.8.2)
mime-types (3.3.1)
mime-types-data (3.2021.0901)
minitest (5.14.4)
mutex_m (default: 0.1.1)
net-ftp (0.1.3, default: 0.1.2)
net-http (0.2.0, default: 0.1.1)
net-http-digest_auth (1.4.1)
net-http-persistent (4.0.1)
net-imap (0.2.2, default: 0.1.1)
net-pop (default: 0.1.1)
net-protocol (0.1.2, default: 0.1.0)
net-smtp (0.3.0, default: 0.2.1)
nkf (0.1.1, default: 0.1.0)
nokogiri (1.12.5 x86-mingw32)
observer (default: 0.1.1)
open-uri (0.2.0, default: 0.1.0)
open3 (default: 0.1.1)
openssl (2.2.1, default: 2.2.0)
optparse (0.2.0, default: 0.1.0)
ostruct (0.5.0, default: 0.3.1)
ox (2.14.5)
pathname (0.2.0, default: 0.1.0)
power_assert (2.0.1)
pp (0.2.1, default: 0.1.0)
prettyprint (0.1.1, default: 0.1.0)
prime (default: 0.1.2)
pstore (default: 0.1.1)
psych (4.0.2, default: 3.3.0)
public_suffix (4.0.6)
racc (1.6.0, default: 1.5.1)
rake (13.0.6)
rbs (1.6.2)
rdoc (6.3.2, default: 6.3.1)
rdoc-babel (1.0.7)
readline (default: 0.0.2)
regexp_parser (2.1.1)
reline (0.2.7, default: 0.2.5)
resolv (0.2.1, default: 0.2.0)
resolv-replace (default: 0.1.0)
rexml (3.2.5)
rinda (0.1.1, default: 0.1.0)
rss (0.2.9)
ruby2_keywords (0.0.5)
rubygems-update (3.2.30)
rubyntlm (0.6.3)
rubyzip (1.3.0)
securerandom (0.1.1, default: 0.1.0)
selenium-webdriver (4.0.3)
set (1.0.2, default: 1.0.1)
shellwords (default: 0.1.0)
singleton (default: 0.1.1)
sqlite3 (1.4.2)
stringio (3.0.1, default: 3.0.0)
strscan (3.0.1, default: 3.0.0)
sublime_dsl (0.1.3)
tempfile (0.1.2, default: 0.1.1)
test-unit (3.5.0)
time (0.2.0, default: 0.1.0)
timeout (0.2.0, default: 0.1.1)
tmpdir (default: 0.1.2)
tracer (default: 0.1.1)
tsort (default: 0.1.0)
typeprof (0.20.2)
un (0.2.0, default: 0.1.0)
unf (0.1.4)
unf_ext (0.0.8 x86-mingw32)
uri (0.11.0, default: 0.10.1)
watir (7.0.0)
weakref (default: 0.1.1)
webrick (1.7.0)
webrobots (0.1.2)
win32-api (1.10.1 universal-mingw32)
win32ole (default: 1.8.8)
yaml (0.2.0, default: 0.1.1)
zlib (2.1.1, default: 1.1.0)
```

**Comment by deivid-rodriguez** [comment]
My patch is still correct and testable, since even if I can't trigger the redefinition warnings, it should result in activating the latest version of `fiddle` in your system, not the default one.

Still, I'm very curious about why the redefinition warnings are happening for you. Can you add similar debugging prints on top of this line here to figure out which code is activating which `fiddle` spec:

https://github.com/rubygems/rubygems/blob/d7b2478e764c965a32a4c1d9e043491cb9349561/lib/rubygems/specification.rb#L1377

**Comment by thyresias** [comment]
Hello David,
Sorry for the late answer, time difference I guess (I'm in Paris, France, where are you?)
Here is the result:
```
> ruby -e "p Fiddle::VERSION"
"1.0.6"

> ruby -e "require 'fiddle'; p Fiddle::VERSION"
this if file c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb, line 1372
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:68:in `synchronize'
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:68:in `gem'
<internal:c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:73:in `require'
-e:1:in `<main>'
c:/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:12: warning: method redefined; discarding old win32_last_error
c:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb:12: warning: previous definition of win32_last_error was here
(...)
"1.0.6"
```

**Comment by deivid-rodriguez** [comment]
No problem, I'm in Spain, so no time difference, just different times to sit in front of the computer :)

So, gem is being activated by rubygems custom `Kernel.require`, however, it should instead be activated at default gem setup time, here:

https://github.com/rubygems/rubygems/blob/d7b2478e764c965a32a4c1d9e043491cb9349561/lib/rubygems.rb#L1220

But I'm guessing that for some reason the `already_loaded?` method is returning `false` for `fiddle` in your case.

Can you add another debug print at the beginning of that method to see why/if the method is returning `false` for `fiddle`. I guess you should add the debugging print only if the parameter passed to `already_loaded?` ends with `fiddle.rb` because the method is called many other times.

**Comment by thyresias** [comment]
Maybe I found the origin of the issue (see the debug prints below).

On my machine, I implemented a very simple system to switch between ruby versions:
* I have one ruby version in `c:/ruby-3.0.2`, another in `c:/ruby-2.7.2`
* I create a directory junction to the one I want to use, e.g., `mklink /j c:\ruby c:\ruby-3.0.2` (I have c:\ruby\bin in my path).

In the debug print below, `$LOADED_FEATURES` references the real directory, but `default_gem_load_paths` references the junction. As a result, the test `feature_path.end_with?(file)` returns true for `file = "fiddle.rb"` and `feature_path = "C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb"`, but the test `default_gem_load_paths.any? {|load_path_entry| feature_path == "#{load_path_entry}/#{file}" }` returns false.

Long ago, this junction method created problems with ruby's native require, but now it has been fixed, so I completely forgot this particularity in my install.

```
> ruby -e "p Fiddle::VERSION"

already_loaded?(fiddle.rb)

backtrace:
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1220:in `block in register_default_spec'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1214:in `each'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1214:in `register_default_spec'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:869:in `block in load_defaults'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:797:in `block in each_spec'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:768:in `block (2 levels) in each_gemspec'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:767:in `each'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:767:in `block in each_gemspec'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:766:in `each'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:766:in `each_gemspec'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:795:in `each_spec'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:866:in `load_defaults'
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems.rb:1377:in `<top (required)>'
<internal:gem_prelude>:2:in `require'
<internal:gem_prelude>:2:in `<internal:gem_prelude>'

$LOADED_FEATURES:
enumerator.so
thread.rb
rational.so
complex.so
ruby2_keywords.rb
C:/ruby-3.0.2/lib/ruby/3.0.0/i386-mingw32/enc/encdb.so
C:/ruby-3.0.2/lib/ruby/3.0.0/i386-mingw32/enc/trans/transdb.so
C:/ruby-3.0.2/lib/ruby/3.0.0/i386-mingw32/enc/windows_1252.so
C:/ruby-3.0.2/lib/ruby/3.0.0/i386-mingw32/rbconfig.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/compatibility.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/defaults.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/deprecate.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/errors.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/exceptions.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/singleton.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/msys2_installation.rb
C:/ruby-3.0.2/lib/ruby/3.0.0/i386-mingw32/fiddle.so
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle/closure.rb
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle/function.rb
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle/version.rb
C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/dll_directory.rb
C:/ruby-3.0.2/lib/ruby/3.0.0/i386-mingw32/enc/utf_16le.so
C:/ruby-3.0.2/lib/ruby/3.0.0/i386-mingw32/enc/trans/utf_16_32.so
C:/ruby-3.0.2/lib/ruby/3.0.0/rubygems/defaults/operating_system.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/basic_specification.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/stub_specification.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/text.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/user_interaction.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification_policy.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/util/list.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/platform.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/version.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/requirement.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/util.rb
C:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/dependency.rb

default_gem_load_paths:
c:/ruby/lib/ruby/site_ruby/3.0.0
c:/ruby/lib/ruby/site_ruby/3.0.0/i386-msvcrt
c:/ruby/lib/ruby/site_ruby
c:/ruby/lib/ruby/vendor_ruby/3.0.0
c:/ruby/lib/ruby/vendor_ruby/3.0.0/i386-msvcrt
c:/ruby/lib/ruby/vendor_ruby
c:/ruby/lib/ruby/3.0.0
c:/ruby/lib/ruby/3.0.0/i386-mingw32

feature_path.end_with?(fiddle.rb): true for feature_path = "C:/ruby-3.0.2/lib/ruby/3.0.0/fiddle.rb"
already_loaded?(fiddle.rb): false
"1.0.6"
```

**Comment by deivid-rodriguez** [comment]
Indeed, that seems like the culprit. We could fix that issue by expanding `default_gem_load_paths` to real paths, but it seems so edgy, and given the change of allowing `operating_system.rb` to activate gems will fix it too, I guess it's fine to leave as is?

**Comment by thyresias** [comment]
I let you judge: I remember there were problems in core ruby with symlinked directories, now fixed. Won't you eventually have problems with this discrepancy between `$LOADED_FEATURES` and `default_gem_load_paths`? In any case, your PR solves by problem, thank you.

**Comment by deivid-rodriguez** [comment]
Not sure, but I guess it doesn't hurt to also fix it, yeah.

**Comment by deivid-rodriguez** [comment]
Hello @thyresias, unfortunately, the fix for your issue created bigger issues than this one, so I'm going to have to revert it (see #5154). I'll propose expanding paths in `default_gem_paths` as an alternative, are you able to try it?

**Comment by deivid-rodriguez** [comment]
The patch would be something like this

```diff
diff --git a/lib/rubygems.rb b/lib/rubygems.rb
index 8e050ef3c7..404d5ab9c9 100644
--- a/lib/rubygems.rb
+++ b/lib/rubygems.rb
@@ -1293,7 +1293,13 @@ def already_loaded?(file)
     end
 
     def default_gem_load_paths
-      @default_gem_load_paths ||= $LOAD_PATH[load_path_insert_index..-1]
+      @default_gem_load_paths ||= $LOAD_PATH[load_path_insert_index..-1].map do |lp|
+        begin
+          File.realpath(lp)
+        rescue Errno::ENOENT
+          nil
+        end
+      end.compact
     end
   end
 
```

**Comment by thyresias** [comment]
Hello David,

With your patch, the problem of loading twice the gem "fiddle" is gone, but only the original is loaded:
```
> gem list fiddle

*** LOCAL GEMS ***

fiddle (1.1.0, default: 1.0.6)

> ruby -e "p Fiddle::VERSION"
"1.0.6"

> ruby -e "require 'fiddle'; p Fiddle::VERSION"
"1.0.6"

> ruby -e "gem 'fiddle', '=1.1.0'; require 'fiddle'; p Fiddle::VERSION"
c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:2229:in `check_version_conflict': can't activate fiddle-1.1.0, already activated fiddle-1.0.6 (Gem::LoadError)
        from c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:1366:in `activate'
        from c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
        from c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:68:in `synchronize'
        from c:/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:68:in `gem'
        from -e:1:in `<main>'
```
With the patch you had to revert:
```
> ruby -e "p Fiddle::VERSION"
"1.1.0"
```

**Comment by deivid-rodriguez** [comment]
Yep, that's expected. Unfortunately we can't get the best of both worlds. I'll open a pull request.

**Comment by thyresias** [comment]
Since the issue was with brew, wouldn't it be possible to "if windows ... else ..."?

**Comment by deivid-rodriguez** [comment]
The issue is not `brew` in particular, it's any distribution that customizes `Gem.default_dir` or `Gem.default_specifications_dir`, which is quite common. In any case, your issue was reloading a different version on `require`, not the particular version being loaded, right? If we want to support specifying `fiddle` inside `Gemfiles` on `Windows`, and being able to activate the latest version of it, `rubyinstaller2` should find a way to do what it needs to do without loading `fiddle` 😬.

**Comment by deivid-rodriguez** [comment]
No problem, I'm not sure there's a good solution for this, unfortunately :(
