### ISSUE TITLE
bundle exec fastlane <lane> fails on: `parse_global_options': undefined method `require_exact=' for #<OptionParser:0x00007fef3ebcc1d8> (NoMethodError)

### ISSUE THREAD

**Issue by rowanmulder** [rubygems/rubygems#5076]
### Describe the problem as clearly as you can

Upgrading Fastlane beyond 2.191 is impossible, due to OptPars giving a build error. Looking at a [similar ticket](https://github.com/rubygems/rubygems/issues/4880) updating Bundler tot 2.2.31 should resolve it, but it hasn't. The same type of error still occurs.

### Did you try upgrading rubygems & bundler?

Yes, this specific scenario requires Bundler 2.2.31 to be resolved (or so I believed).

### Post steps to reproduce the problem

I'm running Ruby 2.7.3 from rbenv on macOS 11.6.1. Ruby/Bundle/Fastlane are triggered by GitLab runners on the machine, using bash as the default console environment.

Here's my Gemfile, and .bundle/config:

Gemfile:
```
source "https://rubygems.org"

gem "fastlane"
gem "xcode-install"
gem "cocoapods"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

.bundle/config:
```
---
BUNDLE_AUTO_INSTALL: "true"
BUNDLE_PATH: vendor/bundle
```

### Which command did you run?

`bundle exec fastlane ios unit_tests`

### What were you expecting to happen?

I expected my fastlane lane (for unit tests) to execute.

### What actually happened?

It fails to load the fastlane command:
```
bundler: failed to load command: fastlane (/Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/bin/fastlane)
/Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.198.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:65:in `parse_global_options': undefined method `require_exact=' for #<OptionParser:0x00007fef3ebcc1d8> (NoMethodError)
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.198.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:91:in `run!'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.198.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.198.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.198.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/gems/fastlane-2.198.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
	from /Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/bin/bundle:23:in `load'
	from /Users/xcodeserver/.rbenv/versions/2.7.4/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.31
  Platforms   ruby, x86_64-darwin-20
Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-darwin20]
  Full Path   /Users/xcodeserver/.rbenv/versions/2.7.4/bin/ruby
  Config Dir  /Users/xcodeserver/.rbenv/versions/2.7.4/etc
RubyGems      3.1.6
  Gem Home    /Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
  Gem Path    /Users/xcodeserver/.gem/ruby/2.7.0:/Users/xcodeserver/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
  User Home   /Users/xcodeserver
  User Path   /Users/xcodeserver/.gem/ruby/2.7.0
  Bin Dir     /Users/xcodeserver/.rbenv/versions/2.7.4/bin
Tools         
  Git         2.33.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-11-08
Git SHA           2505ef8972
Released Version  true
```

## Bundler settings

```
auto_install
  Set for your local app (/Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/.bundle/config): true
path
  Set for your local app (/Users/xcodeserver/builds/8UEPjBbH/0/ios/ios-app/.bundle/config): "vendor/bundle"
  Set for the current user (/Users/xcodeserver/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "fastlane"
gem "xcode-install"
gem "cocoapods"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

### fastlane/Pluginfile

```ruby
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-teams'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.5)
      rexml
    activesupport (6.1.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    artifactory (3.0.15)
    atomos (0.1.3)
    aws-eventstream (1.2.0)
    aws-partitions (1.531.0)
    aws-sdk-core (3.122.1)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.525.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.51.0)
      aws-sdk-core (~> 3, >= 3.122.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.105.1)
      aws-sdk-core (~> 3, >= 3.122.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.4.0)
      aws-eventstream (~> 1, >= 1.0.2)
    babosa (1.0.4)
    claide (1.0.3)
    cocoapods (1.11.2)
      addressable (~> 2.8)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.11.2)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.4.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.4.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.8.0)
      nap (~> 1.0)
      ruby-macho (>= 1.0, < 3.0)
      xcodeproj (>= 1.21.0, < 2.0)
    cocoapods-core (1.11.2)
      activesupport (>= 5.0, < 7)
      addressable (~> 2.8)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix (~> 4.0)
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (1.5.1)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.6.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored (1.2)
    colored2 (3.1.2)
    commander (4.6.0)
      highline (~> 2.0.0)
    concurrent-ruby (1.1.9)
    declarative (0.0.20)
    digest-crc (0.6.4)
      rake (>= 12.0.0, < 14.0.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    emoji_regex (3.2.3)
    escape (0.0.4)
    ethon (0.15.0)
      ffi (>= 1.15.0)
    excon (0.88.0)
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-cookie_jar (0.0.7)
      faraday (>= 0.8.0)
      http-cookie (~> 1.0.0)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    fastimage (2.2.5)
    fastlane (2.198.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.8, < 3.0.0)
      artifactory (~> 3.0)
      aws-sdk-s3 (~> 1.0)
      babosa (>= 1.0.3, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander (~> 4.6)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 4.0)
      excon (>= 0.71.0, < 1.0.0)
      faraday (~> 1.0)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 1.0)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-apis-androidpublisher_v3 (~> 0.3)
      google-apis-playcustomapp_v1 (~> 0.1)
      google-cloud-storage (~> 1.31)
      highline (~> 2.0)
      json (< 3.0.0)
      jwt (>= 2.1.0, < 3)
      mini_magick (>= 4.9.4, < 5.0.0)
      multipart-post (~> 2.0.0)
      naturally (~> 2.2)
      optparse (~> 0.1.1)
      plist (>= 3.1.0, < 4.0.0)
      rubyzip (>= 2.0.0, < 3.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    fastlane-plugin-teams (0.2.0)
    ffi (1.15.4)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    google-apis-androidpublisher_v3 (0.13.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-core (0.4.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    google-apis-iamcredentials_v1 (0.8.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-playcustomapp_v1 (0.6.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-storage_v1 (0.9.0)
      google-apis-core (>= 0.4, < 2.a)
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.5.0)
      faraday (>= 0.17.3, < 2.0)
    google-cloud-errors (1.2.0)
    google-cloud-storage (1.34.1)
      addressable (~> 2.5)
      digest-crc (~> 0.4)
      google-apis-iamcredentials_v1 (~> 0.1)
      google-apis-storage_v1 (~> 0.1)
      google-cloud-core (~> 1.6)
      googleauth (>= 0.16.2, < 2.a)
      mini_mime (~> 1.0)
    googleauth (1.1.0)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    highline (2.0.3)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    jmespath (1.4.0)
    json (2.6.1)
    jwt (2.3.0)
    memoist (0.16.2)
    mini_magick (4.11.0)
    mini_mime (1.1.2)
    minitest (5.14.4)
    molinillo (0.8.0)
    multi_json (1.15.0)
    multipart-post (2.0.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    naturally (2.2.1)
    netrc (0.11.0)
    optparse (0.1.1)
    os (1.1.4)
    plist (3.6.0)
    public_suffix (4.0.6)
    rake (13.0.6)
    representable (3.1.1)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rexml (3.2.5)
    rouge (2.0.7)
    ruby-macho (2.5.1)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    security (0.1.3)
    signet (0.16.0)
      addressable (~> 2.8)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.8)
      CFPropertyList
      naturally
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    trailblazer-option (0.1.2)
    tty-cursor (0.7.1)
    tty-screen (0.8.1)
    tty-spinner (0.9.3)
      tty-cursor (~> 0.7)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8)
    unicode-display_width (1.8.0)
    webrick (1.7.0)
    word_wrap (1.0.0)
    xcode-install (2.8.0)
      claide (>= 0.9.1, < 1.1.0)
      fastlane (>= 2.1.0, < 3.0.0)
    xcodeproj (1.21.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.1)
      xcpretty (~> 0.2, >= 0.0.7)
    zeitwerk (2.5.1)

PLATFORMS
  x86_64-darwin-20

DEPENDENCIES
  cocoapods
  fastlane
  fastlane-plugin-teams
  xcode-install

BUNDLED WITH
   2.2.31
```

**Comment by deivid-rodriguez** [comment]
You're using old rubygems, and this issue end up lying in rubygems. So you need to also update rubygems as suggested by the issue template. Feel free to reopen if this is still broken after also upgrading rubygems. Thanks!!
