### ISSUE TITLE
NoMethodError: undefined method `ruby2_keywords' for Bundler::ConnectionPool::Wrapper:Class

### ISSUE THREAD

**Issue by MaYanpeng** [rubygems/rubygems#5093]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `ruby2_keywords' for Bundler::ConnectionPool::Wrapper:Class
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:42:in `<class:Wrapper>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:2:in `<class:ConnectionPool>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:1:in `<top (required)>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/connection_pool/lib/connection_pool.rb:126:in `require_relative'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/connection_pool/lib/connection_pool.rb:126:in `<top (required)>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:4:in `require_relative'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:4:in `<top (required)>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendored_persistent.rb:11:in `require_relative'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendored_persistent.rb:11:in `<top (required)>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/fetcher.rb:3:in `require_relative'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/fetcher.rb:3:in `<top (required)>'
  /Users/yanpeng.ma/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/yanpeng.ma/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/cli/install.rb:48:in `run'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/cli.rb:253:in `block in install'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/settings.rb:131:in `temporary'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/cli.rb:252:in `install'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/bin/bundle:23:in `load'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/bin/bundle:23:in `<main>'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `eval'
  /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `<main>'
```

## Environment

```
Bundler             2.2.32
  Platforms         ruby, x86_64-darwin-18
Ruby                2.7.0p-1 (2019-05-31 revision c55db6aa271df4a689dc8eb0039c929bf6ed43ff) [x86_64-darwin18]
  Full Path         /Users/yanpeng.ma/.rvm/rubies/ruby-2.7.0-preview1/bin/ruby
  Config Dir        /Users/yanpeng.ma/.rvm/rubies/ruby-2.7.0-preview1/etc
RubyGems            3.0.8
  Gem Home          /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1
  Gem Path          /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1:/Users/yanpeng.ma/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0
  User Home         /Users/yanpeng.ma
  User Path         /Users/yanpeng.ma/.gem/ruby/2.7.0
  Bin Dir           /Users/yanpeng.ma/.rvm/gems/ruby-2.7.0-preview1/bin
OpenSSL             
  Compiled          OpenSSL 1.1.1d  10 Sep 2019
  Loaded            OpenSSL 1.1.1j  16 Feb 2021
  Cert File         /usr/local/etc/openssl@1.1/cert.pem
  Cert Dir          /usr/local/etc/openssl@1.1/certs
Tools               
  Git               2.28.0
  RVM               1.29.10 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2021-11-23
Git SHA           20d4957649
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'fastlane'
gem 'snapshot'
gem 'cocoapods', '~> 1.10'
gem 'jazzy', '~> 0.14'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.4)
      rexml
    activesupport (6.1.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    artifactory (3.0.15)
    atomos (0.1.3)
    aws-eventstream (1.2.0)
    aws-partitions (1.510.0)
    aws-sdk-core (3.121.1)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.49.0)
      aws-sdk-core (~> 3, >= 3.120.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.103.0)
      aws-sdk-core (~> 3, >= 3.120.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.4.0)
      aws-eventstream (~> 1, >= 1.0.2)
    babosa (1.0.4)
    claide (1.0.3)
    cocoapods (1.11.2)
      addressable (~> 2.8)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.11.2)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.4.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.4.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.8.0)
      nap (~> 1.0)
      ruby-macho (>= 1.0, < 3.0)
      xcodeproj (>= 1.21.0, < 2.0)
    cocoapods-core (1.11.2)
      activesupport (>= 5.0, < 7)
      addressable (~> 2.8)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix (~> 4.0)
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (1.5.1)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.6.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored (1.2)
    colored2 (3.1.2)
    commander (4.6.0)
      highline (~> 2.0.0)
    concurrent-ruby (1.1.9)
    declarative (0.0.20)
    digest-crc (0.6.4)
      rake (>= 12.0.0, < 14.0.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    emoji_regex (3.2.3)
    escape (0.0.4)
    ethon (0.14.0)
      ffi (>= 1.15.0)
    excon (0.86.0)
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-cookie_jar (0.0.7)
      faraday (>= 0.8.0)
      http-cookie (~> 1.0.0)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday_middleware (1.1.0)
      faraday (~> 1.0)
    fastimage (2.2.5)
    fastlane (2.195.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.8, < 3.0.0)
      artifactory (~> 3.0)
      aws-sdk-s3 (~> 1.0)
      babosa (>= 1.0.3, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander (~> 4.6)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 4.0)
      excon (>= 0.71.0, < 1.0.0)
      faraday (~> 1.0)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 1.0)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-apis-androidpublisher_v3 (~> 0.3)
      google-apis-playcustomapp_v1 (~> 0.1)
      google-cloud-storage (~> 1.31)
      highline (~> 2.0)
      json (< 3.0.0)
      jwt (>= 2.1.0, < 3)
      mini_magick (>= 4.9.4, < 5.0.0)
      multipart-post (~> 2.0.0)
      naturally (~> 2.2)
      optparse (~> 0.1.1)
      plist (>= 3.1.0, < 4.0.0)
      rubyzip (>= 2.0.0, < 3.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    ffi (1.15.4)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    google-apis-androidpublisher_v3 (0.11.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-core (0.4.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    google-apis-iamcredentials_v1 (0.7.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-playcustomapp_v1 (0.5.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-storage_v1 (0.8.0)
      google-apis-core (>= 0.4, < 2.a)
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.5.0)
      faraday (>= 0.17.3, < 2.0)
    google-cloud-errors (1.2.0)
    google-cloud-storage (1.34.1)
      addressable (~> 2.5)
      digest-crc (~> 0.4)
      google-apis-iamcredentials_v1 (~> 0.1)
      google-apis-storage_v1 (~> 0.1)
      google-cloud-core (~> 1.6)
      googleauth (>= 0.16.2, < 2.a)
      mini_mime (~> 1.0)
    googleauth (1.0.0)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    highline (2.0.3)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    jazzy (0.14.1)
      cocoapods (~> 1.5)
      mustache (~> 1.1)
      open4 (~> 1.3)
      redcarpet (~> 3.4)
      rexml (~> 3.2)
      rouge (>= 2.0.6, < 4.0)
      sassc (~> 2.1)
      sqlite3 (~> 1.3)
      xcinvoke (~> 0.3.0)
    jmespath (1.4.0)
    json (2.5.1)
    jwt (2.3.0)
    liferaft (0.0.6)
    memoist (0.16.2)
    mini_magick (4.11.0)
    mini_mime (1.1.1)
    minitest (5.14.4)
    molinillo (0.8.0)
    multi_json (1.15.0)
    multipart-post (2.0.0)
    mustache (1.1.1)
    nanaimo (0.3.0)
    nap (1.1.0)
    naturally (2.2.1)
    netrc (0.11.0)
    open4 (1.3.4)
    optparse (0.1.1)
    os (1.1.1)
    plist (3.6.0)
    public_suffix (4.0.6)
    rake (13.0.6)
    redcarpet (3.5.1)
    representable (3.1.1)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rexml (3.2.5)
    rouge (2.0.7)
    ruby-macho (2.5.1)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    sassc (2.4.0)
      ffi (~> 1.9)
    security (0.1.3)
    signet (0.16.0)
      addressable (~> 2.8)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.8)
      CFPropertyList
      naturally
    snapshot (2.0.0)
      colored
      fastimage (>= 1.6)
      fastlane (>= 2.0.0, < 3.0.0)
      plist (>= 3.1.0, < 4.0.0)
      xcpretty (>= 0.2.4, < 1.0.0)
    sqlite3 (1.4.2)
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    trailblazer-option (0.1.1)
    tty-cursor (0.7.1)
    tty-screen (0.8.1)
    tty-spinner (0.9.3)
      tty-cursor (~> 0.7)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8)
    unicode-display_width (1.8.0)
    webrick (1.7.0)
    word_wrap (1.0.0)
    xcinvoke (0.3.0)
      liferaft (~> 0.0.6)
    xcodeproj (1.21.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.1)
      xcpretty (~> 0.2, >= 0.0.7)
    zeitwerk (2.4.2)

PLATFORMS
  ruby

DEPENDENCIES
  cocoapods (~> 1.10)
  fastlane
  jazzy (~> 0.14)
  snapshot

BUNDLED WITH
   2.1.4
```

**Comment by hsbt** [comment]
Can you try it with the stable version of Ruby 2.7? Your ruby version is `2.7.0-preview1`.

**Comment by deivid-rodriguez** [comment]
I created [a patch to connection_pool](https://github.com/mperham/connection_pool/pull/157) to fix this. If it's merged, I'll backport it to our vendored version.

But please, upgrade your ruby! :)
