### ISSUE TITLE
unexpected error upon building a new clean website with jekyll

### ISSUE THREAD

**Issue by golovanevsky** [rubygems/rubygems#5104]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::GemNotFoundException: can't find gem bundler (= 2.2.32) with executable bundle
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems.rb:278:in `find_spec_for_exe'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems.rb:255:in `bin_path'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:207:in `bin_path'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:290:in `set_bundle_variables'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:20:in `run'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:478:in `exec'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
  /opt/homebrew/Cellar/ruby/3.0.2_1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/exe/bundle:49:in `block in <top (required)>'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /opt/homebrew/Cellar/ruby/3.0.2_1/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
  /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:23:in `load'
  /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.32
  Platforms   ruby, arm64-darwin-20
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [arm64-darwin20]
  Full Path   /opt/homebrew/opt/ruby/bin/ruby
  Config Dir  /opt/homebrew/Cellar/ruby/3.0.2_1/etc
RubyGems      3.2.32
  Gem Home    /opt/homebrew/lib/ruby/gems/3.0.0
  Gem Path    /Users/eugene/.gem/ruby/3.0.0:/opt/homebrew/lib/ruby/gems/3.0.0:/opt/homebrew/Cellar/ruby/3.0.2_1/lib/ruby/gems/3.0.0
  User Home   /Users/eugene
  User Path   /Users/eugene/.gem/ruby/3.0.0
  Bin Dir     /opt/homebrew/lib/ruby/gems/3.0.0/bin
Tools         
  Git         2.33.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-11-23
Git SHA           20d4957649
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.2.1"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]


gem "webrick", "~> 1.7"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.9)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    ffi (1.15.4)
    forwardable-extended (2.6.0)
    http_parser.rb (0.8.0)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-feed (0.15.1)
      jekyll (>= 3.7, < 5.0)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-seo-tag (2.7.1)
      jekyll (>= 3.8, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.3.1)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    minima (2.5.1)
      jekyll (>= 3.5, < 5.0)
      jekyll-feed (~> 0.9)
      jekyll-seo-tag (~> 2.1)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.26.1)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    unicode-display_width (1.8.0)
    webrick (1.7.0)

PLATFORMS
  arm64-darwin-20

DEPENDENCIES
  jekyll (~> 4.2.1)
  jekyll-feed (~> 0.12)
  minima (~> 2.5)
  tzinfo (~> 1.2)
  tzinfo-data
  wdm (~> 0.1.1)
  webrick (~> 1.7)

BUNDLED WITH
   2.2.32
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
This is very strange because according to the stacktrace you're using bundler 2.2.22 but according to the env you're using 2.3.32. I think this might be the same issue as #5098.

What's the result of `gem list bundler`?

**Comment by deivid-rodriguez** [comment]
Your ruby installation seems completely messed up. How did you install ruby?

**Comment by deivid-rodriguez** [comment]
I guess you installed it with `brew install ruby`, right? What's the result of `which gem`, and also the result of `gem info bundler`.

**Comment by deivid-rodriguez** [comment]
Alright, that explains things. After running `brew install ruby`, you should've got the following post install message:

```
(...)
==> Caveats
By default, binaries installed by gem will be placed into:
  /opt/homebrew/lib/ruby/gems/3.0.0/bin

You may want to add this to your PATH.

ruby is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have ruby first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc

For compilers to find ruby you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"

For pkg-config to find ruby you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"

(...)
```

You need to follow those instructions, in particular the ones about setting your `PATH`. Otherwise your system ruby will be mixed with your brewed ruby and things will go wrong like it happened here.

I think we can improve this by implementing what was suggested in https://github.com/rubygems/rubygems/issues/3339, so I'll defer to that ticket and close this.

Good luck!

**Comment by golovanevsky** [comment]
Thank you David! Will reinstall ruby and follow along these instructions. 
Best wishes, 
Eugene

**Comment by deivid-rodriguez** [comment]
Hei, if you are going to reinstall ruby, I would strongly suggest to go with `brew install rbenv`, then follow whatever setup instructions that prints, then install a ruby version through `rbenv` (`rbenv install 3.0.2` for example). I have never used `ruby` packaged by `brew` so I have no idea how that works, but `rbenv` is a battle tested solution used by many people so it should just work.

**Comment by golovanevsky** [comment]
Sounds great, will use `rbenv`. Thanks a lot for your help David!
