### ISSUE TITLE
Bundler 2.2.32: misleading error message for Errno::EACCES

### ISSUE THREAD

**Issue by SimonEast** [rubygems/rubygems#5105]
### Describe the problem as clearly as you can

When bundler catches an `Errno::EACCES` error, it presents the following error message, which is actually misleading in cases where `Errno::EACCES` is raised by a firewall rule *NOT* a temp directory permissions issue:

```
There was an error while trying to write to `Bundler does not have write access
to create a temp directory within C:/Users/Simon/AppData/Local/Temp. Bundler
must have write access to your systems temp directory to function properly. `.
It is likely that you need to grant write permissions for that path.
```

This may be specific to Windows OS, I'm not sure if other platforms also raise `Errno::EACCES` when blocked by a firewall.

### Did you try upgrading rubygems & bundler?

Yes, using Bundler 2.2.32.

### Post steps to reproduce the problem

1. On Windows, setup a firewall rule to block `ruby.exe` from initiating outgoing connections. On my system, I use TinyWall, but other firewall apps may perform similarly.
2. Run any `bundle` command that requires internet access
3. The error message shown above appears
4. After disabling the firewall block and allowing the application through, the above error message resolves

### Which command did you run?

`bundle install`

### What were you expecting to happen?

To see an error message about internet connectivity.

### What actually happened?

It told me that my temp folder permissions were incorrect.

## Environment

```
Bundler       2.2.32
  Platforms   ruby, x64-mingw32
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x64-mingw32]
  Full Path   d:/Ruby/v30-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.2.32
  Gem Home    d:/Ruby/v30-x64/lib/ruby/gems/3.0.0
  Gem Path    C:/Users/-----/.gem/ruby/3.0.0;d:/Ruby/v30-x64/lib/ruby/gems/3.0.0
  User Home   C:/Users/------
  User Path   C:/Users/-------/.gem/ruby/3.0.0
  Bin Dir     d:/Ruby/v30-x64/bin
Tools
  Git         2.30.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-11-23
Git SHA           20d4957649
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
Just out of curiosity, if you completely remove this error from the source code like I did in #5110, which error do you get instead? Can you copy it here?

**Comment by SimonEast** [comment]
Thanks for the reply David. Here's my output.

```
D:\Dev> bundle update
Fetching https://github.com/eventmachine/eventmachine.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using public_suffix 4.0.6
Fetching addressable 2.8.0 (was 2.7.0)

Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError Errno::EACCES: Failed to open TCP connection to rubygems.org:443 (Permission denied - connect(2) for "rubygems.org" port 443) (https://rubygems.org/gems/addressable-2.8.0.gem)

Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError Errno::EACCES: Failed to open TCP connection to rubygems.org:443 (Permission denied - connect(2) for "rubygems.org" port 443) (https://rubygems.org/gems/addressable-2.8.0.gem)

Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError Errno::EACCES: Failed to open TCP connection to rubygems.org:443 (Permission denied - connect(2) for "rubygems.org" port 443) (https://rubygems.org/gems/addressable-2.8.0.gem)

Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to
underlying error <Errno::EACCES: Failed to open TCP connection to
rubygems.org:443 (Permission denied - connect(2) for "rubygems.org" port 443)
(https://rubygems.org/gems/addressable-2.8.0.gem)>
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:549:in
`rescue in download_gem'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:521:in
`download_gem'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:523:in
`download_gem'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:475:in
`fetch_gem'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:161:in
`install'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in
`install'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in
`do_install'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:171:in
`install_serially'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:97:in
`call'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in
`call'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:262:in
`install_in_parallel'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:209:in `install'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:89:in `block in
run'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:19:in `rescue
in lock'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:15:in `lock'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:71:in `run'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:23:in `install'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli/update.rb:74:in `run'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:301:in `block in
update'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/settings.rb:131:in
`temporary'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:300:in `update'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in
`run'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in
`invoke_command'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in
`dispatch'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in
`start'
  d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
d:/Ruby/v30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:49:in
`block in <top (required)>'
d:/Ruby/v30-x64/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:103:in
`with_friendly_errors'
d:/Ruby/v30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:37:in `<top
(required)>'
  d:/Ruby/v30-x64/bin/bundle:23:in `load'
  d:/Ruby/v30-x64/bin/bundle:23:in `<main>'

An error occurred while installing addressable (2.8.0), and Bundler cannot
continue.
```

**Comment by deivid-rodriguez** [comment]
I'm still confused about how and why this error is being raised. If you comment out the following lines

https://github.com/rubygems/rubygems/blob/ddd3d2cc323b423bdb5d2fbe6324e4683202d2c5/bundler/lib/bundler/rubygems_integration.rb#L536-L537

And rerun the command with the `--verbose` flag, can you copy the result again?

**Comment by SimonEast** [comment]
Thanks David. Looks like you submitted a patch that improved this. 

Did you still want me to troubleshoot the error in more detail?

**Comment by deivid-rodriguez** [comment]
Yes, please!
