### ISSUE TITLE
Bundler should only retry specific network errors, not all errors

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#5161]
### Describe the problem as clearly as you can

If any error occurs during gem package fetching, bundler will always retry it. But many errors will keep happening again and again, and once bundler gives up, it will give a less informative error.

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

You can follow the steps to reproduce #5160.

### Which command did you run?

`bundle install`

### What were you expecting to happen?

I was expecting the kind of error that would happen if gem download was not retried when this kind of error happens, and we aborted immediately instead. It would look like this:

````
$ bundle install
Fetching gem metadata from https://rubygems.org/.
Fetching rake 13.0.6
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Encoding::UndefinedConversionError: "\x8B" from ASCII-8BIT to UTF-8
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems.rb:804:in `write'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems.rb:804:in `block in write_binary'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems.rb:803:in `open'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems.rb:803:in `write_binary'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:292:in `cache_update_path'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:524:in `block in download_gem'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:103:in `filesystem_access'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:523:in `download_gem'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:527:in `download_gem'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:479:in `fetch_gem'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:165:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:90:in `call'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in `call'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:259:in `install_in_parallel'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:209:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:89:in `block in run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:9:in `open'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:9:in `lock'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:71:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:23:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli/install.rb:60:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:253:in `block in install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:252:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
  /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:49:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:37:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.3.0.dev
  Platforms   ruby, aarch64-linux
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.0.dev
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.0.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1k  25 Mar 2021
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-13
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

## Gemfile

### Gemfile

```ruby
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rake", "~> 13.0"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.6)

PLATFORMS
  aarch64-linux

DEPENDENCIES
  rake (~> 13.0)

BUNDLED WITH
   2.2.32
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=%22%5Cx8B%22+from+ASCII-8BIT+to+UTF-8&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
```
````
 
### What actually happened?

I guess when the fetching is retried, there's a corrupted package already in cache, and bundler crashes somewhere else, showing an unrelated backtrace, and from the actual culprit, all we can see is the error class:

````
$ bundle install
Fetching gem metadata from https://rubygems.org/.
Fetching rake 13.0.6

Retrying download gem from https://rubygems.org/ due to error (2/4): Encoding::UndefinedConversionError "\x8B" from ASCII-8BIT to UTF-8
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::Package::FormatError: package metadata is missing in /usr/local/bundle/cache/rake-13.0.6.gem
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:670:in `verify_files'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:596:in `block (2 levels) in verify'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package/tar_reader.rb:27:in `new'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:593:in `block in verify'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:29:in `open'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:592:in `verify'
  /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:573:in `spec'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:238:in `spec_from_gem'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:167:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:90:in `call'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in `call'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:259:in `install_in_parallel'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:209:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:89:in `block in run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:9:in `open'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:9:in `lock'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:71:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:23:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli/install.rb:60:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:253:in `block in install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:252:in `install'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
  /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:49:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:37:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.3.0.dev
  Platforms   ruby, aarch64-linux
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.0.dev
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.0.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1k  25 Mar 2021
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-13
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

## Gemfile

### Gemfile

```ruby
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rake", "~> 13.0"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.6)

PLATFORMS
  aarch64-linux

DEPENDENCIES
  rake (~> 13.0)

BUNDLED WITH
   2.2.32
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=package+metadata+is+missing+in+%2Fusr%2Flocal%2Fbundle%2Fcache%2Frake-13.0.6.gem&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
````

**Comment by ximenasandoval** [comment]
Hi! I'd like to work on this issue 🙌🏽

**Comment by ximenasandoval** [comment]
Hi! I've been having problems while recreating the issue, I was trying to recreate it by using the version of this [commit](https://github.com/rubygems/rubygems/commit/a672e7555c1d04abfd07d896fcd90b147d4aa984), using the same `Gemfile` as stated in this [issue](https://github.com/rubygems/rubygems/issues/5160) and in here too, but I still can't seem to recreate the error, is there a configuration am I missing? Thanks a lot in advance!

**Comment by deivid-rodriguez** [comment]
Hello @ximenasandoval, let me have a look at this now.

**Comment by deivid-rodriguez** [comment]
I did manage to reproduce the issue using the commit you mentioned. Once thing I had to do is to remove the `rake` gem (`gem uninstall rake`) before running `bundle install`.

**Comment by ximenasandoval** [comment]
I managed to reproduce it! Thank you, will start to work on it!

**Comment by deivid-rodriguez** [comment]
Awesome, thanks so much! 💪

**Comment by ximenasandoval** [comment]
Hello! Sorry for the delay, but I figure that a way to fix this is to pass the `StandardError` class to the  `Bundler::Retry` object (`/bundler/lib/bundler/rubygems_integration.rb`) #5270 
```
 Bundler::Retry.new("download gem from #{uri}", StandardError).attempts do
```
I've been working on testing, but since it comes from an older version I've been having problems with it. I haven't been able to figure out how to design a test that covers this change. Any suggestions? I'll keep looking for ways to replicate it with the most recent version!

**Comment by deivid-rodriguez** [comment]
But one question, aren't network errors also `StandardError` instances? If I understand correctly, your change would disable retries for any `StandardError`'s, including network errors? My idea was to keep an allowlist of network errors that need to be retried, and only retry errors when those are raised.

**Comment by ximenasandoval** [comment]
Hi! Thank you for the follow-up, and you're right! Now that I'm double-checking I was checking incorrectly for the error types. I'll fix the approach 😄

**Comment by deivid-rodriguez** [comment]
We've recently fixed a bunch of issues with retries, and I suspect this issue is now fixed, so I'll close this and the related PR.
