### ISSUE TITLE
unable to create a project folder

### ISSUE THREAD

**Issue by haileythompson905** [rubygems/rubygems#5169]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/arm64-darwin-20/3.0.0/racc-1.6.0
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:203:in `write_gem_make_out'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:131:in `build_error'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:165:in `rescue in build_extension'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:154:in `build_extension'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:191:in `block in build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:828:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:62:in `apply_func'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `loop'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `process_queue'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.33
  Platforms   ruby, arm64-darwin-20
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [arm64-darwin20]
  Full Path   /Users/haileythompson/.rbenv/versions/3.0.2/bin/ruby
  Config Dir  /Users/haileythompson/.rbenv/versions/3.0.2/etc
RubyGems      3.2.22
  Gem Home    /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  Gem Path    /Users/haileythompson/.gem/ruby/3.0.0:/Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  User Home   /Users/haileythompson
  User Path   /Users/haileythompson/.gem/ruby/3.0.0
  Bin Dir     /Users/haileythompson/.rbenv/versions/3.0.2/bin
OpenSSL
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   /Users/haileythompson/.rbenv/versions/3.0.2/openssl/ssl/cert.pem
  Cert Dir    /Users/haileythompson/.rbenv/versions/3.0.2/openssl/ssl/certs
Tools
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-07
Git SHA           9b5e2a350b
Released Version  true
```

## Bundler settings

```
ignore_messages
  Set via BUNDLE_IGNORE_MESSAGES: true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.3'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
<No /Users/haileythompson/Desktop/ror_coursework/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Fhaileythompson%2F.rbenv%2Fversions%2F3.0.2%2Flib%2Fruby%2Fgems%2F3.0.0%2Fextensions%2Farm64-darwin-20%2F3.0.0%2Fracc-1.6.0&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
         run  bundle binstubs bundler
Could not find gem 'pg (~> 1.1)' in locally installed gems.
Haileys-Air:desktop haileythompson$
Haileys-Air:desktop haileythompson$ bundle binstubs bundler
Could not locate Gemfile or .bundle/ directory
Haileys-Air:desktop haileythompson$ cd ror_coursework
Haileys-Air:ror_coursework haileythompson$ code .
Haileys-Air:ror_coursework haileythompson$ bundle
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using minitest 5.14.4
Using zeitwerk 2.5.1
Using erubi 1.10.0
Fetching racc 1.6.0
Using crass 1.0.6
Using rack 2.2.3
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Using mini_mime 1.1.2
Fetching msgpack 1.4.2
Using method_source 1.0.0
Using bundler 2.2.33
Fetching pg 1.2.3
Fetching ffi 1.15.4
Using thor 1.1.0
Using spring 4.0.0
Using rb-fsevent 0.11.0
Using coderay 1.1.3
Using builder 3.2.4
Using i18n 1.8.11
Fetching puma 5.5.2
Using tzinfo 2.0.4
Using rack-test 1.1.0
Using websocket-driver 0.7.5
Using mail 2.7.1
Using sprockets 4.0.2
Using activesupport 6.1.4.3
Using faker 2.19.0
Using pry 0.14.1
Using activemodel 6.1.4.3
Using globalid 1.0.0
Using activerecord 6.1.4.3
Using activejob 6.1.4.3
Installing racc 1.6.0 with native extensions
Installing msgpack 1.4.2 with native extensions
Installing puma 5.5.2 with native extensions
Installing pg 1.2.3 with native extensions
Installing ffi 1.15.4 with native extensions
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using minitest 5.14.4
Using zeitwerk 2.5.1
Using builder 3.2.4
Using erubi 1.10.0
Fetching msgpack 1.4.2
Fetching racc 1.6.0
Using crass 1.0.6
Using bundler 2.2.33
Using nio4r 2.5.8
Fetching ffi 1.15.4
Using mini_mime 1.1.2
Using rack 2.2.3
Using websocket-extensions 0.1.5
Fetching pg 1.2.3
Using method_source 1.0.0
Using rb-fsevent 0.11.0
Using spring 4.0.0
Using coderay 1.1.3
Using thor 1.1.0
Fetching puma 5.5.2
Using marcel 1.0.2
Using i18n 1.8.11
Using mail 2.7.1
Using websocket-driver 0.7.5
Using rack-test 1.1.0
Using sprockets 4.0.2
Using faker 2.19.0
Using tzinfo 2.0.4
Using pry 0.14.1
Using activesupport 6.1.4.3
Using globalid 1.0.0
Using activejob 6.1.4.3
Using activemodel 6.1.4.3
Using activerecord 6.1.4.3
Installing racc 1.6.0 with native extensions
Installing msgpack 1.4.2 with native extensions
Installing pg 1.2.3 with native extensions
Installing puma 5.5.2 with native extensions
Installing ffi 1.15.4 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/arm64-darwin-20/3.0.0/racc-1.6.0
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:203:in `write_gem_make_out'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:131:in `build_error'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:165:in `rescue in build_extension'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:154:in `build_extension'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:191:in `block in build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:828:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:62:in `apply_func'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `loop'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `process_queue'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.33
  Platforms   ruby, arm64-darwin-20
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [arm64-darwin20]
  Full Path   /Users/haileythompson/.rbenv/versions/3.0.2/bin/ruby
  Config Dir  /Users/haileythompson/.rbenv/versions/3.0.2/etc
RubyGems      3.2.22
  Gem Home    /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  Gem Path    /Users/haileythompson/.gem/ruby/3.0.0:/Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  User Home   /Users/haileythompson
  User Path   /Users/haileythompson/.gem/ruby/3.0.0
  Bin Dir     /Users/haileythompson/.rbenv/versions/3.0.2/bin
OpenSSL
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   /Users/haileythompson/.rbenv/versions/3.0.2/openssl/ssl/cert.pem
  Cert Dir    /Users/haileythompson/.rbenv/versions/3.0.2/openssl/ssl/certs
Tools
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-07
Git SHA           9b5e2a350b
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.3'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'pry'
  gem 'faker'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
<No /Users/haileythompson/Desktop/ror_coursework/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Fhaileythompson%2F.rbenv%2Fversions%2F3.0.2%2Flib%2Fruby%2Fgems%2F3.0.0%2Fextensions%2Farm64-darwin-20%2F3.0.0%2Fracc-1.6.0&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
Haileys-Air:ror_coursework haileythompson$ bundle exec rails db:create
Could not find gem 'pg (~> 1.1)' in locally installed gems.
Run `bundle install` to install missing gems.
Haileys-Air:ror_coursework haileythompson$ bundle install
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using zeitwerk 2.5.1
Using builder 3.2.4
Fetching racc 1.6.0
Using crass 1.0.6
Using rack 2.2.3
Using websocket-extensions 0.1.5
Fetching msgpack 1.4.2
Using bundler 2.2.33
Using coderay 1.1.3
Fetching ffi 1.15.4
Using minitest 5.14.4
Using rb-fsevent 0.11.0
Using method_source 1.0.0
Fetching pg 1.2.3
Using erubi 1.10.0
Using nio4r 2.5.8
Using marcel 1.0.2
Using mini_mime 1.1.2
Using thor 1.1.0
Using tzinfo 2.0.4
Using rack-test 1.1.0
Using i18n 1.8.11
Using pry 0.14.1
Fetching puma 5.5.2
Using sprockets 4.0.2
Using websocket-driver 0.7.5
Using mail 2.7.1
Using spring 4.0.0
Using faker 2.19.0
Using activesupport 6.1.4.3
Using globalid 1.0.0
Using activemodel 6.1.4.3
Using activejob 6.1.4.3
Using activerecord 6.1.4.3
Installing racc 1.6.0 with native extensions
Installing msgpack 1.4.2 with native extensions
Installing puma 5.5.2 with native extensions
Installing pg 1.2.3 with native extensions
Installing ffi 1.15.4 with native extensions
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using minitest 5.14.4
Using zeitwerk 2.5.1
Fetching racc 1.6.0
Using builder 3.2.4
Using marcel 1.0.2
Fetching msgpack 1.4.2
Using erubi 1.10.0
Using bundler 2.2.33
Using crass 1.0.6
Fetching ffi 1.15.4
Using coderay 1.1.3
Using rack 2.2.3
Using method_source 1.0.0
Fetching pg 1.2.3
Using nio4r 2.5.8
Using rb-fsevent 0.11.0
Using thor 1.1.0
Using mini_mime 1.1.2
Using i18n 1.8.11
Using websocket-extensions 0.1.5
Using rack-test 1.1.0
Using tzinfo 2.0.4
Fetching puma 5.5.2
Using pry 0.14.1
Using spring 4.0.0
Using sprockets 4.0.2
Using faker 2.19.0
Using activesupport 6.1.4.3
Using mail 2.7.1
Using activemodel 6.1.4.3
Using websocket-driver 0.7.5
Using globalid 1.0.0
Using activejob 6.1.4.3
Using activerecord 6.1.4.3
Installing racc 1.6.0 with native extensions
Installing msgpack 1.4.2 with native extensions
Installing pg 1.2.3 with native extensions
Installing puma 5.5.2 with native extensions
Installing ffi 1.15.4 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/arm64-darwin-20/3.0.0/racc-1.6.0
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:203:in `write_gem_make_out'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:131:in `build_error'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:165:in `rescue in build_extension'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:154:in `build_extension'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:191:in `block in build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `each'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:828:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:62:in `apply_func'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `loop'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `process_queue'
  /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.33
  Platforms   ruby, arm64-darwin-20
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [arm64-darwin20]
  Full Path   /Users/haileythompson/.rbenv/versions/3.0.2/bin/ruby
  Config Dir  /Users/haileythompson/.rbenv/versions/3.0.2/etc
RubyGems      3.2.22
  Gem Home    /Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  Gem Path    /Users/haileythompson/.gem/ruby/3.0.0:/Users/haileythompson/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  User Home   /Users/haileythompson
  User Path   /Users/haileythompson/.gem/ruby/3.0.0
  Bin Dir     /Users/haileythompson/.rbenv/versions/3.0.2/bin
OpenSSL
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   /Users/haileythompson/.rbenv/versions/3.0.2/openssl/ssl/cert.pem
  Cert Dir    /Users/haileythompson/.rbenv/versions/3.0.2/openssl/ssl/certs
Tools
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-07
Git SHA           9b5e2a350b
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.3'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'pry'
  gem 'faker'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
<No /Users/haileythompson/Desktop/ror_coursework/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this. It seems related to gem extension caching on a platform specific location. Did you upgrade your MacOS version recently?

**Comment by holako-751** [comment]
![IMG-20211216-WA0005](https://user-images.githubusercontent.com/96255834/146415378-0071cd40-c6ad-41f7-995c-82fe1ceb075f.jpg)

where is the problem
I want help with
shortest time
Give me a way
fix it please

**Comment by holako-751** [comment]
![Screenshot_2021-12-16-18-03-35-408_com termux](https://user-images.githubusercontent.com/96255834/146416193-0c8b97f7-6047-4658-914a-fafcd583746a.jpg)


where is the problem
I want help with
shortest time
Give me a way
fix it please

**Comment by holako-751** [comment]
where is the problem
I want help with
shortest time
Give me a way
fix it please

**Comment by holako-751** [comment]
where is the problem
I want help with
shortest time
Give me a way
fix it please
