### ISSUE TITLE
Getting error while creating demo rails app related to sqlite3 not installed

### ISSUE THREAD

**Issue by eelectron** [rubygems/rubygems#5176]
### Describe the problem as clearly as you can

Getting error while creating demo app .

```
prashantsingh@Prashants-MacBook-Air: ~
$ rails new demo 

...

Bundler::PermissionError: There was an error while trying to delete
`/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0`. It is likely that you need to grant executable
permissions for all parent directories and write permissions for `/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems`,
and the same thing for all subdirectories inside /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0.
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:103:in `strict_rm_rf'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:19:in `install'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in
worker_pool'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing racc (1.6.0), and Bundler cannot continue.

In Gemfile:
  rails was resolved to 6.1.4.4, which depends on
    actioncable was resolved to 6.1.4.4, which depends on
      actionpack was resolved to 6.1.4.4, which depends on
        actionview was resolved to 6.1.4.4, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri was resolved to 1.12.5, which depends on
              racc


Bundler::PermissionError: There was an error while trying to delete
`/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sqlite3-1.4.2`. It is likely that you need to grant executable
permissions for all parent directories and write permissions for `/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems`,
and the same thing for all subdirectories inside /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sqlite3-1.4.2.
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:103:in `strict_rm_rf'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:19:in `install'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in
worker_pool'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.

In Gemfile:
  sqlite3
         run  bundle binstubs bundler
Could not find gem 'sqlite3 (~> 1.4)' in locally installed gems.
       rails  webpacker:install
Could not find gem 'sqlite3 (~> 1.4)' in locally installed gems.
Run `bundle install` to install missing gems.

```

### Did you try upgrading rubygems & bundler?
yes

### Post steps to reproduce the problem

```
prashantsingh@Prashants-MacBook-Air: ~
$ rails -v 
Rails 6.1.3.2

prashantsingh@Prashants-MacBook-Air: ~
$ sw_vers                                                                                                                   
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559

prashantsingh@Prashants-MacBook-Air: ~
$ sqlite3                                                                                                                   
SQLite version 3.36.0 2021-06-18 18:58:49
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> 
```

### What were you expecting to happen?
I am trying to create demo rails app from https://rubyonrails.org .

### What actually happened?
Getting below error related to sqlite3 not installed . But it is installed .

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.

In Gemfile:
  sqlite3
         run  bundle binstubs bundler
Could not find gem 'sqlite3 (~> 1.4)' in locally installed gems.
       rails  webpacker:install
Could not find gem 'sqlite3 (~> 1.4)' in locally installed gems.
Run `bundle install` to install missing gems.

## Environment

```
Bundler       2.2.33
  Platforms   ruby, x86_64-darwin-19
Ruby          3.0.1p64 (2021-04-05 revision 0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0) [x86_64-darwin19]
  Full Path   /Users/prashantsingh/.rbenv/versions/3.0.1/bin/ruby
  Config Dir  /Users/prashantsingh/.rbenv/versions/3.0.1/etc
RubyGems      3.2.33
  Gem Home    /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  Gem Path    /Users/prashantsingh/.gem/ruby/3.0.0:/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  User Home   /Users/prashantsingh
  User Path   /Users/prashantsingh/.gem/ruby/3.0.0
  Bin Dir     /Users/prashantsingh/.rbenv/versions/3.0.1/bin
Tools         
  Git         2.18.0
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-07
Git SHA           9b5e2a350b
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
It seems you have some permission issues in your gem folder? Can you show the result of 

```
ls -ld /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/
```

and

```
tree -pufid /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0
```

**Comment by eelectron** [comment]
```
prashantsingh@Prashants-MacBook-Air: ~/Documents/Learn/Ruby
$ ls -ld /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/                                                                 
drwxr-xr-x  3 prashantsingh  staff  96 Jun 15  2021 /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/
```

```
prashantsingh@Prashants-MacBook-Air: ~/Documents/Learn/Ruby
$ tree -pufid /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0                                   
/Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/bin
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/doc
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/doc/en
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/doc/ja
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/ext
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/ext/racc
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/ext/racc/cparse
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/lib
[drwxr-xr-x root    ]  /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/racc-1.6.0/lib/racc

9 directories
```

**Comment by deivid-rodriguez** [comment]
There you go, bundler can't write to your gem home because it's owned by root. You should fix those permissions by changing the owner to be you. I guess something like `sudo chown -R prashantsingh:staff /Users/prashantsingh/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems` should do the trick.

**Comment by eelectron** [comment]
Finally it worked with little modification in folder path ! Thanks for your time :) 
```
prashantsingh@Prashants-MacBook-Air: ~/Documents/Learn/Ruby
$ sudo chown -R prashantsingh:staff /Users/prashantsingh/.rbenv/versions/3.0.1/                                                    
Password:
 
prashantsingh@Prashants-MacBook-Air: ~/Documents/Learn/Ruby
$ rails new demo  
...
├─ uuid@3.4.0
├─ wbuf@1.7.3
├─ webpack-dev-middleware@3.7.3
├─ webpack-dev-server@3.11.3
├─ websocket-driver@0.7.4
├─ websocket-extensions@0.1.4
└─ ws@6.2.2
✨  Done in 5.93s.
Webpacker successfully installed 🎉 🍰
```

**Comment by deivid-rodriguez** [comment]
No problem!
