### ISSUE TITLE
Test failures with Ruby 3.1 due to OpenSSL changes

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#5192]
Testing with `ruby 3.1.0dev (2021-12-21 master cdb7d699d0) [x86_64-linux]`, I observe the following test failures:

~~~
  1) Error:
TestGemCommandsCertCommand#test_execute_build_ec_key:
OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:430:in `public_key='
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:430:in `get_public_key'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:405:in `create_cert'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:460:in `create_cert_self_signed'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:451:in `create_cert_email'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:157:in `build_cert'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:143:in `build'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:123:in `block in execute'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:122:in `each'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:122:in `execute'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/test/rubygems/test_gem_commands_cert_command.rb:326:in `block in test_execute_build_ec_key'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/user_interaction.rb:46:in `use_ui'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/user_interaction.rb:69:in `use_ui'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/test/rubygems/test_gem_commands_cert_command.rb:325:in `test_execute_build_ec_key'

  2) Error:
TestGemCommandsCertCommand#test_execute_build_key_algorithm_ec_key:
OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:494:in `generate_key!'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:494:in `create_key'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:179:in `build_key'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:142:in `build'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:123:in `block in execute'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:122:in `each'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/commands/cert_command.rb:122:in `execute'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/test/rubygems/test_gem_commands_cert_command.rb:154:in `block in test_execute_build_key_algorithm_ec_key'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/user_interaction.rb:46:in `use_ui'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/user_interaction.rb:69:in `use_ui'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/test/rubygems/test_gem_commands_cert_command.rb:153:in `test_execute_build_key_algorithm_ec_key'

  3) Error:
TestGemSecurity#test_class_get_public_key_ec:
OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:430:in `public_key='
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:430:in `get_public_key'
    /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/test/rubygems/test_gem_security.rb:134:in `test_class_get_public_key_ec'
~~~

**Comment by voxik** [comment]
I should have mentioned that latest OpenSSL changes have landed recently:

https://github.com/ruby/ruby/commits/master/ext/openssl

**Comment by rhenium** [comment]
> ```
> OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0
> ```

Due to an incompatible change in OpenSSL 3.0, Ruby/OpenSSL had no choice but to disable these methods when it's built against OpenSSL >= 3.0.0.

> ```
> /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:494:in `create_key'
> ```
> ```
> /builddir/build/BUILD/ruby-3.1.0-cdb7d699d0/lib/rubygems/security.rb:430:in `get_public_key'
> ```

Both should be simple to work around it. I will come up with a PR.
