### ISSUE TITLE
Bundler requires Gemfile to be updated when Jekyll plugin list is refreshed

### ISSUE THREAD

**Issue by EmilySeville7cfg** [rubygems/rubygems#5239]
### Environment

OS: `Linux Mint 20.2 Cinnamon`
Bundler: `Bundler version 2.3.3`
Ruby: `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`

### Related issue

https://github.com/jekyll/jekyll/issues/8917

### Describe the problem as clearly as you can

It is [written](https://jekyllrb.com/docs/plugins/installation/) that we can just (second option):
- add plugin under `plugins:` key in `_config.yml`
- install mention plugin via `gem install`

But `bundle exec jekyll serve` fails until smth like this is not added to Gemfile:

```ruby
["jekyll-default-layout",
  "jekyll-gist",
  "jekyll-github-metadata",
  "jekyll-optional-front-matter",
  "jekyll-paginate",
  "jekyll-readme-index",
  "jekyll-titles-from-headings",
  "jekyll-relative-links"].each do |plugin|
  gem plugin
end
```

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

1. `jekyll new test`
2. `cd test`
3. `gem install jekyll-default-layout`
4. add `jekyll-default-layout` under `plugins:` in `_config.json`
5. `bundle exec jekyll serve`
6. obtain an error

### Which command did you run?

`bundle exec jekyll serve`

### What were you expecting to happen?

No `Jekyll::Errors::MissingDependencyException` exception thrown is expected.

### What actually happened?

```
Configuration file: /home/emilyseville7cfg/Documents/mine/jekyll/test/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-default-layout or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-default-layout gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- jekyll-default-layout' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
        36: from /home/emilyseville7cfg/gems/bin/bundle:23:in `<main>'
        35: from /home/emilyseville7cfg/gems/bin/bundle:23:in `load'
        34: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
        33: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        32: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
        31: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
        30: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        29: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
        28: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        27: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        26: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        25: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:484:in `exec'
        24: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:23:in `run'
        23: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
        22: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `load'
        21: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `<top (required)>'
        20: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `load'
        19: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        18: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        17: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        16: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        15: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        14: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        13: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        12: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        11: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        10: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
         9: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `process'
         8: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `new'
         7: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:36:in `initialize'
         6: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:131:in `setup'
         5: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
         4: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:30:in `require_gems'
         3: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
         2: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `each'
         1: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail'
/home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:60:in `require': cannot load such file -- jekyll-default-layout (LoadError)
        36: from /home/emilyseville7cfg/gems/bin/bundle:23:in `<main>'
        35: from /home/emilyseville7cfg/gems/bin/bundle:23:in `load'
        34: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
        33: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        32: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
        31: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
        30: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        29: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
        28: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        27: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        26: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        25: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli.rb:484:in `exec'
        24: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:23:in `run'
        23: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
        22: from /home/emilyseville7cfg/gems/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `load'
        21: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `<top (required)>'
        20: from /home/emilyseville7cfg/gems/bin/jekyll:23:in `load'
        19: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        18: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        17: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        16: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        15: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        14: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        13: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        12: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        11: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        10: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
         9: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `process'
         8: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `new'
         7: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:36:in `initialize'
         6: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:131:in `setup'
         5: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
         4: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:30:in `require_gems'
         3: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
         2: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:57:in `each'
         1: from /home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
/home/emilyseville7cfg/gems/gems/jekyll-4.2.1/lib/jekyll/external.rb:73:in `rescue in block in require_with_graceful_fail': jekyll-default-layout (Jekyll::Errors::MissingDependencyException)
```

**Comment by deivid-rodriguez** [comment]
Hi! I don't know much about Jekyll but in principle this seems expected. I think the 2nd documented option is for using Jekyll without Bundler (so for running `jekyll serve` without `bundle exec` and without a `Gemfile`) while the 3rd documented options would be for using Jekyll with Bundler. Does it make sense? Jekyll should probably document just the 3rd option, or at least explicitly recommend it above the 2nd.

**Comment by ashmaroli** [comment]
@EmilySeville7cfg, @deivid-rodriguez I'm sorry for the noise. 
I misunderstood the linked original ticket at `jekyll/jekyll`.

The described behavior is indeed the expected behavior since Bundler narrows the scope of installed gems just to the runtime dependencies resolved from evaluating the (given) Gemfile.

This may be closed.

**Comment by deivid-rodriguez** [comment]
No worries, thanks for confirming!
