### ISSUE TITLE
histor

### ISSUE THREAD

**Issue by daBee** [rubygems/rubygems#5244]
### Describe the problem as clearly as you can

Getting an error of **bundler not found** while it is properly installed.

### Did you try upgrading rubygems & bundler?

Yes, `2.3.4`.  

### Post steps to reproduce the problem
```
$ bundle install

/usr/lib/ruby/vendor_ruby/rubygems.rb:281:in `find_spec_for_exe': Could not find 'bundler' (2.3.4) required by your /home/rich/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.3.4`
	from /usr/lib/ruby/vendor_ruby/rubygems.rb:258:in `bin_path'
	from /usr/lib/ruby/3.0.0/bundler/rubygems_integration.rb:207:in `bin_path'
	from /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:290:in `set_bundle_variables'
	from /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
	from /usr/lib/ruby/3.0.0/bundler/runtime.rb:20:in `setup'
	from /usr/lib/ruby/3.0.0/bundler.rb:150:in `setup'
	from /usr/lib/ruby/3.0.0/bundler/setup.rb:10:in `block in <top (required)>'
	from /usr/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
	from /usr/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
	from /usr/lib/ruby/3.0.0/bundler/setup.rb:10:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/rich/rfs/videos/get_timelapse.rb:6:in `<main>'
[Thu Dec 30 07:32:07 rich@myzero ~/rfs/videos] gem list

*** LOCAL GEMS ***

active_hash (3.1.0)
activesupport (7.0.0)
addressable (2.8.0)
awesome_print (1.9.2)
bcrypt (3.1.16)
bundler (2.3.4, 2.3.3)
canada_eh (0.0.4)

```

Fill this with a list of steps maintainers can follow to reproduce your issue. Note that while you are seeing this issue in your computer, maintainers might not see the same thing on theirs. There is a number of things that could influence this:

* How your ruby is setup (OS package, from source, using a version manager).
- Ruby compiled for `Raspberry Pi OS`, **v3.0.3**.

* How bundler & rubygems are configured.
`gem install bundler`

* The version of each involved piece of software that you are using.
`Ruby 3.0.3`, `bundler 2.3.4`.

I don't have docker. 

### Which command did you run?

`bundle install` ==> installs bundler 2.3.4
require 'bundler/setup'
Bundler.require ==> throws error

### What were you expecting to happen?

`bundler` to load associated gems in `Gemfile`, and run the script.  

### What actually happened?

Throws an error saying it cannot find `bundler` when it is indeed installed.  [Thu Dec 30 07:44:08 rich@myzero ~/rfs/videos] bundle env
## Environment

```
Bundler       2.3.4
  Platforms   ruby, armv7l-linux-eabihf
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [armv7l-linux-eabihf]
  Full Path   /usr/bin/ruby
  Config Dir  /usr/etc
RubyGems      3.2.5
  Gem Home    /var/lib/gems/3.0.0
  Gem Path    /home/rich/.local/share/gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/armv7l-linux-eabihf/ruby/gems/3.0.0:/usr/share/rubygems-integration/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/armv7l-linux-eabihf/rubygems-integration/3.0.0
  User Home   /home/rich
  User Path   /home/rich/.local/share/gem/ruby/3.0.0
  Bin Dir     /usr/local/bin
Tools
  Git         2.30.2
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-29
Git SHA           2296a0d6cc
Released Version  true
```

### ../../Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem 'pg'
# gem "sequel"
gem 'filewatcher'
gem 'clipboard'
gem 'colorize'
gem 'json'
gem 'awesome_print'						# better than stagnant awesome_print

gem 'faraday'									# https post
gem 'watir'						# AJAX stuff
gem 'webdrivers'						# for watir
gem 'faker'						# for watir
gem 'httparty'						# convenient http requests
gem 'smarter_csv'						# better CSV
gem 'pony'						# email

## specialty gems

gem 'bcrypt'
gem 'uuidtools'
gem 'nokogiri'
# gem 'mechanize'
gem 'canada_eh'						# Canadian methods n' stuff
gem 'geocoder'
gem 'faster_xml_simple'						# dealing with xml

gem "openssl"
gem "open3"
gem "date"
gem "open-uri"
```

### ../../Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    active_hash (3.1.0)
      activesupport (>= 5.0.0)
    activesupport (7.0.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    awesome_print (1.9.2)
    bcrypt (3.1.16)
    canada_eh (0.0.4)
      active_hash
    childprocess (4.1.0)
    clipboard (1.3.6)
    colorize (0.8.1)
    concurrent-ruby (1.1.9)
    date (3.2.2)
    faker (2.19.0)
      i18n (>= 1.6, < 2)
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faster_xml_simple (0.5.0)
      libxml-ruby (>= 0.3.8.4)
    filewatcher (1.1.1)
      optimist (~> 3.0)
    geocoder (1.7.0)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    json (2.6.1)
    libxml-ruby (3.2.1)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2021.1115)
    mini_mime (1.1.2)
    mini_portile2 (2.6.1)
    minitest (5.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    nokogiri (1.12.5)
      mini_portile2 (~> 2.6.1)
      racc (~> 1.4)
    open-uri (0.2.0)
      stringio
      time
      uri
    open3 (0.1.1)
    openssl (3.0.0)
    optimist (3.0.1)
    pony (1.13.1)
      mail (>= 2.0)
    racc (1.6.0)
    regexp_parser (2.2.0)
    rexml (3.2.5)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    smarter_csv (1.2.9)
    stringio (3.0.1)
    time (0.2.0)
      date
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    uri (0.11.0)
    uuidtools (2.2.0)
    watir (7.1.0)
      regexp_parser (>= 1.2, < 3)
      selenium-webdriver (~> 4.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)

PLATFORMS
  armv7l-linux-eabihf

DEPENDENCIES
  awesome_print
  bcrypt
  canada_eh
  clipboard
  colorize
  date
  faker
  faraday
  faster_xml_simple
  filewatcher
  geocoder
  httparty
  json
  nokogiri
  open-uri
  open3
  openssl
  pony
  smarter_csv
  uuidtools
  watir
  webdrivers

BUNDLED WITH
   2.3.4
```

**Comment by daBee** [comment]
Some more notes:

```
[Sat Jan 01 02:44:18 rich@myzero ~] gem which rubygems
Error loading RubyGems plugin "/var/lib/gems/3.1.0/plugins/a_plugin.rb": cannot load such file -- /home/rich/temp/ruby-3.1.0/tmp/test_rubygems_20211230-21585-u8vq2g/gemhome/gems/a-2/lib/rubygems_plugin.rb (LoadError)
/usr/lib/ruby/vendor_ruby/rubygems.rb
[Sat Jan 01 02:44:23 rich@myzero ~] l /usr/lib/ruby/vendor_ruby/rubygems
total 128
drwxr-xr-x 11 root root  4096 Dec 30 13:21 .
drwxr-xr-x  8 root root  4096 Dec 30 13:21 ..
drwxr-xr-x  2 root root  4096 Jul  8 15:10 2.7.0
drwxr-xr-x  3 root root  4096 Dec 24 07:10 3.0.0
drwxr-xr-x  3 root root  4096 Dec 30 13:21 3.1.0
drwxr-xr-x  2 root root  4096 Dec 24 01:28 hoe
drwxr-xr-x  2 root root  4096 Dec 24 01:28 minitest
-rw-r--r--  1 root root 24623 Nov 19  2019 minitest.rb
drwxr-xr-x  3 root root  4096 Dec 24 01:28 net
-rw-r--r--  1 root root    21 Mar  1  2016 net-telnet.rb
drwxr-xr-x  2 root root  4096 Dec 24 01:28 power_assert
-rw-r--r--  1 root root  2728 Feb 14  2021 power_assert.rb
drwxr-xr-x 14 root root  4096 Dec 24 01:28 rubygems
-rw-r--r--  1 root root 37906 Jan 13  2021 rubygems.rb
drwxr-xr-x  2 root root  4096 Dec 24 01:28 xmlrpc
-rw-r--r--  1 root root  8183 Jul 22  2018 xmlrpc.rb
```

Seems the file is there, but loading it isn't working, and cannot find the `rubygems` `gem`.

**Comment by deivid-rodriguez** [comment]
This seems some misconfiguration in your system. Somehow some test gems meant for testing rubygems have leaked into your global ruby installation (the "Error loading RubyGems plugin "/var/lib/gems/3.1.0/plugins/a_plugin.rb": cannot load such file -- /home/rich/temp/ruby-3.1.0/tmp/test_rubygems_20211230-21585-u8vq2g/gemhome/gems/a-2/lib/rubygems_plugin.rb (LoadError)" message).

Can you also post the result of `gem env`?

**Comment by daBee** [comment]
```
Error loading RubyGems plugin "/var/lib/gems/3.1.0/plugins/a_plugin.rb": cannot load such file -- /home/rich/temp/ruby-3.1.0/tmp/test_rubygems_20211230-21585-u8vq2g/gemhome/gems/a-2/lib/rubygems_plugin.rb (LoadError)
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.5
  - RUBY VERSION: 3.1.0 (2021-12-25 patchlevel 0) [armv7l-linux-eabihf]
  - INSTALLATION DIRECTORY: /var/lib/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /home/rich/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/rich/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - armv7l-linux-eabihf
  - GEM PATHS:
     - /var/lib/gems/3.1.0
     - /home/rich/.local/share/gem/ruby/3.1.0
     - /usr/local/lib/ruby/gems/3.1.0
     - /usr/lib/ruby/gems/3.1.0
     - /usr/lib/armv7l-linux-eabihf/ruby/gems/3.1.0
     - /usr/share/rubygems-integration/3.1.0
     - /usr/share/rubygems-integration/all
     - /usr/lib/armv7l-linux-eabihf/rubygems-integration/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/rich/.rbenv/shims
     - /users/rich/rfs/
     - /home/rich/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/local/games
     - /usr/games
```

**Comment by deivid-rodriguez** [comment]
Your ruby installation seems completely messed up. It's unclear how you installed Ruby, since there seems to be both `rbenv` and your OS ruby package involved. Also there are paths from both Ruby 3.1 and 3.0 in your reported command outputs.

I recommend that you reinstall `rbenv` from scratch and make sure to use that exclusively.

**Comment by daBee** [comment]
Yes I installed `rbenv` to only find out old versions were available.  So I tried `3.0.3` then `3.1.0`. I will retry `rbenv`.

**Comment by daBee** [comment]
Private method often coming up.  

    private method `require' called for Bundler:Module (NoMethodError)

## Environment

```
Bundler       2.3.5
  Platforms   ruby, armv7l-linux-eabihf
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [armv7l-linux-eabihf]
  Full Path   /home/rich/.rbenv/versions/2.7.1/bin/ruby
  Config Dir  /home/rich/.rbenv/versions/2.7.1/etc
RubyGems      3.1.2
  Gem Home    /home/rich/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0
  Gem Path    /home/rich/.gem/ruby/2.7.0:/home/rich/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0
  User Home   /home/rich
  User Path   /home/rich/.gem/ruby/2.7.0
  Bin Dir     /home/rich/.rbenv/versions/2.7.1/bin
Tools
  Git         2.30.2
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-01-12
Git SHA           a13d015fcb
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
Not sure if you alright reinstalled Rbenv. Anyways the original issue seems not related to a problem in Bundler or RubyGems but an issue with your system, so I'll close this. Feel free to report the new issue separately. Make sure to setup a pristine environment that you can share and where the issue can be reproduced, ok? Thank you!

**Comment by daBee** [comment]
Ya I took everything out but system couldn't be replaced.  So I started up again and it seems to have gone away.  More testing.
