### ISSUE TITLE
Documentation is not installed (--document is ignored)

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#5295]
Testing with Ruby 3.1, `gem install` does not generate documentation:

~~~
$ gem install --document=rdoc,ri gem2rpm
WARNING:  You don't have /builddir/bin in your PATH,
	  gem executables will not run.
Successfully installed gem2rpm-1.0.2
1 gem installed
<mock-chroot> sh-5.1$ gem install --document=rdoc,ri gem2rpm -V
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/gem2rpm
200 OK
WARNING:  You don't have /builddir/bin in your PATH,
	  gem executables will not run.
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/AUTHORS
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/LICENSE
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/README.md
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/bin/gem2rpm
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/configuration.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/distro.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/dependency.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/format.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/package.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/spec_fetcher.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/specification.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/helpers.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_dependency.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_dependency_list.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_file.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_file_list.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/template.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/template_helpers.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/lib/gem2rpm/test_suite.rb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/default.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-17-18.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-19-20.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-21-25-vagrant-plugin.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-21-25.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-26-vagrant-plugin.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-26.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-27-rawhide-vagrant-plugin.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora-27-rawhide.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/fedora.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/opensuse.spec.erb
/builddir/.local/share/gem/ruby/gems/gem2rpm-1.0.2/templates/pld.spec.erb
/builddir/bin/gem2rpm
Successfully installed gem2rpm-1.0.2
1 gem installed

$ gem -v
3.3.3
~~~

There is mentioned the #3888 in 3.3.0 changelog, but is it really available since 3.3?

**Comment by deivid-rodriguez** [comment]
> There is mentioned the #3888 in 3.3.0 changelog, but is it really available since 3.3?

Yes.

**Comment by deivid-rodriguez** [comment]
Interestingly, I cannot reproduce this. Documentation is generated properly on my system. 

```
$ gem install --document=rdoc,ri gem2rpm -V
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/gem2rpm
200 OK
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/AUTHORS
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/LICENSE
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/README.md
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/bin/gem2rpm
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/configuration.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/distro.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/dependency.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/format.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/package.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/spec_fetcher.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/gem/specification.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/helpers.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_dependency.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_dependency_list.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_file.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/rpm_file_list.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/template.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/template_helpers.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/lib/gem2rpm/test_suite.rb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/default.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-17-18.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-19-20.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-21-25-vagrant-plugin.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-21-25.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-26-vagrant-plugin.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-26.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-27-rawhide-vagrant-plugin.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora-27-rawhide.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/fedora.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/opensuse.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/gem2rpm-1.0.2/templates/pld.spec.erb
/Users/deivid/.rbenv/versions/3.1.0/bin/gem2rpm
Successfully installed gem2rpm-1.0.2
Parsing documentation for gem2rpm-1.0.2
Parsing sources...
100% [19/19]  lib/gem2rpm/test_suite.rb
Done installing documentation for gem2rpm after 0 seconds
1 gem installed

$ gem -v
3.3.5
```

**Comment by voxik** [comment]
After first look, I have the feeling that the issue might be the RubyGems plugins hooks, because this seems to workaround the issue:

~~~
$ RUBYOPT=-rrdoc gem install --document=rdoc,ri gem2rpm -V
~~~

This might be Fedora packaging issue (for the beginning, there were missing the RDoc => Psych => StringIO dependencies which were newly introduced).

Or issue with the RubyGems plugins? Is Ruby installer installing the plugin hooks correctly?

**Comment by voxik** [comment]
> This might be Fedora packaging issue (for the beginning, there were missing the RDoc => Psych => StringIO dependencies which were newly introduced).

Fixing the dependencies seems to fix the issue. Although it is surprising that there was not error report, anything. Will try to analyze, where the error is inhibited.

Thx for trying to reproduce and sorry for the noise.

**Comment by voxik** [comment]
https://github.com/rubygems/rubygems/blob/12aeef6ba9a3be0022be9934c1a3e4c46a03ed3a/lib/rubygems/rdoc.rb#L4-L12

Printing the error from the line [11](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/rdoc.rb#L11), I got the following:

~~~
$ gem install --document=rdoc,ri gem2rpm
Could not find 'stringio' (>= 0) among 7 total gem(s)
Checked in 'GEM_PATH=/builddir/.local/share/gem/ruby:/usr/share/gems:/usr/local/share/gems' at: /usr/share/gems/specifications/psych-4.0.3.gemspec, execute `gem env` for more information
/usr/share/rubygems/rubygems/specification.rb:1402:in `rescue in block in activate_dependencies'
/usr/share/rubygems/rubygems/specification.rb:1399:in `block in activate_dependencies'
/usr/share/rubygems/rubygems/specification.rb:1388:in `each'
/usr/share/rubygems/rubygems/specification.rb:1388:in `activate_dependencies'
/usr/share/rubygems/rubygems/specification.rb:1370:in `activate'
/usr/share/rubygems/rubygems/specification.rb:1406:in `block in activate_dependencies'
/usr/share/rubygems/rubygems/specification.rb:1388:in `each'
/usr/share/rubygems/rubygems/specification.rb:1388:in `activate_dependencies'
/usr/share/rubygems/rubygems/specification.rb:1370:in `activate'
/usr/share/rubygems/rubygems.rb:211:in `rescue in try_activate'
/usr/share/rubygems/rubygems.rb:204:in `try_activate'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:153:in `rescue in require'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:149:in `require'
/usr/share/rubygems/rubygems/rdoc.rb:5:in `<top (required)>'
/usr/share/rubygems/rubygems/commands/install_command.rb:254:in `require_relative'
/usr/share/rubygems/rubygems/commands/install_command.rb:254:in `load_hooks'
/usr/share/rubygems/rubygems/commands/install_command.rb:165:in `execute'
/usr/share/rubygems/rubygems/command.rb:323:in `invoke_with_build_args'
/usr/share/rubygems/rubygems/command_manager.rb:180:in `process_args'
/usr/share/rubygems/rubygems/command_manager.rb:149:in `run'
/usr/share/rubygems/rubygems/gem_runner.rb:53:in `run'
/usr/bin/gem:21:in `<main>'
~~~

So obviously it was the dependency issue.

**Comment by voxik** [comment]
Still thinking how to improve this kind of scenarios. I had almost prepared separate ticket, but I am not really sure how to formulate it. The intent of line line [11](https://github.com/rubygems/rubygems/blob/12aeef6ba9a3be0022be9934c1a3e4c46a03ed3a/lib/rubygems/rdoc.rb#L11) was to protect against missing RDoc, but it should not hide the subsequent dependency issues IMHO.

**Comment by deivid-rodriguez** [comment]
Yeah, I'm not totally sure either. I guess at least logging something would go a long way.
