### ISSUE TITLE
Bundler related issue

### ISSUE THREAD

**Issue by AneliaBlagoeva** [rubygems/rubygems#5314]
### Describe the problem as clearly as you can

```
Errno::EPERM: Operation not permitted @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/bundler.lock
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/process_lock.rb:9:in `initialize'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/process_lock.rb:9:in `open'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/process_lock.rb:9:in `lock'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/installer.rb:71:in `run'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/installer.rb:23:in `install'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/install.rb:62:in `run'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:255:in `block in install'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/settings.rb:131:in `temporary'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:254:in `install'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/ablagoeva/.gem/ruby/2.6.0/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.3.6
  Platforms   ruby, universal-darwin-21
Ruby          2.6.8p205 (2021-07-07 revision 67951) [universal-darwin-21]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.3.5
  Gem Home    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  Gem Path    /Users/ablagoeva/.gem/ruby/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/ablagoeva
  User Path   /Users/ablagoeva/.gem/ruby/2.6.0
  Bin Dir     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.30.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-01-26
Git SHA           056f64c33a
Released Version  true
```

## Bundler settings

```
gemfile
  Set via BUNDLE_GEMFILE: "/Users/ablagoeva/git/com.aw.dpa.project/project-consumer-tests-executor/target/devtools/scripts/Gemfile.rb"
```

### target/devtools/scripts/Gemfile.rb

```ruby
source 'http://rubygems.org'

gem 'nokogiri', '~> 1.12', '>= 1.12.1'
gem 'rexml', '~> 3.2', '>= 3.2.5'
```

### target/devtools/scripts/Gemfile.rb.lock

```
<No /Users/ablagoeva/git/com.aw.dpa.project/project-consumer-tests-executor/target/devtools/scripts/Gemfile.rb.lock found>
```

### Did you try upgrading rubygems & bundler?

gem update --system
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems/rubygems-update-3.3.6

bundle update --bundler
Could not locate Gemfile

### Post steps to reproduce the problem
- upgraded MacOS to Monterey
-before the update everything works fine

### Which command did you run?

mvn clean install

### What were you expecting to happen?

build normally

### What actually happened?

build failed and templated pasted above is shown

**Comment by AneliaBlagoeva** [comment]
Resolution - change to not use pre - installed Ruby version in my projects. Installed another version and using rbenv to change which is global version.  
NB! Do not forget to add this in your zsh file: if [ -d "/usr/local/opt/ruby/bin" ]; then
  export PATH=/usr/local/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi

Open zsh file by command:  open -e ~/.zshrc
