### ISSUE TITLE
mongoid gem error

### ISSUE THREAD

**Issue by JustDinooo** [rubygems/rubygems#5316]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_file_s_symlink - (spec/support/../../.mod/drivers-evergreen-tools/.evergreen/ocsp, C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mongo-2.17.0/spec/support/ocsp)
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:446:in `symlink'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:446:in `block (2 levels) in extract_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:412:in `block in extract_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:524:in `block in open_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:521:in `wrap'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:521:in `open_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:411:in `extract_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:391:in `block (2 levels) in extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:388:in `block in extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `open'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `with_read_io'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:385:in `extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/installer.rb:854:in `extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/source/rubygems.rb:200:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:171:in `install_serially'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:97:in `call'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in `call'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:262:in `install_in_parallel'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:209:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:89:in `block in run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/process_lock.rb:19:in `rescue in lock'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/process_lock.rb:15:in `lock'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:71:in `run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:23:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli/install.rb:60:in `run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:253:in `block in install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/settings.rb:131:in `temporary'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:252:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
  C:/RailsInstaller/Ruby2.3.3/bin/bundle:22:in `load'
  C:/RailsInstaller/Ruby2.3.3/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler       2.2.32
  Platforms   ruby, x64-mingw32
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [x64-mingw32]
  Full Path   C:/Ruby30-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.2.32
  Gem Home    C:/Ruby30-x64/lib/ruby/gems/3.0.0
  Gem Path    C:/Users/Dinooo/.local/share/gem/ruby/3.0.0;C:/Ruby30-x64/lib/ruby/gems/3.0.0
  User Home   C:/Users/Dinooo
  User Path   C:/Users/Dinooo/.local/share/gem/ruby/3.0.0
  Bin Dir     C:/Ruby30-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   C:/Ruby30-x64/ssl/cert.pem
  Cert Dir    C:/Ruby30-x64/ssl/certs
Tools
  Git         2.34.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-01-27
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'
gem 'devise', '~> 4.8', '>= 4.8.1'
gem 'mongoid'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.4.4)
      actionpack (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.4.4)
      actionpack (= 6.1.4.4)
      activejob (= 6.1.4.4)
      activerecord (= 6.1.4.4)
      activestorage (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      mail (>= 2.7.1)
    actionmailer (6.1.4.4)
      actionpack (= 6.1.4.4)
      actionview (= 6.1.4.4)
      activejob (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.4.4)
      actionview (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.4.4)
      actionpack (= 6.1.4.4)
      activerecord (= 6.1.4.4)
      activestorage (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      nokogiri (>= 1.8.5)
    actionview (6.1.4.4)
      activesupport (= 6.1.4.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.4.4)
      activesupport (= 6.1.4.4)
      globalid (>= 0.3.6)
    activemodel (6.1.4.4)
      activesupport (= 6.1.4.4)
    activerecord (6.1.4.4)
      activemodel (= 6.1.4.4)
      activesupport (= 6.1.4.4)
    activestorage (6.1.4.4)
      actionpack (= 6.1.4.4)
      activejob (= 6.1.4.4)
      activerecord (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      marcel (~> 1.0.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.4.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    bcrypt (3.1.16)
    bindex (0.8.1)
    bootsnap (1.10.2)
      msgpack (~> 1.2)
    builder (3.2.4)
    byebug (11.1.3)
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    devise (4.8.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    erubi (1.10.0)
    ffi (1.15.5-x64-mingw32)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.9.0)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.13.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.15.0)
    msgpack (1.4.4)
    nio4r (2.5.8)
    nokogiri (1.13.1-x64-mingw32)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    public_suffix (4.0.6)
    puma (5.6.1)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.3)
    rack-mini-profiler (2.3.3)
      rack (>= 1.2.0)
    rack-proxy (0.7.2)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.1.4.4)
      actioncable (= 6.1.4.4)
      actionmailbox (= 6.1.4.4)
      actionmailer (= 6.1.4.4)
      actionpack (= 6.1.4.4)
      actiontext (= 6.1.4.4)
      actionview (= 6.1.4.4)
      activejob (= 6.1.4.4)
      activemodel (= 6.1.4.4)
      activerecord (= 6.1.4.4)
      activestorage (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      bundler (>= 1.15.0)
      railties (= 6.1.4.4)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (6.1.4.4)
      actionpack (= 6.1.4.4)
      activesupport (= 6.1.4.4)
      method_source
      rake (>= 0.13)
      thor (~> 1.0)
    rake (13.0.6)
    regexp_parser (2.2.0)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rexml (3.2.5)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0-x64-mingw32)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    semantic_range (3.0.0)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    thor (1.2.1)
    tilt (2.0.10)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2021.5)
      tzinfo (>= 1.0.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    webpacker (5.4.3)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.3)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  bcrypt (~> 3.1.7)
  bootsnap (>= 1.4.4)
  byebug
  capybara (>= 3.26)
  devise (~> 4.8, >= 4.8.1)
  jbuilder (~> 2.7)
  puma (~> 5.0)
  rack-mini-profiler (~> 2.0)
  rails (~> 6.1.4, >= 6.1.4.4)
  sass-rails (>= 6)
  selenium-webdriver
  turbolinks (~> 5)
  tzinfo-data
  web-console (>= 4.1.0)
  webdrivers
  webpacker (~> 5.0)

RUBY VERSION
   ruby 3.0.3p157

BUNDLED WITH
   2.2.32
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by adiazm00** [comment]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_file_s_symlink - (spec/support/../../.mod/drivers-evergreen-tools/.evergreen/ocsp, C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mongo-2.17.0/spec/support/ocsp)
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:446:in `symlink'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:446:in `block (2 levels) in extract_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:412:in `block in extract_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:524:in `block in open_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:521:in `wrap'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:521:in `open_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:411:in `extract_tar_gz'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:391:in `block (2 levels) in extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:388:in `block in extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `open'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `with_read_io'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/package.rb:385:in `extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/installer.rb:854:in `extract_files'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/source/rubygems.rb:200:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:171:in `install_serially'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:97:in `call'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in `call'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:262:in `install_in_parallel'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:209:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:89:in `block in run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/process_lock.rb:19:in `rescue in lock'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/process_lock.rb:15:in `lock'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:71:in `run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:23:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli/install.rb:60:in `run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:253:in `block in install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/settings.rb:131:in `temporary'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:252:in `install'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
  C:/Ruby30-x64/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
  C:/Ruby30-x64/bin/bundle.cmd:31:in `load'
  C:/Ruby30-x64/bin/bundle.cmd:31:in `<main>'
```

## Environment

```
Bundler       2.2.32
  Platforms   ruby, x64-mingw32
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [x64-mingw32]
  Full Path   C:/Ruby30-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.2.32
  Gem Home    C:/Ruby30-x64/lib/ruby/gems/3.0.0
  Gem Path    C:/Users/adiaz/.local/share/gem/ruby/3.0.0;C:/Ruby30-x64/lib/ruby/gems/3.0.0
  User Home   C:/Users/adiaz
  User Path   C:/Users/adiaz/.local/share/gem/ruby/3.0.0
  Bin Dir     C:/Ruby30-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   C:/Ruby30-x64/ssl/cert.pem
  Cert Dir    C:/Ruby30-x64/ssl/certs
Tools
  Git         2.39.0.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-03-16
Git SHA           unknown
Released Version  false
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

gem "mongoid"

gem 'bcrypt', '~> 3.1', '>= 3.1.11'
# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.3"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.2.3)
      actionpack (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.2.3)
      actionpack (= 7.0.2.3)
      activejob (= 7.0.2.3)
      activerecord (= 7.0.2.3)
      activestorage (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.2.3)
      actionpack (= 7.0.2.3)
      actionview (= 7.0.2.3)
      activejob (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.2.3)
      actionview (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.2.3)
      actionpack (= 7.0.2.3)
      activerecord (= 7.0.2.3)
      activestorage (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.2.3)
      activesupport (= 7.0.2.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.2.3)
      activesupport (= 7.0.2.3)
      globalid (>= 0.3.6)
    activemodel (7.0.2.3)
      activesupport (= 7.0.2.3)
    activerecord (7.0.2.3)
      activemodel (= 7.0.2.3)
      activesupport (= 7.0.2.3)
    activestorage (7.0.2.3)
      actionpack (= 7.0.2.3)
      activejob (= 7.0.2.3)
      activerecord (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.2.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    bcrypt (3.1.17)
    bindex (0.8.1)
    bootsnap (1.11.1)
      msgpack (~> 1.2)
    bson (4.14.1)
    builder (3.2.4)
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    debug (1.4.0)
      irb (>= 1.3.6)
      reline (>= 0.2.7)
    digest (3.1.0)
    erubi (1.10.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.0.3)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.5.11)
    io-wait (0.2.1)
    irb (1.4.1)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.14.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.15.0)
    mongo (2.17.0)
      bson (>= 4.8.2, < 5.0.0)
    mongoid (7.3.4)
      activemodel (>= 5.1, < 7.1, != 7.0.0)
      mongo (>= 2.10.5, < 3.0.0)
      ruby2_keywords (~> 0.0.5)
    msgpack (1.4.5)
    net-imap (0.2.3)
      digest
      net-protocol
      strscan
    net-pop (0.1.1)
      digest
      net-protocol
      timeout
    net-protocol (0.1.2)
      io-wait
      timeout
    net-smtp (0.3.1)
      digest
      net-protocol
      timeout
    nio4r (2.5.8)
    nokogiri (1.13.3-x64-mingw32)
      racc (~> 1.4)
    public_suffix (4.0.6)
    puma (5.6.2)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.3)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (7.0.2.3)
      actioncable (= 7.0.2.3)
      actionmailbox (= 7.0.2.3)
      actionmailer (= 7.0.2.3)
      actionpack (= 7.0.2.3)
      actiontext (= 7.0.2.3)
      actionview (= 7.0.2.3)
      activejob (= 7.0.2.3)
      activemodel (= 7.0.2.3)
      activerecord (= 7.0.2.3)
      activestorage (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      bundler (>= 1.15.0)
      railties (= 7.0.2.3)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (7.0.2.3)
      actionpack (= 7.0.2.3)
      activesupport (= 7.0.2.3)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    regexp_parser (2.2.1)
    reline (0.3.1)
      io-console (~> 0.5)
    rexml (3.2.5)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    sprockets (4.0.3)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    stimulus-rails (1.0.4)
      railties (>= 6.0.0)
    strscan (3.0.1)
    thor (1.2.1)
    timeout (0.2.0)
    turbo-rails (1.0.1)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2021.5)
      tzinfo (>= 1.0.0)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.4)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  bcrypt (~> 3.1, >= 3.1.11)
  bootsnap
  capybara
  debug
  importmap-rails
  jbuilder
  mongoid
  puma (~> 5.0)
  rails (~> 7.0.2, >= 7.0.2.3)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 3.0.3p157

BUNDLED WITH
   2.2.32
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by MSP-Greg** [comment]
Some gems install symlinks (`Errno::EACCES: Permission denied @ rb_file_s_symlink`)

Your system will not allow Ruby to do so.  An option would be to run as an admin for the bundle install step.   Also, most servers will allow symlink creation, so code that runs in 'the cloud' may not run locally.
