### ISSUE TITLE
Flaky test failure in `bundle check` specs against old RubyGems

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#5332]
### Describe the problem as clearly as you can

I thought we had race conditions inside bundler specs completely sorted out, but another one came up: https://github.com/rubygems/rubygems/runs/5039978113?check_suite_focus=true.

```
  1) [TEST_ENV_NUMBER=2] bundle check fails when there's no lock file and frozen is set
/home/runner/work/rubygems/rubygems/bundler/spec/support/rubygems_ext.rb:97:in `gem_load_and_activate'
/home/runner/work/rubygems/rubygems/bundler/spec/support/rubygems_ext.rb:18:in `gem_load'
Tasks: TOP => spec:all => spec:regular
(See full trace by running task with --trace)
     Failure/Error:
               raise <<~ERROR
       
                 Invoking `#{cmd}` failed with output:
                 ----------------------------------------------------------------------
                 #{command_execution.stdboth}
                 ----------------------------------------------------------------------
               ERROR

     RuntimeError:


       Commands:
       $ /opt/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby -I/home/runner/work/rubygems/rubygems/bundler/spec -r/home/runner/work/rubygems/rubygems/bundler/spec/support/artifice/fail.rb -r/home/runner/work/rubygems/rubygems/bundler/spec/support/hax.rb /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/bin/bundle install
       Fetching source index from file:///home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/remote1/
       Resolving dependencies...
       Fetching foo 1.0
       Installing foo 1.0
       Bundle complete! 1 Gemfile dependency, 2 gems now installed.
       Bundled gems are installed into `./.bundle`
       # $? => 0

       $ /opt/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby -I/home/runner/work/rubygems/rubygems/bundler/spec -r/home/runner/work/rubygems/rubygems/bundler/spec/support/artifice/fail.rb -r/home/runner/work/rubygems/rubygems/bundler/spec/support/hax.rb /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/bin/bundle config set --local deployment true
       # $? => 0

       Invoking `/opt/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby -I/home/runner/work/rubygems/rubygems/bundler/spec -r/home/runner/work/rubygems/rubygems/bundler/spec/support/artifice/fail.rb -r/home/runner/work/rubygems/rubygems/bundler/spec/support/hax.rb /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/bin/bundle install` failed with output:
       ----------------------------------------------------------------------
       [/opt/hostedtoolcache/Ruby/2.7.5/x64/lib/ruby/gems/2.7.0/specifications/default/json-2.3.0.gemspec] isn't a Gem::Specification (NilClass instead).
       --- ERROR REPORT TEMPLATE -------------------------------------------------------

       ```
       NoMethodError: undefined method `platform' for nil:NilClass
         /home/runner/work/rubygems/rubygems/bundler/tmp/rubygems/lib/rubygems/specification.rb:1094:in `block in _latest_specs'
         /home/runner/work/rubygems/rubygems/bundler/tmp/rubygems/lib/rubygems/specification.rb:1091:in `reverse_each'
         /home/runner/work/rubygems/rubygems/bundler/tmp/rubygems/lib/rubygems/specification.rb:1091:in `_latest_specs'
         /home/runner/work/rubygems/rubygems/bundler/tmp/rubygems/lib/rubygems/specification.rb:1084:in `latest_specs'
         /home/runner/work/rubygems/rubygems/bundler/tmp/rubygems/lib/rubygems.rb:540:in `find_latest_files'
         /home/runner/work/rubygems/rubygems/bundler/tmp/rubygems/lib/rubygems.rb:1133:in `load_plugins'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/rubygems_integration.rb:187:in `load_plugins'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/installer.rb:225:in `load_plugins'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/installer.rb:84:in `block in run'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/process_lock.rb:12:in `block in lock'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/process_lock.rb:9:in `open'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/process_lock.rb:9:in `lock'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/installer.rb:71:in `run'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/installer.rb:23:in `install'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/cli/install.rb:62:in `run'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/cli.rb:255:in `block in install'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/settings.rb:131:in `temporary'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/cli.rb:254:in `install'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/cli.rb:31:in `dispatch'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/cli.rb:25:in `start'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/exe/bundle:48:in `block in <top (required)>'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/gems/bundler-3.0.0/exe/bundle:36:in `<top (required)>'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/bin/bundle:23:in `load'
         /home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/system/bin/bundle:23:in `<main>'
       ```

       ## Environment

       ```
       Bundler       3.0.0
         Platforms   ruby, x86_64-linux
       Ruby          2.7.5p203 (2021-11-24 revision f69aeb83146be640995753667fdd6c6f157527f5) [x86_64-linux]
         Full Path   /opt/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby
         Config Dir  /opt/hostedtoolcache/Ruby/2.7.5/x64/etc
       RubyGems      3.1.5
         Gem Home    /home/runner/work/rubygems/rubygems/bundler/tmp/2/bundled_app/vendor/bundle/ruby/2.7.0
         Gem Path    /home/runner/work/rubygems/rubygems/bundler/tmp/2/bundled_app/vendor/bundle/ruby/2.7.0
         User Home   /home/runner/work/rubygems/rubygems/bundler/tmp/2/home
         User Path   /home/runner/work/rubygems/rubygems/bundler/tmp/2/home/.gem/ruby/2.7.0
         Bin Dir     /home/runner/work/rubygems/rubygems/bundler/tmp/2/bundled_app/vendor/bundle/ruby/2.7.0/bin
       OpenSSL       
         Compiled    OpenSSL 1.1.1f  31 Mar 2020
         Loaded      OpenSSL 1.1.1f  31 Mar 2020
         Cert File   /usr/lib/ssl/cert.pem
         Cert Dir    /usr/lib/ssl/certs
       Tools         
         Git         2.34.1
         RVM         not installed
         rbenv       not installed
         chruby      not installed
       ```

       ## Bundler Build Metadata

       ```
       Built At          2022-02-02
       Git SHA           80dce3d
       Released Version  true
       ```

       ## Bundler settings

       ```
       deployment
         Set for your local app (/home/runner/work/rubygems/rubygems/bundler/tmp/2/bundled_app/.bundle/config): true
       ```

       ## Gemfile

       ### Gemfile

       ```ruby
       source "file:///home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/remote1"
       gem "foo"
       ```

       ### Gemfile.lock

       ```
       GEM
         remote: file:///home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/remote1/
         specs:
           foo (1.0)

       PLATFORMS
         x86_64-linux

       DEPENDENCIES
         foo

       BUNDLED WITH
          3.0.0
       ```

       --- TEMPLATE END ----------------------------------------------------------------

       Unfortunately, an unexpected error occurred, and Bundler cannot continue.

       First, try this link to see if there are any existing issue reports for this error:
       https://github.com/rubygems/rubygems/search?q=undefined+method+%60platform%27+for+nil+NilClass&type=Issues

       If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
       Fetching source index from file:///home/runner/work/rubygems/rubygems/bundler/tmp/2/gems/remote1/
       ----------------------------------------------------------------------
     # ./spec/support/helpers.rb:207:in `sys_exec'
     # ./spec/support/helpers.rb:124:in `bundle'
     # ./spec/commands/check_spec.rb:237:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:101:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:101:in `block (3 levels) in <top (required)>'
     # ./spec/support/helpers.rb:352:in `block in with_gem_path_as'
     # ./spec/support/helpers.rb:366:in `without_env_side_effects'
     # ./spec/support/helpers.rb:347:in `with_gem_path_as'
     # ./spec/spec_helper.rb:100:in `block (2 levels) in <top (required)>'
     # ./spec/support/rubygems_ext.rb:97:in `load'
     # ./spec/support/rubygems_ext.rb:97:in `gem_load_and_activate'
     # ./spec/support/rubygems_ext.rb:18:in `gem_load'

Finished in 18 minutes 15 seconds (files took 0 seconds to load)
3028 examples, 1 failure, 50 pending

Failed examples:

rspec ./spec/commands/check_spec.rb:230 # [TEST_ENV_NUMBER=2] bundle check fails when there's no lock file and frozen is set
```

### Did you try upgrading rubygems & bundler?

So far only seen in "Bundler 3 mode",with old RubyGems (3.1) and old Ruby (2.7). So it could be something fixed in newer versions.

### Post steps to reproduce the problem

Not reproducible at the moment.

**Comment by deivid-rodriguez** [comment]
Never seen again, will close for now.
