### ISSUE TITLE
gem source -a fails when username contains an '@'

### ISSUE THREAD

**Issue by arc113** [rubygems/rubygems#5360]
I'm having a problem.

My current problem is that `gem source -a https://username:password@site.com` doesn't work when the username contains an @ symbol. The error is 

ERROR:  While executing gem ... (URI::InvalidURIError)
    bad URI(is not URI?):

I'm reporting this because a lot of websites like Jfrog can have emails as the username.

This issue is related to:

  - [y ] Installing a library

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [universal.x86_64-darwin20]
  - INSTALLATION DIRECTORY: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/iarc13/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin
  - SPEC CACHE DIRECTORY: /Users/iarc13/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
     - ruby
     - universal-darwin-20
  - GEM PATHS:
     - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
     - /Users/iarc13/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /var/folders/tx/43y4px7n1h39thh0vks2xlp00000gq/T/fnm_multishells/2965_1644999031151/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

This one seems to be working - it's trying to connect.
![image](https://user-images.githubusercontent.com/18068209/154344048-9c2dd53c-907a-425c-be3c-2b1d8b2b7675.png)

This one doesn't - it just rejects the url.
![image](https://user-images.githubusercontent.com/18068209/154344072-06e607b2-b626-4860-a160-ae7c0e634c27.png)

**Comment by deivid-rodriguez** [comment]
This seems like a `URI` issue?

```
$ ruby -ruri -e 'URI.parse("https://u:p@example.com")' # works
$ ruby -ruri -e 'URI.parse("https://u@u.com:p@example.com")' # raises  
/Users/deivid/.rbenv/versions/3.1.0/lib/ruby/3.1.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://u@u.com:p@example.com" (URI::InvalidURIError)
	from /Users/deivid/.rbenv/versions/3.1.0/lib/ruby/3.1.0/uri/rfc3986_parser.rb:72:in `parse'
	from /Users/deivid/.rbenv/versions/3.1.0/lib/ruby/3.1.0/uri/common.rb:188:in `parse'
	from -e:1:in `<main>'
```

The addressable gem handles it just fine though

```
$ ruby -raddressable -e 'Addressable::URI.parse("https://u:p@example.com")' # works
$ ruby -raddressable -e 'Addressable::URI.parse("https://u@u.com:p@example.com")' # also works
```

Can you report this at https://github.com/ruby/uri?

**Comment by deivid-rodriguez** [comment]
I created an issue at the `uri` repo: https://github.com/ruby/uri/issues/42.

**Comment by duerst** [comment]
What about using  ruby `-ruri -e 'URI.parse("https://u%40u.com:p@example.com")'` ?

**Comment by deivid-rodriguez** [comment]
By the way, I [fixed two uri redaction bugs](https://github.com/rubygems/rubygems/pull/5623) that I saw in the screenshots you posted :)

**Comment by arc113** [comment]
Thanks! Good to know. @deivid-rodriguez
