### ISSUE TITLE
Cannot Load net/smtp

### ISSUE THREAD

**Issue by daBee** [rubygems/rubygems#5367]
### Describe the problem as clearly as you can

I am getting an error on `Bundler.require` which loads some mail `gems` that need `net/smtp`.  Because that is part of the core `ruby`, I've assumed this is a `Bundler` load issue and not a `gem` issue.  

```
/Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `require': cannot load such file -- net/smtp (LoadError)
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail.rb:3:in `<top (required)>'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/pony-1.13.1/lib/pony.rb:1:in `require'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/pony-1.13.1/lib/pony.rb:1:in `<top (required)>'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `require'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `each'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `each'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `require'
	from /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler.rb:176:in `require'
	from grocery_booze.rb:8:in `<main>'
```

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

Using `rbenv` `ruby 3.1.0`.  See the `env` report.  I have a `ruby` script that simply uses `Bundle.require`.  

### Which command did you run?

    Bundle.require

### What were you expecting to happen?

`Bundler` should load the gem and proceed with the script.

### What actually happened?

`Bundler` did not get past loading that core `gem`.  

## Environment

```
Bundler       2.3.7
  Platforms   ruby, arm64-darwin-21
Ruby          3.1.0p0 (2021-12-25 revision fb4df44d1670e9d25aef6b235a7281199a177edb) [arm64-darwin-21]
  Full Path   /Users/rich/.rbenv/versions/3.1.0/bin/ruby
  Config Dir  /Users/rich/.rbenv/versions/3.1.0/etc
RubyGems      3.3.3
  Gem Home    /Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0
  Gem Path    /Users/rich/.gem/ruby/3.1.0:/Users/rich/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0
  User Home   /Users/rich
  User Path   /Users/rich/.gem/ruby/3.1.0
  Bin Dir     /Users/rich/.rbenv/versions/3.1.0/bin
Tools
  Git         2.35.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-02-09
Git SHA           bafe43c593
Released Version  true
```

## Bundler settings

```
build.nokogiri
  Set for the current user (/Users/rich/.bundle/config): "--use-system-libraries"
```

### Gemfile

```ruby
# ~/Gemfile

source 'https://rubygems.org'

gem 'pg'
gem 'filewatcher'
gem 'clipboard'
gem 'json'
gem 'amazing_print'
gem 'square.rb'
gem 'launchy'
gem 'httparty'
gem 'smarter_csv'
gem 'pony'
gem 'growl'
gem 'roo'
gem 'bcrypt'
gem 'uuidtools'
gem 'nokogiri'
gem 'mechanize'
gem 'airrecord'
gem 'rubyzip'
gem "kimurai", "~> 1.4"
gem "terminal-notifier", "~> 2.0"
gem "sequel", "~> 5.40"
gem "openssl", "~> 2.2.0"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.0.2.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    airrecord (1.0.7)
      faraday (>= 0.10, < 2.0)
      net-http-persistent
    amazing_print (1.4.0)
    bcrypt (3.1.16)
    capybara (2.18.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (>= 2.0, < 4.0)
    capybara-mechanize (1.0.1)
      capybara (~> 2.0, >= 2.0.1)
      mechanize (~> 2.5)
    certifi (2018.01.18)
    childprocess (4.1.0)
    chronic (0.10.2)
    clipboard (1.3.6)
    cliver (0.3.2)
    coderay (1.1.3)
    concurrent-ruby (1.1.9)
    connection_pool (2.2.5)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    faraday (1.10.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-http-cache (2.2.0)
      faraday (>= 0.8)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.3)
      multipart-post (>= 1.2, < 3)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    filewatcher (1.1.1)
      optimist (~> 3.0)
    growl (1.0.3)
    headless (2.3.1)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    ipaddr (1.2.4)
    json (2.6.1)
    kimurai (1.4.0)
      activesupport
      capybara (>= 2.15, < 4.0)
      capybara-mechanize
      cliver
      headless
      murmurhash3
      nokogiri
      pmap
      poltergeist
      pry
      rbcat (~> 0.2)
      selenium-webdriver
      thor
      whenever
    launchy (2.5.0)
      addressable (~> 2.7)
    little-plugger (1.1.4)
    logging (2.3.0)
      little-plugger (~> 1.1)
      multi_json (~> 1.14)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    mechanize (2.8.4)
      addressable (~> 2.8)
      domain_name (~> 0.5, >= 0.5.20190701)
      http-cookie (~> 1.0, >= 1.0.3)
      mime-types (~> 3.0)
      net-http-digest_auth (~> 1.4, >= 1.4.1)
      net-http-persistent (>= 2.5.2, < 5.0.dev)
      nokogiri (~> 1.11, >= 1.11.2)
      rubyntlm (~> 0.6, >= 0.6.3)
      webrick (~> 1.7)
      webrobots (~> 0.1.2)
    method_source (1.0.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    mini_mime (1.1.2)
    minitest (5.15.0)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    murmurhash3 (0.1.6)
    net-http-digest_auth (1.4.1)
    net-http-persistent (4.0.1)
      connection_pool (~> 2.2)
    nokogiri (1.13.1-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.1-x86_64-darwin)
      racc (~> 1.4)
    openssl (2.2.1)
      ipaddr
    optimist (3.0.1)
    pg (1.3.2)
    pmap (1.1.1)
    poltergeist (1.18.1)
      capybara (>= 2.1, < 4)
      cliver (~> 0.3.1)
      websocket-driver (>= 0.2.0)
    pony (1.13.1)
      mail (>= 2.0)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    public_suffix (4.0.6)
    racc (1.6.0)
    rack (2.2.3)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rbcat (0.2.1)
    rexml (3.2.5)
    roo (2.8.3)
      nokogiri (~> 1)
      rubyzip (>= 1.3.0, < 3.0.0)
    ruby2_keywords (0.0.5)
    rubyntlm (0.6.3)
    rubyzip (2.3.2)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    sequel (5.53.0)
    smarter_csv (1.4.2)
    square.rb (18.0.0.20220216)
      certifi (~> 2018.1, >= 2018.01.18)
      faraday (~> 1.0, >= 1.0.1)
      faraday-http-cache (~> 2.2)
      faraday_middleware (~> 1.0)
      logging (~> 2.3)
    terminal-notifier (2.0.0)
    thor (1.2.1)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8)
    uuidtools (2.2.0)
    webrick (1.7.0)
    webrobots (0.1.2)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    whenever (1.0.0)
      chronic (>= 0.6.3)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  arm64-darwin-21
  x86_64-darwin-15

DEPENDENCIES
  airrecord
  amazing_print
  bcrypt
  clipboard
  filewatcher
  growl
  httparty
  json
  kimurai (~> 1.4)
  launchy
  mechanize
  nokogiri
  openssl (~> 2.2.0)
  pg
  pony
  roo
  rubyzip
  sequel (~> 5.40)
  smarter_csv
  square.rb
  terminal-notifier (~> 2.0)
  uuidtools

BUNDLED WITH
   2.3.7
```

**Comment by hsbt** [comment]
You need to add `net-smtp` into your Gemfile explicitly. see https://github.com/mikel/mail/pull/1439
