### ISSUE TITLE
Permission errors when running `bundle install`

### ISSUE THREAD

**Issue by eureka7000** [rubygems/rubygems#5384]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Feureka7000%2F.rbenv%2Fversions%2F2.7.0%2Flib%2Fruby%2Fgems%2F2.7.0%2Fextensions%2Fx86_64-darwin-21%2F2.7.0%2Fracc-1.6.0&type=Issues

**Comment by eureka7000** [comment]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-21/2.7.0/racc-1.6.0
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fileutils.rb:211:in `each'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/ext/builder.rb:220:in `write_gem_make_out'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/ext/builder.rb:137:in `build_error'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/ext/builder.rb:183:in `rescue in build_extension'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/ext/builder.rb:160:in `build_extension'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/ext/builder.rb:208:in `block in build_extensions'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/ext/builder.rb:205:in `each'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/ext/builder.rb:205:in `build_extensions'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer/parallel_installer.rb:171:in `install_serially'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer/parallel_installer.rb:97:in `call'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer.rb:259:in `install_in_parallel'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer.rb:209:in `install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer.rb:89:in `block in run'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/process_lock.rb:15:in `lock'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer.rb:71:in `run'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/installer.rb:23:in `install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/cli/install.rb:62:in `run'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/cli.rb:255:in `block in install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/settings.rb:131:in `temporary'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/cli.rb:254:in `install'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
  /Users/eureka7000/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
  /Users/eureka7000/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.3.3
  Platforms   ruby, x86_64-darwin-21
Ruby          2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-darwin21]
  Full Path   /Users/eureka7000/.rbenv/versions/2.7.0/bin/ruby
  Config Dir  /Users/eureka7000/.rbenv/versions/2.7.0/etc
RubyGems      3.1.2
  Gem Home    /Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0
  Gem Path    /Users/eureka7000/.gem/ruby/2.7.0:/Users/eureka7000/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0
  User Home   /Users/eureka7000
  User Path   /Users/eureka7000/.gem/ruby/2.7.0
  Bin Dir     /Users/eureka7000/.rbenv/versions/2.7.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   /Users/eureka7000/.rbenv/versions/2.7.0/openssl/ssl/cert.pem
  Cert Dir    /Users/eureka7000/.rbenv/versions/2.7.0/openssl/ssl/certs
Tools         
  Git         2.35.1
  RVM         1.25.8 (stable)
  rbenv       rbenv 1.2.0
  chruby      To install do: 'rvm install ruby-2.7.0'

```

## Bundler Build Metadata

```
Built At          2021-12-24
Git SHA           688b71febc
Released Version  true
```

## Bundler settings

```
build.nokogiri
  Set for the current user (/Users/eureka7000/.bundle/config): "--use-system-libraries --with-xml2-include=/usr/local/opt/libxml2/include/libxml2"
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

#ruby "3.1.0"
ruby "2.7.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

gem "passenger"

# Use the Puma web server [https://github.com/puma/puma]
#gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "timeout"
gem 'strscan', '1.0.3'

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

gem 'capistrano', '~> 3.11'
gem 'capistrano-rails', '~> 1.4'
gem 'capistrano-passenger', '~> 0.2.0'
gem 'capistrano-rbenv', '~> 2.1', '>= 2.1.4'

gem 'ed25519', '>=1.2', '<2.0'
gem 'bcrypt_pbkdf', '>=1.0', '<2.0'

# gem 'pg'
gem "pg", "~> 1.1"
gem 'activerecord-postgresql-adapter', '~> 0.0.1'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  gem 'capistrano-ssh-doctor', '~> 1.0'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.2.2)
      actionpack (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.2.2)
      actionpack (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activestorage (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.2.2)
      actionpack (= 7.0.2.2)
      actionview (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.2.2)
      actionview (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.2.2)
      actionpack (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activestorage (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.2.2)
      activesupport (= 7.0.2.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.2.2)
      activesupport (= 7.0.2.2)
      globalid (>= 0.3.6)
    activemodel (7.0.2.2)
      activesupport (= 7.0.2.2)
    activerecord (7.0.2.2)
      activemodel (= 7.0.2.2)
      activesupport (= 7.0.2.2)
    activerecord-postgresql-adapter (0.0.1)
      pg
    activestorage (7.0.2.2)
      actionpack (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.2.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    airbrussh (1.4.0)
      sshkit (>= 1.6.1, != 1.7.0)
    bcrypt_pbkdf (1.1.0)
    bcrypt_pbkdf (1.1.0-x64-mingw32)
    bcrypt_pbkdf (1.1.0-x86-mingw32)
    bindex (0.8.1)
    bootsnap (1.10.3)
      msgpack (~> 1.2)
    builder (3.2.4)
    capistrano (3.16.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.0.1)
      capistrano (~> 3.1)
    capistrano-passenger (0.2.1)
      capistrano (~> 3.0)
    capistrano-rails (1.6.2)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rbenv (2.2.0)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    capistrano-ssh-doctor (1.0.0)
      capistrano (>= 3.1)
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    debug (1.4.0)
      irb (>= 1.3.6)
      reline (>= 0.2.7)
    digest (3.1.0)
    digest (3.1.0-java)
    ed25519 (1.3.0)
    ed25519 (1.3.0-java)
    erubi (1.10.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.0.3)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.5.11)
    io-wait (0.2.1)
    irb (1.4.1)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.14.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    mini_portile2 (2.8.0)
    minitest (5.15.0)
    msgpack (1.4.5)
    msgpack (1.4.5-java)
    net-imap (0.2.3)
      digest
      net-protocol
      strscan
    net-pop (0.1.1)
      digest
      net-protocol
      timeout
    net-protocol (0.1.2)
      io-wait
      timeout
    net-scp (3.0.0)
      net-ssh (>= 2.6.5, < 7.0.0)
    net-smtp (0.3.1)
      digest
      net-protocol
      timeout
    net-ssh (6.1.0)
    nio4r (2.5.8)
    nio4r (2.5.8-java)
    nokogiri (1.13.3)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.3-java)
      racc (~> 1.4)
    nokogiri (1.13.3-x64-mingw32)
      racc (~> 1.4)
    nokogiri (1.13.3-x86-mingw32)
      racc (~> 1.4)
    nokogiri (1.13.3-x86_64-darwin)
      racc (~> 1.4)
    passenger (6.0.12)
      rack
      rake (>= 0.8.1)
    pg (1.3.3)
    pg (1.3.3-x64-mingw32)
    pg (1.3.3-x86-mingw32)
    public_suffix (4.0.6)
    racc (1.6.0)
    racc (1.6.0-java)
    rack (2.2.3)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (7.0.2.2)
      actioncable (= 7.0.2.2)
      actionmailbox (= 7.0.2.2)
      actionmailer (= 7.0.2.2)
      actionpack (= 7.0.2.2)
      actiontext (= 7.0.2.2)
      actionview (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activemodel (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activestorage (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      bundler (>= 1.15.0)
      railties (= 7.0.2.2)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (7.0.2.2)
      actionpack (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    regexp_parser (2.2.1)
    reline (0.3.1)
      io-console (~> 0.5)
    rexml (3.2.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    sprockets (4.0.3)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    sshkit (1.21.2)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    stimulus-rails (1.0.4)
      railties (>= 6.0.0)
    strscan (1.0.3)
    thor (1.2.1)
    timeout (0.2.0)
    turbo-rails (1.0.1)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2021.5)
      tzinfo (>= 1.0.0)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-driver (0.7.5-java)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.4)

PLATFORMS
  java
  ruby
  x64-mingw32
  x86-mingw32
  x86-mswin32
  x86_64-darwin-21

DEPENDENCIES
  activerecord-postgresql-adapter (~> 0.0.1)
  bcrypt_pbkdf (>= 1.0, < 2.0)
  bootsnap
  capistrano (~> 3.11)
  capistrano-passenger (~> 0.2.0)
  capistrano-rails (~> 1.4)
  capistrano-rbenv (~> 2.1, >= 2.1.4)
  capistrano-ssh-doctor (~> 1.0)
  capybara
  debug
  ed25519 (>= 1.2, < 2.0)
  importmap-rails
  jbuilder
  passenger
  pg (~> 1.1)
  rails (~> 7.0.2, >= 7.0.2.2)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  strscan (= 1.0.3)
  timeout
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 2.7.0p0

BUNDLED WITH
   2.3.3
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Feureka7000%2F.rbenv%2Fversions%2F2.7.0%2Flib%2Fruby%2Fgems%2F2.7.0%2Fextensions%2Fx86_64-darwin-21%2F2.7.0%2Fracc-1.6.0&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
