### ISSUE TITLE
Error was thrown when I ran `rails new new-app`

### ISSUE THREAD

**Issue by smaranh** [rubygems/rubygems#5395]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/extensions/arm64-darwin-21/3.0.0/io-wait-0.2.1
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:211:in `each'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:205:in `write_gem_make_out'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:133:in `build_error'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:167:in `rescue in build_extension'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:156:in `build_extension'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/installer.rb:845:in `build_extensions'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/source/rubygems.rb:200:in `install'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.32
  Platforms   ruby, arm64-darwin-21
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [arm64-darwin21]
  Full Path   /Users/m1jedi/.rbenv/versions/3.0.3/bin/ruby
  Config Dir  /Users/m1jedi/.rbenv/versions/3.0.3/etc
RubyGems      3.2.32
  Gem Home    /Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0
  Gem Path    /Users/m1jedi/.local/share/gem/ruby/3.0.0:/Users/m1jedi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0
  User Home   /Users/m1jedi
  User Path   /Users/m1jedi/.local/share/gem/ruby/3.0.0
  Bin Dir     /Users/m1jedi/.rbenv/versions/3.0.3/bin
OpenSSL
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   /Users/m1jedi/.rbenv/versions/3.0.3/openssl/ssl/cert.pem
  Cert Dir    /Users/m1jedi/.rbenv/versions/3.0.3/openssl/ssl/certs
Tools
  Git         2.32.0 (Apple Git-132)
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-03-12
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
ignore_messages
  Set via BUNDLE_IGNORE_MESSAGES: true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.3"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
<No /Users/m1jedi/DEV/ruby/foodlog/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by smaranh** [comment]
Maybe this issue is resolved in the latest ruby version 3.1.1. I didn't have to run `sudo gem install rails`, which I had to with ruby version 3.0.3. With version 3.1.1 I can run `gem install rails`.
