### ISSUE TITLE
EROR permission denied

### ISSUE THREAD

**Issue by Akel135** [rubygems/rubygems#5403]
```
Errno::EACCES: Permission denied @ rb_file_s_symlink - (spec/support/../../.mod/drivers-evergreen-tools/.evergreen/ocsp, C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mongo-2.17.0/spec/support/ocsp)
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:445:in `symlink'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:445:in `block (2 levels) in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/tar_reader.rb:67:in `each'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:421:in `block in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:550:in `block in open_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:547:in `wrap'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:547:in `open_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:420:in `extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:400:in `block (2 levels) in extract_files'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/tar_reader.rb:67:in `each'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:397:in `block in extract_files'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/file_source.rb:30:in `open'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/file_source.rb:30:in `with_read_io'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:394:in `extract_files'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/installer.rb:865:in `extract_files'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/source/rubygems.rb:204:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.9/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.3.9
  Platforms   ruby, x64-mingw32
Ruby          2.7.5p203 (2021-11-24 revision f69aeb83146be640995753667fdd6c6f157527f5) [x64-mingw32]
  Full Path   C:/Ruby27-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.1.6
  Gem Home    C:/Ruby27-x64/lib/ruby/gems/2.7.0
  Gem Path    C:/Users/aakel/.gem/ruby/2.7.0;C:/Ruby27-x64/lib/ruby/gems/2.7.0
  User Home   C:/Users/aakel
  User Path   C:/Users/aakel/.gem/ruby/2.7.0
  Bin Dir     C:/Ruby27-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   C:/Ruby27-x64/ssl/cert.pem
  Cert Dir    C:/Ruby27-x64/ssl/certs
Tools
  Git         2.33.0.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-03-09
Git SHA           7f90c0083a
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'capybara'
gem "selenium-webdriver", '3.142.7'
gem 'cucumber', '3.1.2'
gem 'rspec'
gem 'sinatra'
gem 'rest-client'
gem 'json'
gem 'rake', '~> 13.0.3  '
gem 'byebug'
gem 'parallel', '1.12.1'
gem 'capybara-screenshot'
gem 'multipart-post'
gem 'os'
gem 'mongo'
gem 'parallel_tests', '2.19.0'
gem 'regex'
gem 'multipart_body'
gem 'certified'
gem 'mailinator'
gem 'rubysl-securerandom'
gem 'spreadsheet'
gem 'sendgrid-ruby'
gem 'unicode_utils'
gem 'report_builder'
gem 'eyes_capybara'
gem 'rubyXL'
gem 'faker'
gem 'sauce_whisk', '0.0.22'
gem 'rubyzip'
gem 'down'
# gem 'appium_lib'
# gem 'appium_capybara'
```

### Gemfile.lock

```
<No C:/ds1-ui-tests/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
I think the RubyGems upgrade should fix this, so I'll close this. If you upgrade and still have issues, please reopen!
