### ISSUE TITLE
Unable to marshal gemspecs with YAML

### ISSUE THREAD

**Issue by jessebs** [rubygems/rubygems#5405]
### Describe the problem as clearly as you can

This is a doozy and I'm not exactly sure what caused this to pop up - it could be bundler 2.3.9 or there could have been a change on our build stack that brought this to light.

When dependency resolution is done through a full index (downloading gemspec.rz files), there is a condition within the published gemspecs that prevents parsing and prevents bundler from resolving dependencies. 

### Did you try upgrading rubygems & bundler?

Yes - both are the latest

### Post steps to reproduce the problem

Create a gemfile
```
source 'https://rubygems.org'
gem 'pry', '= 0.4.7'
```

Then run:
`bundle install --full-index --verbose`

You'll see the error.  It works without full-index

The problem comes down to line containing: `Bundler.load_marshal Bundler.rubygems.inflate(downloader.fetch(uri).body)` in lib/bundler/fetcher.rb

It looks like a very simple resolution is to `require 'yaml'` in the fetcher.rb file

### Which command did you run?

`bundle install --full-index --verbose`

### What were you expecting to happen?

The gem is installed

### What actually happened?

```
Running `bundle install --full-index --verbose` with bundler 2.3.9
Found no changes, using resolution from the lockfile
The definition is missing ["pry-0.4.7"]
HTTP GET https://index.rubygems.org/versions
HTTP 304 Not Modified https://index.rubygems.org/versions
Fetching source index from https://rubygems.org/
Need to query more than 500 gems. Downloading full index instead...
HTTP GET https://rubygems.org/quick/Marshal.4.8/pry-0.4.7.gemspec.rz
HTTP 200 OK https://rubygems.org/quick/Marshal.4.8/pry-0.4.7.gemspec.rz
Gemspec ["pry", #<Gem::Version "0.4.7">] contained invalid data.
Your network or your gem server is probably having issues right now.
Bundler::HTTPError: Gemspec ["pry", #<Gem::Version "0.4.7">] contained invalid data.
Your network or your gem server is probably having issues right now.
/Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/fetcher.rb:112:in `rescue in fetch_spec'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/fetcher.rb:98:in `fetch_spec'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/remote_specification.rb:108:in `_remote_specification'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/remote_specification.rb:114:in `method_missing'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/lazy_specification.rb:94:in `block in __materialize__'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/lazy_specification.rb:92:in `select'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/lazy_specification.rb:92:in `__materialize__'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/spec_set.rb:75:in `block in materialize'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/spec_set.rb:72:in `map!'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/spec_set.rb:72:in `materialize'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/definition.rb:468:in `materialize'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/definition.rb:190:in `specs'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/installer.rb:243:in `ensure_specs_are_compatible!'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/installer.rb:83:in `block in run'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/process_lock.rb:9:in `open'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/process_lock.rb:9:in `lock'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/installer.rb:71:in `run'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/installer.rb:23:in `install'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/cli/install.rb:62:in `run'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/cli.rb:255:in `block in install'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/settings.rb:131:in `temporary'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/cli.rb:254:in `install'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/bin/bundle:25:in `load'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/bin/bundle:25:in `<main>'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/bin/ruby_executable_hooks:22:in `eval'
  /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/bin/ruby_executable_hooks:22:in `<main>'
```

## Environment

```
Bundler             2.3.9
  Platforms         ruby, x86_64-darwin-21
Ruby                2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-darwin-21]
  Full Path         /Users/ME/.rvm/rubies/ruby-2.7.1/bin/ruby
  Config Dir        /Users/ME/.rvm/rubies/ruby-2.7.1/etc
RubyGems            3.3.9
  Gem Home          /Users/ME/.rvm/gems/ruby-2.7.1@pry_test
  Gem Path          /Users/ME/.rvm/gems/ruby-2.7.1@pry_test:/Users/ME/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0
  User Home         /Users/ME
  User Path         /Users/ME/.gem/ruby/2.7.0
  Bin Dir           /Users/ME/.rvm/gems/ruby-2.7.1@pry_test/bin
Tools               
  Git               2.32.0 (Apple Git-132)
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-03-09
Git SHA           7f90c0083a
Released Version  true
```

## Bundler settings

```
deployment
  Set for the current user (/Users/ME/.bundle/config): false
gem.test
  Set for the current user (/Users/ME/.bundle/config): "minitest"
without
  Set for the current user (/Users/ME/.bundle/config): []
```

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'pry', '= 0.4.7'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    method_source (1.0.0)
    pry (0.4.7)
      method_source (>= 0.2.0)
      ruby_parser (>= 2.0.5)
    ruby_parser (3.18.1)
      sexp_processor (~> 4.16)
    sexp_processor (4.16.0)

PLATFORMS
  x86_64-darwin-21

DEPENDENCIES
  pry (= 0.4.7)

BUNDLED WITH
   2.3.9
```

**Comment by deivid-rodriguez** [comment]
This is my bad, I most likely introduced this with https://github.com/rubygems/rubygems/pull/5277. Will fix!

**Comment by jessebs** [comment]
It sounds like that’s probably the problem. Thanks for addressing this so quickly.

**Comment by ragnarkon** [comment]
excon v0.7.7 is another example of a gem with a gemspec that cannot be loaded.


----------------------------------------------------------

excon-0.7.7.gemspec.rz

```
ArgumentError: undefined class/module YAML::
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1273:in `load'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1273:in `_load'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler.rb:563:in `load'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler.rb:563:in `load_marshal'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/fetcher.rb:109:in `fetch_spec'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/endpoint_specification.rb:121:in `_remote_specification'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/endpoint_specification.rb:26:in `required_ruby_version'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/gem_helpers.rb:105:in `same_deps'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/gem_helpers.rb:51:in `block in select_best_platform_match'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/gem_helpers.rb:51:in `take_while'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/gem_helpers.rb:51:in `select_best_platform_match'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:140:in `block (2 levels) in search_for'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver/spec_group.rb:10:in `create_for'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:148:in `block in search_for'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:135:in `each'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:135:in `reduce'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:135:in `search_for'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:11:in `block in search_for'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:10:in `search_for'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolution.rb:727:in `activate_new_spec'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:49:in `start'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/resolver.rb:23:in `resolve'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:270:in `resolve'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/definition.rb:181:in `resolve_remotely!'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:280:in `resolve_if_needed'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:82:in `block in run'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:9:in `open'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:71:in `run'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/installer.rb:23:in `install'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/cli/install.rb:62:in `run'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:255:in `block in install'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/settings.rb:131:in `temporary'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:254:in `install'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:31:in `dispatch'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:25:in `start'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/ragnarkon/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
  /Users/ragnarkon/.rbenv/versions/2.7.5/bin/bundle:25:in `load'
  /Users/ragnarkon/.rbenv/versions/2.7.5/bin/bundle:25:in `<main>'
```
## Environment

```
Bundler       2.3.14
  Platforms   ruby, arm64-darwin-21
Ruby          2.7.5p203 (2021-11-24 revision f69aeb83146be640995753667fdd6c6f157527f5) [arm64-darwin-21]
  Full Path   /Users/ragnarkon/.rbenv/versions/2.7.5/bin/ruby
  Config Dir  /Users/ragnarkon/.rbenv/versions/2.7.5/etc
RubyGems      3.3.14
  Gem Home    /Users/ragnarkon/repos/puppet/pipelines-pdk/vendor/bundle/ruby/2.7.0
  Gem Path    /Users/ragnarkon/repos/puppet/pipelines-pdk/vendor/bundle/ruby/2.7.0
  User Home   /Users/ragnarkon
  User Path   /Users/ragnarkon/.gem/ruby/2.7.0
  Bin Dir     /Users/ragnarkon/repos/puppet/pipelines-pdk/vendor/bundle/ruby/2.7.0/bin
OpenSSL
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   /Users/ragnarkon/.rbenv/versions/2.7.5/openssl/ssl/cert.pem
  Cert Dir    /Users/ragnarkon/.rbenv/versions/2.7.5/openssl/ssl/certs
Tools
  Git         2.36.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-05-18
Git SHA           467ad58a7c
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
Oh, thanks for reminding me about this. #5415 is mostly ready, I will try to ship it with the next release!
