### ISSUE TITLE
When I run msfconsole I get this error

### ISSUE THREAD

**Issue by mister-vrionz** [rubygems/rubygems#5408]
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- net/ftp (LoadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/dnsruby-1.61.7/lib/dnsruby/dnssec.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/dnsruby-1.61.7/lib/dnsruby.rb:239:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/rex/proto/dns/packet.rb:5:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>

**Comment by deivid-rodriguez** [comment]
Hello, I don't see any traces of RubyGems or Bundler here. Why are you reporting this to our repository? Thanks.

**Comment by mister-vrionz** [comment]
> Hello, I don't see any traces of RubyGems or Bundler here. Why are you reporting this to our repository? Thanks.

Cuz I don't know where to report it. :((

**Comment by deivid-rodriguez** [comment]
Oh I see that you completely edited the issue now 🤣

> Cuz I don't know where to report it. :((

Since it's msfconsole commands that is giving you trouble, I suggest reporting it to msfconsole project. Even if it's not their issue, they might be able to guide you better.
