### ISSUE TITLE
The test/rubygems/test_gem_ext_cargo_builder trigger the errors when cargo is not installed

### ISSUE THREAD

**Issue by junaruga** [rubygems/rubygems#5411]
I'm having a problem.

My current problem is the `test/rubygems/test_gem_ext_cargo_builder.rb` finishes with error when the `cargo` command is not installed. I think the pending is ok, but the error is problem.

```
$ git clean -fdx

$ rake setup

$ rake test
...
some errors and pendings for cargo.
...

$ ruby -Ilib:test:bundler/lib test/rubygems/test_gem_ext_cargo_builder.rb -n /test_build_staticlib/
Loaded suite test/rubygems/test_gem_ext_cargo_builder
Started
P 
===============================================================================================================================
Pending: test_build_staticlib(TestGemExtCargoBuilder): cargo not present
test/rubygems/test_gem_ext_cargo_builder.rb:15:in `setup'
===============================================================================================================================
E
===============================================================================================================================
Error: test_build_staticlib(TestGemExtCargoBuilder): TypeError: no implicit conversion of nil into String
/home/jaruga/var/git/rubygems/test/rubygems/helper.rb:460:in `chdir'
/home/jaruga/var/git/rubygems/test/rubygems/helper.rb:460:in `teardown'
===============================================================================================================================

Finished in 0.013538263 seconds.
-------------------------------------------------------------------------------------------------------------------------------
1 tests, 0 assertions, 0 failures, 1 errors, 1 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------------------------------------------------------
73.86 tests/s, 0.00 assertions/s
```

This error doesn't happen when the `cargo` is installed and running the following commands.

```
$ git clean -fdx
$ rake setup
$ rake test
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

Fedora, Ruby 3.1.1, the latest upstream fe96fb6e2ac5a8b6df5e852470d11fa854301eca .

```
$ ruby -Ilib bin/gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.0.dev
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/jaruga/local/ruby-3.1.1-test-rubygems/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /home/jaruga/.gem/ruby/3.1.0
  - RUBYGEMS PREFIX: /home/jaruga/var/git/rubygems
  - RUBY EXECUTABLE: /home/jaruga/local/ruby-3.1.1-test-rubygems/bin/ruby
  - GIT EXECUTABLE: /bin/git
  - EXECUTABLE DIRECTORY: /home/jaruga/local/ruby-3.1.1-test-rubygems/bin
  - SPEC CACHE DIRECTORY: /home/jaruga/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/jaruga/local/ruby-3.1.1-test-rubygems/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/jaruga/local/ruby-3.1.1-test-rubygems/lib/ruby/gems/3.1.0
     - /home/jaruga/.gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/jaruga/.go/bin
     - /home/root/local/mongodb-4.2/bin
     - /home/root/local/samtools-1.9/bin
     - /home/root/local/bowtie2-dev-580a859/bin
     - /home/root/local/kallisto-dev/bin
     - /home/jaruga/git/gem2rpm/bin
     - /home/jaruga/git/rpmlint/dist/usr/bin
     - /usr/local/valgrind-3.11.0/bin
     - /usr/local/docker-compose-1.8.0/bin
     - /home/jaruga/.local/bin/
     - /home/jaruga/.gem/ruby/3.1.0/bin
     - /home/jaruga/local/ruby-3.1.1-test-rubygems/bin
     - /bin
     - /usr/bin
     - /usr/sbin
     - /usr/local/bin
     - /usr/local/sbin
     - /home/jaruga/bin
     - /var/lib/snapd/snap/bin
     - /home/root/local/miniconda3-py38-4.8.3/bin
     - /usr/local/mongodb-linux-x86_64-rhel80-4.4.1/bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by junaruga** [comment]
> Are you interested in contributing this @junaruga?

Sorry I am not interested in contributing this.

**Comment by junaruga** [comment]
I changed my mind. I will take a look at it later.

**Comment by hsbt** [comment]
I got the similar errors with ruby/ruby repo.

https://github.com/ruby/ruby/pull/5669/checks?check_run_id=5675458282

**Comment by junaruga** [comment]
I think we need to create the fixture directory `test/rubygems/test_gem_ext_cargo_builder/rust_ruby_example` directory path not from `__FILE__` but from a common directory variables. Is there a variable such as in `test/rubygems/helper.rb` to refer?

**Comment by junaruga** [comment]
The command below with the full path for `__FILE__` works.

```
$ ruby -Ilib:test:bundler/lib $(pwd)/test/rubygems/test_gem_ext_cargo_builder.rb -n /test_build_staticlib/
...
Finished in 20.142637792 seconds.
-------------------------------------------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------
0.05 tests/s, 0.05 assertions/s
```

**Comment by junaruga** [comment]
Do you like changing the document below like this?

```
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index 125bf1c2e7..0e80f8b3b9 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -49,11 +49,11 @@ To run the entire test suite you can use:

 To run an individual test file located for example in `test/rubygems/test_deprecate.rb` you can use:

-    ruby -Ilib:test:bundler/lib test/rubygems/test_deprecate.rb
+    ruby -Ilib:test:bundler/lib $(pwd)/test/rubygems/test_deprecate.rb

 And to run an individual test method named `test_default` within a test file, you can use:

-    ruby -Ilib:test:bundler/lib test/rubygems/test_deprecate.rb -n /test_default/
+    ruby -Ilib:test:bundler/lib $(pwd)/test/rubygems/test_deprecate.rb -n /test_default/
```

You may find other test errors by a command below.

```
for file in $(find test/ -name "test_*.rb"); do
  ruby -Ilib:test:bundler/lib "${file}"
done
```

**Comment by junaruga** [comment]
My idea is maybe that the rubygems needs a file to manage static paths used in tests such as `bundler/spec/support/path.rb` in Bundler. Then we can get a patch such as `test/rubygems/test_gem_ext_cargo_builder/rust_ruby_example` without `__FILE__`.

**Comment by junaruga** [comment]
Note the following test files are failed running the script below.

```
$ cat isolated_test.txt
#!/bin/bash

rm -f failed_test_files.txt
for file in $(find test/ -name "test_*.rb"); do
  if ! ruby -Ilib:test:bundler/lib "${file}"; then
    echo "${file}" >> failed_test_files.txt
  fi
done
```

```
$ cat failed_test_files.txt
test/rubygems/test_gem_specification.rb
test/rubygems/test_gem_ext_cmake_builder.rb
test/rubygems/test_gem_ext_cargo_builder.rb
test/rubygems/test_gem_resolver_git_specification.rb
test/rubygems/test_gem_commands_help_command.rb
test/rubygems/test_gem_source_git.rb
test/rubygems/test_gem_dependency_installer.rb
test/test_changelog_generator.rb
```

**Comment by simi** [comment]
Hello @junaruga thanks for the details. I can confirm I can reproduce those and I was wondering recently what's the problem. I was able to trace it down to `__FILE__` change per different executing of tests, but I wasn't able to collect more details.

As you mentioned bundler spec path helper...

https://github.com/rubygems/rubygems/blob/a61b3611554db41022dd7f75907213ccbf2c06f9/bundler/spec/support/path.rb#L8-L10

Can you check if similar trick would work here? I think we can ignore `ruby_core?` check (at least for now).

**Comment by junaruga** [comment]
> Can you check if similar trick would work here? I think we can ignore ruby_core? check (at least for now).

@simi , sure. I only fixed the issue in `test/rubygems/test_gem_ext_cargo_builder.rb` by the way you suggested. Here is the PR, https://github.com/rubygems/rubygems/pull/5437 . If you are ok with the way, I will try to fix other test files too.

**Comment by junaruga** [comment]
> If possible, I would like to make it enforceable (similar to https://github.com/rubygems/rubygems.org/commit/1aa7133bda4258503ecd55106a66b25617ba3df3). That way if something goes wrong on CI and cargo is not setup properly, this test will not silently pass (be skipped). Nobody checks CI if anything new was skipped when CI is green.

I think this proposal to make the tests requiring cargo enforceable is not fixed, right?

**Comment by simi** [comment]
Not yet, I'm going to move forward in my cargo backlog now since it is unlocked again. Anyway if you're interested in this, feel free to open PR.
