### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by goldenprovider** [rubygems/rubygems#5418]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `size' for nil:NilClass

    @read += ret.size
        ^^^^^
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package/tar_reader/entry.rb:139:in `read'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:364:in `block in digest'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:361:in `each'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:361:in `digest'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:647:in `verify_entry'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:666:in `block in verify_files'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:665:in `verify_files'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:596:in `block (2 levels) in verify'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:27:in `new'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:593:in `block in verify'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `open'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:592:in `verify'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/package.rb:573:in `spec'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/rubygems_integration.rb:209:in `spec_from_gem'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/source/rubygems.rb:167:in `install'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/worker.rb:62:in `apply_func'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/worker.rb:54:in `loop'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/worker.rb:54:in `process_queue'
  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.3.7
  Platforms   ruby, x86_64-linux
Ruby          3.1.0p0 (2021-12-25 revision fb4df44d1670e9d25aef6b235a7281199a177edb) [x86_64-linux]
  Full Path   /home/user/.rbenv/versions/3.1.0/bin/ruby
  Config Dir  /home/user/.rbenv/versions/3.1.0/etc
RubyGems      3.3.3
  Gem Home    /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0
  Gem Path    /home/user/.local/share/gem/ruby/3.1.0:/home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0
  User Home   /home/user
  User Path   /home/user/.local/share/gem/ruby/3.1.0
  Bin Dir     /home/user/.rbenv/versions/3.1.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1f  31 Mar 2020
  Loaded      OpenSSL 1.1.1f  31 Mar 2020
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.25.1
  RVM         not installed
  rbenv       rbenv 1.2.0-11-ge4f61e6
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-02-09
Git SHA           bafe43c593
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
<No /home/user/Documents/Work/Forecaster/easy_captcha_example/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Hello!

Sorry I have no idea how this error could end up happening? Did you get the error consistently? Did you try upgrading RubyGems and Bundler?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by tejas-ebizz** [comment]
i am also getting same error.

My gem file is as below

`# frozen_string_literal: true

source "https://rubygems.org"

gem "rails"
gem "fastlane"`

error
`
<No /Users/tl-1/Desktop/FIrstFastlaneProject/Gemfile.lock found>

Unfortunately, an unexpected error occurred, and Bundler cannot continue.
`

**Comment by deivid-rodriguez** [comment]
Please report a separate issue with as much information as possible, ideally with steps that we can run on our laptop to see the error for ourselves. Thanks!
