### ISSUE TITLE
Error found

### ISSUE THREAD

**Issue by belabonga** [rubygems/rubygems#5421]
```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/shania/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-darwin-17/3.0.0/strscan-3.0.1
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `each'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:207:in `write_gem_make_out'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:135:in `build_error'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:169:in `rescue in build_extension'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:158:in `build_extension'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:192:in `each'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:853:in `build_extensions'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/shania/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.3.9
  Platforms   ruby, x86_64-darwin-17
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-darwin-17]
  Full Path   /Users/shania/.rbenv/versions/3.0.2/bin/ruby
  Config Dir  /Users/shania/.rbenv/versions/3.0.2/etc
RubyGems      3.3.9
  Gem Home    /Users/shania/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  Gem Path    /Users/shania/.local/share/gem/ruby/3.0.0:/Users/shania/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  User Home   /Users/shania
  User Path   /Users/shania/.local/share/gem/ruby/3.0.0
  Bin Dir     /Users/shania/.rbenv/versions/3.0.2/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1m  14 Dec 2021
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   /usr/local/etc/openssl@1.1/cert.pem
  Cert Dir    /usr/local/etc/openssl@1.1/certs
Tools         
  Git         2.16.2
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-03-09
Git SHA           7f90c0083a
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.3"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
<No /Users/shania/blog/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
Seems the same as #5384, I'll centralize the fix there.
