### ISSUE TITLE
issue with jeklly 

### ISSUE THREAD

**Issue by sangam14** [rubygems/rubygems#5433]
sudo gem install rake && bundle install  3m 10s
Password:
Fetching rake-13.0.6.gem
Successfully installed rake-13.0.6
Parsing documentation for rake-13.0.6
Installing ri documentation for rake-13.0.6
Done installing documentation for rake after 1 seconds
1 gem installed
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Your lockfile was created by an old Bundler that left some things out.
Because of the missing DEPENDENCIES, we can only install gems one at a time, instead of installing 12 at a time.
You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
The missing gems are:
* nokogiri depended upon by html-pipeline
Using concurrent-ruby 1.1.9
Using i18n 1.8.11
Using minitest 5.14.4
Using tzinfo 2.0.4
Using zeitwerk 2.5.1
Using activesupport 6.1.4.1
Using public_suffix 4.0.6
Using addressable 2.8.0
Using bundler 2.3.4
Using colorator 1.1.0
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.2
Using ffi 1.15.4
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using html-pipeline 2.14.0
Using sassc 2.4.0
Using jekyll-sass-converter 2.1.0
Using rb-fsevent 0.11.0
Using rb-inotify 0.10.1
Using listen 3.7.0
Using jekyll-watch 2.2.1
Using rexml 3.2.5
Using kramdown 2.3.1
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.4.0
Using pathutil 0.16.2
Using rouge 3.26.1
Using safe_yaml 1.0.5
Using unicode-display_width 1.8.0
Using terminal-table 2.0.0
Using jekyll 4.2.1
Using jekyll-feed 0.15.1
Using jekyll-seo-tag 2.7.1
Using jekyll-sitemap 1.4.0
Using jemoji 0.12.0
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `full_name' for nil:NilClass
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:123:in `each'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:122:in `each'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:100:in `call'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer.rb:259:in `install_in_parallel'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer.rb:209:in `install'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer.rb:89:in `block in run'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/process_lock.rb:9:in `open'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/process_lock.rb:9:in `lock'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer.rb:71:in `run'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/installer.rb:23:in `install'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/cli/install.rb:62:in `run'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/cli.rb:255:in `block in install'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/settings.rb:131:in `temporary'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/cli.rb:254:in `install'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/cli.rb:31:in `dispatch'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/cli.rb:25:in `start'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/exe/bundle:48:in `block in <top (required)>'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/sangam/.gem/ruby/2.6.0/gems/bundler-2.3.4/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.3.4
  Platforms   ruby, universal-darwin-21
Ruby          2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.2.32
  Gem Home    /Users/sangam/.gem
  Gem Path    /Users/sangam/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/Users/sangam/.gem:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/sangam
  User Path   /Users/sangam/.gem/ruby/2.6.0
  Bin Dir     /Users/sangam/.gem/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.30.1 (Apple Git-130)
  RVM         1.29.12 (latest)
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-29
Git SHA           2296a0d6cc
Released Version  true
```

## Bundler settings

```
build.nokogiri
  Set for the current user (/Users/sangam/.bundle/config): "--use-system-libraries=true --with-xml2-include=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2"
build.puma
  Set for the current user (/Users/sangam/.bundle/config): "--with-cflags=-Wno-error=implicit-function-declaration"
force_ruby_platform
  Set for the current user (/Users/sangam/.bundle/config): true
```

### Gemfile

```ruby
# frozen_string_literal: true
source "https://rubygems.org"

gem "jemoji"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.1.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.9)
    em-websocket (0.5.2)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.7)
    ffi (1.15.4)
    forwardable-extended (2.6.0)
    gemoji (3.0.1)
    html-pipeline (2.14.0)
      activesupport (>= 2)
      nokogiri (>= 1.4)
    http_parser.rb (0.6.0)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-feed (0.15.1)
      jekyll (>= 3.7, < 5.0)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-seo-tag (2.7.1)
      jekyll (>= 3.8, < 5.0)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    jemoji (0.12.0)
      gemoji (~> 3.0)
      html-pipeline (~> 2.2)
      jekyll (>= 3.0, < 5.0)
    kramdown (2.3.1)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    minitest (5.14.4)
    nokogiri (1.13.3-x86_64-linux)
      racc (~> 1.4)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    racc (1.6.0)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.26.1)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    unicode-display_width (1.8.0)
    zeitwerk (2.5.1)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  jekyll-feed
  jekyll-seo-tag
  jekyll-sitemap
  jemoji

BUNDLED WITH
   2.2.26
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Sorry for not looking into this before, I think this might be a duplicate of https://github.com/rubygems/rubygems/issues/5422, although I cannot yet reproduce it. The setup of this issue seems simpler though, is it reproducible? Did you manage to fix this on your end, and that's why you closed this?

**Comment by sangam14** [comment]
@deivid-rodriguez I did fixed it ! and then closed
