### ISSUE TITLE
rails `bin/bundle install`: NameError: uninitialized constant Gem::Source

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#5451]
- OS: Ubuntu 20.04
- Version manager: `chruby`
- Ruby version: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]`
- Bundler version: `2.3.7`
- Gem environment: 
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/user/.gem/ruby/3.1.1
  - USER INSTALLATION DIRECTORY: /home/user/.gem/ruby/3.1.0
  - RUBY EXECUTABLE: /home/user/.rubies/ruby-3.1.1/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/user/.gem/ruby/3.1.1/bin
  - SPEC CACHE DIRECTORY: /home/user/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/user/.rubies/ruby-3.1.1/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/user/.gem/ruby/3.1.1
     - /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/user/.gem/ruby/3.1.1/bin
     - /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/bin
     - /home/user/.rubies/ruby-3.1.1/bin
     - /home/user/.cargo/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

The issue: Unable to run `bundle install` in new rails application

Reproduction steps:
1. Install most recent rails with `gem install rails` (7.0.2.3) is installed
2. Create a new application with `rails _7.0.2.3_ new ~/testapp --force`
3. Go to `~/testapp`
4. Run `ruby bin/bundle install`

Exp: bundle runs successfuly
Act: 
```
[600, #<Thread:0x00007f400085bc58 run>, #<NameError: uninitialized constant Gem::Source

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
Did you mean?  Gem::SourceList>, ["/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'", "<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'", "<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'", "<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'", "bin/bundle:113:in `load'", "bin/bundle:113:in `<main>'"]]
[600, #<Thread:0x00007f400085bc58 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'", "<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'", "/home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'", "bin/bundle:113:in `load'", "bin/bundle:113:in `<main>'"]]
/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source': uninitialized constant Gem::Source (NameError)

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
Did you mean?  Gem::SourceList
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:26:in `log_error'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:109:in `rescue in with_friendly_errors'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:101:in `with_friendly_errors'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from bin/bundle:113:in `load'
	from bin/bundle:113:in `<main>'
<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from bin/bundle:113:in `load'
	from bin/bundle:113:in `<main>'
<internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from bin/bundle:113:in `load'
	from bin/bundle:113:in `<main>'
/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source': uninitialized constant Gem::Source (NameError)

      (defined?(@source) && @source) || Gem::Source::Installed.new
                                           ^^^^^^^^
Did you mean?  Gem::SourceList
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:18:in `source'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/rubygems_ext.rb:50:in `extension_dir'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:339:in `have_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/basic_specification.rb:86:in `contains_requirable_file?'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1038:in `block (2 levels) in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2555:in `block (2 levels) in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:1:in `<top (required)>'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `require_relative'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendored_persistent.rb:11:in `<top (required)>'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `require_relative'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/fetcher.rb:3:in `<top (required)>'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli/install.rb:50:in `run'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/user/.rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from bin/bundle:113:in `load'
	from bin/bundle:113:in `<main>'
```

If i use regular bundler, not from `bin/bundle` - it works fine.

`bin/bundle` contents:
```
#!/usr/bin/env ruby
# frozen_string_literal: true

#
# This file was generated by Bundler.
#
# The application 'bundle' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require "rubygems"

m = Module.new do
  module_function

  def invoked_as_script?
    File.expand_path($0) == File.expand_path(__FILE__)
  end

  def env_var_version
    ENV["BUNDLER_VERSION"]
  end

  def cli_arg_version
    return unless invoked_as_script? # don't want to hijack other binstubs
    return unless "update".start_with?(ARGV.first || " ") # must be running `bundle update`
    bundler_version = nil
    update_index = nil
    ARGV.each_with_index do |a, i|
      if update_index && update_index.succ == i && a =~ Gem::Version::ANCHORED_VERSION_PATTERN
        bundler_version = a
      end
      next unless a =~ /\A--bundler(?:[= ](#{Gem::Version::VERSION_PATTERN}))?\z/
      bundler_version = $1
      update_index = i
    end
    bundler_version
  end

  def gemfile
    gemfile = ENV["BUNDLE_GEMFILE"]
    return gemfile if gemfile && !gemfile.empty?

    File.expand_path("../../Gemfile", __FILE__)
  end

  def lockfile
    lockfile =
      case File.basename(gemfile)
      when "gems.rb" then gemfile.sub(/\.rb$/, gemfile)
      else "#{gemfile}.lock"
      end
    File.expand_path(lockfile)
  end

  def lockfile_version
    return unless File.file?(lockfile)
    lockfile_contents = File.read(lockfile)
    return unless lockfile_contents =~ /\n\nBUNDLED WITH\n\s{2,}(#{Gem::Version::VERSION_PATTERN})\n/
    Regexp.last_match(1)
  end

  def bundler_requirement
    @bundler_requirement ||=
      env_var_version || cli_arg_version ||
        bundler_requirement_for(lockfile_version)
  end

  def bundler_requirement_for(version)
    return "#{Gem::Requirement.default}.a" unless version

    bundler_gem_version = Gem::Version.new(version)

    requirement = bundler_gem_version.approximate_recommendation

    return requirement unless Gem.rubygems_version < Gem::Version.new("2.7.0")

    requirement += ".a" if bundler_gem_version.prerelease?

    requirement
  end

  def load_bundler!
    ENV["BUNDLE_GEMFILE"] ||= gemfile

    activate_bundler
  end

  def activate_bundler
    gem_error = activation_error_handling do
      gem "bundler", bundler_requirement
    end
    return if gem_error.nil?
    require_error = activation_error_handling do
      require "bundler/version"
    end
    return if require_error.nil? && Gem::Requirement.new(bundler_requirement).satisfied_by?(Gem::Version.new(Bundler::VERSION))
    warn "Activating bundler (#{bundler_requirement}) failed:\n#{gem_error.message}\n\nTo install the version of bundler this project requires, run `gem install bundler -v '#{bundler_requirement}'`"
    exit 42
  end

  def activation_error_handling
    yield
    nil
  rescue StandardError, LoadError => e
    e
  end
end

m.load_bundler!

if m.invoked_as_script?
  load Gem.bin_path("bundler", "bundle")
end
```

Default `bundle` contents:
```
#!/home/user/.rubies/ruby-3.1.1/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ENV['BUNDLER_VERSION'] = str

    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('bundler', 'bundle', version)
else
gem "bundler", version
load Gem.bin_path("bundler", "bundle", version)
end
```

**Comment by hsbt** [comment]
Can you try with bundler-2.3.10?

**Comment by hurricup** [comment]
Yep, it works fine

**Comment by deivid-rodriguez** [comment]
Great, closing then!

**Comment by hsbt** [comment]
I will backport bundler-2.3.11 into Ruby 3.1.2.
