### ISSUE TITLE
Security features tests are failing on RHEL 9 / c9s

### ISSUE THREAD

**Issue by jackorp** [rubygems/rubygems#5454]
Tests related to security features of RubyGems are currently failing during Ruby build in RHEL 9 / CentOS 9 stream.

RHEL 9 / c9s have introduced stricter crypto policies and with that, the SHA1 is disabled by default.
The following tests are failing in this environment, setting the crypto policies to LEGACY instead of DEFAULT makes the tests pass.

What I found the failures have in common are loading certificate fixtures that are using SHA1 in one way or another.

The failures:
```
  1) Failure:
TestGemRequest#test_configure_connection_for_https_ssl_ca_cert [/builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_request.rb:124]:
Failed assertion, no message given.
  2) Failure:
TestGemRequest#test_configure_connection_for_https [/builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_request.rb:105]:
Failed assertion, no message given.
  3) Failure:
TestGemSecurityPolicy#test_check_chain_invalid [/builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:108]:
<"invalid signing chain: certificate /CN=invalidchild/DC=example was not issued by /CN=child/DC=example"> expected but was
<"invalid signing chain: certificate /CN=child/DC=example was not issued by /CN=nobody/DC=example">.
  4) Failure:
TestGemSecurityPolicy#test_verify_signatures_missing [/builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:493]:
<"missing signature for data.tar.gz"> expected but was
<"certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example">.
  5) Error:
TestGemPackageTarWriter#test_add_file_signer:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package_tar_writer.rb:124:in `block in test_add_file_signer'
    /builddir/build/BUILD/ruby-3.1.1/test/resolv/test_dns.rb:29:in `stub'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package_tar_writer.rb:123:in `test_add_file_signer'
  6) Error:
TestGemPackage#test_build_auto_signed_encrypted_key:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:307:in `block (2 levels) in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:306:in `block in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `open'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `with_write_io'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:305:in `build'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:322:in `test_build_auto_signed_encrypted_key'
  7) Error:
TestGemPackage#test_build_signed:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:307:in `block (2 levels) in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:306:in `block in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `open'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `with_write_io'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:305:in `build'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:385:in `test_build_signed'
  8) Error:
TestGemPackage#test_verify_security_policy_low_security:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:307:in `block (2 levels) in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:306:in `block in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `open'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `with_write_io'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:305:in `build'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:989:in `test_verify_security_policy_low_security'
  9) Error:
TestGemPackage#test_build_auto_signed:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:307:in `block (2 levels) in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:306:in `block in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `open'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `with_write_io'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:305:in `build'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:279:in `test_build_auto_signed'
 10) Error:
TestGemPackage#test_build_signed_encrypted_key:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:307:in `block (2 levels) in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:306:in `block in build'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `open'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/file_source.rb:25:in `with_write_io'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:305:in `build'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:422:in `test_build_signed_encrypted_key'
 11) Error:
TestGemPackage#test_verify_security_policy_checksum_missing:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:1012:in `block (2 levels) in test_verify_security_policy_checksum_missing'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:1011:in `block in test_verify_security_policy_checksum_missing'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:1010:in `open'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_package.rb:1010:in `test_verify_security_policy_checksum_missing'
 21) Error:
TestGemSecurityPolicy#test_check_root:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:193:in `test_check_root'
 22) Error:
TestGemSecurityPolicy#test_verify_signatures_chain:
Gem::Security::Exception: invalid signing chain: certificate /CN=child/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:66:in `rescue in check_chain'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:59:in `check_chain'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:245:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:285:in `verify_signatures'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:415:in `test_verify_signatures_chain'
 23) Error:
TestGemSecurityPolicy#test_verify_chain_signatures:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:306:in `test_verify_chain_signatures'
 24) Error:
TestGemSecurityPolicy#test_verify_signatures:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:285:in `verify_signatures'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:464:in `test_verify_signatures'
 25) Error:
TestGemSecurityPolicy#test_verify_signatures_root:
Gem::Security::Exception: invalid signing chain: certificate /CN=child/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:66:in `rescue in check_chain'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:59:in `check_chain'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:245:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:285:in `verify_signatures'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:427:in `test_verify_signatures_root'
 26) Error:
TestGemSecurityPolicy#test_check_cert_issuer:
Gem::Security::Exception: certificate /CN=child/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:156:in `test_check_cert_issuer'
 27) Error:
TestGemSecurityPolicy#test_check_chain:
Gem::Security::Exception: invalid signing chain: certificate /CN=child/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:66:in `rescue in check_chain'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:59:in `check_chain'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:90:in `test_check_chain'
 28) Error:
TestGemSecurityPolicy#test_verify_signatures_trust:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:285:in `verify_signatures'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_policy.rb:441:in `test_verify_signatures_trust'
 29) Error:
TestGemSecuritySigner#test_sign:
Gem::Security::Exception: certificate /CN=nobody/DC=example was not issued by /CN=nobody/DC=example
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:101:in `check_cert'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:141:in `check_root'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/policy.rb:247:in `verify'
    /builddir/build/BUILD/ruby-3.1.1/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.1/test/rubygems/test_gem_security_signer.rb:120:in `test_sign'
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
@jackorp Would you be able to provide a PR to fix this?

**Comment by jackorp** [comment]
> @jackorp Would you be able to provide a PR to fix this?

I can try that, but cannot promise a concrete deadline as of now as I have other higher priority work.

I will have to investigate if it actually is that those certificates are using the SHA1 somewhere under the hood (in which case it would be better if upstream regenerated those instead of us) or if the problem is elsewhere.

**Comment by jackorp** [comment]
I did some digging around and found that the problem is that the certificates use SHA1 in the Signature Algorithm.

I have regenerated the certificates using this file: https://github.com/rubygems/rubygems/blob/master/util/create_certs.rb
with the modification of [Line 69](https://github.com/rubygems/rubygems/blob/master/util/create_certs.rb#L69) replacing `SHA1` with SHA256.

The state is better, but it seems something will need further adjusting to iron out these tests that are failing:
```
[ 2848/21443] TestGemSecuritySigner#test_sign = 0.02 s
  1) Failure:
TestGemSecuritySigner#test_sign [/builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_security_signer.rb:131]:
<"cHze2sEfRysoUMCfGVAx/7o8jxj5liJJ2ptNxe2jf3l+EZvyjdqpXo9Ndzxx\n" +
"6xLp2rxLG4K2//ip4aCH5Sh7hnia+F5u6iuLBETPlklPrmw5dnuKZxolz+vM\n" +
"0O1aOZsQHcVzQoESTGjkms3KZk+gn3lg0sSBbAV5/LyDYoHCEjxlcA5D+Olb\n" +
"rDmRyBMOnMS+q489OZ5Hr6B2YJJ3QbUwIZNhUeNmOxIBEYTrrKkZ92qkxbRN\n" +
"qhlqFP4jR6zXFeyBCOr0KpTiWBNuxBFXDsxmhGyt2BOIjD6qmKn7RSIfYg/U\n" +
"toqvglr0kdbknSRRjBVLK6tsgr07aLT9gNP7mTW2PA==\n"> expected but was
<"FmrCYxEXW3dgYYNMxPdS16VrdXT+d5nyXTVlRm64ZHSgMxMAaPtQJsVYv73m\n" +
"DWHTzNnLhhINSpgBMLh5a4atM52yxVdkPUTgqIH+LeIPBXn8xaP5JLmfDcmI\n" +
"tBpc/9DhS3v9iKCX40igAArFu7Gg3swbgQ61SP+U22LvG5nDQZQz3sudtsw3\n" +
"qKPykFVaYjrRwzvBdSdJ1PwlAsanSwcwS/GKPtmE/ykZ6X5XOx7wvCDL/zGy\n" +
"B8khkB8hDKC6moCzebmUxCBmTmXD0Wjzon+bf4MOriVE3a0ySGRvpr1mKR2+\n" +
"9EaVo7pDJLEM487+xg1CAZHRhwshd6II00XEzG/jBQ==\n">.

[10115/21443] TestGemSecurity#test_class_create_cert_email = 0.02 s
  2) Failure:
TestGemSecurity#test_class_create_cert_email [/builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_security.rb:102]:
<"5F:43:6E:F6:9A:8E:45:25:E9:22:E3:7D:37:5E:A4:D5:36:02:85:1B"> expected but was
<"B1:1A:54:09:67:45:60:02:02:D7:CE:F4:1D:60:4A:89:DF:E7:58:D9">.

[10118/21443] TestGemSecurity#test_class_sign = 0.02 s
  3) Failure:
TestGemSecurity#test_class_sign [/builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_security.rb:233]:
<"5F:43:6E:F6:9A:8E:45:25:E9:22:E3:7D:37:5E:A4:D5:36:02:85:1B"> expected but was
<"B1:1A:54:09:67:45:60:02:02:D7:CE:F4:1D:60:4A:89:DF:E7:58:D9">.

[10119/21443] TestGemSecurity#test_class_create_cert = 0.02 s
  4) Failure:
TestGemSecurity#test_class_create_cert [/builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_security.rb:54]:
<"5F:43:6E:F6:9A:8E:45:25:E9:22:E3:7D:37:5E:A4:D5:36:02:85:1B"> expected but was
<"B1:1A:54:09:67:45:60:02:02:D7:CE:F4:1D:60:4A:89:DF:E7:58:D9">.

[10125/21443] TestGemSecurity#test_class_sign_AltName = 0.03 s
  5) Failure:
TestGemSecurity#test_class_sign_AltName [/builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_security.rb:275]:
<"5F:43:6E:F6:9A:8E:45:25:E9:22:E3:7D:37:5E:A4:D5:36:02:85:1B"> expected but was
<"B1:1A:54:09:67:45:60:02:02:D7:CE:F4:1D:60:4A:89:DF:E7:58:D9">.

[10126/21443] TestGemSecurity#test_class_re_sign = 0.02 s
  6) Failure:
TestGemSecurity#test_class_re_sign [/builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_security.rb:154]:
<"sha1WithRSAEncryption"> expected but was
<"sha256WithRSAEncryption">.

[13315/21443] TestGemPackage#test_build_signed_encrypted_key = 0.03 s
  7) Error:
TestGemPackage#test_build_signed_encrypted_key:
Gem::Security::Exception: certificate /CN=nobody/DC=example does not match the signing key
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/security/policy.rb:118:in `check_key'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/security/policy.rb:241:in `verify'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:307:in `block (2 levels) in build'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:306:in `block in build'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/file_source.rb:25:in `open'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/file_source.rb:25:in `with_write_io'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:305:in `build'
    /builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_package.rb:422:in `test_build_signed_encrypted_key'

[13342/21443] TestGemPackage#test_build_auto_signed_encrypted_key = 0.03 s
  8) Error:
TestGemPackage#test_build_auto_signed_encrypted_key:
Gem::Security::Exception: certificate /CN=nobody/DC=example does not match the signing key
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/security/policy.rb:118:in `check_key'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/security/policy.rb:241:in `verify'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/security/signer.rb:154:in `sign'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/tar_writer.rb:190:in `add_file_signed'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:279:in `add_metadata'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:307:in `block (2 levels) in build'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/tar_writer.rb:78:in `new'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:306:in `block in build'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/file_source.rb:25:in `open'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package/file_source.rb:25:in `with_write_io'
    /builddir/build/BUILD/ruby-3.1.2/lib/rubygems/package.rb:305:in `build'
    /builddir/build/BUILD/ruby-3.1.2/test/rubygems/test_gem_package.rb:322:in `test_build_auto_signed_encrypted_key'
```

**Comment by deivid-rodriguez** [comment]
Thanks for digging!
