### ISSUE TITLE
Issue running bundle install in v2.3.12 - undefined method none? for nil:NilClass

### ISSUE THREAD

**Issue by andrewbelu** [rubygems/rubygems#5492]
The following commit seems to have broken my build: https://github.com/rubygems/rubygems/commit/616c866bde964b963044cffdc7bc1444521e6c15

Running bundle install now fails in my build. I am guessing some of my gems don't have the required_ruby_version or required_rubygems_version set. Works as intended in bundle version 2.3.11.

Error is below:
``` NoMethodError: undefined method "none?' for nil:NilClass
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:103:in "metadata_dependencies'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:83:in "block in dependencies_for'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:82:in "map'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:82:in "dependencies_for'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:26:in "block in initialize'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:50:in "dependencies_for_activated_platforms'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver.rb:104:in "dependencies_for'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:18:in "block in dependencies_for'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in "with_no_such_dependency_error_handling'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:17:in "dependencies_for'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:809:in "block in group_possibilities'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:808:in "reverse_each'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:808:in "group_possibilities'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:779:in "possibilities_for_requirement'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:761:in "push_state_for_requirements'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:744:in "require_nested_dependencies_for'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:727:in "activate_new_spec'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:684:in "attempt_to_activate'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:254:in "process_topmost_state'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:182:in "resolve'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:43:in "resolve'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver.rb:49:in "start'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver.rb:23:in "resolve'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/definition.rb:269:in "resolve'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/definition.rb:180:in "resolve_remotely!'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:280:in "resolve_if_needed'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:82:in "block in run'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/process_lock.rb:12:in "block in lock'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/process_lock.rb:9:in "open'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/process_lock.rb:9:in "lock'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:71:in "run'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:23:in "install'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/install.rb:62:in "run'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:255:in "block in install'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/settings.rb:131:in "temporary'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:254:in "install'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in "run'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in "invoke_command'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in "dispatch'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in "dispatch'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in "start'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in "start'
   /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:48:in "block in <top (required)>'
   /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in "with_friendly_errors'
   /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:36:in "<top (required)>'
   /usr/local/bundle/bin/bundle:23:in "load'
   /usr/local/bundle/bin/bundle:23:in "<main>'```

**Comment by andrewbelu** [comment]
I cannot share my Gemfile, I'll just say that I am running my own gem server, and the gems in question are custom ones that do not seem to specify a `required_ruby_version` and `required_rubygems_version`. These are said to be optional in the documentation (https://guides.rubygems.org/specification-reference).

 ## Environment
 
 ```
 Bundler       2.3.12
   Platforms   ruby, x86_64-linux-musl
 Ruby          3.0.4p208 (2022-04-12 revision 3fa771ddedac25560be57f4055f1767e6c810f58) [x86_64-linux-musl]
   Full Path   /usr/local/bin/ruby
   Config Dir  /usr/local/etc
 RubyGems      3.2.33
   Gem Home    /usr/local/bundle
   Gem Path    /root/.local/share/gem/ruby/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/local/bundle
   User Home   /root
   User Path   /root/.local/share/gem/ruby/3.0.0
   Bin Dir     /usr/local/bundle/bin
 OpenSSL       
   Compiled    OpenSSL 1.1.1n  15 Mar 2022
   Loaded      OpenSSL 1.1.1n  15 Mar 2022
   Cert File   /etc/ssl1.1/cert.pem
   Cert Dir    /etc/ssl1.1/certs
 Tools         
   Git         2.34.2
   RVM         not installed
   rbenv       not installed
   chruby      not installed
 ```
 
 ## Bundler Build Metadata
 
 ```
 Built At          2022-04-20
 Git SHA           75031e03f4
 Released Version  true
 ```

**Comment by deivid-rodriguez** [comment]
Yes, they are absolutely optional. What I mean is that rubygems sets them to an empty requirement by default when they are not set:

https://github.com/rubygems/rubygems/blob/0061c26db8b3b6c24956bde44cd0b1f834b09009/lib/rubygems/specification.rb#L148-L149

Just to make sure. Can you try upgrading Ruby and/or RubyGems?

**Comment by andrewbelu** [comment]
Same issue using Ruby v3.1.2 and RubyGems v3.3.12, which seem to be the latest stable releases of both.

 ## Environment
 
 ```
 Bundler       2.3.12
   Platforms   ruby, x86_64-linux-musl
 Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux-musl]
   Full Path   /usr/local/bin/ruby
   Config Dir  /usr/local/etc
 RubyGems      3.3.12
   Gem Home    /usr/local/bundle
   Gem Path    /root/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/bundle
   User Home   /root
   User Path   /root/.local/share/gem/ruby/3.1.0
   Bin Dir     /usr/local/bundle/bin
 OpenSSL       
   Compiled    OpenSSL 1.1.1n  15 Mar 2022
   Loaded      OpenSSL 1.1.1n  15 Mar 2022
   Cert File   /etc/ssl1.1/cert.pem
   Cert Dir    /etc/ssl1.1/certs
 Tools         
   Git         2.34.2
   RVM         not installed
   rbenv       not installed
   chruby      not installed
 ```
 
 ## Bundler Build Metadata
 
 ```
 Built At          2022-04-20
 Git SHA           75031e03f4
 Released Version  true
 ```

**Comment by Jim-Robbins** [comment]
The same error started occurring for several of our projects, where we pull from both the public rubygems server as well as an internal `gem-in-a-box` server. 


--- ERROR REPORT TEMPLATE -------------------------------------------------------
```
NoMethodError: undefined method `none?' for nil:NilClass
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:103:in `metadata_dependencies'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:83:in `block in dependencies_for'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:82:in `map'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:82:in `dependencies_for'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:26:in `block in initialize'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver/spec_group.rb:50:in `dependencies_for_activated_platforms'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver.rb:104:in `dependencies_for'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:808:in `reverse_each'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:808:in `group_possibilities'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:696:in `attempt_to_filter_existing_spec'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver.rb:49:in `start'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/resolver.rb:23:in `resolve'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/definition.rb:269:in `resolve'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/definition.rb:180:in `resolve_remotely!'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:280:in `resolve_if_needed'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:82:in `block in run'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/process_lock.rb:9:in `open'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/process_lock.rb:9:in `lock'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:71:in `run'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/installer.rb:23:in `install'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/install.rb:62:in `run'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:255:in `block in install'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/settings.rb:[131](https://gitlab.com/digitalturbine/appmedia/qa-automation/admanager/api-qa/-/jobs/2367044470#L131):in `temporary'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:254:in `install'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
  /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
  /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
  /usr/local/bundle/bin/bundle:23:in `load'
  /usr/local/bundle/bin/bundle:23:in `<main>'
```
## Environment
```
Bundler       2.3.12
  Platforms   ruby, x86_64-linux-musl
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.1.2
  Gem Home    /app/vendor/bundle/ruby/2.7.0
  Gem Path    /app/vendor/bundle/ruby/2.7.0
  User Home   /root
  User Path   /root/.gem/ruby/2.7.0
  Bin Dir     /app/vendor/bundle/ruby/2.7.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1g  21 Apr 2020
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   /etc/ssl/cert.pem
  Cert Dir    /etc/ssl/certs
Tools         
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```
## Bundler Build Metadata
```
Built At          [202](https://gitlab.com/digitalturbine/appmedia/qa-automation/admanager/api-qa/-/jobs/2367044470#L202)2-04-20
Git SHA           75031e03f4
Released Version  true
```
## Bundler settings
```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
path
  Set for the current user (/root/.bundle/config): "/app/vendor/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```
## Gemfile
### Gemfile
```ruby
ruby '2.7.1'
source 'https://dtgems.dev.appia.com' do
  gem 'cucumber', '3.1.2'
  gem 'dt-rubocop-config'
  gem 'dt-testrail'
  gem 'factory_bot', '5.2.0'
  gem 'faker', '2.11.0'
  gem 'kafka-handler', '0.2.2'
  gem 'pry', '0.14.1'
  gem 'rake', '13.0.1'
  gem 'require_all'
  gem 'rest-client', '2.1.0'
  gem 'rspec', '3.9.0'
  gem 'ruby-kafka', '1.4.0'
end
```
### Gemfile.lock
```
<No /app/Gemfile.lock found>
```
--- TEMPLATE END ----------------------------------------------------------------
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60none%3F%27+for+nil+NilClass&type=Issues
If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.


We create a bundler docker image and pass in our Gem file to it as follow:
```# base ruby image
ARG RUBY_VERSION="2.7.1"
FROM ruby:${RUBY_VERSION}-alpine

RUN apk update \
    && apk upgrade \
    && apk add --update --no-cache \
    build-base curl-dev zlib-dev

# cd into our app folder (each time we start up)
WORKDIR /app

# Install and confiture bundler and gem source
ARG GEM_IN_A_BOX_HOST="http://dtgems.dev.appia.com/"

RUN  gem sources --add ${GEM_IN_A_BOX_HOST} && gem install bundler
RUN bundle config set path '/app/vendor/bundle'
```

**Comment by Lancelittle** [comment]
Same issue with `2.3.12` in jruby 9.3.4.0.

No issue's with `2.3.11` though.

**Comment by hsbt** [comment]
@andrewbelu Can you reproduce this without `x86_64-linux-musl`? alpine linux is not surppoted by the Ruby language officially.

**Comment by deivid-rodriguez** [comment]
It's somehow related to private rubygems servers using gemstash or geminabox, and it's 100% created by https://github.com/rubygems/rubygems/commit/616c866bde964b963044cffdc7bc1444521e6c15. It also seems related to another recent regression: https://github.com/rubygems/rubygems/pull/5447.

I will revert https://github.com/rubygems/rubygems/commit/616c866bde964b963044cffdc7bc1444521e6c15 and further investigate this issue for the next release.

**Comment by pawan-parashar** [comment]
Still seeing the issue with latest saw branch.. do we have a solution for this issue.

![image](https://user-images.githubusercontent.com/104378564/165167735-c0f62004-b43c-4ed6-b0f7-ab8021d22468.png)

**Comment by deivid-rodriguez** [comment]
Please have some patience, I will fix this in the next days.

**Comment by deivid-rodriguez** [comment]
#5496 will fix this, please give it a try to confirm!

**Comment by deivid-rodriguez** [comment]
Next Wednesday at the latest.
