### ISSUE TITLE
Bundler uses rubygems.org to install itself ignoring remote sources configuration

### ISSUE THREAD

**Issue by dudarenko-io** [rubygems/rubygems#5498]
### Describe the problem as clearly as you can

Bundler always use rubygems.org to install itself. After bundler 2.3 was released with locking the bundler version we encountered an issue with running `bundle install`. 

Our environment forbids use of rubygems source, we use Nexus repo server instead. Because of [this issue #5446](https://github.com/rubygems/rubygems/issues/5446) we now locked bundler to 2.3.4 in our projects. We have some machines with latest bundler and access to rubygems.org and it works fine. However in our docker builds we can't use latest bunder, because it trying to download drom rubygems.org by default.
See hardcoded source: https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/self_manager.rb#L114

As workaround maybe we can do the following 
```
gem install bundler -v '2.3.4'
export BUNDLER_VERSION='2.3.4' # that disables locking bundler?
bundle install
```

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

Use docker environment:
```(docker)
FROM ruby:2.7.5
ENV HTTP_PROXY='proxy.company.com:80'
ENV HTTPS_PROXY='proxy.company.com:80'
RUN \
    gem source --clear-all \
    && gem source --remove 'https://rubygems.org/' \
    && gem source --add 'https://nexus.company.com/repository/ruby-gems-group-repo/' \
    && gem update --system

```
Run `bundle init` and change bundled with version to 2.3.4, then `bundle install`

### Which command did you run?

bundle install

### What were you expecting to happen?

Succesfull installation of bundler 2.3.4 used in Gemfile.lock from used gem source

### What actually happened?

```
Bundler 2.3.12 is running, but your lockfile was generated with 2.3.4. Installing Bundler 2.3.4 and restarting using that version.
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see https://railsapps.github.io/openssl-certificate-verify-failed.html. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.

...

There was an error installing the locked bundler version (2.3.4), rerun with the `--verbose` flag for more details. Going on using bundler 2.3.12.
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

## Environment

```
Bundler       2.3.12
  Platforms   ruby, x86_64-linux
Ruby          2.7.5p203 (2021-11-24 revision f69aeb83146be640995753667fdd6c6f157527f5) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.12
  Gem Home    /usr/local/bundle
  Gem Path    /root/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-04-20
Git SHA           75031e03f4
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://nexus.company.com/repository/ruby-gems-group-repo/"

# gem "rails"
```

### Gemfile.lock

```
GEM
  remote: https://nexus.company.com/repository/ruby-gems-group-repo/
  specs:

PLATFORMS
  x86_64-darwin-21
  x86_64-linux

DEPENDENCIES

BUNDLED WITH
   2.3.4
```

**Comment by deivid-rodriguez** [comment]
Yes, this is a known issue, thanks for reporting it because I forgot to do it when we added bundler version locking. We should probably use the default source in the `Gemfile`, rather than what's in `Gem.sources`, I think?

And yes, any exact selection of the bundler version through `BUNDLER_VERSION=<version>` or `bundle _<version>_` completely disables the locking mechanism for the Bundler version 👍.

**Comment by dudarenko-io** [comment]
> We should probably use the default source in the Gemfile, rather than what's in Gem.sources, I think?
Yes, I think bundler should use source from Gemfile if it is defined.

If source is not defined in Gemfile, bundler produce this warning:
```
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
```

**Comment by marwin1991** [comment]
I think I have something similar:

when using:
```
    - gem install -s $RUBYGEMS_REPOSITORY --no-http-proxy gitlab-triage
```
 eveything was okey untill in the scope there was defined variables:

```
    http_proxy: 'x.x.x.x'
    https_proxy: 'x.x.x.x''
    no_proxy: 'a'
    HTTP_PROXY: 'x.x.x.x''
    HTTPS_PROXY: 'x.x.x.x''
    NO_PROXY: 'a'
```

And then this happend:

```
$ gem install --debug --verbose  -s $RUBYGEMS_REPOSITORY --no-http-proxy gitlab-triage
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `IPAddr::InvalidAddressError' at /usr/local/lib/ruby/3.1.0/ipaddr.rb:684 - invalid address: 
Exception `IPAddr::InvalidAddressError' at /usr/local/lib/ruby/3.1.0/ipaddr.rb:684 - invalid address: 
Exception `IPAddr::InvalidAddressError' at /usr/local/lib/ruby/3.1.0/ipaddr.rb:684 - invalid address: 
Exception `Net::HTTPServerException' at /usr/local/lib/ruby/3.1.0/net/http/response.rb:124 - 403 "Forbidden"
Exception `Net::HTTPServerException' at /usr/local/lib/ruby/3.1.0/net/http.rb:1065 - 403 "Forbidden"
ERROR:  While executing gem ... (Net::HTTPServerException)
    403 "Forbidden"
	/usr/local/lib/ruby/3.1.0/net/http/response.rb:124:in `error!'
	/usr/local/lib/ruby/3.1.0/net/http/response.rb:133:in `value'
	/usr/local/lib/ruby/3.1.0/net/http.rb:1020:in `connect'
	/usr/local/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
	/usr/local/lib/ruby/3.1.0/net/http.rb:971:in `start'
	/usr/local/lib/ruby/3.1.0/rubygems/request/http_pool.rb:43:in `setup_connection'
	/usr/local/lib/ruby/3.1.0/rubygems/request/https_pool.rb:7:in `setup_connection'
	/usr/local/lib/ruby/3.1.0/rubygems/request/http_pool.rb:39:in `make_connection'
	/usr/local/lib/ruby/3.1.0/rubygems/request/http_pool.rb:20:in `checkout'
	/usr/local/lib/ruby/3.1.0/rubygems/request.rb:129:in `connection_for'
	/usr/local/lib/ruby/3.1.0/rubygems/request.rb:188:in `perform_request'
	/usr/local/lib/ruby/3.1.0/rubygems/request.rb:154:in `fetch'
	/usr/local/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:309:in `request'
	/usr/local/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:209:in `fetch_http'
	/usr/local/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:248:in `fetch_path'
	/usr/local/lib/ruby/3.1.0/rubygems/source.rb:95:in `dependency_resolver_set'
	/usr/local/lib/ruby/3.1.0/rubygems/resolver/best_set.rb:23:in `block in pick_sets'
	/usr/local/lib/ruby/3.1.0/rubygems/source_list.rb:98:in `each'
	/usr/local/lib/ruby/3.1.0/rubygems/source_list.rb:98:in `each_source'
	/usr/local/lib/ruby/3.1.0/rubygems/resolver/best_set.rb:22:in `pick_sets'
	/usr/local/lib/ruby/3.1.0/rubygems/resolver/best_set.rb:28:in `find_all'
	/usr/local/lib/ruby/3.1.0/rubygems/resolver/installer_set.rb:175:in `find_all'
	/usr/local/lib/ruby/3.1.0/rubygems/resolver/installer_set.rb:61:in `add_always_install'
	/usr/local/lib/ruby/3.1.0/rubygems/dependency_installer.rb:[32](https://gitlab.corp.softnet.com.pl/softnet/cicd/-/jobs/286426#L32)2:in `resolve_dependencies'
	/usr/local/lib/ruby/3.1.0/rubygems/commands/install_command.rb:201:in `install_gem'
	/usr/local/lib/ruby/3.1.0/rubygems/commands/install_command.rb:226:in `block in install_gems'
	/usr/local/lib/ruby/3.1.0/rubygems/commands/install_command.rb:219:in `each'
	/usr/local/lib/ruby/3.1.0/rubygems/commands/install_command.rb:219:in `install_gems'
	/usr/local/lib/ruby/3.1.0/rubygems/commands/install_command.rb:167:in `execute'
	/usr/local/lib/ruby/3.1.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/usr/local/lib/ruby/3.1.0/rubygems/command_manager.rb:180:in `process_args'
	/usr/local/lib/ruby/3.1.0/rubygems/command_manager.rb:1[49](https://gitlab.corp.softnet.com.pl/softnet/cicd/-/jobs/286426#L49):in `run'
	/usr/local/lib/ruby/3.1.0/rubygems/gem_runner.rb:[53](https://gitlab.corp.softnet.com.pl/softnet/cicd/-/jobs/286426#L53):in `run'
	/usr/local/bin/gem:21:in `<main>'
```
```

**Comment by deivid-rodriguez** [comment]
That sounds like an issue with the `--no-proxy` flag, but does not seem related to this particular issue (this one is with `bundle install`). Can you open a separate ticket to track your issue?

**Comment by jasonwbarnett** [comment]
@deivid-rodriguez could you give me some insight into what needs to be changed so I can contribute a fix for this? I'm guessing it's somewhere in [bundler/lib/bundler/self_manager.rb][1], but I would like some more insight from an expert before diving any further.

[1]: https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/self_manager.rb#L112-L119

**Comment by deivid-rodriguez** [comment]
Yep, those are the two places! Basically we need to feed the default source in the Gemfile (`Bundler::SourceList` knows about this) to this source in `SelfManager`.

**Comment by jasonwbarnett** [comment]
@deivid-rodriguez would you recommend using the `Dsl` class directly?

**Comment by deivid-rodriguez** [comment]
In principle, I'd rather reuse `Bundler::Definition#sources` which should have the `SourceList` parsed from the `Gemfile` ready to use, but maybe this happens too early and we haven't yet evaluated the `Gemfile` and we don't even have a `Bundler::Definition` at this point... 🤔 Maybe move that a bit earlier if that's the case.
