### ISSUE TITLE
Error when running 'bundle gem tzinfo' or bundle gem tzinfo-data on Windows

### ISSUE THREAD

**Issue by monicakochofar** [rubygems/rubygems#5501]
My terminal generated the below error report when i ran the above command, this was basically on a fresh install, already ran "gem update --system" as well.

Reason why this command is relevant, is because when i run "rails s" command i also get this error which mentions tzinfo:

C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.4/lib/tzinfo/data_source.rb:159:in 'rescue in create_default_data_source': tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install (TZInfo::DataSourceNotFound)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tzinfo-2.0.4/lib/tzinfo/data_source.rb:156:in `create_default_data_source'

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EBADF: Bad file descriptor
  C:/Ruby31-x64/lib/ruby/3.1.0/reline/ansi.rb:248:in `raw'
  C:/Ruby31-x64/lib/ruby/3.1.0/reline/ansi.rb:248:in `cursor_pos'
  C:/Ruby31-x64/lib/ruby/3.1.0/reline.rb:478:in `may_req_ambiguous_char_width'
  C:/Ruby31-x64/lib/ruby/3.1.0/reline.rb:291:in `inner_readline'
  C:/Ruby31-x64/lib/ruby/3.1.0/reline.rb:267:in `readline'
  C:/Ruby31-x64/lib/ruby/3.1.0/forwardable.rb:238:in `readline'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/line_editor/readline.rb:20:in `readline'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/line_editor.rb:7:in `readline'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/shell/basic.rb:460:in `ask_simply'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/shell/basic.rb:85:in `ask'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:57:in `ask'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli/gem.rb:272:in `ask_and_set_test_framework'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli/gem.rb:96:in `run'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:604:in `run'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
  C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
  C:/RailsInstaller/Ruby2.3.3/bin/bundle:22:in `load'
  C:/RailsInstaller/Ruby2.3.3/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler       2.3.12
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x64-mingw-ucrt]
  Full Path   C:/Ruby31-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.3.12
  Gem Home    C:/Ruby31-x64/lib/ruby/gems/3.1.0
  Gem Path    C:/Users/Lily/.local/share/gem/ruby/3.1.0;C:/Ruby31-x64/lib/ruby/gems/3.1.0
  User Home   C:/Users/Lily
  User Path   C:/Users/Lily/.local/share/gem/ruby/3.1.0
  Bin Dir     C:/Ruby31-x64/bin
Tools
  Git         2.36.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-04-20
Git SHA           75031e03f4
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"
gem 'tzinfo'
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]


# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.2.4)
      actionpack (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.2.4)
      actionpack (= 7.0.2.4)
      activejob (= 7.0.2.4)
      activerecord (= 7.0.2.4)
      activestorage (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.2.4)
      actionpack (= 7.0.2.4)
      actionview (= 7.0.2.4)
      activejob (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.2.4)
      actionview (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.2.4)
      actionpack (= 7.0.2.4)
      activerecord (= 7.0.2.4)
      activestorage (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.2.4)
      activesupport (= 7.0.2.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.2.4)
      activesupport (= 7.0.2.4)
      globalid (>= 0.3.6)
    activemodel (7.0.2.4)
      activesupport (= 7.0.2.4)
    activerecord (7.0.2.4)
      activemodel (= 7.0.2.4)
      activesupport (= 7.0.2.4)
    activestorage (7.0.2.4)
      actionpack (= 7.0.2.4)
      activejob (= 7.0.2.4)
      activerecord (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.2.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    bindex (0.8.1)
    bootsnap (1.11.1)
      msgpack (~> 1.2)
    builder (3.2.4)
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    debug (1.5.0)
      irb (>= 1.3.6)
      reline (>= 0.2.7)
    digest (3.1.0)
    erubi (1.10.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.0.3)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.5.11)
    irb (1.4.1)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.16.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.15.0)
    msgpack (1.5.1)
    net-imap (0.2.3)
      digest
      net-protocol
      strscan
    net-pop (0.1.1)
      digest
      net-protocol
      timeout
    net-protocol (0.1.3)
      timeout
    net-smtp (0.3.1)
      digest
      net-protocol
      timeout
    nio4r (2.5.8)
    nokogiri (1.13.4-x64-mingw-ucrt)
      racc (~> 1.4)
    public_suffix (4.0.7)
    puma (5.6.4)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.3)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (7.0.2.4)
      actioncable (= 7.0.2.4)
      actionmailbox (= 7.0.2.4)
      actionmailer (= 7.0.2.4)
      actionpack (= 7.0.2.4)
      actiontext (= 7.0.2.4)
      actionview (= 7.0.2.4)
      activejob (= 7.0.2.4)
      activemodel (= 7.0.2.4)
      activerecord (= 7.0.2.4)
      activestorage (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      bundler (>= 1.15.0)
      railties (= 7.0.2.4)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (7.0.2.4)
      actionpack (= 7.0.2.4)
      activesupport (= 7.0.2.4)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    regexp_parser (2.3.1)
    reline (0.3.1)
      io-console (~> 0.5)
    rexml (3.2.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    sprockets (4.0.3)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    stimulus-rails (1.0.4)
      railties (>= 6.0.0)
    strscan (3.0.1)
    thor (1.2.1)
    timeout (0.2.0)
    turbo-rails (1.0.1)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.4)

PLATFORMS
  x64-mingw-ucrt

DEPENDENCIES
  bootsnap
  capybara
  debug
  importmap-rails
  jbuilder
  puma (~> 5.0)
  rails (~> 7.0.2, >= 7.0.2.4)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  turbo-rails
  tzinfo
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.12
```

Additional:
Rails version: 7.0.2.4

**Comment by monicakochofar** [comment]
So luckily a few seconds after I posted this, was sent this issue: https://github.com/rubygems/rubygems/issues/5269

issue was actually resolved by doing the below, closing this one now.

in Gemfile, locate the following line:
`gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]`

remove platforms so it looks like so:
`gem "tzinfo-data"`

run bundle update,

try again!
