### ISSUE TITLE
Bundler 2.3.12 fails in `normalize_uri`

### ISSUE THREAD

**Issue by viraptor** [rubygems/rubygems#5502]
### Describe the problem as clearly as you can

When running `bundle install` for an internal project using rails, I get the following exception:

```
Fetching gem metadata from https://rubygems.org/.
Traceback (most recent call last):
        31: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `<main>'
        30: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `load'
        29: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
        28: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        27: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
        26: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
        25: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        24: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
        23: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        22: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        21: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        20: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:254:in `install'
        19: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/settings.rb:131:in `temporary'
        18: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:255:in `block in install'
        17: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli/install.rb:57:in `run'
        16: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/plugin.rb:101:in `gemfile_install'
        15: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/settings.rb:131:in `temporary'
        14: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/plugin.rb:114:in `block in gemfile_install'
        13: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/plugin/installer.rb:36:in `install_definition'
        12: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/definition.rb:180:in `resolve_remotely!'
        11: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/definition.rb:269:in `resolve'
        10: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:23:in `resolve'
         9: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:48:in `start'
         8: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:252:in `verify_gemfile_dependencies_are_found!'
         7: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:252:in `map!'
         6: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:255:in `block in verify_gemfile_dependencies_are_found!'
         5: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:112:in `search_for'
         4: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:175:in `results_for'
         3: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/resolver.rb:167:in `index_for'
         2: from /Users/viraptor/src/marketplace/.bundle/plugin/gems/bootboot-0.2.0/lib/bootboot/ruby_source.rb:20:in `specs'
         1: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/index.rb:9:in `build'
/Users/viraptor/src/marketplace/.bundle/plugin/gems/bootboot-0.2.0/lib/bootboot/ruby_source.rb:29:in `block in specs': undefined method `to_gem_version_with_patchlevel' for #<Bundler::RubyVersion:0x00007fef1113e2c0> (NoMethodError)
        13: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `<main>'
        12: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `load'
        11: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
        10: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:101:in `with_friendly_errors'
         9: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:109:in `rescue in with_friendly_errors'
         8: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:50:in `log_error'
         7: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:72:in `request_issue_report_for'
         6: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/env.rb:22:in `report'
         5: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/env.rb:22:in `each'
         4: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/env.rb:24:in `block in report'
         3: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/settings.rb:187:in `pretty_values_for'
         2: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/settings.rb:304:in `key_for'
         1: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/settings.rb:490:in `key_for'
/Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/settings.rb:508:in `normalize_uri': Gem sources must be absolute. You provided '#bundle_mirror.https://rails-assets.org/'. (ArgumentError)
```

Same gemfile works fine with `2.3.11`.
I don't understand where the `rails-assets.org` entry comes from - it's not mentioned explicitly in the `Gemfile`

### Did you try upgrading rubygems & bundler?

There's no more recent bundler at this point.

### Post steps to reproduce the problem

Unfortunately it's a private project with a quite large Gemfile. I'll try to minimise it and post more information, but maybe the stacktrace is enough this issue.

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Installation

### What actually happened?

exception as above

### If not included with the output of your command, run `bundle env` and paste the output below

Turns out `bundle env` also fails:

```
Traceback (most recent call last):
        19: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `<main>'
        18: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `load'
        17: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
        16: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        15: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
        14: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
        13: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        12: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
        11: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        10: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
         9: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
         8: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli.rb:679:in `env'
         7: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/env.rb:9:in `write'
         6: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/env.rb:22:in `report'
         5: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/env.rb:22:in `each'
         4: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/env.rb:24:in `block in report'
         3: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:187:in `pretty_values_for'
         2: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:304:in `key_for'
         1: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:490:in `key_for'
/Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:508:in `normalize_uri': Gem sources must be absolute. You provided '#bundle_mirror.https://rails-assets.org/'. (ArgumentError)
        13: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `<main>'
        12: from /Users/viraptor/.asdf/installs/ruby/2.7.6/bin/bundle:23:in `load'
        11: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
        10: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:101:in `with_friendly_errors'
         9: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:109:in `rescue in with_friendly_errors'
         8: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:50:in `log_error'
         7: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:72:in `request_issue_report_for'
         6: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/env.rb:22:in `report'
         5: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/env.rb:22:in `each'
         4: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/env.rb:24:in `block in report'
         3: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:187:in `pretty_values_for'
         2: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:304:in `key_for'
         1: from /Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:490:in `key_for'
/Users/viraptor/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/settings.rb:508:in `normalize_uri': Gem sources must be absolute. You provided '#bundle_mirror.https://rails-assets.org/'. (ArgumentError)
```

**Comment by deivid-rodriguez** [comment]
Hi @viraptor!

You're getting two crashes.

The first one is due to an issue introduced with Bundler 2.3.12 where I accidentally removed an internal method that the booboot plugin was using. Bootboot has released 0.2.1 that fixes this and I'm still considering reverting the change anyways.

Then you're getting another crash when reporting the Bundler environment. I think this is due to a bad setting. Can you share your applications `.bundle/config` file (or the one in your users folder, `~/.bundle/config`). Make sure you redact any sensitive information if any.

**Comment by viraptor** [comment]
Ah, I think I see it now - I missed it before because of the uppercase. In my `.bundle/config` I've got a commented out line:
```
#BUNDLE_MIRROR__HTTPS://RAILS___ASSETS__ORG/: "http://localhost:9292"
```
This worked ok in previous versions (the setting was ignored) but in `2.3.12` it looks like the whole line is being parsed?

**Comment by deivid-rodriguez** [comment]
I think nothing has changed regarding parsing settings.

The culprit of your error is what I mentioned first. Upgrade bootboot to 0.2.1 and the error should go away.

The second crash happens because Bundler tries to read the environment in order to print a nicer bug report with helpful information for the first error, but crashes while doing so due to this commented out setting. In Bundler 2.3.11 this was not happening because the first crash was not happening so Bundler was not trying to read settings. But `bundle env` should crash too in 2.3.11 with this configuration.

**Comment by deivid-rodriguez** [comment]
I tried the setting issues all the way back to Bundler 2.0 and every version crashed. Perhaps it was some change in the underlying `uri` library 🤷.
