### ISSUE TITLE
asciidoctor installation issue: Directory not empty

### ISSUE THREAD

**Issue by beniza** [rubygems/rubygems#5556]
```
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /tmp/bundler20220519-29690-zm2gc2asciidoctor-2.0.17
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1459:in `rmdir'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1459:in `block in remove_dir1'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1470:in `platform_support'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1458:in `remove_dir1'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1451:in `remove'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:746:in `block in remove_entry_secure'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1508:in `ensure in postorder_traverse'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1508:in `postorder_traverse'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:744:in `remove_entry_secure'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler.rb:320:in `rm_rf'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:237:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.3.14
  Platforms   ruby, x86_64-linux
Ruby          2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-linux]
  Full Path   /usr/bin/ruby2.7
  Config Dir  /etc
RubyGems      3.1.2
  Gem Home    /var/lib/gems/2.7.0
  Gem Path    /home/salabu/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0
  User Home   /home/salabu
  User Path   /home/salabu/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1f  31 Mar 2020
  Loaded      OpenSSL 1.1.1f  31 Mar 2020
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.25.1
  RVM         not installed
  rsalabuv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-05-18
Git SHA           467ad58a7c
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

# Look in asciidoctor-epub3.gemspec for runtime and development dependencies.
gemspec

if ENV.key? 'ASCIIDOCTOR_VERSION'
  gem 'asciidoctor', ENV['ASCIIDOCTOR_VERSION'], require: false
  # Newer asciidoctor-diagram 1.5.x require asciidoctor >=1.5.7
  gem 'asciidoctor-diagram', '1.5.16', require: false if Gem::Version.new(ENV['ASCIIDOCTOR_VERSION']) < Gem::Version.new('2.0.0')
end

group :optional do
  # epubcheck-ruby might be safe to be converted into runtime dependency, but could have issues when packaged into asciidoctorj-epub3
  gem 'epubcheck-ruby', '~> 4.2.6.0'
  # Kindlegen is unavailable neither for 64-bit MacOS nor for ARM
  gem 'kindlegen', '~> 3.1.0' unless RbConfig::CONFIG['host_os'] =~ /darwin/
end
```

### Gemfile.lock

```
<No /mnt/c/Users/dell/Documents/Personal/Nerveedhi/Gundert/asciidoctor-book-template/asciidoctor-epub3/Gemfile.lock found>
```

### asciidoctor-epub3.gemspec

```ruby
# frozen_string_literal: true

require_relative 'lib/asciidoctor-epub3/version'
require 'open3' unless defined? Open3

Gem::Specification.new do |s|
  s.name = 'asciidoctor-epub3'
  s.version = Asciidoctor::Epub3::VERSION

  s.summary = 'Converts AsciiDoc documents to EPUB3 and KF8/MOBI (Kindle) e-book formats'
  s.description = <<-EOS
An extension for Asciidoctor that converts AsciiDoc documents to EPUB3 and KF8/MOBI (Kindle) e-book archives.
  EOS

  s.authors = ['Dan Allen', 'Sarah White']
  s.email = 'dan@opendevise.com'
  s.homepage = 'https://github.com/asciidoctor/asciidoctor-epub3'
  s.license = 'MIT'

  s.required_ruby_version = '>= 2.4.0'

  files = begin
    (result = Open3.popen3('git ls-files -z') {|_, out| out.read }.split %(\0)).empty? ? Dir['**/*'] : result
  rescue
    Dir['**/*']
  end
  s.files = files.grep %r/^(?:(?:data\/(?:fonts|images|styles)|lib)\/.+|Gemfile|Rakefile|LICENSE|(?:CHANGELOG|NOTICE|README)\.adoc|\.yardopts|#{s.name}\.gemspec)$/
  s.executables = %w(asciidoctor-epub3 adb-push-ebook)
  s.test_files = s.files.grep(/^(?:test|spec|feature)\/.*$/)

  s.require_paths = ['lib']

  s.add_development_dependency 'asciidoctor-diagram', '>= 1.5.0', '< 3.0.0'
  s.add_development_dependency 'asciimath', '~> 2.0'
  s.add_development_dependency 'coderay', '~> 1.1.0'
  s.add_development_dependency 'pygments.rb', '~> 2.3.0'
  s.add_development_dependency 'rake', '~> 13.0.0'
  s.add_development_dependency 'rouge', '~> 3.0'
  s.add_development_dependency 'rspec', '~> 3.11.0'
  s.add_development_dependency 'rubocop', '~> 1.12.1'
  s.add_development_dependency 'rubocop-rake', '~> 0.5.0'
  s.add_development_dependency 'rubocop-rspec', '~> 2.2.0'

  s.add_runtime_dependency 'asciidoctor', '>= 1.5.6', '< 3.0.0'
  s.add_runtime_dependency 'gepub', '~> 1.0.0'
  s.add_runtime_dependency 'mime-types', '~> 3.0'
end
```

**Comment by simi** [comment]
I tried same gemspec/Gemfile resolution locally and it was resolved and installed without any problems. Can you check what's in given folder?

**Comment by deivid-rodriguez** [comment]
We'll be adding some changes to the next version so that this kind of error is more helpful. We would appreciate if you can upgrade and report the new error once we release.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
