### ISSUE TITLE
Permission denied @ rb_sysopen - /home/ubuntu/.rvm/gems/ruby-2.6.5/wrappers/rackup

### ISSUE THREAD

**Issue by alilland** [rubygems/rubygems#5571]
When trying to run bundle install in our production server i received the following error

```
Errno::EACCES: Permission denied @ rb_sysopen - /home/ubuntu/.rvm/gems/ruby-2.6.5/wrappers/rackup
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `initialize'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `open'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `install_file'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:50:in `install'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:23:in `block in install'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:22:in `each'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:22:in `install'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb:15:in `block in <top (required)>'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:371:in `block in run_post_install_hooks'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:370:in `each'
  /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:370:in `run_post_install_hooks'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/rubygems_gem_installer.rb:43:in `install'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:204:in `install'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /home/ubuntu/.rvm/gems/ruby-2.6.5/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler             2.3.14
  Platforms         ruby, x86_64-linux
Ruby                2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
  Full Path         /usr/share/rvm/rubies/ruby-2.6.5/bin/ruby
  Config Dir        /etc
RubyGems            3.0.6
  Gem Home          /home/ubuntu/.rvm/gems/ruby-2.6.5
  Gem Path          /home/ubuntu/.rvm/gems/ruby-2.6.5:/usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0
  User Home         /home/ubuntu
  User Path         /home/ubuntu/.gem/ruby/2.6.0
  Bin Dir           /home/ubuntu/.rvm/gems/ruby-2.6.5/bin
OpenSSL
  Compiled          OpenSSL 1.1.1c  28 May 2019
  Loaded            OpenSSL 1.1.1  11 Sep 2018
  Cert File         /usr/lib/ssl/cert.pem
  Cert Dir          /usr/lib/ssl/certs
Tools
  Git               2.17.1
  RVM               1.29.12 (manual)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-05-18
Git SHA           467ad58a7c
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'http://rubygems.org'

gem 'awesome_print'
gem 'aws-sdk', require: %w[aws-sdk-s3 aws-sdk-ses]
gem 'benchmark-ips'
gem 'benchmark-memory'
gem 'bitly', '~> 1.1.2'
gem 'bunny', '>= 2.9.2'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'carrierwave-mongoid', require: 'carrierwave/mongoid'
gem 'dotenv'
gem 'elasticsearch', '~> 6.1.0'
gem 'faraday', '~> 0.17.1'
gem 'faraday_middleware'
gem 'faraday_middleware-aws-sigv4', require: 'faraday_middleware/aws_sigv4'
gem 'geocoder'
gem 'gibberish'
gem 'grape'
gem 'grape-entity'
gem 'haml'
gem 'hashie'
gem 'humanize'
gem 'jwe', '0.4.0'
gem 'jwt', '2.2.1'
gem 'kaminari', '~> 1.0'
gem 'kaminari-mongoid', '~> 1.0'
gem 'lob'
gem 'mini_magick'
gem 'monetize'
gem 'money'
gem 'mongoid', '~> 6.4'
gem 'mongoid-encrypted-fields'
gem 'mustache'
gem 'parser', '<= 3.0.2', group: :development
gem 'phone'
gem 'postmark', '~>1.21.3'
gem 'prawn'
gem 'prawn-table'
gem 'pry'
gem 'puma'
gem 'rack'
gem 'rack-contrib'
gem 'rack-cors'
gem 'rack-test'
gem 'rake', '~> 13.0.1'
gem 'redis'
gem 'rest-client', require: 'rest_client'
gem 'rspec'
gem 'rubocop', '<= 1.10', group: :development
gem 'rubyXL'
gem 'sanitize', '~> 4.5.0'
gem 'sinatra'
gem 'sneakers'
gem 'symmetric-encryption', '~> 3.9.1'
gem 'tux'
gem 'twilio-ruby'
```

### Gemfile.lock

```
<No /var/www/titan-api/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
Hi! Does it work if you uninstall the `gem-wrappers` gem? If yes, can you report this to the `gem-wrappers` gem? Thanks!

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
