### ISSUE TITLE
Unresolved or ambiguous specs during Gem::Specification.reset warning with plugin

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#5597]
ruby 3.1.1p18 on Mac, rubygems 3.3.15 (full env below)

I'm seeing a bunch of warnings when I try to use a local rubygems plugin. There is nothing special about the plugin, it's just a clock skew checker that you can see at https://github.com/djberg96/skew_guard/blob/main/lib/rubygems_plugin.rb. A regular `gem install` does not emit any warnings:

```
>RUBYOPT=-Ilib gem install sys-admin
/Users/dberger/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1245:in `reset': WARN: Unresolved or ambiguous specs during Gem::Specification.reset: (StructuredWarnings::StandardWarning)
/Users/dberger/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1247:in `block in reset':       rspec (~> 3.9) (StructuredWarnings::StandardWarning)
/Users/dberger/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1251:in `block in reset':       Available/installed versions of this gem: (StructuredWarnings::StandardWarning)
/Users/dberger/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1252:in `block (2 levels) in reset':       - 3.11.0 (StructuredWarnings::StandardWarning)
/Users/dberger/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1252:in `block (2 levels) in reset':       - 3.10.0 (StructuredWarnings::StandardWarning)
/Users/dberger/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1255:in `reset': WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>' (StructuredWarnings::StandardWarning)
/Users/dberger/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1256:in `reset': Please report a bug if this causes problems. (StructuredWarnings::StandardWarning)
```

I tried uninstalling and/or cleaning first, but that had no effect.

```
>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.15
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x86_64-darwin21]
  - INSTALLATION DIRECTORY: /Users/dberger/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /Users/dberger/.gem/ruby/3.1.0
  - RUBY EXECUTABLE: /Users/dberger/.rbenv/versions/3.1.1/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/dberger/.rbenv/versions/3.1.1/bin
  - SPEC CACHE DIRECTORY: /Users/dberger/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/dberger/.rbenv/versions/3.1.1/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-21
  - GEM PATHS:
     - /Users/dberger/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0
     - /Users/dberger/.gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - :install => "-b --conservative --minimal-deps --env-shebang"
     - :sources => ["https://rubygems.org/"]
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/dberger/.rbenv/versions/3.1.1/bin
     - /usr/local/Cellar/rbenv/1.2.0/libexec
     - /usr/local/opt/llvm/bin
     - /Users/dberger/.rbenv/shims
     - /usr/local/opt/icu4c/bin
     - /usr/local/opt/icu4c/sbin
     - /usr/local/opt/postgresql@13/bin
     - /usr/local/sbin
     - /Users/dberger/.rbenv/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/VMware Fusion.app/Contents/Public
     - /Library/TeX/texbin
     - /Library/Apple/usr/bin
     - /Applications/Wireshark.app/Contents/MacOS
     - /usr/local/opt/icu4c/bin
     - /usr/local/opt/icu4c/sbin
     - /usr/local/opt/postgresql@13/bin
     - /usr/local/sbin
     - /Users/dberger/.rbenv/bin
     - /Users/dberger/golang/bin
     - /usr/local/opt/go@1.16/libexec/bin
     - /Users/dberger/golang/bin
     - /usr/local/opt/go@1.16/libexec/bin
 ```

**Comment by djberg96** [comment]
Unrelated, but looking at specification.rb, line 1245, I see this:
```
w = "W" + "ARN"
warn "#{w}: Unresolved or ambiguous specs during Gem::Specification.reset:
```
Someone's gonna have to explain the point of `w = "W" + "ARN"` to me.

**Comment by djberg96** [comment]
Inspecting `unresolved_deps` I see `{"rspec"=><Gem::Dependency type=:runtime name="rspec" requirements="~> 3.9">}`, which is the declaration for the sys-admin gem, but I have rspec 3.11.0 installed, which should match `~> 3.9`, right?

`Gem::Dependency.new('rspec', '~> 3.9').match?('rspec', '3.11') # => true`

**Comment by deivid-rodriguez** [comment]
> Someone's gonna have to explain the point of w = "W" + "ARN" to me.

I have no idea what's the point of that either, feel free to dig further into git history :)

Regarding your issue, I'll have a look!

**Comment by djberg96** [comment]
@deivid-rodriguez https://github.com/rubygems/rubygems/commit/1146b29c07961fb866d469d2515af238e7357825

Short answer: it was written 11 years ago that way to avoid editor highlighting, lol.
