### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by kenaitian** [rubygems/rubygems#5609]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::Package::FormatError: No such file or directory @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/cache/rake-13.0.6.gem
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:612:in `rescue in verify'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:589:in `verify'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:574:in `spec'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/rubygems_integration.rb:209:in `spec_from_gem'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/source/rubygems.rb:167:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:90:in `call'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:259:in `install_in_parallel'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:209:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:89:in `block in run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/process_lock.rb:15:in `lock'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:71:in `run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:23:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/install.rb:62:in `run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:255:in `block in install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/settings.rb:131:in `temporary'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:254:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
Errno::ENOENT: No such file or directory @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/cache/rake-13.0.6.gem
  /Library/Ruby/Site/2.6.0/rubygems/package/file_source.rb:29:in `initialize'
  /Library/Ruby/Site/2.6.0/rubygems/package/file_source.rb:29:in `open'
  /Library/Ruby/Site/2.6.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:593:in `verify'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:574:in `spec'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/rubygems_integration.rb:209:in `spec_from_gem'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/source/rubygems.rb:167:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:90:in `call'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:259:in `install_in_parallel'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:209:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:89:in `block in run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/process_lock.rb:15:in `lock'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:71:in `run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/installer.rb:23:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/install.rb:62:in `run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:255:in `block in install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/settings.rb:131:in `temporary'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:254:in `install'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/ken/.gem/ruby/2.6.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler       2.3.15
  Platforms   ruby, universal-darwin-21
Ruby          2.6.8p205 (2021-07-07 revision 67951) [universal-darwin-21]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.3.15
  Gem Home    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  Gem Path    /Users/ken/.gem/ruby/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/ken
  User Path   /Users/ken/.gem/ruby/2.6.0
  Bin Dir     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.36.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-06-01
Git SHA           e7e41afd92
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "fastlane"

gem "fastlane-plugin-flutter_version", git: "https://github.com/tianhaoz95/fastlane-plugin-flutter-version"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

### Gemfile.lock

```
<No /Users/ken/StudioProjects/lessimp/android/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by deivid-rodriguez** [comment]
Hi @kenaitian, could you copy, not only the error but also the full command that you run, and the full output you got?

**Comment by kenaitian** [comment]
@deivid-rodriguez, you should find the steps taken before the error report template:

1. This was the GitHub Action log:
https://github.com/lessimp/lessimp_logs/blob/main/github_action_log

2. lintOption seems to have suppressed ':app:validateSigningRelease' following the ':app:lintVitalRelease' problem.
3. running the validate_play_store_json_key json_key has confirmed that there may be a ruby/bundle related issue as before - [http://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials](https://www.google.com/url?q=http://docs.fastlane.tools/getting-started/android/setup/%23collect-your-google-credentials&sa=D&source=buganizer&usg=AOvVaw1CftLxnvClpXhcd2LXZCRY):
% fastlane run validate_play_store_json_key json_key:/Users/DevAccount/StudioProjects/lessimp/android/service_account_key.json    
/Library/Ruby/Site/2.6.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem fastlane (>= 0.a) with executable fastlane (Gem::GemNotFoundException)
        from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `activate_bin_path'
        from /usr/local/bin/fastlane:23:in `<main>'
% sudo bundle install
[https://github.com/rubygems/rubygems/issues/5609](https://www.google.com/url?q=https://github.com/rubygems/rubygems/issues/5609&sa=D&source=buganizer&usg=AOvVaw3q5Ut3gJoi5Z2rAFhpnB3r)

**Comment by deivid-rodriguez** [comment]
Thank you @kenaitian, any chance you can share a public GitHub actions log where I can see the problem? That way I can clone the repo and play around to try to fix this.

**Comment by kenaitian** [comment]
@deivid-rodriguez I can VS Live Share the github code (private) and I'm not sure how many components you'd need that since I'm also on a macbook pro. I suspect that the issue lies with the dev environment where it's look for gemfile while ruby and bundle is also affecting fastlane.

The scripts/decrypt_android_secrets.sh and the YAML file on GitHub Actions are already posted here if those two files are what you're looking for: https://github.com/maierj/fastlane-action/issues/90

**Comment by deivid-rodriguez** [comment]
Where are you seeing the problem, locally or in GitHub actions?

**Comment by kenaitian** [comment]
Locally since the yml file run on GitHub Action is supposed to run Fastlane along with the gemfile, ruby and bundle. I thought my macOS would be corrupted and factory reset but still the same issue.

**Comment by deivid-rodriguez** [comment]
None of those errors match the one you reported here, no?

The one in Github Actions seems completely unrelated to RubyGems and Bundler. The one you're getting locally means your Ruby installation (Default Ruby that comes with MacOS) has its home configured to be `/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0`, but that directory (`/System`) in particular is protected by MacOS System Integrity Protection, so you get an operation not permitted error when RubyGems tries to right to it.

This is expected, I recommend you install Ruby using [ruby-build & rbenv](https://github.com/rbenv) or [asdf](https://asdf-vm.com) and try again.

**Comment by kenaitian** [comment]
@deivid-rodriguez ill keep you posted when I use ruby-build & rbenv or asdf the GitHub Action error is related when I executed what the command posted previously as “validate_play_store_json_key json_key:/Users/DevAccount/StudioProjects/lessimp/android/service_account_key.json”

**Comment by deivid-rodriguez** [comment]
> Please note that the GitHub Action error is related, especially when I executed locally as “fastlane run validate_play_store_json_key json_key:/Users/ken/StudioProjects/lessimp/android/service_account_key.json”
>
> GitHub is looking for that service_account_key.json file so to finalize the android deployment to the Play Store but it cannot find it due to the error previously posted above.

I have no idea what all that issue, definitely things completely unrelated to RubyGems. So, yes, it might be related to your issue, but not to our software.

I'll close this for now, but if you still have issues after switching away from your system Ruby let me know.
