### ISSUE TITLE
Bundler fails on travis ci on ruby 2.6.1

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#5616]
Here is the output I have:
```
$ rake test
DEV=1 rake test
rake aborted!
TypeError: superclass mismatch for class Command
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:2:in `<class:Thor>'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:1:in `require_relative'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:1:in `require_relative'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendored_thor.rb:8:in `require_relative'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/vendored_thor.rb:8:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/ui/shell.rb:3:in `require_relative'
/home/travis/.rvm/gems/ruby-2.6.1/gems/bundler-2.3.15/lib/bundler/ui/shell.rb:3:in `<top (required)>'
...
```
Other versions working well

**Comment by deivid-rodriguez** [comment]
Can you link to a public travis CI log?

**Comment by hurricup** [comment]
Unfortunately it's close sourced test. What part do you need?

**Comment by deivid-rodriguez** [comment]
I need a way to reproduce locally, so anything relevant, `Gemfile`, `Gemfile.lock`, `bundle env`, definition of `rake test` task... Ideally a public repository where the issue reproduces.

I suspect this Ruby version includes a very old version of Bundler that used to vendor an old version of Thor where the `Thor::Command` class inherited from a different struct. And somehow both incompatible definitions are getting loaded. Did you try upgrading RubyGems?

**Comment by deivid-rodriguez** [comment]
No problem, thanks to you for reporting the issues you find 👍.
