### ISSUE TITLE
Add an option for satisfying a subset of dependencies from local system

### ISSUE THREAD

**Issue by pravi** [rubygems/rubygems#5657]
Currently `bundle install --local` expect all dependencies to be available locally. In Debian, we try to package as much rubygems as possible but for big packages like gitlab we are sometimes not able to package all dependencies in time. So we want a hybrid approach where gems not available locally only needs to be fetched from rubygems.org. So please add an option like --prefer-local which will take a rubygem installed locally even if a newer version is available from rubygems.org

Without --local option, by default bundler try to fetch newer versions from rubygems.org even if an older version satisfying the requirement in Gemfile is available locally.

In this example Gemfile has re2 ~> 1.2 and re2 1.2.0 is installed locally, it tries to fetch re2 1.4.0 from rubygems.org

```
$ gem list re2

*** LOCAL GEMS ***

re2 (1.2.0)
$ gem list -r re2

*** REMOTE GEMS ***

arbre2 (2.2.4)
digistore24 (0.1.1)
extracare2of (0.3)
foursquare2 (2.0.2)
jqajax_core2 (0.0.82)
motion_require2 (0.4.0)
pcre2 (0.2.0)
rb-pure25519 (1.0.3)
re2 (1.4.0)
re2quire (0.1.0)
require2 (0.0.3)
store2 (0.1.0)
testing_please_ignore2 (0.0.0)
wire2air (0.3.5)
$ cat Gemfile 
source 'https://rubygems.org'

gem 're2', '~> 1.2'

$ bundle install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.3.5
Fetching re2 1.4.0
Installing re2 1.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gitlab/.gem/gems/re2-1.4.0/ext/re2
/usr/bin/ruby3.0 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20220626-39588-iw8ovn.rb extconf.rb
checking for -lstdc++... yes
checking for stdint.h... yes
checking for rb_str_sublen()... yes
checking for -lre2... no
You must have re2 installed and specified with --with-re2-dir, please see
https://github.com/google/re2/wiki/Install
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)3.0
	--with-re2-dir
	--without-re2-dir
	--with-re2-include
	--without-re2-include=${re2-dir}/include
	--with-re2-lib
	--without-re2-lib=${re2-dir}/lib
	--with-stdc++-dir
	--without-stdc++-dir
	--with-stdc++-include
	--without-stdc++-include=${stdc++-dir}/include
	--with-stdc++-lib
	--without-stdc++-lib=${stdc++-dir}/lib
	--with-stdc++lib
	--without-stdc++lib
	--with-stdint-dir
	--without-stdint-dir
	--with-stdint-include
	--without-stdint-include=${stdint-dir}/include
	--with-stdint-lib
	--without-stdint-lib=${stdint-dir}/lib
	--with-re2lib
	--without-re2lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gitlab/.gem/extensions/x86_64-linux/3.0.0/re2-1.4.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gitlab/.gem/gems/re2-1.4.0 for inspection.
Results logged to /var/lib/gitlab/.gem/extensions/x86_64-linux/3.0.0/re2-1.4.0/gem_make.out

  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:95:in `run'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /usr/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:161:in `build_extension'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:192:in `each'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:192:in `build_extensions'
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:847:in `build_extensions'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:204:in
`install'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/worker.rb:62:in `apply_func'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/worker.rb:57:in `block in
process_queue'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in `loop'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in
`process_queue'
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing re2 (1.4.0), and Bundler cannot continue.

In Gemfile:
  re2
```

cc @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
@pravi Please give #5761 a try!

**Comment by pravi** [comment]
@deivid-rodriguez thanks a lot for this and sorry for getting back late in this. I can confirm this is working with a simple Gemfile, will try this with gitlab soon.

```
(debian-sid)pravi@mahishi:/tmp$ cat Gemfile
source "https://rubygems.org"

gem "mini_portile2", "~> 2.8.1"

(debian-sid)pravi@mahishi:/tmp$ bundle install
Fetching gem metadata from https://rubygems.org/....
Resolving dependencies...
Using bundler 2.3.20
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/3.1.0
  /var/lib/gems/3.1.0/build_info
  /var/lib/gems/3.1.0/cache
  /var/lib/gems/3.1.0/doc
  /var/lib/gems/3.1.0/extensions
  /var/lib/gems/3.1.0/gems
  /var/lib/gems/3.1.0/plugins
  /var/lib/gems/3.1.0/specifications
Fetching mini_portile2 2.8.2


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle config set --local path 'vendor/bundle'
      bundle install

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
sudo: a password is required
(debian-sid)pravi@mahishi:/tmp$ bundle install --prefer-local
Resolving dependencies...
Using bundler 2.3.20
Using mini_portile2 2.8.1
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/3.1.0
  /var/lib/gems/3.1.0/build_info
  /var/lib/gems/3.1.0/cache
  /var/lib/gems/3.1.0/doc
  /var/lib/gems/3.1.0/extensions
  /var/lib/gems/3.1.0/gems
  /var/lib/gems/3.1.0/plugins
  /var/lib/gems/3.1.0/specifications
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

```

**Comment by pravi** [comment]
@deivid-rodriguez I have opened #6705 for cases where we need to force an older version via Gemfile.

**Comment by pravi** [comment]
In other cases too, it fails when local version does not match the constraint.

```
Fetching gem metadata from https://rubygems.org/........
Could not find gem 'graphiql-rails (~> 1.8)' in locally installed gems.

The source contains the following gems matching 'graphiql-rails':
  * graphiql-rails-1.4.10

```

**Comment by pravi** [comment]
When a matching version available it takes it (which is half of what we need), and the other half is, if the matching version is not available, it should continue to install it from rubygems.org

**Comment by deivid-rodriguez** [comment]
Right, @pravi, I missed that requirement when implementing `--prefer-local`. Can you reopen this as a bug report against the `--prefer-local` flag, so this doesn't get lost on a closed ticket?

**Comment by deivid-rodriguez** [comment]
Oh, sorry, I just saw that you already did that, thanks!
