### ISSUE TITLE
Bundler 2.3.16 and 2.3.17 raises an error when updating vendor/cache

### ISSUE THREAD

**Issue by no-itsbackpack** [rubygems/rubygems#5675]
### Describe the problem as clearly as you can
`bundle install` and `bundle cache` throws an error when updating the `vendor/cache` after upgrading bundler to `2.3.16`. `bundle install --local` still works and I am guessing it does because it does not call out to `rubygems.org`

### Did you try upgrading rubygems & bundler?

Yes, the bug occurs on `2.3.16` and `2.3.17`

### Which command did you run?

`bundle install` and `bundle cache` both fail 😞 

### What were you expecting to happen?

The command should exit without throwing any error

### What actually happened?

The command exited with an error message

### If not included with the output of your command, run `bundle env` and paste the output below

```
Using maxmind-geoip2 1.1.0
Using mini_portile2 2.8.0
Using minitest-focus 1.3.1
Using minitest-spec-rails 6.1.0
Using minitest-stub-const 0.6
Using mocha 1.14.0
Using mock_redis 0.32.0
Using multi_json 1.15.0
Using mysql2 0.5.4
Using nanoid 2.0.0
Using noticed 1.5.9
Using oauth2 1.4.9
Using rack-protection 2.2.0
Using omniauth 2.1.0
Using omniauth-oauth2 1.7.2
Using omniauth-github 2.0.0
Using omniauth-rails_csrf_protection 1.0.1
Using openssl 3.0.0
Using optimist 3.0.1
Using planetscale 0.3.4
Using pry 0.13.1
Using pry-byebug 3.9.0
Using pry-rails 0.3.9
Using puma 5.6.4
Using pundit 2.2.0
Using pusher-signature 0.1.8
Using pusher 2.0.2
Using pwned 2.4.0
Using rdkafka 0.12.0
Using racecar 2.8.1
Using rack-attack 6.6.1
Using rack-cors 1.1.1
Using rack-proxy 0.7.2
Using rails-reverse-proxy 0.11.0
Using rbtrace 0.4.14
Using redis 4.7.0
Using reverse_markdown 2.1.1
Using roadie 5.0.1
Using roadie-rails 3.0.0
Using rotp 6.2.0
Using rouge 3.29.0
Using rubocop-performance 1.14.2
Using rubocop-rails 2.15.1
Using rubocop-shopify 2.8.0
Using semantic_range 3.0.0
Using sentry-ruby-core 5.3.1
Using sentry-rails 5.3.1
Using sentry-ruby 5.3.1
Using sidekiq 6.5.1
Using sentry-sidekiq 5.3.1
Using shakapacker 6.4.1
Using sidekiq-pro 5.5.1
Using sidekiq-ent 2.5.1
Using sidekiq-logstash 2.0.2
Using webrick 1.7.0
Using sidekiq_alive 2.1.5
Using simplecov-html 0.12.3
Using simplecov_json_formatter 0.1.4
Using simplecov 0.21.2
Using slack-ruby-client 1.0.0
Using tilt 2.0.10
Using yard 0.9.27
Using solargraph 0.45.0
Using sorbet-runtime 0.5.10132
Using stripe 5.55.0
Using stripe-ruby-mock 3.1.0.rc3
Using strong_password 0.0.10
Using vcr 6.1.0
Using webmock 3.14.0
Using workos 2.3.0
Using yajl-ruby 1.4.3
Using zendesk_api 1.36.0
Bundle complete! 106 Gemfile dependencies, 257 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Updating files in vendor/cache
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.pkg.github.com/planetscale/...
--- ERROR REPORT TEMPLATE -------------------------------------------------------

--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `uri' for nil:NilClass

uri = spec.remote.uri
         ^^^^
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/source/rubygems.rb:530:in `download_gem'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/source/rubygems.rb:480:in `fetch_gem'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/runtime.rb:128:in `block in cache'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/runtime.rb:125:in `each'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/runtime.rb:125:in `cache'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/cli/cache.rb:23:in `block in run'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/settings.rb:131:in `temporary'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/cli/cache.rb:22:in `run'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/cli.rb:460:in `cache'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/cli.rb:31:in `dispatch'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/cli.rb:25:in `start'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/exe/bundle:48:in `block in <top (required)>'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.16/exe/bundle:36:in `<top (required)>'
  /Users/francesthai/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
  /Users/francesthai/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'

## Environment

Bundler       2.3.16
  Platforms   ruby, x86_64-darwin-20
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-darwin-20]
  Full Path   /Users/francesthai/.rbenv/versions/3.1.2/bin/ruby
  Config Dir  /Users/francesthai/.rbenv/versions/3.1.2/etc
RubyGems      3.3.7
  Gem Home    /Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  Gem Path    /Users/francesthai/.gem/ruby/3.1.0:/Users/francesthai/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/francesthai
  User Path   /Users/francesthai/.gem/ruby/3.1.0
  Bin Dir     /Users/francesthai/.rbenv/versions/3.1.2/bin
OpenSSL
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   /Users/francesthai/.rbenv/versions/3.1.2/openssl/ssl/cert.pem
  Cert Dir    /Users/francesthai/.rbenv/versions/3.1.2/openssl/ssl/certs
Tools
  Git         2.36.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed


## Bundler Build Metadata


Built At          2022-06-15
Git SHA           324ee6e542
Released Version  true


## Bundler settings


build.mysql2
  Set for your local app (/Users/francesthai/planetscale/api-bb/.bundle/config): "--with-opt-dir=/opt/homebrew/opt/zstd"
  Set for the current user (/Users/francesthai/.bundle/config): "--with-opt-dir=/usr/local/opt/openssl@1.1"
cache_all
  You have not configured a value for `cache_all`
cache_all_platforms
  Set for your local app (/Users/francesthai/planetscale/api-bb/.bundle/config): true
https://rubygems.pkg.github.com/planetscale/
  Set for the current user (/Users/francesthai/.bundle/config): "notfelineit:[REDACTED]"

```

cc @notfelineit

**Comment by no-itsbackpack** [comment]
I did some extra snooping around and found these changes might be causing the bug https://github.com/rubygems/rubygems/pull/5614/files#diff-cae021dce97344756b9347e262ca14ff32d50fdc3b48930398f37a68515afe2eL462-L463. version `2.3.15` had an early return if `spec.remote` was false but that line seems to have been removed in `2.3.16+`

**Comment by 4-Eyes** [comment]
I'm seeing the exact same error when running `bundle update` on `2.3.16+`. It similarly throws the error when it gets to updating the `vendor/cache`.

**Comment by deivid-rodriguez** [comment]
Uggh, thanks for the report. I overlooked something. Let me fix this.

**Comment by deivid-rodriguez** [comment]
#5679 should fix this!
