### ISSUE TITLE
NoMethodError: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by n-rodriguez** [rubygems/rubygems#5685]
Hi there!

I'm working on [rest-client](https://github.com/jbox-web/rest-client) maintenance ([remember me?](https://github.com/rest-client/rest-client/pull/719#issuecomment-772039811) ^^) and I struggle to manage the Windows version of this gem :

```sh
Fetching https://github.com/jbox-web/rest-client.git
[/home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rest-client-f40a0631faa5/rest-client.windows.gemspec] isn't a Gem::Specification (NilClass instead).
--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `name' for nil:NilClass

    data.name
^^^^^
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/stub_specification.rb:155:in `name'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/stub_specification.rb:7:in `from_stub'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source/git.rb:338:in `load_gemspec'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source/path.rb:177:in `block in load_spec_files'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source/path.rb:176:in `each'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source/path.rb:176:in `load_spec_files'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source/git.rb:211:in `load_spec_files'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source/path.rb:107:in `local_specs'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source/git.rb:178:in `specs'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source.rb:58:in `spec_names'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source_map.rb:21:in `block in all_requirements'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source_map.rb:20:in `map'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/source_map.rb:20:in `all_requirements'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:764:in `source_requirements'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:269:in `resolve'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:181:in `resolve_remotely!'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:271:in `resolve_if_needed'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:82:in `block in run'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:12:in `block in lock'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `open'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `lock'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:71:in `run'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:23:in `install'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli/update.rb:78:in `run'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:303:in `block in update'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/settings.rb:131:in `temporary'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:302:in `update'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
  /home/nicolas/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
  /home/nicolas/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
```

I don't know why bundler picks `rest-client.windows.gemspec` in the first place as it should be dynamic : https://github.com/jbox-web/rest-client/blob/master/Gemfile (like in upstream: https://github.com/rest-client/rest-client/blob/master/Gemfile)

I've changed a bit how gemspec are managed to make CI pass :

upstream:
* https://github.com/rest-client/rest-client/blob/master/rest-client.gemspec
* https://github.com/rest-client/rest-client/blob/master/rest-client.windows.gemspec

fork:
* https://github.com/jbox-web/rest-client/blob/wip/load/rest-client.gemspec
* https://github.com/jbox-web/rest-client/blob/wip/load/rest-client.windows.gemspec

Do you know how can I do to manage multiplatform gems? Thank you!

**Comment by n-rodriguez** [comment]
> How can I reproduce it? Just clone the repo and run `bundle install`?

I prepare you a branch ;)

**Comment by n-rodriguez** [comment]
here we are : https://github.com/jbox-web/rest-client/tree/wip/bundler_bug

https://github.com/jbox-web/rest-client/runs/7186046801?check_suite_focus=true#step:3:59

**Comment by n-rodriguez** [comment]
To workaround this bug and make CI pass on master branch I've duplicated `rest-client.gemspec` in `rest-client.windows.gemspec` and I mv the file before calling bundler : https://github.com/jbox-web/rest-client/blob/master/.github/workflows/ci.yml#L53

**Comment by deivid-rodriguez** [comment]
Hi!

I can't reproduce the original error in this ticket, but judging from the `[/home/nicolas/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rest-client-f40a0631faa5/rest-client.windows.gemspec] isn't a Gem::Specification (NilClass instead).` message, I guess there was an error in the gemspec file.

Later you provided a repro at https://github.com/jbox-web/rest-client/runs/7186046801?check_suite_focus=true#step:3:59. But that error is expected, because there's no `gemspec` named `rest-client.windows`. I think it's a bit confusing but the documentation for the [gemspec directive](https://bundler.io/v2.3/man/gemfile.5.html#GEMSPEC) explains it.

There's two related options:

* The `:name` option controls the name of the gemspec that gets loaded, namely, the `Gem::Specification#name` attribute. This is useful for monorepo's with many gems.
* The `:glob` option controls the name of the gemspec file that get loaded. This is useful for a situation like yours.

Let me know if things work if you switch to using the `:glob` option!

**Comment by n-rodriguez** [comment]
@deivid-rodriguez  thank you!
