### ISSUE TITLE
`bundle package --all-platforms` breaks with Nokogiri installed

### ISSUE THREAD

**Issue by emmahsax** [rubygems/rubygems#5688]
### Describe the problem as clearly as you can

With Bundler version 2.3.17 and Ruby 3.1.2, I am now getting an error running `bundle package --all-platforms`. I have tried it with multiple different `Gemfile`s, and they all react the same way, **as long as Nokogiri (specifically version 1.13.6) is installed**.

> NOTE: If Nokogiri is **not** installed, then the command works properly

```
$ bundle package --all-platforms
Using concurrent-ruby 1.1.10
Using i18n 1.10.0
.
.
.
Using nokogiri 1.13.6 (arm64-darwin)
.
.
.
Using regexp_parser 2.5.0
Using rubocop-ast 1.18.0
Using ruby-progressbar 1.11.0
Using rubocop 1.31.1
Using webrick 1.7.0
Bundle complete! 18 Gemfile dependencies, 71 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
Updating files in vendor/cache
Fetching gem metadata from https://rubygems.org/.........
--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `fetch_platform' for #<Gem::Specification:0x000000010a342ac8 @cache_file=nil, @original_platform="ruby", @installed_by_version=nil, @autorequire=nil, @date=2022-05-08 00:00:00 UTC, @description="Nokogiri (鋸) makes it easy and painless to work with XML and HTML from Ruby. It provides a\nsensible, easy-to-understand API for reading, writing, modifying, and querying documents. It is\nfast and standards-compliant by relying on native parsers like libxml2 (C) and xerces (Java).\n", @email="nokogiri-talk@googlegroups.com", @homepage="https://nokogiri.org", @name="nokogiri", @post_install_message=nil, @signing_key=nil, @summary="Nokogiri (鋸) makes it easy and painless to work with XML and HTML from Ruby.", @version=#<Gem::Version "1.13.6">, @authors=["Mike Dalessio", "Aaron Patterson", "Yoko Harada", "Akinori MUSHA", "John Shahid", "Karol Bucek", "Sam Ruby", "Craig Barnes", "Stephen Checkoway", "Lars Kanis", "Sergio Arbeo", "Timothy Elliott", "Nobuyoshi Nakada"], @bindir="bin", @cert_chain=[], @dependencies=[<Gem::Dependency type=:runtime name="mini_portile2" requirements="~> 2.8.0">, <Gem::Dependency type=:runtime name="racc" requirements="~> 1.4">, <Gem::Dependency type=:development name="bundler" requirements="~> 2.2">, <Gem::Dependency type=:development name="hoe-markdown" requirements="~> 1.4">, <Gem::Dependency type=:development name="minitest" requirements="~> 5.15">, <Gem::Dependency type=:development name="minitest-reporters" requirements="~> 1.4">, <Gem::Dependency type=:development name="rake" requirements="~> 13.0">, <Gem::Dependency type=:development name="rake-compiler" requirements="= 1.1.7">, <Gem::Dependency type=:development name="rake-compiler-dock" requirements="~> 1.2">, <Gem::Dependency type=:development name="rdoc" requirements="~> 6.3">, <Gem::Dependency type=:development name="rexical" requirements="~> 1.0.7">, <Gem::Dependency type=:development name="rubocop" requirements="~> 1.28, >= 1.28.2">, <Gem::Dependency type=:development name="rubocop-minitest" requirements="~> 0.17">, <Gem::Dependency type=:development name="rubocop-performance" requirements="~> 1.12">, <Gem::Dependency type=:development name="rubocop-rake" requirements="~> 0.6">, <Gem::Dependency type=:development name="rubocop-shopify" requirements="~> 2.3">, <Gem::Dependency type=:development name="ruby_memcheck" requirements="~> 1.0">, <Gem::Dependency type=:development name="simplecov" requirements="~> 0.21">], @executables=["nokogiri"], @extensions=["ext/nokogiri/extconf.rb"], @extra_rdoc_files=["ext/nokogiri/gumbo.c", "ext/nokogiri/html4_document.c", "ext/nokogiri/html4_element_description.c", "ext/nokogiri/html4_entity_lookup.c", "ext/nokogiri/html4_sax_parser_context.c", "ext/nokogiri/html4_sax_push_parser.c", "ext/nokogiri/libxml2_backwards_compat.c", "ext/nokogiri/nokogiri.c", "ext/nokogiri/test_global_handlers.c", "ext/nokogiri/xml_attr.c", "ext/nokogiri/xml_attribute_decl.c", "ext/nokogiri/xml_cdata.c", "ext/nokogiri/xml_comment.c", "ext/nokogiri/xml_document.c", "ext/nokogiri/xml_document_fragment.c", "ext/nokogiri/xml_dtd.c", "ext/nokogiri/xml_element_content.c", "ext/nokogiri/xml_element_decl.c", "ext/nokogiri/xml_encoding_handler.c", "ext/nokogiri/xml_entity_decl.c", "ext/nokogiri/xml_entity_reference.c", "ext/nokogiri/xml_namespace.c", "ext/nokogiri/xml_node.c", "ext/nokogiri/xml_node_set.c", "ext/nokogiri/xml_processing_instruction.c", "ext/nokogiri/xml_reader.c", "ext/nokogiri/xml_relax_ng.c", "ext/nokogiri/xml_sax_parser.c", "ext/nokogiri/xml_sax_parser_context.c", "ext/nokogiri/xml_sax_push_parser.c", "ext/nokogiri/xml_schema.c", "ext/nokogiri/xml_syntax_error.c", "ext/nokogiri/xml_text.c", "ext/nokogiri/xml_xpath_context.c", "ext/nokogiri/xslt_stylesheet.c", "README.md"], @files=["Gemfile", "LICENSE-DEPENDENCIES.md", "LICENSE.md", "README.md", "bin/nokogiri", "dependencies.yml", "ext/nokogiri/depend", "ext/nokogiri/extconf.rb", "ext/nokogiri/gumbo.c", "ext/nokogiri/html4_document.c", "ext/nokogiri/html4_element_description.c", "ext/nokogiri/html4_entity_lookup.c", "ext/nokogiri/html4_sax_parser_context.c", "ext/nokogiri/html4_sax_push_parser.c", "ext/nokogiri/libxml2_backwards_compat.c", "ext/nokogiri/nokogiri.c", "ext/nokogiri/nokogiri.h", "ext/nokogiri/test_global_handlers.c", "ext/nokogiri/xml_attr.c", "ext/nokogiri/xml_attribute_decl.c", "ext/nokogiri/xml_cdata.c", "ext/nokogiri/xml_comment.c", "ext/nokogiri/xml_document.c", "ext/nokogiri/xml_document_fragment.c", "ext/nokogiri/xml_dtd.c", "ext/nokogiri/xml_element_content.c", "ext/nokogiri/xml_element_decl.c", "ext/nokogiri/xml_encoding_handler.c", "ext/nokogiri/xml_entity_decl.c", "ext/nokogiri/xml_entity_reference.c", "ext/nokogiri/xml_namespace.c", "ext/nokogiri/xml_node.c", "ext/nokogiri/xml_node_set.c", "ext/nokogiri/xml_processing_instruction.c", "ext/nokogiri/xml_reader.c", "ext/nokogiri/xml_relax_ng.c", "ext/nokogiri/xml_sax_parser.c", "ext/nokogiri/xml_sax_parser_context.c", "ext/nokogiri/xml_sax_push_parser.c", "ext/nokogiri/xml_schema.c", "ext/nokogiri/xml_syntax_error.c", "ext/nokogiri/xml_text.c", "ext/nokogiri/xml_xpath_context.c", "ext/nokogiri/xslt_stylesheet.c", "gumbo-parser/CHANGES.md", "gumbo-parser/Makefile", "gumbo-parser/THANKS", "gumbo-parser/src/Makefile", "gumbo-parser/src/README.md", "gumbo-parser/src/ascii.c", "gumbo-parser/src/ascii.h", "gumbo-parser/src/attribute.c", "gumbo-parser/src/attribute.h", "gumbo-parser/src/char_ref.c", "gumbo-parser/src/char_ref.h", "gumbo-parser/src/char_ref.rl", "gumbo-parser/src/error.c", "gumbo-parser/src/error.h", "gumbo-parser/src/foreign_attrs.c", "gumbo-parser/src/foreign_attrs.gperf", "gumbo-parser/src/gumbo.h", "gumbo-parser/src/insertion_mode.h", "gumbo-parser/src/macros.h", "gumbo-parser/src/parser.c", "gumbo-parser/src/parser.h", "gumbo-parser/src/replacement.h", "gumbo-parser/src/string_buffer.c", "gumbo-parser/src/string_buffer.h", "gumbo-parser/src/string_piece.c", "gumbo-parser/src/svg_attrs.c", "gumbo-parser/src/svg_attrs.gperf", "gumbo-parser/src/svg_tags.c", "gumbo-parser/src/svg_tags.gperf", "gumbo-parser/src/tag.c", "gumbo-parser/src/tag_lookup.c", "gumbo-parser/src/tag_lookup.gperf", "gumbo-parser/src/tag_lookup.h", "gumbo-parser/src/token_buffer.c", "gumbo-parser/src/token_buffer.h", "gumbo-parser/src/token_type.h", "gumbo-parser/src/tokenizer.c", "gumbo-parser/src/tokenizer.h", "gumbo-parser/src/tokenizer_states.h", "gumbo-parser/src/utf8.c", "gumbo-parser/src/utf8.h", "gumbo-parser/src/util.c", "gumbo-parser/src/util.h", "gumbo-parser/src/vector.c", "gumbo-parser/src/vector.h", "lib/nokogiri.rb", "lib/nokogiri/class_resolver.rb", "lib/nokogiri/css.rb", "lib/nokogiri/css/node.rb", "lib/nokogiri/css/parser.rb", "lib/nokogiri/css/parser.y", "lib/nokogiri/css/parser_extras.rb", "lib/nokogiri/css/syntax_error.rb", "lib/nokogiri/css/tokenizer.rb", "lib/nokogiri/css/tokenizer.rex", "lib/nokogiri/css/xpath_visitor.rb", "lib/nokogiri/decorators/slop.rb", "lib/nokogiri/extension.rb", "lib/nokogiri/gumbo.rb", "lib/nokogiri/html.rb", "lib/nokogiri/html4.rb", "lib/nokogiri/html4/builder.rb", "lib/nokogiri/html4/document.rb", "lib/nokogiri/html4/document_fragment.rb", "lib/nokogiri/html4/element_description.rb", "lib/nokogiri/html4/element_description_defaults.rb", "lib/nokogiri/html4/entity_lookup.rb", "lib/nokogiri/html4/sax/parser.rb", "lib/nokogiri/html4/sax/parser_context.rb", "lib/nokogiri/html4/sax/push_parser.rb", "lib/nokogiri/html5.rb", "lib/nokogiri/html5/document.rb", "lib/nokogiri/html5/document_fragment.rb", "lib/nokogiri/html5/node.rb", "lib/nokogiri/jruby/dependencies.rb", "lib/nokogiri/syntax_error.rb", "lib/nokogiri/version.rb", "lib/nokogiri/version/constant.rb", "lib/nokogiri/version/info.rb", "lib/nokogiri/xml.rb", "lib/nokogiri/xml/attr.rb", "lib/nokogiri/xml/attribute_decl.rb", "lib/nokogiri/xml/builder.rb", "lib/nokogiri/xml/cdata.rb", "lib/nokogiri/xml/character_data.rb", "lib/nokogiri/xml/document.rb", "lib/nokogiri/xml/document_fragment.rb", "lib/nokogiri/xml/dtd.rb", "lib/nokogiri/xml/element_content.rb", "lib/nokogiri/xml/element_decl.rb", "lib/nokogiri/xml/entity_decl.rb", "lib/nokogiri/xml/entity_reference.rb", "lib/nokogiri/xml/namespace.rb", "lib/nokogiri/xml/node.rb", "lib/nokogiri/xml/node/save_options.rb", "lib/nokogiri/xml/node_set.rb", "lib/nokogiri/xml/notation.rb", "lib/nokogiri/xml/parse_options.rb", "lib/nokogiri/xml/pp.rb", "lib/nokogiri/xml/pp/character_data.rb", "lib/nokogiri/xml/pp/node.rb", "lib/nokogiri/xml/processing_instruction.rb", "lib/nokogiri/xml/reader.rb", "lib/nokogiri/xml/relax_ng.rb", "lib/nokogiri/xml/sax.rb", "lib/nokogiri/xml/sax/document.rb", "lib/nokogiri/xml/sax/parser.rb", "lib/nokogiri/xml/sax/parser_context.rb", "lib/nokogiri/xml/sax/push_parser.rb", "lib/nokogiri/xml/schema.rb", "lib/nokogiri/xml/searchable.rb", "lib/nokogiri/xml/syntax_error.rb", "lib/nokogiri/xml/text.rb", "lib/nokogiri/xml/xpath.rb", "lib/nokogiri/xml/xpath/syntax_error.rb", "lib/nokogiri/xml/xpath_context.rb", "lib/nokogiri/xslt.rb", "lib/nokogiri/xslt/stylesheet.rb", "lib/xsd/xmlparser/nokogiri.rb", "patches/libxml2/0001-Remove-script-macro-support.patch", "patches/libxml2/0002-Update-entities-to-remove-handling-of-ssi.patch", "patches/libxml2/0003-libxml2.la-is-in-top_builddir.patch", "patches/libxml2/0004-use-glibc-strlen.patch", "patches/libxml2/0005-avoid-isnan-isinf.patch", "patches/libxml2/0006-update-automake-files-for-arm64.patch", "patches/libxml2/0008-htmlParseComment-handle-abruptly-closed-comments.patch", "patches/libxml2/0009-allow-wildcard-namespaces.patch", "patches/libxslt/0001-update-automake-files-for-arm64.patch", "ports/archives/libxml2-2.9.14.tar.xz", "ports/archives/libxslt-1.1.35.tar.xz"], @licenses=["MIT"], @metadata={"homepage_uri"=>"https://nokogiri.org", "bug_tracker_uri"=>"https://github.com/sparklemotion/nokogiri/issues", "documentation_uri"=>"https://nokogiri.org/rdoc/index.html", "changelog_uri"=>"https://nokogiri.org/CHANGELOG.html", "source_code_uri"=>"https://github.com/sparklemotion/nokogiri", "rubygems_mfa_required"=>"true"}, @platform="ruby", @rdoc_options=["--main", "README.md"], @require_paths=["lib"], @required_ruby_version=#<Gem::Requirement:0x000000010a2f8f90 @requirements=[[">=", #<Gem::Version "2.6.0">]]>, @required_rubygems_version=#<Gem::Requirement:0x000000010a2f8450 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="3.3.5", @specification_version=4, @test_files=[], @new_platform="ruby", @full_name="nokogiri-1.13.6", @source=#<Bundler::Source::Rubygems:0x3280 rubygems repository https://rubygems.org/ or installed locally> nokogiri-1.13.6>
Did you mean?  match_platform
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2111:in `method_missing'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/source/rubygems.rb:466:in `fetch_gem'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/runtime.rb:128:in `block in cache'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/runtime.rb:125:in `each'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/runtime.rb:125:in `cache'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/cache.rb:23:in `block in run'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/settings.rb:131:in `temporary'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/cache.rb:22:in `run'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:464:in `cache'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:31:in `dispatch'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:25:in `start'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
  /Users/emmasax/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
  /Users/emmasax/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'

## Environment

Bundler       2.3.17
  Platforms   ruby, arm64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [arm64-darwin-21]
  Full Path   /Users/emmasax/.rbenv/versions/3.1.2/bin/ruby
  Config Dir  /Users/emmasax/.rbenv/versions/3.1.2/etc
RubyGems      3.3.7
  Gem Home    /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  Gem Path    /Users/emmasax/.gem/ruby/3.1.0:/Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/emmasax
  User Path   /Users/emmasax/.gem/ruby/3.1.0
  Bin Dir     /Users/emmasax/.rbenv/versions/3.1.2/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   /Users/emmasax/.rbenv/versions/3.1.2/openssl/ssl/cert.pem
  Cert Dir    /Users/emmasax/.rbenv/versions/3.1.2/openssl/ssl/certs
Tools         
  Git         2.36.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed

## Bundler Build Metadata

Built At          2022-06-29
Git SHA           539b20c172
Released Version  true

## Bundler settings

cache_all
  You have not configured a value for `cache_all`

## Gemfile

### Gemfile

# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails'
.
.
.

group :test, :development do
  gem 'html-proofer' # << This is what installs Nokogiri here
  gem 'mdl'
  gem 'rubocop'
end

### Gemfile.lock

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.0.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    .
    .
    .
    nokogiri (1.13.6)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.6-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.6-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.6-x86_64-linux)
      racc (~> 1.4)
    parallel (1.22.1)
    parser (3.1.2.0)
      ast (~> 2.4.1)
    .
    .
    .
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    unicode-display_width (1.8.0)
    webrick (1.7.0)
    yell (2.2.2)

PLATFORMS
  arm64-darwin
  ruby
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  html-proofer
  mdl
  rubocop

BUNDLED WITH
   2.3.17

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60fetch_platform%27+for+%23%3CGem++Specification+0x000000010a342ac8+%40cache_fil...1.13.6%22%2C+%40source%3D%23%3CBundler++Source++Rubygems+0x3280+rubygems+repository+https+%2F%2Frubygems.org%2F+or+installed+locally%3E+nokogiri-1.13.6%3E&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

```

### Did you try upgrading rubygems & bundler?

Yes, I am on the latest version of RubyGems and Bundler.

### Post steps to reproduce the problem

1. Grab any `Gemfile` that will result in Nokogiri being installed (either directly or indirectly)
2. Switch to the latest version of Ruby 3.1.2 and of Bundler 2.3.17
3. Run `bundle install`
4. Run `bundle package --all-platforms` and it should fail

### Which command did you run?

```
bundle package --all-platforms
```

### What were you expecting to happen?

No big yellow error.

### What actually happened?

A big yellow error.

## Environment

```
Bundler       2.3.17
  Platforms   ruby, arm64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [arm64-darwin-21]
  Full Path   /Users/emmasax/.rbenv/versions/3.1.2/bin/ruby
  Config Dir  /Users/emmasax/.rbenv/versions/3.1.2/etc
RubyGems      3.3.17
  Gem Home    /Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  Gem Path    /Users/emmasax/.gem/ruby/3.1.0:/Users/emmasax/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/emmasax
  User Path   /Users/emmasax/.gem/ruby/3.1.0
  Bin Dir     /Users/emmasax/.rbenv/versions/3.1.2/bin
Tools         
  Git         2.37.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-06-29
Git SHA           539b20c172
Released Version  true
```

## Bundler settings

```
cache_all
  Set for your local app (/Users/emmasax/projects/PROJECT-NAME/.bundle/config): false
```

**Comment by deivid-rodriguez** [comment]
@emmahsax I'm pretty sure this is the same underlying issue as #5675, which is already fixed in the main branch. Can you try cloning the repository, switching to the `bundler/` folder and running `bin/rake install` from there to install the development version 2.4.0.dev? I think it should fix the issue for you.

**Comment by emmahsax** [comment]
I got an error running the `bin/rake` file:
```
$ bash bin/rake
bin/rake: line 4: require_relative: command not found
bin/rake: line 6: syntax error near unexpected token `('
bin/rake: line 6: `if ["dev:deps", "dev:frozen_deps", "spec:deps", "spec:parallel_deps"].include?(ARGV[0])'
```

But I think you are right that the next release of Bundler will fix my issue. Thank you!

**Comment by deivid-rodriguez** [comment]
Oh, `bin/rake` is a ruby script, you can't run it using bash! Run `bin/rake install` directly if your system supports shebangs, otherwise run `ruby bin/rake install`.

**Comment by emmahsax** [comment]
@deivid-rodriguez Yes, you're right! The dev version of Bundler fixed the issue. Hopefully a new version will be released to RubyGems soon. Thank you!

**Comment by deivid-rodriguez** [comment]
I will release a new version next Wednesday!
