### ISSUE TITLE
undefined method 'version' - @name="libv8-node

### ISSUE THREAD

**Issue by TeldridgeLDN** [rubygems/rubygems#5849]
### Describe the problem as clearly as you can

Looking to install Jekyll Theme template https://github.com/TeldridgeLDN/TeldridgeLDN.github.io

Mac OSx Monterey

Step 1. installed Ruby 3.1.0 using home-brew
Step 2. cd TeldridgeLDN.github.io 
Step 2. installed latest rubygems using gem update --system
Step 3. Error when running bundle install

### Did you try upgrading rubygems & bundler?

Yes rubygems is latest version

bundle update --bundler returns an error

### Which command did you run?

bundle install

### What were you expecting to happen?

to install bundle

### What actually happened?

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `version' for #<Bundler::IncompleteSpecification:0x0000000111a87408 @name="libv8-node", @platform=nil>

[s.version, platform_string == RUBY ? NULL : platform_string]
  ^^^^^^^^
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/index.rb:84:in `block in sort_specs'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/index.rb:82:in `each'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/index.rb:82:in `sort_by'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/index.rb:82:in `sort_specs'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:159:in `lookup'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:184:in `block in tsort_each_child'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:182:in `each'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:182:in `tsort_each_child'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:415:in `call'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:168:in `block in tsort_each_node'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:168:in `each'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:168:in `tsort_each_node'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:347:in `call'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:176:in `each'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:176:in `to_a'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:176:in `tsort'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/tsort/lib/tsort.rb:152:in `tsort'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:143:in `sorted'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/spec_set.rb:135:in `each'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:243:in `ensure_specs_are_compatible!'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:83:in `block in run'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `open'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `lock'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:71:in `run'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:23:in `install'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli/update.rb:78:in `run'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:305:in `block in update'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/settings.rb:132:in `temporary'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:304:in `update'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
  /usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/exe/bundle:48:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.20/exe/bundle:36:in `<top (required)>'
  /usr/local/lib/ruby/gems/3.1.0/bin/bundle:25:in `load'
  /usr/local/lib/ruby/gems/3.1.0/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.3.20
  Platforms   ruby, x86_64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-darwin-21]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/3.1.2/etc
RubyGems      3.3.20
  Gem Home    /usr/local/lib/ruby/gems/3.1.0
  Gem Path    /Users/tomeldridge/.gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/tomeldridge
  User Path   /Users/tomeldridge/.gem/ruby/3.1.0
  Bin Dir     /usr/local/lib/ruby/gems/3.1.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1q  5 Jul 2022
  Cert File   /usr/local/etc/openssl@1.1/cert.pem
  Cert Dir    /usr/local/etc/openssl@1.1/certs
Tools         
  Git         2.37.2
  RVM         not installed
  rbenv       not installed
  chruby      Restored session: Fri 19 Aug 2022 17:14:47 BST

Gem.ruby      /usr/local/opt/ruby/bin/ruby
bundle #!     /usr/local/Cellar/ruby/3.1.2/bin/ruby

```

## Bundler Build Metadata

```
Built At          2022-08-10
Git SHA           4fd2813f54
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-imagemagick'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'httparty'
    gem 'feedjira'
end

gem "mini_racer", "~> 0.6.3"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.1.6.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    bibtex-ruby (6.0.0)
      latex-decode (~> 0.0)
    citeproc (1.0.10)
      namae (~> 1.0)
    citeproc-ruby (1.1.14)
      citeproc (~> 1.0, >= 1.0.9)
      csl (~> 1.6)
    colorator (1.1.0)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    csl (1.6.0)
      namae (~> 1.0)
      rexml
    csl-styles (1.0.1.11)
      csl (~> 1.0)
    cssminify2 (2.0.1)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    execjs (2.8.1)
    feedjira (3.2.1)
      loofah (>= 2.3.1)
      sax-machine (>= 1.0)
    ffi (1.15.5)
    forwardable-extended (2.6.0)
    gemoji (3.0.1)
    html-pipeline (2.14.2)
      activesupport (>= 2)
      nokogiri (>= 1.4)
    htmlcompressor (0.4.0)
    http_parser.rb (0.8.0)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.2)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-archives (2.2.1)
      jekyll (>= 3.6, < 5.0)
    jekyll-diagrams (0.10.0)
      jekyll (>= 3.8, < 5.0)
    jekyll-email-protect (1.1.0)
    jekyll-feed (0.16.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-imagemagick (1.4.0)
      jekyll (>= 3.4)
    jekyll-minifier (0.1.10)
      cssminify2 (~> 2.0)
      htmlcompressor (~> 0.4)
      jekyll (>= 3.5)
      json-minify (~> 0.0.3)
      uglifier (~> 4.1)
    jekyll-paginate-v2 (3.0.0)
      jekyll (>= 3.0, < 5.0)
    jekyll-sass-converter (2.2.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-scholar (7.1.0)
      bibtex-ruby (~> 6.0)
      citeproc-ruby (~> 1.0)
      csl-styles (~> 1.0)
      jekyll (~> 4.0)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-target-blank (2.0.0)
      jekyll (>= 3.0, < 5.0)
      nokogiri (~> 1.10)
    jekyll-twitter-plugin (2.1.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    jemoji (0.12.0)
      gemoji (~> 3.0)
      html-pipeline (~> 2.2)
      jekyll (>= 3.0, < 5.0)
    json (2.6.2)
    json-minify (0.0.3)
      json (> 0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    latex-decode (0.4.0)
    libv8-node (16.10.0.0-arm64-darwin)
    libv8-node (16.10.0.0-x86_64-darwin)
    libv8-node (16.10.0.0-x86_64-linux)
    libv8-node (16.10.0.0-x86_64-linux-musl)
    liquid (4.0.3)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.18.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mercenary (0.4.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    mini_racer (0.6.3)
      libv8-node (~> 16.10.0.0)
    minitest (5.16.3)
    multi_xml (0.6.0)
    namae (1.1.1)
    nokogiri (1.13.8-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.8-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.8-x86_64-linux)
      racc (~> 1.4)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.7)
    racc (1.6.0)
    rb-fsevent (0.11.1)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.30.0)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    sax-machine (1.3.2)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (1.8.0)
    unicode_utils (1.4.0)
    webrick (1.7.0)
    zeitwerk (2.6.0)

PLATFORMS
  universal-darwin-21
  x86_64-linux

DEPENDENCIES
  feedjira
  httparty
  jekyll
  jekyll-archives
  jekyll-diagrams
  jekyll-email-protect
  jekyll-feed
  jekyll-imagemagick
  jekyll-minifier
  jekyll-paginate-v2
  jekyll-scholar
  jekyll-sitemap
  jekyll-target-blank
  jekyll-twitter-plugin
  jemoji
  mini_racer
  unicode_utils
  webrick

BUNDLED WITH
   2.3.20
```

--- TEMPLATE END ---------

## Environment

```
Bundler       2.3.20
  Platforms   ruby, x86_64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-darwin-21]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/3.1.2/etc
RubyGems      3.3.20
  Gem Home    /usr/local/lib/ruby/gems/3.1.0
  Gem Path    /Users/tomeldridge/.gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/tomeldridge
  User Path   /Users/tomeldridge/.gem/ruby/3.1.0
  Bin Dir     /usr/local/lib/ruby/gems/3.1.0/bin
Tools         
  Git         2.37.2
  RVM         not installed
  rbenv       not installed
  chruby      Restored session: Fri 19 Aug 2022 17:27:30 BST

Gem.ruby      /usr/local/opt/ruby/bin/ruby
bundle #!     /usr/local/Cellar/ruby/3.1.2/bin/ruby

```

## Bundler Build Metadata

```
Built At          2022-08-10
Git SHA           4fd2813f54
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-imagemagick'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'httparty'
    gem 'feedjira'
end

gem "mini_racer", "~> 0.6.3"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.1.6.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    bibtex-ruby (6.0.0)
      latex-decode (~> 0.0)
    citeproc (1.0.10)
      namae (~> 1.0)
    citeproc-ruby (1.1.14)
      citeproc (~> 1.0, >= 1.0.9)
      csl (~> 1.6)
    colorator (1.1.0)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    csl (1.6.0)
      namae (~> 1.0)
      rexml
    csl-styles (1.0.1.11)
      csl (~> 1.0)
    cssminify2 (2.0.1)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    execjs (2.8.1)
    feedjira (3.2.1)
      loofah (>= 2.3.1)
      sax-machine (>= 1.0)
    ffi (1.15.5)
    forwardable-extended (2.6.0)
    gemoji (3.0.1)
    html-pipeline (2.14.2)
      activesupport (>= 2)
      nokogiri (>= 1.4)
    htmlcompressor (0.4.0)
    http_parser.rb (0.8.0)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.2)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-archives (2.2.1)
      jekyll (>= 3.6, < 5.0)
    jekyll-diagrams (0.10.0)
      jekyll (>= 3.8, < 5.0)
    jekyll-email-protect (1.1.0)
    jekyll-feed (0.16.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-imagemagick (1.4.0)
      jekyll (>= 3.4)
    jekyll-minifier (0.1.10)
      cssminify2 (~> 2.0)
      htmlcompressor (~> 0.4)
      jekyll (>= 3.5)
      json-minify (~> 0.0.3)
      uglifier (~> 4.1)
    jekyll-paginate-v2 (3.0.0)
      jekyll (>= 3.0, < 5.0)
    jekyll-sass-converter (2.2.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-scholar (7.1.0)
      bibtex-ruby (~> 6.0)
      citeproc-ruby (~> 1.0)
      csl-styles (~> 1.0)
      jekyll (~> 4.0)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-target-blank (2.0.0)
      jekyll (>= 3.0, < 5.0)
      nokogiri (~> 1.10)
    jekyll-twitter-plugin (2.1.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    jemoji (0.12.0)
      gemoji (~> 3.0)
      html-pipeline (~> 2.2)
      jekyll (>= 3.0, < 5.0)
    json (2.6.2)
    json-minify (0.0.3)
      json (> 0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    latex-decode (0.4.0)
    libv8-node (16.10.0.0-arm64-darwin)
    libv8-node (16.10.0.0-x86_64-darwin)
    libv8-node (16.10.0.0-x86_64-linux)
    libv8-node (16.10.0.0-x86_64-linux-musl)
    liquid (4.0.3)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.18.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mercenary (0.4.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    mini_racer (0.6.3)
      libv8-node (~> 16.10.0.0)
    minitest (5.16.3)
    multi_xml (0.6.0)
    namae (1.1.1)
    nokogiri (1.13.8-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.8-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.8-x86_64-linux)
      racc (~> 1.4)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.7)
    racc (1.6.0)
    rb-fsevent (0.11.1)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.30.0)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    sax-machine (1.3.2)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (1.8.0)
    unicode_utils (1.4.0)
    webrick (1.7.0)
    zeitwerk (2.6.0)

PLATFORMS
  universal-darwin-21
  x86_64-linux

DEPENDENCIES
  feedjira
  httparty
  jekyll
  jekyll-archives
  jekyll-diagrams
  jekyll-email-protect
  jekyll-feed
  jekyll-imagemagick
  jekyll-minifier
  jekyll-paginate-v2
  jekyll-scholar
  jekyll-sitemap
  jekyll-target-blank
  jekyll-twitter-plugin
  jemoji
  mini_racer
  unicode_utils
  webrick

BUNDLED WITH
   2.3.20
```
(base) tomeldridge@Toms-MBP-3 TeldridgeLDN.github.io %

**Comment by deivid-rodriguez** [comment]
Hi!

If you install latest master (clone the repo, cd to the bundler folder, and run `bin/rake install`), does `bundle install` work? I suspect https://github.com/rubygems/rubygems/pull/5840 may fix this, although the error is not the same.

**Comment by deivid-rodriguez** [comment]
I tried this myself but could not reproduce with Bundler 2.3.20, I would need more machine independent and specific instructions to reproduce. For example, the repository your pointed out does not include a `Gemfile.lock` file while yours includes it. Anyways, I tried with your `Gemfile.lock` and without and everything worked.

**Comment by eregon** [comment]
FWIW, also observed on https://github.com/Shopify/yjit-bench/pull/108#issue-1343744966

**Comment by deivid-rodriguez** [comment]
Yes, I saw that and also tried to reproduce by installing Ruby's master branch and running `bundle install` over a revision of the repo before that PR. But it all worked too. I guess it's because I'm on `arm-darwin-21` which neither of the two repros are using. I can hopefully try linux in a few days/weeks, but for now if someone experiencing the issue can verify our current master branch, that would help!

**Comment by TeldridgeLDN** [comment]
> If you install latest master (clone the repo, cd to the bundler folder, and run bin/rake install), does bundle install work? 

This seemed to work. What's really strange is that the bin/rake install command returned a zsh: no such file or directory: bin/rake

but when I ran bundle install again it worked.

**Comment by deivid-rodriguez** [comment]
mmm that sounds like you did not install the master branch the. What does `bundle -v` report?

**Comment by TeldridgeLDN** [comment]
Bundler version 2.3.20

**Comment by deivid-rodriguez** [comment]
Right, so the update did not happen. Did you switch to the `bundler/` subfolder before trying to run the `bin/rake` script? Note that it's located at `bundler/bin/rake`.

Anyways, it seems like even without the update, `bundle install` worked the second time, so this is no longer reproducible?

**Comment by TeldridgeLDN** [comment]
> Did you switch to the bundler/ subfolder before trying to run the bin/rake script? Note that it's located at bundler/bin/rake

Ah I see where I went wrong. I hadn't switched to the bundler subfolder.

Bu everything is working as it should now

**Comment by deivid-rodriguez** [comment]
Alright, let me know if you run into issues again!
