### ISSUE TITLE
Bundle failing during capistrano deployment

### ISSUE THREAD

**Issue by Jimreed91** [rubygems/rubygems#5882]
I recently deployed my application to an aws ubuntu server with no issues but after adding pdfkit and wkhtmltopdf gems my deployment fails and I can't quite figure out why. I've updated rubygems and bundler but the result is the same...

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60size%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

Tasks: TOP => deploy:updated => bundler:install
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@my_server_ip: bundle exit status: 1
bundle stdout: Nothing written
bundle stderr: Exception while verifying /var/www/spray-day/shared/bundle/ruby/3.0.0/cache/wkhtmltopdf-binary-0.12.6.5.gem
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `size' for nil:NilClass
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package/tar_reader/entry.rb:139:in `read'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:364:in `block in digest'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:361:in `each'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:361:in `digest'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:647:in `verify_entry'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:666:in `block in verify_files'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:665:in `verify_files'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:596:in `block (2 levels) in verify'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package/tar_reader.rb:27:in `new'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:593:in `block in verify'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `open'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:592:in `verify'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/package.rb:573:in `spec'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/rubygems_gem_installer.rb:95:in `spec'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/source/rubygems.rb:190:in `install'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/worker.rb:62:in `apply_func'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/worker.rb:54:in `loop'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/worker.rb:54:in `process_queue'
  /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.21/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.3.21
  Platforms   ruby, x86_64-linux
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [x86_64-linux]
  Full Path   /home/deploy/.rbenv/versions/3.0.3/bin/ruby
  Config Dir  /home/deploy/.rbenv/versions/3.0.3/etc
RubyGems      3.2.32
  Gem Home    /var/www/spray-day/shared/bundle/ruby/3.0.0
  Gem Path    /var/www/spray-day/shared/bundle/ruby/3.0.0
  User Home   /home/deploy
  User Path   /home/deploy/.local/share/gem/ruby/3.0.0
  Bin Dir     /var/www/spray-day/shared/bundle/ruby/3.0.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1f  31 Mar 2020
  Loaded      OpenSSL 1.1.1f  31 Mar 2020
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.25.1
  RVM         not installed
  rbenv       rbenv 1.2.0-16-gc4395e5
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-08-24
Git SHA           d54be5fdd8
Released Version  true
```

## Bundler settings

```
deployment
  Set for your local app (/var/www/spray-day/releases/20220828102732/.bundle/config): true
jobs
  Set for your local app (/var/www/spray-day/releases/20220828102732/.bundle/config): 4
path
  Set for your local app (/var/www/spray-day/releases/20220828102732/.bundle/config): "/var/www/spray-day/shared/bundle"
without
  Set for your local app (/var/www/spray-day/releases/20220828102732/.bundle/config): [:development, :test]
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'
gem 'cocoon'
gem 'devise'
# custom
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.6'
# Use postgresql as the database for Active Record
gem 'pdfkit'
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'

gem 'render_anywhere', require: false
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
gem 'wkhtmltopdf-binary', '~> 0.12.6.5'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

gem 'autoprefixer-rails'
gem 'simple_form', github: 'heartcombo/simple_form'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'bundler-audit', require: false
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  gem 'capybara', '>= 3.26'
  gem 'factory_bot_rails'
  gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'

  gem 'lefthook'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rails-erd'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'ruby_audit', require: false
end

group :development do
  gem 'capistrano', '~> 3.10', require: false
  gem 'capistrano-db-tasks', require: false
  gem 'capistrano-rails', '~> 1.5', require: false
  gem 'capistrano-rbenv', '~> 2.1'
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  gem 'launchy'
  gem 'selenium-webdriver', '>= 4.0.0.rc1'
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'rails_12factor', group: :production
```

### Gemfile.lock

```
GIT
  remote: https://github.com/faker-ruby/faker.git
  revision: aaf6cbe9841877113da1ead8b5538fc072e4efb6
  branch: master
  specs:
    faker (2.22.0)
      i18n (>= 1.8.11, < 2)

GIT
  remote: https://github.com/heartcombo/simple_form.git
  revision: 31fe25504771bd6cd425b585a4e0ed652fba4521
  specs:
    simple_form (5.1.0)
      actionpack (>= 5.2)
      activemodel (>= 5.2)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.6.1)
      actionpack (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.6.1)
      actionpack (= 6.1.6.1)
      activejob (= 6.1.6.1)
      activerecord (= 6.1.6.1)
      activestorage (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      mail (>= 2.7.1)
    actionmailer (6.1.6.1)
      actionpack (= 6.1.6.1)
      actionview (= 6.1.6.1)
      activejob (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.6.1)
      actionview (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.6.1)
      actionpack (= 6.1.6.1)
      activerecord (= 6.1.6.1)
      activestorage (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      nokogiri (>= 1.8.5)
    actionview (6.1.6.1)
      activesupport (= 6.1.6.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.6.1)
      activesupport (= 6.1.6.1)
      globalid (>= 0.3.6)
    activemodel (6.1.6.1)
      activesupport (= 6.1.6.1)
    activerecord (6.1.6.1)
      activemodel (= 6.1.6.1)
      activesupport (= 6.1.6.1)
    activestorage (6.1.6.1)
      actionpack (= 6.1.6.1)
      activejob (= 6.1.6.1)
      activerecord (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.6.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    airbrussh (1.4.1)
      sshkit (>= 1.6.1, != 1.7.0)
    ast (2.4.2)
    autoprefixer-rails (10.4.7.0)
      execjs (~> 2)
    bcrypt (3.1.18)
    bindex (0.8.1)
    bootsnap (1.13.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    bundler-audit (0.9.1)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    byebug (11.1.3)
    capistrano (3.17.1)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.1.0)
      capistrano (~> 3.1)
    capistrano-db-tasks (0.6)
      capistrano (>= 3.0.0)
    capistrano-rails (1.6.2)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rbenv (2.2.0)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    capybara (3.37.1)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    choice (0.2.0)
    cocoon (1.2.15)
    coderay (1.1.3)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    devise (4.8.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.5.0)
    docile (1.4.0)
    erubi (1.11.0)
    execjs (2.8.1)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    ffi (1.15.5)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    json (2.6.2)
    launchy (2.5.0)
      addressable (~> 2.7)
    lefthook (1.1.1)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.18.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.16.3)
    msgpack (1.5.6)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (7.0.1)
    nio4r (2.5.8)
    nokogiri (1.13.8-x86_64-linux)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    parallel (1.22.1)
    parser (3.1.2.1)
      ast (~> 2.4.1)
    pdfkit (0.8.6)
    pg (1.4.3)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.10.1)
      byebug (~> 11.0)
      pry (>= 0.13, < 0.15)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    public_suffix (5.0.0)
    puma (5.6.5)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.4)
    rack-mini-profiler (2.3.4)
      rack (>= 1.2.0)
    rack-proxy (0.7.2)
      rack
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (6.1.6.1)
      actioncable (= 6.1.6.1)
      actionmailbox (= 6.1.6.1)
      actionmailer (= 6.1.6.1)
      actionpack (= 6.1.6.1)
      actiontext (= 6.1.6.1)
      actionview (= 6.1.6.1)
      activejob (= 6.1.6.1)
      activemodel (= 6.1.6.1)
      activerecord (= 6.1.6.1)
      activestorage (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      bundler (>= 1.15.0)
      railties (= 6.1.6.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-erd (1.7.2)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
      choice (~> 0.2.0)
      ruby-graphviz (~> 1.2)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.5)
    railties (6.1.6.1)
      actionpack (= 6.1.6.1)
      activesupport (= 6.1.6.1)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
    rainbow (3.1.1)
    rake (13.0.6)
    rb-fsevent (0.11.1)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (2.5.0)
    render_anywhere (0.0.12)
      rails (>= 3.0.7)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rexml (3.2.5)
    rspec-core (3.11.0)
      rspec-support (~> 3.11.0)
    rspec-expectations (3.11.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-mocks (3.11.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-rails (5.1.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      railties (>= 5.2)
      rspec-core (~> 3.10)
      rspec-expectations (~> 3.10)
      rspec-mocks (~> 3.10)
      rspec-support (~> 3.10)
    rspec-support (3.11.0)
    rubocop (1.35.1)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.1.2.1)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.20.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.21.0)
      parser (>= 3.1.1.0)
    rubocop-rails (2.15.2)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.7.0, < 2.0)
    rubocop-rspec (2.12.1)
      rubocop (~> 1.31)
    ruby-graphviz (1.2.5)
      rexml
    ruby-progressbar (1.11.0)
    ruby_audit (2.1.0)
      bundler-audit (~> 0.9.0)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.4.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    semantic_range (3.0.0)
    simplecov (0.21.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov-rcov (0.3.1)
      simplecov (>= 0.4.1)
    simplecov_json_formatter (0.1.4)
    spring (4.0.0)
    sprockets (4.1.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sshkit (1.21.2)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (1.2.1)
    tilt (2.0.11)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.2.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    webpacker (5.4.3)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    wkhtmltopdf-binary (0.12.6.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  autoprefixer-rails
  bootsnap (>= 1.4.4)
  bundler-audit
  byebug
  capistrano (~> 3.10)
  capistrano-db-tasks
  capistrano-rails (~> 1.5)
  capistrano-rbenv (~> 2.1)
  capybara (>= 3.26)
  cocoon
  devise
  factory_bot_rails
  faker!
  jbuilder (~> 2.7)
  launchy
  lefthook
  listen (~> 3.3)
  pdfkit
  pg (~> 1.1)
  pry-byebug
  pry-rails
  puma (~> 5.0)
  rack-mini-profiler (~> 2.0)
  rails (~> 6.1.6)
  rails-erd
  rails_12factor
  render_anywhere
  rspec-rails
  rubocop
  rubocop-rails
  rubocop-rspec
  ruby_audit
  sass-rails (>= 6)
  selenium-webdriver (>= 4.0.0.rc1)
  simple_form!
  simplecov
  simplecov-rcov
  spring
  turbolinks (~> 5)
  tzinfo-data
  web-console (>= 4.1.0)
  webdrivers
  webpacker (~> 5.0)
  wkhtmltopdf-binary (~> 0.12.6.5)

RUBY VERSION
   ruby 3.0.3p157

BUNDLED WITH
   2.3.21
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
I think this could be related to https://github.com/rubygems/rubygems/pull/5681, maybe your disk is full and a corrupt `.gem` file was written due to lack of space?

**Comment by deivid-rodriguez** [comment]
I'll assume this is the same as #5681 and close this, since we got no further feedback.
