### ISSUE TITLE
Problems validating 3.2.0.preview2

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#5919]
I'm not quite sure who to blame here, is it rais or bundler. Anyway, when bundler runs after creating a new rails app we get:

```
Your Ruby version is 3.2.0.preview2, but your Gemfile specified 3.2.0
run  bundle binstubs bundler
Your Ruby version is 3.2.0.preview2, but your Gemfile specified 3.2.0
rails  importmap:install
/home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/definition.rb:443:in `validate_ruby!': Your Ruby version is 3.2.0.preview2, but your Gemfile specified 3.2.0 (Bundler::RubyVersionMismatch)
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/definition.rb:418:in `validate_runtime!'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler.rb:156:in `setup'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/setup.rb:20:in `block in <top (required)>'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/ui/shell.rb:136:in `with_level'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/ui/shell.rb:88:in `silence'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/setup.rb:20:in `<top (required)>'
from <internal:/home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /mnt/agent/temp/buildTmp/unitTest_Minitest_2EWZklR3spiHluaeqFXRlrIQbTS/config/boot.rb:3:in `<top (required)>'
from bin/rails:3:in `require_relative'
from bin/rails:3:in `<main>'
rails  turbo:install stimulus:install
/home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/definition.rb:443:in `validate_ruby!': Your Ruby version is 3.2.0.preview2, but your Gemfile specified 3.2.0 (Bundler::RubyVersionMismatch)
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/definition.rb:418:in `validate_runtime!'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler.rb:156:in `setup'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/setup.rb:20:in `block in <top (required)>'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/ui/shell.rb:136:in `with_level'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/ui/shell.rb:88:in `silence'
from /home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/bundler/setup.rb:20:in `<top (required)>'
from <internal:/home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/home/user/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /mnt/agent/temp/buildTmp/unitTest_Minitest_2EWZklR3spiHluaeqFXRlrIQbTS/config/boot.rb:3:in `<top (required)>'
from bin/rails:3:in `require_relative'
from bin/rails:3:in `<main>'
```

Did not have the problem with `preview1` irr.

**Comment by deivid-rodriguez** [comment]
Hello @hurricup!

It's a change on our side where the `ruby` DSL has been made more strict (and correct) that has introduced this problem: https://github.com/rubygems/rubygems/pull/5766.

Ideally Rails should adapt its template here: https://github.com/rails/rails/blob/fcac1c4c07ec0846e0c6c08a7a4d0021333f51d6/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L4 to play nice with this change like this:

```ruby
ruby <%= "\"#{Gem.ruby_version}\"" -%>
```

or some other approach that plays nice with Ruby prereleases (note that for your Ruby version, `RUBY_VERSION` returns `3.2.0`, while `Gem.ruby_version` returns `3.2.0.preview2`).

I'm happy to provide a PR to Rails for this.

**Comment by hurricup** [comment]
Should I fill an issue for rails?

**Comment by deivid-rodriguez** [comment]
It's already done, and it was a clear bug, since `ruby "3.2.0"` means match `ruby "3.2.0"` exactly, and Ruby 3.2.0.preview2 does not match that. Also, it affects only Ruby prereleases of Ruby. I think it's fine.

**Comment by deivid-rodriguez** [comment]
> Should I fill an issue for rails?

I'd go with a PR directly.

**Comment by deivid-rodriguez** [comment]
I created a PR: https://github.com/rails/rails/pull/45979.

Sorry for the trouble, I figured it was ok given the limited scope. I should've probably checked with Rails first to make sure that the change I'm proposing now was in place _before_ there was a Ruby prerelease including the "offending" Bundler version, but I didn't realize.

**Comment by deivid-rodriguez** [comment]
PR to Rails was merged, although a Rails will be needed for this to work again.

I'll close this regardless, since I think there's not much else we can do at this point! Happy to discuss more though.
