### ISSUE TITLE
Bundle is not working 

### ISSUE THREAD

**Issue by Gurpreet7732** [rubygems/rubygems#5953]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
![Screenshot_20220927_230759](https://user-images.githubusercontent.com/94563315/192597378-ec121102-cf32-46c7-b58e-359e20426f26.jpg)

**Comment by deivid-rodriguez** [comment]
Sorry, but an incomplete screenshot is not enough for us to figure out what's wrong. Please copy at least the full error report.

**Comment by LondonAtlas** [comment]
I am seeing the same issue as well. Here are the logs but it looks like a server timeout.

```$ bundle install --verbose

Running `bundle install --verbose` with bundler 2.1.4
Found changes from the lockfile, re-resolving dependencies because the dependencies in your gemfile changed
HTTP GET https://index.rubygems.org/versions
Net::OpenTimeout: execution expired
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `open'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:958:in `connect'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:938:in `start'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:719:in `start'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:648:in `connection_for'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendored_persistent.rb:23:in `connection_for'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:936:in `request'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/fetcher/downloader.rb:59:in `request'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/fetcher/downloader.rb:17:in `fetch'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/fetcher/compact_index.rb:131:in `call'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/compact_index_client/updater.rb:53:in `block in update'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/compact_index_client/updater.rb:31:in `update'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/compact_index_client.rb:98:in `update'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/compact_index_client.rb:85:in `update_and_parse_checksums!'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/fetcher/compact_index.rb:75:in `available?'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/fetcher/compact_index.rb:16:in `call'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/fetcher.rb:162:in `use_api'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/source/rubygems.rb:388:in `block in api_fetchers'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/source/rubygems.rb:388:in `select'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/source/rubygems.rb:388:in `api_fetchers'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/source/rubygems.rb:393:in `block in remote_specs'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/index.rb:11:in `build'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/source/rubygems.rb:392:in `remote_specs'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/source/rubygems.rb:88:in `specs'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/definition.rb:273:in `block (2 levels) in index'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/definition.rb:271:in `each'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/definition.rb:271:in `block in index'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/index.rb:11:in `build'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/definition.rb:268:in `index'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/definition.rb:258:in `resolve'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/definition.rb:158:in `resolve_remotely!'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/installer.rb:303:in `resolve_if_needed'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/installer.rb:84:in `block in run'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `open'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/installer.rb:73:in `run'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/installer.rb:25:in `install'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/install.rb:66:in `run'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:256:in `block in install'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:255:in `install'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
~/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
~/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
~/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
Bundler::HTTPError: Network error while fetching https://index.rubygems.org/versions (execution expired)```

**Comment by LondonAtlas** [comment]
Thanks! I think my issue might be a rubygems problem as this command is also timing out.

**Comment by deivid-rodriguez** [comment]
Yeah, looks like a server side issue, can you copy the logs of `gem update --system` then?

**Comment by LondonAtlas** [comment]
turns out it's my local wifi. Connecting via hotspot worked immediately.

**Comment by deivid-rodriguez** [comment]
Closing since we never got any feedback on the original issue.
