### ISSUE TITLE
Bundler v2.3.23 does not install dependencies that v2.3.22 did

### ISSUE THREAD

**Issue by mx-psi** [rubygems/rubygems#5969]
### Describe the problem as clearly as you can

We use bundler to install the gems on [this Gemfile](https://github.com/DataDog/datadog-agent/blob/e0d771b881189e74d9f928840850758fb864658f/omnibus/Gemfile). On v2.3.22, this Gemfile installs the `win32-process` gem, while on v2.3.23 it does not, breaking our build.

We have temporarily fixed this by pinning bundler DataDog/datadog-agent-buildimages/pull/298.

### Did you try upgrading rubygems & bundler?

Yes! This problem is related to upgrading bundler :)

### Post steps to reproduce the problem

It seems to be as simple as:

1. Install bundler v2.3.23 on Windows (version does not seem to matter, we reproduced it on 1809, 1909, 2004, 20h2 and ltsc2022).
2. Run `bundle install` with [this Gemfile](https://github.com/DataDog/datadog-agent/blob/e0d771b881189e74d9f928840850758fb864658f/omnibus/Gemfile)

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Install passes, as with v2.3.22

### What actually happened?

Install failed

<details>

<summary> Logs (click to expand)</summary>

```
cd omnibus && bundle install[0m
Fetching https://github.com/DataDog/omnibus-software.git

Fetching https://github.com/DataDog/omnibus-ruby.git

Fetching https://github.com/chef/chef-sugar.git

Fetching gem metadata from https://rubygems.org/.........

Resolving dependencies...

Using bundler 2.3.23

Using chef-sugar 3.6.0 from https://github.com/chef/chef-sugar.git (at v3.6.0@956f1d7)

Fetching public_suffix 5.0.0

Fetching awesome_print 1.9.2

Fetching aws-eventstream 1.2.0

Fetching jmespath 1.6.1

Fetching fuzzyurl 0.9.0

Fetching tomlrb 1.3.0

Fetching mixlib-shellout 2.4.4

Fetching citrus 3.0.2

Installing aws-eventstream 1.2.0

Installing jmespath 1.6.1

Installing fuzzyurl 0.9.0

Installing tomlrb 1.3.0

Installing mixlib-shellout 2.4.4

Installing awesome_print 1.9.2

Installing citrus 3.0.2

Installing public_suffix 5.0.0

Fetching cleanroom 1.0.0

Using ffi 1.15.5

Using libyajl2 1.2.0

Fetching mime-types-data 3.2022.0105

Installing cleanroom 1.0.0

Fetching multi_xml 0.6.0

Fetching iostruct 0.0.4

Installing multi_xml 0.6.0

Installing iostruct 0.0.4

Installing mime-types-data 3.2022.0105

Fetching ipaddress 0.8.3

Fetching mixlib-cli 1.7.0

Installing ipaddress 0.8.3

Fetching mixlib-log 1.7.1

Installing mixlib-cli 1.7.0

Installing mixlib-log 1.7.1

Fetching mixlib-versioning 1.2.12

Fetching multipart-post 2.2.3

Installing mixlib-versioning 1.2.12

Installing multipart-post 2.2.3

Fetching plist 3.6.0

Installing plist 3.6.0

Fetching systemu 2.6.5

Fetching wmi-lite 1.0.7

Fetching rainbow 3.1.1

Installing wmi-lite 1.0.7

Installing systemu 2.6.5

Installing rainbow 3.1.1

Fetching zhexdump 0.0.2

Fetching ruby-progressbar 1.11.0

Installing zhexdump 0.0.2

Fetching thor 0.20.3

Installing ruby-progressbar 1.11.0

Installing thor 0.20.3

Using omnibus-software 4.0.0 from https://github.com/DataDog/omnibus-software.git (at master@c32452f)

Fetching ffi-yajl 2.3.4

Fetching mixlib-config 2.2.18

Fetching aws-sigv4 1.5.2

Fetching mime-types 3.4.1

Installing mixlib-config 2.2.18

Fetching addressable 2.8.1

Installing aws-sigv4 1.5.2

Installing mime-types 3.4.1

Installing addressable 2.8.1

Fetching toml-rb 2.2.0

Fetching aws-sdk-core 2.11.632

Installing toml-rb 2.2.0

Installing aws-sdk-core 2.11.632

Fetching chef-config 13.12.14

Fetching httparty 0.20.0

Installing chef-config 13.12.14

Fetching pedump 0.6.5

Installing httparty 0.20.0

Installing pedump 0.6.5

Installing ffi-yajl 2.3.4 with native extensions

Fetching aws-sdk-resources 2.11.632

Installing aws-sdk-resources 2.11.632

Fetching aws-sdk 2.11.632

Installing aws-sdk 2.11.632

Fetching license_scout 1.2.16

Fetching ohai 8.26.1

Installing license_scout 1.2.16

Installing ohai 8.26.1

Using omnibus 5.5.0 from https://github.com/DataDog/omnibus-ruby.git (at datadog-5.5.0@2d8c376)

Bundle complete! 4 Gemfile dependencies, 44 gems now installed.

Use `bundle info [gemname]` to see where a bundled gem is installed.

Post-install message from aws-sdk-core:

AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.

Post-install message from aws-sdk-resources:

AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.

Post-install message from aws-sdk:

AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.

Post-install message from httparty:

When you HTTParty, you must party hard!

c:/tools/ruby/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/windows.rb:21:in `require': cannot load such file -- win32/process (LoadError)

	from c:/tools/ruby/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/windows.rb:21:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:32:in `require'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:32:in `<class:ShellOut>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:26:in `<module:Mixlib>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:24:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/util.rb:17:in `require'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/util.rb:17:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/git_repository.rb:1:in `require'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/git_repository.rb:1:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/changelog.rb:1:in `require'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/changelog.rb:1:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/cli/changelog.rb:17:in `require'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/cli/changelog.rb:17:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/cli.rb:101:in `require'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/cli.rb:101:in `<class:CLI>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/cli.rb:22:in `<module:Omnibus>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/lib/omnibus/cli.rb:21:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/bin/omnibus:10:in `require'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bundler/gems/omnibus-ruby-2d8c37625edb/bin/omnibus:10:in `<top (required)>'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bin/omnibus:23:in `load'

	from c:/tools/ruby/lib/ruby/gems/2.6.0/bin/omnibus:23:in `<main>'
```

</details>

### If not included with the output of your command, run `bundle env` and paste the output below

n/a at the moment, I can fetch it if necessary

**Comment by deivid-rodriguez** [comment]
Hello @mx-psi, sorry about that :(

I will have a look at this and try to fix it.

**Comment by mx-psi** [comment]
Thanks! Happy to provide more context if necessary :)

**Comment by deivid-rodriguez** [comment]
Thank you! Given you've shared an open source repo, I think this should be easy to reproduce. I'll ask for clarifications if needed later.

**Comment by tvo** [comment]
In case it helps, I found a likely related issue with bundler 2.3.23 where it fails to install `grpc` on CentOS 7.

On bundler 2.3.22, it shows `Fetching grpc 1.36.0 (x86_64-linux)` and succeeds.

On bundler 2.3.23, it shows `Fetching grpc 1.36.0` and then fails with the following C++ compile error:
```
./src/core/ext/filters/client_channel/server_address.h:135:41: error: no
matching function for call to 'StrFormat(const char [3], const uint32_t&)'
     return absl::StrFormat("%d", weight_);
``` 

I don't think the specific error is super relevant but I do suspect that the lack of mention of the platform `x86_64-linux` could be related.

Happy to create a new issue for this if desired.

**Comment by deivid-rodriguez** [comment]
@mx-psi Can you share a link to the failing CI? I tried to reproduce this on my Windows VM and I couldn't, I got win32-process with both versions.

**Comment by mx-psi** [comment]
Hey, unfortunately I can't share the CI link, but I can give you the logs and a (admitedly huge) Docker for Windows image where we have been able to reproduce this outside of CI.

<details>
<summary>Logs when using bundler 2.3.22, win32-process is installed (click to expand)</summary>

```
PS C:\Users\kylian> docker run -it datadog/agent-buildimages-windows_x64:1809-v10345198-80e69c3 powershell
PS C:\> bundle version
Bundler version 2.3.22 (2022-09-07 commit 44fb4c9ef5)
PS C:\> Add-Content -Path Gemfile -Value "source 'https://rubygems.org/'
>>
>> # Install omnibus
>> gem 'chef-sugar', git: 'https://github.com/chef/chef-sugar.git', tag: 'v3.6.0'
>> gem 'omnibus', git: 'https://github.com/DataDog/omnibus-ruby.git', branch: (ENV['OMNIBUS_RUBY_VERSION'] || 'datadog-5.5.0')
>>
>> # Use Chef's software definitions. It is recommended that you write your own
>> # software definitions, but you can clone/fork Chef's to get you started.
>> gem 'omnibus-software', git: 'https://github.com/DataDog/omnibus-software.git', branch: (ENV['OMNIBUS_SOFTWARE_VERSION'] || 'master')
>>
>>
>> gem 'mixlib-cli', '~> 1.7.0'"
PS C:\> bundle install
Fetching https://github.com/DataDog/omnibus-software.git
Fetching https://github.com/DataDog/omnibus-ruby.git
Fetching https://github.com/chef/chef-sugar.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching public_suffix 5.0.0
Fetching aws-eventstream 1.2.0
Fetching awesome_print 1.9.2
Fetching jmespath 1.6.1
Installing aws-eventstream 1.2.0
Installing jmespath 1.6.1
Installing awesome_print 1.9.2
Installing public_suffix 5.0.0
Using bundler 2.3.22
Fetching fuzzyurl 0.9.0
Installing fuzzyurl 0.9.0
Fetching tomlrb 1.3.0
Installing tomlrb 1.3.0
Fetching ffi 1.15.5 (x64-mingw32)
Fetching wmi-lite 1.0.7
Installing wmi-lite 1.0.7
Installing ffi 1.15.5 (x64-mingw32)
Using chef-sugar 3.6.0 from https://github.com/chef/chef-sugar.git (at v3.6.0@956f1d7)
Fetching citrus 3.0.2
Fetching cleanroom 1.0.0
Installing citrus 3.0.2
Installing cleanroom 1.0.0
Fetching libyajl2 1.2.0
Installing libyajl2 1.2.0 with native extensions
Fetching mime-types-data 3.2022.0105
Installing mime-types-data 3.2022.0105
Fetching multi_xml 0.6.0
Installing multi_xml 0.6.0
Fetching iostruct 0.0.4
Installing iostruct 0.0.4
Fetching ipaddress 0.8.3
Installing ipaddress 0.8.3
Fetching mixlib-cli 1.7.0
Installing mixlib-cli 1.7.0
Fetching mixlib-log 1.7.1
Fetching mixlib-versioning 1.2.12
Fetching multipart-post 2.2.3
Installing mixlib-log 1.7.1
Installing mixlib-versioning 1.2.12
Installing multipart-post 2.2.3
Fetching plist 3.6.0
Fetching systemu 2.6.5
Fetching rainbow 3.1.1
Installing plist 3.6.0
Installing rainbow 3.1.1
Installing systemu 2.6.5
Fetching zhexdump 0.0.2
Installing zhexdump 0.0.2
Fetching ruby-progressbar 1.11.0
Fetching thor 0.20.3
Installing ruby-progressbar 1.11.0
Installing thor 0.20.3
Using omnibus-software 4.0.0 from https://github.com/DataDog/omnibus-software.git (at master@c32452f)
Fetching aws-sigv4 1.5.2
Installing aws-sigv4 1.5.2
Fetching mixlib-config 2.2.18
Installing mixlib-config 2.2.18
Fetching addressable 2.8.1
Fetching toml-rb 2.2.0
Installing addressable 2.8.1
Installing toml-rb 2.2.0
Fetching mime-types 3.4.1
Installing mime-types 3.4.1
Fetching win32-process 0.8.3
Fetching pedump 0.6.5
Installing win32-process 0.8.3
Installing pedump 0.6.5
Fetching aws-sdk-core 2.11.632
Fetching httparty 0.20.0
Installing httparty 0.20.0
Installing aws-sdk-core 2.11.632
Fetching mixlib-shellout 2.4.4 (universal-mingw32)
Installing mixlib-shellout 2.4.4 (universal-mingw32)
Fetching chef-config 13.12.14
Installing chef-config 13.12.14
Fetching ffi-yajl 2.3.4
Installing ffi-yajl 2.3.4 with native extensions
Fetching aws-sdk-resources 2.11.632
Installing aws-sdk-resources 2.11.632
Fetching aws-sdk 2.11.632
Installing aws-sdk 2.11.632
Fetching license_scout 1.2.16
Fetching ohai 8.26.1
Installing license_scout 1.2.16
Installing ohai 8.26.1
Using omnibus 5.5.0 from https://github.com/DataDog/omnibus-ruby.git (at datadog-5.5.0@2d8c376)
Bundle complete! 4 Gemfile dependencies, 45 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from aws-sdk-core:
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Post-install message from aws-sdk-resources:
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Post-install message from aws-sdk:
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Post-install message from httparty:
When you HTTParty, you must party hard!
```

</details>

<details>
<summary>Same Docker for Windows image, but now using 2.3.23, win32-process is not installed (click to expand)</summary>

```
PS C:\Users\kylian> docker run -it datadog/agent-buildimages-windows_x64:1809-v10345198-80e69c3 powershell
PS C:\> gem install bundler -v 2.3.23
Fetching bundler-2.3.23.gem
Successfully installed bundler-2.3.23
Parsing documentation for bundler-2.3.23
Installing ri documentation for bundler-2.3.23
Done installing documentation for bundler after 0 seconds
1 gem installed
PS C:\> bundle version
Bundler version 2.3.23 (2022-10-05 commit 250d9d485d)
PS C:\> Add-Content -Path Gemfile -Value "source 'https://rubygems.org/'
>>
>> # Install omnibus
>> gem 'chef-sugar', git: 'https://github.com/chef/chef-sugar.git', tag: 'v3.6.0'
>> gem 'omnibus', git: 'https://github.com/DataDog/omnibus-ruby.git', branch: (ENV['OMNIBUS_RUBY_VERSION'] || 'datadog-5.5.0')
>>
>> # Use Chef's software definitions. It is recommended that you write your own
>> # software definitions, but you can clone/fork Chef's to get you started.
>> gem 'omnibus-software', git: 'https://github.com/DataDog/omnibus-software.git', branch: (ENV['OMNIBUS_SOFTWARE_VERSION'] || 'master')
>>
>>
>> gem 'mixlib-cli', '~> 1.7.0'"
PS C:\> bundle install
Fetching https://github.com/DataDog/omnibus-software.git
Fetching https://github.com/DataDog/omnibus-ruby.git
Fetching https://github.com/chef/chef-sugar.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching public_suffix 5.0.0
Fetching awesome_print 1.9.2
Fetching aws-eventstream 1.2.0
Fetching jmespath 1.6.1
Installing aws-eventstream 1.2.0
Installing jmespath 1.6.1
Installing awesome_print 1.9.2
Installing public_suffix 5.0.0
Using bundler 2.3.23
Fetching fuzzyurl 0.9.0
Installing fuzzyurl 0.9.0
Fetching tomlrb 1.3.0
Installing tomlrb 1.3.0
Using chef-sugar 3.6.0 from https://github.com/chef/chef-sugar.git (at v3.6.0@956f1d7)
Fetching mixlib-shellout 2.4.4
Fetching citrus 3.0.2
Installing mixlib-shellout 2.4.4
Installing citrus 3.0.2
Fetching cleanroom 1.0.0
Fetching ffi 1.15.5
Installing cleanroom 1.0.0
Installing ffi 1.15.5 with native extensions
Fetching libyajl2 1.2.0
Installing libyajl2 1.2.0 with native extensions
Fetching mime-types-data 3.2022.0105
Fetching multi_xml 0.6.0
Installing multi_xml 0.6.0
Installing mime-types-data 3.2022.0105
Fetching iostruct 0.0.4
Installing iostruct 0.0.4
Fetching ipaddress 0.8.3
Fetching mixlib-cli 1.7.0
Installing ipaddress 0.8.3
Installing mixlib-cli 1.7.0
Fetching mixlib-log 1.7.1
Installing mixlib-log 1.7.1
Fetching multipart-post 2.2.3
Installing multipart-post 2.2.3
Fetching plist 3.6.0
Installing plist 3.6.0
Fetching systemu 2.6.5
Installing systemu 2.6.5
Fetching wmi-lite 1.0.7
Installing wmi-lite 1.0.7
Fetching rainbow 3.1.1
Fetching zhexdump 0.0.2
Installing rainbow 3.1.1
Installing zhexdump 0.0.2
Fetching ruby-progressbar 1.11.0
Fetching thor 0.20.3
Installing ruby-progressbar 1.11.0
Installing thor 0.20.3
Using omnibus-software 4.0.0 from https://github.com/DataDog/omnibus-software.git (at master@c32452f)
Fetching aws-sigv4 1.5.2
Installing aws-sigv4 1.5.2
Fetching mixlib-config 2.2.18
Fetching addressable 2.8.1
Installing mixlib-config 2.2.18
Installing addressable 2.8.1
Fetching toml-rb 2.2.0
Installing toml-rb 2.2.0
Fetching mime-types 3.4.1
Fetching pedump 0.6.5
Installing mime-types 3.4.1
Installing pedump 0.6.5
Fetching aws-sdk-core 2.11.632
Installing aws-sdk-core 2.11.632
Fetching chef-config 13.12.14
Installing chef-config 13.12.14
Fetching httparty 0.20.0
Installing httparty 0.20.0
Fetching ffi-yajl 2.3.4
Installing ffi-yajl 2.3.4 with native extensions
Fetching aws-sdk-resources 2.11.632
Installing aws-sdk-resources 2.11.632
Fetching aws-sdk 2.11.632
Installing aws-sdk 2.11.632
Fetching license_scout 1.2.16
Fetching ohai 8.26.1
Installing license_scout 1.2.16
Installing ohai 8.26.1
Using omnibus 5.5.0 from https://github.com/DataDog/omnibus-ruby.git (at datadog-5.5.0@2d8c376)
Bundle complete! 4 Gemfile dependencies, 44 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from aws-sdk-core:
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Post-install message from aws-sdk-resources:
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Post-install message from aws-sdk:
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Post-install message from httparty:
When you HTTParty, you must party hard!
```
</details>

To reproduce, we used the latest Docker for Windows image available [here](https://hub.docker.com/layers/datadog/agent-buildimages-windows_x64/2004-v10345198-80e69c3/images/sha256-efc72537e78a72c990e89fd486948daee3c61ce8be04016d1ec2ab3630cc3fe8?context=explore). That's for Windows 2004, you could replace the `2004` bit on the tag by something else if you need a different option.

One interesting difference in the logs is that we see

```
Installing mixlib-shellout 2.4.4 (universal-mingw32)
```

versus

```
Installing mixlib-shellout 2.4.4
```

which seems similar to @tvo's comment. The [mixlib-shellout](https://github.com/chef/mixlib-shellout) dependency has three different gemspecs, two of them platform specific, which seem to be ignored.

My current bet would be that this is related to rubygems/rubygems/pull/5939, based on our issue and @tvo's comment.

**Comment by deivid-rodriguez** [comment]
Nice, thank you. I'll try to reproduce it 👍.

**Comment by deivid-rodriguez** [comment]
I haven't been able to reproduce this due to not being able to properly get docker to work inside my Windows VM. I guess I need to install Windows for real, but I'm not sure when I'll be able to do that.

I'm going to try to reproduce other issues opened about problem with the latest release on Windows. Hopefully some of the reproduces more easily and the culprit ends up being the same as this issue.

**Comment by mx-psi** [comment]
Per https://github.com/rubygems/rubygems/issues/5969#issuecomment-1270296862, it sounds like the underlying issue can be reproduced on CentOS 7 too? Maybe that's easier

**Comment by deivid-rodriguez** [comment]
@mx-psi I think Bundler 2.3.24 should've fixed this. Can you try it?

**Comment by mx-psi** [comment]
The test suite from DataDog/datadog-agent-buildimages/pull/304 passed, so it looks like the new version fixed this :) Thanks again for the prompt reply and the quick turnaround!
