### ISSUE TITLE
NoMethodError: undefined method `full_name' for nil:NilClass

### ISSUE THREAD

**Issue by kiwidude68** [rubygems/rubygems#5971]
### Describe the problem as clearly as you can

Trying to setup a GitHub Pages website, following the instructions on this page on my Windows 10 machine:
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

Never used Ruby/Bundler etc before so these were all first time installs from a few hours ago. However things went wrong at step 12 of "Creating your site" when running: bundle install

### Did you try upgrading rubygems & bundler?

Yes

### Which command did you run?

bundle install

### What actually happened?

$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies....
Your lockfile was created by an old Bundler that left some things out.
Because of the missing DEPENDENCIES, we can only install gems one at a time, instead of installing 8 at a time.
You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
The missing gems are:
* mini_portile2 depended upon by nokogiri
Using concurrent-ruby 1.1.10
Using i18n 0.9.5
Using minitest 5.16.3
Using thread_safe 0.3.6
Using tzinfo 1.2.10
Using zeitwerk 2.6.1
Using activesupport 6.0.6
Using public_suffix 4.0.7
Using addressable 2.8.1
Using bundler 2.3.23
Using coffee-script-source 1.11.1
Using execjs 2.8.1
Using coffee-script 2.4.1
Using colorator 1.1.0
Using commonmarker 0.23.6
Using unf_ext 0.0.8.2 (x64-mingw-ucrt)
Using unf 0.1.4
Using simpleidn 0.2.1
Using dnsruby 1.61.9
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using ffi 1.15.5
Using ethon 0.15.0
Using faraday-net_http 3.0.0
Using ruby2_keywords 0.0.5
Using faraday 2.6.0
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using sawyer 0.9.2
Using octokit 4.25.1
Using typhoeus 1.4.0
Using github-pages-health-check 1.17.9
Using rb-fsevent 0.11.2
Using rb-inotify 0.10.1
Using sass-listen 4.0.0
Using sass 3.7.4
Using jekyll-sass-converter 1.5.2
Using listen 3.7.1
Using jekyll-watch 2.2.1
Using rexml 3.2.5
Using kramdown 2.3.2
Using liquid 4.0.3
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.26.0
Using safe_yaml 1.0.5
Using jekyll 3.9.2
Using jekyll-avatar 0.7.0
Using jekyll-coffeescript 1.1.1
Using jekyll-commonmark 1.4.0
Using jekyll-commonmark-ghpages 0.2.0
Using jekyll-default-layout 0.1.4
Using jekyll-feed 0.15.1
Using jekyll-gist 1.5.0
Using jekyll-github-metadata 2.13.0
Using jekyll-include-cache 0.2.1
Using racc 1.6.0
Installing nokogiri 1.13.8 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `full_name' for nil:NilClass

  warning << "* #{unmet_spec_dependency}, depended upon #{spec.full_name}, unsatisfied by #{@specs.find {|s| s.name == unmet_spec_dependency.name && !unmet_spec_dependency.matches_spec?(s.spec) }.full_name}"
                                                                                                                                                                                           ^^^^^^^^^^
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:123:in `each'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:122:in `each'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:100:in `call'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:71:in `call'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:254:in `install_in_parallel'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:209:in `install'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:89:in `block in run'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:12:in `block in lock'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `open'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `lock'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:71:in `run'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:23:in `install'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli/install.rb:62:in `run'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:257:in `block in install'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/settings.rb:131:in `temporary'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:256:in `install'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundle:48:in `block in <top (required)>'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  D:/Dev/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundle:36:in `<top (required)>'
  D:/Dev/Tools/Ruby31-x64/bin/bundle:32:in `load'
  D:/Dev/Tools/Ruby31-x64/bin/bundle:32:in `<main>'

```

## Environment

```
Bundler       2.3.23
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x64-mingw-ucrt]
  Full Path   D:/Dev/Tools/Ruby31-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.3.23
  Gem Home    D:/Dev/Tools/Ruby31-x64/lib/ruby/gems/3.1.0
  Gem Path    C:/Users/foo/.local/share/gem/ruby/3.1.0;D:/Dev/Tools/Ruby31-x64/lib/ruby/gems/3.1.0
  User Home   C:/Users/foo
  User Path   C:/Users/foo/.local/share/gem/ruby/3.1.0
  Bin Dir     D:/Dev/Tools/Ruby31-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   D:/Dev/Tools/Ruby31-x64/ssl/cert.pem
  Cert Dir    D:/Dev/Tools/Ruby31-x64/ssl/certs
Tools
  Git         2.38.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-10-05
Git SHA           250d9d485d
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# gem "jekyll", "~> 4.2.2"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", "~> 227", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```

### Gemfile.lock

```
<No D:/Dev/CalibreDev/kiwidude68.github.io/docs/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by Guikube** [comment]
Same exact situation, same exact versions and same exact problem.

**Comment by jim-liu** [comment]
> Update : I had to downgrade the `bundler` package to its ` 2.3.20` version for the `bundle install` to work
> (did not try ` 2.3.21` & ` 2.3.22`).

Setting bundler version to 2.3.22 works for me.

**Comment by deivid-rodriguez** [comment]
Closing in favour of #5970, please subscribe to that one!
