### ISSUE TITLE
NoMethodError: undefined method `full_name' for nil:NilClass

### ISSUE THREAD

**Issue by TheLidlMan** [rubygems/rubygems#5986]
```
NoMethodError: undefined method `full_name' for nil:NilClass

  warning << "* #{unmet_spec_dependency}, depended upon #{spec.full_name}, unsatisfied by #{@specs.find {|s| s.name == unmet_spec_dependency.name && !unmet_spec_dependency.matches_spec?(s.spec) }.full_name}"
                                                                                                                                                                                           ^^^^^^^^^^
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:123:in `each'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:122:in `each'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:100:in `call'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:71:in `call'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer.rb:254:in `install_in_parallel'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer.rb:209:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer.rb:89:in `block in run'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/process_lock.rb:12:in `block in lock'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/process_lock.rb:9:in `open'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/process_lock.rb:9:in `lock'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer.rb:71:in `run'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/installer.rb:23:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/cli/install.rb:62:in `run'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/cli.rb:257:in `block in install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/settings.rb:131:in `temporary'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/cli.rb:256:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/cli.rb:31:in `dispatch'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/cli.rb:25:in `start'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundle:48:in `block in <top (required)>'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundle:36:in `<top (required)>'
  C:/Ruby31-x64/bin/bundle:32:in `load'
  C:/Ruby31-x64/bin/bundle:32:in `<main>'

```

## Environment

```
Bundler       2.3.23
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x64-mingw-ucrt]
  Full Path   C:/Ruby31-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.3.7
  Gem Home    C:/Ruby31-x64/lib/ruby/gems/3.1.0
  Gem Path    C:/Users/Sam/.local/share/gem/ruby/3.1.0;C:/Ruby31-x64/lib/ruby/gems/3.1.0
  User Home   C:/Users/Sam
  User Path   C:/Users/Sam/.local/share/gem/ruby/3.1.0
  Bin Dir     C:/Ruby31-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   C:/Ruby31-x64/ssl/cert.pem
  Cert Dir    C:/Ruby31-x64/ssl/certs
Tools
  Git         2.38.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-10-05
Git SHA           250d9d485d
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll-theme-chirpy", "~> 5.3", ">= 5.3.0"

group :test do
  gem "html-proofer", "~> 3.18"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

# Jekyll <= 4.2.0 compatibility with Ruby 3.0
gem "webrick", "~> 1.7"
```

### Gemfile.lock

```
<No C:/Users/Sam/docs.github.io/Gemfile.lock found>
```

**Comment by ccoenen** [comment]
exact same error here while cloning and trying to build someone's jekyll site.

**Comment by TheLidlMan** [comment]
As I was running on windows, I setup the Linux bash environment in cmd and now it all working for me. Slightly annoying it didn’t work bare metal on Win11

**Comment by deivid-rodriguez** [comment]
I'm sorry folks you're all having this issue on Windows. The fix is already committed to master and it will be released early next week.

**Comment by deivid-rodriguez** [comment]
Normally I tend to close issues already fix when their fix lands on master, but in this case I think it makes sense to keep one report opened in case it may prevent duplicate reports. So I will close this one in favor of #5985, please subscribe to that other issue.
