### ISSUE TITLE
Heroku deployments fail bundle with undefined method `metadata' for nil:NilClass

### ISSUE THREAD

**Issue by dp6ai** [rubygems/rubygems#5995]
### Describe the problem as clearly as you can

Heroku deployments which were working are now failing with: 

```
remote:        
remote:        NoMethodError: undefined method `metadata' for nil:NilClass
remote:
remote:              count = current_dependencies.count {|dep| current_specs[dep.name].first.metadata.key?("funding_uri") }
remote:                                                                             ^^^^^^^^^
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/common.rb:22:in `block in output_fund_metadata_summary'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/common.rb:22:in `count'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/common.rb:22:in `output_fund_metadata_summary'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/install.rb:87:in `run'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:255:in `block in install'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/settings.rb:131:in `temporary'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:254:in `install'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
remote:          /tmp/build_152accec/vendor/bundle/bin/bundle:113:in `load'
remote:          /tmp/build_152accec/vendor/bundle/bin/bundle:113:in `<main>'
remote:        
```

Although running `bundle` and `bundle update` locally are both working.

### Did you try upgrading rubygems & bundler?

I am using the latest version of bundler locally.

### Post steps to reproduce the problem

`git push HEROKU_REMOTE main`

### Which command did you run?

`git push HEROKU_REMOTE main`

### What actually happened?
```
remote:       
remote:        NoMethodError: undefined method `metadata' for nil:NilClass
remote:
remote:              count = current_dependencies.count {|dep| current_specs[dep.name].first.metadata.key?("funding_uri") }
remote:                                                                             ^^^^^^^^^
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/common.rb:22:in `block in output_fund_metadata_summary'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/common.rb:22:in `count'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/common.rb:22:in `output_fund_metadata_summary'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/install.rb:87:in `run'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:255:in `block in install'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/settings.rb:131:in `temporary'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:254:in `install'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
remote:          /tmp/build_152accec/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
remote:          /tmp/build_152accec/vendor/bundle/bin/bundle:113:in `load'
remote:          /tmp/build_152accec/vendor/bundle/bin/bundle:113:in `<main>'
remote:        ```
remote:
remote:        ## Environment
remote:
remote:        ```
remote:        Bundler       2.3.10
remote:          Platforms   ruby, x86_64-linux
remote:        Ruby          3.1.0p0 (2021-12-25 revision fb4df44d1670e9d25aef6b235a7281199a177edb) [x86_64-linux]
remote:          Full Path   /tmp/build_152accec/vendor/ruby-3.1.0/bin/ruby
remote:          Config Dir  /app/vendor/ruby-3.1.0/etc
remote:        RubyGems      3.3.3
remote:          Gem Home    /tmp/build_152accec/vendor/bundle/ruby/3.1.0
remote:          Gem Path    /tmp/build_152accec/vendor/bundle/ruby/3.1.0
remote:          User Home   /app
remote:          User Path   /app/.local/share/gem/ruby/3.1.0
remote:          Bin Dir     /tmp/build_152accec/vendor/bundle/ruby/3.1.0/bin
remote:        OpenSSL
remote:          Compiled    OpenSSL 3.0.1 14 Dec 2021
remote:          Loaded      OpenSSL 3.0.2 15 Mar 2022
remote:          Cert File   /usr/lib/ssl/cert.pem
remote:          Cert Dir    /usr/lib/ssl/certs
remote:        Tools
remote:          Git         2.34.1
remote:          RVM         not installed
remote:          rbenv       not installed
remote:          chruby      not installed
remote:        ```
remote:
remote:        ## Bundler Build Metadata
remote:
remote:        ```
remote:        Built At          2022-03-23
remote:        Git SHA           4bbb70e7de
remote:        Released Version  true
remote:        ```
remote:
remote:        ## Bundler settings
remote:
remote:        ```
remote:        bin
remote:          Set via BUNDLE_BIN: "vendor/bundle/bin"
remote:        clean
remote:          You have not configured a value for `clean`
remote:        config
remote:          Set via BUNDLE_CONFIG: "/tmp/build_152accec/.bundle/config"
remote:        deployment
remote:          Set via BUNDLE_DEPLOYMENT: true
remote:        disable_version_check
remote:          Set via BUNDLE_DISABLE_VERSION_CHECK: true
remote:        gemfile
remote:          Set via BUNDLE_GEMFILE: "/tmp/build_152accec/Gemfile"
remote:        jobs
remote:          Set for your local app (/tmp/build_152accec/.bundle/config): 4
remote:        path
remote:          Set via BUNDLE_PATH: "vendor/bundle"
remote:        without
remote:          Set via BUNDLE_WITHOUT: [:development, :linters]
remote:        
```

**Comment by deivid-rodriguez** [comment]
Hei! I'm sorry you're having issues.

Hard to help from our side, since the latest version of our code seems to be working for you, so it's unlikely that there's something to fix on our side that we have not already fixed.

This is what I would recommend. Try to reproduce the heroku issue locally but using the same settings and Bundler version Heroku is using. Then bump the Bundler version until things work again. That should let you know which version fixed the issue. With that information, you can request Heroku team to start using the fixed Bundler version.

**Comment by dp6ai** [comment]
running `bundle lock --add-platform x86_64-linux` fixed the issue.

**Comment by simi** [comment]
Same problem has happened at rubygems.org - https://github.com/rubygems/rubygems.org/actions/runs/3250532768/jobs/5334333346. I can reproduce locally in that branch.

**Comment by mnyon-grandkru** [comment]
@dp6ai Is this applied at the command line, or in a Github workflow? Asking for a self.

**Comment by kristof-mattei** [comment]
@mnyon-grandkru 

```
BUNDLE_IGNORE_FUNDING_REQUESTS=1 bundle install
```

or

```
- name: Release
  shell: bash
  env:
    BUNDLE_IGNORE_FUNDING_REQUESTS: "1"
  run: |
    bundle install
```

**Comment by mnyon-grandkru** [comment]
I'd found & used the latter and that fixed my problem a couple of weeks ago. Still useful @kristof-mattei , so thanks.
