### ISSUE TITLE
Having trouble with installing Rails on Ubuntu 22.10

### ISSUE THREAD

**Issue by wildaces215** [rubygems/rubygems#6079]
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Following files may not be writable, so sudo is needed:
  /usr/share/rvm/gems/ruby-3.0.4
  /usr/share/rvm/gems/ruby-3.0.4/bin
  /usr/share/rvm/gems/ruby-3.0.4/bin
  /usr/share/rvm/gems/ruby-3.0.4/build_info
  /usr/share/rvm/gems/ruby-3.0.4/cache
  /usr/share/rvm/gems/ruby-3.0.4/doc
  /usr/share/rvm/gems/ruby-3.0.4/environment
  /usr/share/rvm/gems/ruby-3.0.4/extensions
  /usr/share/rvm/gems/ruby-3.0.4/gems
  /usr/share/rvm/gems/ruby-3.0.4/plugins
  /usr/share/rvm/gems/ruby-3.0.4/specifications
  /usr/share/rvm/gems/ruby-3.0.4/wrappers
Installing rake 13.0.6
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /usr/share/rvm/gems/ruby-3.0.4/wrappers directory.
  /usr/share/rvm/rubies/ruby-3.0.4/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:26:in `ensure'
  /usr/share/rvm/rubies/ruby-3.0.4/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:19:in `install'
  /usr/share/rvm/rubies/ruby-3.0.4/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb:15:in `block in <top (required)>'
  /home/phoenix/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:373:in `block in run_post_install_hooks'
  /home/phoenix/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:372:in `each'
  /home/phoenix/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:372:in `run_post_install_hooks'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:43:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:90:in `call'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer.rb:254:in `install_in_parallel'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer.rb:209:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer.rb:89:in `block in run'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/process_lock.rb:15:in `lock'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer.rb:71:in `run'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer.rb:23:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli/install.rb:62:in `run'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:257:in `block in install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/settings.rb:131:in `temporary'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:256:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundler:4:in `load'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundler:4:in `<top (required)>'
  /usr/share/rvm/gems/ruby-3.0.4/bin/bundler:23:in `load'
  /usr/share/rvm/gems/ruby-3.0.4/bin/bundler:23:in `<main>'
Errno::EACCES: Permission denied @ rb_sysopen - /usr/share/rvm/gems/ruby-3.0.4/bundler.lock
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/process_lock.rb:9:in `initialize'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer.rb:71:in `run'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/installer.rb:23:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli/install.rb:62:in `run'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:257:in `block in install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/settings.rb:131:in `temporary'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:256:in `install'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundler:4:in `load'
  /usr/share/rvm/gems/ruby-3.0.4/gems/bundler-2.3.26/exe/bundler:4:in `<top (required)>'
  /usr/share/rvm/gems/ruby-3.0.4/bin/bundler:23:in `load'
  /usr/share/rvm/gems/ruby-3.0.4/bin/bundler:23:in `<main>'

```

## Environment

```
Bundler       2.3.26
  Platforms   ruby, x86_64-linux
Ruby          3.0.4p208 (2022-04-12 revision 3fa771ddedac25560be57f4055f1767e6c810f58) [x86_64-linux]
  Full Path   /home/phoenix/.rbenv/versions/3.0.4/bin/ruby
  Config Dir  /home/phoenix/.rbenv/versions/3.0.4/etc
RubyGems      3.2.33
  Gem Home    /usr/share/rvm/gems/ruby-3.0.4
  Gem Path    /usr/share/rvm/gems/ruby-3.0.4:/usr/share/rvm/rubies/ruby-3.0.4/lib/ruby/gems/3.0.0
  User Home   /home/phoenix
  User Path   /home/phoenix/.gem/ruby/3.0.0
  Bin Dir     /usr/share/rvm/gems/ruby-3.0.4/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1s  1 Nov 2022
  Loaded      OpenSSL 1.1.1s  1 Nov 2022
  Cert File   /home/phoenix/.rbenv/versions/3.0.4/openssl/ssl/cert.pem
  Cert Dir    /home/phoenix/.rbenv/versions/3.0.4/openssl/ssl/certs
Tools         
  Git         2.37.2
  RVM         1.29.12 (manual)
  rbenv       rbenv 1.2.0-48-g6717c62
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           23ec5b8501
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
<No /home/phoenix/Documents/Programming/ruby/todoapp/Gemfile.lock found>
```

**Comment by simi** [comment]
As mentioned you need to use `sudo` or install to other place (like home using `--user-install`). It seems you're using bundler (it is not clear which command you started, looking at backtrace it was kind of `bundle install`). You can specify other directory to install gems to. Feel free to try with following.

```bash
bundle config set --local path 'vendor/bundle'
bundle install
```

That will install gems into `vendor/bundle` directory (which is kind of unwritten standard for local installation).

**Comment by deivid-rodriguez** [comment]
I think your Ruby installation is messed up because RVM paths appear on the stack trace, but the Ruby executable lives in a Rbenv-owned path. I recommended completely removing RVM and the `gem-wrappers` gem and try again.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
