### ISSUE TITLE
NoMethodError: undefined method `full_name' for nil:NilClass

### ISSUE THREAD

**Issue by eabartlett** [rubygems/rubygems#6094]
```
#0 68.85 NoMethodError: undefined method `full_name' for nil:NilClass
#0 68.85
#0 68.85   warning << "* #{unmet_spec_dependency}, depended upon #{spec.full_name}, unsatisfied by #{@specs.find {|s| s.name == unmet_spec_dependency.name && !unmet_spec_dependency.matches_spec?(s.spec) }.full_name}"
#0 68.85                                                                                                                                                                                                    ^^^^^^^^^^
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:123:in `each'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:122:in `each'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:100:in `call'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:71:in `call'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer.rb:259:in `install_in_parallel'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer.rb:209:in `install'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer.rb:89:in `block in run'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/process_lock.rb:12:in `block in lock'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/process_lock.rb:9:in `open'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/process_lock.rb:9:in `lock'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer.rb:71:in `run'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/installer.rb:23:in `install'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/cli/install.rb:62:in `run'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/cli.rb:255:in `block in install'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/settings.rb:131:in `temporary'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/cli.rb:254:in `install'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
#0 68.85   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.3/libexec/bundle:48:in `block in <top (required)>'
#0 68.85   /usr/local/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
#0 68.85   /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.3/libexec/bundle:36:in `<top (required)>'
#0 68.85   /usr/local/bundle/bin/bundle:25:in `load'
#0 68.85   /usr/local/bundle/bin/bundle:25:in `<main>'
#0 68.85 ```
#0 68.85
#0 68.85 ## Environment
#0 68.85
#0 68.85 ```
#0 68.85 Bundler       2.3.3
#0 68.85   Platforms   ruby, aarch64-linux
#0 68.85 Ruby          3.1.0p0 (2021-12-25 revision fb4df44d1670e9d25aef6b235a7281199a177edb) [aarch64-linux]
#0 68.85   Full Path   /usr/local/bin/ruby
#0 68.85   Config Dir  /usr/local/etc
#0 68.85 RubyGems      3.3.3
#0 68.85   Gem Home    /usr/local/bundle
#0 68.85   Gem Path    /home/accountaim/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/bundle
#0 68.85   User Home   /home/accountaim
#0 68.85   User Path   /home/accountaim/.local/share/gem/ruby/3.1.0
#0 68.85   Bin Dir     /usr/local/bundle/bin
#0 68.85 OpenSSL
#0 68.85   Compiled    OpenSSL 1.1.1k  25 Mar 2021
#0 68.85   Loaded      OpenSSL 1.1.1k  25 Mar 2021
#0 68.85   Cert File   /usr/lib/ssl/cert.pem
#0 68.85   Cert Dir    /usr/lib/ssl/certs
#0 68.85 Tools
#0 68.85   Git         2.30.2
#0 68.85   RVM         not installed
#0 68.85   rbenv       not installed
#0 68.85   chruby      not installed
#0 68.85 ```
#0 68.85
#0 68.85 ## Bundler Build Metadata
#0 68.85
#0 68.85 ```
#0 68.85 Built At          2022-12-01
#0 68.85 Git SHA           unknown
#0 68.85 Released Version  false
#0 68.85 ```
#0 68.85
#0 68.85 ## Bundler settings
#0 68.85
#0 68.85 ```
#0 68.85 app_config
#0 68.85   Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
#0 68.85 retry
#0 68.85   Set via BUNDLE_RETRY: 5
#0 68.85 silence_root_warning
#0 68.85   Set via BUNDLE_SILENCE_ROOT_WARNING: true
#0 68.85 ```
#0 68.85
#0 68.85 ## Gemfile
#0 68.85
#0 68.85 ### Gemfile
#0 68.85
#0 68.85 ```ruby
#0 68.85 # frozen_string_literal: true
#0 68.85
#0 68.85 source 'https://rubygems.org'
#0 68.85 git_source(:github) { |repo| "https://github.com/#{repo}.git" }
#0 68.85
#0 68.85 ruby File.read('.ruby-version').strip
#0 68.85
#0 68.85 # Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
#0 68.85 gem 'rails', '~> 7.0.4'
#0 68.85
#0 68.85 # The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
#0 68.85 gem 'sprockets-rails'
#0 68.85
#0 68.85 # Use sqlite3 as the database for Active Record
#0 68.85 gem 'pg'
#0 68.85
#0 68.85 # Use the Puma web server [https://github.com/puma/puma]
#0 68.85 gem 'puma', '~> 5.0'
#0 68.85
#0 68.85 # Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
#0 68.85 gem 'importmap-rails'
#0 68.85
#0 68.85 # Hotwire"s SPA-like page accelerator [https://turbo.hotwired.dev]
#0 68.85 gem 'turbo-rails'
#0 68.85
#0 68.85 # Hotwire"s modest JavaScript framework [https://stimulus.hotwired.dev]
#0 68.85 gem 'stimulus-rails'
#0 68.85
#0 68.85 # Build JSON APIs with ease [https://github.com/rails/jbuilder]
#0 68.85 gem 'jbuilder'
#0 68.85
#0 68.85 # Reusable Components
#0 68.85 gem 'view_components'
#0 68.85
#0 68.85 # ActiveStorage validations library
#0 68.85 gem 'activestorage-validator'
#0 68.85
#0 68.85 # Sorbet gems
#0 68.85 gem 'sorbet', group: :development
#0 68.85 gem 'sorbet-rails'
#0 68.85 gem 'sorbet-runtime'
#0 68.85 gem 'tapioca', require: false, group: :development
#0 68.85
#0 68.85 # rubocop
#0 68.85 gem 'overcommit'
#0 68.85 gem 'rubocop'
#0 68.85
#0 68.85 # 3rd Party API clients
#0 68.85 gem 'stytch'
#0 68.85 gem "google-cloud-storage", "~> 1.11", require: false
#0 68.85
#0 68.85 # for session storage and management
#0 68.85 gem 'activerecord-session_store'
#0 68.85
#0 68.85 # Use Redis adapter to run Action Cable in production
#0 68.85 # gem "redis", "~> 4.0"
#0 68.85
#0 68.85 # Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
#0 68.85 # gem "kredis"
#0 68.85
#0 68.85 # Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
#0 68.85 # gem "bcrypt", "~> 3.1.7"
#0 68.85
#0 68.85 # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#0 68.85 gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
#0 68.85
#0 68.85 # Reduces boot times through caching; required in config/boot.rb
#0 68.85 gem 'bootsnap', require: false
#0 68.85
#0 68.85 # Use Sass to process CSS
#0 68.85 # gem "sassc-rails"
#0 68.85
#0 68.85 # Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
#0 68.85 # gem "image_processing", "~> 1.2"
#0 68.85
#0 68.85 group :development, :test do
#0 68.85   # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
#0 68.85   gem 'debug', platforms: %i[mri mingw x64_mingw]
#0 68.85
#0 68.85   gem 'minitest-rails'
#0 68.85   gem 'factory_bot_rails'
#0 68.85 end
#0 68.85
#0 68.85 group :development do
#0 68.85   # Use console on exceptions pages [https://github.com/rails/web-console]
#0 68.85   gem 'web-console'
#0 68.85
#0 68.85   # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
#0 68.85   # gem "rack-mini-profiler"
#0 68.85
#0 68.85   # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
#0 68.85   # gem "spring"
#0 68.85 end
#0 68.85
#0 68.85 group :test do
#0 68.85   # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
#0 68.85   gem 'capybara'
#0 68.85   gem 'selenium-webdriver'
#0 68.85   gem 'webdrivers'
#0 68.85 end
#0 68.85
#0 68.85 gem "sidekiq", "~> 7.0"
#0 68.85
#0 68.85 gem "activejob-uniqueness", "~> 0.2.4"
#0 68.85
#0 68.85 gem 'jsbundling-rails'  # needed for bootstrap javascript
#0 68.85 gem 'cssbundling-rails' # Install bootstrap 5
#0 68.85
#0 68.85 gem "algorithms", "~> 1.0"
#0 68.85 ```
#0 68.85
#0 68.85 ### Gemfile.lock
#0 68.85
#0 68.85 ```
#0 68.85 GEM
#0 68.85   remote: https://rubygems.org/
#0 68.85   specs:
#0 68.85     actioncable (7.0.4)
#0 68.85       actionpack (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       nio4r (~> 2.0)
#0 68.85       websocket-driver (>= 0.6.1)
#0 68.85     actionmailbox (7.0.4)
#0 68.85       actionpack (= 7.0.4)
#0 68.85       activejob (= 7.0.4)
#0 68.85       activerecord (= 7.0.4)
#0 68.85       activestorage (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       mail (>= 2.7.1)
#0 68.85       net-imap
#0 68.85       net-pop
#0 68.85       net-smtp
#0 68.85     actionmailer (7.0.4)
#0 68.85       actionpack (= 7.0.4)
#0 68.85       actionview (= 7.0.4)
#0 68.85       activejob (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       mail (~> 2.5, >= 2.5.4)
#0 68.85       net-imap
#0 68.85       net-pop
#0 68.85       net-smtp
#0 68.85       rails-dom-testing (~> 2.0)
#0 68.85     actionpack (7.0.4)
#0 68.85       actionview (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       rack (~> 2.0, >= 2.2.0)
#0 68.85       rack-test (>= 0.6.3)
#0 68.85       rails-dom-testing (~> 2.0)
#0 68.85       rails-html-sanitizer (~> 1.0, >= 1.2.0)
#0 68.85     actiontext (7.0.4)
#0 68.85       actionpack (= 7.0.4)
#0 68.85       activerecord (= 7.0.4)
#0 68.85       activestorage (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       globalid (>= 0.6.0)
#0 68.85       nokogiri (>= 1.8.5)
#0 68.85     actionview (7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       builder (~> 3.1)
#0 68.85       erubi (~> 1.4)
#0 68.85       rails-dom-testing (~> 2.0)
#0 68.85       rails-html-sanitizer (~> 1.1, >= 1.2.0)
#0 68.85     activejob (7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       globalid (>= 0.3.6)
#0 68.85     activejob-uniqueness (0.2.4)
#0 68.85       activejob (>= 4.2, < 7.1)
#0 68.85       redlock (>= 1.2, < 2)
#0 68.85     activemodel (7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85     activerecord (7.0.4)
#0 68.85       activemodel (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85     activerecord-session_store (2.0.0)
#0 68.85       actionpack (>= 5.2.4.1)
#0 68.85       activerecord (>= 5.2.4.1)
#0 68.85       multi_json (~> 1.11, >= 1.11.2)
#0 68.85       rack (>= 2.0.8, < 3)
#0 68.85       railties (>= 5.2.4.1)
#0 68.85     activestorage (7.0.4)
#0 68.85       actionpack (= 7.0.4)
#0 68.85       activejob (= 7.0.4)
#0 68.85       activerecord (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       marcel (~> 1.0)
#0 68.85       mini_mime (>= 1.1.0)
#0 68.85     activestorage-validator (0.2.2)
#0 68.85       rails (>= 6.0.4.1)
#0 68.85     activesupport (7.0.4)
#0 68.85       concurrent-ruby (~> 1.0, >= 1.0.2)
#0 68.85       i18n (>= 1.6, < 2)
#0 68.85       minitest (>= 5.1)
#0 68.85       tzinfo (~> 2.0)
#0 68.85     addressable (2.8.1)
#0 68.85       public_suffix (>= 2.0.2, < 6.0)
#0 68.85     aes_key_wrap (1.1.0)
#0 68.85     algorithms (1.0.0)
#0 68.85     ast (2.4.2)
#0 68.85     bindata (2.4.14)
#0 68.85     bindex (0.8.1)
#0 68.85     bootsnap (1.15.0)
#0 68.85       msgpack (~> 1.2)
#0 68.85     builder (3.2.4)
#0 68.85     capybara (3.38.0)
#0 68.85       addressable
#0 68.85       matrix
#0 68.85       mini_mime (>= 0.1.3)
#0 68.85       nokogiri (~> 1.8)
#0 68.85       rack (>= 1.6.0)
#0 68.85       rack-test (>= 0.6.3)
#0 68.85       regexp_parser (>= 1.5, < 3.0)
#0 68.85       xpath (~> 3.2)
#0 68.85     childprocess (4.1.0)
#0 68.85     commander (4.6.0)
#0 68.85       highline (~> 2.0.0)
#0 68.85     concurrent-ruby (1.1.10)
#0 68.85     connection_pool (2.3.0)
#0 68.85     crass (1.0.6)
#0 68.85     cssbundling-rails (1.1.1)
#0 68.85       railties (>= 6.0.0)
#0 68.85     debug (1.6.3)
#0 68.85       irb (>= 1.3.6)
#0 68.85       reline (>= 0.3.1)
#0 68.85     declarative (0.0.20)
#0 68.85     diff-lcs (1.5.0)
#0 68.85     digest-crc (0.6.4)
#0 68.85       rake (>= 12.0.0, < 14.0.0)
#0 68.85     erubi (1.11.0)
#0 68.85     factory_bot (6.2.1)
#0 68.85       activesupport (>= 5.0.0)
#0 68.85     factory_bot_rails (6.2.0)
#0 68.85       factory_bot (~> 6.2.0)
#0 68.85       railties (>= 5.0.0)
#0 68.85     faraday (1.10.2)
#0 68.85       faraday-em_http (~> 1.0)
#0 68.85       faraday-em_synchrony (~> 1.0)
#0 68.85       faraday-excon (~> 1.1)
#0 68.85       faraday-httpclient (~> 1.0)
#0 68.85       faraday-multipart (~> 1.0)
#0 68.85       faraday-net_http (~> 1.0)
#0 68.85       faraday-net_http_persistent (~> 1.0)
#0 68.85       faraday-patron (~> 1.0)
#0 68.85       faraday-rack (~> 1.0)
#0 68.85       faraday-retry (~> 1.0)
#0 68.85       ruby2_keywords (>= 0.0.4)
#0 68.85     faraday-em_http (1.0.0)
#0 68.85     faraday-em_synchrony (1.0.0)
#0 68.85     faraday-excon (1.1.0)
#0 68.85     faraday-httpclient (1.0.1)
#0 68.85     faraday-multipart (1.0.4)
#0 68.85       multipart-post (~> 2)
#0 68.85     faraday-net_http (1.0.1)
#0 68.85     faraday-net_http_persistent (1.2.0)
#0 68.85     faraday-patron (1.0.0)
#0 68.85     faraday-rack (1.0.0)
#0 68.85     faraday-retry (1.0.3)
#0 68.85     faraday_middleware (1.2.0)
#0 68.85       faraday (~> 1.0)
#0 68.85     globalid (1.0.0)
#0 68.85       activesupport (>= 5.0)
#0 68.85     google-apis-core (0.9.1)
#0 68.85       addressable (~> 2.5, >= 2.5.1)
#0 68.85       googleauth (>= 0.16.2, < 2.a)
#0 68.85       httpclient (>= 2.8.1, < 3.a)
#0 68.85       mini_mime (~> 1.0)
#0 68.85       representable (~> 3.0)
#0 68.85       retriable (>= 2.0, < 4.a)
#0 68.85       rexml
#0 68.85       webrick
#0 68.85     google-apis-iamcredentials_v1 (0.16.0)
#0 68.85       google-apis-core (>= 0.9.1, < 2.a)
#0 68.85     google-apis-storage_v1 (0.19.0)
#0 68.85       google-apis-core (>= 0.9.0, < 2.a)
#0 68.85     google-cloud-core (1.6.0)
#0 68.85       google-cloud-env (~> 1.0)
#0 68.85       google-cloud-errors (~> 1.0)
#0 68.85     google-cloud-env (1.6.0)
#0 68.85       faraday (>= 0.17.3, < 3.0)
#0 68.85     google-cloud-errors (1.3.0)
#0 68.85     google-cloud-storage (1.44.0)
#0 68.85       addressable (~> 2.8)
#0 68.85       digest-crc (~> 0.4)
#0 68.85       google-apis-iamcredentials_v1 (~> 0.1)
#0 68.85       google-apis-storage_v1 (~> 0.19.0)
#0 68.85       google-cloud-core (~> 1.6)
#0 68.85       googleauth (>= 0.16.2, < 2.a)
#0 68.85       mini_mime (~> 1.0)
#0 68.85     googleauth (1.3.0)
#0 68.85       faraday (>= 0.17.3, < 3.a)
#0 68.85       jwt (>= 1.4, < 3.0)
#0 68.85       memoist (~> 0.16)
#0 68.85       multi_json (~> 1.11)
#0 68.85       os (>= 0.9, < 2.0)
#0 68.85       signet (>= 0.16, < 2.a)
#0 68.85     highline (2.0.3)
#0 68.85     httpclient (2.8.3)
#0 68.85     i18n (1.12.0)
#0 68.85       concurrent-ruby (~> 1.0)
#0 68.85     importmap-rails (1.1.5)
#0 68.85       actionpack (>= 6.0.0)
#0 68.85       railties (>= 6.0.0)
#0 68.85     iniparse (1.5.0)
#0 68.85     io-console (0.5.11)
#0 68.85     irb (1.5.1)
#0 68.85       reline (>= 0.3.0)
#0 68.85     jbuilder (2.11.5)
#0 68.85       actionview (>= 5.0.0)
#0 68.85       activesupport (>= 5.0.0)
#0 68.85     jsbundling-rails (1.0.3)
#0 68.85       railties (>= 6.0.0)
#0 68.85     json (2.6.2)
#0 68.85     json-jwt (1.15.3)
#0 68.85       activesupport (>= 4.2)
#0 68.85       aes_key_wrap
#0 68.85       bindata
#0 68.85       httpclient
#0 68.85     jwt (2.5.0)
#0 68.85     loofah (2.19.0)
#0 68.85       crass (~> 1.0.2)
#0 68.85       nokogiri (>= 1.5.9)
#0 68.85     mail (2.7.1)
#0 68.85       mini_mime (>= 0.1.1)
#0 68.85     marcel (1.0.2)
#0 68.85     matrix (0.4.2)
#0 68.85     memoist (0.16.2)
#0 68.85     method_source (1.0.0)
#0 68.85     mini_mime (1.1.2)
#0 68.85     minitest (5.16.3)
#0 68.85     minitest-rails (7.0.0)
#0 68.85       minitest (~> 5.10)
#0 68.85       railties (~> 7.0.0)
#0 68.85     msgpack (1.6.0)
#0 68.85     multi_json (1.15.0)
#0 68.85     multipart-post (2.2.3)
#0 68.85     net-imap (0.3.1)
#0 68.85       net-protocol
#0 68.85     net-pop (0.1.2)
#0 68.85       net-protocol
#0 68.85     net-protocol (0.1.3)
#0 68.85       timeout
#0 68.85     net-smtp (0.3.3)
#0 68.85       net-protocol
#0 68.85     netrc (0.11.0)
#0 68.85     nio4r (2.5.8)
#0 68.85     nokogiri (1.13.9-arm64-darwin)
#0 68.85       racc (~> 1.4)
#0 68.85     nokogiri (1.13.9-x86_64-linux)
#0 68.85       racc (~> 1.4)
#0 68.85     os (1.1.4)
#0 68.85     overcommit (0.59.1)
#0 68.85       childprocess (>= 0.6.3, < 5)
#0 68.85       iniparse (~> 1.4)
#0 68.85       rexml (~> 3.2)
#0 68.85     parallel (1.22.1)
#0 68.85     parlour (8.0.0)
#0 68.85       commander (~> 4.5)
#0 68.85       parser
#0 68.85       rainbow (~> 3.0)
#0 68.85       sorbet-runtime (>= 0.5)
#0 68.85     parser (3.1.3.0)
#0 68.85       ast (~> 2.4.1)
#0 68.85     pg (1.4.5)
#0 68.85     polyfill (1.9.0)
#0 68.85     public_suffix (5.0.0)
#0 68.85     puma (5.6.5)
#0 68.85       nio4r (~> 2.0)
#0 68.85     racc (1.6.0)
#0 68.85     rack (2.2.4)
#0 68.85     rack-test (2.0.2)
#0 68.85       rack (>= 1.3)
#0 68.85     rails (7.0.4)
#0 68.85       actioncable (= 7.0.4)
#0 68.85       actionmailbox (= 7.0.4)
#0 68.85       actionmailer (= 7.0.4)
#0 68.85       actionpack (= 7.0.4)
#0 68.85       actiontext (= 7.0.4)
#0 68.85       actionview (= 7.0.4)
#0 68.85       activejob (= 7.0.4)
#0 68.85       activemodel (= 7.0.4)
#0 68.85       activerecord (= 7.0.4)
#0 68.85       activestorage (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       bundler (>= 1.15.0)
#0 68.85       railties (= 7.0.4)
#0 68.85     rails-dom-testing (2.0.3)
#0 68.85       activesupport (>= 4.2.0)
#0 68.85       nokogiri (>= 1.6)
#0 68.85     rails-html-sanitizer (1.4.3)
#0 68.85       loofah (~> 2.3)
#0 68.85     railties (7.0.4)
#0 68.85       actionpack (= 7.0.4)
#0 68.85       activesupport (= 7.0.4)
#0 68.85       method_source
#0 68.85       rake (>= 12.2)
#0 68.85       thor (~> 1.0)
#0 68.85       zeitwerk (~> 2.5)
#0 68.85     rainbow (3.1.1)
#0 68.85     rake (13.0.6)
#0 68.85     rbi (0.0.16)
#0 68.85       ast
#0 68.85       parser (>= 2.6.4.0)
#0 68.85       sorbet-runtime (>= 0.5.9204)
#0 68.85       unparser
#0 68.85     redis (5.0.5)
#0 68.85       redis-client (>= 0.9.0)
#0 68.85     redis-client (0.11.2)
#0 68.85       connection_pool
#0 68.85     redlock (1.3.2)
#0 68.85       redis (>= 3.0.0, < 6.0)
#0 68.85     regexp_parser (2.6.1)
#0 68.85     reline (0.3.1)
#0 68.85       io-console (~> 0.5)
#0 68.85     representable (3.2.0)
#0 68.85       declarative (< 0.1.0)
#0 68.85       trailblazer-option (>= 0.1.1, < 0.2.0)
#0 68.85       uber (< 0.2.0)
#0 68.85     retriable (3.1.2)
#0 68.85     rexml (3.2.5)
#0 68.85     rubocop (1.39.0)
#0 68.85       json (~> 2.3)
#0 68.85       parallel (~> 1.10)
#0 68.85       parser (>= 3.1.2.1)
#0 68.85       rainbow (>= 2.2.2, < 4.0)
#0 68.85       regexp_parser (>= 1.8, < 3.0)
#0 68.85       rexml (>= 3.2.5, < 4.0)
#0 68.85       rubocop-ast (>= 1.23.0, < 2.0)
#0 68.85       ruby-progressbar (~> 1.7)
#0 68.85       unicode-display_width (>= 1.4.0, < 3.0)
#0 68.85     rubocop-ast (1.24.0)
#0 68.85       parser (>= 3.1.1.0)
#0 68.85     ruby-progressbar (1.11.0)
#0 68.85     ruby2_keywords (0.0.5)
#0 68.85     rubyzip (2.3.2)
#0 68.85     safe_type (1.1.1)
#0 68.85     selenium-webdriver (4.6.1)
#0 68.85       childprocess (>= 0.5, < 5.0)
#0 68.85       rexml (~> 3.2, >= 3.2.5)
#0 68.85       rubyzip (>= 1.2.2, < 3.0)
#0 68.85       websocket (~> 1.0)
#0 68.85     sidekiq (7.0.2)
#0 68.85       concurrent-ruby (< 2)
#0 68.85       connection_pool (>= 2.3.0)
#0 68.85       rack (>= 2.2.4)
#0 68.85       redis-client (>= 0.11.0)
#0 68.85     signet (0.17.0)
#0 68.85       addressable (~> 2.8)
#0 68.85       faraday (>= 0.17.5, < 3.a)
#0 68.85       jwt (>= 1.5, < 3.0)
#0 68.85       multi_json (~> 1.10)
#0 68.85     sorbet (0.5.10566)
#0 68.85       sorbet-static (= 0.5.10566)
#0 68.85     sorbet-coerce (0.7.0)
#0 68.85       polyfill (~> 1.8)
#0 68.85       safe_type (~> 1.1, >= 1.1.1)
#0 68.85       sorbet-runtime (>= 0.4.4704)
#0 68.85     sorbet-rails (0.7.34)
#0 68.85       method_source (>= 0.9.2)
#0 68.85       parlour (>= 4.0.1)
#0 68.85       parser (>= 2.7)
#0 68.85       sorbet-coerce (>= 0.2.6)
#0 68.85       sorbet-runtime (>= 0.5.9892)
#0 68.85     sorbet-runtime (0.5.10566)
#0 68.85     sorbet-static (0.5.10566-universal-darwin-21)
#0 68.85     sorbet-static (0.5.10566-x86_64-linux)
#0 68.85     sorbet-static-and-runtime (0.5.10566)
#0 68.85       sorbet (= 0.5.10566)
#0 68.85       sorbet-runtime (= 0.5.10566)
#0 68.85     spoom (1.1.13)
#0 68.85       sorbet (>= 0.5.9204)
#0 68.85       sorbet-runtime (>= 0.5.9204)
#0 68.85       thor (>= 0.19.2)
#0 68.85     sprockets (4.1.1)
#0 68.85       concurrent-ruby (~> 1.0)
#0 68.85       rack (> 1, < 3)
#0 68.85     sprockets-rails (3.4.2)
#0 68.85       actionpack (>= 5.2)
#0 68.85       activesupport (>= 5.2)
#0 68.85       sprockets (>= 3.0.0)
#0 68.85     stimulus-rails (1.2.1)
#0 68.85       railties (>= 6.0.0)
#0 68.85     stytch (4.0.0)
#0 68.85       faraday (>= 0.17.0, < 2.0)
#0 68.85       faraday_middleware (>= 0.14.0, < 2.0)
#0 68.85       json-jwt (>= 1.13.0)
#0 68.85       jwt (>= 2.3.0)
#0 68.85     tapioca (0.10.3)
#0 68.85       bundler (>= 1.17.3)
#0 68.85       netrc (>= 0.11.0)
#0 68.85       parallel (>= 1.21.0)
#0 68.85       rbi (~> 0.0.0, >= 0.0.16)
#0 68.85       sorbet-static-and-runtime (>= 0.5.9892)
#0 68.85       spoom (~> 1.1.0, >= 1.1.11)
#0 68.85       thor (>= 1.2.0)
#0 68.85       yard-sorbet
#0 68.85     thor (1.2.1)
#0 68.85     timeout (0.3.0)
#0 68.85     trailblazer-option (0.1.2)
#0 68.85     turbo-rails (1.3.2)
#0 68.85       actionpack (>= 6.0.0)
#0 68.85       activejob (>= 6.0.0)
#0 68.85       railties (>= 6.0.0)
#0 68.85     tzinfo (2.0.5)
#0 68.85       concurrent-ruby (~> 1.0)
#0 68.85     uber (0.1.0)
#0 68.85     unicode-display_width (2.3.0)
#0 68.85     unparser (0.6.5)
#0 68.85       diff-lcs (~> 1.3)
#0 68.85       parser (>= 3.1.0)
#0 68.85     view_components (0.1.0)
#0 68.85       rails
#0 68.85     web-console (4.2.0)
#0 68.85       actionview (>= 6.0.0)
#0 68.85       activemodel (>= 6.0.0)
#0 68.85       bindex (>= 0.4.0)
#0 68.85       railties (>= 6.0.0)
#0 68.85     webdrivers (5.2.0)
#0 68.85       nokogiri (~> 1.6)
#0 68.85       rubyzip (>= 1.3.0)
#0 68.85       selenium-webdriver (~> 4.0)
#0 68.85     webrick (1.7.0)
#0 68.85     websocket (1.2.9)
#0 68.85     websocket-driver (0.7.5)
#0 68.85       websocket-extensions (>= 0.1.0)
#0 68.85     websocket-extensions (0.1.5)
#0 68.85     xpath (3.2.0)
#0 68.85       nokogiri (~> 1.8)
#0 68.85     yard (0.9.28)
#0 68.85       webrick (~> 1.7.0)
#0 68.85     yard-sorbet (0.7.0)
#0 68.85       sorbet-runtime (>= 0.5)
#0 68.85       yard (>= 0.9)
#0 68.85     zeitwerk (2.6.6)
#0 68.85
#0 68.85 PLATFORMS
#0 68.85   arm64-darwin-21
#0 68.85   x86_64-linux
#0 68.85
#0 68.85 DEPENDENCIES
#0 68.85   activejob-uniqueness (~> 0.2.4)
#0 68.85   activerecord-session_store
#0 68.85   activestorage-validator
#0 68.85   algorithms (~> 1.0)
#0 68.85   bootsnap
#0 68.85   capybara
#0 68.85   cssbundling-rails
#0 68.85   debug
#0 68.85   factory_bot_rails
#0 68.85   google-cloud-storage (~> 1.11)
#0 68.85   importmap-rails
#0 68.85   jbuilder
#0 68.85   jsbundling-rails
#0 68.85   minitest-rails
#0 68.85   overcommit
#0 68.85   pg
#0 68.85   puma (~> 5.0)
#0 68.85   rails (~> 7.0.4)
#0 68.85   rubocop
#0 68.85   selenium-webdriver
#0 68.85   sidekiq (~> 7.0)
#0 68.85   sorbet
#0 68.85   sorbet-rails
#0 68.85   sorbet-runtime
#0 68.85   sprockets-rails
#0 68.85   stimulus-rails
#0 68.85   stytch
#0 68.85   tapioca
#0 68.85   turbo-rails
#0 68.85   tzinfo-data
#0 68.85   view_components
#0 68.85   web-console
#0 68.85   webdrivers
#0 68.85
#0 68.85 RUBY VERSION
#0 68.85    ruby 3.1.0p0
#0 68.85
#0 68.85 BUNDLED WITH
#0 68.85    2.3.3
#0 68.85 ```

**Comment by deivid-rodriguez** [comment]
This issue is most likely fixed in the latest Bundler version. Please follow upgrade instructions as advised in the issue template, thanks!

**Comment by adisciple50** [comment]
gem install bunder. worked for me
