### ISSUE TITLE
problem about sifdecode

### ISSUE THREAD

**Issue by pangtai6** [rubygems/rubygems#6095]
My computer is a mac, version 11. The following error occurs when running： brew test sifdecode.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/74003099/205296839-38888a98-506d-4450-84d5-17c53aee49a1.png">
Would you please let me know how to correct it? I would be very grateful to you.

**Comment by deivid-rodriguez** [comment]
Hi, could you please copy-paste the full error report? Thanks.

**Comment by pangtai6** [comment]
Last login: Thu Dec  1 20:32:27 on console
pangtai@pangtaideMacBook-Pro ~ % brew test sifdecode
==> Installing 'bundler' gem
Fetching bundler-2.3.26.gem
Ignoring bootsnap-1.11.1 because its extensions are not built. Try: gem pristine bootsnap --version 1.11.1
Ignoring byebug-11.1.3 because its extensions are not built. Try: gem pristine byebug --version 11.1.3
Ignoring hpricot-0.8.6 because its extensions are not built. Try: gem pristine hpricot --version 0.8.6
Ignoring msgpack-1.4.5 because its extensions are not built. Try: gem pristine msgpack --version 1.4.5
Ignoring racc-1.6.0 because its extensions are not built. Try: gem pristine racc --version 1.6.0
Ignoring rdiscount-2.2.0.2 because its extensions are not built. Try: gem pristine rdiscount --version 2.2.0.2
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Fetching gem metadata from https://rubygems.org/.......
Using concurrent-ruby 1.1.10
Fetching minitest 5.16.3
Fetching zeitwerk 2.6.6
Fetching public_suffix 5.0.0
Using ast 2.4.2
Fetching bindata 2.4.14
Installing zeitwerk 2.6.6
Fetching msgpack 1.6.0
Installing public_suffix 5.0.0
Using bundler 2.3.26
Installing byebug 11.1.3 with native extensions
Fetching connection_pool 2.3.0
Installing minitest 5.16.3
Installing bindata 2.4.14
Using did_you_mean 1.6.1
Using diff-lcs 1.5.0
Using docile 1.4.0
Fetching unf_ext 0.0.8.2
Fetching regexp_parser 2.6.1
Installing connection_pool 2.3.0
Using hana 1.3.7
Installing hpricot 0.8.6 with native extensions
Fetching json 2.6.2
Installing regexp_parser 2.6.1
Installing unf_ext 0.0.8.2 with native extensions
Installing json 2.6.2 with native extensions
Installing msgpack 1.6.0 with native extensions
Using uri_template 0.7.0
Using mime-types-data 3.2022.0105
Using net-http-digest_auth 1.4.1
Installing racc 1.6.0 with native extensions
Using rubyntlm 0.6.3
Using webrick 1.7.0
Using webrobots 0.1.2
Using mustache 1.1.1
Using parallel 1.22.1
Using plist 3.6.0
Fetching rack 3.0.1
Installing rack 3.0.1
Using rainbow 3.1.1
Fetching rdiscount 2.2.7
Installing rdiscount 2.2.7 with native extensions
Using rexml 3.2.5
Fetching rspec-support 3.12.0
Installing rspec-support 3.12.0
Fetching sorbet-runtime 0.5.10461
Installing sorbet-runtime 0.5.10461
Using ruby-progressbar 1.11.0
Fetching unicode-display_width 2.3.0
Installing unicode-display_width 2.3.0
Using ruby-macho 3.0.0
Using simplecov-html 0.12.3
Using simplecov_json_formatter 0.1.4
Fetching warning 1.3.0
Installing warning 1.3.0
Fetching i18n 1.12.0
Installing i18n 1.12.0
Fetching tzinfo 2.0.5
Installing tzinfo 2.0.5
Fetching parser 3.1.2.1
Installing parser 3.1.2.1
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
ArgumentError: parent directory is world writable, Bundler::FileUtils#remove_entry_secure does not work; abort: "/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.6" (parent directory mode 40777)
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/vendor/fileutils/lib/fileutils.rb:702:in `remove_entry_secure'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler.rb:330:in `rm_rf'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:111:in `strict_rm_rf'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:19:in `install'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in `install'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `loop'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.3.26
  Platforms   ruby, x86_64-darwin-15
Ruby          2.6.8p205 (2021-07-07 revision 67951) [x86_64-darwin-15]
  Full Path   /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
  Config Dir  /usr/local/Cellar/portable-ruby/2.6.8_1/etc
RubyGems      3.0.3.1
  Gem Home    /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0
  Gem Path    /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0
  User Home   /Users/pangtai
  User Path   /Users/pangtai/.gem/ruby/2.6.0
  Bin Dir     /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1o  3 May 2022
  Loaded      OpenSSL 1.1.1o  3 May 2022
  Cert File   /usr/local/Cellar/portable-openssl/1.1.1o/libexec/etc/openssl/cert.pem
  Cert Dir    /usr/local/Cellar/portable-openssl/1.1.1o/libexec/etc/openssl/certs
Tools         
  Git         2.38.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           23ec5b8501
Released Version  true
```

## Bundler settings

```
bin
  Set for your local app (/usr/local/Homebrew/Library/Homebrew/.bundle/config): false
clean
  Set for your local app (/usr/local/Homebrew/Library/Homebrew/.bundle/config): true
disable_shared_gems
  Set for your local app (/usr/local/Homebrew/Library/Homebrew/.bundle/config): true
forget_cli_options
  Set for your local app (/usr/local/Homebrew/Library/Homebrew/.bundle/config): true
frozen
  Set via BUNDLE_FROZEN: true
gemfile
  Set via BUNDLE_GEMFILE: "/usr/local/Homebrew/Library/Homebrew/Gemfile"
jobs
  Set for your local app (/usr/local/Homebrew/Library/Homebrew/.bundle/config): 4
path
  Set for your local app (/usr/local/Homebrew/Library/Homebrew/.bundle/config): "vendor/bundle"
retry
  Set for your local app (/usr/local/Homebrew/Library/Homebrew/.bundle/config): 3
with
  Set via BUNDLE_WITH: []
```

## Gemfile

### ../../usr/local/Homebrew/Library/Homebrew/Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

if ENV.fetch("HOMEBREW_DEVELOPER", "").empty? || ENV.fetch("HOMEBREW_USE_RUBY_FROM_PATH", "").empty?
  ruby "~> 2.6.0"
else
  ruby ">= 2.6.0"
end

# disallowed gems (should not be used)
# * nokogiri - use rexml instead for XML parsing

# installed gems (should all be require: false)
gem "bootsnap", require: false
gem "byebug", require: false
gem "json_schemer", require: false
gem "minitest", require: false
gem "parallel_tests", require: false
gem "ronn", require: false
gem "rspec", require: false
gem "rspec-github", require: false
gem "rspec-its", require: false
gem "rspec_junit_formatter", require: false
gem "rspec-retry", require: false
gem "rspec-sorbet", require: false
gem "rspec-wait", require: false
gem "rubocop", require: false
gem "rubocop-ast", require: false
gem "simplecov", require: false
gem "simplecov-cobertura", require: false
gem "warning", require: false

group :sorbet, optional: true do
  gem "parlour", require: false
  gem "sorbet-static-and-runtime", require: false
  gem "spoom", require: false
  gem "tapioca", require: false
end

# vendored gems
gem "activesupport"
gem "addressable"
gem "concurrent-ruby"
gem "mechanize"
gem "patchelf"
gem "plist"
gem "rubocop-performance"
gem "rubocop-rails"
gem "rubocop-rspec"
gem "rubocop-sorbet"
gem "ruby-macho"
gem "sorbet-runtime"

# remove when HOMEBREW_REQUIRED_RUBY_VERSION >= 2.7
install_if -> { RUBY_VERSION < "2.7" } do
  gem "did_you_mean"
end
```

### ../../usr/local/Homebrew/Library/Homebrew/Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.1.7)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    ast (2.4.2)
    bindata (2.4.14)
    bootsnap (1.14.0)
      msgpack (~> 1.2)
    byebug (11.1.3)
    coderay (1.1.3)
    commander (4.6.0)
      highline (~> 2.0.0)
    concurrent-ruby (1.1.10)
    connection_pool (2.3.0)
    did_you_mean (1.6.1)
    diff-lcs (1.5.0)
    docile (1.4.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    ecma-re-validator (0.4.0)
      regexp_parser (~> 2.2)
    elftools (1.2.0)
      bindata (~> 2)
    hana (1.3.7)
    highline (2.0.3)
    hpricot (0.8.6)
    http-cookie (1.0.5)
      domain_name (~> 0.5)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    json (2.6.2)
    json_schemer (0.2.23)
      ecma-re-validator (~> 0.3)
      hana (~> 1.3)
      regexp_parser (~> 2.0)
      uri_template (~> 0.7)
    mechanize (2.8.5)
      addressable (~> 2.8)
      domain_name (~> 0.5, >= 0.5.20190701)
      http-cookie (~> 1.0, >= 1.0.3)
      mime-types (~> 3.0)
      net-http-digest_auth (~> 1.4, >= 1.4.1)
      net-http-persistent (>= 2.5.2, < 5.0.dev)
      nokogiri (~> 1.11, >= 1.11.2)
      rubyntlm (~> 0.6, >= 0.6.3)
      webrick (~> 1.7)
      webrobots (~> 0.1.2)
    method_source (1.0.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    mini_portile2 (2.8.0)
    minitest (5.16.3)
    msgpack (1.6.0)
    mustache (1.1.1)
    net-http-digest_auth (1.4.1)
    net-http-persistent (4.0.1)
      connection_pool (~> 2.2)
    nokogiri (1.13.9)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.9-aarch64-linux)
      racc (~> 1.4)
    nokogiri (1.13.9-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.9-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.9-x86_64-linux)
      racc (~> 1.4)
    parallel (1.22.1)
    parallel_tests (3.13.0)
      parallel
    parlour (8.0.0)
      commander (~> 4.5)
      parser
      rainbow (~> 3.0)
      sorbet-runtime (>= 0.5)
    parser (3.1.2.1)
      ast (~> 2.4.1)
    patchelf (1.4.0)
      elftools (>= 1.2)
    plist (3.6.0)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    public_suffix (5.0.0)
    racc (1.6.0)
    rack (3.0.1)
    rainbow (3.1.1)
    rbi (0.0.14)
      ast
      parser (>= 2.6.4.0)
      sorbet-runtime (>= 0.5.9204)
      unparser
    rdiscount (2.2.7)
    regexp_parser (2.6.1)
    rexml (3.2.5)
    ronn (0.7.3)
      hpricot (>= 0.8.2)
      mustache (>= 0.7.0)
      rdiscount (>= 1.5.8)
    rspec (3.12.0)
      rspec-core (~> 3.12.0)
      rspec-expectations (~> 3.12.0)
      rspec-mocks (~> 3.12.0)
    rspec-core (3.12.0)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-github (2.4.0)
      rspec-core (~> 3.0)
    rspec-its (1.3.0)
      rspec-core (>= 3.0.0)
      rspec-expectations (>= 3.0.0)
    rspec-mocks (3.12.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-retry (0.6.2)
      rspec-core (> 3.3)
    rspec-sorbet (1.9.1)
      sorbet-runtime
    rspec-support (3.12.0)
    rspec-wait (0.0.9)
      rspec (>= 3, < 4)
    rspec_junit_formatter (0.6.0)
      rspec-core (>= 2, < 4, != 2.12.0)
    rubocop (1.35.1)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.1.2.1)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.20.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.23.0)
      parser (>= 3.1.1.0)
    rubocop-performance (1.15.1)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rails (2.17.3)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
    rubocop-rspec (2.15.0)
      rubocop (~> 1.33)
    rubocop-sorbet (0.6.11)
      rubocop (>= 0.90.0)
    ruby-macho (3.0.0)
    ruby-progressbar (1.11.0)
    rubyntlm (0.6.3)
    simplecov (0.21.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-cobertura (2.1.0)
      rexml
      simplecov (~> 0.19)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.4)
    sorbet (0.5.10461)
      sorbet-static (= 0.5.10461)
    sorbet-runtime (0.5.10461)
    sorbet-static (0.5.10461-universal-darwin-14)
    sorbet-static (0.5.10461-universal-darwin-15)
    sorbet-static (0.5.10461-universal-darwin-16)
    sorbet-static (0.5.10461-universal-darwin-17)
    sorbet-static (0.5.10461-universal-darwin-18)
    sorbet-static (0.5.10461-universal-darwin-19)
    sorbet-static (0.5.10461-universal-darwin-20)
    sorbet-static (0.5.10461-universal-darwin-21)
    sorbet-static (0.5.10461-universal-darwin-22)
    sorbet-static (0.5.10461-x86_64-linux)
    sorbet-static-and-runtime (0.5.10461)
      sorbet (= 0.5.10461)
      sorbet-runtime (= 0.5.10461)
    spoom (1.1.11)
      sorbet (>= 0.5.9204)
      sorbet-runtime (>= 0.5.9204)
      thor (>= 0.19.2)
    tapioca (0.7.3)
      bundler (>= 1.17.3)
      pry (>= 0.12.2)
      rbi (~> 0.0.0, >= 0.0.14)
      sorbet-runtime (>= 0.5.9204)
      sorbet-static (>= 0.5.9204)
      spoom (~> 1.1.0, >= 1.1.11)
      thor (>= 1.2.0)
      yard-sorbet
    thor (1.2.1)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8.2)
    unicode-display_width (2.3.0)
    unparser (0.6.4)
      diff-lcs (~> 1.3)
      parser (>= 3.1.0)
    uri_template (0.7.0)
    warning (1.3.0)
    webrick (1.7.0)
    webrobots (0.1.2)
    yard (0.9.28)
      webrick (~> 1.7.0)
    yard-sorbet (0.6.1)
      sorbet-runtime (>= 0.5)
      yard (>= 0.9)
    zeitwerk (2.6.6)

PLATFORMS
  aarch64-linux
  arm-linux
  arm64-darwin
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  activesupport
  addressable
  bootsnap
  byebug
  concurrent-ruby
  did_you_mean
  json_schemer
  mechanize
  minitest
  parallel_tests
  parlour
  patchelf
  plist
  ronn
  rspec
  rspec-github
  rspec-its
  rspec-retry
  rspec-sorbet
  rspec-wait
  rspec_junit_formatter
  rubocop
  rubocop-ast
  rubocop-performance
  rubocop-rails
  rubocop-rspec
  rubocop-sorbet
  ruby-macho
  simplecov
  simplecov-cobertura
  sorbet-runtime
  sorbet-static-and-runtime
  spoom
  tapioca
  warning

RUBY VERSION
   ruby 2.6.8p205

BUNDLED WITH
   2.3.26
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=parent+directory+is+world+writable%2C+Bundler++FileUtils%23remove_entry_secure+does+not+work%3B+abort++%22%2Fusr%2Flocal%2FHomebrew%2FLibrary%2FHomebrew%2Fvendor%2Fbundle%2Fruby%2F2.6.0%2Fgems%2Fzeitwerk-2.6.6%22+%28parent+directory+mode+40777%29&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
Error: failed to run `/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle install`!
pangtai@pangtaideMacBook-Pro ~ %

**Comment by pangtai6** [comment]
> 

All the commands are here. They're long. They're running correctly up front. Thank you for your trouble.

**Comment by pangtai6** [comment]
I have not changed the access permission, but I would like to ask you how to change it back to 755 permission.

**Comment by pangtai6** [comment]
I have not changed the access permission, but I would like to ask you how to change it back to 755 permission.

**Comment by deivid-rodriguez** [comment]
I googled this for you: https://www.macinstruct.com/tutorials/how-to-set-file-permissions-on-a-mac/. Good luck!

It's strange that this happens if you didn't change any permissions. How did you install Ruby? What is "sifdecode"?

**Comment by deivid-rodriguez** [comment]
I'm going to close this due to lack of feedback, feel free to reopen if you're still running into this and would like to provide more information!

**Comment by scientificworld** [comment]
Also meet this problem. You can solve it by changing the mode of `gems` directory to 755.
