### ISSUE TITLE
bundle install issue

### ISSUE THREAD

**Issue by aarn-1** [rubygems/rubygems#6103]
### Describe the problem as clearly as you can

Trying to create a Github Pages site with Jekyll (https://docs.github.com/de/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll?platform=windows#creating-your-site -> Step 12). On windows 10 in case it matters...

### Did you try upgrading rubygems & bundler?

Just installed the newest versions for the first time (6.12.2022)

### Post steps to reproduce the problem

Everything in the following guide until the error in step 12
https://docs.github.com/de/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll?platform=windows#creating-your-site

### Which command did you run?

bundle install

### What were you expecting to happen?

Installation of the gems specified in my Gemfile

### What actually happened?

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby31-x64/bin/rougify.bat
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:477:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:546:in `generate_bin_script'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:490:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:490:in `generate_bin'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby31-x64/bin/rougify.bat
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:477:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:546:in `generate_bin_script'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:490:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:490:in `generate_bin'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.3.26
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [x64-mingw-ucrt]
  Full Path   C:/Ruby31-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.3.26
  Gem Home    C:/Ruby31-x64/lib/ruby/gems/3.1.0
  Gem Path    C:/Users/xyz/.local/share/gem/ruby/3.1.0;C:/Ruby31-x64/lib/ruby/gems/3.1.0
  User Home   C:/Users/xyz
  User Path   C:/Users/xyz/.local/share/gem/ruby/3.1.0
  Bin Dir     C:/Ruby31-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1s  1 Nov 2022
  Loaded      OpenSSL 1.1.1s  1 Nov 2022
  Cert File   C:/Ruby31-x64/ssl/cert.pem
  Cert Dir    C:/Ruby31-x64/ssl/certs
Tools
  Git         2.29.2.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           asdf
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# gem "jekyll", "~> 4.3.1"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", "~> 227", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```

### Gemfile.lock

```
<No C:/Users/xyz/Desktop/aarn-1/aarn-1.github.io/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by HarrisonAllen** [comment]
I got this error when using Git Bash to try and run `bundle install` on Windows 10. For me, running `bundle install` in a command prompt with administrator privileges seemed to resolve the permission error and complete the install.
