### ISSUE TITLE
"NameError: uninitialized constant Gem::BundlerVersionFinder" encountered during require

### ISSUE THREAD

**Issue by joshuaswett** [rubygems/rubygems#6145]
### Describe the problem as clearly as you can

When running outside of a bundled context and given a particular dependency structure for a gem (more on this in the reproduction steps section), a "NameError: uninitialized constant Gem::BundlerVersionFinder" was encountered during a "require" invocation and this crashed the program.

Here is the stack trace:

```
#<NameError: uninitialized constant Gem::BundlerVersionFinder

    Gem::BundlerVersionFinder.prioritize!(matches) if prioritizes_bundler?
       ^^^^^^^^^^^^^^^^^^^^^^>, ["/home/sanitized/rubygems/lib/rubygems/dependency.rb:280:in `matching_specs'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:2590:in `block in traverse'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `each'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `traverse'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:1067:in `block in find_in_unresolved_tree'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `each'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `find_in_unresolved_tree'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:114:in `require'", "/home/sanitized/rubygems/lib/rubygems/dependency.rb:280:in `matching_specs'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:2590:in `block in traverse'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `each'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `traverse'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:1067:in `block in find_in_unresolved_tree'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `each'", "/home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `find_in_unresolved_tree'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:114:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/generic_object.rb:2:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:3:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "-e:2:in `<main>'"]]
[36689, #<Thread:0x00007fd1a744fcc0 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/generic_object.rb:2:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:3:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "-e:2:in `<main>'"]]
[36689, #<Thread:0x00007fd1a744fcc0 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:3:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "-e:2:in `<main>'"]]
[36689, #<Thread:0x00007fd1a744fcc0 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'", "-e:2:in `<main>'"]]
<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `require'
        from -e:2:in `<main>'
<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from -e:2:in `<main>'
<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:3:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from -e:2:in `<main>'
<internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:167:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/generic_object.rb:2:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:3:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from -e:2:in `<main>'
/home/sanitized/rubygems/lib/rubygems/dependency.rb:280:in `matching_specs': uninitialized constant Gem::BundlerVersionFinder (NameError)

    Gem::BundlerVersionFinder.prioritize!(matches) if prioritizes_bundler?
       ^^^^^^^^^^^^^^^^^^^^^^
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:2590:in `block in traverse'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `each'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `traverse'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:1067:in `block in find_in_unresolved_tree'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `each'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `find_in_unresolved_tree'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:114:in `require'
        from /home/sanitized/rubygems/lib/rubygems/dependency.rb:280:in `matching_specs'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:2590:in `block in traverse'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `each'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:2588:in `traverse'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:1067:in `block in find_in_unresolved_tree'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `each'
        from /home/sanitized/rubygems/lib/rubygems/specification.rb:1066:in `find_in_unresolved_tree'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:114:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/generic_object.rb:2:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:3:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from /home/sanitized/.rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json.rb:2:in `<top (required)>'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/home/sanitized/rubygems/lib/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from -e:2:in `<main>'
```
As best as I can tell, the gems I have installed and the specifics of the dependency structure make it so that BundlerVersionFinder cannot be loaded:  dependency.rb tries to autoload BundlerVersionFinder at an inopportune time and while handling this autoload, the code gets back to a spot where it tries to load BundlerVersionFinder again.

I believe this issue was introduced in https://github.com/rubygems/rubygems/commit/43ceae7ac03d91996d5bcc031c538fe5e232719a.  Before this change, BundlerVersionFinder was explicitly required, and the rare circumstances where the autoloading fails were not possible.  I have verified that this issue can be fixed by restoring the `require "rubygems/bundler_version_finder"` at the top of dependency.rb

This issue was originally discovered while running a program that was requiring some custom gems.  To provide a simpler means of reproducing this, I boiled it down to a test that can be run in the project test suite.

### Did you try upgrading RubyGems?

Yes.  This issue is reproducible on the latest version of rubygems (3.3.26) and on the master branch (as of commit 57cb5e74fcfb26a970ce10d59e72ded3fa70bece)

### Post steps to reproduce the problem

I created this test that is able to reproduce the issue.  If you put this in test/rubygems/test_require.rb and run the tests, you should get the failure (the name of the test is written such that this test could be added once a fix is in place):

```
  def test_require_does_not_crash_when_utilizing_bundler_version_finder
    a1 = util_spec "a", "1.1", { "bundler" => ">= 0" }
    a2 = util_spec "a", "1.2", { "bundler" => ">= 0" }
    b1 = util_spec "bundler", "2.3.7"
    b2 = util_spec "bundler", "2.3.24"
    c = util_spec "c", "1", { "a" => [">= 1.1", "< 99.0"] }, "lib/test_gem_require_c.rb"

    install_specs a1, a2, b1, b2, c

    cmd = <<-RUBY
      require "test_gem_require_c"
      require "json"
    RUBY
    Gem::Util.popen({ "GEM_HOME" => @gemhome }, *ruby_with_rubygems_in_load_path, "-e", cmd)
    assert $?.success?
  end
```
There are some aspects of your Ruby environment that may cause this test to not fail, and I am currently unsure why.  Here is an environment that I have found capable of reproducing the issue:
* Ubuntu 22.04
* Ruby 3.1.2 installed via RVM
* You can run `gem update --system` to update Rubygems, but don't update other gems

Even with this minimal environment, I have found that doing a `gem update ostruct:0.5.2` (this is the same version that is installed as a default gem) will cause the issue to not happen anymore.  I am not sure why this changes the result, but it seems to be related to ostruct being installed as a default gem vs. being installed with `gem update ostruct:0.5.2`.  I would guess this small environmental change causes BundlerVersionFinder to be loaded at an earlier time, thereby getting around the issue.

### Which command did you run?

After adding the test mentioned above, I ran `ruby -Ilib:test:bundler/lib test/rubygems/test_require.rb` and this new test failed.

### What were you expecting to happen?

I was expecting the test to pass, and in older versions of Rubygems, this crash did not happen.

### What actually happened?

The test failed.  See the stack trace posted above.

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.26
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/sanitized/.rvm/gems/ruby-3.1.2
  - USER INSTALLATION DIRECTORY: /home/sanitized/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /home/sanitized/.rvm/rubies/ruby-3.1.2/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/sanitized/.rvm/gems/ruby-3.1.2/bin
  - SPEC CACHE DIRECTORY: /home/sanitized/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/sanitized/.rvm/gems/ruby-3.1.2
     - /home/sanitized/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/sanitized/bin
     - /home/sanitized/.rvm/gems/ruby-3.1.2/bin
     - /home/sanitized/.rvm/gems/ruby-3.1.2@global/bin
     - /home/sanitized/.rvm/rubies/ruby-3.1.2/bin
     - /home/sanitized/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
     - /snap/bin
     - /home/sanitized/.rvm/bin
     - /home/sanitized/.rvm/bin
     - /home/sanitized/.rvm/bin
     - /home/sanitized/.rvm/bin
```

**Comment by deivid-rodriguez** [comment]
Thanks for the report and investigation! The issue does repro for me with your test.

I guess we can have the same effect of autoloading by requiring `bundler_version_finder` right before using it:

```diff
diff --git a/lib/rubygems.rb b/lib/rubygems.rb
index 0c0ca9c1ba..5e6818860b 100644
--- a/lib/rubygems.rb
+++ b/lib/rubygems.rb
@@ -1297,7 +1297,6 @@ def default_gem_load_paths
 
   MARSHAL_SPEC_DIR = "quick/Marshal.#{Gem.marshal_version}/".freeze
 
-  autoload :BundlerVersionFinder, File.expand_path("rubygems/bundler_version_finder", __dir__)
   autoload :ConfigFile,         File.expand_path("rubygems/config_file", __dir__)
   autoload :Dependency,         File.expand_path("rubygems/dependency", __dir__)
   autoload :DependencyList,     File.expand_path("rubygems/dependency_list", __dir__)
diff --git a/lib/rubygems/dependency.rb b/lib/rubygems/dependency.rb
index 85f8609677..7fa0f91bd4 100644
--- a/lib/rubygems/dependency.rb
+++ b/lib/rubygems/dependency.rb
@@ -277,7 +277,10 @@ def matching_specs(platform_only = false)
       requirement.satisfied_by?(spec.version) && env_req.satisfied_by?(spec.version)
     end.map(&:to_spec)
 
-    Gem::BundlerVersionFinder.prioritize!(matches) if prioritizes_bundler?
+    if prioritizes_bundler?
+      require_relative "bundler_version_finder"
+      Gem::BundlerVersionFinder.prioritize!(matches)
+    end
 
     if platform_only
       matches.reject! do |spec|
```

 Can you send us a PR with the fix and the test?

**Comment by deivid-rodriguez** [comment]
Since we plan to ship this fix imminently, I early created the PR myself at #6152.

**Comment by joshuaswett** [comment]
Thank you for taking a look at this and preparing a PR so quickly!

**Comment by deivid-rodriguez** [comment]
No problem, thanks to you for making it straightforward!
