### ISSUE TITLE
Windows - very recent TestGemExtCargoBuilder failures

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#6190]
This morning, ruby-loco's Windows Ruby head builds (using `ruby 3.2.0dev (2022-12-24T08:54:21Z master d521c9e5a7)`), all failed running `test_gem_ext_cargo_builder.rb`.  Previously, the tests in the file often failed when run parallel, but passed when run 'serial'.

Below is output from serial run.  Any ideas?  I'm very rust challenged...

<details>
  <summary>Test output</summary>

```
[116/120] TestGemExtCargoBuilder#test_rubygems_cfg_passed_to_rustc["current directory: /ruby/test/tmp/test_rubygems_20221224-2144-869nzs/ext",
 "cargo rustc --crate-type cdylib --target-dir /ruby/test/tmp/test_rubygems_20221224-2144-869nzs/prefix --manifest-path /ruby/test/tmp/test_rubygems_20221224-2144-869nzs/ext/Cargo.toml --lib --profile release --locked -- -C linker\\=x86_64-w64-mingw32-cc -L native\\=/ruby-ucrt/lib -C link-args\\=-l:libssp.a -C link-args\\=-l:libz.a -C link-args\\=-pipe -C link-args\\=-fstack-protector-strong -C link-args\\=-s -C link-args\\=-Wl,--enable-auto-image-base,--enable-auto-import -l shell32 -l ws2_32 -l iphlpapi -l imagehlp -l shlwapi -l bcrypt -l x64-ucrt-ruby320 -C link-arg\\=-Wl,--dynamicbase -C link-arg\\=-Wl,--disable-auto-image-base -C link-arg\\=-static-libgcc",
 "   Compiling memchr v2.5.0\n" +
 "   Compiling winapi-x86_64-pc-windows-gnu v0.4.0\n" +
 "   Compiling winapi v0.3.9\n" +
 "   Compiling glob v0.3.0\n" +
 "   Compiling proc-macro2 v1.0.47\n" +
 "   Compiling clang-sys v1.4.0\n" +
 "   Compiling libc v0.2.138\n" +
 "   Compiling minimal-lexical v0.2.1\n" +
 "   Compiling unicode-ident v1.0.5\n" +
 "   Compiling quote v1.0.21\n" +
 "   Compiling libloading v0.7.4\n" +
 "   Compiling nom v7.1.1\n" +
 "   Compiling aho-corasick v0.7.20\n" +
 "   Compiling bindgen v0.60.1\n" +
 "   Compiling regex-syntax v0.6.28\n" +
 "   Compiling cexpr v0.6.0\n" +
 "   Compiling regex v1.7.0\n" +
 "   Compiling bitflags v1.3.2\n" +
 "   Compiling lazy_static v1.4.0\n" +
 "   Compiling peeking_take_while v0.1.2\n" +
 "   Compiling rustc-hash v1.1.0\n" +
 "   Compiling shlex v1.1.0\n" +
 "   Compiling lazycell v1.3.0\n" +
 "   Compiling shell-words v1.1.0\n" +
 "   Compiling rb-sys-build v0.9.52\n" +
 "   Compiling rb-sys v0.9.52\n" +
 "error: failed to run custom build command for `rb-sys v0.9.52`\n" +
 "\n" +
 "Caused by:\n" +
 "  process didn't exit successfully: `/ruby/test/tmp/test_rubygems_20221224-2144-869nzs/prefix\\release\\build\\rb-sys-c6d6428395a3a7a8\\build-script-main` (exit code: 101)\n" +
 "  --- stdout\n" +
 "  cargo:rerun-if-env-changed=RUBY\n" +
 "  cargo:rerun-if-env-changed=RUBY_ROOT\n" +
 "  cargo:rerun-if-env-changed=RUBY_VERSION\n" +
 "  cargo:rerun-if-env-changed=RUBY\n" +
 "  cargo:rerun-if-changed=wrapper.h\n" +
 "  cargo:rerun-if-changed=build\\features.rs\n" +
 "  cargo:rerun-if-changed=build\\main.rs\n" +
 "  cargo:rerun-if-changed=build\\ruby_macros.rs\n" +
 "  cargo:rerun-if-changed=build\\version.rs\n" +
 "  cargo:rerun-if-env-changed=RUBY_STATIC\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_ENABLE_SHARED\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_rubyhdrdir\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_rubyarchhdrdir\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_CPPFLAGS\n" +
 "\n" +
 "  --- stderr\n" +
 "  Using bindgen with clang args: [\"-I/ruby-ucrt/include/ruby-3.2.0+3\", \"-I/ruby-ucrt/include/ruby-3.2.0+3/x64-mingw-ucrt\", \"-fms-extensions\", \"-O3\", \"-fno-omit-frame-pointer\", \"-fno-fast-math\", \"-ggdb3\", \"-Wall\", \"-Wextra\", \"-Wdeprecated-declarations\", \"-Wdiv-by-zero\", \"-Wduplicated-cond\", \"-Wimplicit-function-declaration\", \"-Wimplicit-int\", \"-Wmisleading-indentation\", \"-Wpointer-arith\", \"-Wwrite-strings\", \"-Wold-style-definition\", \"-Wimplicit-fallthrough=0\", \"-Wmissing-noreturn\", \"-Wno-cast-function-type\", \"-Wno-constant-logical-operand\", \"-Wno-long-long\", \"-Wno-missing-field-initializers\", \"-Wno-overlength-strings\", \"-Wno-packed-bitfield-compat\", \"-Wno-parentheses-equality\", \"-Wno-self-assign\", \"-Wno-tautological-compare\", \"-Wno-unused-parameter\", \"-Wno-unused-value\", \"-Wsuggest-attribute=format\", \"-Wsuggest-attribute=noreturn\", \"-Wunused-variable\", \"-Wundef\"]\n" +
 "  warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wno-packed-bitfield-compat' [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]\n" +
 "  /ruby-ucrt/include/ruby-3.2.0+3\\ruby/defines.h:43:11: fatal error: 'strings.h' file not found\n" +
 "  clang diag: warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wno-packed-bitfield-compat' [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]\n" +
 "  thread 'main' panicked at 'Unable to generate bindings for bindings-raw.rs', C:\\Users\\runneradmin/.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\rb-sys-build-0.9.52\\src\\bindings.rs:136:29\n" +
 "  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"]
 = 26.95 s
[117/120] TestGemExtCargoBuilder#test_full_integration = 0.61 s
[118/120] TestGemExtCargoBuilder#test_custom_name = 0.60 s
[119/120] TestGemExtCargoBuilder#test_build_cdylib["current directory: /ruby/test/tmp/test_rubygems_20221224-2144-yx11c5/ext",
 "cargo rustc --crate-type cdylib --target-dir /ruby/test/tmp/test_rubygems_20221224-2144-yx11c5/prefix --manifest-path /ruby/test/tmp/test_rubygems_20221224-2144-yx11c5/ext/Cargo.toml --lib --profile release --locked -- -C linker\\=x86_64-w64-mingw32-cc -L native\\=/ruby-ucrt/lib -C link-args\\=-l:libssp.a -C link-args\\=-l:libz.a -C link-args\\=-pipe -C link-args\\=-fstack-protector-strong -C link-args\\=-s -C link-args\\=-Wl,--enable-auto-image-base,--enable-auto-import -l shell32 -l ws2_32 -l iphlpapi -l imagehlp -l shlwapi -l bcrypt -l x64-ucrt-ruby320 -C link-arg\\=-Wl,--dynamicbase -C link-arg\\=-Wl,--disable-auto-image-base -C link-arg\\=-static-libgcc",
 "   Compiling memchr v2.5.0\n" +
 "   Compiling winapi-x86_64-pc-windows-gnu v0.4.0\n" +
 "   Compiling winapi v0.3.9\n" +
 "   Compiling glob v0.3.0\n" +
 "   Compiling libc v0.2.138\n" +
 "   Compiling clang-sys v1.4.0\n" +
 "   Compiling proc-macro2 v1.0.47\n" +
 "   Compiling unicode-ident v1.0.5\n" +
 "   Compiling quote v1.0.21\n" +
 "   Compiling minimal-lexical v0.2.1\n" +
 "   Compiling nom v7.1.1\n" +
 "   Compiling libloading v0.7.4\n" +
 "   Compiling aho-corasick v0.7.20\n" +
 "   Compiling bindgen v0.60.1\n" +
 "   Compiling regex-syntax v0.6.28\n" +
 "   Compiling cexpr v0.6.0\n" +
 "   Compiling regex v1.7.0\n" +
 "   Compiling rustc-hash v1.1.0\n" +
 "   Compiling lazycell v1.3.0\n" +
 "   Compiling peeking_take_while v0.1.2\n" +
 "   Compiling bitflags v1.3.2\n" +
 "   Compiling shlex v1.1.0\n" +
 "   Compiling lazy_static v1.4.0\n" +
 "   Compiling shell-words v1.1.0\n" +
 "   Compiling rb-sys-build v0.9.52\n" +
 "   Compiling rb-sys v0.9.52\n" +
 "error: failed to run custom build command for `rb-sys v0.9.52`\n" +
 "\n" +
 "Caused by:\n" +
 "  process didn't exit successfully: `/ruby/test/tmp/test_rubygems_20221224-2144-yx11c5/prefix\\release\\build\\rb-sys-c6d6428395a3a7a8\\build-script-main` (exit code: 101)\n" +
 "  --- stdout\n" +
 "  cargo:rerun-if-env-changed=RUBY\n" +
 "  cargo:rerun-if-env-changed=RUBY_ROOT\n" +
 "  cargo:rerun-if-env-changed=RUBY_VERSION\n" +
 "  cargo:rerun-if-env-changed=RUBY\n" +
 "  cargo:rerun-if-changed=wrapper.h\n" +
 "  cargo:rerun-if-changed=build\\features.rs\n" +
 "  cargo:rerun-if-changed=build\\main.rs\n" +
 "  cargo:rerun-if-changed=build\\ruby_macros.rs\n" +
 "  cargo:rerun-if-changed=build\\version.rs\n" +
 "  cargo:rerun-if-env-changed=RUBY_STATIC\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_ENABLE_SHARED\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_rubyhdrdir\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_rubyarchhdrdir\n" +
 "  cargo:rerun-if-env-changed=RBCONFIG_CPPFLAGS\n" +
 "\n" +
 "  --- stderr\n" +
 "  Using bindgen with clang args: [\"-I/ruby-ucrt/include/ruby-3.2.0+3\", \"-I/ruby-ucrt/include/ruby-3.2.0+3/x64-mingw-ucrt\", \"-fms-extensions\", \"-O3\", \"-fno-omit-frame-pointer\", \"-fno-fast-math\", \"-ggdb3\", \"-Wall\", \"-Wextra\", \"-Wdeprecated-declarations\", \"-Wdiv-by-zero\", \"-Wduplicated-cond\", \"-Wimplicit-function-declaration\", \"-Wimplicit-int\", \"-Wmisleading-indentation\", \"-Wpointer-arith\", \"-Wwrite-strings\", \"-Wold-style-definition\", \"-Wimplicit-fallthrough=0\", \"-Wmissing-noreturn\", \"-Wno-cast-function-type\", \"-Wno-constant-logical-operand\", \"-Wno-long-long\", \"-Wno-missing-field-initializers\", \"-Wno-overlength-strings\", \"-Wno-packed-bitfield-compat\", \"-Wno-parentheses-equality\", \"-Wno-self-assign\", \"-Wno-tautological-compare\", \"-Wno-unused-parameter\", \"-Wno-unused-value\", \"-Wsuggest-attribute=format\", \"-Wsuggest-attribute=noreturn\", \"-Wunused-variable\", \"-Wundef\"]\n" +
 "  warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wno-packed-bitfield-compat' [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]\n" +
 "  warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]\n" +
 "  /ruby-ucrt/include/ruby-3.2.0+3\\ruby/defines.h:43:11: fatal error: 'strings.h' file not found\n" +
 "  clang diag: warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wno-packed-bitfield-compat' [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]\n" +
 "  clang diag: warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]\n" +
 "  thread 'main' panicked at 'Unable to generate bindings for bindings-raw.rs', C:\\Users\\runneradmin/.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\rb-sys-build-0.9.52\\src\\bindings.rs:136:29\n" +
 "  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"]
 = 25.00 s
[120/120] TestGemExtCargoBuilder#test_build_fail = 0.22 s

  1) Error:
TestGemExtCargoBuilder#test_full_integration:
Errno::E2BIG: Arg list too long - /ruby-ucrt/bin/ruby.exe
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:222:in `spawn'
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:222:in `popen_run'
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:210:in `popen2e'
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:399:in `capture2e'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:115:in `block (2 levels) in test_full_integration'
    /ruby-ucrt/lib/ruby/3.2.0+3/tmpdir.rb:94:in `mktmpdir'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:112:in `block in test_full_integration'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:106:in `chdir'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:106:in `test_full_integration'

  2) Error:
TestGemExtCargoBuilder#test_custom_name:
Errno::E2BIG: Arg list too long - /ruby-ucrt/bin/ruby.exe
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:222:in `spawn'
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:222:in `popen_run'
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:210:in `popen2e'
    /ruby-ucrt/lib/ruby/3.2.0+3/open3.rb:399:in `capture2e'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:137:in `block (2 levels) in test_custom_name'
    /ruby-ucrt/lib/ruby/3.2.0+3/tmpdir.rb:94:in `mktmpdir'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:134:in `block in test_custom_name'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:128:in `chdir'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:128:in `test_custom_name'

  3) Error:
TestGemExtCargoBuilder#test_build_cdylib:
Gem::InstallError: cargo failed, exit code 101
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/builder.rb:102:in `run'
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/cargo_builder.rb:32:in `call'
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/cargo_builder.rb:32:in `build_crate'
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/cargo_builder.rb:22:in `build'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:36:in `block in test_build_cdylib'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:32:in `chdir'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:32:in `test_build_cdylib'

  4) Error:
TestGemExtCargoBuilder#test_rubygems_cfg_passed_to_rustc:
Gem::InstallError: cargo failed, exit code 101
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/builder.rb:102:in `run'
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/cargo_builder.rb:32:in `call'
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/cargo_builder.rb:32:in `build_crate'
    /ruby-ucrt/lib/ruby/3.2.0+3/rubygems/ext/cargo_builder.rb:22:in `build'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:63:in `block in test_rubygems_cfg_passed_to_rustc'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:59:in `chdir'
    /ruby/test/rubygems/test_gem_ext_cargo_builder.rb:59:in `test_rubygems_cfg_passed_to_rustc'
```
</details>

**Comment by MSP-Greg** [comment]
@ianks

As mentioned above, ruby-loco passed the tests using Actions default Rust/Cargo for mswin, and the MSYS2 cargo.

I added `dtolnay/rust-toolchain@stable` to the workflows (as done here), and they're passing now.  I did not install rb_sys...

Happy Holidays, Greg
