### ISSUE TITLE
`bundle gem --ext=rust` generates gem that fails to load when installed

### ISSUE THREAD

**Issue by ankane** [rubygems/rubygems#6204]
### Describe the problem as clearly as you can

The gem created by `bundle gem --ext=rust` fails to load when installed.

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

With Ruby 3.2:

```sh
bundle gem hello --ext=rust
cd hello
# manually remove TODOs in gemspec
bundle exec rake compile
git add .
git commit -m "First commit"
bundle exec rake build
gem install pkg/hello-0.1.0.gem
ruby -e 'require "hello"'
```

### Which command did you run?

See above.

### What were you expecting to happen?

Gem to load.

### What actually happened?

Gem fails to load, since it tries to load `lib/hello/hello.bundle` (on Mac), but the Cargo builder creates `lib/hello.bundle`.

```text
/Users/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/hello-0.1.0/lib/hello.rb:4:in `require_relative': cannot load such file -- /Users/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/hello-0.1.0/lib/hello/hello (LoadError)
    from /Users/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/hello-0.1.0/lib/hello.rb:4:in `<top (required)>'
    from <internal:/Users/user/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
    from <internal:/Users/user/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
    from <internal:/Users/user/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
    from -e:1:in `<main>'
<internal:/Users/user/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- hello (LoadError)
    from <internal:/Users/user/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    from -e:1:in `<main>'
```

## Environment

```
Bundler       2.4.1
  Platforms   ruby, x86_64-darwin-22
Ruby          3.2.0p0 (2022-12-25 revision a528908271c678360d2d8ca232c178e7cdd340b4) [x86_64-darwin-22]
  Full Path   /Users/user/.rbenv/versions/3.2.0/bin/ruby
  Config Dir  /Users/user/.rbenv/versions/3.2.0/etc
RubyGems      3.4.1
  Gem Home    /Users/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0
  Gem Path    /Users/user/.gem/ruby/3.2.0:/Users/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0
  User Home   /Users/user
  User Path   /Users/user/.gem/ruby/3.2.0
  Bin Dir     /Users/user/.rbenv/versions/3.2.0/bin
Tools         
  Git         2.38.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-12-26
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/user/.bundle/config): false
gem.ci
  Set for the current user (/Users/user/.bundle/config): false
gem.coc
  Set for the current user (/Users/user/.bundle/config): false
gem.linter
  Set for the current user (/Users/user/.bundle/config): false
gem.mit
  Set for the current user (/Users/user/.bundle/config): false
gem.test
  Set for the current user (/Users/user/.bundle/config): false
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in hello.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"
gem "rb_sys"
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    hello (0.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.6)
    rake-compiler (1.2.1)
      rake
    rb_sys (0.9.53)

PLATFORMS
  x86_64-darwin-22

DEPENDENCIES
  hello!
  rake (~> 13.0)
  rake-compiler
  rb_sys

BUNDLED WITH
   2.4.1
```

### hello.gemspec

```ruby
# frozen_string_literal: true

require_relative "lib/hello/version"

Gem::Specification.new do |spec|
  spec.name = "hello"
  spec.version = Hello::VERSION
  spec.authors = ["user"]
  spec.email = ["user@example.com"]

  spec.summary = "Write a short summary, because RubyGems requires one."
  spec.required_ruby_version = ">= 2.6.0"
  spec.required_rubygems_version = ">= 3.3.11"

  spec.metadata["allowed_push_host"] = "TODO: Set to your gem server 'https://example.com'"

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.chdir(__dir__) do
    `git ls-files -z`.split("\x0").reject do |f|
      (f == __FILE__) || f.match(%r{\A(?:(?:bin|test|spec|features)/|\.(?:git|circleci)|appveyor)})
    end
  end
  spec.bindir = "exe"
  spec.executables = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]
  spec.extensions = ["ext/hello/Cargo.toml"]

  # Uncomment to register a new dependency of your gem
  # spec.add_dependency "example-gem", "~> 1.0"

  # For more information and examples about making a new gem, check out our
  # guide at: https://bundler.io/guides/creating_gem.html
end
```

**Comment by matsadler** [comment]
I also ran into this trying to port an existing gem to using the same structure as generated by `bundle gem --ext=rust`.

I'd not used the Cargo builder before, previously I'd used a Rakefile with the Rake builder, and later `rb-sys` with ext_conf builder. I had been configuring things to put the extension at `lib/gemname/gemname.dlext` as that seemed to match most C extensions, and the general pattern of `gemname.rb` being the only thing directly in the `lib` dir.

I guess the Cargo builder is setup to put things at `lib/gemname.dlext` without the extra dir? I couldn't figure out how to change it.

I did manage to get things working by editing the other files I could control. Using the `bundle gem hello --ext=rust` example:

in `ext/hello/extconf.rb` change `"hello/hello"` to `"hello"`
in `lib/hello.rb` change `"hello/hello"` to `"hello.so"`
in `Rakefile` change `"lib/hello"` to `"lib"` (or delete that line as I think `lib` is the default)

This keeps the development stuff (`rake compile`) working and fixes `gem install`ed version.

The `require "hello.so"` is because `hello.rb` and `hello.[dlext]` will be in the same directory, and `require "hello"` will try `hello.rb` first. Adding `.so` to require the extension works regardless of platform as Ruby special cases `.so` to try whatever the correct file extension for the current platform is.

**Comment by simi** [comment]
@ianks can you please check what's the best way of fixing this? Should we fix copying into extension directory into proper place to be loadable by default?

**Comment by ianks** [comment]
### Research

Here is how the installed gem lib structures look for various configurations

#### C (using extconf.rb)

Plain jane gem (i.e. `bundle gem --ext=c testing`):

```
❯ tree $GEM_HOME/gems/testing-0.1.0/lib
├── testing
│   ├── testing.bundle
│   └── version.rb
└── testing.rb

1 directory, 3 files
```

#### Rust extension (using CargoBuilder)

In this example (which produces the incorrect file tree), we have `spec.extensions = ["ext/testing/Cargo.toml"]` set so that the `Gem::Ext::CargoBuilder` is used (which is built into Rubygems).

```
❯ tree $GEM_HOME/gems/testing-0.1.0/lib
├── testing
│   └── version.rb
├── testing.bundle
└── testing.rb

1 directory, 3 files
```

#### Rust extension (using `extconf.rb` with `rb_sys`

This example produces the correct result, and is definitely the most feature rich way to do it. However, it brings in a dependency on `rb_sys` which is a bit annoying.

```diff
diff --git i/testing.gemspec w/testing.gemspec
index 19914ed..649c698 100644
--- i/testing.gemspec
+++ w/testing.gemspec
@@ -28,7 +28,8 @@ Gem::Specification.new do |spec|
   spec.bindir = "exe"
   spec.executables = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
   spec.require_paths = ["lib"]
-  spec.extensions = ["ext/testing/Cargo.toml"]
+  spec.extensions = ["ext/testing/extconf.rb"]
+  spec.add_dependency "rb_sys"
 
   # Uncomment to register a new dependency of your gem
   # spec.add_dependency "example-gem", "~> 1.0"
```

You can see it produces the correct lib structure:

```
❯ tree $GEM_HOME/gems/testing-0.1.0/lib
/Users/ianks/.gem/ruby/3.2.0/gems/testing-0.1.0/lib
├── testing
│   ├── testing.bundle
│   └── version.rb
└── testing.rb

1 directory, 3 files
```

It also includes less build artifacts, which is nice.

```
❯ tree $GEM_HOME/extensions/arm64-darwin-22/3.2.0/testing-0.1.0
$GEM_HOME/extensions/arm64-darwin-22/3.2.0/testing-0.1.0
├── gem.build_complete
├── gem_make.out
├── mkmf.log
└── testing
    └── testing.bundle
```

## My take

Overall, there are a couple of different solutions here, and I think we should do both.

### Short-term (just get it fixed ASAP)

We can do this now as a way to make things work as expected with `CargoBuilder`. The solution is to copy the `testing.#{RbConfig::CONFG["DLEXT"]}` to `lib/testing/testing.#{dlext}`, such that the folder structure looks like:

```
├── testing
│   ├── testing.bundle
│   └── version.rb
└── testing.rb
```

### Long-term

Overall the above is a bit of a brittle hack because it makes assumptions about where the placement of the dylib should be. The desired location for the dylib is specified in the `extconf.rb`. Unfortunately, `CargoBuilder` doesn't actually execute the `extconf.rb` by default since it would have to bring in a full dependency on `rb_sys`, which is not ideal...

In an _ideal_ world, the `extconf.rb` would be the blessed / one-true-way specifying how the extension should be built (since it allows for configurability, feature detection, etc.). These are things CargoBuilder` shouldn't be worried about.

In fact, I think in this _ideal world_ `Gem::Ext::CargoBuilder` can disappear.

#### What's stopping this ideal world?

Right now, there is no way to specify a build-time dependency for gems. As such, `rb_sys` has to resolve to a single version shared by _all gems_, even though it is only needed for a short-time in the `gem install` phase.

#### Feature request time!

Adding something like `spec.build_dependency` could help to solve this. With this feature, two gems could have entirely isolated build dependencies and avoid the dependency hell...

```
# gem A
spec.add_build_dependency 'rb_sys', '~> 0.9'`
# gem B
spec.add_build_dependency 'rb_sys', '~> 1.0'`
```

**Comment by ankane** [comment]
As an alternative to build dependencies, could `create_rust_makefile` be built into Rubygems? I think this could provide the same benefits (build is configured in `extconf.rb` and `CargoBuilder` is no longer needed) with less complexity.

Also, fwiw, changing the output location of `CargoBuilder` seems like a breaking change (gem authors would need to check both locations or set `spec.required_rubygems_version = ">= updated_version"`).

**Comment by ianks** [comment]
> As an alternative to build dependencies, could `create_rust_makefile` be built into Rubygems? I think this could provide the same benefits (build is configured in `extconf.rb` and `CargoBuilder` is no longer needed) with less complexity.

I would eventually like to get it into Ruby proper, but I'm not *quite* ready to fully commit to an interface stable enough for being in ruby-core. I'm getting close to something 1.0-ish, but not there yet. Committing to a stable interface prematurely would cause more problems than it solves at this point.

Keeping things outside of the core is good for gems in early development since it allows for fast iteration cycles and, ultimately, innovation in the gem building/bundling/packaging space 😃

**Comment by simi** [comment]
> As an alternative to build dependencies, could create_rust_makefile be built into Rubygems? I think this could provide the same benefits (build is configured in extconf.rb and CargoBuilder is no longer needed) with less complexity.

> I would eventually like to get it into Ruby proper, but I'm not quite ready to fully commit to an interface stable enough for being in ruby-core. I'm getting close to something 1.0-ish, but not there yet. Committing to a stable interface prematurely would cause more problems than it solves at this point.

I think that is super nice idea and makes most sense. `mkmf` is stable part of ruby. Making it capable of handling rust extensions (or introducing other separated library) in the Ruby core would be the way to go.

> Keeping things outside of the core is good for gems in early development since it allows for fast iteration cycles and, ultimately, innovation in the gem building/bundling/packaging space smiley

Per my understanding, Cargo builder was never considered stable and it is not properly documented. We can start documenting the current way (after fixing `bundle gem --ext=rust` + install) and make it clear it is experimental for now. AFAIK adoption of cargo builder is low (probably none for now).

**Comment by ianks** [comment]
> Per my understanding, Cargo builder was never considered stable and it is not properly documented. We can start documenting the current way (after fixing bundle gem --ext=rust + install) and make it clear it is experimental for now. AFAIK adoption of cargo builder is low (probably none for now).

Sounds like a good plan. For those curious, here is a mini Q&A I wrote for myself to help clarify some things...

**Q: So what's the best practice for Rust gems?**

1. Use [`rb_sys/mkmf`](https://github.com/oxidize-rb/rb-sys/blob/main/gem/README.md#create_rust_makefile) directly in an `extconf.rb`
2. Set `spec.extensions = ["ext/foo/extconf.rb"]`, and include `rb_sys` in `spec.add_dependency` (until we can get `add_build_dependency`)
3. (_optional but **HIGHLY** **HIGHLY** encouraged_) [Precompile gems](https://oxidize-rb.github.io/rb-sys/tutorial/publishing/cross-compilation.html) for the most common platforms using `rb_sys` / `rake-compiler-dock`. Bonus: remove `rb_sys` as a dependency for the precompiled gems since it won't be needed

[`wasmtime-rb`](https://github.com/bytecodealliance/wasmtime-rb) does all of these things and serves as the best production example of these things.

**Q: Does this mean `CargoBuilder` is bad?**

No. `CargoBuilder` is a very robust implementation. However, since it is completely detached from "development" experience and not easily configurable, it is best used only for very simple gems.

**Q: Do you still want `spec.add_build_dependency`?

Absolutely. Without it, it's going to become very hard to improve rb-sys since all gems would be forced to use the same version. It will also could eventually lead to subtle bugs / behavioral differences that will be very annoying to users and maintainers. In the meantime, I'm exploring ways to get around this by vendoring `rb_sys` somehow (which is not ideal...)

**Comment by indirect** [comment]
I don't think `add_build_dependency` is going to do what you want. The Ruby process created by `gem install` or `bundle install` can only load one version of any dependency. The build-time dependencies would have to all be fully resolved together so that `bundle install` can require all of them and then build and install all the needed gems.

**Comment by ianks** [comment]
> I don't think `add_build_dependency` is going to do what you want. The Ruby process created by `gem install` or `bundle install` can only load one version of any dependency. The build-time dependencies would have to all be fully resolved together so that `bundle install` can require all of them and then build and install all the needed gems.

`extconf.rb` is run from a separate process, so we could have a `RUBYOPT=-I/path/to/build-deps` type of thing to ensure a separate gemset.

**Comment by indirect** [comment]
Oh, cool. TIL. That does make it seem like build deps could be useful (albeit probably complicated to implement well).

**Comment by steakknife** [comment]
'.so' is unimportant and platform-dependent. The important part is `s/require_relative ("{{gem}}\/{{gem}}")/require \1/`.

Also, the extension build process is installing to the wrong final location that's Rust/Cargo dependent on the build type with an extra '/release/' in the path.

Actual `/usr/lib64/gems/ruby/{{gem}}-0.1.0/release/{{gem}}.so`

Expected `/usr/lib64/gems/ruby/{{gem}}-0.1.0/{{gem}}/{{gem}}.so`

**Comment by matsadler** [comment]
I've had a go at addressing this in https://github.com/rubygems/rubygems/pull/6298.

**Comment by ankane** [comment]
Awesome, thanks @matsadler and @simi!

**Comment by steakknife** [comment]
It's still broken on 2.4.6.

**Comment by ianks** [comment]
@steakknife Care to expand?

**Comment by hsbt** [comment]
@ianks Unfortunately, I banned this user from rubygems organization.
