### ISSUE TITLE
Installing packages silently fails when compatible binaries are not available

### ISSUE THREAD

**Issue by fulldecent** [rubygems/rubygems#6214]
### Describe the problem as clearly as you can

Running `bundle install` reports success. But the binary package is not installed.

If a binary package is not available an error should be reported.

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

Depend on the json package.

Use a Mac M1 computer with Docker to install. (i.e. you are installing with a Linux-aarch8 platform)

Then at runtime try to use that package.

(Tooling for this is at https://github.com/rubygems/rubygems/issues/6212#issuecomment-1367176246)

### Which command did you run?

bundle install

### What were you expecting to happen?

An error that the binary was not installed.

### What actually happened?

The command claims that installation was successful.

<img width="1388" alt="Screenshot 2022-12-29 at 09 37 56" src="https://user-images.githubusercontent.com/382183/209999277-66d24fbb-4bfc-453a-b671-4b7b79e30d8a.png">
<img width="1388" alt="Screenshot 2022-12-29 at 09 37 58" src="https://user-images.githubusercontent.com/382183/209999288-a77e0670-daff-4f30-83c6-4c92542cb752.png">
<img width="1388" alt="Screenshot 2022-12-29 at 09 38 06" src="https://user-images.githubusercontent.com/382183/209999291-e7bee3d5-d191-4857-91f5-074c7f82edde.png">

### If not included with the output of your command, run `bundle env` and paste the output below

vscode ➜ /workspaces/911coned.com (911coned.com ✗) $ bundle env
## Environment

```
Bundler       2.4.1
  Platforms   ruby, aarch64-linux
Ruby          3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [aarch64-linux]
  Full Path   /usr/local/rvm/rubies/ruby-3.1.3/bin/ruby
  Config Dir  /usr/local/rvm/rubies/ruby-3.1.3/etc
RubyGems      3.3.26
  Gem Home    /usr/local/rvm/gems/default
  Gem Path    /usr/local/rvm/gems/default:/usr/local/rvm/gems/default@global
  User Home   /home/vscode
  User Path   /home/vscode/.local/share/gem/ruby/3.1.0
  Bin Dir     /usr/local/rvm/gems/default/bin
Tools         
  Git         2.39.0
  RVM         1.29.12 (latest)
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-12-24
Git SHA           f3175f033c
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'jekyll', '~> 4.3', '>= 4.3.1'
gem 'lightning_sites', '~> 1.4', '>= 1.4.23'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    async (2.3.1)
      console (~> 1.10)
      io-event (~> 1.1)
      timers (~> 4.1)
    colorator (1.1.0)
    colorize (0.8.1)
    concurrent-ruby (1.1.10)
    console (1.16.2)
      fiber-local
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    eventmachine (1.2.7)
    ffi (1.15.5)
    ffi-compiler (1.0.1)
      ffi (>= 1.0.0)
      rake
    fiber-local (1.0.0)
    forwardable-extended (2.6.0)
    google-protobuf (3.21.12)
    html-proofer (5.0.3)
      addressable (~> 2.3)
      async (~> 2.1)
      nokogiri (~> 1.13)
      rainbow (~> 3.0)
      typhoeus (~> 1.3)
      yell (~> 2.0)
      zeitwerk (~> 2.5)
    html-proofer-mailto_awesome (1.0.4)
      html-proofer (~> 5.0, >= 5.0.3)
    http (5.1.1)
      addressable (~> 2.8)
      http-cookie (~> 1.0)
      http-form_data (~> 2.2)
      llhttp-ffi (~> 0.4.0)
    http-cookie (1.0.5)
      domain_name (~> 0.5)
    http-form_data (2.3.0)
    http_parser.rb (0.8.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    io-event (1.1.4)
    jekyll (4.3.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-sass-converter (3.0.0)
      sass-embedded (~> 1.54)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    json (2.6.3)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    lightning_sites (1.4.25)
      colorize (~> 0.8.1)
      html-proofer (~> 5.0, >= 5.0.3)
      html-proofer-mailto_awesome (~> 1.0, >= 1.0.3)
      minitest
      rake (>= 12)
      w3c_validators (~> 1.3, >= 1.3.7)
      web-puc (~> 0.4, >= 0.4.1)
    liquid (4.0.3)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    llhttp-ffi (0.4.0)
      ffi-compiler (~> 1.0)
      rake (~> 13.0)
    mercenary (0.4.0)
    minitest (5.16.3)
    nokogiri (1.13.10-aarch64-linux)
      racc (~> 1.4)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (5.0.1)
    racc (1.6.2)
    rainbow (3.1.1)
    rake (13.0.6)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (4.0.1)
    safe_yaml (1.0.5)
    sass-embedded (1.57.1-aarch64-linux-gnu)
      google-protobuf (~> 3.21)
    structured-acceptance-test (0.0.8)
      colorize (~> 0.8, >= 0.8.1)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    timers (4.3.5)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8.2)
    unicode-display_width (2.3.0)
    w3c_validators (1.3.7)
      json (>= 1.8)
      nokogiri (~> 1.6)
      rexml (~> 3.2)
    web-puc (0.4.2)
      http (~> 5.1)
      rake (>= 12)
      structured-acceptance-test (~> 0.0.7)
    webrick (1.7.0)
    yell (2.2.2)
    zeitwerk (2.6.6)

PLATFORMS
  aarch64-linux

DEPENDENCIES
  jekyll (~> 4.3, >= 4.3.1)
  lightning_sites (~> 1.4, >= 1.4.23)

BUNDLED WITH
   2.4.1
```
vscode ➜ /workspaces/911coned.com (911coned.com ✗) $

**Comment by deivid-rodriguez** [comment]
@fulldecent Unfortunately I don't understand this issue. Which problem exactly are you having? Which binary package are you referring to? Are you not able to use the `json` gem after `bundle install`? I did some basic tests with `JSON` in the devcontainer after running `bundle install` and it all worked fine.

**Comment by fulldecent** [comment]
Thank you, sorry, just fixed the issue and added the screenshots

**Comment by deivid-rodriguez** [comment]
I'm still missing some information in order to reproduce this. In the codespace I created with just the information you have provided, everything seems fine:

```
vscode ➜ /workspaces/dev-container-jekyll $ bundle install
Using rake 13.0.6
Using public_suffix 5.0.1
Using addressable 2.8.1
Using fiber-local 1.0.0
Using console 1.16.2
Using io-event 1.1.4
Using timers 4.3.5
Using async 2.3.1
Using bundler 2.4.1
Using colorator 1.1.0
Using colorize 0.8.1
Using concurrent-ruby 1.1.10
Using unf_ext 0.0.8.2
Using unf 0.1.4
Using domain_name 0.5.20190701
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using ffi 1.15.5
Using ethon 0.16.0
Using ffi-compiler 1.0.1
Using forwardable-extended 2.6.0
Using google-protobuf 3.21.12
Using racc 1.6.2
Using nokogiri 1.13.10 (aarch64-linux)
Using rainbow 3.1.1
Using typhoeus 1.4.0
Using yell 2.2.2
Using zeitwerk 2.6.6
Using html-proofer 5.0.3
Using html-proofer-mailto_awesome 1.0.4
Using http-cookie 1.0.5
Using http-form_data 2.3.0
Using llhttp-ffi 0.4.0
Using http 5.1.1
Using i18n 1.12.0
Using sass-embedded 1.57.1 (aarch64-linux-gnu)
Using jekyll-sass-converter 3.0.0
Using rb-fsevent 0.11.2
Using rb-inotify 0.10.1
Using listen 3.7.1
Using jekyll-watch 2.2.1
Using rexml 3.2.5
Using kramdown 2.4.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.4.0
Using pathutil 0.16.2
Using rouge 4.0.1
Using safe_yaml 1.0.5
Using unicode-display_width 2.3.0
Using terminal-table 3.0.2
Using webrick 1.7.0
Using jekyll 4.3.1
Using json 2.6.3
Using minitest 5.16.3
Using w3c_validators 1.3.7
Using structured-acceptance-test 0.0.8
Using web-puc 0.4.2
Using lightning_sites 1.4.25
Bundle complete! 2 Gemfile dependencies, 60 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

vscode ➜ /workspaces/dev-container-jekyll $ bundle exec rake test
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/default/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/rvm/gems/default/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
/usr/local/rvm/gems/default/bin/bundle:25:in `load'
/usr/local/rvm/gems/default/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)

vscode ➜ /workspaces/dev-container-jekyll $ bundle exec ruby -rjson -e'puts JSON.parse("{}")'
{}
```

Can you create a minimal repository that reproduces the issue?

**Comment by fulldecent** [comment]
Sorry about this!

Here is the repro case I was using:

```
❯ grep -r '^.*' .
Binary file ./.DS_Store matches
./.devcontainer/post-create.sh:#!/bin/sh
./.devcontainer/post-create.sh:# This script is referenced and executed in the container from the
./.devcontainer/post-create.sh:# mcr.microsoft.com/devcontainers/jekyll image.
./.devcontainer/post-create.sh:
./.devcontainer/post-create.sh:# Install the version of Bundler.
./.devcontainer/post-create.sh:if [ -f Gemfile.lock ] && grep "BUNDLED WITH" Gemfile.lock > /dev/null; then
./.devcontainer/post-create.sh:    cat Gemfile.lock | tail -n 2 | grep -C2 "BUNDLED WITH" | tail -n 1 | xargs gem install bundler -v
./.devcontainer/post-create.sh:fi
./.devcontainer/post-create.sh:
./.devcontainer/post-create.sh:# If there's a Gemfile, then run `bundle install`
./.devcontainer/post-create.sh:# It's assumed that the Gemfile will install Jekyll too
./.devcontainer/post-create.sh:if [ -f Gemfile ]; then
./.devcontainer/post-create.sh:    bundle install
./.devcontainer/post-create.sh:fi
./.devcontainer/devcontainer.json:// Documentation:
./.devcontainer/devcontainer.json://  - https://github.com/devcontainers/images/tree/main/src/jekyll
./.devcontainer/devcontainer.json://  - https://github.com/devcontainers/features/tree/main/src/node
./.devcontainer/devcontainer.json:
./.devcontainer/devcontainer.json:{
./.devcontainer/devcontainer.json:	"name": "Jekyll",
./.devcontainer/devcontainer.json:	"image": "mcr.microsoft.com/devcontainers/jekyll",
./.devcontainer/devcontainer.json:	"features": {
./.devcontainer/devcontainer.json:		// Install Ruby 3.1
./.devcontainer/devcontainer.json:		"ghcr.io/devcontainers/features/ruby:1": {
./.devcontainer/devcontainer.json:			"version": "3.1"
./.devcontainer/devcontainer.json:		},
./.devcontainer/devcontainer.json:		// Install latest stable Node
./.devcontainer/devcontainer.json:		"ghcr.io/devcontainers/features/node:1": {
./.devcontainer/devcontainer.json:			"version": "lts"
./.devcontainer/devcontainer.json:		}
./.devcontainer/devcontainer.json:	}
./.devcontainer/devcontainer.json:}
./Gemfile:source 'https://rubygems.org'
./Gemfile:
./Gemfile:gem 'jekyll', '>= 4.3.1', '< 5.0.0'
```

This seems to be an issue with VS Code — Dev Containers. Somehow I managed to build the container and install with bundler got binaries with architecture linux-aarch8. In VS Code after running "Rebuild Container" it would re-setup Docker. But for some reason some state of the container was kept.

So my "bad" repo was always producing the bad problem I screens hotted above. And the new "repro" repo was giving the good results you see.

After delete all containers from the Docker app and then trying both again, they both are successfully installing with bundler and not having the problem I see above.

---

So this means that I unfortunately lost the ability to reproduce the problem from my "bad"/container.

---

Since an issue is only valuable if it can be reproduced, closing this issue for now. But the screenshots at top still document the problem I had and if someone else has it then we can resurrect.

**Comment by deivid-rodriguez** [comment]
No problem, thanks for reporting back!
