### ISSUE TITLE
ArgumentError Malformed version number string 0.42.0.pre.b1e6081|checksum:117e4fe894c0fa9d9d1ffae9395311df271c8119a1db08b1dd29b4a5905fe396

### ISSUE THREAD

**Issue by jedrekdomanski** [rubygems/rubygems#6264]
### Describe the problem as clearly as you can
Probably the latest commit https://github.com/rubygems/rubygems/commit/9abd8acdb11378d7c4a97d6e252360cb60e88ec6 causes the problem. I am not able to install any gems either in CI or locally.
```
Retrying fetcher due to error (2/4): ArgumentError Malformed version number string 0.42.0.pre.b1e6081|checksum:117e4fe894c0fa9d9d1ffae9395311df271c8119a1db08b1dd29b4a5905fe396

ArgumentError: Malformed version number string 0.42.0.pre.b1e6081|checksum:117e4fe894c0fa9d9d1ffae9395311df271c8119a1db08b1dd29b4a5905fe396

  /usr/local/lib/ruby/2.7.0/rubygems/version.rb:215:in `initialize'

  /usr/local/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'

  /usr/local/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'

  /usr/local/lib/ruby/2.7.0/rubygems/version.rb:195:in `create'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/endpoint_specification.rb:15:in `initialize'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/fetcher.rb:142:in `new'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/fetcher.rb:142:in `block in specs'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/fetcher.rb:140:in `each'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/fetcher.rb:140:in `specs'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/fetcher.rb:118:in `block in specs_with_retry'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/retry.rb:40:in `run'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/retry.rb:30:in `attempt'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/fetcher.rb:117:in `specs_with_retry'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/source/rubygems.rb:427:in `block in fetch_names'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/source/rubygems.rb:424:in `each'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/source/rubygems.rb:424:in `fetch_names'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/source/rubygems.rb:294:in `double_check_for'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/spec_set.rb:82:in `block in materialize'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/spec_set.rb:77:in `each'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/spec_set.rb:77:in `materialize'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/definition.rb:188:in `specs'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/installer.rb:247:in `ensure_specs_are_compatible!'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/installer.rb:84:in `block in run'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/process_lock.rb:12:in `block in lock'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/process_lock.rb:9:in `open'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/process_lock.rb:9:in `lock'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/installer.rb:72:in `run'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/installer.rb:24:in `install'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli/install.rb:60:in `run'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli.rb:260:in `block in install'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/settings.rb:131:in `temporary'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli.rb:259:in `install'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'

  /usr/local/bundle/gems/bundler-2.2.24/exe/bundle:49:in `block in <top (required)>'

  /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'

  /usr/local/bundle/gems/bundler-2.2.24/exe/bundle:37:in `<top (required)>'

  /usr/local/bundle/bin/bundle:23:in `load'

  /usr/local/bundle/bin/bundle:23:in `<main>'
```

### Did you try upgrading RubyGems?
No

### Which command did you run?
```
bundle install
```

### What were you expecting to happen?
Install gems

### What actually happened?
```
Retrying fetcher due to error (2/4): ArgumentError Malformed version number string 0.42.0.pre.b1e6081|checksum:117e4fe894c0fa9d9d1ffae9395311df271c8119a1db08b1dd29b4a5905fe396
```

### Run `gem env` and paste the output below
```
## Environment

Bundler       2.2.24

  Platforms   ruby, x86_64-linux-musl

Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-linux-musl]

  Full Path   /usr/local/bin/ruby

  Config Dir  /usr/local/etc

RubyGems      3.1.6

  Gem Home    /app/vendor/bundle/ruby/2.7.0

  Gem Path    /app/vendor/bundle/ruby/2.7.0

  User Home   /root

  User Path   /root/.gem/ruby/2.7.0

  Bin Dir     /app/vendor/bundle/ruby/2.7.0/bin

OpenSSL       

  Compiled    OpenSSL 1.1.1l  24 Aug 2021

  Loaded      OpenSSL 1.1.1l  24 Aug 2021

  Cert File   /etc/ssl/cert.pem

  Cert Dir    /etc/ssl/certs

Tools         

  Git         2.32.0

  RVM         not installed

  rbenv       not installed

  chruby      not installed
```

**Comment by deivid-rodriguez** [comment]
I believe GitHub Packages are migrating to the compact index API (which is quite awesome), but it's still not fully working. Please subscribe to https://github.com/orgs/community/discussions/43861 instead :)

**Comment by jedrekdomanski** [comment]
Ok, I now see there are some other changes from the past couple of hours so I edited my post. Thanks for checking, it looks like GitHub Packages issue because some other people are seeing the same issue.
