### ISSUE TITLE
Gem::Requirement::BadRequirementError: Illformed requirement [" < 61.0 (java)"]

### ISSUE THREAD

**Issue by mogman1** [rubygems/rubygems#6267]
### Describe the problem as clearly as you can

When upgrading to bundler v2.4.3 and running bundle with a Gemfile containing rails 6.0.x and activerecord-jdbcpostgresql-adapter using jruby 9.3.8.0, bundler fails indicating an illformed requirement.  This does not happen when using MRI 2.6.x.

### Did you try upgrading rubygems & bundler?

Yes:

```
➜ bundle -v
Bundler version 2.4.3
➜ gem -v
3.4.3
```

### Post steps to reproduce the problem

Running OSX 13.0.1 and using jruby-9.3.8.0 running on JVM 8:

```
➜  ruby -v
jruby 9.3.8.0 (2.6.8) 2022-09-13 98d69c9461 OpenJDK 64-Bit Server VM 25.345-b00 on 1.8.0_345-bre_2022_08_04_23_35-b00 +jit [x86_64-darwin]
```

Set up the following Gemfile:

```ruby
source "https://rubygems.org/"

gem "rails", "~> 6.0.0"
gem "activerecord-jdbcpostgresql-adapter"
```

Running bundle has reliably reproduced the error for me.  I was also able to replicate this using the jruby:9.3.8.0 docker image:

```Dockerfile
FROM jruby:9.3.8.0
WORKDIR /
RUN apt-get update && apt-get install -y --no-install-recommends build-essential
COPY Gemfile .
RUN gem install bundler
RUN gem update --system
RUN bundle install
```

### Which command did you run?

`bundle install`

### Template from error

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::Requirement::BadRequirementError: Illformed requirement [" < 61.0 (java)"]
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/rubygems/requirement.rb:106:in `parse'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/rubygems/requirement.rb:138:in `block in initialize'
  org/jruby/RubyArray.java:2699:in `map!'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/rubygems/requirement.rb:138:in `initialize'
  org/jruby/RubyClass.java:890:in `new'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/resolver.rb:142:in `block in no_versions_incompatibility_for'
  org/jruby/RubyArray.java:2667:in `map'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/resolver.rb:142:in `no_versions_incompatibility_for'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:130:in `choose_package_version'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:41:in `work'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:58:in `solve'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/resolver.rb:76:in `solve_versions'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/resolver.rb:37:in `start'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/definition.rb:554:in `start_resolution'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/definition.rb:279:in `resolve'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/definition.rb:177:in `resolve_remotely!'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/installer.rb:261:in `resolve_if_needed'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/installer.rb:82:in `block in run'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/process_lock.rb:12:in `block in lock'
  org/jruby/RubyIO.java:1148:in `open'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/process_lock.rb:9:in `lock'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/installer.rb:71:in `run'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/installer.rb:23:in `install'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/cli/install.rb:62:in `run'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/cli.rb:260:in `block in install'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/settings.rb:131:in `temporary'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/cli.rb:259:in `install'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/cli.rb:34:in `dispatch'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/cli.rb:28:in `start'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/gems/shared/gems/bundler-2.4.3/exe/bundle:45:in `block in <main>'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/stdlib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/gems/shared/gems/bundler-2.4.3/exe/bundle:33:in `<main>'
  org/jruby/RubyKernel.java:1052:in `load'
  /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/bin/bundle:25:in `<main>'
  org/jruby/RubyKernel.java:1091:in `eval'
  /Users/shaun.carlson/.rvm/gems/jruby-9.3.8.0/bin/jruby_executable_hooks:22:in `<main>'

```

## Environment

```
Bundler             2.4.3
  Platforms         ruby, universal-java-1.8
Ruby                2.6.8p0 (2022-09-13 revision 67951) [universal-java-1.8]
  Full Path         /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/bin/jruby
  Config Dir        /Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/etc
RubyGems            3.4.3
  Gem Home          /Users/shaun.carlson/.rvm/gems/jruby-9.3.8.0
  Gem Path          /Users/shaun.carlson/.rvm/gems/jruby-9.3.8.0:/Users/shaun.carlson/.rvm/rubies/jruby-9.3.8.0/lib/ruby/gems/shared
  User Home         /Users/shaun.carlson
  User Path         /Users/shaun.carlson/.gem/jruby/2.6.0
  Bin Dir           /Users/shaun.carlson/.rvm/gems/jruby-9.3.8.0/bin
OpenSSL             
  Compiled          JRuby-OpenSSL 0.14.0
  Loaded            JRuby-OpenSSL 0.14.0
  Cert File         /usr/local/Cellar/openjdk@8/1.8.0+345/libexec/openjdk.jdk/Contents/Home/jre/lib/security/cacerts
  Cert Dir          /etc/ssl/certs
Tools               
  Git               2.32.1 (Apple Git-133)
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2023-01-06
Git SHA           ed1f27f75c
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org/"

gem "activerecord-jdbcpostgresql-adapter"
gem "rails", "~> 6.0.0"
```

### Gemfile.lock

```
<No /Users/shaun.carlson/tmp/blah/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Thanks for the report @mogman1, on it!

**Comment by deivid-rodriguez** [comment]
#6270 should fix this!

**Comment by mogman1** [comment]
Thank you so much! <3
