### ISSUE TITLE
Bundler 2.4.4 unable to resolve dependencies when used inline

### ISSUE THREAD

**Issue by schm** [rubygems/rubygems#6281]
### Describe the problem as clearly as you can

I'm using bundler inline for some simple scripts. With the release of Bundler 2.4.4 they are no longer able to install/resolve the dependency. This is a simplified version to reproduce the issue.

```ruby
# script.rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'json_schemer'
end

puts 'Hello, World'
```

Using Ruby 3.1.3 and bundler **2.3.26**. But it also works with 2.4.3.
```
% ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]

% bundle -v
Bundler version 2.3.26

% gem list uri_template json_schemer

*** LOCAL GEMS ***



*** LOCAL GEMS ***


% ruby script.rb
Hello, World

% gem list uri_template json_schemer

*** LOCAL GEMS ***

uri_template (0.7.0)

*** LOCAL GEMS ***

json_schemer (0.2.24)
```

**Using bundler 2.4.4 I'm getting the following error.**

```
% bundle -v
Bundler version 2.4.4

% gem list uri_template json_schemer

*** LOCAL GEMS ***



*** LOCAL GEMS ***


% ruby script.rb
/Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/resolver.rb:106:in `rescue in solve_versions': Could not find compatible versions (Bundler::SolveFailure)

Because json_schemer < 0.2.2 depends on uri_template ~> 0.7.0
  and json_schemer >= 0.2.2 depends on uri_template ~> 0.7,
  uri_template >= 0.7.0, < 1.A is required.
So, because uri_template ~> 0.7 could not be found in any of the sources,
  version solving has failed.
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/resolver.rb:69:in `solve_versions'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/resolver.rb:32:in `start'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/definition.rb:554:in `start_resolution'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/definition.rb:289:in `resolve'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/definition.rb:507:in `materialize'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/definition.rb:197:in `specs'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/installer.rb:83:in `block in run'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/process_lock.rb:12:in `block in lock'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/process_lock.rb:9:in `open'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/process_lock.rb:9:in `lock'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/installer.rb:71:in `run'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/installer.rb:23:in `install'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/inline.rb:58:in `block (2 levels) in gemfile'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/settings.rb:131:in `temporary'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/inline.rb:57:in `block in gemfile'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/settings.rb:131:in `temporary'
	from /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/inline.rb:51:in `gemfile'
	from script.rb:3:in `<main>'
/Users/schmidt/.rvm/gems/ruby-3.1.3@gad/gems/bundler-2.4.4/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:229:in `resolve_conflict': Could not find compatible versions (Bundler::PubGrub::SolveFailure)
```

After installing the gem "manually" with `gem install json_schemer` the script runs fine.

### Did you try upgrading rubygems & bundler?

This only occurs with bundler 2.4.4. It worked fine until yesterday before 2.4.4 was released.

### Post steps to reproduce the problem

see above

### Which command did you run?

see above

### What were you expecting to happen?

it should install the missing gems and run the script

### What actually happened?

It didn't install the gems because dependencies couldn't be resolved. Using a proper Gemfile and `bundle install` or installing the gems explicitly fixes the issue.

## Environment

```
Bundler             2.4.4
  Platforms         ruby, arm64-darwin-22
Ruby                3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [arm64-darwin-22]
  Full Path         /Users/schmidt/.rvm/rubies/ruby-3.1.3/bin/ruby
  Config Dir        /Users/schmidt/.rvm/rubies/ruby-3.1.3/etc
RubyGems            3.3.26
  Gem Home          /Users/schmidt/.rvm/gems/ruby-3.1.3@gad
  Gem Path          /Users/schmidt/.rvm/gems/ruby-3.1.3@gad:/Users/schmidt/.rvm/rubies/ruby-3.1.3/lib/ruby/gems/3.1.0
  User Home         /Users/schmidt
  User Path         /Users/schmidt/.gem/ruby/3.1.0
  Bin Dir           /Users/schmidt/.rvm/gems/ruby-3.1.3@gad/bin
Tools
  Git               2.37.1 (Apple Git-137.1)
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2023-01-16
Git SHA           e1c0b50e84
Released Version  true
```

## Bundler settings

```
build.eventmachine
  Set for the current user (/Users/schmidt/.bundle/config): "--with-cppflags=-I/opt/homebrew/opt/openssl@1.1/include"
build.libv8
  Set for the current user (/Users/schmidt/.bundle/config): "--with-system-v8"
build.therubyracer
  Set for the current user (/Users/schmidt/.bundle/config): "--with-v8-dir=/usr/local/opt/v8@3.15"
gem.coc
  Set for the current user (/Users/schmidt/.bundle/config): false
gem.mit
  Set for the current user (/Users/schmidt/.bundle/config): false
gem.test
  Set for the current user (/Users/schmidt/.bundle/config): "rspec"
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting. I will have a look in a bit at how we regressed here.

**Comment by deivid-rodriguez** [comment]
This will be fixed by #6282. Planning to release that shortly.

**Comment by schm** [comment]
Thank you so much for looking into this and fixing it so quickly. 👍

**Comment by deivid-rodriguez** [comment]
No problem, thanks for reporting it quickly too. 2.4.5 is out now!
