### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by LaxmiTSB** [rubygems/rubygems#6283]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/plugins directory.
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:961:in `ensure_writable_dir'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/rubygems_gem_installer.rb:54:in `generate_plugins'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/rubygems_gem_installer.rb:33:in `install'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/source/rubygems.rb:200:in `install'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/worker.rb:62:in `apply_func'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/worker.rb:54:in `loop'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/worker.rb:54:in `process_queue'
  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.4.4/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.4
  Platforms   ruby, x86_64-darwin-22
Ruby          2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-darwin-22]
  Full Path   /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/bin/ruby
  Config Dir  /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/etc
RubyGems      3.4.4
  Gem Home    /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0
  Gem Path    /Users/laxminarayanpatidar/.gem/ruby/2.7.0:/Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0
  User Home   /Users/laxminarayanpatidar
  User Path   /Users/laxminarayanpatidar/.gem/ruby/2.7.0
  Bin Dir     /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1s  1 Nov 2022
  Loaded      OpenSSL 1.1.1s  1 Nov 2022
  Cert File   /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/openssl/ssl/cert.pem
  Cert Dir    /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/openssl/ssl/certs
Tools         
  Git         2.37.1 (Apple Git-137.1)
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-01-16
Git SHA           e1c0b50e84
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "fastlane", '2.183.2'
gem "cocoapods", '1.10.0'
gem "xcode-install"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

### fastlane/Pluginfile

```ruby
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-appcenter'
gem 'fastlane-plugin-xcconfig'
gem 'fastlane-plugin-badge'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.5)
      rexml
    activesupport (5.2.8.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    artifactory (3.0.15)
    atomos (0.1.3)
    aws-eventstream (1.2.0)
    aws-partitions (1.694.0)
    aws-sdk-core (3.168.4)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.5)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.61.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.117.2)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.5.2)
      aws-eventstream (~> 1, >= 1.0.2)
    babosa (1.0.4)
    badge (0.13.0)
      fastimage (>= 1.6)
      fastlane (>= 2.0)
      mini_magick (>= 4.9.4, < 5.0.0)
    claide (1.1.0)
    cocoapods (1.10.0)
      addressable (~> 2.6)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.10.0)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.4.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.4.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.6.6)
      nap (~> 1.0)
      ruby-macho (~> 1.4)
      xcodeproj (>= 1.19.0, < 2.0)
    cocoapods-core (1.10.0)
      activesupport (> 5.0, < 6)
      addressable (~> 2.6)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (1.6.3)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.6.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored (1.2)
    colored2 (3.1.2)
    commander (4.6.0)
      highline (~> 2.0.0)
    concurrent-ruby (1.1.10)
    declarative (0.0.20)
    digest-crc (0.6.4)
      rake (>= 12.0.0, < 14.0.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.8.1)
    emoji_regex (3.2.3)
    escape (0.0.4)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    excon (0.97.1)
    faraday (1.10.2)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-cookie_jar (0.0.7)
      faraday (>= 0.8.0)
      http-cookie (~> 1.0.0)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    fastimage (2.2.6)
    fastlane (2.183.2)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.3, < 3.0.0)
      artifactory (~> 3.0)
      aws-sdk-s3 (~> 1.0)
      babosa (>= 1.0.3, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander (~> 4.6)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 4.0)
      excon (>= 0.71.0, < 1.0.0)
      faraday (~> 1.0)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 1.0)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-apis-androidpublisher_v3 (~> 0.1)
      google-apis-playcustomapp_v1 (~> 0.1)
      google-cloud-storage (~> 1.31)
      highline (~> 2.0)
      json (< 3.0.0)
      jwt (>= 2.1.0, < 3)
      mini_magick (>= 4.9.4, < 5.0.0)
      multipart-post (~> 2.0.0)
      naturally (~> 2.2)
      plist (>= 3.1.0, < 4.0.0)
      rubyzip (>= 2.0.0, < 3.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    fastlane-plugin-appcenter (2.0.0)
    fastlane-plugin-badge (1.5.0)
      badge (~> 0.13.0)
    fastlane-plugin-xcconfig (2.0.0)
    ffi (1.15.5)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    google-apis-androidpublisher_v3 (0.32.0)
      google-apis-core (>= 0.9.1, < 2.a)
    google-apis-core (0.9.5)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    google-apis-iamcredentials_v1 (0.16.0)
      google-apis-core (>= 0.9.1, < 2.a)
    google-apis-playcustomapp_v1 (0.12.0)
      google-apis-core (>= 0.9.1, < 2.a)
    google-apis-storage_v1 (0.19.0)
      google-apis-core (>= 0.9.0, < 2.a)
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.6.0)
      faraday (>= 0.17.3, < 3.0)
    google-cloud-errors (1.3.0)
    google-cloud-storage (1.44.0)
      addressable (~> 2.8)
      digest-crc (~> 0.4)
      google-apis-iamcredentials_v1 (~> 0.1)
      google-apis-storage_v1 (~> 0.19.0)
      google-cloud-core (~> 1.6)
      googleauth (>= 0.16.2, < 2.a)
      mini_mime (~> 1.0)
    googleauth (1.3.0)
      faraday (>= 0.17.3, < 3.a)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    highline (2.0.3)
    http-cookie (1.0.5)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jmespath (1.6.2)
    json (2.6.3)
    jwt (2.6.0)
    memoist (0.16.2)
    mini_magick (4.12.0)
    mini_mime (1.1.2)
    minitest (5.17.0)
    molinillo (0.6.6)
    multi_json (1.15.0)
    multipart-post (2.0.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    naturally (2.2.1)
    netrc (0.11.0)
    os (1.1.4)
    plist (3.6.0)
    public_suffix (5.0.1)
    rake (13.0.6)
    representable (3.2.0)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rexml (3.2.5)
    rouge (2.0.7)
    ruby-macho (1.4.0)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    security (0.1.3)
    signet (0.17.0)
      addressable (~> 2.8)
      faraday (>= 0.17.5, < 3.a)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.8)
      CFPropertyList
      naturally
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thread_safe (0.3.6)
    trailblazer-option (0.1.2)
    tty-cursor (0.7.1)
    tty-screen (0.8.1)
    tty-spinner (0.9.3)
      tty-cursor (~> 0.7)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (1.2.10)
      thread_safe (~> 0.1)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8.2)
    unicode-display_width (1.8.0)
    webrick (1.7.0)
    word_wrap (1.0.0)
    xcode-install (2.8.1)
      claide (>= 0.9.1)
      fastlane (>= 2.1.0, < 3.0.0)
    xcodeproj (1.22.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.1)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  universal-darwin-20
  universal-darwin-21
  universal-darwin-22

DEPENDENCIES
  cocoapods (= 1.10.0)
  fastlane (= 2.183.2)
  fastlane-plugin-appcenter
  fastlane-plugin-badge
  fastlane-plugin-xcconfig
  xcode-install

BUNDLED WITH
   2.4.4
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Can you show the output of `ls -la /Users/laxminarayanpatidar/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/`?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
