### ISSUE TITLE
Bundler mixing files of the default and bundled gems when the same version installed for both

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#6307]
### Describe the problem as clearly as you can

I use (used) `bundle config --global path ~/.bundle` as a way to share gems correctly between Rubies based on the RUBY_ENGINE and ABI version, since Bundler nicely puts the "gem homes" under `PATH/RUBY_ENGINE/ABI_VERSION`.

In that scenario, it's possible to have Bundler 2.3.26 installed both as the default gem of Ruby 3.1.3.
And also as a regular gem when doing `bundle install` on Ruby 3.1.2 with a Gemfile like:
```
$ cat Gemfile
source "https://rubygems.org"
```

`bundle install` on 3.1.3 will produce:
```
$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x86_64-linux

DEPENDENCIES

BUNDLED WITH
   2.3.26
```

`bundle install` on 3.1.2 will install Bundler 2.3.26:
```
bundle install
Bundler 2.3.7 is running, but your lockfile was generated with 2.3.26. Installing Bundler 2.3.26 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.3.26
Installing bundler 2.3.26
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/home/eregon/.bundle`
```

So far so good, but then it breaks on 3.1.3:
```
$ bundle exec ruby -e 'system "bundle", "package"'
/home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
/home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
	from /home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/errors.rb:20:in `<class:GemfileError>'
	from /home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/errors.rb:20:in `<module:Bundler>'
	from /home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/errors.rb:3:in `<top (required)>'
	from /home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler.rb:7:in `require_relative'
	from /home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler.rb:7:in `<top (required)>'
	from /home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/exe/bundle:13:in `require_relative'
	from /home/eregon/.bundle/ruby/3.1.0/gems/bundler-2.3.26/exe/bundle:13:in `<top (required)>'
	from /home/eregon/.bundle/ruby/3.1.0/bin/bundle:25:in `load'
	from /home/eregon/.bundle/ruby/3.1.0/bin/bundle:25:in `<main>'
```

The original case I found is `sh "bundle package"` inside the Rakefile of concurrent-ruby, but the above does the same with less setup.
`Bundler.with_original_env` is a possible workaround but it shouldn't be neeeded, any shelling to bundle inside `bundle exec rake` should pick the right Bundler with no errors.

From https://bundler.slack.com/archives/C08V1RPAP/p1674491821354229

**Comment by Confusion** [comment]
I've observed this issue using rubygems 3.4.3 with bundler 2.4.3 on Ruby 3.1.3, when shelling out to `bundle exec`. As @eregon suggested, `Bundler.with_original_env` is a successful workaround.

**Comment by hsbt** [comment]
This was fixed by `exe/bundle` always resolving the runtime through `$LOAD_PATH` (121a861c39, Bundler 2.5.0) and the metadata source materializing the actually loaded copy from `Gem.loaded_specs` (ada6de765d, Bundler 2.6.0).

I reconstructed the scenario with two rubies sharing one `BUNDLE_PATH` under the same ABI and bundle exec now runs cleanly, so I am closing this. If you can still reproduce it on Bundler 4, please comment and we will reopen.
