### ISSUE TITLE
Make gem uninstall more forgiving

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#6347]
Atm if you uninstall multiple gems and one of those gems is a default gem, process just fails with error, doing nothing.
Would be nice if I could uninstall all gems that possible. Warning could be emitted for not uninstalled ones. 

This is a follow up for #6345

**Comment by simi** [comment]
Can you provide more info? I tried following.

```bash
$ gem install ABO
Fetching ABO-0.0.2.gem
Successfully installed ABO-0.0.2
Building YARD (yri) index for ABO-0.0.2...
Done installing documentation for ABO after 0 seconds
1 gem installed

$ gem uninstall zlib ABO
Successfully uninstalled ABO-0.0.2
Gem zlib-2.1.1 cannot be uninstalled because it is a default gem

$ gem list | grep ABO
# nothing, uninstalled
```

**Comment by hurricup** [comment]
this probably depends on uninstallation order. In our case we have a bunch of gems we need to uninstall and some of those are happen to be default gems. And rubygems fails because of this without uninstalling the rest.

**Comment by deivid-rodriguez** [comment]
I've never seen this either. I would've said the current behavior is exactly what you request: uninstall all possible, warn when something could not be uninstalled. Can you show the error you're getting?

**Comment by deivid-rodriguez** [comment]
Please reopen if you see this again 👍.

**Comment by hurricup** [comment]
So, here it seems again:

Gem env:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.17
  - RUBY VERSION: 3.3.0 (2023-12-25 patchlevel 0) [x86_64-darwin21]
  - INSTALLATION DIRECTORY: /Users/builduser/.rvm/gems/ruby-3.3.0
  - USER INSTALLATION DIRECTORY: /Users/builduser/.local/share/gem/ruby/3.3.0
  - RUBY EXECUTABLE: /Users/builduser/.rvm/rubies/ruby-3.3.0/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/builduser/.rvm/gems/ruby-3.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/builduser/.cache/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/builduser/.rvm/rubies/ruby-3.3.0/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-21
  - GEM PATHS:
     - /Users/builduser/.rvm/gems/ruby-3.3.0
     - /Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/", "https://rubygems.org/"]
     - :concurrent_downloads => 8
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/builduser/.rvm/gems/ruby-3.3.0/bin
     - /Users/builduser/.rvm/gems/ruby-3.3.0@global/bin
     - /Users/builduser/.rvm/rubies/ruby-3.3.0/bin
     - /Users/builduser/.rvm/bin
     - /Users/builduser/.cargo/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
```
Command 
```
/bin/bash -c "/Users/builduser/.rvm/bin/rvm ruby-3.3.0 do /Users/builduser/.rvm/rubies/ruby-3.3.0/bin/ruby /Users/builduser/.rvm/rubies/ruby-3.3.0/bin/gem uninstall -a -x -I -V --backtrace irb:1.14.0 brakeman:6.1.2 bindex:0.8.1 io-console:0.7.2 actionmailbox:7.0.8.4 public_suffix:6.0.1 sprockets-rails:3.5.2 activemodel:7.0.8.4 selenium-webdriver:4.23.0 web-console:4.2.1 actiontext:7.0.8.4 capybara:3.40.0 racc:1.8.1 regexp_parser:2.9.2 addressable:2.8.7 activerecord:7.0.8.4 rubyzip:2.3.2 importmap-rails:2.0.1 rexml:3.3.4 reline:0.5.9 rdoc:6.7.0 timeout:0.4.1 net-protocol:0.2.2 turbo-rails:2.0.6 puma:5.6.8 sprockets:4.2.1 railties:7.0.8.4 net-smtp:0.5.0 minitest:5.24.1 stringio:3.1.1 activestorage:7.0.8.4 websocket:1.2.11 rake:13.2.1 stimulus-rails:1.3.3 base64:0.2.0 debug:1.9.2 jbuilder:2.12.0 actionpack:7.0.8.4 msgpack:1.7.2 date:3.3.4 bootsnap:1.18.4 rails:7.0.8.4 activejob:7.0.8.4 strscan:3.1.0 xpath:3.2.0 activesupport:7.0.8.4 actioncable:7.0.8.4 net-imap:0.4.14 actionmailer:7.0.8.4 sqlite3:1.7.3 actionview:7.0.8.4"
```
We are requesting to remove the 51 gems:
```
actioncable:7.0.8.4
actionmailbox:7.0.8.4
actionmailer:7.0.8.4
actionpack:7.0.8.4
actiontext:7.0.8.4
actionview:7.0.8.4
activejob:7.0.8.4
activemodel:7.0.8.4
activerecord:7.0.8.4
activestorage:7.0.8.4
activesupport:7.0.8.4
addressable:2.8.7
base64:0.2.0
bindex:0.8.1
bootsnap:1.18.4
brakeman:6.1.2
capybara:3.40.0
date:3.3.4
debug:1.9.2
importmap-rails:2.0.1
io-console:0.7.2
irb:1.14.0
jbuilder:2.12.0
minitest:5.24.1
msgpack:1.7.2
net-imap:0.4.14
net-protocol:0.2.2
net-smtp:0.5.0
public_suffix:6.0.1
puma:5.6.8
racc:1.8.1
rails:7.0.8.4
railties:7.0.8.4
rake:13.2.1
rdoc:6.7.0
regexp_parser:2.9.2
reline:0.5.9
rexml:3.3.4
rubyzip:2.3.2
selenium-webdriver:4.23.0
sprockets-rails:3.5.2
sprockets:4.2.1
sqlite3:1.7.3
stimulus-rails:1.3.3
stringio:3.1.1
strscan:3.1.0
timeout:0.4.1
turbo-rails:2.0.6
web-console:4.2.1
websocket:1.2.11
xpath:3.2.0
```
output (NB: stdout/stderr are separated, not in chronological order with each other):
```
stdout: Successfully uninstalled sqlite3-1.7.3-x86_64-darwin
stdout: Successfully uninstalled rails-7.0.8.4
stdout: Successfully uninstalled actioncable-7.0.8.4
stdout: Successfully uninstalled actionmailer-7.0.8.4
stdout: Removing bootsnap
stdout: Successfully uninstalled bootsnap-1.18.4
stdout: Successfully uninstalled date-3.3.4
stdout: There was both a regular copy and a default copy of date-3.3.4. The regular copy was successfully uninstalled, but the default copy was left around because default gems can't be removed.
stdout: Successfully uninstalled msgpack-1.7.2
stdout: Successfully uninstalled jbuilder-2.12.0
stdout: Successfully uninstalled debug-1.9.2
stdout: Successfully uninstalled base64-0.2.0
stdout: There was both a regular copy and a default copy of base64-0.2.0. The regular copy was successfully uninstalled, but the default copy was left around because default gems can't be removed.
stdout: Successfully uninstalled stimulus-rails-1.3.3
stdout: Successfully uninstalled stringio-3.1.1
stdout: Removing puma
stdout: Removing pumactl
stdout: Successfully uninstalled puma-5.6.8
stdout: Successfully uninstalled turbo-rails-2.0.6
stdout: Successfully uninstalled net-protocol-0.2.2
stdout: There was both a regular copy and a default copy of net-protocol-0.2.2. The regular copy was successfully uninstalled, but the default copy was left around because default gems can't be removed.
stdout: Successfully uninstalled timeout-0.4.1
stdout: There was both a regular copy and a default copy of timeout-0.4.1. The regular copy was successfully uninstalled, but the default copy was left around because default gems can't be removed.
stdout: Successfully uninstalled importmap-rails-2.0.1
stdout: Successfully uninstalled capybara-3.40.0
stdout: Successfully uninstalled xpath-3.2.0
stdout: Successfully uninstalled regexp_parser-2.9.2
stdout: Successfully uninstalled addressable-2.8.7
stdout: Successfully uninstalled actiontext-7.0.8.4
stdout: Successfully uninstalled web-console-4.2.1
stdout: Successfully uninstalled railties-7.0.8.4
stdout: Successfully uninstalled rake-13.2.1
stdout: Successfully uninstalled selenium-webdriver-4.23.0
stdout: Successfully uninstalled websocket-1.2.11
stdout: Successfully uninstalled rubyzip-2.3.2
stdout: Successfully uninstalled rexml-3.3.4
stdout: Successfully uninstalled strscan-3.1.0
stderr: ERROR:  While executing gem ... (Gem::InstallError)
stderr:     gem "base64" is not installed
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/uninstaller.rb:96:in `uninstall'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:197:in `uninstall'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:183:in `uninstall_gem'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:178:in `block in uninstall_specific'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:170:in `each'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:170:in `uninstall_specific'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:132:in `execute'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:255:in `invoke_command'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/bin/gem:12:in `<main>'
```

Not quite sure what `gem "base64" is not installed` means together with `Successfully uninstalled base64-0.2.0`

**Comment by hurricup** [comment]
@deivid-rodriguez not quite sure how to re-open this

**Comment by hurricup** [comment]
In other case this happening on other gem:
```
Exit code: 1
stdout: Successfully uninstalled sqlite3-1.7.3-x86_64-darwin
stdout: Successfully uninstalled rails-7.0.8.4
stdout: Successfully uninstalled actioncable-7.0.8.4
stdout: Successfully uninstalled actionmailer-7.0.8.4
stdout: Removing bootsnap
stdout: Successfully uninstalled bootsnap-1.18.4
stdout: Successfully uninstalled date-3.3.4
stdout: There was both a regular copy and a default copy of date-3.3.4. The regular copy was successfully uninstalled, but the default copy was left around because default gems can't be removed.
stderr: ERROR:  While executing gem ... (Gem::InstallError)
stderr:     gem "date" is not installed
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/uninstaller.rb:96:in `uninstall'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:197:in `uninstall'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:183:in `uninstall_gem'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:178:in `block in uninstall_specific'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:170:in `each'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:170:in `uninstall_specific'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/commands/uninstall_command.rb:132:in `execute'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:255:in `invoke_command'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
stderr: 	/Users/builduser/.rvm/rubies/ruby-3.3.0/bin/gem:12:in `<main>'
```

I see the pattern here. In both cases it is about the gem duplicating default one (btw, why should it be installed at all?)
Observing this only on mac and with ruby 3.3

**Comment by hurricup** [comment]
And sometimes it works fine, so looks like kinda race or smth.

**Comment by deivid-rodriguez** [comment]
I managed to reproduce the issue and hopefully #7949 fixes it.

**Comment by hurricup** [comment]
Confirming this update fixed our issues. Thank you!!!
