### ISSUE TITLE
error ruby 3.0.2 bundled 2.3.15

### ISSUE THREAD

**Issue by gabrielgiroe1** [rubygems/rubygems#6354]
```
Errno::EACCES: Permission denied @ rb_sysopen - /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/wrappers/thor
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `initialize'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `open'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `install_file'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:50:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:27:in `block in install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:26:in `each'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:26:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb:15:in `block in <top (required)>'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:367:in `block in run_post_install_hooks'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:366:in `each'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:366:in `run_post_install_hooks'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:43:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:171:in `install_serially'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:97:in `call'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer.rb:259:in `install_in_parallel'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer.rb:209:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer.rb:89:in `block in run'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/process_lock.rb:15:in `lock'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer.rb:71:in `run'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer.rb:23:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli/install.rb:62:in `run'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli.rb:255:in `block in install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/settings.rb:131:in `temporary'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli.rb:254:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
  /Users/georgelgabrielgiroe/developer/instagram/bin/bundle:113:in `load'
  /Users/georgelgabrielgiroe/developer/instagram/bin/bundle:113:in `<main>'
Errno::EACCES: Permission denied @ rb_sysopen - /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/wrappers/thor
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `initialize'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `open'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:74:in `install_file'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:50:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:27:in `block in install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:26:in `each'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:26:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb:15:in `block in <top (required)>'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:367:in `block in run_post_install_hooks'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:366:in `each'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:366:in `run_post_install_hooks'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:43:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/worker.rb:62:in `apply_func'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in `loop'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in `process_queue'
  /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.15/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler             2.3.15
  Platforms         ruby, arm64-darwin-22
Ruby                3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [arm64-darwin-22]
  Full Path         /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/bin/ruby
  Config Dir        /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/etc
RubyGems            3.2.22
  Gem Home          /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0
  Gem Path          /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0
  User Home         /Users/georgelgabrielgiroe
  User Path         /Users/georgelgabrielgiroe/.gem/ruby/3.0.0
  Bin Dir           /Users/georgelgabrielgiroe/.rvm/rubies/ruby-3.0.2/bin
OpenSSL             
  Compiled          OpenSSL 1.1.1s  1 Nov 2022
  Loaded            OpenSSL 1.1.1s  1 Nov 2022
  Cert File         /opt/homebrew/etc/openssl@1.1/cert.pem
  Cert Dir          /opt/homebrew/etc/openssl@1.1/certs
Tools               
  Git               2.37.1 (Apple Git-137.1)
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-06-01
Git SHA           e7e41afd92
Released Version  true
```

## Bundler settings

```
gemfile
  Set via BUNDLE_GEMFILE: "/Users/georgelgabrielgiroe/developer/instagram/Gemfile"
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
gem 'bootstrap', '~> 5.2.3'

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.4.2)
      actionpack (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.4.2)
      actionpack (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activestorage (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.4.2)
      actionpack (= 7.0.4.2)
      actionview (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.4.2)
      actionview (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.4.2)
      actionpack (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activestorage (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.4.2)
      activesupport (= 7.0.4.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.4.2)
      activesupport (= 7.0.4.2)
      globalid (>= 0.3.6)
    activemodel (7.0.4.2)
      activesupport (= 7.0.4.2)
    activerecord (7.0.4.2)
      activemodel (= 7.0.4.2)
      activesupport (= 7.0.4.2)
    activestorage (7.0.4.2)
      actionpack (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.4.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    autoprefixer-rails (10.4.7.0)
      execjs (~> 2)
    bindex (0.8.1)
    bootsnap (1.16.0)
      msgpack (~> 1.2)
    bootstrap (5.2.3)
      autoprefixer-rails (>= 9.1.0)
      popper_js (>= 2.11.6, < 3)
      sassc-rails (>= 2.0.0)
    builder (3.2.4)
    capybara (3.38.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.2.0)
    crass (1.0.6)
    date (3.3.3)
    debug (1.7.1)
      irb (>= 1.5.0)
      reline (>= 0.3.1)
    erubi (1.12.0)
    execjs (2.8.1)
    ffi (1.15.5)
    globalid (1.1.0)
      activesupport (>= 5.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.1.5)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.6.0)
    irb (1.6.2)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.19.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.17.0)
    msgpack (1.6.0)
    net-imap (0.3.4)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-smtp (0.3.3)
      net-protocol
    nio4r (2.5.8)
    nokogiri (1.14.1-arm64-darwin)
      racc (~> 1.4)
    popper_js (2.11.6)
    public_suffix (5.0.1)
    puma (5.6.5)
      nio4r (~> 2.0)
    racc (1.6.2)
    rack (2.2.6.2)
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (7.0.4.2)
      actioncable (= 7.0.4.2)
      actionmailbox (= 7.0.4.2)
      actionmailer (= 7.0.4.2)
      actionpack (= 7.0.4.2)
      actiontext (= 7.0.4.2)
      actionview (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activemodel (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activestorage (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      bundler (>= 1.15.0)
      railties (= 7.0.4.2)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.5.0)
      loofah (~> 2.19, >= 2.19.1)
    railties (7.0.4.2)
      actionpack (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    regexp_parser (2.6.2)
    reline (0.3.2)
      io-console (~> 0.5)
    rexml (3.2.5)
    rubyzip (2.3.2)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.8.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sprockets (4.2.0)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.6.0-arm64-darwin)
    stimulus-rails (1.2.1)
      railties (>= 6.0.0)
    thor (1.2.1)
    tilt (2.0.11)
    timeout (0.3.1)
    turbo-rails (1.3.3)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.2.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.6)

PLATFORMS
  arm64-darwin-22

DEPENDENCIES
  bootsnap
  bootstrap (~> 5.2.3)
  capybara
  debug
  importmap-rails
  jbuilder
  puma (~> 5.0)
  rails (~> 7.0.4.2)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 3.0.2p107

BUNDLED WITH
   2.3.15
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

Fill this with a list of steps maintainers can follow to reproduce your issue. Note that while you are seeing this issue in your computer, maintainers might not see the same thing on theirs. There is a number of things that could influence this:

* How your ruby is setup (OS package, from source, using a version manager).
* How bundler & rubygems are configured.
* The version of each involved piece of software that you are using.
* ...

The more complete the steps to simulate your particular environment are, the easier it will be for maintainers to reproduce your issue on their machines.

Ideally, we recommend you to set up the list of steps as a [Dockerfile](https://docs.docker.com/get-started/). A Dockerfile provides a neutral environment that should give the same results, no matter where it's run.

-->

**Comment by deivid-rodriguez** [comment]
Hello @gabrielgiroe1. You have only copy-pasted an error without explaining anything. And the error show that it happens when using old Bundler, Ruby, and RubyGems versions. Please upgrade Bundler, Ruby, and RubyGems and report a new issue if you are still running into problems. And also please fill in the questions in the bug report template so that we can actually help you. Thanks!
