### ISSUE TITLE
undefined method `path' for "data.tar.gz" String

### ISSUE THREAD

**Issue by UnclePene** [rubygems/rubygems#6379]
Hi Team,

As instructed in the error message, below is the error that I got when attempting to install a gem from a file. I'm using ZSH as my shell. Please let me know if anymore information is needed, I did not fill out the standard template as the error message told me to copy and paste the template instead.

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `path' for "data.tar.gz":String
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:58:in `initialize'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:691:in `new'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:691:in `rescue in verify_gz'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:686:in `verify_gz'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:654:in `verify_entry'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:666:in `block in verify_files'
  /usr/lib/ruby/vendor_ruby/rubygems/package/tar_reader.rb:65:in `each'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:665:in `verify_files'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:596:in `block (2 levels) in verify'
  /usr/lib/ruby/vendor_ruby/rubygems/package/tar_reader.rb:27:in `new'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:593:in `block in verify'
  /usr/lib/ruby/vendor_ruby/rubygems/package/file_source.rb:29:in `open'
  /usr/lib/ruby/vendor_ruby/rubygems/package/file_source.rb:29:in `with_read_io'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:592:in `verify'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:573:in `spec'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/rubygems_gem_installer.rb:95:in `spec'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/source/rubygems.rb:183:in `install'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:62:in `apply_func'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:54:in `loop'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:54:in `process_queue'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Zlib::GzipFile::Error: unexpected end of file
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:688:in `read'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:688:in `block in verify_gz'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:687:in `wrap'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:687:in `verify_gz'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:654:in `verify_entry'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:666:in `block in verify_files'
  /usr/lib/ruby/vendor_ruby/rubygems/package/tar_reader.rb:65:in `each'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:665:in `verify_files'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:596:in `block (2 levels) in verify'
  /usr/lib/ruby/vendor_ruby/rubygems/package/tar_reader.rb:27:in `new'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:593:in `block in verify'
  /usr/lib/ruby/vendor_ruby/rubygems/package/file_source.rb:29:in `open'
  /usr/lib/ruby/vendor_ruby/rubygems/package/file_source.rb:29:in `with_read_io'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:592:in `verify'
  /usr/lib/ruby/vendor_ruby/rubygems/package.rb:573:in `spec'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/rubygems_gem_installer.rb:95:in `spec'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/source/rubygems.rb:183:in `install'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:62:in `apply_func'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:54:in `loop'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:54:in `process_queue'
  /home/master/gems/gems/bundler-2.4.6/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.6
  Platforms   ruby, x86_64-linux
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-linux]
  Full Path   /usr/bin/ruby3.0
  Config Dir  /etc
RubyGems      3.3.5
  Gem Home    /home/master/gems
  Gem Path    /home/master/.local/share/gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0:/usr/share/rubygems-integration/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0:/home/master/gems
  User Home   /home/master
  User Path   /home/master/.local/share/gem/ruby/3.0.0
  Bin Dir     /home/master/gems/bin
OpenSSL       
  Compiled    OpenSSL 3.0.2 15 Mar 2022
  Loaded      OpenSSL 3.0.2 15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.34.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-01-31
Git SHA           598c04d54a
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'jekyll'
```

### Gemfile.lock

```
<No /home/master/testing/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

### Terminal error message
```
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60path%27+for+%22data.tar.gz%22+String&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
```

**Comment by deivid-rodriguez** [comment]
So, what's in `/home/master/gems`. Is there some `.gem` file that you built yourself? It seems that somehow you built a corrupted gem?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
