### ISSUE TITLE
Cannot get Gemfile.lock when I run bundle install

### ISSUE THREAD

**Issue by RoyZiO** [rubygems/rubygems#6393]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /var/lib/gems/2.7.0 directory.
  /usr/lib/ruby/2.7.0/rubygems/installer.rb:735:in `verify_gem_home'
  /usr/lib/ruby/2.7.0/rubygems/installer.rb:908:in `pre_install_checks'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:64:in `pre_install_checks'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:12:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:200:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:167:in `do_install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:158:in `block in worker_pool'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - /var/lib/gems/2.7.0/bundler.lock
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `initialize'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `open'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `lock'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/installer.rb:71:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/installer.rb:23:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/cli/install.rb:62:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/cli.rb:261:in `block in install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/settings.rb:131:in `temporary'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/cli.rb:260:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /var/lib/gems/2.7.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler       2.4.7
  Platforms   ruby, x86_64-linux
Ruby          2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-linux]
  Full Path   /usr/bin/ruby2.7
  Config Dir  /etc
RubyGems      3.1.2
  Gem Home    /var/lib/gems/2.7.0
  Gem Path    /home/student/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0
  User Home   /home/student
  User Path   /home/student/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1f  31 Mar 2020
  Loaded      OpenSSL 1.1.1f  31 Mar 2020
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.25.1
  RVM         not installed
  rbenv       rbenv 1.2.0-46-g52acbdf
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-02-15
Git SHA           5d717a27e0
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "hashie"
gem "sinatra", "2.0.2"
gem "octokit", "~> 2.0"
#gem "awesome_print", git: "git@github.com:awesome-print/awesome_print.git"
gem "rspec"
gem "rest-client"
gem "pry", :group => "development"

#group :test do
 # gem "rspec"
#end
```

### Gemfile.lock

```
<No /home/student/Development/phase-3/phase-3-ruby-building-applications-gems-and-bundler/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Hi! Do you want to install gems or to generate a lock file? If you want to generate a lockfile, then `bundle lock` will do. If you want to install gems, then you need to make sure Bundler installs to a location it can write to. The default location where Bundler wants to install gems is not writable by Bundler (`/var/lib/gems/2.7.0`, I assume owned by root). You can fix this in several ways:

* `bundle config path <writable_path>`, and then `bundle install` again.
* `sudo bundle install`.
* Change permissions of `/var/lib/gems/2.7.0` to be writable by Bundler.

Good luck!
