### ISSUE TITLE
NoMethodError: private method `select' called for nil:NilClass

### ISSUE THREAD

**Issue by rammpeter** [rubygems/rubygems#6397]
### Describe the problem as clearly as you can

"bundle install" without an existing Gefiel.lock leads to this error in jRuby 9.4.1.0

### Did you try upgrading rubygems & bundler?

yes

### Post steps to reproduce the problem

> git clone github.com/rammpeter/panorama
> change content of file  .ruby-version to "jruby-9.4.1.0"
> rm Gemfile.lock
> rvm use jruby-9.4.1.0 or similar
> bundle install

### Which command did you run?

> bundle install

### What were you expecting to happen?

Working without error, creating Gemfile.lock and install dependencies

### What actually happened?

NoMethodError: private method `select' called for nil:NilClass

### If not included with the output of your command, run `bundle env` and paste the output below

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: private method `select' called for nil:NilClass
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/installer.rb:219:in `load_plugins'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/installer.rb:84:in `block in run'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/process_lock.rb:12:in `block in lock'
  org/jruby/RubyIO.java:1176:in `open'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `lock'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/installer.rb:71:in `run'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/installer.rb:23:in `install'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/cli/install.rb:62:in `run'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/cli.rb:261:in `block in install'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/settings.rb:131:in `temporary'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/cli.rb:260:in `install'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/exe/bundle:45:in `block in <main>'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared/gems/bundler-2.4.7/exe/bundle:33:in `<main>'
  org/jruby/RubyKernel.java:1091:in `load'
  /Users/pramm/.rvm/gems/jruby-9.4.1.0/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler             2.4.7
  Platforms         ruby, universal-java-19
Ruby                3.1.0p0 (2023-02-07 revision 237d5fa5f4487aa9f1b88e0de8fe600b4dad2dc2) [universal-java-19]
  Full Path         /Users/pramm/.rvm/rubies/jruby-9.4.1.0/bin/jruby
  Config Dir        /Users/pramm/.rvm/rubies/jruby-9.4.1.0/etc
RubyGems            3.3.25
  Gem Home          /Users/pramm/.rvm/gems/jruby-9.4.1.0
  Gem Path          /Users/pramm/.rvm/gems/jruby-9.4.1.0:/Users/pramm/.rvm/rubies/jruby-9.4.1.0/lib/ruby/gems/shared
  User Home         /Users/pramm
  User Path         /Users/pramm/.local/share/gem/jruby/3.1.0
  Bin Dir           /Users/pramm/.rvm/gems/jruby-9.4.1.0/bin
OpenSSL             
  Compiled          JRuby-OpenSSL 0.14.0
  Loaded            JRuby-OpenSSL 0.14.0
  Cert File         /usr/local/Cellar/openjdk/19.0.2/libexec/openjdk.jdk/Contents/Home/lib/security/cacerts
  Cert Dir          /etc/ssl/certs
Tools               
  Git               2.39.1
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
Gem.ruby            /Users/pramm/.rvm/rubies/jruby-9.4.1.0/bin/jruby
bundle #!           /usr/bin/env jruby

```

## Bundler Build Metadata

```
Built At          2023-02-15
Git SHA           5d717a27e0
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

# Variante für build war-file
gem 'panorama_gem', :git => 'http://github.com/rammpeter/Panorama_Gem'

# Development-Variante mit direktem File-Zugriff
#gem 'panorama_gem', path: '~/Documents/Projekte/rammpeter.github/Panorama_Gem'

# Use Puma as the app server
gem 'puma'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyrhino'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'
# gem 'sass-rails', '>= 6'
# gem 'sass-rails', '~> 5.0'
# Use the deprecated sass instead of sassc because sassc is not compatible with warbler (pure ruby needed)
# gem 'sass'

gem 'listen', group: :development

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Build Panorama.war with warbler (./build_war.sh), Use warbler directly from git
# gem install specific_install
# gem specific_install https://github.com/jruby/warbler.git

# Adding warbler this waay sadly doesn't install the executable warble
#group :development do
#  gem 'warbler', :git => 'https://github.com/jruby/warbler.git'
#end
```

### Gemfile.lock

```
<No /private/tmp/panorama/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by rammpeter** [comment]
The problem could be solved by replacing 
> gem 'panorama_gem', :git => 'http://github.com/rammpeter/Panorama_Gem'
with
> gem 'panorama_gem', :git => 'https://github.com/rammpeter/Panorama_Gem'
in Gemfile.

The original URL 'http://github.com/rammpeter/Panorama_Gem' resulted in 301 redirect response code.

But it would be nice to have a more expressive error message in that case.

**Comment by deivid-rodriguez** [comment]
Does this still reproduce after upgrading RubyGems (`gem update --system`)?

**Comment by deivid-rodriguez** [comment]
I just tried this with the JRuby, RubyGems and Bundler, and it all worked fine. So I'm going to assume this is fixed. If you can still reproduce this with Bundler 2.4.8, RubyGems 3.4.8, and JRuby 9.4.2.0, feel free to reopen!
