### ISSUE TITLE
bundle install error 

### ISSUE THREAD

**Issue by xiaoduwuer** [rubygems/rubygems#6445]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
LoadError: dlopen(/Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle, 0x0009): tried: '/Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/date-3.3.3/lib/date_core.bundle
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/date-3.3.3/lib/date.rb:4:in `<top (required)>'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/time.rb:3:in `<top (required)>'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/request.rb:3:in `<top (required)>'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/fetcher.rb:7:in `<top (required)>'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/cli/install.rb:50:in `run'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/cli.rb:261:in `block in install'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/settings.rb:131:in `temporary'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/cli.rb:260:in `install'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
  /Users/maying/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
  /Users/maying/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler       2.4.7
  Platforms   ruby, -darwin-21
Ruby          2.6.5p114 (2019-10-01 revision 67812) [-darwin-21]
  Full Path   /Users/maying/.rbenv/versions/2.6.5/bin/ruby
  Config Dir  /Users/maying/.rbenv/versions/2.6.5/etc
RubyGems      3.0.3
  Gem Home    /Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
  Gem Path    /Users/maying/.gem/ruby/2.6.0:/Users/maying/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
  User Home   /Users/maying
  User Path   /Users/maying/.gem/ruby/2.6.0
  Bin Dir     /Users/maying/.rbenv/versions/2.6.5/bin
OpenSSL
  Compiled    OpenSSL 1.1.1t  7 Feb 2023
  Loaded      OpenSSL 1.1.1t  7 Feb 2023
  Cert File   /Users/maying/.rbenv/versions/2.6.5/openssl/ssl/cert.pem
  Cert Dir    /Users/maying/.rbenv/versions/2.6.5/openssl/ssl/certs
Tools
  Git         2.32.1 (Apple Git-133)
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-02-15
Git SHA           5d717a27e0
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'


gem 'rails', '~> 6.1.6'
gem 'pg', '>= 0.18', '< 2.0'
gem 'dotenv-rails', groups: [:development, :test], require: 'dotenv/rails-now'
gem 'activerecord-postgis-adapter'
gem 'activerecord-import'
gem 'mini_sql'
gem 'puma', '~> 4.1'
gem 'bcrypt', '~> 3.1.7'
gem 'active_model_serializers', '~> 0.10.2'

gem 'graphql', '~> 1.10', '>= 1.10.6'
gem 'graphql-batch'
gem 'json_web_token', '~> 0.3.5'

gem 'aasm', '~> 5.0', '>= 5.0.8'
gem 'rolify', '~> 5.2'
gem 'action_policy-graphql', '~> 0.4'
gem 'search_object_graphql', '~> 0.3.2'
gem 'dingtalk', github: 'feipinghuang/dingtalk'
gem 'feishu', github: 'OneMain/feishu'
# gem 'feishu', path: './local/feishu'
gem 'groupdate', '~> 5.0'
gem 'counter_culture', '~> 2.0'
# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

gem 'activestorage_qiniu', github: 'feipinghuang/activestorage_qiniu'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

gem 'rack-cors'

gem 'mina', '~> 1.2', require: false
gem 'mina-ng-puma', require: false
gem "mina-sidekiq", "~> 1.1", require: false

gem 'anyway_config', '~> 2.0.0'

gem 'rollbar'
gem 'whenever', require: false
gem 'mina-whenever', require: false

gem 'hiredis', '~> 0.6.0'
gem 'redis', '>= 4.6.0', require: ['redis', 'redis/connection/hiredis']
gem "sidekiq", "~> 6.4"
gem "sidekiq-cron", "~> 1.4"

gem 'wechat-rails', github: 'guanyun/wechat-rails'

gem 'rubyXL', '~> 3.4', '>= 3.4.14'
gem 'roo-xls'

gem 'acts-as-taggable-on'

gem 'after_commit_everywhere', '~> 0.1.5'

gem "kaminari", "~> 1.2"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'faker'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'graphiql-rails', github: 'guanyun/graphiql-rails'
  # gem 'graphiql-rails', path: './local/graphiql-rails'
  gem 'sprockets', '~> 3'
  gem 'annotate'
  gem 'awesome_print'
  gem 'next_rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "apollo_upload_server", "~> 2.0"

gem "audited", "~> 5.0"

gem "selenium-webdriver", "~> 3.142"
gem "vessel"
```

### Gemfile.lock

```
GIT
  remote: https://github.com/OneMain/feishu.git
  revision: 8f7f0b8bbcacf36800eb783064a0d1ca411a460a
  specs:
    feishu (0.1.0)
      anyway_config
      httparty
      redis

GIT
  remote: https://github.com/feipinghuang/activestorage_qiniu.git
  revision: 475743a91d49a4c8281c15493f787f901ba6f61a
  specs:
    activestorage_qiniu (0.2.0)
      qiniu (~> 6.9)
      rails (>= 5.1.6.2)
      retries (~> 0.0.5)

GIT
  remote: https://github.com/feipinghuang/dingtalk.git
  revision: d702163b09bb195703928cc89b2f25bbb916fb2d
  specs:
    dingtalk (0.1.0)
      anyway_config (= 2.0.1)
      httparty (~> 0.16)
      redis

GIT
  remote: https://github.com/guanyun/graphiql-rails.git
  revision: 396345bf2097f439d8aaa31933bc587ac35ca115
  specs:
    graphiql-rails (1.8.0)
      railties
      sprockets-rails

GIT
  remote: https://github.com/guanyun/wechat-rails.git
  revision: d3dafc40b68edaf68baf70842d6f51152fb050fa
  specs:
    wechat-rails (0.1.1)
      anyway_config (= 2.0.1)
      nokogiri (>= 1.6.0)
      rails (>= 3.2.14)
      rest-client (>= 2.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    aasm (5.0.8)
      concurrent-ruby (~> 1.0)
    action_policy (0.4.3)
    action_policy-graphql (0.4.0)
      action_policy (>= 0.3.0)
      graphql (>= 1.9.3)
    actioncable (6.1.6)
      actionpack (= 6.1.6)
      activesupport (= 6.1.6)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.6)
      actionpack (= 6.1.6)
      activejob (= 6.1.6)
      activerecord (= 6.1.6)
      activestorage (= 6.1.6)
      activesupport (= 6.1.6)
      mail (>= 2.7.1)
    actionmailer (6.1.6)
      actionpack (= 6.1.6)
      actionview (= 6.1.6)
      activejob (= 6.1.6)
      activesupport (= 6.1.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.6)
      actionview (= 6.1.6)
      activesupport (= 6.1.6)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.6)
      actionpack (= 6.1.6)
      activerecord (= 6.1.6)
      activestorage (= 6.1.6)
      activesupport (= 6.1.6)
      nokogiri (>= 1.8.5)
    actionview (6.1.6)
      activesupport (= 6.1.6)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    active_model_serializers (0.10.13)
      actionpack (>= 4.1, < 7.1)
      activemodel (>= 4.1, < 7.1)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    activejob (6.1.6)
      activesupport (= 6.1.6)
      globalid (>= 0.3.6)
    activemodel (6.1.6)
      activesupport (= 6.1.6)
    activerecord (6.1.6)
      activemodel (= 6.1.6)
      activesupport (= 6.1.6)
    activerecord-import (1.4.1)
      activerecord (>= 4.2)
    activerecord-postgis-adapter (7.1.1)
      activerecord (~> 6.1)
      rgeo-activerecord (~> 7.0.0)
    activestorage (6.1.6)
      actionpack (= 6.1.6)
      activejob (= 6.1.6)
      activerecord (= 6.1.6)
      activesupport (= 6.1.6)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.6)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    acts-as-taggable-on (9.0.1)
      activerecord (>= 6.0, < 7.1)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    after_commit_action (1.1.0)
      activerecord (>= 3.0.0)
      activesupport (>= 3.0.0)
    after_commit_everywhere (0.1.5)
      activerecord (>= 4.2)
    annotate (3.1.1)
      activerecord (>= 3.2, < 7.0)
      rake (>= 10.4, < 14.0)
    anyway_config (2.0.1)
      ruby-next-core (>= 0.5.1)
    apollo_upload_server (2.0.5)
      actionpack (>= 4.2)
      graphql (>= 1.8)
    audited (5.0.2)
      activerecord (>= 5.0, < 7.1)
    awesome_print (1.8.0)
    bcrypt (3.1.13)
    bcrypt (3.1.13-java)
    bootsnap (1.4.6)
      msgpack (~> 1.0)
    bootsnap (1.4.6-java)
      msgpack (~> 1.0)
    builder (3.2.4)
    byebug (11.1.1)
    case_transform (0.2)
      activesupport
    childprocess (3.0.0)
    chronic (0.10.2)
    cliver (0.3.2)
    colorize (0.8.1)
    concurrent-ruby (1.1.10)
    connection_pool (2.2.5)
    counter_culture (2.5.1)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
      after_commit_action (~> 1.0)
    crass (1.0.6)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    dotenv-rails (2.7.6)
      dotenv (= 2.7.6)
      railties (>= 3.2)
    erubi (1.10.0)
    et-orbi (1.2.7)
      tzinfo
    faker (2.11.0)
      i18n (>= 1.6, < 2)
    ferrum (0.11)
      addressable (~> 2.5)
      cliver (~> 0.3)
      concurrent-ruby (~> 1.1)
      websocket-driver (>= 0.6, < 0.8)
    ffi (1.13.1)
    ffi (1.13.1-java)
    ffi (1.13.1-x64-mingw32)
    ffi (1.13.1-x86-mingw32)
    fugit (1.5.3)
      et-orbi (~> 1, >= 1.2.7)
      raabro (~> 1.4)
    globalid (1.0.0)
      activesupport (>= 5.0)
    graphql (1.10.6)
    graphql-batch (0.4.2)
      graphql (>= 1.3, < 2)
      promise.rb (~> 0.7.2)
    groupdate (5.0.0)
      activesupport (>= 5)
    hiredis (0.6.3)
    hiredis (0.6.3-java)
    http-accept (1.7.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    json (2.3.0)
    json (2.3.0-java)
    json_web_token (0.3.5)
      json (~> 2.1)
    jsonapi-renderer (0.2.2)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.18.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    method_source (1.0.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    mina (1.2.3)
      open4 (~> 1.3.4)
      rake
    mina-ng-puma (1.4.0)
      mina (~> 1.2.0)
      puma (>= 2.13)
    mina-sidekiq (1.1.0)
      mina (>= 1.0.2)
    mina-whenever (1.0.1)
      mina (~> 1.0)
    mini_mime (1.1.2)
    mini_portile2 (2.8.0)
    mini_sql (0.3)
    minitest (5.16.1)
    msgpack (1.3.3)
    msgpack (1.3.3-java)
    msgpack (1.3.3-x64-mingw32)
    msgpack (1.3.3-x86-mingw32)
    multi_xml (0.6.0)
    netrc (0.11.0)
    next_rails (1.1.0)
      colorize (>= 0.8.1)
    nio4r (2.5.8)
    nio4r (2.5.8-java)
    nokogiri (1.13.6)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.6-java)
      racc (~> 1.4)
    nokogiri (1.13.6-x64-mingw32)
      racc (~> 1.4)
    nokogiri (1.13.6-x86-mingw32)
      racc (~> 1.4)
    open4 (1.3.4)
    pg (1.2.3)
    pg (1.2.3-x64-mingw32)
    pg (1.2.3-x86-mingw32)
    promise.rb (0.7.4)
    public_suffix (4.0.7)
    puma (4.3.7)
      nio4r (~> 2.0)
    puma (4.3.7-java)
      nio4r (~> 2.0)
    qiniu (6.9.0)
      mime-types (~> 3.1)
      rest-client (~> 2.0)
    raabro (1.4.0)
    racc (1.6.0)
    racc (1.6.0-java)
    rack (2.2.4)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (6.1.6)
      actioncable (= 6.1.6)
      actionmailbox (= 6.1.6)
      actionmailer (= 6.1.6)
      actionpack (= 6.1.6)
      actiontext (= 6.1.6)
      actionview (= 6.1.6)
      activejob (= 6.1.6)
      activemodel (= 6.1.6)
      activerecord (= 6.1.6)
      activestorage (= 6.1.6)
      activesupport (= 6.1.6)
      bundler (>= 1.15.0)
      railties (= 6.1.6)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    railties (6.1.6)
      actionpack (= 6.1.6)
      activesupport (= 6.1.6)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
    rake (13.0.6)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    redis (4.7.1)
    rest-client (2.1.0)
      http-accept (>= 1.7.0, < 2.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rest-client (2.1.0-x64-mingw32)
      ffi (~> 1.9)
      http-accept (>= 1.7.0, < 2.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rest-client (2.1.0-x86-mingw32)
      ffi (~> 1.9)
      http-accept (>= 1.7.0, < 2.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rest-client (2.1.0-x86-mswin32)
      ffi (~> 1.9)
      http-accept (>= 1.7.0, < 2.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    retries (0.0.5)
    rgeo (2.4.0)
    rgeo-activerecord (7.0.1)
      activerecord (>= 5.0)
      rgeo (>= 1.0.0)
    rolify (5.2.0)
    rollbar (2.25.0)
    roo (2.8.3)
      nokogiri (~> 1)
      rubyzip (>= 1.3.0, < 3.0.0)
    roo-xls (1.2.0)
      nokogiri
      roo (>= 2.0.0, < 3)
      spreadsheet (> 0.9.0)
    ruby-next-core (0.15.1)
    ruby-ole (1.2.12.2)
    rubyXL (3.4.14)
      nokogiri (>= 1.10.8)
      rubyzip (>= 1.3.0)
    ruby_dep (1.5.0)
    rubyzip (2.3.0)
    search_object (1.2.4)
    search_object_graphql (0.3.2)
      graphql (~> 1.8)
      search_object (~> 1.2.2)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    sidekiq (6.4.2)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
    sidekiq-cron (1.4.0)
      fugit (~> 1)
      sidekiq (>= 4.2.1)
    spreadsheet (1.2.6)
      ruby-ole (>= 1.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    thor (1.2.1)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2022.1)
      tzinfo (>= 1.0.0)
    unf (0.1.4)
      unf_ext
    unf (0.1.4-java)
    unf_ext (0.0.7.7)
    unf_ext (0.0.7.7-x64-mingw32)
    unf_ext (0.0.7.7-x86-mingw32)
    vessel (0.2.0)
      ferrum (>= 0.8)
      thor (~> 1.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-driver (0.7.5-java)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    whenever (1.0.0)
      chronic (>= 0.6.3)
    zeitwerk (2.6.0)

PLATFORMS
  java
  ruby
  x64-mingw32
  x86-mingw32
  x86-mswin32

DEPENDENCIES
  aasm (~> 5.0, >= 5.0.8)
  action_policy-graphql (~> 0.4)
  active_model_serializers (~> 0.10.2)
  activerecord-import
  activerecord-postgis-adapter
  activestorage_qiniu!
  acts-as-taggable-on
  after_commit_everywhere (~> 0.1.5)
  annotate
  anyway_config (~> 2.0.0)
  apollo_upload_server (~> 2.0)
  audited (~> 5.0)
  awesome_print
  bcrypt (~> 3.1.7)
  bootsnap (>= 1.4.2)
  byebug
  counter_culture (~> 2.0)
  dingtalk!
  dotenv-rails
  faker
  feishu!
  graphiql-rails!
  graphql (~> 1.10, >= 1.10.6)
  graphql-batch
  groupdate (~> 5.0)
  hiredis (~> 0.6.0)
  json_web_token (~> 0.3.5)
  kaminari (~> 1.2)
  listen (>= 3.0.5, < 3.2)
  mina (~> 1.2)
  mina-ng-puma
  mina-sidekiq (~> 1.1)
  mina-whenever
  mini_sql
  next_rails
  pg (>= 0.18, < 2.0)
  puma (~> 4.1)
  rack-cors
  rails (~> 6.1.6)
  redis (>= 4.6.0)
  rolify (~> 5.2)
  rollbar
  roo-xls
  rubyXL (~> 3.4, >= 3.4.14)
  search_object_graphql (~> 0.3.2)
  selenium-webdriver (~> 3.142)
  sidekiq (~> 6.4)
  sidekiq-cron (~> 1.4)
  sprockets (~> 3)
  tzinfo-data
  vessel
  wechat-rails!
  whenever

RUBY VERSION
   ruby 2.6.5p114

BUNDLED WITH
   2.2.17
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by xiaoduwuer** [comment]
uninstall date
install date
