### ISSUE TITLE
ruby issue

### ISSUE THREAD

**Issue by tanmay-veer** [rubygems/rubygems#6447]
### If not included with the output of your command, run `bundle env` and paste the output below

```
Gem::FilePermissionError: You don't have write permissions for the /var/lib/gems/3.0.0 directory.
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:715:in `verify_gem_home'
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:906:in `pre_install_checks'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:64:in `pre_install_checks'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:12:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:200:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:167:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:158:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - /var/lib/gems/3.0.0/bundler.lock
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `initialize'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `open'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `lock'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/installer.rb:71:in `run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/installer.rb:23:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/cli/install.rb:62:in `run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:261:in `block in install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/settings.rb:131:in `temporary'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:260:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /var/lib/gems/3.0.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.7
  Platforms   ruby, x86_64-linux
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-linux]
  Full Path   /usr/bin/ruby3.0
  Config Dir  /etc
RubyGems      3.3.5
  Gem Home    /var/lib/gems/3.0.0
  Gem Path    /home/c/.local/share/gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0:/usr/share/rubygems-integration/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0
  User Home   /home/c
  User Path   /home/c/.local/share/gem/ruby/3.0.0
  Bin Dir     /usr/local/bin
OpenSSL
  Compiled    OpenSSL 3.0.2 15 Mar 2022
  Loaded      OpenSSL 3.0.2 15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.2.0-59-g0704e65
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-02-15
Git SHA           5d717a27e0
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4", ">= 7.0.4.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
<No /home/c/sabitestapp/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
Hi!

You may want to install a ruby version manager to keep your Ruby and RubyGems installs local to your user like [Rbenv](https://github.com/rbenv/rbenv). If you want to stick to OS provided Ruby, you'll need to configure Bundler to use a location writable by your user with something like `bundle config path foo`.
