### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by SafetyMeeting** [rubygems/rubygems#6489]
### Describe the problem as clearly as you can

I really don't understand what is going on here. This is my first issue commit. I was having trouble updating this template earlier and had to start at square one with it all. perhaps if this is solved my other issue may go away

**Comment by SafetyMeeting** [comment]
Run docker run \
Unable to find image 'jekyll/builder:latest' locally
latest: Pulling from jekyll/builder
df9b9388f04a: Pulling fs layer
837e9cfc7e43: Pulling fs layer
c7850f1a8c23: Pulling fs layer
[6](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:7)ca4c39baa3d: Pulling fs layer
daa3a8cb[7](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:8)9d3: Pulling fs layer
227459[8](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:9)56603: Pulling fs layer
6ca4c3[9](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:10)baa3d: Waiting
daa3a8cb79d3: Waiting
227459856603: Waiting
c7850f1a8c23: Verifying Checksum
c7850f1a8c23: Download complete
837e9cfc7e43: Verifying Checksum
837e9cfc7e43: Download complete
df9b9388f04a: Verifying Checksum
df9b9388f04a: Download complete
df9b9388f04a: Pull complete
daa3a8cb79d3: Verifying Checksum
daa3a8cb79d3: Download complete
6ca4c39baa3d: Verifying Checksum
6ca4c39baa3d: Download complete
837e9cfc7e43: Pull complete
c7850f1a8c23: Pull complete
227459856603: Verifying Checksum
227459856603: Download complete
6ca4c39baa3d: Pull complete
daa3a8cb79d3: Pull complete
227459856603: Pull complete
Digest: sha256:439d7a3d94dd0547f47de5ff03fa9[10](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:11)ba93c45dd748bc2b0cde6446d1c322a80
Status: Downloaded newer image for jekyll/builder:latest
Bundler 2.3.25 is running, but your lockfile was generated with 2.3.7. Installing Bundler 2.3.7 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.3.7
Installing bundler 2.3.7
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Your lockfile was created by an old Bundler that left some things out.
Because of the missing DEPENDENCIES, we can only install gems one at a time, instead of installing 2 at a time.
You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
The missing gems are:
* sass-embedded depended upon by jekyll-sass-converter
Fetching public_suffix 5.0.1
Installing public_suffix 5.0.1
Using addressable 2.8.1
Fetching backports 3.23.0
Installing backports 3.23.0
Using bundler 2.3.7
Using colorator 1.1.0
Fetching concurrent-ruby 1.2.0
Installing concurrent-ruby 1.2.0
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Fetching faraday-net_http 3.0.2
Installing faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Fetching faraday 2.7.4
Installing faraday 2.7.4
Fetching faraday-retry 2.0.0
Installing faraday-retry 2.0.0
Using ffi 1.15.5
Using forwardable-extended 2.6.0
Using i18n 1.12.0
Fetching jekyll-sass-converter 3.0.0
Installing jekyll-sass-converter 3.0.0
Using rb-fsevent 0.[11](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:12).2
Using rb-inotify 0.10.1
Fetching listen 3.8.0
Installing listen 3.8.0
Using jekyll-watch 2.2.1
Using rexml 3.2.5
Using kramdown 2.4.0
Using kramdown-parser-gfm 1.1.0
Fetching liquid 4.0.4
Installing liquid 4.0.4
Using mercenary 0.4.0
Using pathutil 0.16.2
Fetching rouge 4.0.1
Installing rouge 4.0.1
Using safe_yaml 1.0.5
Fetching unicode-display_width 2.4.2
Installing unicode-display_width 2.4.2
Fetching terminal-table 3.0.2
Installing terminal-table 3.0.2
Fetching webrick 1.8.1
Installing webrick 1.8.1
Fetching jekyll 4.3.2
Installing jekyll 4.3.2
Fetching mustermann 3.0.0
Installing mustermann 3.0.0
Fetching rack 2.2.6.2
Installing rack 2.2.6.2
Fetching rack-protection 3.0.5
Installing rack-protection 3.0.5
Fetching tilt 2.0.11
Installing tilt 2.0.11
Fetching sinatra 3.0.5
Installing sinatra 3.0.5
Fetching multi_json 1.15.0
Installing multi_json 1.15.0
Fetching sinatra-contrib 3.0.5
Installing sinatra-contrib 3.0.5
Fetching jekyll-admin 0.11.1
Installing jekyll-admin 0.11.1
Using jekyll-feed 0.17.0
Fetching sawyer 0.9.2
Installing sawyer 0.9.2
Fetching octokit 4.25.1
Installing octokit 4.25.1
Fetching jekyll-gist 1.5.0
Installing jekyll-gist 1.5.0
Using jekyll-paginate 1.1.0
Using jekyll-seo-tag 2.8.0
Using jekyll-sitemap 1.4.0
Fetching trollop 2.9.9
Installing trollop 2.9.9
Fetching jgd 1.[12](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:13)
Installing jgd 1.12
Fetching nio4r 2.5.8
Installing nio4r 2.5.8 with native extensions
Fetching puma 6.1.1
Installing puma 6.1.1 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `full_name' for nil:NilClass

  warning << "* #{unmet_spec_dependency}, depended upon #{spec.full_name}, unsatisfied by #{@specs.find {|s| s.name == unmet_spec_dependency.name && !unmet_spec_dependency.matches_spec?(s.spec) }.full_name}"
                                                                                                                                                                                                   ^^^^^^^^^^
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:123:in `each'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:122:in `each'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:100:in `call'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer.rb:259:in `install_in_parallel'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer.rb:209:in `install'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer.rb:89:in `block in run'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/process_lock.rb:9:in `open'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/process_lock.rb:9:in `lock'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer.rb:71:in `run'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/installer.rb:23:in `install'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/cli/install.rb:62:in `run'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/cli.rb:255:in `block in install'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/settings.rb:[13](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:14)1:in `temporary'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/cli.rb:254:in `install'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
  /usr/gem/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
  /usr/gem/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/gem/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'
```

## Environment

```
Bundler       2.3.7
  Platforms   ruby, x86_64-linux-musl
Ruby          3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd5109b18) [x86_64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.25
  Gem Home    /usr/gem
  Gem Path    /home/jekyll/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/gem
  User Home   /home/jekyll
  User Path   /home/jekyll/.local/share/gem/ruby/3.1.0
  Bin Dir     /usr/gem/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1n  [15](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:16) Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   /etc/ssl1.1/cert.pem
  Cert Dir    /etc/ssl1.1/certs
Tools         
  Git         2.34.5
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-02-09
Git SHA           bafe43c593
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
build.nokogiri
  Set for your local app (/usr/local/bundle/config): "--use-system-libraries"
disable_platform_warnings
  Set via BUNDLE_DISABLE_PLATFORM_WARNINGS: "true"
disable_version_check
  Set for your local app (/usr/local/bundle/config): true
home
  Set via BUNDLE_HOME: "/usr/local/bundle"
ignore_messages
  Set for your local app (/usr/local/bundle/config): true
jobs
  Set for your local app (/usr/local/bundle/config): 2
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"

gem 'jekyll', '~> 4.3.2'
gem 'bundler', '~> 2.3.7'
gem 'faraday-retry'
gem 'backports', '~> 3.23'
gem 'kramdown'
gem 'puma'


# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# Plugins
group :jekyll_plugins do
    # gem 'devlopr', '~> 0.4.5'
    gem 'jgd', '~> 1.12'
    gem 'jekyll-feed', '~> 0.17.0'
    gem 'jekyll-paginate', '~> 1.1.0'
    gem 'jekyll-gist', '~> 1.5.0'
    gem 'jekyll-seo-tag', '~> 2.8.0'
    gem 'jekyll-sitemap', '~> 1.4.0'
    gem 'jekyll-admin', '~> 0.11.1'
end


# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?
gem "webrick", "~> 1.7"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    backports (3.23.0)
    colorator (1.1.0)
    concurrent-ruby (1.2.0)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    faraday (2.7.4)
      faraday-net_http (>= 2.0, < 3.1)
      ruby2_keywords (>= 0.0.4)
    faraday-net_http (3.0.2)
    faraday-retry (2.0.0)
      faraday (~> 2.0)
    ffi (1.15.5)
    forwardable-extended (2.6.0)
    google-protobuf (3.21.12-x86_64-darwin)
    google-protobuf (3.21.12-x86_64-linux)
    http_parser.rb (0.8.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jekyll (4.3.2)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-admin (0.11.1)
      jekyll (>= 3.7, < 5.0)
      sinatra (>= 1.4)
      sinatra-contrib (>= 1.4)
    jekyll-feed (0.17.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-gist (1.5.0)
      octokit (~> 4.2)
    jekyll-paginate (1.1.0)
    jekyll-sass-converter (3.0.0)
      sass-embedded (~> 1.54)
    jekyll-seo-tag (2.8.0)
      jekyll (>= 3.8, < 5.0)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    jgd (1.12)
      jekyll (>= 1.5.1)
      trollop (= 2.9.9)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.4)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    multi_json (1.15.0)
    mustermann (3.0.0)
      ruby2_keywords (~> 0.0.1)
    nio4r (2.5.8)
    octokit (4.25.1)
      faraday (>= 1, < 3)
      sawyer (~> 0.9)
    pathutil (0.[16](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:17).2)
      forwardable-extended (~> 2.6)
    public_suffix (5.0.1)
    puma (6.1.1)
      nio4r (~> 2.0)
    rack (2.2.6.2)
    rack-protection (3.0.5)
      rack
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (4.0.1)
    ruby2_keywords (0.0.5)
    safe_yaml (1.0.5)
    sass-embedded (1.58.0-arm64-darwin)
      google-protobuf (~> 3.21)
    sass-embedded (1.58.0-x86_64-darwin)
      google-protobuf (~> 3.21)
    sass-embedded (1.58.0-x86_64-linux-gnu)
      google-protobuf (~> 3.21)
    sawyer (0.9.2)
      addressable (>= 2.3.5)
      faraday (>= 0.[17](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:18).3, < 3)
    sinatra (3.0.5)
      mustermann (~> 3.0)
      rack (~> 2.2, >= 2.2.4)
      rack-protection (= 3.0.5)
      tilt (~> 2.0)
    sinatra-contrib (3.0.5)
      multi_json
      mustermann (~> 3.0)
      rack-protection (= 3.0.5)
      sinatra (= 3.0.5)
      tilt (~> 2.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    tilt (2.0.11)
    trollop (2.9.9)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.[20](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:21)22.7)
      tzinfo (>= 1.0.0)
    unicode-display_width (2.4.2)
    wdm (0.1.1)
    webrick (1.8.1)

PLATFORMS
  universal-darwin-[21](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:22)
  x86_64-linux

DEPENDENCIES
  backports (~> 3.[23](https://github.com/SafetyMeeting/devlopr-jekyll/actions/runs/4431789682/jobs/7775121827?pr=4#step:3:24))
  bundler (~> 2.3.7)
  faraday-retry
  jekyll (~> 4.3.2)
  jekyll-admin (~> 0.11.1)
  jekyll-feed (~> 0.17.0)
  jekyll-gist (~> 1.5.0)
  jekyll-paginate (~> 1.1.0)
  jekyll-seo-tag (~> 2.8.0)
  jekyll-sitemap (~> 1.4.0)
  jgd (~> 1.12)
  kramdown
  puma
  tzinfo (~> 2.0)
  tzinfo-data
  wdm (~> 0.1.1)
  webrick (~> 1.7)

BUNDLED WITH
   2.3.7
```

--- TEMPLATE END ----------------------------------------------------------------
