### ISSUE TITLE
Jekyll bundle issue

### ISSUE THREAD

**Issue by rebekahford** [rubygems/rubygems#6521]
### Describe the problem as clearly as you can

I have run  `bundle install `  on an existing freshly cloned Jekyll site but a new MacBook Pro. It was working fine tin another machine. I have build everything, checked etc. I am getting the following error.

`Unfortunately, an unexpected error occurred, and Bundler cannot continue.`

I've run `gem update --system` and then `bundle update --bundler` but the latter is incurring the same error message

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

Once I cloned the Jekyll site I ran `bundle install` and `bundle exec jekyll serve`
The latter caused the error

## Environment

```
Bundler       2.4.2
  Platforms   ruby, arm64-darwin-22
Ruby          2.6.10p210 (2022-04-12 revision 67958) [arm64-darwin-22]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.2.3
  Gem Home    /Library/Ruby/Gems/2.6.0
  Gem Path    /Users/XXX/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/XXX
  User Path   /Users/XXX/.gem/ruby/2.6.0
  Bin Dir     /usr/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.37.1 (Apple Git-137.1)
  RVM         1.29.12 (latest)
  rbenv       rbenv 1.2.0
  chruby      not installed
## Environment

```
Bundler       2.4.2
  Platforms   ruby, arm64-darwin-22
Ruby          2.6.10p210 (2022-04-12 revision 67958) [arm64-darwin-22]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.2.3
  Gem Home    /Library/Ruby/Gems/2.6.0
  Gem Path    /Users/XXX/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/XXX
  User Path   /Users/XXX/.gem/ruby/2.6.0
  Bin Dir     /usr/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.37.1 (Apple Git-137.1)
  RVM         1.29.12 (latest)
  rbenv       rbenv 1.2.0
  chruby      not installed

PLATFORMS
  ruby
  x86_64-darwin-20

DEPENDENCIES
  http_parser.rb (~> 0.6.0)
  jekyll (~> 4.3.1)
  jekyll-feed (~> 0.12)
  minima (~> 2.5)
  tzinfo (>= 1, < 3)
  tzinfo-data
  wdm (~> 0.1.1)

Ruby is part of my OS package

### Which command did you run?

bundle install

### What were you expecting to happen?

I was expecting it to update and install all of a fresh git cloned and functioning (on other machines)Jekyll site

### What actually happened?

I got this very long message

Ignoring bigdecimal-3.1.3 because its extensions are not built. Try: gem pristine bigdecimal --version 3.1.3
Ignoring date-3.3.3 because its extensions are not built. Try: gem pristine date --version 3.3.3
Ignoring dbm-1.1.0 because its extensions are not built. Try: gem pristine dbm --version 1.1.0
Ignoring etc-1.4.2 because its extensions are not built. Try: gem pristine etc --version 1.4.2
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring fcntl-1.0.2 because its extensions are not built. Try: gem pristine fcntl --version 1.0.2
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Ignoring fiddle-1.1.1 because its extensions are not built. Try: gem pristine fiddle --version 1.1.1
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring io-console-0.6.0 because its extensions are not built. Try: gem pristine io-console --version 0.6.0
Fetching gem metadata from https://rubygems.org/.--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
LoadError: dlopen(/Library/Ruby/Gems/2.6.0/gems/etc-1.4.2/lib/etc.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/etc-1.4.2/lib/etc.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Ruby/Gems/2.6.0/gems/etc-1.4.2/lib/etc.bundle' (no such file), '/Library/Ruby/Gems/2.6.0/gems/etc-1.4.2/lib/etc.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) - /Library/Ruby/Gems/2.6.0/gems/etc-1.4.2/lib/etc.bundle
  /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/settings.rb:212:in `processor_count'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher/compact_index.rb:107:in `bundle_worker'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher/compact_index.rb:91:in `block in parallel_compact_index_client'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/compact_index_client.rb:70:in `dependencies'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher/compact_index.rb:41:in `specs_for_names'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher/compact_index.rb:28:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher/compact_index.rb:15:in `call'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher.rb:133:in `block in specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher.rb:132:in `drop_while'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher.rb:132:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher.rb:119:in `block in specs_with_retry'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/retry.rb:40:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/retry.rb:30:in `attempt'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/fetcher.rb:118:in `specs_with_retry'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/source/rubygems.rb:420:in `block in fetch_names'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/source/rubygems.rb:417:in `each'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/source/rubygems.rb:417:in `fetch_names'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/source/rubygems.rb:412:in `block in remote_specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/index.rb:9:in `build'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/source/rubygems.rb:399:in `remote_specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/source/rubygems.rb:131:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/lazy_specification.rb:88:in `materialize_for_installation'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/spec_set.rb:195:in `map!'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/spec_set.rb:195:in `specs_for_dependency'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/spec_set.rb:33:in `block in for'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/spec_set.rb:22:in `loop'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/spec_set.rb:22:in `for'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/spec_set.rb:79:in `materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/definition.rb:506:in `materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/definition.rb:186:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/installer.rb:83:in `block in run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/process_lock.rb:15:in `lock'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/installer.rb:71:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/installer.rb:23:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli/install.rb:62:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:260:in `block in install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/settings.rb:131:in `temporary'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:259:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:34:in `dispatch'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:28:in `start'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
Errno::EACCES: Permission denied @ rb_sysopen - /Library/Ruby/Gems/2.6.0/bundler.lock
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/process_lock.rb:9:in `initialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/process_lock.rb:9:in `open'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/process_lock.rb:9:in `lock'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/installer.rb:71:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/installer.rb:23:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli/install.rb:62:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:260:in `block in install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/settings.rb:131:in `temporary'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:259:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:34:in `dispatch'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/cli.rb:28:in `start'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler       2.4.2
  Platforms   ruby, arm64-darwin-22
Ruby          2.6.10p210 (2022-04-12 revision 67958) [arm64-darwin-22]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.2.3
  Gem Home    /Library/Ruby/Gems/2.6.0
  Gem Path    /Users/XXX/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/XXX
  User Path   /Users/XXX/.gem/ruby/2.6.0
  Bin Dir     /usr/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.37.1 (Apple Git-137.1)
  RVM         1.29.12 (latest)
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-01-01
Git SHA           2cd3ed45bf
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.3.1"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.7)
    em-websocket (0.5.2)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.7)
    ffi (1.13.1)
    forwardable-extended (2.6.0)
    http_parser.rb (0.6.0)
    i18n (1.8.5)
      concurrent-ruby (~> 1.0)
    jekyll (4.3.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-feed (0.15.1)
      jekyll (>= 3.7, < 5.0)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-seo-tag (2.7.1)
      jekyll (>= 3.8, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.3.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    minima (2.5.1)
      jekyll (>= 3.5, < 5.0)
      jekyll-feed (~> 0.9)
      jekyll-seo-tag (~> 2.1)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.4)
    rouge (3.25.0)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    unicode-display_width (1.7.0)
    webrick (1.7.0)

PLATFORMS
  ruby
  x86_64-darwin-20

DEPENDENCIES
  http_parser.rb (~> 0.6.0)
  jekyll (~> 4.3.1)
  jekyll-feed (~> 0.12)
  minima (~> 2.5)
  tzinfo (>= 1, < 3)
  tzinfo-data
  wdm (~> 0.1.1)

BUNDLED WITH
   2.4.2
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fetc-1.4.2%2Flib%2Fetc.bundle%2C+0x0009%29++tried++%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fetc-1.4.2%2Flib%2Fetc.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64%27%29%29%2C+%27%2FSystem%2FVolumes%2FPreboot%2FCryptexes%2FOS%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fetc-1.4.2%2Flib%2Fetc.bundle%27+%28no+such+file%29%2C+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fetc-1.4.2%2Flib%2Fetc.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64%27%29%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fetc-1.4.2%2Flib%2Fetc.bundle&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.4.2
  Platforms   ruby, arm64-darwin-22
Ruby          2.6.10p210 (2022-04-12 revision 67958) [arm64-darwin-22]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.2.3
  Gem Home    /Library/Ruby/Gems/2.6.0
  Gem Path    /Users/XXX/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/XXX
  User Path   /Users/XXX/.gem/ruby/2.6.0
  Bin Dir     /usr/bin
Tools         
  Git         2.37.1 (Apple Git-137.1)
  RVM         1.29.12 (latest)
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-01-01
Git SHA           2cd3ed45bf
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.3.1"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.7)
    em-websocket (0.5.2)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.7)
    ffi (1.13.1)
    forwardable-extended (2.6.0)
    http_parser.rb (0.6.0)
    i18n (1.8.5)
      concurrent-ruby (~> 1.0)
    jekyll (4.3.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-feed (0.15.1)
      jekyll (>= 3.7, < 5.0)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-seo-tag (2.7.1)
      jekyll (>= 3.8, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.3.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    minima (2.5.1)
      jekyll (>= 3.5, < 5.0)
      jekyll-feed (~> 0.9)
      jekyll-seo-tag (~> 2.1)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.4)
    rouge (3.25.0)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    unicode-display_width (1.7.0)
    webrick (1.7.0)

PLATFORMS
  ruby
  x86_64-darwin-20

DEPENDENCIES
  http_parser.rb (~> 0.6.0)
  jekyll (~> 4.3.1)
  jekyll-feed (~> 0.12)
  minima (~> 2.5)
  tzinfo (>= 1, < 3)
  tzinfo-data
  wdm (~> 0.1.1)

BUNDLED WITH
   2.4.2
```

**Comment by rubyFeedback** [comment]
I lack the expertise to be able to help you, so hopefully someone else with a better understanding of both
rubygems and bundler, but ideally also Mac, can yield more useful information pertaining to the issue at hand.

The notice of "Ignoring bigdecimal-3.1.3 because its extensions are not built. Try: gem pristine bigdecimal --version 3.1.3" indicates that you may have had or have more than one ruby; I typically encounter this problem when I 
install/recompile another ruby version, but the gems in my HOME_DIR have not been recompiled (yet) either.

Do you have only one ruby version? If so then I assume that something, perhaps bundler, installed a separate
set of gems perhaps (but again, I don't know bundler well, I am just assuming something; clearly the notice 
must have been originating from some perceived issue by bundler/gem).

I assume you never ran into the same notice on the other machine where everything worked, so I assume there
must be some difference(s) pertaining to the ruby versions; or whatever bundler did on that machine but not
the other.

**Comment by deivid-rodriguez** [comment]
Hei @rebekahford!

This is probably due to using the Ruby installation that comes with default in MacOS. This Ruby is not well maintained and essentially deprecated.

Have a look at https://www.ruby-lang.org/en/documentation/installation/ for the different installation options and make sure you install the latest Ruby (3.2.1). If you still run into issues after upgrading and moving away from Ruby bundled with macOS, feel free to ask for help!
