### ISSUE TITLE
Bundler::SpecSet can break on iteration/array coercion after PR #6495

### ISSUE THREAD

**Issue by zackse** [rubygems/rubygems#6528]
### Describe the problem as clearly as you can

Starting in bundler 2.4.9, iteration over a `Bundler::SpecSet` can fail due to a missing method when some entries are `Bundler::IncompleteSpecification` objects. Conversion to an array (e.g., via `map` or `.to_a`) results in a runtime failure:

```
/usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:207:in `tsort_each_child': undefined method `dependencies' for #<Bundler::IncompleteSpecification:0x00007f90179ef788 @name="addressable", @partially_complete_specs=[]> (NoMethodError)

      s.dependencies.sort_by(&:name).each do |d|
       ^^^^^^^^^^^^^
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:415:in `call'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:195:in `block in tsort_each_node'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:195:in `each'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:195:in `tsort_each_node'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:347:in `call'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:226:in `tsort_each'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:176:in `each'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:176:in `to_a'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:176:in `tsort'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:152:in `tsort'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:170:in `sorted'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:74:in `to_a'
        from test.rb:60:in `<main>'
```

 See further below for the `test.rb` source.

I don't really know anything about bundler, but it looks like the problem was created with this [change](https://github.com/rubygems/rubygems/pull/6495/files#diff-3ada38090bec028614dcf46678cd1dbf7ef8918a69f00b2f0a1c18ebe0b48fc3) which can add `IncompleteSpecification` objects to `@specs`. In the past, the rough equivalent (`Bundler::LazySpecification`) objects had a `dependencies` accessor and were also not included in the "base" `@specs`, but instead were tracked in a separate instance variable `@incomplete_specs`.

Inside the array conversion routines, which call `sorted`, the `tsort_each_child` method expects each member (from `@specs`) to have a `dependencies` method/attr.

I don't know what the best solution is... for example, adding a no-op accessor to `IncompleteSpecification`.

One might wonder why anyone would construct a SpecSet in such a state -- the code in question is somewhat like `bundler-diff`: it is generating a list of gems that have changed from one version of a `Gemfile.lock` to the next. This list is (typically) a subset of the full list in `Gemfile.lock` which means a SpecSet with some incomplete entries.

### Did you try upgrading rubygems & bundler?

This is due to changes in 2.4.9. Downgrading to 2.4.8 avoids the problem.

### Post steps to reproduce the problem

```ruby
# test.rb
require 'bundler'

contents = <<EOT
GEM
  remote: https://rubygems.org/
  specs:
    async (2.5.0)
      console (~> 1.10)
      io-event (~> 1.1)
      timers (~> 4.1)
    console (1.16.2)
      fiber-local
    fiber-local (1.0.0)
    io-event (1.1.7)
    timers (4.3.5)

PLATFORMS
  ruby

DEPENDENCIES
  async

BUNDLED WITH
   2.4.9
EOT

lockfile = Bundler::LockfileParser.new(contents)

# By pruning the list of specs here, the SpecSet created below will 
# include some IncompleteSpecification objects, which will result
# in an error when the SpecSet is iterated over later
specs = lockfile.specs.select do |spec|
  spec.name == "async"
end

spec_set = Bundler::SpecSet.new(specs).materialize(specs)
puts spec_set.to_a
```

### Which command did you run?

In a Linux container based on `ruby:3.1-slim`, switching between bundler 2.4.8 and 2.4.9, we can observe the error:

```sh
$ ruby --version
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]

$ gem install -v 2.4.8 bundler
Successfully installed bundler-2.4.8
1 gem installed

$ bundle exec ruby test.rb
#<Bundler::StubSpecification name=async version=2.5.0 platform=ruby>
#<Bundler::StubSpecification name=html-proofer version=5.0.6 platform=ruby>


# now try with 2.4.9

$ gem install -v 2.4.9 bundler
Fetching bundler-2.4.9.gem
Successfully installed bundler-2.4.9
1 gem installed

$ bundle exec ruby test.rb
/usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:207:in `tsort_each_child': undefined method `dependencies' for #<Bundler::IncompleteSpecification:0x00007f753d70a0f8 @name="addressable", @partially_complete_specs=[]> (NoMethodError)

      s.dependencies.sort_by(&:name).each do |d|
       ^^^^^^^^^^^^^
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:415:in `call'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:195:in `block in tsort_each_node'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:195:in `each'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:195:in `tsort_each_node'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:347:in `call'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:226:in `tsort_each'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:176:in `each'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:176:in `to_a'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:176:in `tsort'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/tsort/lib/tsort.rb:152:in `tsort'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:170:in `sorted'
        from /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/spec_set.rb:74:in `to_a'
        from test.rb:129:in `<main>'
```

### What were you expecting to happen?

No errors.

### What actually happened?

Runtime error due to a missing method.

## Environment

```
Bundler       2.4.9
  Platforms   ruby, x86_64-linux
Ruby          3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.26
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.1.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-03-20
Git SHA           6f8e92bcc6
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
jobs
  Set for the current user (/root/.bundle/config): 15
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'async'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    async (2.5.0)
      console (~> 1.10)
      io-event (~> 1.1)
      timers (~> 4.1)
    console (1.16.2)
      fiber-local
    fiber-local (1.0.0)
    io-event (1.1.7)
    timers (4.3.5)

PLATFORMS
  ruby

DEPENDENCIES
  async

BUNDLED WITH
   2.4.9
```

**Comment by zackse** [comment]
Hi @deivid-rodriguez, thank you for the prompt response!

We are materializing so we can pass the specs to rubygems to download the gems and get full specs. Cc @wspurgin

We are looking at changing our code to materialize all specs to avoid incomplete entries, then applying filtering (limit to gems that have changed versions) afterwards. That would avoid the problematic code path.

I don't know if anyone else might run into this, Hyrum's Law in action, I suppose.

Also just to clarify, our code ends up in the array conversion path by way of `map`, which gets to the same place as calling `.to_a`.

```ruby
# map -> #each -> #sorted -> #tsort ...
Bundler::SpecSet.new(specs).materialize(specs).map do |spec| ...
```

**Comment by wspurgin** [comment]
Ha hey @deivid-rodriguez long time no see - brings me back to ActiveAdmin :heart: - the short of it is that we were trying to cut a corner and materalize only the specs we detected as being "different" between two lockfiles (and then get information about the differences that are in full specs like homepage and other metadata).

I think our error of ways (apart from using internals 😛) was assuming that any ol' collection of specs could be put into a `SpecSet` and materialized. i.e., we were doing something like (excuse the rails-y pseudo code - using it for brevity):
```ruby
previous_specs = old_lockfile.specs.index_by(&:name)

updated_specs = new_lockfile.specs.find_all do |spec|
  spec.version != previous_specs[spec.name]&.version
end

Bundler::SpecSet.new(updated_specs).materialize(updated_specs).map do |spec| 
  # find full spec locally or download the fullspec from the gem 
  # pull info from the full spec to show in a diff
end
```

My guess is that either we need to do provide _all_ the lockfile specs in the set, but only materialize the ones we care about:
```ruby
Bundler::SpecSet.new(new_lockfile.specs).materialize(updated_specs).map do ...
```

or as Evan indicated, just materialize allthethings, then find the ones that actually updated after
```ruby
current_spec_set = Bundler::SpecSet.new(new_lockfile.specs).materialize(new_lockfile.specs)
previous_spec_set = Bundler::SpecSet.new(old_lockfile.specs).materialize(old_lockfile.specs)

# compare current_spec_set and previous_spec_set..
```

What's your take @deivid-rodriguez ?

**Comment by deivid-rodriguez** [comment]
Hei!

Unfortunately I don't have a lot of cycles right now to look into this properly, but I'm also noticing issues myself with the extraction of `Bundler::IncompleteSpecification` while deduplicating specs, because `#full_name` is not defined on them either and it's needed when calling `uniq` on a `SpecSet`.

Since the commits that broke this were just refactoring commits, I'll happily revert them and release a new version until I can have a proper look at how to best do this.

So I created #6532.

**Comment by zackse** [comment]
Thanks @deivid-rodriguez! Appreciate the quick turnaround on this.
