### ISSUE TITLE
bundle install jekyll-sitemap incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by yangdanny97** [rubygems/rubygems#6538]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:503:in `expand_path'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:503:in `install_location'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:419:in `block (2 levels) in extract_tar_gz'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:65:in `each'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:415:in `block in extract_tar_gz'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:541:in `block in open_tar_gz'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:538:in `wrap'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:538:in `open_tar_gz'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:414:in `extract_tar_gz'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:392:in `block (2 levels) in extract_files'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:65:in `each'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:389:in `block in extract_files'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package/file_source.rb:29:in `open'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/package.rb:386:in `extract_files'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/installer.rb:852:in `extract_files'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/source/rubygems.rb:200:in `install'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/installer/gem_installer.rb:54:in `install'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/worker.rb:62:in `apply_func'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/worker.rb:57:in `block in process_queue'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/worker.rb:54:in `loop'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/worker.rb:54:in `process_queue'
  /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.9/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.9
  Platforms   ruby, arm64-darwin-22
Ruby          3.2.1p31 (2023-02-08 revision 31819e82c88c6f8ecfaeb162519bfa26a14b21fd) [arm64-darwin-22]
  Full Path   /opt/homebrew/opt/ruby/bin/ruby
  Config Dir  /opt/homebrew/Cellar/ruby/3.2.1/etc
RubyGems      3.4.6
  Gem Home    /Users/dannyyang/Documents/Documents - Danny’s MacBook Pro/GitHub/yangdanny97.github.io/vendor/bundle/ruby/3.2.0
  Gem Path    /Users/dannyyang/Documents/Documents - Danny’s MacBook Pro/GitHub/yangdanny97.github.io/vendor/bundle/ruby/3.2.0
  User Home   /Users/dannyyang
  User Path   /Users/dannyyang/.gem/ruby/3.2.0
  Bin Dir     /Users/dannyyang/Documents/Documents - Danny’s MacBook Pro/GitHub/yangdanny97.github.io/vendor/bundle/ruby/3.2.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1t  7 Feb 2023
  Loaded      OpenSSL 1.1.1t  7 Feb 2023
  Cert File   /opt/homebrew/etc/openssl@1.1/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@1.1/certs
Tools         
  Git         2.37.1 (Apple Git-137.1)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      Restored session: Thu Mar 23 22:37:59 PDT 2023

Gem.ruby      /opt/homebrew/opt/ruby/bin/ruby
bundle #!     /opt/homebrew/Cellar/ruby/3.2.1/bin/ruby

```

## Bundler Build Metadata

```
Built At          2023-03-20
Git SHA           6f8e92bcc6
Released Version  true
```

## Bundler settings

```
build.ffi
  Set for the current user (/Users/dannyyang/.bundle/config): "--with-cflags=-Wno-implicit-function-declaration"
path
  Set for your local app (/Users/dannyyang/Documents/Documents - Danny’s MacBook Pro/GitHub/yangdanny97.github.io/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", group: :jekyll_plugins

gem "jekyll"
```

### Gemfile.lock

```
<No /Users/dannyyang/Documents/Documents - Danny’s MacBook Pro/GitHub/yangdanny97.github.io/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
This seems related to the folder `Documents - Danny’s MacBook Pro` having the `’` character. You may be able to workaround this by renaming that folder.

**Comment by chdemko** [comment]
I had the same issue here (when using a folder containing a non ASCII character)
