### ISSUE TITLE
Template Report for Bundler Issue

### ISSUE THREAD

**Issue by Ridham151101** [rubygems/rubygems#6539]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
ArgumentError: Malformed version number string 2.3.
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/version.rb:223:in `initialize'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/version.rb:206:in `new'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/version.rb:206:in `new'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/self_manager.rb:165:in `lockfile_version'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/self_manager.rb:89:in `autoswitching_applies?'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/self_manager.rb:79:in `needs_switching?'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/self_manager.rb:10:in `restart_with_locked_bundler_if_needed'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:67:in `initialize'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:388:in `new'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:388:in `dispatch'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:34:in `dispatch'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:28:in `start'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
  /usr/share/rvm/rubies/ruby-3.0.0/bin/bundle:25:in `load'
  /usr/share/rvm/rubies/ruby-3.0.0/bin/bundle:25:in `<main>'
  /usr/share/rvm/gems/ruby-3.0.0@pms_online/bin/ruby_executable_hooks:22:in `eval'
  /usr/share/rvm/gems/ruby-3.0.0@pms_online/bin/ruby_executable_hooks:22:in `<main>'

```

## Environment

```
Bundler             2.4.7
  Platforms         ruby, x86_64-linux
Ruby                3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-linux]
  Full Path         /usr/share/rvm/rubies/ruby-3.0.0/bin/ruby
  Config Dir        /usr/share/rvm/rubies/ruby-3.0.0/etc
RubyGems            3.4.7
  Gem Home          /usr/share/rvm/gems/ruby-3.0.0@pms_online
  Gem Path          /usr/share/rvm/gems/ruby-3.0.0@pms_online:/usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0
  User Home         /home/ridham
  User Path         /home/ridham/.gem/ruby/3.0.0
  Bin Dir           /usr/share/rvm/gems/ruby-3.0.0@pms_online/bin
Tools               
  Git               2.25.1
  RVM               1.29.12 (manual)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2023-02-15
Git SHA           5d717a27e0
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

gem 'webpacker', '~> 5.4', '>= 5.4.3'

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'tzinfo-data'

gem 'devise'
gem 'nested_scaffold'
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.4)
      actionpack (= 7.0.4)
      activesupport (= 7.0.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.4)
      actionpack (= 7.0.4)
      activejob (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.4)
      actionpack (= 7.0.4)
      actionview (= 7.0.4)
      activejob (= 7.0.4)
      activesupport (= 7.0.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.4)
      actionview (= 7.0.4)
      activesupport (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.4)
      actionpack (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.4)
      activesupport (= 7.0.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.4)
      activesupport (= 7.0.4)
      globalid (>= 0.3.6)
    activemodel (7.0.4)
      activesupport (= 7.0.4)
    activerecord (7.0.4)
      activemodel (= 7.0.4)
      activesupport (= 7.0.4)
    activestorage (7.0.4)
      actionpack (= 7.0.4)
      activejob (= 7.0.4)
      activerecord (= 7.0.4)
      activesupport (= 7.0.4)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    bcrypt (3.1.18)
    bindex (0.8.1)
    bootsnap (1.13.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    capybara (3.37.1)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    debug (1.4.0)
      irb (>= 1.3.6)
      reline (>= 0.2.7)
    devise (4.8.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    erubi (1.11.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.1.5)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.5.11)
    irb (1.4.1)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.19.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.16.3)
    msgpack (1.6.0)
    nested_scaffold (1.1.0)
    net-imap (0.3.1)
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.1.3)
      timeout
    net-smtp (0.3.2)
      net-protocol
    nio4r (2.5.8)
    nokogiri (1.13.8-x64-mingw-ucrt)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    public_suffix (5.0.0)
    puma (5.6.5)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.4)
    rack-proxy (0.7.4)
      rack
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (7.0.4)
      actioncable (= 7.0.4)
      actionmailbox (= 7.0.4)
      actionmailer (= 7.0.4)
      actionpack (= 7.0.4)
      actiontext (= 7.0.4)
      actionview (= 7.0.4)
      activejob (= 7.0.4)
      activemodel (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      bundler (>= 1.15.0)
      railties (= 7.0.4)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    railties (7.0.4)
      actionpack (= 7.0.4)
      activesupport (= 7.0.4)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    regexp_parser (2.6.0)
    reline (0.3.0)
      io-console (~> 0.5)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rexml (3.2.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.5.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    semantic_range (3.0.0)
    sprockets (4.1.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.5.3-x64-mingw-ucrt)
    stimulus-rails (1.1.0)
      railties (>= 6.0.0)
    thor (1.2.1)
    timeout (0.3.0)
    turbo-rails (1.3.0)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2022.5)
      tzinfo (>= 1.0.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.2.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    webpacker (5.4.3)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.1)

PLATFORMS
  x64-mingw-ucrt

DEPENDENCIES
  bootsnap
  capybara
  debug
  devise
  importmap-rails
  jbuilder
  nested_scaffold
  puma (~> 5.0)
  rails (~> 7.0.4)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers
  webpacker (~> 5.4, >= 5.4.3)

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by Ridham151101** [comment]
bundle error

**Comment by deivid-rodriguez** [comment]
Thanks for the report.

The problem is that your lockfile include an invalid `BUNDLED WITH` section with the value "2.3.", which is malformed.

We should silently ignore this kind of situation and not bother with any auto switching, and let Bundler fix the lockfile the next time it writes it.

**Comment by Sannitya-13** [comment]
hello i hope i can solve this issue can u assign me.

**Comment by Sannitya-13** [comment]
The error message indicates that there is a problem with the version number string "2.3" in the BUNDLED WITH section of the lockfile. This string does not conform to the expected format of a valid version number, causing Bundler to crash when it tries to parse it.

To fix the issue,..... you should update the version number string in the BUNDLED WITH section of the lockfile to a valid version number. The correct format for a version number is major.minor.patch, where each component is a non-negative integer.

For example, you might update the BUNDLED WITH section to look like this:
BUNDLED WITH   2.2.25
After making this change, you should run bundle update to regenerate the lockfile and ensure that all dependencies are resolved correctly.

but im not sure

**Comment by Sannitya-13** [comment]
Hey hi....and can we connect on watsapp...bw...
My phone number:8639070419
And i guess ur ne is ridham??

**Comment by makketagg** [comment]
@deivid-rodriguez hey! Sorry, but i missed "Closes" in the PR body. Can you close this issue? Thanks.
