### ISSUE TITLE
More helpful error message for `Bundler::Runtime#check_for_activated_spec!` possible?

### ISSUE THREAD

**Issue by aeroastro** [rubygems/rubygems#6667]
### Describe the problem as clearly as you can

When default gem is activated (primary through `require`) prior to `bundler/setup`,
the following message is displayed on my console. I believe the message might be challenging for an average user to understand and address appropriately.

```
You have already activated uri 0.12.1, but your Gemfile requires uri 0.10.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
```

### Did you try upgrading rubygems & bundler?

Yes, I attempted upgrading both rubygems and bundler. I have identified three scenarios that can reproduce this error message. The message is consistent across different versions of rubygems and bundler, with two out of three scenarios being resolved by upgrading rubygems or bundler versions.

* The first scenario is resolved by upgrading rubygems to either `3.3.0` or `3.2.28`
  * https://github.com/rubygems/rubygems/pull/4897
* The second scenario is resolved by upgrading both bundler and rubygems to the latest versions.
  * I have not identified a specific improvement that solved this issue yet.
* The third scenario remains unresolved as it appears to be an issue on the user's end.

I'll detail these scenarios in the next section. However, as the main focus of this issue is to improve the error message, I won't delve too deeply into the reproduction steps. (Please request further information if necessary.)

### Post steps to reproduce the problem

* Ruby setup
  * Intel Mac
  * rbenv + ruby-build
* Gemfile

```ruby
source 'https://rubygems.org'

gem 'uri', '0.10.0'
gem 'rspec'
```

#### Scenario 1 (command)

Command

```bash
$ rbenv local 3.0.6
$ gem update --system 3.2.27 --no-document
$ bundle install --path=vendor/bundle
$ bundle exec rspec
```

Error Message

```
/Users/*/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated uri 0.10.2, but your Gemfile requires uri 0.10.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
```

Solution

```bash
$ gem update --system 3.2.28 --no-document
```

#### Scenario 2 (`ruby -r` option)

Command

```bash
$ rbenv local 3.1.4
$ bundler --version # Bundler version 2.3.26
$ bundle update --bundler
$ bundle install
$ bundle exec ruby -ruri -e 'puts "URI: #{URI::VERSION}"'
```

Error Message

```
/Users/*/.rbenv/versions/3.1.4/lib/ruby/3.1.0/bundler/runtime.rb:308:in `check_for_activated_spec!': You have already activated uri 0.12.1, but your Gemfile requires uri 0.10.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
```

Solution

```bash
$ gem update --system --no-document
$ bundle update --bundler
```

#### Scenario 3 (user-side issue)

Command

```bash
$ rbenv local 3.2.2
$ gem update --system --no-document
$ bundle update --bundler
$ ruby -e 'require "uri"; require "bundler/setup"; puts "URI: #{URI::VERSION}"'
```

Error Message

```
/Users/*/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated uri 0.12.1, but your Gemfile requires uri 0.10.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
```

Solution

```bash
$ ruby -e 'require "bundler/setup"; require "uri"; puts "URI: #{URI::VERSION}"' 
```

### What were you expecting to happen?

I believe the following error message would be more helpful to users:

```
You have already activated uri 0.12.1, but your Gemfile requires uri 0.10.0. Please try the following: 1: prepend `bundle exec` to your command, 2: ensure nothing is `require`d before `require "bundler/setup"`, and 3: `gem update --system && bundle update --bundler`. Alternatively, you can remove the "uri" dependency from your Gemfile. (Gem::LoadError)
```

The first two suggestions are based on bundler usage guidelines from https://bundler.io/guides/getting_started.html, such as `bundle exec rspec`, or `require "bundler/setup"`. These steps can address user-side issues (like in Scenario 3).

The third suggestion addresses issues concerning "rubygems" and "bundler". I included "rubygems" because one scenario was resolved by updating "rubygems".

I've moved the suggestion to remove the dependency to the end because:

* I've observed developers working to remove rubygems and bundler's dependency on default gems.
  * https://github.com/rubygems/rubygems/pull/4897
  * https://github.com/rubygems/rubygems/pull/5535
* In some cases, users may need to explicitly depend on a default gem.
  * https://github.com/ruby/net-imap/issues/16#issuecomment-803086765
  * Here, the `net-http` depends on `uri`, and the `uri` has trouble being loaded on rubygems under 3.2.28.

As I don't fully understand the desired current and future specifications of bundler, I'd appreciate any advice or feedback on the message I'm proposing.

### What actually happened?

```
You have already activated uri 0.12.1, but your Gemfile requires uri 0.12.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
```

## Environment

```
Bundler       2.4.10
  Platforms   ruby, x86_64-darwin-22
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-darwin-22]
  Full Path   /Users/*/.rbenv/versions/3.2.2/bin/ruby
  Config Dir  /Users/*/.rbenv/versions/3.2.2/etc
RubyGems      3.4.10
  Gem Home    /Users/*/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
  Gem Path    /Users/*/.gem/ruby/3.2.0:/Users/*/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
  User Home   /Users/*
  User Path   /Users/*/.gem/ruby/3.2.0
  Bin Dir     /Users/*/.rbenv/versions/3.2.2/bin
Tools         
  Git         2.38.1
  RVM         not installed
  rbenv       rbenv 1.2.0-59-g0704e65
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-05-09
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
build.mysql2
  Set for the current user (/Users/*/.bundle/config): "--with-ldflags=-L/usr/local/opt/openssl/lib"
gem.ci
  Set for the current user (/Users/*/.bundle/config): "github"
gem.coc
  Set for the current user (/Users/*/.bundle/config): true
gem.mit
  Set for the current user (/Users/*/.bundle/config): true
gem.rubocop
  Set for the current user (/Users/*/.bundle/config): "true"
gem.test
  Set for the current user (/Users/*/.bundle/config): "minitest"
path
  Set for your local app (/Users/*/git/temp/bundler-test-2/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'uri', '0.10.0'
gem 'rspec'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.5.0)
    rspec (3.12.0)
      rspec-core (~> 3.12.0)
      rspec-expectations (~> 3.12.0)
      rspec-mocks (~> 3.12.0)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.5)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-support (3.12.0)
    uri (0.10.0)

PLATFORMS
  x86_64-darwin-22

DEPENDENCIES
  rspec
  uri (= 0.10.0)

BUNDLED WITH
   2.4.10
```

**Comment by jeromedalbert** [comment]
@aeroastro I am able to repro your issue for scenario 1 but I have trouble running your repro steps in isolation for scenario 2 and 3. Focusing on scenario 3:

```Dockerfile
# Dockerfile
FROM ruby:3.2.2

RUN cat <<EOF > Gemfile
source 'https://rubygems.org'
gem 'uri', '0.10.0'
gem 'rspec'
EOF

RUN gem update --system --no-document
RUN bundle update --bundler
RUN ruby -e 'require "uri"; require "bundler/setup"; puts "URI: #{URI::VERSION}"'
```

Error I get when running `docker build .`:

```
 > [4/5] RUN bundle update --bundler:
0.179 This Bundle hasn't been installed yet. Run `bundle install` to update and
0.179 install the bundled gems.
```

Would you mind updating your repro steps for scenario 3 and to so that they work in isolation?

**Comment by deivid-rodriguez** [comment]
My understanding is that scenario 1 and scenario 2 were Bundler & RubyGems issues now fixed. Scenario 3 is a user error. To reproduce scenario 3 I think you need to change `bundle update --bundler` with `bundle install`.

We could try to differentiate user error vs Bundler/RubyGems bug/gotcha. An idea could be as early as possible in the Bundler process, save all specs activated _before_ Bundler is loaded and their versions. Then, if we find a mismatch when activating gems against those, we raise the current error as it is (possibly replacing the suggestion to upgrade Bundler with the improvements suggested here). If the mismatch is with a different gem, that means Bundler or RubyGems themselves activated it, so we could print the bug report template (or a different error if it's a known issue we don't really know how to solve).

**Comment by deivid-rodriguez** [comment]
This is essentially the same as https://github.com/rubygems/rubygems/issues/7178, I think?

**Comment by pboling** [comment]
I am getting this here:
https://github.com/oauth-xx/rots/actions/runs/11023033739/job/30613547035#step:4:8

I have no idea why it happens there.  I'm on Ruby 2.7.8, running bundler 2.4.22 in that workflow, but when I run the exact same thing locally, with the same commands, using the same `BUNDLE_GEMFILE`, it works fine.

**Comment by pboling** [comment]
The result is identical with and without a lockfile.
```
bundler: failed to load command: rake (/home/runner/work/rots/rots/vendor/bundle/ruby/2.7.0/bin/rake)
/opt/hostedtoolcache/Ruby/2.[7](https://github.com/oauth-xx/rots/actions/runs/11023286935/job/30614306104#step:4:8).8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated uri 0.10.0.2, but your Gemfile requires uri 0.13.1. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
```

@deivid-rodriguez Sicne the _Gemfile.lock_ is not relevant, and the behavior is exact same with and without,this is either unrelated to https://github.com/rubygems/rubygems/issues/7178, or perhaps that issue is misidentifying the lockfile as part of the problem? Or perhaps the problem is present from fresh lockfile generation, rather than a conflict with an existing lockfile (`install` vs `udpate`).

**Comment by deivid-rodriguez** [comment]
@pboling That indeed sounds like Rubygems activating the default version of `uri` internally, and then some indirect dependency trying to activate a different version of it. We fixed this by vendoring URI inside RubyGems, but the version of RubyGems in Ruby 2.7 probably does not have it. I recommend to drop support for Ruby 2.7 and move on.

**Comment by pboling** [comment]
Unfortunately I'm working through upgrading a huge number of Ruby libraries and a large number of apps, and many of them are struggling to even get to Ruby 2.7.  I'll likely be figuring out how to live with 2.7 for another couple years. :(

Companies that don't upgrade their apps for 13 years are heading for pain, and there's no way around that.  Every option is painful.

Thanks for the confirmation!  Maybe I can get everything off 2.7 before 3.5... it is nice to now have that as a goal.

**Comment by pboling** [comment]
@deivid-rodriguez I think this can be closed, since the original report, and my report are both relevant to rubygems 3.4, and bundler 2.4, which are now mostly dead, and no support is planned for this issue.  More motivation to upgrade all the things.

**Comment by deivid-rodriguez** [comment]
I think there are improvements that can be made, but I think we can track them in #7178, so I'll close in favor of that issue 👍.
