### ISSUE TITLE
Alpine Linux: NoMethodError: undefined method `metadata' for nil:NilClass

### ISSUE THREAD

**Issue by Quintasan** [rubygems/rubygems#6677]
## How to reproduce?

Put the provided `Gemfile` and `Gemfile.lock` in a directory, then

1. `cd <directory>`
2. `docker run -it --rm -v "$(pwd):/test" ruby:3.2.1-alpine /bin/sh`
3. `cd /test && apk add --no-cache build-base postgresql-dev`
4. `bundle config set --local deployment 'true'`
5. `bundle check || bundle install --jobs $(nproc)`

## Error

```
NoMethodError: undefined method `metadata' for nil:NilClass
  /usr/local/lib/ruby/3.2.0/bundler/cli/common.rb:23:in `block in output_fund_metadata_summary'
  /usr/local/lib/ruby/3.2.0/bundler/cli/common.rb:23:in `count'
  /usr/local/lib/ruby/3.2.0/bundler/cli/common.rb:23:in `output_fund_metadata_summary'
  /usr/local/lib/ruby/3.2.0/bundler/cli/install.rb:87:in `run'
  /usr/local/lib/ruby/3.2.0/bundler/cli.rb:260:in `block in install'
  /usr/local/lib/ruby/3.2.0/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/3.2.0/bundler/cli.rb:259:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
  /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
  /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'
```

## Environment

```
Bundler       2.4.6
  Platforms   ruby, x86_64-linux-musl
Ruby          3.2.1p31 (2023-02-08 revision 31819e82c88c6f8ecfaeb162519bfa26a14b21fd) [x86_64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.4.6
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.2.0:/usr/local/lib/ruby/gems/3.2.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.2.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 3.0.8 7 Feb 2023
  Loaded      OpenSSL 3.0.8 7 Feb 2023
  Cert File   /etc/ssl/cert.pem
  Cert Dir    /etc/ssl/certs
Tools         
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-05-14
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

gem "bootsnap", require: false
gem "dry-monads"
gem "dry-schema"
gem "dry-transaction"
gem "dry-types"
gem "dry-validation"
gem "mrsk", "~> 0.12.1"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rails", "~> 7.0.4"
gem "rswag-api"
gem "rswag-ui"
gem "tzinfo-data"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "factory_trace"
  gem "pg_query"
  gem "prosopite"
  gem "pry"
  gem "pry-byebug"
  gem "pry-rails"
  gem "relaxed-rubocop", require: false
  gem "rspec-rails"
  gem "rswag-specs"
  gem "rubocop", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-thread_safety", require: false
end

group :development do
  gem "lefthook"
  gem "solargraph"
  gem "solargraph-rails"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.4.3)
      actionpack (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.4.3)
      actionpack (= 7.0.4.3)
      activejob (= 7.0.4.3)
      activerecord (= 7.0.4.3)
      activestorage (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.4.3)
      actionpack (= 7.0.4.3)
      actionview (= 7.0.4.3)
      activejob (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.4.3)
      actionview (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.4.3)
      actionpack (= 7.0.4.3)
      activerecord (= 7.0.4.3)
      activestorage (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.4.3)
      activesupport (= 7.0.4.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.4.3)
      activesupport (= 7.0.4.3)
      globalid (>= 0.3.6)
    activemodel (7.0.4.3)
      activesupport (= 7.0.4.3)
    activerecord (7.0.4.3)
      activemodel (= 7.0.4.3)
      activesupport (= 7.0.4.3)
    activestorage (7.0.4.3)
      actionpack (= 7.0.4.3)
      activejob (= 7.0.4.3)
      activerecord (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.4.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.4)
      public_suffix (>= 2.0.2, < 6.0)
    ast (2.4.2)
    backport (1.2.0)
    bcrypt_pbkdf (1.1.0)
    benchmark (0.2.1)
    bootsnap (1.16.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    byebug (11.1.3)
    coderay (1.1.3)
    concurrent-ruby (1.2.2)
    crass (1.0.6)
    date (3.3.3)
    debug (1.8.0)
      irb (>= 1.5.0)
      reline (>= 0.3.1)
    diff-lcs (1.5.0)
    dotenv (2.8.1)
    dry-configurable (1.0.1)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-core (1.0.0)
      concurrent-ruby (~> 1.0)
      zeitwerk (~> 2.6)
    dry-events (1.0.1)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
    dry-inflector (1.0.0)
    dry-initializer (3.1.1)
    dry-logic (1.5.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-matcher (0.10.0)
      dry-core (~> 1.0)
    dry-monads (1.6.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-schema (1.13.1)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 1.0, >= 1.0.1)
      dry-core (~> 1.0, < 2)
      dry-initializer (~> 3.0)
      dry-logic (>= 1.4, < 2)
      dry-types (>= 1.7, < 2)
      zeitwerk (~> 2.6)
    dry-transaction (0.15.0)
      dry-core (~> 1.0)
      dry-events (~> 1.0)
      dry-matcher (~> 0.10)
      dry-monads (~> 1.6)
    dry-types (1.7.1)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0)
      dry-inflector (~> 1.0)
      dry-logic (~> 1.4)
      zeitwerk (~> 2.6)
    dry-validation (1.10.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
      dry-initializer (~> 3.0)
      dry-schema (>= 1.12, < 2)
      zeitwerk (~> 2.6)
    e2mmap (0.1.0)
    ed25519 (1.3.0)
    erubi (1.12.0)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    factory_trace (1.0.1)
      factory_bot (>= 4.0)
    globalid (1.1.0)
      activesupport (>= 5.0)
    google-protobuf (3.23.0-x86_64-linux)
    i18n (1.13.0)
      concurrent-ruby (~> 1.0)
    io-console (0.6.0)
    irb (1.6.4)
      reline (>= 0.3.0)
    jaro_winkler (1.5.4)
    json (2.6.3)
    json-schema (3.0.0)
      addressable (>= 2.8)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    lefthook (1.3.13)
    loofah (2.21.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.18.0)
    mrsk (0.12.1)
      activesupport (>= 7.0)
      bcrypt_pbkdf (~> 1.0)
      dotenv (~> 2.8)
      ed25519 (~> 1.2)
      net-ssh (~> 7.0)
      sshkit (~> 1.21)
      thor (~> 1.2)
      zeitwerk (~> 2.5)
    msgpack (1.7.0)
    net-imap (0.3.4)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-scp (4.0.0)
      net-ssh (>= 2.6.5, < 8.0.0)
    net-smtp (0.3.3)
      net-protocol
    net-ssh (7.1.0)
    nio4r (2.5.9)
    nokogiri (1.14.4-x86_64-linux)
      racc (~> 1.4)
    parallel (1.23.0)
    parser (3.2.2.1)
      ast (~> 2.4.1)
    pg (1.5.3)
    pg_query (4.2.0)
      google-protobuf (>= 3.19.2)
    prosopite (1.3.1)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.10.1)
      byebug (~> 11.0)
      pry (>= 0.13, < 0.15)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    public_suffix (5.0.1)
    puma (5.6.5)
      nio4r (~> 2.0)
    racc (1.6.2)
    rack (2.2.7)
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (7.0.4.3)
      actioncable (= 7.0.4.3)
      actionmailbox (= 7.0.4.3)
      actionmailer (= 7.0.4.3)
      actionpack (= 7.0.4.3)
      actiontext (= 7.0.4.3)
      actionview (= 7.0.4.3)
      activejob (= 7.0.4.3)
      activemodel (= 7.0.4.3)
      activerecord (= 7.0.4.3)
      activestorage (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      bundler (>= 1.15.0)
      railties (= 7.0.4.3)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.5.0)
      loofah (~> 2.19, >= 2.19.1)
    railties (7.0.4.3)
      actionpack (= 7.0.4.3)
      activesupport (= 7.0.4.3)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rainbow (3.1.1)
    rake (13.0.6)
    rbs (2.8.4)
    regexp_parser (2.8.0)
    relaxed-rubocop (2.5)
    reline (0.3.3)
      io-console (~> 0.5)
    reverse_markdown (2.1.1)
      nokogiri
    rexml (3.2.5)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.5)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-rails (6.0.2)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (~> 3.12)
      rspec-expectations (~> 3.12)
      rspec-mocks (~> 3.12)
      rspec-support (~> 3.12)
    rspec-support (3.12.0)
    rswag-api (2.9.0)
      railties (>= 3.1, < 7.1)
    rswag-specs (2.9.0)
      activesupport (>= 3.1, < 7.1)
      json-schema (>= 2.2, < 4.0)
      railties (>= 3.1, < 7.1)
      rspec-core (>= 2.14)
    rswag-ui (2.9.0)
      actionpack (>= 3.1, < 7.1)
      railties (>= 3.1, < 7.1)
    rubocop (1.51.0)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.2.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.28.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.28.1)
      parser (>= 3.2.1.0)
    rubocop-minitest (0.31.0)
      rubocop (>= 1.39, < 2.0)
    rubocop-performance (1.17.1)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rails (2.19.1)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
    rubocop-thread_safety (0.5.1)
      rubocop (>= 0.90.0)
    ruby-progressbar (1.13.0)
    solargraph (0.49.0)
      backport (~> 1.2)
      benchmark
      bundler (~> 2.0)
      diff-lcs (~> 1.4)
      e2mmap
      jaro_winkler (~> 1.5)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.1)
      parser (~> 3.0)
      rbs (~> 2.0)
      reverse_markdown (~> 2.0)
      rubocop (~> 1.38)
      thor (~> 1.0)
      tilt (~> 2.0)
      yard (~> 0.9, >= 0.9.24)
    solargraph-rails (1.1.0)
      activesupport
      solargraph
    sshkit (1.21.4)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (1.2.2)
    tilt (2.1.0)
    timeout (0.3.2)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.4.2)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    yard (0.9.34)
    zeitwerk (2.6.8)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  bootsnap
  debug
  dry-monads
  dry-schema
  dry-transaction
  dry-types
  dry-validation
  factory_bot_rails
  factory_trace
  lefthook
  mrsk (~> 0.12.1)
  pg (~> 1.1)
  pg_query
  prosopite
  pry
  pry-byebug
  pry-rails
  puma (~> 5.0)
  rails (~> 7.0.4)
  relaxed-rubocop
  rspec-rails
  rswag-api
  rswag-specs
  rswag-ui
  rubocop
  rubocop-minitest
  rubocop-performance
  rubocop-rails
  rubocop-thread_safety
  solargraph
  solargraph-rails
  tzinfo-data

RUBY VERSION
   ruby 3.2.1p31

BUNDLED WITH
   7.4.6
```

**Comment by deivid-rodriguez** [comment]
Hei!

It seems that you edited your `Gemfile.lock` file directly, since the `tzinfo-data` gem is missing from it, even if it's included in the `Gemfile`. In addition to this, since Bundler is being run in frozen mode, it can't fix the problem automatically, since it involves updating the lockfile, which is forbidden.

I'll try to create a PR so that we give a proper error in this case instead of unhelpfully crashing like here, but in the mean time, you can run `bundle config unset deployment && bundle lock && bundle config set deployment true`, and try again and I think it should work.

**Comment by deivid-rodriguez** [comment]
Actually, the lockfile has also been edited directly in the `BUNDLE WITH` section, which includes `7.4.6`. Since that version of Bundler does not exist, it continues with Bundler 2.4.6 which crashes in this way.

If you replace the `BUNDLED WITH` section with `2.4.13` (latest Bundler version), then the lockfile is automatically fixed and things just work if `deployment` is not set, and you get the following error if `deployment` is set:

```
$ bundle 
Fetching gem metadata from https://rubygems.org/........
Could not find gem 'tzinfo-data' in rubygems repository https://rubygems.org/ or installed locally.
```

This is better than crashing but not ideal since it does not inmediately point to the problem, let me look into improving this.

**Comment by deivid-rodriguez** [comment]
#6733 should fix this, now you should instead get

```
$ bundle
Lockfile is missing resolution for gem "tzinfo-data" and Bundler can't fix it because it's running in frozen mode.
Run `bundle install` elsewhere and add the updated Gemfile.lock to version control.
If this is a development machine, remove the Gemfile freeze by running `bundle config set frozen false`.
```

which I expect to be more helpful.

**Comment by Quintasan** [comment]
@deivid-rodriguez thanks for your hard work on this despite being 100% my fault for messing with the lockfile directly
