### ISSUE TITLE
Bundler inline doesn't work when you have multiple gem sources on Bundler 2.4.4 through 2.4.13

### ISSUE THREAD

**Issue by myronmarston** [rubygems/rubygems#6696]
### Describe the problem as clearly as you can

I'm seeing the bug described in #6282 still happening for me on Bundler 2.4.4 through 2.4.13, but in a slightly different situation:

```ruby
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"

  source "https://gems.mycompany.com/private/" do
    gem "some-internal-gem", ">= 0.1.18.0"
  end
end

puts 'Hello, World'
```

Here I've got a private gem published to my employer's gem server named `some-internal-gem`.  It has dependencies on some other private gems from that gem server and also on some public gems available on rubygems.org, so I have to list both sources.

When I run this, I get:

```
/Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:232:in `resolve_conflict': Could not find compatible versions (Bundler::PubGrub::SolveFailure)

Because every version of some-internal-gem depends on some-other-internal-gem ~> 12.3
  and some-other-internal-gem ~> 12.3 could not be found in any of the sources,
  some-internal-gem cannot be used.
So, because Gemfile depends on some-internal-gem >= 0.1.18.0,
  version solving has failed.
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:73:in `block in propagate'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `reverse_each'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `propagate'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:42:in `work'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:58:in `solve'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/resolver.rb:73:in `solve_versions'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/resolver.rb:32:in `start'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:554:in `start_resolution'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:289:in `resolve'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:507:in `materialize'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:197:in `specs'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:83:in `block in run'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/process_lock.rb:12:in `block in lock'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/process_lock.rb:9:in `open'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/process_lock.rb:9:in `lock'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:71:in `run'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:23:in `install'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:58:in `block (3 levels) in gemfile'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/settings.rb:131:in `temporary'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:57:in `block (2 levels) in gemfile'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/settings.rb:131:in `temporary'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:51:in `block in gemfile'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler.rb:410:in `block in with_unbundled_env'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler.rb:656:in `with_env'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler.rb:410:in `with_unbundled_env'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:42:in `gemfile'
        from script.rb:3:in `<main>'
```

Note that I've confirmed that 2.4.5 fixes the issue for the specific case reported in #6282 but it's still occurring for this case of multiple sources in an inline `gemfile` block.

### Did you try upgrading rubygems & bundler?

Yes.  The problem does not exist on bundler 2.4.3 (and before) but exists on Bundler 2.4.4 through 2.4.13 (I've tried on each of those versions).

### Post steps to reproduce the problem

```ruby
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"

  source "https://gems.mycompany.com/private/" do
    gem "some-internal-gem", ">= 0.1.18.0"
  end
end

puts 'Hello, World'
```

Because this involves both a private and public gem source I can't provide a script that will work for you to reproduce it, but hopefully the example above gives you an idea of how to reproduce it.

Run that script with any version between bundler 2.4.4 and 2.4.13 and you'll see the failure. Run it on bundler 2.4.3 and it works.

### Which command did you run?

I just ran the script containing the inline `gemfile`.

### What were you expecting to happen?

I was expecting it to install and use the referenced gems.

### What actually happened?

```
/Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:232:in `resolve_conflict': Could not find compatible versions (Bundler::PubGrub::SolveFailure)

Because every version of some-internal-gem depends on some-other-internal-gem ~> 12.3
  and some-other-internal-gem ~> 12.3 could not be found in any of the sources,
  some-internal-gem cannot be used.
So, because Gemfile depends on some-internal-gem >= 0.1.18.0,
  version solving has failed.
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:73:in `block in propagate'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `reverse_each'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `propagate'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:42:in `work'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:58:in `solve'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/resolver.rb:73:in `solve_versions'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/resolver.rb:32:in `start'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:554:in `start_resolution'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:289:in `resolve'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:507:in `materialize'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/definition.rb:197:in `specs'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:83:in `block in run'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/process_lock.rb:12:in `block in lock'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/process_lock.rb:9:in `open'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/process_lock.rb:9:in `lock'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:71:in `run'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/installer.rb:23:in `install'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:58:in `block (3 levels) in gemfile'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/settings.rb:131:in `temporary'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:57:in `block (2 levels) in gemfile'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/settings.rb:131:in `temporary'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:51:in `block in gemfile'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler.rb:410:in `block in with_unbundled_env'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler.rb:656:in `with_env'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler.rb:410:in `with_unbundled_env'
        from /Users/myron/.rvm/gems/ruby-3.1.2/gems/bundler-2.4.13/lib/bundler/inline.rb:42:in `gemfile'
        from script.rb:3:in `<main>'
```

### If not included with the output of your command, run `bundle env` and paste the output below

N/A

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this regression @myronmarston, #6699 should fix this!
