### ISSUE TITLE
bundle install failing with incompatible library version error on Rails 6

### ISSUE THREAD

**Issue by steady-daddy** [rubygems/rubygems#6789]
```
LoadError: incompatible library version - /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/date-3.3.3/lib/date_core.so
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/date-3.3.3/lib/date.rb:4:in `<top (required)>'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/time.rb:3:in `<top (required)>'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/request.rb:3:in `<top (required)>'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/fetcher.rb:7:in `<top (required)>'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/cli/install.rb:50:in `run'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/cli.rb:261:in `block in install'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/settings.rb:131:in `temporary'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/cli.rb:260:in `install'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/cli.rb:34:in `dispatch'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/cli.rb:28:in `start'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/exe/bundle:45:in `block in <top (required)>'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /home/ubuntu/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.13/exe/bundle:33:in `<top (required)>'
  /usr/bin/bundle:23:in `load'
  /usr/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler             2.4.13
  Platforms         ruby, x86_64-linux
Ruby                2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-linux]
  Full Path         /usr/bin/ruby2.7
  Config Dir        /etc
RubyGems            3.1.2
  Gem Home          /home/ubuntu/.rvm/gems/ruby-2.7.2
  Gem Path          /home/ubuntu/.rvm/gems/ruby-2.7.2:/home/ubuntu/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0
  User Home         /home/ubuntu
  User Path         /home/ubuntu/.gem/ruby/2.7.0
  Bin Dir           /home/ubuntu/.rvm/gems/ruby-2.7.2/bin
OpenSSL
  Compiled          OpenSSL 1.1.1f  31 Mar 2020
  Loaded            OpenSSL 1.1.1f  31 Mar 2020
  Cert File         /usr/lib/ssl/cert.pem
  Cert Dir          /usr/lib/ssl/certs
Tools
  Git               2.25.1
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
Gem.ruby            /usr/bin/ruby2.7
bundle #!           /usr/bin/ruby

```

## Bundler Build Metadata

```
Built At          2023-05-10
Git SHA           26eb456c6c
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
ruby '2.7.2'
gem 'dotenv-rails', '~> 2.7', require: 'dotenv/rails-now'
# gem 'dotenv-rails', '~> 2.7'

gem 'rails', '~> 6.1'
gem 'actionpack-action_caching'
gem 'angular-rails-templates', '~> 1.1'
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', require: 'bcrypt'
gem 'bootsnap', '~> 1.9', '>= 1.9.1'
gem 'brakeman', '~> 5.1', '>= 5.1.1'
gem 'capistrano3-puma', github: "seuros/capistrano-puma"
gem 'capistrano-bundler', '~> 2.0', '>= 2.0.1'
gem 'capistrano-rails', '~> 1.6.0'
gem 'capistrano-rvm', '~> 0.1.0'
gem 'certified', '1.0'
gem 'city-state', '0.0.13'
gem 'coderay', '~> 1.1'
# gem 'compass'
# gem 'compass-rails'
# gem 'compass-rails', '~> 4.0'
gem 'devise', '~> 4.8'
gem 'friendly_id', '~> 5.4.0'
gem 'gemsurance', '~> 0.10.0'
gem 'geocoder', '>= 1.6.1'
gem 'jquery-rails', '~> 4.4'
# gem 'meta_request'
gem 'mime-types', '~> 3.3'
gem 'nested_form', '0.3.2'
gem 'net-ssh', '4.1.0'
gem 'nokogiri', '~> 1.11'
gem 'omniauth', '~> 2.0'
gem 'omniauth-facebook', '~> 8.0'
gem 'omniauth-github', '~> 2.0'
gem 'omniauth-linkedin', '0.2.0'
gem 'omniauth-twitter', '1.4.0'
gem 'paperclip', '~> 6.0'
gem 'pg', '1.4.4'
gem 'puma', '6.0.0'
gem 'recaptcha', '4.12.0'
gem 'redis', '~> 4.4.0'
gem 'redis-namespace', '~> 1.8.1'
gem 'sassc-rails', '~> 2.1', '>= 2.1.2'
gem 'sdoc', '0.4.0', group: :doc
gem 'sidekiq', '~> 6.2.1'
gem 'sprockets', '~> 3.0'
gem 'sprockets-rails', '~> 3.0'
gem 'tinymce-rails', '4.4.0'
gem 'uglifier', '~> 4.2.0'
gem 'will_paginate', '3.1.7'
gem 'ed25519', '~> 1.3'
gem 'bcrypt_pbkdf', '~> 1.1', '< 2.0'
gem 'rbnacl', '~> 3.2', '< 5.0'
gem 'rbnacl-libsodium', '~> 1.0', '>= 1.0.16'

group :development, :test do
  gem 'factory_bot', '~> 6.2'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 2.19'
  # gem 'rspec', '~> 3.4'
  gem 'listen', '~> 3.5'
  gem 'pry', '~> 0.12.2'
  gem 'rspec-rails', '~> 4.1.0'
  gem 'rubocop', '~> 1.21', require: false
  gem 'rubocop-performance', '~> 1.11', '>= 1.11.5', require: false
  gem 'rubocop-rails', '~> 2.12', '>= 2.12.2', require: false
  gem 'rubocop-rake', '~> 0.6.0', require: false
  gem 'rubocop-rspec', '~> 2.5', require: false
  gem 'shoulda-matchers', '~> 5.0'
end

group :development do
  gem 'annotate', '~> 3.1', '>= 3.1.1'
  gem 'byebug', '9.0.6'
  gem 'web-console', '~> 4.1.0'
end
```

### Gemfile.lock

```
GIT
  remote: https://github.com/codahale/bcrypt-ruby.git
  revision: e402d692b1bfd2623e9cb414afb2bbe190e9e500
  specs:
    bcrypt (3.1.18)

GIT
  remote: https://github.com/seuros/capistrano-puma.git
  revision: 2cc11846540489edda10d83e026c9bea04e6fab1
  specs:
    capistrano3-puma (6.0.0.beta.1)
      capistrano (~> 3.7)
      capistrano-bundler
      puma (>= 5.1, < 7.0)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.7.3)
      actionpack (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.7.3)
      actionpack (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activestorage (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      mail (>= 2.7.1)
    actionmailer (6.1.7.3)
      actionpack (= 6.1.7.3)
      actionview (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.7.3)
      actionview (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actionpack-action_caching (1.2.2)
      actionpack (>= 4.0.0)
    actiontext (6.1.7.3)
      actionpack (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activestorage (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      nokogiri (>= 1.8.5)
    actionview (6.1.7.3)
      activesupport (= 6.1.7.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.7.3)
      activesupport (= 6.1.7.3)
      globalid (>= 0.3.6)
    activemodel (6.1.7.3)
      activesupport (= 6.1.7.3)
    activerecord (6.1.7.3)
      activemodel (= 6.1.7.3)
      activesupport (= 6.1.7.3)
    activestorage (6.1.7.3)
      actionpack (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.7.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.4)
      public_suffix (>= 2.0.2, < 6.0)
    airbrussh (1.4.1)
      sshkit (>= 1.6.1, != 1.7.0)
    angular-rails-templates (1.2.0)
      railties (>= 5.0, < 7.1)
      sprockets (>= 3.0, < 5)
      sprockets-rails
      tilt
    annotate (3.2.0)
      activerecord (>= 3.2, < 8.0)
      rake (>= 10.4, < 14.0)
    ast (2.4.2)
    bcrypt_pbkdf (1.1.0)
    bindex (0.8.1)
    bootsnap (1.16.0)
      msgpack (~> 1.2)
    brakeman (5.4.1)
    builder (3.2.4)
    byebug (9.0.6)
    capistrano (3.17.3)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.1.0)
      capistrano (~> 3.1)
    capistrano-rails (1.6.2)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    certified (1.0.0)
    city-state (0.0.13)
      rubyzip (~> 1.1)
    climate_control (0.2.0)
    coderay (1.1.3)
    concurrent-ruby (1.2.2)
    connection_pool (2.4.1)
    crass (1.0.6)
    date (3.3.3)
    devise (4.9.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.5.0)
    dotenv (2.8.1)
    dotenv-rails (2.8.1)
      dotenv (= 2.8.1)
      railties (>= 3.2)
    ed25519 (1.3.0)
    erubi (1.12.0)
    execjs (2.8.1)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    faker (2.23.0)
      i18n (>= 1.8.11, < 2)
    faraday (2.7.5)
      faraday-net_http (>= 2.0, < 3.1)
      ruby2_keywords (>= 0.0.4)
    faraday-net_http (3.0.2)
    ffi (1.15.5)
    friendly_id (5.4.2)
      activerecord (>= 4.0.0)
    gems (1.2.0)
    gemsurance (0.10.0)
      bundler (>= 1.2, < 3.0)
      gems (>= 0.8)
      git (~> 1.2)
    geocoder (1.8.1)
    git (1.18.0)
      addressable (~> 2.8)
      rchardet (~> 1.8)
    globalid (1.1.0)
      activesupport (>= 5.0)
    hashie (5.0.0)
    i18n (1.13.0)
      concurrent-ruby (~> 1.0)
    jquery-rails (4.5.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.6)
    jwt (2.7.0)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.21.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    method_source (0.9.2)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2023.0218.1)
    mimemagic (0.3.10)
      nokogiri (~> 1)
      rake
    mini_mime (1.1.2)
    mini_portile2 (2.8.2)
    minitest (5.18.0)
    msgpack (1.7.1)
    multi_xml (0.6.0)
    nested_form (0.3.2)
    net-imap (0.3.4)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-scp (4.0.0)
      net-ssh (>= 2.6.5, < 8.0.0)
    net-smtp (0.3.3)
      net-protocol
    net-ssh (4.1.0)
    nio4r (2.5.9)
    nokogiri (1.15.2)
      mini_portile2 (~> 2.8.2)
      racc (~> 1.4)
    nokogiri (1.15.2-x86_64-linux)
      racc (~> 1.4)
    oauth (1.1.0)
      oauth-tty (~> 1.0, >= 1.0.1)
      snaky_hash (~> 2.0)
      version_gem (~> 1.1)
    oauth-tty (1.0.5)
      version_gem (~> 1.1, >= 1.1.1)
    oauth2 (2.0.9)
      faraday (>= 0.17.3, < 3.0)
      jwt (>= 1.0, < 3.0)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 4)
      snaky_hash (~> 2.0)
      version_gem (~> 1.1)
    omniauth (2.1.1)
      hashie (>= 3.4.6)
      rack (>= 2.2.3)
      rack-protection
    omniauth-facebook (8.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-github (2.0.1)
      omniauth (~> 2.0)
      omniauth-oauth2 (~> 1.8)
    omniauth-linkedin (0.2.0)
      omniauth-oauth (~> 1.0)
    omniauth-oauth (1.2.0)
      oauth
      omniauth (>= 1.0, < 3)
    omniauth-oauth2 (1.8.0)
      oauth2 (>= 1.4, < 3)
      omniauth (~> 2.0)
    omniauth-twitter (1.4.0)
      omniauth-oauth (~> 1.1)
      rack
    orm_adapter (0.5.0)
    paperclip (6.1.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      mime-types
      mimemagic (~> 0.3.0)
      terrapin (~> 0.6.0)
    parallel (1.23.0)
    parser (3.2.2.1)
      ast (~> 2.4.1)
    pg (1.4.4)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    public_suffix (5.0.1)
    puma (6.0.0)
      nio4r (~> 2.0)
    racc (1.6.2)
    rack (2.2.7)
    rack-protection (3.0.6)
      rack
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (6.1.7.3)
      actioncable (= 6.1.7.3)
      actionmailbox (= 6.1.7.3)
      actionmailer (= 6.1.7.3)
      actionpack (= 6.1.7.3)
      actiontext (= 6.1.7.3)
      actionview (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activemodel (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activestorage (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      bundler (>= 1.15.0)
      railties (= 6.1.7.3)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.5.0)
      loofah (~> 2.19, >= 2.19.1)
    railties (6.1.7.3)
      actionpack (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
    rainbow (3.1.1)
    rake (13.0.6)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rbnacl (3.4.0)
      ffi
    rbnacl-libsodium (1.0.16)
      rbnacl (>= 3.0.1)
    rchardet (1.8.0)
    rdoc (4.3.0)
    recaptcha (4.12.0)
      json
    redis (4.4.0)
    redis-namespace (1.8.2)
      redis (>= 3.0.4)
    regexp_parser (2.8.0)
    responders (3.1.0)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.2.5)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.5)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-rails (4.1.2)
      actionpack (>= 4.2)
      activesupport (>= 4.2)
      railties (>= 4.2)
      rspec-core (~> 3.10)
      rspec-expectations (~> 3.10)
      rspec-mocks (~> 3.10)
      rspec-support (~> 3.10)
    rspec-support (3.12.0)
    rubocop (1.31.0)
      parallel (~> 1.10)
      parser (>= 3.1.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.18.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.28.1)
      parser (>= 3.2.1.0)
    rubocop-performance (1.18.0)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rails (2.15.2)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.7.0, < 2.0)
    rubocop-rake (0.6.0)
      rubocop (~> 1.0)
    rubocop-rspec (2.12.1)
      rubocop (~> 1.31)
    ruby-progressbar (1.13.0)
    ruby2_keywords (0.0.5)
    rubyzip (1.3.0)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    sdoc (0.4.0)
      json (~> 1.8)
      rdoc (~> 4.0, < 5.0)
    shoulda-matchers (5.3.0)
      activesupport (>= 5.2.0)
    sidekiq (6.2.2)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
    snaky_hash (2.0.1)
      hashie
      version_gem (~> 1.1, >= 1.1.1)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sshkit (1.21.4)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    terrapin (0.6.0)
      climate_control (>= 0.0.3, < 1.0)
    thor (1.2.2)
    tilt (2.1.0)
    timeout (0.3.2)
    tinymce-rails (4.4.0)
      railties (>= 3.1.1)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (2.4.2)
    version_gem (1.1.2)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.1.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    will_paginate (3.1.7)
    zeitwerk (2.6.8)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  actionpack-action_caching
  angular-rails-templates (~> 1.1)
  annotate (~> 3.1, >= 3.1.1)
  bcrypt!
  bcrypt_pbkdf (~> 1.1, < 2.0)
  bootsnap (~> 1.9, >= 1.9.1)
  brakeman (~> 5.1, >= 5.1.1)
  byebug (= 9.0.6)
  capistrano-bundler (~> 2.0, >= 2.0.1)
  capistrano-rails (~> 1.6.0)
  capistrano-rvm (~> 0.1.0)
  capistrano3-puma!
  certified (= 1.0)
  city-state (= 0.0.13)
  coderay (~> 1.1)
  devise (~> 4.8)
  dotenv-rails (~> 2.7)
  ed25519 (~> 1.3)
  factory_bot (~> 6.2)
  factory_bot_rails (~> 6.2)
  faker (~> 2.19)
  friendly_id (~> 5.4.0)
  gemsurance (~> 0.10.0)
  geocoder (>= 1.6.1)
  jquery-rails (~> 4.4)
  listen (~> 3.5)
  mime-types (~> 3.3)
  nested_form (= 0.3.2)
  net-ssh (= 4.1.0)
  nokogiri (~> 1.11)
  omniauth (~> 2.0)
  omniauth-facebook (~> 8.0)
  omniauth-github (~> 2.0)
  omniauth-linkedin (= 0.2.0)
  omniauth-twitter (= 1.4.0)
  paperclip (~> 6.0)
  pg (= 1.4.4)
  pry (~> 0.12.2)
  puma (= 6.0.0)
  rails (~> 6.1)
  rbnacl (~> 3.2, < 5.0)
  rbnacl-libsodium (~> 1.0, >= 1.0.16)
  recaptcha (= 4.12.0)
  redis (~> 4.4.0)
  redis-namespace (~> 1.8.1)
  rspec-rails (~> 4.1.0)
  rubocop (~> 1.21)
  rubocop-performance (~> 1.11, >= 1.11.5)
  rubocop-rails (~> 2.12, >= 2.12.2)
  rubocop-rake (~> 0.6.0)
  rubocop-rspec (~> 2.5)
  sassc-rails (~> 2.1, >= 2.1.2)
  sdoc (= 0.4.0)
  shoulda-matchers (~> 5.0)
  sidekiq (~> 6.2.1)
  sprockets (~> 3.0)
  sprockets-rails (~> 3.0)
  tinymce-rails (= 4.4.0)
  uglifier (~> 4.2.0)
  web-console (~> 4.1.0)
  will_paginate (= 3.1.7)

RUBY VERSION
   ruby 2.7.2p137

BUNDLED WITH
   2.4.13
```

**Comment by deivid-rodriguez** [comment]
Ugg, I got no idea how you ended up there but I'd say that `.so` file was generated with a different Ruby or something?

Does it work if you force a reinstall with `bundle install --force`?

**Comment by kurko** [comment]
I'm getting this problem as well (rbenv, not rvm). It began happening around some time after bundler was merged into `rubygems`.

My quick fix was `gem pristine -all`, but the error always returned (I have multiple Ruby projects on my machine with different versions). Ultimately I decided to `bundle install --path vendor/bundle` to completely isolate the gems per project and never had problems again.

In my case, I noticed that despite using `3.1.2` or `3.1.4`, the load path always has `3.1.0`, meaning bundler is using a single bucket for gems from all `3.1.x` versions. Of course they won't be compatible. It doesn't seem to be case looking at your path, though, but worth looking what you have in `BUNDLE_PATH`.

**Comment by deivid-rodriguez** [comment]
My understanding is that all Ruby 3.1.x versions should be ABI compatible, so I don't think that's an issue.

I'm going to close this since I believe it's unlikely to be a problem in RubyGems and/or Bundler.

But if you are able to provide some steps to reproduce this reliably, I'll be happy to look into it!

**Comment by deivid-rodriguez** [comment]
In any case, configuring Bundler to be completely isolated for each app as recommended by @kurko is a good thing 👍.
