### ISSUE TITLE
Errors starting server & downloading gems/bundler

### ISSUE THREAD

**Issue by laurenesco** [rubygems/rubygems#6948]
### Describe the problem as clearly as you can

I am following the documentation found here: https://guides.rubyonrails.org/getting_started.html

On step 4.1, when running the command `ruby bin/rails server`, I get the following error:

```
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': 126: The specified module could not be found.   - C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/msgpack-1.7.2/lib/msgpack/msgpack.so (LoadError)\
```

I have tried uninstalling Ruby completely, as initially I did not install the devkit. I now have a fresh installation with the devkit, and get the same error. It is also worth noting I am running this command from the blog directory as specified in the documentation.

I went into my file system and found the file it cannot find at the same path:

```
C:\Ruby32-x64\lib\ruby\gems\3.2.0\gems\msgpack-1.7.2\lib\msgpack\msgpack.so
```

So the file exists, and is at the right location.

I have tried manually uninstalling and installing msgpack with `gem install msgpack`, and `gem install msgpack`, but that didn't change anything. Ruby is in the PATH variable for my machine as well, as: `C:\Ruby32-x64\bin`. I am running on Windows 11 working in PowerShell, so I am following all the notes for Windows machines in the documentation. I have updated with `gem update`, and still same error.

`ruby --version` returns `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]`, but `gems --version` returns the same error that this post is about. If I try to uninstall rails with `gem uninstall rails` I get:

```
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require': 126: The specified module could not be found.   - C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/stringio-3.0.8/lib/stringio.so (LoadError)
```

I was directed to this StackOverflow question https://stackoverflow.com/questions/59479802/unable-to-create-a-rails-app-due-to-incompatible-library-version-load-error so I tried the command `bundle install --redownload`, which resulted in and error report which indicted I should open an issue here. The command 'bundle update --bundler` also results in this error.

Here is the problem template generated:

```
LoadError: 126: The specified module could not be found.   - C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/stringio-3.0.8/lib/stringio.so
  <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  C:/Ruby32-x64/lib/ruby/3.2.0/psych/nodes/node.rb:2:in `<top (required)>'
  C:/Ruby32-x64/lib/ruby/3.2.0/psych/nodes.rb:2:in `require_relative'
  C:/Ruby32-x64/lib/ruby/3.2.0/psych/nodes.rb:2:in `<top (required)>'
  C:/Ruby32-x64/lib/ruby/3.2.0/psych.rb:15:in `require_relative'
  C:/Ruby32-x64/lib/ruby/3.2.0/psych.rb:15:in `<top (required)>'
  <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems.rb:608:in `load_yaml'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/config_file.rb:346:in `load_file'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/config_file.rb:189:in `initialize'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems.rb:329:in `new'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems.rb:329:in `configuration'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/fetcher.rb:254:in `connection'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/fetcher.rb:100:in `initialize'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:258:in `new'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:258:in `block in fetchers'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:256:in `map'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:256:in `fetchers'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:400:in `block in remote_specs'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/index.rb:9:in `build'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:399:in `remote_specs'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:133:in `specs'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:205:in `map!'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:205:in `specs_for_dependency'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:34:in `block in for'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:22:in `loop'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:22:in `for'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:85:in `materialize'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/definition.rb:523:in `materialize'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/definition.rb:200:in `specs'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer.rb:83:in `block in run'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/process_lock.rb:12:in `block in lock'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/process_lock.rb:9:in `open'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/process_lock.rb:9:in `lock'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer.rb:71:in `run'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer.rb:23:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/cli/install.rb:62:in `run'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/cli.rb:261:in `block in install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/settings.rb:130:in `temporary'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/cli.rb:260:in `install'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/cli.rb:34:in `dispatch'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/cli.rb:28:in `start'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
  C:/Ruby32-x64/bin/bundle:25:in `load'
  C:/Ruby32-x64/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.19
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x64-mingw-ucrt]
  Full Path   C:/Ruby32-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.4.10
  Gem Home    C:/Ruby32-x64/lib/ruby/gems/3.2.0
  Gem Path    C:/Users/Anon/.local/share/gem/ruby/3.2.0;C:/Ruby32-x64/lib/ruby/gems/3.2.0
  User Home   C:/Users/Anon
  User Path   C:/Users/Anon/.local/share/gem/ruby/3.2.0
  Bin Dir     C:/Ruby32-x64/bin
OpenSSL
  Compiled    OpenSSL 3.1.0 14 Mar 2023
  Loaded      OpenSSL 3.1.0 14 Mar 2023
  Cert File   C:/Ruby32-x64/bin/etc/ssl/cert.pem
  Cert Dir    C:/Ruby32-x64/bin/etc/ssl/certs
Tools
  Git         2.35.1.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-08-17
Git SHA           86f98098e3
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.8"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"

end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.8)
      actionpack (= 7.0.8)
      activesupport (= 7.0.8)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.8)
      actionpack (= 7.0.8)
      activejob (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.8)
      actionpack (= 7.0.8)
      actionview (= 7.0.8)
      activejob (= 7.0.8)
      activesupport (= 7.0.8)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.8)
      actionview (= 7.0.8)
      activesupport (= 7.0.8)
      rack (~> 2.0, >= 2.2.4)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.8)
      actionpack (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.8)
      activesupport (= 7.0.8)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.8)
      activesupport (= 7.0.8)
      globalid (>= 0.3.6)
    activemodel (7.0.8)
      activesupport (= 7.0.8)
    activerecord (7.0.8)
      activemodel (= 7.0.8)
      activesupport (= 7.0.8)
    activestorage (7.0.8)
      actionpack (= 7.0.8)
      activejob (= 7.0.8)
      activerecord (= 7.0.8)
      activesupport (= 7.0.8)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.8)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    bindex (0.8.1)
    bootsnap (1.16.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    capybara (3.39.2)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.2.2)
    crass (1.0.6)
    date (3.3.3)
    debug (1.7.1)
      irb (>= 1.5.0)
      reline (>= 0.3.1)
    erubi (1.12.0)
    globalid (1.2.1)
      activesupport (>= 6.1)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.2.1)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.6.0)
    irb (1.6.2)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.21.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.5)
    minitest (5.20.0)
    msgpack (1.7.2)
    net-imap (0.3.7)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-smtp (0.3.3)
      net-protocol
    nio4r (2.5.9)
    nokogiri (1.15.4-x64-mingw-ucrt)
      racc (~> 1.4)
    public_suffix (5.0.3)
    puma (5.6.7)
      nio4r (~> 2.0)
    racc (1.7.1)
    rack (2.2.8)
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (7.0.8)
      actioncable (= 7.0.8)
      actionmailbox (= 7.0.8)
      actionmailer (= 7.0.8)
      actionpack (= 7.0.8)
      actiontext (= 7.0.8)
      actionview (= 7.0.8)
      activejob (= 7.0.8)
      activemodel (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      bundler (>= 1.15.0)
      railties (= 7.0.8)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.0.8)
      actionpack (= 7.0.8)
      activesupport (= 7.0.8)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    regexp_parser (2.8.1)
    reline (0.3.8)
      io-console (~> 0.5)
    rexml (3.2.6)
    rubyzip (2.3.2)
    selenium-webdriver (4.12.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.6.5-x64-mingw-ucrt)
    stimulus-rails (1.2.2)
      railties (>= 6.0.0)
    thor (1.2.2)
    timeout (0.4.0)
    turbo-rails (1.4.0)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2023.3)
      tzinfo (>= 1.0.0)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    websocket (1.2.9)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.11)

PLATFORMS
  x64-mingw-ucrt

DEPENDENCIES
  bootsnap
  capybara
  debug
  importmap-rails
  jbuilder
  puma (~> 5.0)
  rails (~> 7.0.8)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  turbo-rails
  tzinfo-data
  web-console

RUBY VERSION
   ruby 3.2.2p53

BUNDLED WITH
   2.4.19
```

**Comment by deivid-rodriguez** [comment]
We got several reports about this kind of mismatch on Windows recently. But in this case it sounds like the report may be reproducible with a bit of effort since this seems to happen on a pristine install of Ruby?

**Comment by deivid-rodriguez** [comment]
@laurenesco Can you reproduce this error consistently?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
