### ISSUE TITLE
Fail to uninstall gem on windows

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#6955]
- Additional gems installed with `--user-install`
- Running: `C:\Ruby30-x64\bin\ruby.exe C:\Ruby30-x64\bin\gem uninstall timeout -x -I -V --backtrace -v 0.4.0 --user-install`
- Got:
```
Exit code: 1
stderr: ERROR:  While executing gem ... (NameError)
stderr:     uninitialized constant Gem::RDoc
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/uninstaller.rb:265:in `remove'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/uninstaller.rb:166:in `uninstall_gem'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/uninstaller.rb:143:in `uninstall'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/commands/uninstall_command.rb:195:in `uninstall'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/commands/uninstall_command.rb:181:in `uninstall_gem'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/commands/uninstall_command.rb:175:in `block in uninstall_specific'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/commands/uninstall_command.rb:167:in `each'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/commands/uninstall_command.rb:167:in `uninstall_specific'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/commands/uninstall_command.rb:133:in `execute'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/command_manager.rb:180:in `process_args'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/command_manager.rb:149:in `run'
stderr: 	C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/gem_runner.rb:53:in `run'
stderr: 	C:/Ruby30-x64/bin/gem:21:in `<main>'
```

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.33
  - RUBY VERSION: 3.0.6 (2023-03-30 patchlevel 216) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby30-x64/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: C:/Users/hurri/.gem/ruby/3.0.0
  - RUBY EXECUTABLE: C:/Ruby30-x64/bin/ruby.exe
  - GIT EXECUTABLE: C:\Program Files\Git\cmd/git.EXE
  - EXECUTABLE DIRECTORY: C:/Ruby30-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/hurri/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x64-mingw32
  - GEM PATHS:
     - C:/Ruby30-x64/lib/ruby/gems/3.0.0
     - C:/Users/hurri/.gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Ruby30-x64\bin\
     - C:\Strawberry\c\bin
     - C:\Strawberry\perl\site\bin
     - C:\Strawberry\perl\bin
     - C:\msys64\usr\bin\
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Windows\System32\OpenSSH\
     - C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\Program Files\nodejs\
     - C:\ProgramData\chocolatey\bin
     - C:\Program Files\Git\cmd
     - C:\Ruby31-x64\bin
     - C:\Ruby32-x64\bin
     - C:\Ruby24-x64\bin
     - C:\Ruby25-x64\bin
     - C:\Ruby26-x64\bin
     - C:\Ruby27-x64\bin
     - C:\Ruby30-x64\bin
     - c:\jruby-9.4.0.0\bin
     - C:\Users\hurri\AppData\Local\Microsoft\WindowsApps
     - C:\Users\hurri\AppData\Local\JetBrains\Toolbox\scripts
     - C:\Users\hurri\AppData\Local\Programs\Microsoft VS Code\bin
     - C:\Users\hurri\AppData\Roaming\npm
     - C:\Strawberry\perl\bin\
     - C:\Users\hurri\.jdks\jbr-17.0.5\bin
```

## Gem list
```
abbrev (default: 0.1.0)
actioncable (7.0.8)
actionmailbox (7.0.8)
actionmailer (7.0.8)
actionpack (7.0.8)
actiontext (7.0.8)
actionview (7.0.8)
activejob (7.0.8)
activemodel (7.0.8)
activerecord (7.0.8)
activestorage (7.0.8)
activesupport (7.0.8)
addressable (2.8.5)
base64 (default: 0.1.0)
benchmark (default: 0.1.1)
bigdecimal (default: 3.0.0)
bindex (0.8.1)
bootsnap (1.16.0)
brakeman (6.0.1)
builder (3.2.4)
bundler (default: 2.2.33)
capybara (3.39.2)
cgi (default: 0.2.2)
concurrent-ruby (1.2.2)
crass (1.0.6)
csv (default: 3.1.9)
date (default: 3.1.3)
dbm (default: 1.1.0)
debug (1.8.0, default: 0.2.1)
delegate (default: 0.2.0)
did_you_mean (default: 1.5.0)
digest (default: 3.0.0)
drb (default: 2.0.5)
english (default: 0.7.1)
erb (default: 2.2.0)
erubi (1.12.0)
etc (default: 1.3.0)
fcntl (default: 1.0.1)
ffi (1.15.5 x64-mingw32)
fiddle (default: 1.0.8)
fileutils (default: 1.5.0)
find (default: 0.1.0)
forwardable (default: 1.3.2)
gdbm (default: 2.1.0)
getoptlong (default: 0.1.1)
globalid (1.2.1)
i18n (1.14.1)
importmap-rails (1.2.1)
io-console (0.6.0, default: 0.5.7)
io-nonblock (default: 0.1.0)
io-wait (default: 0.2.0)
ipaddr (default: 1.2.2)
irb (1.8.1, default: 1.3.5)
jbuilder (2.11.5)
json (default: 2.5.1)
logger (default: 1.4.3)
loofah (2.21.3)
mail (2.8.1)
marcel (1.0.2)
matrix (0.4.2, default: 0.3.1)
method_source (1.0.0)
mini_mime (1.1.5)
minitest (5.20.0, 5.14.2)
msgpack (1.7.2)
mutex_m (default: 0.1.1)
net-ftp (default: 0.1.2)
net-http (default: 0.1.1)
net-imap (0.3.7, default: 0.1.1)
net-pop (0.1.2, default: 0.1.1)
net-protocol (0.2.1, default: 0.1.1)
net-smtp (0.3.3, default: 0.2.1)
nio4r (2.5.9)
nkf (default: 0.1.0)
nokogiri (1.15.4 x64-mingw32)
observer (default: 0.1.1)
open-uri (default: 0.1.0)
open3 (default: 0.1.1)
openssl (default: 2.2.2)
optparse (default: 0.1.1)
ostruct (default: 0.3.1)
pathname (default: 0.1.0)
power_assert (1.2.0)
pp (default: 0.2.1)
prettyprint (default: 0.1.1)
prime (default: 0.1.2)
pstore (default: 0.1.1)
psych (default: 3.3.2)
public_suffix (5.0.3)
puma (5.6.7)
racc (1.7.1, default: 1.5.2)
rack (2.2.8)
rack-test (2.1.0)
rails (7.0.8)
rails-dom-testing (2.2.0)
rails-html-sanitizer (1.6.0)
railties (7.0.8)
rake (13.0.6, 13.0.3)
rbs (1.4.0)
rdoc (6.5.0, default: 6.3.3)
readline (default: 0.0.2)
regexp_parser (2.8.1)
reline (0.3.8, default: 0.2.5)
resolv (default: 0.2.1)
resolv-replace (default: 0.1.0)
rexml (3.2.6, 3.2.5)
rinda (default: 0.1.1)
rss (0.2.9)
rubyzip (2.3.2)
securerandom (default: 0.1.0)
selenium-webdriver (4.12.0)
set (default: 1.0.1)
shellwords (default: 0.1.0)
singleton (default: 0.1.1)
sprockets (4.2.1)
sprockets-rails (3.4.2)
sqlite3 (1.6.6 x64-mingw32)
stimulus-rails (1.2.2)
stringio (3.0.8, default: 3.0.1)
strscan (default: 3.0.1)
tempfile (default: 0.1.1)
test-unit (3.3.7)
thor (1.2.2)
time (default: 0.1.1)
timeout (0.4.0, default: 0.1.1)
tmpdir (default: 0.1.2)
tracer (default: 0.1.1)
tsort (default: 0.1.0)
turbo-rails (1.4.0)
typeprof (0.15.2)
tzinfo (2.0.6)
tzinfo-data (1.2023.3)
un (default: 0.1.0)
uri (default: 0.10.2)
weakref (default: 0.1.1)
web-console (4.2.1)
websocket (1.2.9)
websocket-driver (0.7.6)
websocket-extensions (0.1.5)
win32ole (default: 1.8.8)
yaml (default: 0.1.1)
zeitwerk (2.6.11)
zlib (default: 2.0.0)
```

**Comment by hurricup** [comment]
Installed version missing begin block around `Gem::RDoc.new`

But updating gems seems not possible as well:
```
C:\Ruby30-x64\lib\ruby\3.0.0\rubygems>gem update --system  --no-document                                                                                                                                                                                                        Updating rubygems-update                                                                                                                                                                                                                                                        Fetching rubygems-update-3.4.19.gem                                                                                                                                                                                                                                             Successfully installed rubygems-update-3.4.19                                                                                                                                                                                                                                   Installing RubyGems 3.4.19                                                                                                                                                                                                                                                        Successfully built RubyGem                                                                                                                                                                                                                                                      Name: bundler                                                                                                                                                                                                                                                                   Version: 2.4.19                                                                                                                                                                                                                                                                 File: bundler-2.4.19.gem                                                                                                                                                                                                                                                      Bundler 2.4.19 installed                                                                                                                                                                                                                                                        RubyGems 3.4.19 installed                                                                                                                                                                                                                                                       Regenerating binstubs                                                                                                                                                                                                                                                           Regenerating plugins                                                                                                                                                                                                                                                            ERROR:  While executing gem ... (NameError)                                                                                                                                                                                                                                         uninitialized constant Gem::RDoc                                                                                                                                                                                                                                                    C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubygems-update-3.4.19/lib/rubygems/commands/setup_command.rb:351:in `install_rdoc'                                                                                                                                                      C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubygems-update-3.4.19/lib/rubygems/commands/setup_command.rb:189:in `execute'                                                                                                                                                           C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubygems-update-3.4.19/lib/rubygems/command.rb:328:in `invoke_with_build_args'                                                                                                                                                           C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubygems-update-3.4.19/lib/rubygems/command_manager.rb:253:in `invoke_command'                                                                                                                                                           C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubygems-update-3.4.19/lib/rubygems/command_manager.rb:193:in `process_args'                                                                                                                                                             C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubygems-update-3.4.19/lib/rubygems/command_manager.rb:151:in `run'                                                                                                                                                                      C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubygems-update-3.4.19/lib/rubygems/gem_runner.rb:52:in `run'                                                                                                                                                                            setup.rb:34:in `<main>'                                                                                                        
```
Probably this is about `--no-document`

**Comment by deivid-rodriguez** [comment]
Pretty sure this was fixed by https://github.com/rubygems/rubygems/pull/4691. Feel free to reopen if that's not the case though!
