### ISSUE TITLE
Gem::Package::PathError: installing into parent path sorbet/rbi/sorbet-typed/lib/rubocop/~>0.85/rubocop.rbi of C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/workos-2.1.1 is not allowed

### ISSUE THREAD

**Issue by leonardovin** [rubygems/rubygems#6978]
### Describe the problem as clearly as you can

I'm using ruby 2.7.6 on windows 11, installed with the ruby installer, already have the ruby sdk, using newest bundler version. I am using an admin powershell.

### Which command did you run?

bundle install

### What were you expecting to happen?

install all gems in my gemfile

### What actually happened?

i got a permission error for the instalation path for rubocop 

### If not included with the output of your command, run `bundle env` and paste the output below
Output:

`--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::Package::PathError: installing into parent path sorbet/rbi/sorbet-typed/lib/rubocop/~>0.85/rubocop.rbi of C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/workos-2.1.1 is not allowed   
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:522:in `block in mkdir_p_safe'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:516:in `each'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:516:in `reduce'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:516:in `mkdir_p_safe'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:438:in `block (2 levels) in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/tar_reader.rb:67:in `each'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:421:in `block in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:550:in `block in open_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:547:in `wrap'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:547:in `open_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:420:in `extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:400:in `block (2 levels) in extract_files'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/tar_reader.rb:67:in `each'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:397:in `block in extract_files'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/file_source.rb:30:in `open'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package/file_source.rb:30:in `with_read_io'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/package.rb:394:in `extract_files'
  C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/installer.rb:865:in `extract_files'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:202:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.19
  Platforms   ruby, x64-mingw32
Ruby          2.7.6p219 (2022-04-12 revision c9c2245c0a25176072e02db9254f0e0c84c805cd) [x64-mingw32]
  Full Path   C:/Ruby27-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.1.6
  Gem Home    C:/Ruby27-x64/lib/ruby/gems/2.7.0
  Gem Path    C:/Ruby27/lib/ruby/gems/2.7.0;C:/Ruby27/lib/ruby/gems/2.7.0/gems;C:/Users/hotle/.gem/ruby/2.7.0;C:/Ruby27-x64/lib/ruby/gems/2.7.0
  User Home   C:/Users/hotle
  User Path   C:/Users/hotle/.gem/ruby/2.7.0
  Bin Dir     C:/Ruby27-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   C:/Ruby27-x64/ssl/cert.pem
  Cert Dir    C:/Ruby27-x64/ssl/certs
Tools
  Git         2.38.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-08-17
Git SHA           86f98098e3
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', github: 'rails/rails', branch: '6-1-stable'

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

# Use Puma as the app server
gem 'puma', '~> 4.3.12'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

gem 'aws-sdk-rails'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-sqs', '~> 1'
gem 'dotenv-rails', groups: %i[development test]
gem 'graphql'
gem 'http'
gem 'interactor', '~> 3.0'
gem 'interactor-rails', '~> 2.0'
gem 'jwt'
gem 'mjml-rails'
gem 'olive_branch'
gem 'pundit'
gem 'sendgrid-actionmailer', '~> 2.4'
gem 'stripe'
gem 'stripe_event'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'brakeman'
  gem 'letter_opener'
  gem 'rubocop'
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_bot_rails', '~> 4.0'
  gem 'faker'
  gem 'rspec-rails', '~> 4.1.0'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov'

  # Stripe Mock
  # TODO Update lib once Price API is supported in stripe-ruby-mock
  gem 'stripe-ruby-mock', '~> 3.0.1', require: 'stripe_mock',
                              git: 'https://github.com/PlaybookUX/stripe-ruby-mock.git', branch: 'create-price'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'logging-rails', require: 'logging/rails'
gem 'lograge'

# Fix for licencing issue with mimemagic gem.
#   Requires user to install shared mime database separately.
#   Linux: sudo apt install shared-mime-info
#   macOS: brew install shared-mime-info
gem 'mimemagic', '~> 0.3.8'

gem 'icalendar'
gem 'nokogiri'
gem 'pg_search'
gem 'rack-attack'
gem 'workos', '~> 2.1.0'

# PayPal
gem 'paypal-payouts-sdk'

# Elasticsearch
gem 'elasticsearch', '<7.14'

gem 'sanitize', '~> 6.0.1'

gem 'graphql-batch'

gem 'graphql-guard'

gem 'lockbox'

gem 'blind_index'
```

### Gemfile.lock

```
GIT
  remote: https://github.com/PlaybookUX/stripe-ruby-mock.git
  revision: e8172927a9b8d19392a86a803df3947302fbf511
  branch: create-price
  specs:
    stripe-ruby-mock (3.0.1)
      dante (>= 0.2.0)
      multi_json (~> 1.0)
      stripe (> 5, < 6)

GIT
  remote: https://github.com/rails/rails.git
  revision: 33a9277546644bd2fac328f1c764a3323bad3eea
  branch: 6-1-stable
  specs:
    actioncable (6.1.7.3)
      actionpack (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.7.3)
      actionpack (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activestorage (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      mail (>= 2.7.1)
    actionmailer (6.1.7.3)
      actionpack (= 6.1.7.3)
      actionview (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.7.3)
      actionview (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.7.3)
      actionpack (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activestorage (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      nokogiri (>= 1.8.5)
    actionview (6.1.7.3)
      activesupport (= 6.1.7.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.7.3)
      activesupport (= 6.1.7.3)
      globalid (>= 0.3.6)
    activemodel (6.1.7.3)
      activesupport (= 6.1.7.3)
    activerecord (6.1.7.3)
      activemodel (= 6.1.7.3)
      activesupport (= 6.1.7.3)
    activestorage (6.1.7.3)
      actionpack (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.7.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    rails (6.1.7.3)
      actioncable (= 6.1.7.3)
      actionmailbox (= 6.1.7.3)
      actionmailer (= 6.1.7.3)
      actionpack (= 6.1.7.3)
      actiontext (= 6.1.7.3)
      actionview (= 6.1.7.3)
      activejob (= 6.1.7.3)
      activemodel (= 6.1.7.3)
      activerecord (= 6.1.7.3)
      activestorage (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      bundler (>= 1.15.0)
      railties (= 6.1.7.3)
      sprockets-rails (>= 2.0.0)
    railties (6.1.7.3)
      actionpack (= 6.1.7.3)
      activesupport (= 6.1.7.3)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.3)
      public_suffix (>= 2.0.2, < 6.0)
    argon2-kdf (0.1.7)
    ast (2.4.1)
    aws-eventstream (1.1.0)
    aws-partitions (1.370.0)
    aws-sdk-core (3.107.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.38.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-rails (3.1.0)
      aws-sdk-ses (~> 1)
      railties (>= 5.2.0)
    aws-sdk-s3 (1.81.0)
      aws-sdk-core (~> 3, >= 3.104.3)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sdk-ses (1.35.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-sqs (1.33.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.2)
      aws-eventstream (~> 1, >= 1.0.2)
    bcrypt (3.1.16)
    blind_index (2.3.1)
      activesupport (>= 5.2)
      argon2-kdf (>= 0.1.1)
    bootsnap (1.4.8)
      msgpack (~> 1.0)
    brakeman (5.0.0)
    builder (3.2.4)
    byebug (11.1.3)
    concurrent-ruby (1.2.2)
    crass (1.0.6)
    dante (0.2.0)
    database_cleaner (1.8.5)
    date (3.3.3)
    diff-lcs (1.5.0)
    docile (1.3.4)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    dotenv-rails (2.7.6)
      dotenv (= 2.7.6)
      railties (>= 3.2)
    elasticsearch (7.13.3)
      elasticsearch-api (= 7.13.3)
      elasticsearch-transport (= 7.13.3)
    elasticsearch-api (7.13.3)
      multi_json
    elasticsearch-transport (7.13.3)
      faraday (~> 1)
      multi_json
    erubi (1.12.0)
    factory_bot (4.11.1)
      activesupport (>= 3.0.0)
    factory_bot_rails (4.11.1)
      factory_bot (~> 4.11.1)
      railties (>= 3.0.0)
    faker (2.14.0)
      i18n (>= 1.6, < 2)
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    ffi (1.15.5)
    ffi-compiler (1.0.1)
      ffi (>= 1.0.0)
      rake
    globalid (1.1.0)
      activesupport (>= 5.0)
    graphql (1.11.4)
    graphql-batch (0.5.1)
      graphql (>= 1.10, < 3)
      promise.rb (~> 0.7.2)
    graphql-guard (2.0.0)
      graphql (>= 1.10.0, < 2)
    http (4.4.1)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 2.2)
      http-parser (~> 1.2.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http-form_data (2.3.0)
    http-parser (1.2.3)
      ffi-compiler (>= 1.0, < 2.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    icalendar (2.7.0)
      ice_cube (~> 0.16)
    ice_cube (0.16.3)
    interactor (3.1.2)
    interactor-rails (2.2.1)
      interactor (~> 3.0)
      rails (>= 4.2)
    jmespath (1.6.2)
    jwt (2.2.2)
    launchy (2.5.0)
      addressable (~> 2.7)
    letter_opener (1.7.0)
      launchy (~> 2.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    little-plugger (1.1.4)
    lockbox (1.1.0)
    logging (2.3.0)
      little-plugger (~> 1.1)
      multi_json (~> 1.14)
    logging-rails (0.6.0)
      logging (>= 1.8)
    lograge (0.11.2)
      actionpack (>= 4)
      activesupport (>= 4)
      railties (>= 4)
      request_store (~> 1.0)
    loofah (2.20.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    method_source (1.0.0)
    mimemagic (0.3.10)
      nokogiri (~> 1)
      rake
    mini_mime (1.1.2)
    mini_portile2 (2.8.1)
    minitest (5.18.0)
    mjml-rails (4.4.0)
    msgpack (1.3.3)
    multi_json (1.15.0)
    multipart-post (2.1.1)
    net-imap (0.3.4)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-smtp (0.3.3)
      net-protocol
    nio4r (2.5.9)
    nokogiri (1.14.3)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    oj (3.10.14)
    olive_branch (3.0.0)
      multi_json
      oj
      rails (>= 4.0)
    parallel (1.20.1)
    parser (3.0.0.0)
      ast (~> 2.4.1)
    paypal-payouts-sdk (1.0.1)
      paypalhttp (~> 1.0.1)
    paypalhttp (1.0.1)
    pg (1.2.3)
    pg_search (2.3.2)
      activerecord (>= 5.2)
      activesupport (>= 5.2)
    promise.rb (0.7.4)
    public_suffix (5.0.1)
    puma (4.3.12)
      nio4r (~> 2.0)
    pundit (2.1.0)
      activesupport (>= 3.0.0)
    racc (1.6.2)
    rack (2.2.6.4)
    rack-attack (6.5.0)
      rack (>= 1.0, < 3)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.5.0)
      loofah (~> 2.19, >= 2.19.1)
    rainbow (3.0.0)
    rake (13.0.6)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    redis (4.8.0)
    regexp_parser (2.0.3)
    request_store (1.5.0)
      rack (>= 1.4)
    rexml (3.2.5)
    rspec-core (3.12.1)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.5)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-rails (4.1.2)
      actionpack (>= 4.2)
      activesupport (>= 4.2)
      railties (>= 4.2)
      rspec-core (~> 3.10)
      rspec-expectations (~> 3.10)
      rspec-mocks (~> 3.10)
      rspec-support (~> 3.10)
    rspec-support (3.12.0)
    rubocop (1.7.0)
      parallel (~> 1.10)
      parser (>= 2.7.1.5)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.2.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 2.0)
    rubocop-ast (1.3.0)
      parser (>= 2.7.1.5)
    rubocop-rails (2.15.2)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.7.0, < 2.0)
    rubocop-rspec (2.4.0)
      rubocop (~> 1.0)
      rubocop-ast (>= 1.1.0)
    ruby-progressbar (1.10.1)
    ruby2_keywords (0.0.5)
    ruby_dep (1.5.0)
    ruby_http_client (3.5.1)
    sanitize (6.0.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    sendgrid-actionmailer (2.6.0)
      mail (~> 2.5)
      sendgrid-ruby (~> 6.0)
    sendgrid-ruby (6.3.4)
      ruby_http_client (~> 3.4)
    shoulda-matchers (3.1.3)
      activesupport (>= 4.0.0)
    simplecov (0.21.1)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.2)
    sorbet-runtime (0.5.9818)
    spring (2.1.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (4.2.0)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    stripe (5.25.0)
    stripe_event (2.3.1)
      activesupport (>= 3.1)
      stripe (>= 2.8, < 6)
    thor (1.2.1)
    timeout (0.3.2)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.7)
    unicode-display_width (1.7.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    workos (2.1.1)
      sorbet-runtime (~> 0.5)
    zeitwerk (2.6.7)

PLATFORMS
  ruby

DEPENDENCIES
  aws-sdk-rails
  aws-sdk-s3 (~> 1)
  aws-sdk-sqs (~> 1)
  bcrypt (~> 3.1.7)
  blind_index
  bootsnap (>= 1.1.0)
  brakeman
  byebug
  database_cleaner
  dotenv-rails
  elasticsearch (< 7.14)
  factory_bot_rails (~> 4.0)
  faker
  graphql
  graphql-batch
  graphql-guard
  http
  icalendar
  interactor (~> 3.0)
  interactor-rails (~> 2.0)
  jwt
  letter_opener
  listen (>= 3.0.5, < 3.2)
  lockbox
  logging-rails
  lograge
  mimemagic (~> 0.3.8)
  mjml-rails
  nokogiri
  olive_branch
  paypal-payouts-sdk
  pg (>= 0.18, < 2.0)
  pg_search
  puma (~> 4.3.12)
  pundit
  rack-attack
  rack-cors
  rails!
  redis (~> 4.0)
  rspec-rails (~> 4.1.0)
  rubocop
  rubocop-rails
  rubocop-rspec
  sanitize (~> 6.0.1)
  sendgrid-actionmailer (~> 2.4)
  shoulda-matchers (~> 3.1)
  simplecov
  spring
  spring-watcher-listen (~> 2.0.0)
  stripe
  stripe-ruby-mock (~> 3.0.1)!
  stripe_event
  tzinfo-data
  workos (~> 2.1.0)

RUBY VERSION
   ruby 2.7.6p219

BUNDLED WITH
   2.3.16
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=installing+into+parent+path+sorbet%2Frbi%2Fsorbet-typed%2Flib%2Frubocop%2F~%3E0.85%2Frubocop.rbi+of+C+%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fworkos-2.1.1+is+not+allowed&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
`

**Comment by deivid-rodriguez** [comment]
This is so weird. Could you create a github actions workflow on a public repo using this Gemfile that reproduces the issue?

**Comment by hsbt** [comment]
and Can you try it with the latest version of RubyGems/Bundler? It caused by `sorbet-typed` especially `~>` path and `mkdir_p_safe` method of RubyGems.

**Comment by leonardovin** [comment]
Will try it this weekend on a native Windows 11 boot and let you know!

**Comment by deivid-rodriguez** [comment]
Please reopen if you retry and run into the issue again. Thanks!
