### ISSUE TITLE
Cannot install bundler

### ISSUE THREAD

**Issue by zouineex** [rubygems/rubygems#7007]
### Describe the problem as clearly as you can

When i try to install bundler byn running "bundler install", i get the following error : 

Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this machine.
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Bundler::URI::InvalidURIError: bad Bundler::URI(is not Bundler::URI?): "http://SVC_*_PROXY:*@proxy-ng.*.fr:8080"
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/uri/lib/uri/rfc3986_parser.rb:66:in `split'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/uri/lib/uri/rfc3986_parser.rb:71:in `parse'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/uri/lib/uri/common.rb:193:in `parse'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/uri/lib/uri/common.rb:722:in `URI'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:788:in `proxy_from_env'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:738:in `proxy='
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:520:in `initialize'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/fetcher.rb:253:in `new'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/fetcher.rb:253:in `connection'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/fetcher.rb:100:in `initialize'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:258:in `new'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:258:in `block in fetchers'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:256:in `map'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:256:in `fetchers'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:400:in `block in remote_specs'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/index.rb:9:in `build'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:399:in `remote_specs'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/source/rubygems.rb:133:in `specs'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:205:in `map!'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:205:in `specs_for_dependency'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:34:in `block in for'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:22:in `loop'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:22:in `for'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/spec_set.rb:85:in `materialize'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/definition.rb:523:in `materialize'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/definition.rb:200:in `specs'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer.rb:83:in `block in run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/process_lock.rb:12:in `block in lock'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/process_lock.rb:9:in `open'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/process_lock.rb:9:in `lock'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer.rb:71:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/installer.rb:23:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/cli/install.rb:62:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/cli.rb:261:in `block in install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/settings.rb:130:in `temporary'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/cli.rb:260:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/cli.rb:34:in `dispatch'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/cli.rb:28:in `start'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /var/lib/gems/2.7.0/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler       2.4.19
  Platforms   ruby, x86_64-linux
Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-linux]
  Full Path   /usr/bin/ruby2.7
  Config Dir  /etc
RubyGems      3.2.5
  Gem Home    /var/lib/gems/2.7.0
  Gem Path    /root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0
  User Home   /root
  User Path   /root/.local/share/gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
OpenSSL
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-08-17
Git SHA           86f98098e3
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

group :development do
  gem 'capistrano', '~> 3.5.0'
  gem 'capistrano-composer', '~> 0.0.6'
  gem 'openssl', '~> 2.2.2'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    airbrussh (1.3.0)
      sshkit (>= 1.6.1, != 1.7.0)
    capistrano (3.5.0)
      airbrussh (>= 1.0.0)
      capistrano-harrow
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-composer (0.0.6)
      capistrano (>= 3.0.0.pre)
    capistrano-harrow (0.5.3)
    concurrent-ruby (1.0.5)
    i18n (0.9.3)
      concurrent-ruby (~> 1.0)
    ipaddr (1.2.4)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (4.2.0)
    openssl (2.2.2)
      ipaddr
    rake (12.3.0)
    sshkit (1.15.1)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)

PLATFORMS
  ruby

DEPENDENCIES
  capistrano (~> 3.5.0)
  capistrano-composer (~> 0.0.6)
  openssl (~> 2.2.2)

BUNDLED WITH
   2.3.22
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=bad+Bundler++URI%28is+not+Bundler++URI%3F%29++%22http+%2F%2FSVC_*_PROXY+*proxy-ng.*.fr+8080%22&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

**Comment by zouineex** [comment]
In fact, it was me who replaced some infos with *

**Comment by deivid-rodriguez** [comment]
Ok, so this is probably some particularity of this URL that https://github.com/ruby/uri does not support. If you run `ruby -ruri -e'URI.parse("<your-proxy-uri>")'`, do you get a similar error?
