### ISSUE TITLE
Bundler Error behind Proxy

### ISSUE THREAD

**Issue by AmanShaikh1099** [rubygems/rubygems#7009]
// I am installing bundle behind a proxy ,i tried white Listing (ruby.org) but I got same error every time 

//Tried sudo bundle install ,but the installation was incomplete. I don't know what to do your answer would be really appreciated 
bundle install
Ignoring bcrypt-3.1.18 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.18
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring byebug-11.1.3 because its extensions are not built. Try: gem pristine byebug --version 11.1.3
Ignoring date-3.3.3 because its extensions are not built. Try: gem pristine date --version 3.3.3
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Ignoring haml-6.1.1 because its extensions are not built. Try: gem pristine haml --version 6.1.1
Ignoring json-2.6.3 because its extensions are not built. Try: gem pristine json --version 2.6.3
Ignoring mysql2-0.5.5 because its extensions are not built. Try: gem pristine mysql2 --version 0.5.5
Ignoring nio4r-2.5.8 because its extensions are not built. Try: gem pristine nio4r --version 2.5.8
Ignoring nokogiri-1.14.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.14.2
Ignoring puma-5.6.5 because its extensions are not built. Try: gem pristine puma --version 5.6.5
Ignoring racc-1.6.2 because its extensions are not built. Try: gem pristine racc --version 1.6.2
Ignoring rinku-2.0.6 because its extensions are not built. Try: gem pristine rinku --version 2.0.6
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
ArgumentError: proxy must be :ENV or a Bundler::URI::HTTP
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:741:in `proxy='
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/fetcher.rb:255:in `connection'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/fetcher.rb:100:in `initialize'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:258:in `new'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:258:in `block in fetchers'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:256:in `map'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:256:in `fetchers'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:400:in `block in remote_specs'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/index.rb:9:in `build'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:399:in `remote_specs'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:133:in `specs'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/lazy_specification.rb:82:in `materialize_for_installation'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/spec_set.rb:205:in `map!'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/spec_set.rb:205:in `specs_for_dependency'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/spec_set.rb:34:in `block in for'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/spec_set.rb:22:in `loop'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/spec_set.rb:22:in `for'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/spec_set.rb:85:in `materialize'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:523:in `materialize'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:200:in `specs'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:83:in `block in run'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/process_lock.rb:9:in `open'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/process_lock.rb:9:in `lock'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:71:in `run'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:23:in `install'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/cli/install.rb:62:in `run'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:261:in `block in install'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/settings.rb:130:in `temporary'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:260:in `install'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
  /usr/local/rvm/gems/ruby-3.2.1@hroot/bin/bundle:25:in `load'
  /usr/local/rvm/gems/ruby-3.2.1@hroot/bin/bundle:25:in `<main>'
  /usr/local/rvm/gems/ruby-3.2.1@hroot/bin/ruby_executable_hooks:22:in `eval'
  /usr/local/rvm/gems/ruby-3.2.1@hroot/bin/ruby_executable_hooks:22:in `<main>'

```

## Environment

```
Bundler             2.4.19
  Platforms         ruby, x86_64-linux
Ruby                3.2.1p31 (2023-02-08 revision 31819e82c88c6f8ecfaeb162519bfa26a14b21fd) [x86_64-linux]
  Full Path         /usr/local/rvm/rubies/ruby-3.2.1/bin/ruby
  Config Dir        /etc
RubyGems            3.4.19
  Gem Home          /usr/local/rvm/gems/ruby-3.2.1@hroot
  Gem Path          /usr/local/rvm/gems/ruby-3.2.1@hroot:/usr/local/rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0
  User Home         /home/claus
  User Path         /home/claus/.gem/ruby/3.2.0
  Bin Dir           /usr/local/rvm/gems/ruby-3.2.1@hroot/bin
OpenSSL
  Compiled          OpenSSL 1.1.1n  15 Mar 2022
  Loaded            OpenSSL 1.1.1n  15 Mar 2022
  Cert File         /usr/lib/ssl/cert.pem
  Cert Dir          /usr/lib/ssl/certs
Tools
  Git               2.30.2
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2023-08-17
Git SHA           86f98098e3
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'rails'
gem 'bundler'
gem 'railties', '7.0.4.2'
gem 'mysql2'
gem "haml-rails"
gem 'sprockets', '~> 3.0'
gem 'sass-rails'
gem 'coffee-script'
gem 'ledermann-rails-settings'
gem 'sequel'
gem 'jquery-rails'
gem 'will_paginate-bootstrap'
gem 'devise'
gem 'simple_form'
gem 'event-calendar', :require => 'event_calendar'
gem 'exception_notification'
gem 'icalendar'
gem 'cancancan'
gem "rubyzip"
gem "spreadsheet"
gem 'acts-as-taggable-on'
gem 'whenever', :require => false
gem "bundler-audit"
gem 'date_validator'
gem 'rinku', :require => 'rails_rinku'
gem 'momentjs-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'uglifier'
gem 'i18n-active_record', :require => 'i18n/active_record'
gem "simple-navigation"
gem 'js-routes'
gem 'rails-controller-testing'
gem 'tzinfo-data'
gem 'turnout'
gem 'net-smtp'

group :development do
  gem 'web-console'
  gem 'rubocop', require: false
end

group :development, :test do
  gem 'byebug'
  gem 'simplecov', :require => false
  gem 'jslint_on_rails'
  gem 'factory_bot_rails'
  gem 'test-unit'
  gem 'shoulda-context', '~> 2.0'
  gem 'shoulda-matchers', '~> 5.0'
  gem 'rubocop-rspec'
  gem 'mocha', :require => 'mocha/minitest'
  gem 'puma', '~> 5.2'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.4.2)
      actionpack (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.4.2)
      actionpack (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activestorage (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.4.2)
      actionpack (= 7.0.4.2)
      actionview (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.4.2)
      actionview (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.4.2)
      actionpack (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activestorage (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.4.2)
      activesupport (= 7.0.4.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.4.2)
      activesupport (= 7.0.4.2)
      globalid (>= 0.3.6)
    activemodel (7.0.4.2)
      activesupport (= 7.0.4.2)
    activerecord (7.0.4.2)
      activemodel (= 7.0.4.2)
      activesupport (= 7.0.4.2)
    activestorage (7.0.4.2)
      actionpack (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.4.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    acts-as-taggable-on (9.0.1)
      activerecord (>= 6.0, < 7.1)
    ast (2.4.2)
    bcrypt (3.1.18)
    bindex (0.8.1)
    bootstrap3-datetimepicker-rails (4.17.47)
      momentjs-rails (>= 2.8.1)
    builder (3.2.4)
    bundler-audit (0.9.1)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    byebug (11.1.3)
    cancancan (3.5.0)
    chronic (0.10.2)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.2.2)
    crass (1.0.6)
    date (3.3.3)
    date_validator (0.12.0)
      activemodel (>= 3)
      activesupport (>= 3)
    devise (4.9.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    docile (1.4.0)
    erubi (1.12.0)
    event-calendar (2.3.3)
    exception_notification (4.5.0)
      actionmailer (>= 5.2, < 8)
      activesupport (>= 5.2, < 8)
    execjs (2.8.1)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    ffi (1.15.5)
    globalid (1.1.0)
      activesupport (>= 5.0)
    haml (6.1.1)
      temple (>= 0.8.2)
      thor
      tilt
    haml-rails (2.1.0)
      actionpack (>= 5.1)
      activesupport (>= 5.1)
      haml (>= 4.0.6)
      railties (>= 5.1)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    i18n-active_record (1.1.0)
      i18n (>= 0.5.0)
    icalendar (2.8.0)
      ice_cube (~> 0.16)
    ice_cube (0.16.4)
    jquery-rails (4.5.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    js-routes (2.2.4)
      railties (>= 4)
    jslint_on_rails (1.1.1)
    json (2.6.3)
    ledermann-rails-settings (2.5.0)
      activerecord (>= 4.2)
    loofah (2.19.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    mini_portile2 (2.8.4)
    minitest (5.18.0)
    mocha (2.0.2)
      ruby2_keywords (>= 0.0.5)
    momentjs-rails (2.29.4.1)
      railties (>= 3.1)
    mysql2 (0.5.5)
    net-imap (0.3.4)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-smtp (0.3.3)
      net-protocol
    nio4r (2.5.8)
    nokogiri (1.14.2)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.14.2-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.14.2-x86_64-darwin)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    parallel (1.22.1)
    parser (3.2.1.0)
      ast (~> 2.4.1)
    power_assert (2.0.3)
    puma (5.6.5)
      nio4r (~> 2.0)
    racc (1.6.2)
    rack (2.2.6.3)
    rack-accept (0.4.5)
      rack (>= 0.4)
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (7.0.4.2)
      actioncable (= 7.0.4.2)
      actionmailbox (= 7.0.4.2)
      actionmailer (= 7.0.4.2)
      actionpack (= 7.0.4.2)
      actiontext (= 7.0.4.2)
      actionview (= 7.0.4.2)
      activejob (= 7.0.4.2)
      activemodel (= 7.0.4.2)
      activerecord (= 7.0.4.2)
      activestorage (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      bundler (>= 1.15.0)
      railties (= 7.0.4.2)
    rails-controller-testing (1.0.5)
      actionpack (>= 5.0.1.rc1)
      actionview (>= 5.0.1.rc1)
      activesupport (>= 5.0.1.rc1)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.5.0)
      loofah (~> 2.19, >= 2.19.1)
    railties (7.0.4.2)
      actionpack (= 7.0.4.2)
      activesupport (= 7.0.4.2)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rainbow (3.1.1)
    rake (13.0.6)
    regexp_parser (2.7.0)
    responders (3.1.0)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.2.5)
    rinku (2.0.6)
    rubocop (1.48.0)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.2.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.26.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.27.0)
      parser (>= 3.2.1.0)
    rubocop-capybara (2.17.1)
      rubocop (~> 1.41)
    rubocop-rspec (2.19.0)
      rubocop (~> 1.33)
      rubocop-capybara (~> 2.17)
    ruby-ole (1.2.12.2)
    ruby-progressbar (1.13.0)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    sequel (5.66.0)
    shoulda-context (2.0.0)
    shoulda-matchers (5.3.0)
      activesupport (>= 5.2.0)
    simple-navigation (4.4.0)
      activesupport (>= 2.3.2)
    simple_form (5.2.0)
      actionpack (>= 5.2)
      activemodel (>= 5.2)
    simplecov (0.22.0)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.4)
    spreadsheet (1.3.0)
      ruby-ole
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    temple (0.10.0)
    test-unit (3.5.7)
      power_assert
    thor (1.2.1)
    tilt (2.1.0)
    timeout (0.3.2)
    turnout (2.5.0)
      i18n (>= 0.7, < 2)
      rack (>= 1.3, < 3)
      rack-accept (~> 0.4)
      tilt (>= 1.4, < 3)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2022.7)
      tzinfo (>= 1.0.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (2.4.2)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    whenever (1.0.0)
      chronic (>= 0.6.3)
    will_paginate (3.3.1)
    will_paginate-bootstrap (1.0.2)
      will_paginate (>= 3.0.3)
    zeitwerk (2.6.7)

PLATFORMS
  arm64-darwin-22
  ruby
  x86_64-darwin-21

DEPENDENCIES
  acts-as-taggable-on
  bootstrap3-datetimepicker-rails
  bundler
  bundler-audit
  byebug
  cancancan
  coffee-script
  date_validator
  devise
  event-calendar
  exception_notification
  factory_bot_rails
  haml-rails
  i18n-active_record
  icalendar
  jquery-rails
  js-routes
  jslint_on_rails
  ledermann-rails-settings
  mocha
  momentjs-rails
  mysql2
  net-smtp
  puma (~> 5.2)
  rails
  rails-controller-testing
  railties (= 7.0.4.2)
  rinku
  rubocop
  rubocop-rspec
  rubyzip
  sass-rails
  sequel
  shoulda-context (~> 2.0)
  shoulda-matchers (~> 5.0)
  simple-navigation
  simple_form
  simplecov
  spreadsheet
  sprockets (~> 3.0)
  test-unit
  turnout
  tzinfo-data
  uglifier
  web-console
  whenever
  will_paginate-bootstrap

BUNDLED WITH
   2.4.19
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by simi** [comment]
@AmanShaikh1099 can you please add more info? How do you setup proxy (just ensure you mask sensitive data)?

**Comment by AmanShaikh1099** [comment]
Yeah Sure, basically I am mentioning all the website the surpases the proxy server. @simi 

![bundlererror](https://github.com/rubygems/rubygems/assets/133968597/124b2e25-b57b-42ad-b5c4-d1995aebdacf)

**Comment by simi** [comment]
And how do you set proxy for bundler?

**Comment by AmanShaikh1099** [comment]
you can see by mentioning  https://rubygems.org/gem/bundler

**Comment by simi** [comment]
> you can see by mentioning https://rubygems.org/gem/bundler

That is not URL related to bundle/gem install. I'm interested in your setup. How do you setup bundler to use proxy server?

**Comment by AmanShaikh1099** [comment]
sudo nano xyz
-- This open a text editor and then ---
Acquire::https::Proxy::dl.gna.org "https://rubygems.org";
Acquire::https::Proxy::dl.gna.org "https://rubygems.org/gems/bundler";

I save it ctrl+o then 

bundle install

this is how I surpasses the secure proxy server,which are not directly accessible if I am doing it wrong can you tell me the right  @simi .

**Comment by deivid-rodriguez** [comment]
Sorry for the late followup. If still intereset, could you please try again using the latest version of Bundler? Thanks!
