### ISSUE TITLE
Ruby first Run Error Template

### ISSUE THREAD

**Issue by JackLeJack99** [rubygems/rubygems#7032]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/irb.bat
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `open'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:546:in `generate_bin_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `each'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/source/rubygems.rb:200:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/irb.bat
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `open'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:546:in `generate_bin_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `each'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/source/rubygems.rb:200:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```
![Immagine](https://github.com/rubygems/rubygems/assets/146847274/3f507f60-748e-44d8-8045-455633c0edec)
![Immagine 2023-10-03 152958](https://github.com/rubygems/rubygems/assets/146847274/aaf63aba-1155-4f44-869d-bdbc1a2e3594)

**Comment by deivid-rodriguez** [comment]
Could you please copy the full output? Thanks!

**Comment by JackLeJack99** [comment]
Sure, there u go

PS C:\Users\jacks\OneDrive\Desktop\RubyOnRails\ProgettoMensa2> rails s
Could not find gem 'sprockets-rails' in locally installed gems.
Run `bundle install --gemfile C:/Users/jacks/OneDrive/Desktop/RubyOnRails/ProgettoMensa2/Gemfile` to install missing gems.
PS C:\Users\jacks\OneDrive\Desktop\RubyOnRails\ProgettoMensa2> bundle install --gemfile C:/Users/jacks/OneDrive/Desktop/RubyOnRails/ProgettoMensa2/Gemfile
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.2.2
Using date 3.3.3
Using minitest 5.20.0
Using builder 3.2.4
Using erubi 1.12.0
Using bundler 2.4.10
Using crass 1.0.6
Using rack 2.2.8
Using nio4r 2.5.9
Using io-console 0.6.0
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Using mini_mime 1.1.5
Using timeout 0.4.0
Using public_suffix 5.0.3
Using bindex 0.8.1
Using msgpack 1.7.2
Using matrix 0.4.2
Using regexp_parser 2.8.1
Using stringio 3.0.8
Using method_source 1.0.0
Using thor 1.2.2
Using zeitwerk 2.6.12
Using rexml 3.2.6
Using net-protocol 0.2.1
Using rubyzip 2.3.2
Using websocket 1.2.10
Using sqlite3 1.6.6 (x64-mingw-ucrt)
Using i18n 1.14.1
Using tzinfo 2.0.6
Using rack-test 2.1.0
Using websocket-driver 0.7.6
Using reline 0.3.8
Using puma 5.6.7
Using sprockets 4.2.1
Using addressable 2.8.5
Using bootsnap 1.16.0
Using psych 5.1.0
Using activesupport 7.0.8
Using rdoc 6.5.0
Using net-imap 0.3.7
Using net-pop 0.1.2
Using net-smtp 0.4.0
Using selenium-webdriver 4.13.1
Using tzinfo-data 1.2023.3
Using globalid 1.2.1
Using activemodel 7.0.8
Using mail 2.8.1
Using activejob 7.0.8
Using activerecord 7.0.8
Installing racc 1.7.1 with native extensions
Installing irb 1.8.1
Using rake 13.0.6
Using date 3.3.3
Using concurrent-ruby 1.2.2
Using minitest 5.20.0
Using builder 3.2.4
Using erubi 1.12.0
Using bundler 2.4.10
Using crass 1.0.6
Using rack 2.2.8
Using nio4r 2.5.9
Using io-console 0.6.0
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Using mini_mime 1.1.5
Using timeout 0.4.0
Using public_suffix 5.0.3
Using bindex 0.8.1
Using msgpack 1.7.2
Using matrix 0.4.2
Using regexp_parser 2.8.1
Using stringio 3.0.8
Using method_source 1.0.0
Using thor 1.2.2
Using zeitwerk 2.6.12
Using rexml 3.2.6
Using rubyzip 2.3.2
Using websocket 1.2.10
Using sqlite3 1.6.6 (x64-mingw-ucrt)
Using net-protocol 0.2.1
Using i18n 1.14.1
Using tzinfo 2.0.6
Using rack-test 2.1.0
Using websocket-driver 0.7.6
Using addressable 2.8.5
Using bootsnap 1.16.0
Using psych 5.1.0
Using reline 0.3.8
Using puma 5.6.7
Using sprockets 4.2.1
Using net-imap 0.3.7
Using net-pop 0.1.2
Using rdoc 6.5.0
Using net-smtp 0.4.0
Using selenium-webdriver 4.13.1
Using activesupport 7.0.8
Using tzinfo-data 1.2023.3
Using mail 2.8.1
Using globalid 1.2.1
Using activemodel 7.0.8
Using activejob 7.0.8
Using activerecord 7.0.8
Installing racc 1.7.1 with native extensions
Installing irb 1.8.1
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/irb.bat
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `open'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:546:in `generate_bin_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `each'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/source/rubygems.rb:200:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/irb.bat
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `initialize'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `open'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:477:in `generate_windows_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:546:in `generate_bin_script'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:506:in `block in generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `each'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:490:in `generate_bin'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:32:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/source/rubygems.rb:200:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  C:/Ruby32-x64/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.10
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x64-mingw-ucrt]
  Full Path   C:/Ruby32-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.4.10
  Gem Home    C:/Ruby32-x64/lib/ruby/gems/3.2.0
  Gem Path    C:/Users/jacks/.local/share/gem/ruby/3.2.0;C:/Ruby32-x64/lib/ruby/gems/3.2.0
  User Home   C:/Users/jacks
  User Path   C:/Users/jacks/.local/share/gem/ruby/3.2.0
  Bin Dir     C:/Ruby32-x64/bin
OpenSSL
  Compiled    OpenSSL 3.1.0 14 Mar 2023
  Loaded      OpenSSL 3.1.0 14 Mar 2023
  Cert File   C:/Ruby32-x64/bin/etc/ssl/cert.pem
  Cert Dir    C:/Ruby32-x64/bin/etc/ssl/certs
Tools
  Git         2.42.0.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-10-03
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
gemfile
  Set via BUNDLE_GEMFILE: "C:/Users/jacks/OneDrive/Desktop/RubyOnRails/ProgettoMensa2/Gemfile"
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.8"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"

end
```

### Gemfile.lock

```
<No C:/Users/jacks/OneDrive/Desktop/RubyOnRails/ProgettoMensa2/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+rb_sysopen+-+C+%2FRuby32-x64%2Fbin%2Firb.bat&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

**Comment by deivid-rodriguez** [comment]
Can you run `gem update --system` and try again?

**Comment by JackLeJack99** [comment]
Now it works, thank you so much Deivid, muchas gracias <3

**Comment by deivid-rodriguez** [comment]
I guess some bug in older versions 🤷‍♂️. De nada! :)
