### ISSUE TITLE
Infinite style loop when attempting to bundle

### ISSUE THREAD

**Issue by luke-hill** [rubygems/rubygems#7044]
### Describe the problem as clearly as you can

I tried to bundle the following gemspec

```
  s.add_runtime_dependency('capybara', '>= 3.11', '< 4')
  s.add_runtime_dependency('cucumber', '>= 5', '< 10')
  s.add_runtime_dependency('railties', '>= 5.2', '< 8')

  # Main development dependencies
  s.add_development_dependency('ammeter', '>= 1.1.4')
  s.add_development_dependency('appraisal', '>= 2.4.1', '< 3')
  s.add_development_dependency('aruba', '>= 1.1.2', '< 3')
  s.add_development_dependency('bundler', '>= 1.17')
  s.add_development_dependency('database_cleaner', '>= 1.8', '< 3.0')
  s.add_development_dependency('rails', '>= 5.2', '< 8')
  s.add_development_dependency('rake', '>= 12.0')
  s.add_development_dependency('rspec', '~> 3.6')
  s.add_development_dependency('rubocop', '~> 1.33.0')
  s.add_development_dependency('rubocop-packaging', '~> 0.5.2')
  s.add_development_dependency('rubocop-performance', '~> 1.17.0')
  s.add_development_dependency('rubocop-rspec', '~> 2.16.0')
  s.add_development_dependency('sqlite3', '~> 1.3')

  # For Documentation:
  s.add_development_dependency('yard', '~> 0.9.10')
```

### Did you try upgrading rubygems & bundler?

They are already very new versions
```
[18:49:30] luke@luke-ubuntu:~/Code/cucumber-rails$ gem -v
3.4.13
[18:49:41] luke@luke-ubuntu:~/Code/cucumber-rails$ bundler -v
Bundler version 2.4.18
```
-->

### Post steps to reproduce the problem

Run `bundle`. It just does nothing, it just hangs

### Which command did you run?

`bundle --verbose`

### What were you expecting to happen?

It to bundle or give me an error

### What actually happened?

After about 5 mins I gave up

```
Found no changes, using resolution from the lockfile
The definition is missing ["aruba-2.2.0", "rails-7.0.8", "rubocop-1.33.0", "rubocop-packaging-0.5.2", "rubocop-rspec-2.16.0", "sqlite3-1.6.6-x86_64-linux", "capybara-3.39.2", "railties-7.0.8", "activesupport-7.0.8", "actioncable-7.0.8", "actionmailbox-7.0.8", "actionmailer-7.0.8", "actionpack-7.0.8", "actiontext-7.0.8", "actionview-7.0.8", "activejob-7.0.8", "activemodel-7.0.8", "activerecord-7.0.8", "activestorage-7.0.8", "parser-3.2.2.4", "unicode-display_width-2.5.0", "nokogiri-1.15.4-x86_64-linux", "zeitwerk-2.6.12", "nio4r-2.5.9", "websocket-driver-0.7.6", "mail-2.8.1", "net-imap-0.3.7", "net-pop-0.1.2", "net-smtp-0.4.0", "rails-html-sanitizer-1.6.0", "globalid-1.2.1", "marcel-1.0.2", "ffi-1.16.2", "websocket-extensions-0.1.5", "date-3.3.3", "net-protocol-0.2.1", "timeout-0.4.0"]
HTTP GET https://index.rubygems.org/versions
HTTP 304 Not Modified https://index.rubygems.org/versions
Fetching gem metadata from https://rubygems.org/
Looking up gems ["actioncable", "actionmailbox", "actionmailer", "actionpack", "actiontext", "actionview", "activejob", "activemodel", "activerecord", "activestorage", "activesupport", "addressable", "ammeter", "appraisal", "aruba", "ast", "builder", "capybara", "concurrent-ruby", "contracts", "crass", "cucumber", "cucumber-ci-environment", "cucumber-core", "cucumber-cucumber-expressions", "cucumber-gherkin", "cucumber-html-formatter", "cucumber-messages", "cucumber-tag-expressions", "database_cleaner", "database_cleaner-active_record", "database_cleaner-core", "date", "diff-lcs", "erubi", "ffi", "globalid", "i18n", "json", "loofah", "mail", "marcel", "matrix", "method_source", "mime-types", "mime-types-data", "mini_mime", "minitest", "multi_test", "net-imap", "net-pop", "net-protocol", "net-smtp", "nio4r", "nokogiri", "parallel", "parser", "public_suffix", "racc", "rack", "rack-test", "rails", "rails-dom-testing", "rails-html-sanitizer", "railties", "rainbow", "rake", "regexp_parser", "rexml", "rspec", "rspec-core", "rspec-expectations", "rspec-mocks", "rspec-rails", "rspec-support", "rubocop", "rubocop-ast", "rubocop-packaging", "rubocop-performance", "rubocop-rspec", "ruby-progressbar", "sqlite3", "sys-uname", "thor", "timeout", "tzinfo", "unicode-display_width", "websocket-driver", "websocket-extensions", "xpath", "yard", "zeitwerk"]
Looking up gems ["celluloid", "coffee-rails", "em-hiredis", "faye-websocket", "redis", "bundler", "background_process", "childprocess", "bcat", "rdiscount", "event-bus", "culerity", "selenium-webdriver", "celerity", "uglifier", "erubis", "rails-deprecated_sanitizer", "activemodel-globalid", "memcache-client", "multi_json", "thread_safe", "base64", "bigdecimal", "connection_pool", "drb", "mutex_m", "functional-ruby", "ref", "text-format", "rack-mount", "rack-cache", "sprockets", "journey", "rack-session", "arel", "activerecord-deprecated_finders", "bcrypt-ruby", "mimemagic", "digest", "hoe", "weakling", "mini_portile", "mini_portile2", "pkg-config", "sexp_processor", "slop", "google-protobuf", "protobuf-cucumber", "treetop", "tlsmail", "polyglot", "term-ansicolor", "json_pure", "gherkin", "gherkin3", "cucumber-wire", "cucumber-expressions", "cucumber-formatter-dots", "cucumber-create-meta", "io-wait", "backports", "powerpack", "astrolabe", "tins", "jaro_winkler", "psych", "language_server-protocol", "strscan", "rubocop-capybara", "rubocop-factory_bot", "ruby_parser", "cucumber-tag_expressions", "webrat", "rspec-collection_matchers", "activeresource", "actionwebservice", "sprockets-rails", "rack-ssl", "rdoc", "irb", "rackup", "webrick"]
Looking up gems ["rubyzip", "libwebsocket", "websocket", "ZenTest", "RubyInline", "atomic", "ruby2_keywords", "redis-client", "abstract", "eventmachine", "thin", "rubyforge", "gemcutter", "therubyracer", "execjs", "text-hyphen", "timers", "facter", "celluloid-essentials", "celluloid-extras", "celluloid-fsm", "celluloid-pool", "celluloid-supervision", "dotenv", "nenv", "rspec-logsplit", "multimap", "middleware", "coffee-script", "hiredis", "spruz", "net-ftp", "sync", "trollop", "c21e", "os", "rails-observers", "activemodel-serializers-xml", "jar-dependencies", "stringio", "bcrypt", "facets", "ParseTree", "hpricot", "hike", "tilt", "reline"]
Looking up gems ["celluloid-gems", "coveralls", "daemons", "coffee-script-source", "time", "dotenv-deployment", "libv8", "SexpProcessor", "net-scp", "ruby-maven", "rake-compiler", "hitimes", "CFPropertyList", "sys-admin", "win32-api", "win32console", "win32-dir", "windows-api", "windows-pr", "win32-security", "hocon", "sys-filesystem", "io-console", "curses"]
Looking up gems ["colorize", "rest-client", "simplecov", "net-ssh", "maven-tools", "ruby-maven-libs", "configuration", "mkrf", "libxml-ruby", "test-unit", "ffi-win32-extensions"]
Looking up gems ["virtus", "simplecov-html", "docile", "lockfile", "simplecov_json_formatter", "netrc", "http-cookie", "http-accept", "needle", "jruby-pageant", "bcrypt_pbkdf", "rbnacl", "rbnacl-libsodium", "power_assert"]
Looking up gems ["descendants_tracker", "axiom-types", "coercible", "equalizer", "pattern-match", "domain_name"]
Looking up gems ["adamantium", "ice_nine", "unf"]
Looking up gems ["memoizable", "unf_ext"]
The lockfile does not have all gems needed for the current platform though, Bundler will still re-resolve dependencies
Resolving dependencies...
Found conflicts with locked dependencies. Will retry with ammeter, actionview, rspec-rails unlocked...
Found conflicts with dependencies with prereleases. Will retrying considering prereleases for Ruby, actionpack...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with ammeter, actionview, rspec-rails unlocked...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with ammeter, actionview, rspec-rails unlocked...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with activestorage, tzinfo unlocked...
Found conflicts with dependencies with prereleases. Will retrying considering prereleases for rails, activesupport...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with activemodel, tzinfo unlocked...
Found conflicts with dependencies with prereleases. Will retrying considering prereleases for activerecord...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with activejob unlocked...
Found conflicts with dependencies with prereleases. Will retrying considering prereleases for railties...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with actiontext, actionmailer, tzinfo unlocked...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with actionmailbox, actioncable, tzinfo unlocked...
Retrying resolution...
Found conflicts with locked dependencies. Will retry with activestorage, tzinfo unlocked...
Retrying resolution...
^C
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/resolver/package.rb:45:in `hash'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/partial_solution.rb:21:in `key?'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/partial_solution.rb:21:in `relation'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:87:in `block in propagate_incompatibility'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:86:in `each'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:86:in `propagate_incompatibility'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:71:in `block in propagate'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `reverse_each'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `propagate'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:42:in `work'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:58:in `solve'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/resolver.rb:73:in `solve_versions'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/resolver.rb:32:in `start'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/definition.rb:570:in `start_resolution'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/definition.rb:550:in `block in materialize'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/definition.rb:544:in `loop'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/definition.rb:544:in `materialize'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/definition.rb:200:in `specs'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/installer.rb:83:in `block in run'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/process_lock.rb:12:in `block in lock'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/process_lock.rb:9:in `open'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/process_lock.rb:9:in `lock'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/installer.rb:71:in `run'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/installer.rb:23:in `install'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/cli/install.rb:62:in `run'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/cli.rb:261:in `block in install'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/settings.rb:130:in `temporary'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/cli.rb:260:in `install'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/cli.rb:34:in `dispatch'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/cli.rb:28:in `start'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/exe/bundle:37:in `block in <top (required)>'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/share/rvm/gems/ruby-2.6.10/gems/bundler-2.4.18/exe/bundle:29:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.6.10/bin/bundle:25:in `load'
/usr/share/rvm/gems/ruby-2.6.10/bin/bundle:25:in `<main>'
```

**Comment by luke-hill** [comment]
EDIT: I haven't managed to solve "this" problem. But I did manage to mitigate it... Bear with me the steps to mitigate this were clunky.

1) Deleted Gemfile.lock
2) Downgraded several rubocop gems to previous versions.
3) Downgraded cucumber rules from 5-10 to 5-9
4) Bundled -> This worked (But was on previous ruleset)
5) Upgraded just cucumber from 5-9 to 5-10
6) Rebundled -> This worked because no gems were upgraded (I was running ruby 2.6)
7) Updated rubocop gems
8) Rebundled, some gems upgraded

Maybe gemfile.lock was buggy. But without upgrading the gems were fine? :shrug:

**Comment by deivid-rodriguez** [comment]
Could you point me to a specific revision in cucumber-rails that has this problem? I tried changing the requirements to what you wrote but everything worked fine.

**Comment by luke-hill** [comment]
It wasn't a revision, it was on a PR whilst I was upgrading. The versions are in the above snippet.

**Comment by deivid-rodriguez** [comment]
If it was a PR, can you point me to which one, and which commit had the issue. As I said, I tried with the exact requirements in the above snippet and everything worked for me.

I'm going to close this as non reproducible, but if you can provide a way for us to reproduce we'll happily look into it.

Thanks!

**Comment by luke-hill** [comment]
If you can't repro it then I don't want to waste your time. But if you're not convinced of an exit loop being present after a certain timeframe it's a worry.

I appreciate it's probably hard to repro. But is there a way you can check if after 5/10/15 loops inside the bundling it exits and says something like "Could not bundle - Code 147 :gun: "

**Comment by deivid-rodriguez** [comment]
Thanks, that's exactly what I was asking for. I still can't repro using that commit though, I get a resolution error very fast:

```
$ bundle          
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Could not find compatible versions

Because rubocop-packaging >= 0.5.2 depends on rubocop >= 1.33, < 2.0
  and Gemfile depends on rubocop ~> 1.31.0,
  rubocop-packaging >= 0.5.2 cannot be used.
So, because Gemfile depends on rubocop-packaging ~> 0.5.2,
  version solving has failed.
```

I guess it may depend on the Ruby version used?

I'll be happy to look into this or add some loop detection if it comes up again.

Thanks again.
