### ISSUE TITLE
bundler refuses to load psych under Fedora's ruby 3.2.2 package

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems#7061]
For some reason bundler is refusing to load the `psych` gem, although I can manually load it outside of bundler. This issue only occurs when using Fedora Linux's ruby 3.2.2 package (`ruby-3.2.2-180.fc38.src.rpm`).

## Steps To Reproduce

1. Create a `Gemfile`:
```ruby
source 'https://rubygems.org/'

gem 'psych'
```
2. `bundle install`
3. Double-check that `psych` can be loaded outside of bundler: `ruby -r psych -e 'p Psych::VERSION'`

### Expected Results

`psych` can be loaded under bundler.

### Actual Results

```
$ bundle install
Ignoring psych-5.1.1 because its extensions are not built. Try: gem pristine psych --version 5.1.1
Ignoring stringio-3.0.8 because its extensions are not built. Try: gem pristine stringio --version 3.0.8
Ignoring psych-5.1.1 because its extensions are not built. Try: gem pristine psych --version 5.1.1
Ignoring stringio-3.0.8 because its extensions are not built. Try: gem pristine stringio --version 3.0.8
--- ERROR REPORT TEMPLATE -------------------------------------------------------

LoadError: cannot load such file -- psych
  <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
  <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
  /usr/share/rubygems/rubygems.rb:608:in `load_yaml'
  /usr/share/rubygems/rubygems/config_file.rb:346:in `load_file'
  /usr/share/rubygems/rubygems/config_file.rb:189:in `initialize'
  /usr/share/rubygems/rubygems.rb:329:in `new'
  /usr/share/rubygems/rubygems.rb:329:in `configuration'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/fetcher.rb:244:in `connection'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/fetcher.rb:90:in `initialize'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/source/rubygems.rb:257:in `new'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/source/rubygems.rb:257:in `block in fetchers'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/source/rubygems.rb:255:in `map'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/source/rubygems.rb:255:in `fetchers'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/source/rubygems.rb:399:in `block in remote_specs'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/index.rb:9:in `build'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/source/rubygems.rb:398:in `remote_specs'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/source/rubygems.rb:132:in `specs'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/spec_set.rb:205:in `map!'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/spec_set.rb:205:in `specs_for_dependency'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/spec_set.rb:34:in `block in for'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/spec_set.rb:22:in `loop'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/spec_set.rb:22:in `for'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/spec_set.rb:85:in `materialize'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/definition.rb:523:in `materialize'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/definition.rb:200:in `specs'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/installer.rb:83:in `block in run'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/process_lock.rb:12:in `block in lock'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/process_lock.rb:9:in `open'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/process_lock.rb:9:in `lock'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/installer.rb:71:in `run'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/installer.rb:23:in `install'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/cli/install.rb:62:in `run'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/cli.rb:261:in `block in install'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/settings.rb:131:in `temporary'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/cli.rb:260:in `install'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.15/exe/bundle:29:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'

## Environment

Bundler       2.4.15
  Platforms   ruby, x86_64-linux
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux]
  Full Path   /usr/bin/ruby
  Config Dir  /etc
RubyGems      3.4.10
  Gem Home    /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0
  Gem Path    /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0
  User Home   /home/postmodern
  User Path   /home/postmodern/.gem/ruby
  Bin Dir     /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.2.0/bin
OpenSSL       
  Compiled    OpenSSL 3.0.8 7 Feb 2023
  Loaded      OpenSSL 3.0.9 30 May 2023
  Cert File   /etc/pki/tls/cert.pem
  Cert Dir    /etc/pki/tls/certs
Tools         
  Git         2.41.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9

## Bundler Build Metadata

Built At          2023-06-29
Git SHA           702f922bf2
Released Version  true

## Bundler settings

path
  Set for the current user (/home/postmodern/.bundle/config): "vendor/bundle"

## Gemfile

### Gemfile

source 'https://rubygems.org/'

gem 'psych'

### Gemfile.lock

GEM
  remote: https://rubygems.org/
  specs:
    psych (5.1.1)
      stringio
    stringio (3.0.8)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  psych

BUNDLED WITH
   2.4.15

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=cannot+load+such+file+--+psych&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
```

Confirming that the `psych` gem can be loaded outside of bundler:

```
$ ruby -r psych -e 'p Psych::VERSION'
"5.1.0"
````

### Additional Information

```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ which ruby
/usr/bin/ruby
$ which bundle
/usr/local/bin/bundle
```

**Comment by postmodern** [comment]
Appears that `psych-5.1.0` is installed into `/usr/local/share/gems/`.

```
$ ruby -r psych -e 'puts $LOADED_FEATURES.grep(/psych/)'
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/versions.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/exception.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/syntax_error.rb
/usr/local/lib64/gems/ruby/psych-5.1.0/psych.so
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/omap.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/set.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/class_loader.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/scalar_scanner.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes/node.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes/stream.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes/document.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes/sequence.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes/scalar.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes/mapping.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes/alias.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/nodes.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/streaming.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/visitors/visitor.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/visitors/to_ruby.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/visitors/emitter.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/handler.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/tree_builder.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/visitors/yaml_tree.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/json/ruby_events.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/visitors/json_tree.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/visitors/depth_first.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/visitors.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/parser.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/coder.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/core_ext.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/stream.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/json/yaml_events.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/json/tree_builder.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/json/stream.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych/handlers/document_stream.rb
/usr/local/share/gems/gems/psych-5.1.0/lib/psych.rb
```

**Comment by postmodern** [comment]
Appears that somehow `/usr/share/gems/gems/psych-5.0.1/lib/psych` got removed (likely when running `sudo gem pristin psych` or `sudo gem update psych`). Running `sudo dnf reinstall rubygem-psych` re-installed the "bundled" psych gem. Now bundler can load psych and proceed normally:

```
$ bundle i
Ignoring psych-5.1.1 because its extensions are not built. Try: gem pristine psych --version 5.1.1
Ignoring stringio-3.0.8 because its extensions are not built. Try: gem pristine stringio --version 3.0.8
Fetching gem metadata from https://rubygems.org/........
Using bundler 2.4.15
Installing stringio 3.0.8 with native extensions
Installing psych 5.1.1 with native extensions
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```
