### ISSUE TITLE
lib/rubygems/util.rb:104 glob_files_in_dir - <internal:dir>:411:in glob: File name too long - (Errno::ENAMETOOLONG)

### ISSUE THREAD

**Issue by junaruga** [rubygems/rubygems#7132]
### Describe the problem as clearly as you can

When running `make test-all` in ruby/ruby's Travis CI arm32 case (emulation environment by `setarch linux32 --verbose --32bit` on Ubuntu Jammy arm64, I got the following error `<internal:dir>:411:in glob: File name too long - ... (Errno::ENAMETOOLONG) ...` at the push trigger of the commit ruby/ruby@35da6f864a05624433be2c8059b87d30b899b370.

The setting for the arm32 emulation on the arm64 is a bit complicated. But I assume that the arm32 environment things are not related to this issue.

I had never seen this issue in ruby/ruby CI until today. So, my guess is that this issue can happen quite rarely.

Sorry for a lack of the reproducing steps. My intention to report here is you may have ideas to avoid this issue from the following tracing log information.

https://app.travis-ci.com/github/ruby/ruby/jobs/612698429#L136

```
...
$ $SETARCH make -s test-all RUBYOPT="-w"
+ setarch linux32 --verbose --32bit make -s test-all RUBYOPT=-w
Switching on ADDR_LIMIT_32BIT.
...
Run options: 
  --seed=43690
  "--ruby=./miniruby -I../lib -I. -I.ext/common  ../tool/runruby.rb --extout=.ext  -- --disable-gems"
  --excludes-dir=../test/.excludes
  --name=!/memory_leak/
  -j3
  -q
  --tty=no
...
[876/903] 58763=test_word
<internal:dir>:411:in `glob': File name too long - /home/travis/build/ruby/ruby/build/tmp/test_rubygems_20231103-58763-wqj5wo/tmp/test_rubygems_20231103-58763-uozw4x/tmp/test_rubygems_20231103-58763-aynilx/tmp/test_rubygems_20231103-58763-uig8qn/tmp/test_rubygems_20231103-58763-qk9jwm/tmp/test_rubygems_20231103-58763-bqnh8u/tmp/test_rubygems_20231103-58763-wh60wp/tmp/test_rubygems_20231103-58763-azzl/tmp/test_rubygems_20231103-58763-j4ko76/tmp/test_rubygems_20231103-58763-6cmvsx/tmp/test_rubygems_20231103-58763-pbtdpq/tmp/test_rubygems_20231103-58763-g8jvr5/tmp/test_rubygems_20231103-58763-dbuk7i/tmp/test_rubygems_20231103-58763-ugq6z1/tmp/test_rubygems_20231103-58763-68jwjn/tmp/test_rubygems_20231103-58763-d0wx0e/tmp/test_rubygems_20231103-58763-5rb6pe/tmp/test_rubygems_20231103-58763-928gqr/tmp/test_rubygems_20231103-58763-9bu1hw/tmp/test_rubygems_20231103-58763-7jgp2l/tmp/test_rubygems_20231103-58763-vmnfpf/tmp/test_rubygems_20231103-58763-ihfgax/tmp/test_rubygems_20231103-58763-chv5j6/tmp/test_rubygems_20231103-58763-r5v93t/tmp/test_rubygems_20231103-58763-4fo642/tmp/test_rubygems_20231103-58763-t32695/tmp/test_rubygems_20231103-58763-6fhnv8/tmp/test_rubygems_20231103-58763-pnofcc/tmp/test_rubygems_20231103-58763-9s8lwn/tmp/test_rubygems_20231103-58763-92rmuk/tmp/test_rubygems_20231103-58763-pz32h0/tmp/test_rubygems_20231103-58763-61h0pn/tmp/test_rubygems_20231103-58763-mp74jh/tmp/test_rubygems_20231103-58763-ltgjkh/tmp/test_rubygems_20231103-58763-pmxtdi/tmp/test_rubygems_20231103-58763-b86fnv/tmp/test_rubygems_20231103-58763-7t7krx/tmp/test_rubygems_20231103-58763-lrfy00/tmp/test_rubygems_20231103-58763-wya3jq/tmp/test_rubygems_20231103-58763-br3he5/tmp/test_rubygems_20231103-58763-tszp4s/tmp/test_rubygems_20231103-58763-vmp7vq/tmp/test_rubygems_20231103-58763-vjajkg/tmp/test_rubygems_20231103-58763-n7upjp/tmp/test_rubygems_20231103-58763-11oq7x/tmp/test_rubygems_20231103-58763-4bb9ir/tmp/test_rubygems_20231103-58763-7z6pbc/tmp/test_rubygems_20231103-58763-y1oo34/tmp/test_rubygems_20231103-58763-yqawwb/tmp/test_rubygems_20231103-58763-9cwwk9/tmp/test_rubygems_20231103-58763-1pkzam/tmp/test_rubygems_20231103-58763-pv6n3r/tmp/test_rubygems_20231103-58763-lwhmgn/tmp/test_rubygems_20231103-58763-rhj0o8/tmp/test_rubygems_20231103-58763-ybfwp2/tmp/test_rubygems_20231103-58763-e76zks/tmp/test_rubygems_20231103-58763-7uys5s/tmp/test_rubygems_20231103-58763-fbds23/tmp/test_rubygems_20231103-58763-hleiyi/tmp/test_rubygems_20231103-58763-cqc0s4/tmp/test_rubygems_20231103-58763-74boys/tmp/test_rubygems_20231103-58763-sixvbm/tmp/test_rubygems_20231103-58763-kvpik5/tmp/test_rubygems_20231103-58763-luxmd7/tmp/test_rubygems_20231103-58763-tb291n/tmp/test_rubygems_20231103-58763-6rfv5y/tmp/test_rubygems_20231103-58763-ma1f9i/tmp/test_rubygems_20231103-58763-p0nwt9/tmp/test_rubygems_20231103-58763-vr401t/tmp/test_rubygems_20231103-58763-ym4i2p/tmp/test_rubygems_20231103-58763-d0l1xz/tmp/test_rubygems_20231103-58763-3g7g22/tmp/test_rubygems_20231103-58763-cdr1hi/tmp/test_rubygems_20231103-58763-t3h4n7/tmp/test_rubygems_20231103-58763-ilpboj/tmp/test_rubygems_20231103-58763-fk1b3u/tmp/test_rubygems_20231103-58763-bplwla/tmp/test_rubygems_20231103-58763-1jd58z/tmp/test_rubygems_20231103-58763-ejti3i/tmp/test_rubygems_20231103-58763-5frphu/tmp/test_rubygems_20231103-58763-r3j2nn/tmp/test_rubygems_20231103-58763-dumjga/tmp/test_rubygems_20231103-58763-ulchms/tmp/test_rubygems_20231103-58763-7edhfp/tmp/test_rubygems_20231103-58763-3gx9e1/tmp/test_rubygems_20231103-58763-oecldk/tmp/test_rubygems_20231103-58763-uik6dx/tmp/test_rubygems_20231103-58763-5aeost/tmp/test_rubygems_20231103-58763-jszuih/tmp/test_rubygems_20231103-58763-85jsrh/tmp/test_rubygems_20231103-58763-k1rxq8/tmp/test_rubygems_20231103-58763-bytd8d/tmp/test_rubygems_20231103-58763-i4gxze/tmp/test_rubygems_20231103-58763-jczqvh/tmp/test_rubygems_20231103-58763-jp9ns6/tmp/test_rubygems_20231103-58763-4g1ns7/tmp/test_rubygems_20231103-58763-6r2uwk/tmp/test_rubygems_20231103-58763-ayp78r/tmp/test_rubygems_20231103-58763-j3ntv4/tmp/test_rubygems_20231103-58763-9mn7jn/tmp/test_rubygems_20231103-58763-8z9cvo/gemhome/specifications/default (Errno::ENAMETOOLONG)
  /home/travis/build/ruby/ruby/lib/rubygems/util.rb:104:in `glob_files_in_dir'
  /home/travis/build/ruby/ruby/lib/rubygems/specification.rb:784:in `gemspec_stubs_in'
  /home/travis/build/ruby/ruby/lib/rubygems/specification.rb:830:in `default_stubs'
  /home/travis/build/ruby/ruby/lib/rubygems/specification.rb:856:in `stubs_for_pattern'
  /home/travis/build/ruby/ruby/lib/rubygems/specification.rb:817:in `stubs'
  /home/travis/build/ruby/ruby/lib/rubygems/specification.rb:1033:in `find_by_path'
  /home/travis/build/ruby/ruby/lib/rubygems.rb:199:in `try_activate'
  <internal:/home/travis/build/ruby/ruby/lib/rubygems/core_ext/kernel_require.rb>:131:in `block in require'
  <internal:/home/travis/build/ruby/ruby/lib/rubygems/core_ext/kernel_require.rb>:131:in `synchronize'
  <internal:/home/travis/build/ruby/ruby/lib/rubygems/core_ext/kernel_require.rb>:131:in `rescue in require'
  <internal:/home/travis/build/ruby/ruby/lib/rubygems/core_ext/kernel_require.rb>:127:in `require'
  /home/travis/build/ruby/ruby/test/win32ole/test_word.rb:6:in `<top (required)>'
  <internal:/home/travis/build/ruby/ruby/lib/rubygems/core_ext/kernel_require.rb>:128:in `require'
  <internal:/home/travis/build/ruby/ruby/lib/rubygems/core_ext/kernel_require.rb>:128:in `require'
  /home/travis/build/ruby/ruby/tool/lib/test/unit/parallel.rb:122:in `run'
  /home/travis/build/ruby/ruby/tool/lib/test/unit/parallel.rb:215:in `<main>'
running file: /home/travis/build/ruby/ruby/test/win32ole/test_word.rb

A test worker crashed. It might be an interpreter bug or
a bug in test/unit/parallel.rb. Try again without the -j
option.

make: *** [uncommon.mk:942: yes-test-all] Error 1
```

### Did you try upgrading RubyGems?

Sorry, I haven't tried upgrading RubyGems. Because this issue can quite rarely happen.

### Post steps to reproduce the problem

```
$ ./autogen.sh
$ ./configure
$ make -jN test-all
```

### Which command did you run?

```
$ export debugflags=-ggdb3
$ export RUBY_TESTOPTS="-j3 -q --tty=no"
$ export SETARCH='setarch linux32 --verbose --32bit'
$ export optflags=-O1
$ sudo -E apt-get $travis_apt_get_options install
  crossbuild-essential-armhf
  libc6:armhf
  libstdc++-10-dev:armhf
  libffi-dev:armhf
  libncurses-dev:armhf
  libncursesw5-dev:armhf
  libreadline-dev:armhf
  libssl-dev:armhf
  libyaml-dev:armhf
  linux-libc-dev:armhf
  zlib1g-dev:armhf
$ ./autogen.sh
$ $SETARCH ../configure -C --disable-install-doc --prefix=$(pwd)/install
$ $SETARCH make -s $JOBS
$ $SETARCH make -s test
$ $SETARCH make -s test-all RUBYOPT="-w"
```

### What were you expecting to happen?

I was expecting the `Errno::ENAMETOOLONG` error didn't happen.

### What actually happened?

The `Errno::ENAMETOOLONG` error happened at the following lines.

```
/tmp/test_rubygems_20231103-58763-8z9cvo/gemhome/specifications/default (Errno::ENAMETOOLONG)
  /home/travis/build/ruby/ruby/lib/rubygems/util.rb:104:in `glob_files_in_dir'
  /home/travis/build/ruby/ruby/lib/rubygems/specification.rb:784:in `gemspec_stubs_in'
```

The code is below.

https://github.com/ruby/ruby/blob/35da6f864a05624433be2c8059b87d30b899b370/lib/rubygems/util.rb#L104

### Run `gem env` and paste the output below

```

$SETARCH $(pwd)/install/bin/gem env
Switching on ADDR_LIMIT_32BIT.
Execute command `/home/travis/build/junaruga/ruby/build/install/bin/gem'.
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
Ignoring executable-hooks-1.6.1 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.1
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring rbs-2.1.0 because its extensions are not built. Try: gem pristine rbs --version 2.1.0
Error loading RubyGems plugin "/home/travis/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/plugins/executable-hooks_plugin.rb": cannot load such file -- executable-hooks/wrapper (LoadError)
Error loading RubyGems plugin "/home/travis/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/plugins/gem-wrappers_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.0.dev
  - RUBY VERSION: 3.3.0 (2023-11-03 patchlevel -1) [armv8l-linux-eabihf]
  - INSTALLATION DIRECTORY: /home/travis/.rvm/gems/ruby-3.1.2
  - USER INSTALLATION DIRECTORY: /home/travis/.local/share/gem/ruby/3.3.0+0
  - RUBY EXECUTABLE: /home/travis/build/junaruga/ruby/build/install/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/travis/.rvm/gems/ruby-3.1.2/bin
  - SPEC CACHE DIRECTORY: /home/travis/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/travis/build/junaruga/ruby/build/install/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - armv8l-linux-eabihf
  - GEM PATHS:
     - /home/travis/.rvm/gems/ruby-3.1.2
     - /home/travis/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/travis/bin
     - /home/travis/.local/bin
     - /home/travis/.rvm/gems/ruby-3.1.2/bin
     - /home/travis/.rvm/gems/ruby-3.1.2@global/bin
     - /home/travis/.rvm/rubies/ruby-3.1.2/bin
     - /home/travis/.phpenv/shims
     - /home/travis/perl5/perlbrew/bin
     - /home/travis/.nvm/versions/node/v8.12.0/bin
     - /home/travis/.kiex/elixirs/elixir-1.15.4/bin
     - /opt/ant/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
     - /home/travis/.phpenv/bin
     - /home/travis/.rvm/bin
```

**Comment by deivid-rodriguez** [comment]
I threw some guess at this issue at #7152.
