### ISSUE TITLE
Issues when Ruby installed through brew formula

### ISSUE THREAD

**Issue by suleymantemiz** [rubygems/rubygems#7136]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::GemNotFoundException: can't find gem bundler (= 2.4.21) with executable bundle
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems.rb:264:in `find_spec_for_exe'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems.rb:244:in `bin_path'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/rubygems_integration.rb:178:in `bin_path'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:20:in `run'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:492:in `exec'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
  /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
  /usr/local/opt/ruby/bin/bundle:25:in `load'
  /usr/local/opt/ruby/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.21
  Platforms   ruby, x86_64-darwin-22
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-darwin-22]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/3.2.2_1/etc
RubyGems      3.4.21
  Gem Home    /usr/local/lib/ruby/gems/3.2.0
  Gem Path    /Users/macbook/.gem/ruby/3.2.0:/usr/local/lib/ruby/gems/3.2.0:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/gems/3.2.0
  User Home   /Users/macbook
  User Path   /Users/macbook/.gem/ruby/3.2.0
  Bin Dir     /usr/local/lib/ruby/gems/3.2.0/bin
Tools         
  Git         2.39.3 (Apple Git-145)
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
Gem.ruby      /usr/local/opt/ruby/bin/ruby
bundle #!     /usr/local/Cellar/ruby/3.2.2_1/bin/ruby

```

## Bundler Build Metadata

```
Built At          2023-10-17
Git SHA           d10b46bd15
Released Version  true
```

## Bundler settings

```
force_ruby_platform
  Set for your local app (/Users/macbook/Desktop/AwesomeProject/DemoProject/.bundle/config): true
path
  Set for your local app (/Users/macbook/Desktop/AwesomeProject/DemoProject/.bundle/config): "vendor/bundle"
```

### ../Gemfile

```ruby
source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

gem 'cocoapods', '~> 1.13'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
```

### ../Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.6)
      rexml
    activesupport (7.0.8)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    atomos (0.1.3)
    claide (1.1.0)
    cocoapods (1.14.2)
      addressable (~> 2.8)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.14.2)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.6.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.8.0)
      nap (~> 1.0)
      ruby-macho (>= 2.3.0, < 3.0)
      xcodeproj (>= 1.23.0, < 2.0)
    cocoapods-core (1.14.2)
      activesupport (>= 5.0, < 8)
      addressable (~> 2.8)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix (~> 4.0)
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (2.0)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.6.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored2 (3.1.2)
    concurrent-ruby (1.2.2)
    escape (0.0.4)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    ffi (1.16.3)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    httpclient (2.8.3)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    json (2.6.3)
    minitest (5.20.0)
    molinillo (0.8.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    netrc (0.11.0)
    public_suffix (4.0.7)
    rexml (3.2.6)
    ruby-macho (2.5.1)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    xcodeproj (1.23.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport (>= 6.1.7.3, < 7.1.0)
  cocoapods (~> 1.13)

RUBY VERSION
   ruby 3.2.2p53

BUNDLED WITH
   2.4.21
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by martinemde** [comment]
Did you already try `gem install bundler --version "2.4.21"`?

**Comment by suleymantemiz** [comment]
@martinemde  I install  gem install bundler --version "2.4.21" and it is successfull but again errors.

**Comment by theomelo** [comment]
Did you try this?
```bash
gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
```

From: https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html

**Comment by deivid-rodriguez** [comment]
It seems that your rubygems installation is messed up.

I assumed you installed Ruby with `brew install ruby` and then how did you upgrade rubygems? `gem update --system`? It seems like you upgraded rubygems, but for some reason `/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/gems/3.2.0/specifications/default/bundler-2.4.21.gemspec` is not there, when it should.

**Comment by Bo98** [comment]
Can you confirm if `gem update --system` is something you did indeed do? If you have steps to reproduce from a clean install let me know and I can look into it.

Updating system RubyGems isn't something we actively test over in the Homebrew formula, so it could well be broken and need fixing (or potentially even blocking via `disable_system_update_message`).

Similarly for Bundler, we do support custom installs but at the caveat that we uninstall Bundler when upgrading Ruby, but that currently happens only from `/usr/local/lib/ruby/gems` and not `/usr/local/lib/ruby/site_ruby` - so maybe there's more to cover here if site_ruby installs can be broken easily.
