### ISSUE TITLE
Arbitrary SSL certificate verification failure for rubygems.org (using bundler) 

### ISSUE THREAD

**Issue by nayden** [rubygems/rubygems#714]
I am getting an arbitrary failure when installing gems from rubygems.org. 
The error is
Bundler::Fetcher::CertificateFailureError: Could not verify the SSL certificate for https://rubygems.org/.

I have found a number of the workarounds
http://railsapps.github.io/openssl-certificate-verify-failed.html
https://trello.com/c/e1hCBFMw/22-bundler-fetcher-certificatefailureerror-could-not-verify-the-ssl-certificate-for-https-rubygems-org
http://help.rubygems.org/discussions/problems/11197-sporadic-ssl-errors

Although these suggestions are helpful in building individual packages (most of the time), I am still getting arbitrary failures. 

My build system is CentOS 6.4 with the latest distro version of openssl and ca-certificates (RHEL SSL certificates package).

I also tried replacing the RHEL ca bundle with the one provided by the curl folks from
http://curl.haxx.se/docs/caextract.html
but this didn't fix the problem. 

I originally noticed this issue when our CI was arbitrary failing to build packages that would most of the time successfully build. My initial thought was that there was an inconsistency with the environment on the different build boxes so I decided to rebuild the same package on the same host a number of times.  After a quick bash for loop I noticed that out of 20 times the package rebuild failed twice, in two subsequent builds with the rubygems.org SSL error. 

This was very puzzling.  All builds were done on the same host. No other user was logged in on the host at that time. The environment was kept the same throughout the builds. Some of the gems were successfully installed by 'bundle install'. This condition is reproducible, although not predictably.  
Is it possible that the rubygems.org back end servers are having different SSL certs?  If that is the case is it possible that (from time to time) I am querying a back-end server for which I don't have an SSL cert in my ca-bunldes (RHEL and CURL). 

```
Fetching source index from https://rubygems.org/
Installing amq-protocol (1.0.1) 
Installing eventmachine (1.0.0) 
Installing amq-client (1.0.0.pre2) 
Installing amqp (1.0.0.pre2) 

Bundler::Fetcher::CertificateFailureError: Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
An error occurred while installing beefcake (0.3.7), and Bundler cannot
continue.
Make sure that `gem install beefcake -v '0.3.7'` succeeds before bundling.
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/utils.rb:21:in `sh': Command failed with status (5): [/opt/fire/embedded/bin/bundle install --path=bundled_gems --binstubs=bin]. (RuntimeError)
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/software.rb:71:in `block in build'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/software.rb:70:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/software.rb:70:in `build'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/tasks.rb:29:in `block (2 levels) in task_build'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/tasks.rb:29:in `chdir'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/tasks.rb:29:in `block in task_build'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:205:in `call'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:200:in `each'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `each'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `each'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
    from ./solo-fireamp:47:in `<main>'
Rebuilding package: synthetic_events

-------------------------

I, [2013-11-15T13:55:10.506846 #23702]  INFO -- : Executing: [/opt/fire/embedded/bin/bundle install --path=bundled_gems --binstubs=bin]
Fetching source index from https://rubygems.org/
Installing amq-protocol (1.0.1) 
Installing eventmachine (1.0.0) 
Installing amq-client (1.0.0.pre2) 
Installing amqp (1.0.0.pre2) 
Installing beefcake (0.3.7) 
Installing bson (1.8.1) 
Installing bson_ext (1.8.1) 
Installing builder (3.1.4) 
Installing daemons (1.1.9) 
Installing dalli (2.6.0) 
Installing diff-lcs (1.1.3) 
Installing em-synchrony (1.0.2) 
Installing i18n (0.6.1) 
Installing innertube (1.0.2) 
Installing janus_events (2.2.0) 
Installing mongo (1.8.1) 
Installing multi_json (1.5.0) 
Installing mysql2 (0.3.11) 
Installing rack (1.4.3) 
Installing rack-fiber_pool (0.9.2) 
Installing riak-client (1.1.1) 
Installing rspec-core (2.12.2) 

Bundler::Fetcher::CertificateFailureError: Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
An error occurred while installing rspec-expectations (2.12.1), and Bundler
cannot continue.
Make sure that `gem install rspec-expectations -v '2.12.1'` succeeds before
bundling.
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/utils.rb:21:in `sh': Command failed with status (5): [/opt/fire/embedded/bin/bundle install --path=bundled_gems --binstubs=bin]. (RuntimeError)
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/software.rb:71:in `block in build'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/software.rb:70:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/software.rb:70:in `build'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/tasks.rb:29:in `block (2 levels) in task_build'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/tasks.rb:29:in `chdir'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bunchr-0.2.1/lib/bunchr/tasks.rb:29:in `block in task_build'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:205:in `call'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:200:in `each'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `each'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `each'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
    from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
    from ./solo-fireamp:47:in `<main>'
```

**Comment by allthesignals** [comment]
I'm having this same issue what feels like over and over again. I was able to develop just fine until now. Is it my network? I'm not sure. Any thoughts would be helpful. Same error, here's the `gem install -V`:


```
MacBook-Air% gem install -V semantic-ui-sass
ERROR:  Could not find a valid gem 'semantic-ui-sass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```

**Comment by pboettcher** [comment]
I experience

Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/

because we have enterprise Sophos firewall and I must somehow install Sophos certificate into gem system so that bundler will use it. How to do this?

**Comment by colby-swandale** [comment]
@pboettcher you will have to consult your OS's documentation on how to install a certificate into your your OS's certificate store.
