### ISSUE TITLE
package metadata is missing in .../vendor/cache/actioncable-7.0.8.gem

### ISSUE THREAD

**Issue by ShadSterling** [rubygems/rubygems#7171]
### Which command did you run?

bundle update --all

### What were you expecting to happen?

Any outdated dependencies would be updated

### What actually happened?

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::Package::FormatError: package metadata is missing in /Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/vendor/cache/actioncable-7.0.8.gem
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:693:in `verify_files'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:620:in `block (2 levels) in verify'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:23:in `new'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:617:in `block in verify'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package/file_source.rb:30:in `open'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:616:in `verify'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:597:in `spec'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/rubygems_integration.rb:208:in `spec_from_gem'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:387:in `block in cached_specs'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:386:in `each'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:386:in `cached_specs'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/source/rubygems.rb:135:in `specs'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:41:in `block in setup_solver'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:240:in `all_versions_for'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:57:in `block in setup_solver'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:159:in `versions_for'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:382:in `block in prepare_dependencies'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:377:in `each'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:377:in `map'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:377:in `prepare_dependencies'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:61:in `setup_solver'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/resolver.rb:28:in `start'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:570:in `start_resolution'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:301:in `resolve'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:523:in `materialize'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:200:in `specs'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:83:in `block in run'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/process_lock.rb:12:in `block in lock'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/process_lock.rb:9:in `open'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/process_lock.rb:9:in `lock'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:71:in `run'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/installer.rb:23:in `install'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/update.rb:79:in `run'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:311:in `block in update'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/settings.rb:142:in `temporary'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:310:in `update'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/sxs5ith/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
  /Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/bin/bundle:108:in `load'
  /Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/bin/bundle:108:in `<main>'

```

## Environment

```
Bundler       2.4.21
  Platforms   ruby, arm64-darwin-23
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [arm64-darwin-23]
  Full Path   /Users/sxs5ith/.rbenv/versions/3.2.2/bin/ruby
  Config Dir  /Users/sxs5ith/.rbenv/versions/3.2.2/etc
RubyGems      3.4.21
  Gem Home    /Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/vendor_bundle/ruby/3.2.0
  Gem Path    /Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/vendor_bundle/ruby/3.2.0
  User Home   /Users/sxs5ith
  User Path   /Users/sxs5ith/.local/share/gem/ruby/3.2.0
  Bin Dir     /Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/vendor_bundle/ruby/3.2.0/bin
OpenSSL       
  Compiled    OpenSSL 3.1.4 24 Oct 2023
  Loaded      OpenSSL 3.1.4 24 Oct 2023
  Cert File   /opt/homebrew/etc/openssl@3/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@3/certs
Tools         
  Git         2.42.1
  RVM         not installed
  rbenv       rbenv 1.2.0-80-gd6bb1c6
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-10-17
Git SHA           d10b46bd15
Released Version  true
```

## Bundler settings

```
bin
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): ".bundle/bin"
cache_all
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): true
cache_all_platforms
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): true
clean
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): true
gemfile
  Set via BUNDLE_GEMFILE: "/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/Gemfile"
jobs
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): 4
path
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): "vendor_bundle"
retry
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): 4
rubygems.artifactory.homedepot.com
  Set via BUNDLE_RUBYGEMS__ARTIFACTORY__HOMEDEPOT__COM: "sxs5ith:[REDACTED]"
with
  Set for your local app (/Users/sxs5ith/Library/CloudStorage/OneDrive-TheHomeDepot/Documents/Repositories/pec/.bundle/config): [:deployed]
```

### Gemfile

```ruby
#!/usr/bin/env ruby
# encoding: UTF-8
# warnings: all
# immutable: string
$VERBOSE = true
$INTERACTIVE = $stdin.isatty && $stdout.isatty

$_______load_tag_depth_______ ||= 1; $stderr.puts "-=≡  #{Process.pid.to_s.rjust 5}  #{(">"*$_______load_tag_depth_______).ljust 5}  #{__FILE__.inspect.ljust 146}  ≡=-"; $_______load_tag_depth_______ += 1
$stderr.puts "#{__FILE__}:#{__LINE__}: warning: direct execution of Gemfile" if $0 == __FILE__

fn = "(file-scope)»Gemfile"
$stderr.puts "[#{Time.now}] #{fn}: Running #{$0.inspect} with #{ARGV.inspect} in #{ENV["RAILS_ENV"].inspect}"


##  Baseline
source File.read( File.join( __dir__, ".gem-source" ) ).chomp  ##  Shared URL also used by cicd/toolchain  ##  Credentials MUST be configured in gem configuration; scripts use cicd/artifactory to update
ruby File.read File.join( __dir__, ".ruby-version" ), engine: "ruby"  ##  Match version available when deployed
gem "bundler", File.read( File.join( __dir__, ".bundler-version" ) )  ##  Match version available when deployed
gem "bundle"


##  Core
gem "rails", "<7.1"
gem "rspec-rails"  ##  Used by PCF buildpack  ##  TODO: what tasks does the buildpack run?
gem "rspec-mocks"

##  Server stack
gem "puma"
gem "rack-timeout"

##  Frontend
gem "importmap-rails"
gem "sass-rails"  ##  TODO: replace this with something that doesn't require sprockets, such as cssbundling-rails with dartsass-rails - https://github.com/rails/cssbundling-rails , https://github.com/rails/dartsass-rails

##  Job management
gem "sidekiq"
gem "sidekiq-enqueuer"
gem "sidekiq-scheduler"

##  Client libraries
gem "httparty"
gem "ruby-kafka"

# Web
gem "cf-app-utils"
gem "responders"
gem "health_check"
gem "react-rails"
gem "nokogiri"
gem "json-jwt"

# Database
gem "mysql2"

# Logging & Stats
gem "lograge"

##  Helpers
gem "business_time"
gem "immutable-struct"
gem "rounding"

##  Shims
gem "sorted_set"  ##  Removed from stdlib; See https://stackoverflow.com/questions/68208165


##  Pro-eCommerce has these environments:
##    none:        tasks that need autoloaded dependencies but don't use PeC code
##    test:        automated tests
##    local:       running on development workstations
##    development: branches deployed during development
##    staging:     staging branch autodeployed
##    production:  production branch after approvals

group :test do
        gem "capybara"
        gem "capybara-screenshot"
        gem "factory_bot_rails"
        gem "ffaker"
        gem "poltergeist"
        gem "rails-controller-testing"
        gem "rspec-its"
        gem "rspec_junit_formatter"
        gem "shoulda-matchers"
        gem "simplecov", require: false
        gem "sinatra"
        gem "timecop"
        gem "webmock"
end

group :test, :local do  ##  TODO: include one gem group in another, e.g. include local group in test group
        gem "brakeman", require: false
        gem "bundler-audit"
        gem "byebug"
        gem "colorize"
        gem "dotenv-rails"
        gem "hirb"
        gem "letter_opener"
        gem "pry-byebug"
        gem "pry-rails"
        gem "pry-stack_explorer"
        gem "rbs"
        gem "typeprof"
        gem "webrick"
end

group :local do
        gem "rubocop", require: false
        gem "rufo", require: false
        gem "solargraph", require: false
end

group :development, :staging do
        gem "web-console"
end

group :production do
end


##  Enable null update to use with `bundle update --bundler --ruby`
group :none do; end


$_______load_tag_depth_______ -= 1; $stderr.puts "-=≡  #{Process.pid.to_s.rjust 5}  #{("<"*$_______load_tag_depth_______).ljust 5}  #{__FILE__.inspect.ljust 146}  ≡=-"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.artifactory.homedepot.com/artifactory/api/gems/gems-remote/
  specs:
    actioncable (7.0.8)
      actionpack (= 7.0.8)
      activesupport (= 7.0.8)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.8)
      actionpack (= 7.0.8)
      activejob (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.8)
      actionpack (= 7.0.8)
      actionview (= 7.0.8)
      activejob (= 7.0.8)
      activesupport (= 7.0.8)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.8)
      actionview (= 7.0.8)
      activesupport (= 7.0.8)
      rack (~> 2.0, >= 2.2.4)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.8)
      actionpack (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.8)
      activesupport (= 7.0.8)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.8)
      activesupport (= 7.0.8)
      globalid (>= 0.3.6)
    activemodel (7.0.8)
      activesupport (= 7.0.8)
    activerecord (7.0.8)
      activemodel (= 7.0.8)
      activesupport (= 7.0.8)
    activestorage (7.0.8)
      actionpack (= 7.0.8)
      activejob (= 7.0.8)
      activerecord (= 7.0.8)
      activesupport (= 7.0.8)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.8)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    aes_key_wrap (1.1.0)
    ast (2.4.2)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    backport (1.2.0)
    base64 (0.2.0)
    benchmark (0.3.0)
    bindata (2.4.15)
    bindex (0.8.1)
    binding_of_caller (1.0.0)
      debug_inspector (>= 0.0.1)
    brakeman (6.0.1)
    builder (3.2.4)
    bundle (0.0.1)
      bundler
    bundler-audit (0.9.1)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    business_time (0.13.0)
      activesupport (>= 3.2.0)
      tzinfo
    byebug (11.1.3)
    capybara (3.39.2)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    capybara-screenshot (1.0.26)
      capybara (>= 1.0, < 4)
      launchy
    cf-app-utils (0.6)
    cliver (0.3.2)
    coderay (1.1.3)
    colorize (1.1.0)
    concurrent-ruby (1.2.2)
    connection_pool (2.4.1)
    crack (0.4.5)
      rexml
    crass (1.0.6)
    date (3.3.4)
    debug_inspector (1.1.0)
    diff-lcs (1.5.0)
    digest-crc (0.6.5)
      rake (>= 12.0.0, < 14.0.0)
    docile (1.4.0)
    dotenv (2.8.1)
    dotenv-rails (2.8.1)
      dotenv (= 2.8.1)
      railties (>= 3.2)
    e2mmap (0.1.0)
    erubi (1.12.0)
    et-orbi (1.2.7)
      tzinfo
    execjs (2.9.1)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    faraday (2.7.11)
      base64
      faraday-net_http (>= 2.0, < 3.1)
      ruby2_keywords (>= 0.0.4)
    faraday-follow_redirects (0.3.0)
      faraday (>= 1, < 3)
    faraday-net_http (3.0.2)
    ffaker (2.23.0)
    ffi (1.16.3)
    fugit (1.9.0)
      et-orbi (~> 1, >= 1.2.7)
      raabro (~> 1.4)
    globalid (1.2.1)
      activesupport (>= 6.1)
    hashdiff (1.0.1)
    health_check (3.1.0)
      railties (>= 5.0)
    hirb (0.7.3)
    httparty (0.21.0)
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    immutable-struct (2.4.1)
    importmap-rails (1.2.3)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    jaro_winkler (1.5.6)
    json (2.6.3)
    json-jwt (1.16.3)
      activesupport (>= 4.2)
      aes_key_wrap
      bindata
      faraday (~> 2.0)
      faraday-follow_redirects
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    language_server-protocol (3.17.0.3)
    launchy (2.5.2)
      addressable (~> 2.8)
    letter_opener (1.8.1)
      launchy (>= 2.2, < 3)
    lograge (0.14.0)
      actionpack (>= 4)
      activesupport (>= 4)
      railties (>= 4)
      request_store (~> 1.0)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.5)
    mini_portile2 (2.8.5)
    minitest (5.20.0)
    multi_xml (0.6.0)
    mustermann (3.0.0)
      ruby2_keywords (~> 0.0.1)
    mysql2 (0.5.5)
    net-imap (0.4.5)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.4.0)
      net-protocol
    nio4r (2.6.0)
    nokogiri (1.15.4)
      mini_portile2 (~> 2.8.2)
      racc (~> 1.4)
    nokogiri (1.15.4-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.15.4-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.15.4-x86_64-linux)
      racc (~> 1.4)
    parallel (1.23.0)
    parser (3.2.2.4)
      ast (~> 2.4.1)
      racc
    poltergeist (1.18.1)
      capybara (>= 2.1, < 4)
      cliver (~> 0.3.1)
      websocket-driver (>= 0.2.0)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.10.1)
      byebug (~> 11.0)
      pry (>= 0.13, < 0.15)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    pry-stack_explorer (0.6.1)
      binding_of_caller (~> 1.0)
      pry (~> 0.13)
    public_suffix (5.0.3)
    puma (6.4.0)
      nio4r (~> 2.0)
    raabro (1.4.0)
    racc (1.7.3)
    rack (2.2.8)
    rack-protection (3.1.0)
      rack (~> 2.2, >= 2.2.4)
    rack-test (2.1.0)
      rack (>= 1.3)
    rack-timeout (0.6.3)
    rails (7.0.8)
      actioncable (= 7.0.8)
      actionmailbox (= 7.0.8)
      actionmailer (= 7.0.8)
      actionpack (= 7.0.8)
      actiontext (= 7.0.8)
      actionview (= 7.0.8)
      activejob (= 7.0.8)
      activemodel (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      bundler (>= 1.15.0)
      railties (= 7.0.8)
    rails-controller-testing (1.0.5)
      actionpack (>= 5.0.1.rc1)
      actionview (>= 5.0.1.rc1)
      activesupport (>= 5.0.1.rc1)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.0.8)
      actionpack (= 7.0.8)
      activesupport (= 7.0.8)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rainbow (3.1.1)
    rake (13.1.0)
    rbs (2.8.4)
    rbtree (0.4.6)
    react-rails (3.1.1)
      babel-transpiler (>= 0.7.0)
      connection_pool
      execjs
      railties (>= 3.2)
      tilt
    redis-client (0.18.0)
      connection_pool
    regexp_parser (2.8.2)
    request_store (1.5.1)
      rack (>= 1.4)
    responders (3.1.1)
      actionpack (>= 5.2)
      railties (>= 5.2)
    reverse_markdown (2.1.1)
      nokogiri
    rexml (3.2.6)
    rounding (1.0.1)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-its (1.3.0)
      rspec-core (>= 3.0.0)
      rspec-expectations (>= 3.0.0)
    rspec-mocks (3.12.6)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-rails (6.0.3)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (~> 3.12)
      rspec-expectations (~> 3.12)
      rspec-mocks (~> 3.12)
      rspec-support (~> 3.12)
    rspec-support (3.12.1)
    rspec_junit_formatter (0.6.0)
      rspec-core (>= 2, < 4, != 2.12.0)
    rubocop (1.57.2)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.2.2.4)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.28.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.30.0)
      parser (>= 3.2.1.0)
    ruby-kafka (1.5.0)
      digest-crc
    ruby-progressbar (1.13.0)
    ruby2_keywords (0.0.5)
    rufo (0.16.3)
    rufus-scheduler (3.9.1)
      fugit (~> 1.1, >= 1.1.6)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    set (1.0.3)
    shoulda-matchers (5.3.0)
      activesupport (>= 5.2.0)
    sidekiq (7.2.0)
      concurrent-ruby (< 2)
      connection_pool (>= 2.3.0)
      rack (>= 2.2.4)
      redis-client (>= 0.14.0)
    sidekiq-enqueuer (2.1.1)
    sidekiq-scheduler (5.0.3)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 6, < 8)
      tilt (>= 1.4.0)
    simplecov (0.22.0)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.4)
    sinatra (3.1.0)
      mustermann (~> 3.0)
      rack (~> 2.2, >= 2.2.4)
      rack-protection (= 3.1.0)
      tilt (~> 2.0)
    solargraph (0.49.0)
      backport (~> 1.2)
      benchmark
      bundler (~> 2.0)
      diff-lcs (~> 1.4)
      e2mmap
      jaro_winkler (~> 1.5)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.1)
      parser (~> 3.0)
      rbs (~> 2.0)
      reverse_markdown (~> 2.0)
      rubocop (~> 1.38)
      thor (~> 1.0)
      tilt (~> 2.0)
      yard (~> 0.9, >= 0.9.24)
    sorted_set (1.0.3)
      rbtree
      set (~> 1.0)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    thor (1.3.0)
    tilt (2.3.0)
    timecop (0.9.8)
    timeout (0.4.1)
    typeprof (0.21.8)
      rbs (>= 1.8.1)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webmock (3.19.1)
      addressable (>= 2.8.0)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)
    webrick (1.8.1)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    yard (0.9.34)
    zeitwerk (2.6.12)

PLATFORMS
  arm64-darwin
  arm64-darwin-22
  ruby
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  brakeman
  bundle
  bundler (= 2.4.21)
  bundler-audit
  business_time
  byebug
  capybara
  capybara-screenshot
  cf-app-utils
  colorize
  dotenv-rails
  factory_bot_rails
  ffaker
  health_check
  hirb
  httparty
  immutable-struct
  importmap-rails
  json-jwt
  letter_opener
  lograge
  mysql2
  nokogiri
  poltergeist
  pry-byebug
  pry-rails
  pry-stack_explorer
  puma
  rack-timeout
  rails (< 7.1)
  rails-controller-testing
  rbs
  react-rails
  responders
  rounding
  rspec-its
  rspec-mocks
  rspec-rails
  rspec_junit_formatter
  rubocop
  ruby-kafka
  rufo
  sass-rails
  shoulda-matchers
  sidekiq
  sidekiq-enqueuer
  sidekiq-scheduler
  simplecov
  sinatra
  solargraph
  sorted_set
  timecop
  typeprof
  web-console
  webmock
  webrick

RUBY VERSION
   ruby 3.2.2p53

BUNDLED WITH
   2.4.21
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by martinemde** [comment]
Hey, this may be as simple as deleting the cached gem at `vendor/cache/actioncable-7.0.8.gem`.

It's no unheard of for gems to get corrupted during download/sync, and since I can see this is in OneDrive there's a very real chance this happened.

If this is not the case or if it happens repeatedly, please let us know or hop in the bundler slack and we can debug it.

**Comment by ShadSterling** [comment]
I'm not sure what happened, this occurrence of the error was after a previous error that may have been the same and then running my reset-everything script and trying again, now I've repeated that and it worked.  I've had earlier problems that were clearly caused by OneDrive, but in this case OneDrive was not running since before the first occurrence and still isn't running after the success, so I'm not sure whether it was related or not.  I guess there's nothing to do but reach out in slack if it keeps happening.
