### ISSUE TITLE
Solving failures, possibly due to bundling net-* libraries

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#7273]
Testing with recent versions of Ruby (ruby/ruby@e51f9e9f75cc1dde9234836fa92077d71b3c5141) on Fedora, trying to run ActionMailbox (but also e.g. vagrant-libvirt) as we always did, [we hit the following error](https://lists.fedoraproject.org/archives/list/ruby-sig@lists.fedoraproject.org/message/UKPIMD7ZO4ECR6GNCQFXFXZVRJUDMTMQ/):

~~~
$ BUNDLE_GEMFILE=/builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/../Gemfile
$ ruby -rbundler -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'
/usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/resolver.rb:116:in `rescue in solve_versions': Could not find compatible versions (Bundler::SolveFailure)

Because every version of actionmailer depends on net-imap >= 0
  and every version of net-imap depends on net-protocol >= 0,
  every version of actionmailer requires net-protocol >= 0.
So, because net-protocol >= 0 could not be found in locally installed gems
  and Gemfile depends on actionmailer >= 0,
  version solving has failed.
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/resolver.rb:79:in `solve_versions'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/resolver.rb:32:in `start'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:592:in `start_resolution'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:311:in `resolve'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:545:in `materialize'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:203:in `specs'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:270:in `specs_for'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/runtime.rb:18:in `setup'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler.rb:164:in `setup'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/setup.rb:23:in `block in <top (required)>'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/ui/shell.rb:159:in `with_level'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/ui/shell.rb:111:in `silence'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/boot.rb:4:in `<top (required)>'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/application.rb:1:in `require_relative'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/application.rb:1:in `<top (required)>'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/environment.rb:2:in `require_relative'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/environment.rb:2:in `<top (required)>'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/test_helper.rb:6:in `require_relative'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/test_helper.rb:6:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/controllers/ingresses/mailgun/inbound_emails_controller_test.rb:3:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:dir>:411:in `glob'
	from -e:1:in `<main>'
/usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:237:in `resolve_conflict': Could not find compatible versions (Bundler::PubGrub::SolveFailure)

Because every version of actionmailer depends on net-imap >= 0
  and every version of net-imap depends on net-protocol >= 0,
  every version of actionmailer requires net-protocol >= 0.
So, because net-protocol >= 0 could not be found in locally installed gems
  and Gemfile depends on actionmailer >= 0,
  version solving has failed.
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:73:in `block in propagate'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `reverse_each'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `propagate'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:42:in `work'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:58:in `solve'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/resolver.rb:81:in `solve_versions'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/resolver.rb:32:in `start'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:592:in `start_resolution'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:311:in `resolve'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:545:in `materialize'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:203:in `specs'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:270:in `specs_for'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/runtime.rb:18:in `setup'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler.rb:164:in `setup'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/setup.rb:23:in `block in <top (required)>'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/ui/shell.rb:159:in `with_level'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/ui/shell.rb:111:in `silence'
	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/boot.rb:4:in `<top (required)>'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/application.rb:1:in `require_relative'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/application.rb:1:in `<top (required)>'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/environment.rb:2:in `require_relative'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/dummy/config/environment.rb:2:in `<top (required)>'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/test_helper.rb:6:in `require_relative'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/test_helper.rb:6:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/test/controllers/ingresses/mailgun/inbound_emails_controller_test.rb:3:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:dir>:411:in `glob'
	from -e:1:in `<main>'
~~~

I have just briefly tried to check if it due to e.g. #7242, but even with revert by #7266, we still hit this issue. I also tried to revert our recent `operating_system.rb` changes and it still happens. So the only other thing we can think of is the vendoring of net-* libraries #6793

I'll try to investigate further, but I figured somebody more knowledgeable then me could have fester answer.

**Comment by voxik** [comment]
Forget to attach the Gemfile:

~~~
$ cat /builddir/build/BUILD/actionmailbox-7.0.8/usr/share/gems/gems/actionmailbox-7.0.8/../Gemfile
gem "railties"
gem "actionmailer"
gem "activestorage"
gem "sprockets-rails"
gem "sqlite3"
gem "webmock"
~~~

and `gem list`:

~~~
$ gem list

*** LOCAL GEMS ***

abbrev (default: 0.1.1)
actionmailer (7.0.8)
actionpack (7.0.8)
actionview (7.0.8)
activejob (7.0.8)
activemodel (7.0.8)
activerecord (7.0.8)
activestorage (7.0.8)
activesupport (7.0.8)
addressable (2.8.1)
base64 (default: 0.2.0)
benchmark (default: 0.3.0)
bigdecimal (3.1.5)
builder (3.2.4)
bundler (2.5.0.dev)
cgi (default: 0.4.1)
concurrent-ruby (1.1.9)
crack (0.4.5)
crass (1.0.4)
csv (default: 3.2.8)
date (default: 3.3.4)
debug (1.9.0)
delegate (default: 0.3.1)
did_you_mean (default: 1.6.3)
digest (default: 3.1.1)
drb (default: 2.2.0)
english (default: 0.8.0)
erb (default: 4.0.3)
error_highlight (default: 0.6.0)
erubi (1.10.0)
etc (default: 1.4.3)
fcntl (default: 1.1.0)
fiddle (default: 1.1.2)
fileutils (default: 1.7.2)
find (default: 0.2.0)
forwardable (default: 1.3.3)
getoptlong (default: 0.2.1)
globalid (1.1.0)
hashdiff (1.0.1)
i18n (1.14.1)
io-console (0.7.0)
io-nonblock (default: 0.3.0)
io-wait (default: 0.3.1)
ipaddr (default: 1.2.5)
irb (1.10.1)
json (2.7.1)
logger (default: 1.6.0)
loofah (2.22.0)
mail (2.7.1)
marcel (1.0.2)
matrix (0.4.2)
method_source (1.0.0)
mini_mime (1.1.0)
minitest (5.20.0)
mutex_m (default: 0.2.0)
net-ftp (0.3.2)
net-http (default: 0.4.0)
net-imap (0.4.8)
net-pop (0.1.2)
net-protocol (default: 0.2.2)
net-smtp (0.4.0)
nkf (default: 0.1.3)
nokogiri (1.15.5)
observer (default: 0.1.2)
open-uri (default: 0.4.1)
open3 (default: 0.2.0)
openssl (default: 3.2.0)
optparse (default: 0.4.0)
ostruct (default: 0.6.0)
pathname (default: 0.3.0)
pp (default: 0.5.0)
prettyprint (default: 0.2.0)
prime (0.1.2)
prism (default: 0.18.0)
pstore (default: 0.1.3)
psych (5.1.1.1)
public_suffix (5.0.0)
racc (1.7.3)
rack (2.2.4)
rack-test (1.1.0)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.6.0)
railties (7.0.8)
rake (13.1.0)
rdoc (6.6.1)
readline (default: 0.0.3)
reline (default: 0.4.0)
resolv (default: 0.3.0)
resolv-replace (default: 0.1.1)
rexml (3.2.6)
rinda (default: 0.2.0)
ruby2_keywords (default: 0.0.5)
securerandom (default: 0.3.0)
set (default: 1.0.4)
shellwords (default: 0.2.0)
singleton (default: 0.2.0)
sprockets (4.2.0)
sprockets-rails (3.4.2)
sqlite3 (1.6.1)
stringio (default: 3.1.1)
strscan (default: 3.0.8)
syntax_suggest (default: 2.0.0)
syslog (default: 0.1.1)
tempfile (default: 0.2.1)
thor (1.2.1)
time (default: 0.3.0)
timeout (default: 0.4.1)
tmpdir (default: 0.2.0)
tsort (default: 0.2.0)
tzinfo (2.0.6)
un (default: 0.3.0)
uri (default: 0.13.0)
weakref (default: 0.1.3)
webmock (3.18.1)
yaml (default: 0.3.0)
zeitwerk (2.6.6)
zlib (default: 3.1.0)
~~~

**Comment by voxik** [comment]
And just FTR, the test was passing just fine for ruby/ruby@1ab91b12fa

**Comment by mtasaka** [comment]
Maybe https://github.com/ruby/ruby/blob/master/gems/bundled_gems and https://github.com/ruby/ruby/blob/master/lib/bundled_gems.rb need updating??

**Comment by deivid-rodriguez** [comment]
I'd say this is unrelated to vendoring net-* libraries, but due to https://github.com/rubygems/rubygems/pull/7266 not having landed the ruby repo yet. I'll sync again bundler & rubygems with ruby-core and see if that fixes. If it doesn't fix it, I'll look closer.

**Comment by voxik** [comment]
> due to #7266 not having landed the ruby repo yet

It has landed IMHO

**Comment by hsbt** [comment]
@deivid-rodriguez I'll do that now.

**Comment by deivid-rodriguez** [comment]
I did check myself. I'm just not sure if it will fix it, but I am sure the commit is not there.

**Comment by voxik** [comment]
> I'd say this is unrelated to vendoring net-* libraries, but due to #7266 not having landed the ruby repo yet. I'll sync again bundler & rubygems with ruby-core and see if that fixes. If it doesn't fix it, I'll look closer.

You are actually right. I have probably checked only RubyGems, not Bundler 🙈 Sorry

> @deivid-rodriguez I'll do that now.

@hsbt Thx a lot.

**Comment by voxik** [comment]
Going to test ruby/ruby@e3631277c37861d5e99fbefd8bd3eeefc0120825 which seems to contain the #7266 (if I am not mistaken again 🙈)

**Comment by deivid-rodriguez** [comment]
Cool, let me know how that goes!

**Comment by voxik** [comment]
Success. Sorry for the noise, I'd need to take a better look next time.

But at least, you have some feedback on #7242 :wink: :angel:
