### ISSUE TITLE
Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#7277]
While there was already #7186 reported, I don't think there was provided enough context. I have hit this issue when testing shoulda-matchers on Fedora:

~~~
  1) shoulda-matchers integrates with Rails in a project that uses Spring
     Failure/Error: run_rake_tasks!('db:drop', 'db:create', 'db:migrate')

     RuntimeError:
       Command "BUNDLE_GEMFILE=\"/tmp/shoulda-matchers-acceptance/test-project/Gemfile\" bundle _2.5.0.dev_ exec rake db:drop db:create db:migrate --trace" exited with status 1.
       Output:
       ---START----------------------------------------------------------------
       bundler: failed to load command: rake (/usr/bin/rake)
       /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:451:in `validate_ruby!': Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0 (Bundler::RubyVersionMismatch)
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/definition.rb:426:in `validate_runtime!'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler.rb:157:in `setup'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/setup.rb:23:in `block in <top (required)>'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/ui/shell.rb:159:in `with_level'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/ui/shell.rb:111:in `silence'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/setup.rb:23:in `<top (required)>'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/cli/exec.rb:56:in `require_relative'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/cli/exec.rb:56:in `kernel_load'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/cli/exec.rb:23:in `run'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/cli.rb:491:in `exec'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/cli.rb:34:in `dispatch'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/cli.rb:28:in `start'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/libexec/bundle:28:in `block in <top (required)>'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
       	from /usr/share/gems/gems/bundler-2.5.0.dev/libexec/bundle:20:in `<top (required)>'
       	from /usr/bin/bundle:25:in `load'
       	from /usr/bin/bundle:25:in `<main>'
       ---END------------------------------------------------------------------
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:111:in `fail!'
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:69:in `block (2 levels) in call'
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:196:in `possibly_running_quickly'
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:65:in `block in call'
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:202:in `possibly_retrying'
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:64:in `call'
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:11:in `block in run'
     # /builddir/build/BUILD/spec/support/tests/command_runner.rb:9:in `run'
     # /builddir/build/BUILD/spec/support/acceptance/helpers/command_helpers.rb:10:in `run_command'
     # /builddir/build/BUILD/spec/support/acceptance/helpers/command_helpers.rb:24:in `run_command_isolated_from_bundle'
     # /builddir/build/BUILD/spec/support/acceptance/helpers/command_helpers.rb:41:in `run_command_within_bundle'
     # /builddir/build/BUILD/spec/support/acceptance/helpers/command_helpers.rb:50:in `run_command_within_bundle!'
     # /builddir/build/BUILD/spec/support/acceptance/helpers/command_helpers.rb:65:in `run_rake_tasks!'
     # ./spec/acceptance/rails_integration_spec.rb:17:in `block (2 levels) in <top (required)>'
     # /usr/share/gems/gems/bundler-2.5.0.dev/libexec/bundle:28:in `block in <top (required)>'
     # /usr/share/gems/gems/bundler-2.5.0.dev/libexec/bundle:20:in `<top (required)>'
~~~

Trying to reproduce manually, I took Rail 7.0.8 and generated new app:

~~~
/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/assets.rb
      remove  app/assets/config/manifest.js
      remove  app/assets/config
      remove  app/assets/stylesheets/application.css
      create  app/assets/stylesheets/application.css
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb

$ cd tr

$ rake
Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0
~~~

From my perspective, this is quite unfortunate, because Rails generated Gemfile with `ruby "3.3.0"` but why Bundler should not be able to match that? Just peeking into `lib/bundler/definition.rb`, the `Bundler::RubyVersion.system` content is:

~~~
#<Bundler::RubyVersion:0x00007faaf473fba8 @versions=["3.3.0.dev"], @gem_version=#<Gem::Version "3.3.0.dev">, @input_engine="ruby", @engine="ruby", @engine_versions=["3.3.0.dev"], @engine_gem_version=#<Gem::Version "3.3.0.dev">, @patchlevel="-1">
~~~

IOW there is IMHO enough information to recognize we are dealing with development version and it should IMHO be acceptable if the `validate_ruby!` method should not be more relaxed in this case.

Please note that to my experience, there are quite a few libraries around, which are creating Rails applications for testing purposes. Why they should be broken or workaround this somehow?

Admitedly, I am also not sure why Rails simply won't put the `3.3.0.dev` string there. But there likely is used just plain `RUBY_VERSION` or something akin.

**Comment by deivid-rodriguez** [comment]
Rails generates the [correct value](https://github.com/rails/rails/blob/9517841bc3ff69019317e7564a6ceb96dd67ac87/railties/lib/rails/generators/app_base.rb#L420) as long as you use RubyGems at least 3.3.13 (I think because previous RubyGems versions did not generate the correct pre-release identifier).

Maybe that test is using an old RubyGems version?

From the Bundler point of view, this is expected. The `ruby` Gemfile DSL accepts arbitrary constraint, but if you use an exact constraint (like Rails does), then it is expected that prerelease versions don't match released versions.

**Comment by voxik** [comment]
> Rails generates the [correct value](https://github.com/rails/rails/blob/9517841bc3ff69019317e7564a6ceb96dd67ac87/railties/lib/rails/generators/app_base.rb#L420) as long as you use RubyGems at least 3.3.13

I hopefully do:

~~~
$ gem -v
3.5.0.dev
~~~

You could have noticed `/usr/share/gems/gems/bundler-2.5.0.dev`

But let me check the link you have provided.

**Comment by voxik** [comment]
Hm:

~~~
$ cat /usr/share/gems/gems/railties-7.0.8/lib/rails/generators/app_base.rb | grep RUBY_VERSION
        !options[:skip_bootsnap] && !options[:dev] && !defined?(JRUBY_VERSION)
~~~

Probably not Rails 7? Investigating further ...

**Comment by voxik** [comment]
Checking the https://github.com/rails/rails/commit/af4a07b4fc3d2fbcb13dddccc7427a4036907ab5 commit, GH suggests it is just in 7.1: v7.1.2 v7.1.1 v7.1.0 v7.1.0.rc2 v7.1.0.rc1 v7.1.0.beta1

Checking the [7.0 branch](https://github.com/rails/rails/blame/7-0-stable/railties/lib/rails/generators/app_base.rb), I can't see there the same expression.

Should I ask Rails?

**Comment by deivid-rodriguez** [comment]
I guess, if you think that's worth backporting, you can ask them!
