### ISSUE TITLE
Error when requiring default bundled gem by path

### ISSUE THREAD

**Issue by ianks** [rubygems/rubygems#7295]
When attempting to require a default bundled gem by full path, Bundler causes Ruby `3.3.0-rc1` to error out when trying to print a warning.

It seems like an obscure use case, but it's important to fix because `bootsnap`'s load path cache can require default gems via absolute path, which is how I discovered this bug.

### Repro

```bash
$ ruby -e "puts require('/opt/rubies/3.3.0-rc1/lib/ruby/3.3.0+0/base64.rb')"
true

$ bundle exec ruby -e "puts require('/opt/rubies/3.3.0-rc1/lib/ruby/3.3.0+0/base64.rb')"
/opt/rubies/3.3.0-rc1/lib/ruby/3.3.0+0/bundled_gems.rb:120:in `<': comparison of String with nil failed (ArgumentError)

    msg = " #{RUBY_VERSION < SINCE[gem] ? "will no longer be" : "is not"} part of the default gems since Ruby #{SINCE[gem]}."
                             ^^^^^^^^^^
        from /opt/rubies/3.3.0-rc1/lib/ruby/3.3.0+0/bundled_gems.rb:120:in `build_message'
        from /opt/rubies/3.3.0-rc1/lib/ruby/3.3.0+0/bundled_gems.rb:116:in `warning?'
        from /opt/rubies/3.3.0-rc1/lib/ruby/3.3.0+0/bundled_gems.rb:65:in `block (2 levels) in replace_require'
        from -e:1:in `<main>'
```

It ends up calling `def self.build_message(gem)` with some weird path slug, but that's all I know:

```ruby
  def self.build_message(gem)
    puts "gem: #{gem.inspect}" # gem: "-opt-rubies-3.3.0-rc1-lib-ruby-3.3.0+0-base64"
    ...
  end
```

## Environment

```
Bundler       2.5.1
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.0p-1 (2023-12-11 revision a49643340eb6b8d65299912b640887ea18495909) [arm64-darwin-23]
  Full Path   /opt/rubies/3.3.0-rc1/bin/ruby
  Config Dir  /opt/rubies/3.3.0-rc1/etc
RubyGems      3.5.0.dev
  Gem Home    /Users/ianks/.gem/ruby/3.3.0-rc1
  Gem Path    /Users/ianks/.gem/ruby/3.3.0-rc1:/opt/rubies/3.3.0-rc1/lib/ruby/gems/3.3.0+0
  User Home   /Users/ianks
  User Path   /Users/ianks/.gem/ruby/3.3.0+0
  Bin Dir     /Users/ianks/.gem/ruby/3.3.0-rc1/bin
Tools         
  Git         2.42.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-12-15
Git SHA           c944d05909
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/ianks/.bundle/config): false
gem.ci
  Set for the current user (/Users/ianks/.bundle/config): "github"
gem.coc
  Set for the current user (/Users/ianks/.bundle/config): true
gem.linter
  Set for the current user (/Users/ianks/.bundle/config): "rubocop"
gem.mit
  Set for the current user (/Users/ianks/.bundle/config): true
gem.test
  Set for the current user (/Users/ianks/.bundle/config): "minitest"
local.gem_name
  Set for the current user (/Users/ianks/.bundle/config): "/path/to/local/git/repository"
pkgs.shopify.io
  Set for the current user (/Users/ianks/.bundle/config): "token:[REDACTED]"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  arm64-darwin-22
  arm64-darwin-23

DEPENDENCIES

BUNDLED WITH
   2.5.1
```

**Comment by ianks** [comment]
[Looks like this has already been resolved](https://bugs.ruby-lang.org/issues/20060), sorry for the noise!

**Comment by hsbt** [comment]
@ianks If you have a time, I'm happy to test with current master of `ruby/ruby`.
