### ISSUE TITLE
rackup command with Sinatra gives Gem::ConflictError with ruby-3.3.0-rc1

### ISSUE THREAD

**Issue by MatzFan** [rubygems/rubygems#7320]
`Unable to activate sinatra-3.1.0, because rack-3.0.8 conflicts with rack (~> 2.2, >= 2.2.4) (Gem::ConflictError)` results from `rackup` command with ruby 3.3.0-rc1 in Sinatra app with gems installed with bundler 2.5.2:

Gemfile:
```ruby
source 'https://rubygems.org'

gem 'sinatra'
```
app.rb
```ruby
require 'sinatra/base'

class App < Sinatra::Base
  get '/' do
    'Hello world!'
  end
end
```
config.ru
```
require_relative 'app'

run App
```

```bash
$ bundle install
Bundle complete! 1 Gemfile dependency, 7 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ rackup
/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/specification.rb:2317:in `raise_if_conflicts': Unable to activate sinatra-3.1.0, because rack-3.0.8 conflicts with rack (~> 2.2, >= 2.2.4) (Gem::ConflictError)
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/specification.rb:1450:in `activate'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems.rb:205:in `rescue in try_activate'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems.rb:198:in `try_activate'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:130:in `block in require'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:130:in `synchronize'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:130:in `rescue in require'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:126:in `require'
	from /home/me/gitlab/sinatra/app.rb:3:in `<top (required)>'
	from /home/me/gitlab/sinatra/config.ru:3:in `require_relative'
	from /home/me/gitlab/sinatra/config.ru:3:in `block in <main>'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `eval'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `new_from_string'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:94:in `load_file'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:64:in `parse_file'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:182:in `start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/bin/rackup:5:in `<top (required)>'
	from /home/me/.rbenv/versions/3.3.0-rc1/bin/rackup:25:in `load'
	from /home/me/.rbenv/versions/3.3.0-rc1/bin/rackup:25:in `<main>'
/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/specification.rb:2317:in `raise_if_conflicts': Unable to activate sinatra-3.1.0, because rack-3.0.8 conflicts with rack (~> 2.2, >= 2.2.4) (Gem::ConflictError)
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/specification.rb:1450:in `activate'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems.rb:199:in `try_activate'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:130:in `block in require'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:130:in `synchronize'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:130:in `rescue in require'
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:126:in `require'
	from /home/me/gitlab/sinatra/app.rb:3:in `<top (required)>'
	from /home/me/gitlab/sinatra/config.ru:3:in `require_relative'
	from /home/me/gitlab/sinatra/config.ru:3:in `block in <main>'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `eval'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `new_from_string'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:94:in `load_file'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:64:in `parse_file'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:182:in `start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/bin/rackup:5:in `<top (required)>'
	from /home/me/.rbenv/versions/3.3.0-rc1/bin/rackup:25:in `load'
	from /home/me/.rbenv/versions/3.3.0-rc1/bin/rackup:25:in `<main>'
<internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- sinatra/base (LoadError)
	from <internal:/home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/site_ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /home/me/gitlab/sinatra/app.rb:3:in `<top (required)>'
	from /home/me/gitlab/sinatra/config.ru:3:in `require_relative'
	from /home/me/gitlab/sinatra/config.ru:3:in `block in <main>'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `eval'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:103:in `new_from_string'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:94:in `load_file'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rack-3.0.8/lib/rack/builder.rb:64:in `parse_file'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/lib/rackup/server.rb:182:in `start'
	from /home/me/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/rackup-2.1.0/bin/rackup:5:in `<top (required)>'
	from /home/me/.rbenv/versions/3.3.0-rc1/bin/rackup:25:in `load'
	from /home/me/.rbenv/versions/3.3.0-rc1/bin/rackup:25:in `<main>'
```

No problem with ruby 3.3.0-preview3 (bundler 2.5.0.dev) and below.
`ruby ./app.rb` works fine

LMDE 6 (Faye) - based on Debian Bookworm
Ruby 3.3.0-rc1 - installed with rbenv 1.2.0-80-gd6bb1c6
rubygems 3.5.2
bundler 2.5.2 (note the [release notes for ruby 3.3.0-rc1](https://www.ruby-lang.org/en/news/2023/12/11/ruby-3-3-0-rc1-released/) state bundler 2.5.0.dev is default, but `gem list bundler` shows: `bundler (default: 2.5.2)`

**Comment by deivid-rodriguez** [comment]
This is expected.

The `rackup` command comes from the [`rackup-2.1.0` gem](https://rubygems.org/gems/rackup/versions/2.1.0), which depends on `rack >= 3`. So it loads `rack-3.0.8`. Then when your `app.rb` file requires `sinatra/base`, RubyGems detects that Sinatra has a dependency on `rack (~> 2.2, >= 2.2.4)`, which conflicts with the already activated `rack-3.0.8` gem.

The solution to make your Gemfile dependencies be respected would be to run `bundle exec rackup` instead of `rackup`. However, your global `rackup` binstub has probably been taken over by the `rackup` gem, so you'll probably also need to uninstall that, or make sure to use a local setup for bundler (`bundle config path vendor/bundle` for example).

I'm closing this but happy to help out here and keep discussing.

**Comment by MatzFan** [comment]
@deivid-rodriguez many thanks for the explanation. The solution was actually to add gem `rackup` to my Gemfile.
