### ISSUE TITLE
Installing pods failed. This doesn't affect project initialization and you can safely proceed. 

### ISSUE THREAD

**Issue by dezudas** [rubygems/rubygems#7339]
```
Gem::GemNotFoundException: can't find gem bundler (= 2.3.14) with executable bundle
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe'
  /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:245:in `bin_path'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/rubygems_integration.rb:178:in `bin_path'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/shared_helpers.rb:283:in `set_bundle_variables'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli/exec.rb:20:in `run'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:483:in `exec'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
  /usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
  /usr/local/lib/ruby/gems/3.1.0/bin/bundle:25:in `load'
  /usr/local/lib/ruby/gems/3.1.0/bin/bundle:25:in `<main>'
```

## Environment

```
Bundler       2.3.14
  Platforms   ruby, x86_64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-darwin-21]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/3.1.2/etc
RubyGems      3.3.14
  Gem Home    /usr/local/lib/ruby/gems/3.1.0
  Gem Path    /Users/dijuptuladhar/.gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/dijuptuladhar
  User Path   /Users/dijuptuladhar/.gem/ruby/3.1.0
  Bin Dir     /usr/local/lib/ruby/gems/3.1.0/bin
Tools         
  Git         2.39.3 (Apple Git-145)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      /usr/local/opt/ruby/bin/ruby
bundle #!     /usr/local/Cellar/ruby/3.1.2/bin/ruby

```

## Bundler Build Metadata

```
Built At          2022-05-18
Git SHA           467ad58a7c
Released Version  true
```

## Bundler settings

```
force_ruby_platform
  Set for your local app (/Users/dijuptuladhar/Project/react-native/rn73/.bundle/config): true
path
  Set for your local app (/Users/dijuptuladhar/Project/react-native/rn73/.bundle/config): "vendor/bundle"
```

### ../Gemfile

```ruby
source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

gem 'cocoapods', '~> 1.13'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
```

### ../Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.6)
      rexml
    activesupport (7.0.8)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.6)
      public_suffix (>= 2.0.2, < 6.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    atomos (0.1.3)
    claide (1.1.0)
    cocoapods (1.14.3)
      addressable (~> 2.8)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.14.3)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 2.1, < 3.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.6.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.8.0)
      nap (~> 1.0)
      ruby-macho (>= 2.3.0, < 3.0)
      xcodeproj (>= 1.23.0, < 2.0)
    cocoapods-core (1.14.3)
      activesupport (>= 5.0, < 8)
      addressable (~> 2.8)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix (~> 4.0)
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (2.1)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.6.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored2 (3.1.2)
    concurrent-ruby (1.2.2)
    escape (0.0.4)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    ffi (1.16.3)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    httpclient (2.8.3)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    json (2.7.1)
    minitest (5.20.0)
    molinillo (0.8.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    netrc (0.11.0)
    public_suffix (4.0.7)
    rexml (3.2.6)
    ruby-macho (2.5.1)
    typhoeus (1.4.1)
      ethon (>= 0.9.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    xcodeproj (1.23.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport (>= 6.1.7.3, < 7.1.0)
  cocoapods (~> 1.13)

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.14
```

**Comment by deivid-rodriguez** [comment]
This seems similar to https://github.com/rubygems/rubygems/issues/7136. Can you confirm which steps did you take before running into this issue? You installed ruby with `brew` right, then did you modify the ruby installation in any way (running `gem update --system` or something?). Which actual command were you running when you saw this error?
