### ISSUE TITLE
bundle install issue

### ISSUE THREAD

**Issue by bharath-naik** [rubygems/rubygems#7351]
```
NoMethodError: undefined method `metadata' for nil:NilClass
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/cli/common.rb:23:in `block in output_fund_metadata_summary'
  org/jruby/RubyArray.java:3241:in `count'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/cli/common.rb:23:in `output_fund_metadata_summary'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/cli/install.rb:87:in `run'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/cli.rb:257:in `block in install'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/settings.rb:131:in `temporary'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/cli.rb:256:in `install'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/exe/bundle:48:in `block in <main>'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.3.26/exe/bundle:36:in `<main>'
  org/jruby/RubyKernel.java:1013:in `load'
  /home/naikvad/.rvm/gems/jruby-9.2.9.0/bin/bundle:25:in `<main>'
  org/jruby/RubyKernel.java:1052:in `eval'
  /home/naikvad/.rvm/gems/jruby-9.2.9.0/bin/jruby_executable_hooks:22:in `<main>'

```

## Environment

```
Bundler             2.3.26
  Platforms         ruby, universal-java-1.8
Ruby                2.5.7p0 (2019-10-30 revision 67816) [universal-java-1.8]
  Full Path         /home/naikvad/.rvm/rubies/jruby-9.2.9.0/bin/jruby
  Config Dir        /home/naikvad/.rvm/rubies/jruby-9.2.9.0/etc
RubyGems            3.0.9
  Gem Home          /home/naikvad/.rvm/gems/jruby-9.2.9.0
  Gem Path          /home/naikvad/.rvm/gems/jruby-9.2.9.0:/home/naikvad/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared
  User Home         /home/naikvad
  User Path         /home/naikvad/.gem/jruby/2.5.0
  Bin Dir           /home/naikvad/.rvm/gems/jruby-9.2.9.0/bin
OpenSSL             
  Compiled          JRuby-OpenSSL 0.14.2
  Loaded            JRuby-OpenSSL 0.14.2
  Cert File         /usr/lib/jvm/jdk1.8.0_342/jre/lib/security/cacerts
  Cert Dir          /etc/ssl/certs
Tools               
  Git               2.34.1
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           23ec5b8501
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "concurrent-ruby", "~> 1.1"
gem "write_xlsx", "~> 1.7"
gem "sequel", "~> 5.47"
gem "httparty"
gem 'tiny_tds', platform: :mri, groups: [:local_sql_server_conns]
gem 'msgpack'

group :development, :test do
  gem 'pry-byebug', platform: :mri
  gem 'pry-debugger-jruby', platform: :jruby
  gem 'ruby-debug-base', '0.11.0', platform: :jruby
  gem 'ruby-debug-ide', platform: :jruby
end

group :test do
  gem 'sqlite3', platform: :mri
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    byebug (11.1.3)
    coderay (1.1.3)
    concurrent-ruby (1.1.9)
    diff-lcs (1.5.0)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    method_source (1.0.0)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2021.0901)
    msgpack (1.4.2)
    msgpack (1.4.2-java)
    multi_xml (0.6.0)
    pry (0.13.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.9.0)
      byebug (~> 11.0)
      pry (~> 0.13.0)
    rspec-core (3.11.0)
      rspec-support (~> 3.11.0)
    rspec-expectations (3.11.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-mocks (3.11.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-support (3.11.0)
    rubyzip (2.3.2)
    sequel (5.47.0)
    sqlite3 (1.4.2)
    tiny_tds (2.1.5)
    write_xlsx (1.07.0)
      rubyzip (>= 1.0.0)
      zip-zip
    zip-zip (0.3)
      rubyzip (>= 1.0.0)

PLATFORMS
  ruby
  universal-java-1.8
  x86_64-darwin-19

DEPENDENCIES
  concurrent-ruby (~> 1.1)
  httparty
  msgpack
  pry-byebug
  pry-debugger-jruby
  rspec-core
  rspec-expectations
  rspec-mocks
  ruby-debug-base (= 0.11.0)
  ruby-debug-ide
  sequel (~> 5.47)
  sqlite3
  tiny_tds
  write_xlsx (~> 1.7)

BUNDLED WITH
   2.3.4
```

**Comment by deivid-rodriguez** [comment]
This report is using old Bundler, RubyGems, and Ruby versions.

It's likely that either of these has fixed the underlying issue. Could you upgrade everything and see if it still reproduces? Feel free to reopen if it does, thank you!
