### ISSUE TITLE
Ruby with `--with-sitedir=no` configuration

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#7414]
I am trying to prepare minimal and self contained Ruby RPM package. Therefore I chose to configure Ruby using `--with-sitedir=no --with-vendordir=no` configuration options. And now I am facing test suite errors such as:

~~~
111) Error:
TestGemCommandsSetupCommand#test_execute_regenerate_binstubs:
Errno::ENOENT: No such file or directory @ dir_chdir0 - $(sitedir)/ruby3.3/rubygems
    /builddir/build/BUILD/ruby-3.3.0/lib/rubygems/commands/setup_command.rb:465:in `chdir'
    /builddir/build/BUILD/ruby-3.3.0/lib/rubygems/commands/setup_command.rb:465:in `files_in'
    /builddir/build/BUILD/ruby-3.3.0/lib/rubygems/commands/setup_command.rb:509:in `block in remove_old_lib_files'
    /builddir/build/BUILD/ruby-3.3.0/lib/rubygems/commands/setup_command.rb:506:in `each'
    /builddir/build/BUILD/ruby-3.3.0/lib/rubygems/commands/setup_command.rb:506:in `remove_old_lib_files'
    /builddir/build/BUILD/ruby-3.3.0/lib/rubygems/commands/setup_command.rb:170:in `execute'
    /builddir/build/BUILD/ruby-3.3.0/test/rubygems/test_gem_commands_setup_command.rb:68:in `test_execute_regenerate_binstubs'
~~~

If I understand correctly, the `$(sitedir)` actually comes from here:

https://github.com/rubygems/rubygems/blob/4198033da31a834ad892f82d6f91d46404d79d33/lib/rubygems/commands/setup_command.rb#L449-L462

In normal situation, with the default site dir configuration, the `RbConfig::CONFIG[site_or_vendor]` would be expanded into proper path. However, with disabled site dir, the `RbConfig` does not have value for the `sitedir`, therefore the `$(sitedir)` is kept. It seems that the Ruby's `rbinstall.rb` script handles this scenario:

https://github.com/ruby/ruby/blob/a846d391d38b34fcc4f90adef967c166c923bd56/tool/rbinstall.rb#L354-L361

IOW, I don't think this is just test suite error. The test suite error correctly points out that there might be user scenario, which is not correctly handled (is it trying to update RubyGems via `gem update`?). If this is valid Ruby configuration, I believe that RubyGems should properly handle this situation (even if "properly" was just reporting that there is no location for updated RubyGems).

**Comment by voxik** [comment]
There actually are small [traces](https://github.com/rubygems/rubygems/commit/9c5d2eceb1a3c90d5a0a3544b760551847cd431) of handling the missing vendor dir. That means also JRuby might struggle to pass these test cases and indeed, the whole test file is just disabled:

https://github.com/rubygems/rubygems/blob/a7aa64a918a590efe0e8c4da0eba189a8aa5140d/test/rubygems/test_gem_commands_setup_command.rb#L472
