### ISSUE TITLE
Bundle Install Error

### ISSUE THREAD

**Issue by carmenalexander** [rubygems/rubygems#7421]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/extensions/x86_64-darwin-23/3.0.0/stringio-3.1.0
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/fileutils.rb:211:in `each'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:205:in `write_gem_make_out'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:133:in `build_error'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:167:in `rescue in build_extension'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:156:in `build_extension'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.33
  Platforms   ruby, x86_64-darwin-23
Ruby          3.0.4p208 (2022-04-12 revision 3fa771ddedac25560be57f4055f1767e6c810f58) [x86_64-darwin23]
  Full Path   /Users/carmenalexander/.rbenv/versions/3.0.4/bin/ruby
  Config Dir  /Users/carmenalexander/.rbenv/versions/3.0.4/etc
RubyGems      3.2.33
  Gem Home    /Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0
  Gem Path    /Users/carmenalexander/.gem/ruby/3.0.0:/Users/carmenalexander/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0
  User Home   /Users/carmenalexander
  User Path   /Users/carmenalexander/.gem/ruby/3.0.0
  Bin Dir     /Users/carmenalexander/.rbenv/versions/3.0.4/bin
OpenSSL
  Compiled    OpenSSL 1.1.1w  11 Sep 2023
  Loaded      OpenSSL 1.1.1w  11 Sep 2023
  Cert File   /usr/local/etc/openssl@1.1/cert.pem
  Cert Dir    /usr/local/etc/openssl@1.1/certs
Tools
  Git         2.43.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-01-25
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
<No /Users/carmenalexander/Desktop/digital-declaration-of-conformity/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Hei! Please upgrade Bundler & RubyGems and feel free to reopen if still not working. Thanks!
