### ISSUE TITLE
Ruby Gems Issue Feb 7th, 2024. Lots of Missing Package Metadata

### ISSUE THREAD

**Issue by cmhhelgeson** [rubygems/rubygems#7463]
Error report template is below:

Gem::Package::FormatError: package metadata is missing in /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/cache/irb-1.11.1.gem
  /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:693:in `verify_files'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:620:in `block (2 levels) in verify'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package/tar_reader.rb:25:in `new'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:617:in `block in verify'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package/file_source.rb:30:in `open'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:616:in `verify'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:597:in `spec'
          /root/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/installer.rb:291:in `spec'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/rubygems_gem_installer.rb:101:in `spec'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/source/rubygems.rb:186:in `install'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/gem_installer.rb:54:in `install'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:62:in `apply_func'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:57:in `block in process_queue'
          <internal:kernel>:187:in `loop'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:54:in `process_queue'
          /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.5.5
  Platforms   ruby, x86_64-linux
Ruby          3.3.0p0 (2023-12-25 revision 5124f9ac7513eb590c37717337c430cb93caa151) [x86_64-linux]
  Full Path   /root/.rbenv/versions/3.3.0/bin/ruby
  Config Dir  /root/.rbenv/versions/3.3.0/etc
RubyGems      3.5.6
  Gem Home    /root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0
  Gem Path    /root/.local/share/gem/ruby/3.3.0:/root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.3.0
  Bin Dir     /root/.rbenv/versions/3.3.0/bin
OpenSSL
  Compiled    OpenSSL 3.0.2 15 Mar 2022
  Loaded      OpenSSL 3.0.2 15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-01-18
Git SHA           2efa8cec93
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"

ruby "3.3.0"

# Rails
gem "rails", github: "rails/rails", branch: "main"

# Drivers
gem "pg", "~> 1.1"
gem "redis", ">= 4.0.1"

# Deployment
gem "puma", ">= 5.0"
gem "bootsnap", require: false

# Assets
gem "importmap-rails"
gem "propshaft"
gem "tailwindcss-rails"

# Hotwire
gem "stimulus-rails"
gem "turbo-rails"

# Other
gem "bcrypt", "~> 3.1.7"
gem "inline_svg"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "money-rails", "~> 1.12"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "dotenv-rails"
  gem "letter_opener"
  gem "i18n-tasks"
end

group :development do
  gem "web-console"
  gem "hotwire-livereload"
  gem "ruby-lsp-rails"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
```

### Gemfile.lock

```
GIT
  remote: https://github.com/rails/rails.git
  revision: f0d433bb46ac233ec7fd7fae48f458978908d905
  branch: main
  specs:
    actioncable (7.2.0.alpha)
      actionpack (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (7.2.0.alpha)
      actionpack (= 7.2.0.alpha)
      activejob (= 7.2.0.alpha)
      activerecord (= 7.2.0.alpha)
      activestorage (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      mail (>= 2.8.0)
    actionmailer (7.2.0.alpha)
      actionpack (= 7.2.0.alpha)
      actionview (= 7.2.0.alpha)
      activejob (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      mail (>= 2.8.0)
      rails-dom-testing (~> 2.2)
    actionpack (7.2.0.alpha)
      actionview (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      nokogiri (>= 1.8.5)
      racc
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
      useragent (~> 0.16)
    actiontext (7.2.0.alpha)
      actionpack (= 7.2.0.alpha)
      activerecord (= 7.2.0.alpha)
      activestorage (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    activejob (7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      globalid (>= 0.3.6)
    activemodel (7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
    activerecord (7.2.0.alpha)
      activemodel (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      timeout (>= 0.4.0)
    activestorage (7.2.0.alpha)
      actionpack (= 7.2.0.alpha)
      activejob (= 7.2.0.alpha)
      activerecord (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      marcel (~> 1.0)
    activesupport (7.2.0.alpha)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1, < 5.22.0)
      tzinfo (~> 2.0, >= 2.0.5)
    rails (7.2.0.alpha)
      actioncable (= 7.2.0.alpha)
      actionmailbox (= 7.2.0.alpha)
      actionmailer (= 7.2.0.alpha)
      actionpack (= 7.2.0.alpha)
      actiontext (= 7.2.0.alpha)
      actionview (= 7.2.0.alpha)
      activejob (= 7.2.0.alpha)
      activemodel (= 7.2.0.alpha)
      activerecord (= 7.2.0.alpha)
      activestorage (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      bundler (>= 1.15.0)
      railties (= 7.2.0.alpha)
    railties (7.2.0.alpha)
      actionpack (= 7.2.0.alpha)
      activesupport (= 7.2.0.alpha)
      irb
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.6)
      public_suffix (>= 2.0.2, < 6.0)
    ast (2.4.2)
    base64 (0.2.0)
    bcrypt (3.1.20)
    better_html (2.0.2)
      actionview (>= 6.0)
      activesupport (>= 6.0)
      ast (~> 2.0)
      erubi (~> 1.4)
      parser (>= 2.4)
      smart_properties
    bigdecimal (3.1.6)
    bindex (0.8.1)
    bootsnap (1.18.3)
      msgpack (~> 1.2)
    brakeman (6.1.2)
      racc
    builder (3.2.4)
    capybara (3.40.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.11)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.2.3)
    connection_pool (2.4.1)
    crass (1.0.6)
    date (3.3.4)
    debug (1.9.1)
      irb (~> 1.10)
      reline (>= 0.3.8)
    dotenv (2.8.1)
    dotenv-rails (2.8.1)
      dotenv (= 2.8.1)
      railties (>= 3.2)
    drb (2.2.0)
      ruby2_keywords
    erubi (1.12.0)
    ffi (1.16.3)
    globalid (1.2.1)
      activesupport (>= 6.1)
    highline (3.0.1)
    hotwire-livereload (1.3.1)
      actioncable (>= 6.0.0)
      listen (>= 3.0.0)
      railties (>= 6.0.0)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    i18n-tasks (1.0.13)
      activesupport (>= 4.0.2)
      ast (>= 2.1.0)
      better_html (>= 1.0, < 3.0)
      erubi
      highline (>= 2.0.0)
      i18n
      parser (>= 3.2.2.1)
      rails-i18n
      rainbow (>= 2.2.2, < 4.0)
      terminal-table (>= 1.5.1)
    importmap-rails (2.0.1)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    inline_svg (1.9.0)
      activesupport (>= 3.0)
      nokogiri (>= 1.6)
    io-console (0.7.2)
    irb (1.11.1)
      rdoc
      reline (>= 0.4.2)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    json (2.7.1)
    language_server-protocol (3.17.0.3)
    launchy (2.5.2)
      addressable (~> 2.8)
    letter_opener (1.8.1)
      launchy (>= 2.2, < 3)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    matrix (0.4.2)
    mini_mime (1.1.5)
    minitest (5.21.2)
    monetize (1.13.0)
      money (~> 6.12)
    money (6.16.0)
      i18n (>= 0.6.4, <= 2)
    money-rails (1.15.0)
      activesupport (>= 3.0)
      monetize (~> 1.9)
      money (~> 6.13)
      railties (>= 3.0)
    msgpack (1.7.2)
    net-imap (0.4.10)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.4.0.1)
      net-protocol
    nio4r (2.7.0)
    nokogiri (1.16.2-aarch64-linux)
      racc (~> 1.4)
    nokogiri (1.16.2-arm-linux)
      racc (~> 1.4)
    nokogiri (1.16.2-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.16.2-x86-linux)
      racc (~> 1.4)
    nokogiri (1.16.2-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.16.2-x86_64-linux)
      racc (~> 1.4)
    parallel (1.24.0)
    parser (3.3.0.5)
      ast (~> 2.4.1)
      racc
    pg (1.5.4)
    prism (0.19.0)
    propshaft (0.8.0)
      actionpack (>= 7.0.0)
      activesupport (>= 7.0.0)
      rack
      railties (>= 7.0.0)
    psych (5.1.2)
      stringio
    public_suffix (5.0.4)
    puma (6.4.2)
      nio4r (~> 2.0)
    racc (1.7.3)
    rack (3.0.9)
    rack-session (2.0.0)
      rack (>= 3.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (2.1.0)
      rack (>= 3)
      webrick (~> 1.8)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    rails-i18n (7.0.8)
      i18n (>= 0.7, < 2)
      railties (>= 6.0.0, < 8)
    rainbow (3.1.1)
    rake (13.1.0)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rdoc (6.6.2)
      psych (>= 4.0.0)
    redis (5.0.8)
      redis-client (>= 0.17.0)
    redis-client (0.19.1)
      connection_pool
    regexp_parser (2.9.0)
    reline (0.4.2)
      io-console (~> 0.5)
    rexml (3.2.6)
    rubocop (1.60.2)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.30.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.30.0)
      parser (>= 3.2.1.0)
    rubocop-minitest (0.34.5)
      rubocop (>= 1.39, < 2.0)
      rubocop-ast (>= 1.30.0, < 2.0)
    rubocop-performance (1.20.2)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.30.0, < 2.0)
    rubocop-rails (2.23.1)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
      rubocop-ast (>= 1.30.0, < 2.0)
    rubocop-rails-omakase (1.0.0)
      rubocop
      rubocop-minitest
      rubocop-performance
      rubocop-rails
    ruby-lsp (0.13.4)
      language_server-protocol (~> 3.17.0)
      prism (>= 0.19.0, < 0.20)
      sorbet-runtime (>= 0.5.10782)
    ruby-lsp-rails (0.2.9)
      actionpack (>= 6.0)
      activerecord (>= 6.0)
      railties (>= 6.0)
      ruby-lsp (>= 0.13.0, < 0.14.0)
      sorbet-runtime (>= 0.5.9897)
    ruby-progressbar (1.13.0)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.17.0)
      base64 (~> 0.2)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    smart_properties (1.17.0)
    sorbet-runtime (0.5.11226)
    stimulus-rails (1.3.3)
      railties (>= 6.0.0)
    stringio (3.1.0)
    tailwindcss-rails (2.3.0)
      railties (>= 6.0.0)
    tailwindcss-rails (2.3.0-aarch64-linux)
      railties (>= 6.0.0)
    tailwindcss-rails (2.3.0-arm-linux)
      railties (>= 6.0.0)
    tailwindcss-rails (2.3.0-arm64-darwin)
      railties (>= 6.0.0)
    tailwindcss-rails (2.3.0-x86_64-darwin)
      railties (>= 6.0.0)
    tailwindcss-rails (2.3.0-x86_64-linux)
      railties (>= 6.0.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    thor (1.3.0)
    timeout (0.4.1)
    turbo-rails (2.0.0)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)
    useragent (0.16.10)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webrick (1.8.1)
    websocket (1.2.10)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.13)

PLATFORMS
  aarch64-linux
  arm-linux
  arm64-darwin
  x86-linux
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  bcrypt (~> 3.1.7)
  bootsnap
  brakeman
  capybara
  debug
  dotenv-rails
  hotwire-livereload
  i18n-tasks
  importmap-rails
  inline_svg
  jbuilder
  letter_opener
  money-rails (~> 1.12)
  pg (~> 1.1)
  propshaft
  puma (>= 5.0)
  rails!
  redis (>= 4.0.1)
  rubocop-rails-omakase
  ruby-lsp-rails
  selenium-webdriver
  stimulus-rails
  tailwindcss-rails
  turbo-rails
  tzinfo-data
  web-console

RUBY VERSION
   ruby 3.3.0p0

BUNDLED WITH
   2.5.5

**Comment by deivid-rodriguez** [comment]
Is this still happening?

I guess this was some temporary issue in `rubygems.org` and working fine now? We could definitely use a better message if that's the case, but we'd need some postmortem analysis to understand what happened and it may be too late now?
