### ISSUE TITLE
Azure Devops android builds failing due to below error "failed to load command: fastlane (/usr/local/lib/ruby/gems/3.0.0/bin/fastlane)"

### ISSUE THREAD

**Issue by Prabhudevg92** [rubygems/rubygems#7469]
```
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/3.0.0/bin/fastlane)
/usr/local/lib/ruby/gems/3.0.0/gems/ffi-1.16.3/lib/ffi/dynamic_library.rb:65:in `load_library': Could not open library '/usr/local/lib/ruby/gems/3.0.0/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle': dlopen(/usr/local/lib/ruby/gems/3.0.0/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle, 0x0005): tried: '/usr/local/lib/ruby/gems/3.0.0/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))). (LoadError)
Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib

	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
##[debug]Exit code 1 received from tool '/bin/bash'

##[debug]STDIO streams have closed for tool '/bin/bash'
##[error]Bash exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
Finishing: Build Script copy copy
```

**Comment by ianhall** [comment]
I've seen similar here too, on a number of different machines.

The solution so far has been to force the `http` gem to version `5.1.1`

**Comment by ryantanlien** [comment]
This is due to an incorrect local setup for gems. I managed to fix it on my own local:

The fix:
1. Go to the gem installation location. Mine was: `.asdf/installs/ruby/2.7.8/lib/ruby/gems/2.7.0/gems/llhttp-ffi-0.5.0`. For you it should be: `/usr/local/lib/ruby/gems/3.0.0/gems/llhttp-ffi-0.5.0/`
2. Navigate to `ext` directory
3. Delete the `aarch64-darwin` folder with `rm -r aarch64-darwin`
4. Install the x86_64 version with `arch -x86_64 gem install llhttp-ffi`
5. `x86_64-darwin` folder should appear in the gem installation location.
6. Done!

This fix should be generalisable for any two architectures. Find out your processor architecture with `ruby -v`

**Comment by WoodyWoodsta** [comment]
This sounds more like a workaround than a fix. Why was the wrong architecture for the gem installed in the first place?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
