### ISSUE TITLE
LoadError when trying to install gem from local source

### ISSUE THREAD

**Issue by TJNII** [rubygems/rubygems#7474]
### Describe the problem as clearly as you can

When attempting to use a gem from a local path `require '[gemname]'` throws LoadError.

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

I have cloned https://github.com/svoboda-jan/asterisk-ari to a local branch, below my working directory:

```bash
$ ls ../asterisk-ari/
asterisk-ari-client.gemspec  examples  Gemfile  lib  LICENSE.txt  Rakefile  README.md  test
$ cat ../asterisk-ari/asterisk-ari-client.gemspec 
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'asterisk/ari/client/version'

Gem::Specification.new do |spec|
  spec.name          = "asterisk-ari-client"
  spec.version       = Asterisk::Ari::Client::VERSION
  spec.authors       = ["Jan Svoboda"]
  spec.email         = ["jan@mluv.cz"]
  spec.summary       = %q{Ruby client library for the Asterisk REST Interface (ARI).}
  spec.description   = %q{Ruby client library for the Asterisk REST Interface (ARI).}
  spec.homepage      = ""
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0")
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ["lib"]

  spec.required_ruby_version = ">= 1.9"

  spec.add_development_dependency "bundler"
  spec.add_development_dependency "rake"

  spec.add_development_dependency "minitest", "~> 5.4"
  spec.add_development_dependency "vcr", "~> 2.9"
  spec.add_development_dependency "webmock", "~> 1.19"

  spec.add_development_dependency "activesupport", "~> 4.1"

  spec.add_dependency "multi_json"
  spec.add_dependency "websocket-client-simple", "~> 0.2"
  spec.add_dependency "event_emitter", "~> 0.2"
end
```

In my working directory I have created a Gemfile containing the following, per https://bundler.io/v2.5/man/gemfile.5.html:

```ruby
$ cat Gemfile
source 'https://rubygems.org'

gem 'asterisk-ari-client', path: '../asterisk-ari/'
```

`bundle install` works as expected:

```bash
$ bundle install
Bundle complete! 1 Gemfile dependency, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ cat Gemfile.lock 
PATH
  remote: ../asterisk-ari
  specs:
    asterisk-ari-client (0.0.8)
      event_emitter (~> 0.2)
      multi_json
      websocket-client-simple (~> 0.2)

GEM
  remote: https://rubygems.org/
  specs:
    event_emitter (0.2.6)
    multi_json (1.15.0)
    websocket (1.2.10)
    websocket-client-simple (0.8.0)
      event_emitter
      websocket

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  asterisk-ari-client!

BUNDLED WITH
   2.5.6
```

However, when I try and `require` the gem I get `LoadError`:

```
$ bundle console
[DEPRECATED] bundle console will be replaced by `bin/console` generated by `bundle gem <name>`
irb(main):001:0> require 'asterisk-ari-client'
<internal:/home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- asterisk-ari-client (LoadError)
        from <internal:/home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from (irb):1:in `<main>'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli/console.rb:20:in `run'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:482:in `console'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
        from /home/tom/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
        from /home/tom/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
irb(main):002:0> 
```

I've used this Gemfile syntax successfully in other projects.  If this is user error I'm not spotting it.  The source gem is several years behind; this is why I'm trying to work out of a local checkout, I want to easily be able to update the gem if I find issues.  Nothing in the `asterisk-ari-client` gemspec is jumping out to me as incorrect, but I don't build enough gems to have an eye for that.

### What were you expecting to happen?

I was expecting the `require 'asterisk-ari-client'` to load the gem same as if it had been installed from RubyGems.

### What actually happened?

`require` threw `LoadError`

## Environment

```
Bundler       2.5.6
  Platforms   ruby, x86_64-linux
Ruby          3.2.3p157 (2024-01-18 revision 52bb2ac0a6971d0391efa2275f7a66bff319087c) [x86_64-linux]
  Full Path   /home/tom/.rbenv/versions/3.2.3/bin/ruby
  Config Dir  /home/tom/.rbenv/versions/3.2.3/etc
RubyGems      3.5.6
  Gem Home    /home/tom/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0
  Gem Path    /home/tom/.gem/ruby/3.2.0:/home/tom/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0
  User Home   /home/tom
  User Path   /home/tom/.gem/ruby/3.2.0
  Bin Dir     /home/tom/.rbenv/versions/3.2.3/bin
Tools         
  Git         2.39.2
  RVM         not installed
  rbenv       rbenv 1.1.2-11-gc46a970
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-02-06
Git SHA           7ac045dcaa
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'asterisk-ari-client', path: '../asterisk-ari/'
```

### Gemfile.lock

```
PATH
  remote: ../asterisk-ari
  specs:
    asterisk-ari-client (0.0.8)
      event_emitter (~> 0.2)
      multi_json
      websocket-client-simple (~> 0.2)

GEM
  remote: https://rubygems.org/
  specs:
    event_emitter (0.2.6)
    multi_json (1.15.0)
    websocket (1.2.10)
    websocket-client-simple (0.8.0)
      event_emitter
      websocket

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  asterisk-ari-client!

BUNDLED WITH
   2.5.6
```

**Comment by TJNII** [comment]
False issue, it's something with this gem.  Pulling from RubyGems:

```
$ cat Gemfile
source 'https://rubygems.org'

gem 'asterisk-ari-client'

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    asterisk-ari-client (0.0.8)
      event_emitter (~> 0.2.5)
      multi_json
      websocket-client-simple (~> 0.2.0)
    event_emitter (0.2.6)
    multi_json (1.15.0)
    websocket (1.2.10)
    websocket-client-simple (0.2.5)
      event_emitter
      websocket

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  asterisk-ari-client

BUNDLED WITH
   2.5.6
```

I get the same error:

```
$ bundle console
[DEPRECATED] bundle console will be replaced by `bin/console` generated by `bundle gem <name>`
irb(main):001:0> require 'asterisk-ari-client'
<internal:/home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- asterisk-ari-client (LoadError)
        from <internal:/home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from (irb):1:in `<main>'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli/console.rb:20:in `run'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:482:in `console'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /home/tom/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
        from /home/tom/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
        from /home/tom/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
```

I figured I'd need to touch this gem but I didn't think I'd need to start this early...
Closing as this looks like a compatibility issue with a old gem, not a bug.
