### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by phaedonv** [rubygems/rubygems#7512]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /usr/share/rvm/gems/ruby-3.2.2 directory.
  /usr/share/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/installer.rb:712:in `verify_gem_home'
  /usr/share/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/installer.rb:902:in `pre_install_checks'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:64:in `pre_install_checks'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:12:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/source/rubygems.rb:203:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:130:in `do_install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:115:in `install_serially'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:91:in `call'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:67:in `call'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer.rb:244:in `install_in_parallel'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer.rb:201:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer.rb:89:in `block in run'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/process_lock.rb:19:in `rescue in lock'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/process_lock.rb:15:in `lock'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer.rb:71:in `run'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer.rb:23:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli/install.rb:62:in `run'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:261:in `block in install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/settings.rb:142:in `temporary'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:260:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
  /usr/share/rvm/gems/ruby-3.2.2/bin/bundle:25:in `load'
  /usr/share/rvm/gems/ruby-3.2.2/bin/bundle:25:in `<main>'
Errno::EACCES: Permission denied @ rb_sysopen - /usr/share/rvm/gems/ruby-3.2.2/bundler.lock
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/process_lock.rb:9:in `initialize'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer.rb:71:in `run'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/installer.rb:23:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli/install.rb:62:in `run'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:261:in `block in install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/settings.rb:142:in `temporary'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:260:in `install'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/share/rvm/gems/ruby-3.2.2/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
  /usr/share/rvm/gems/ruby-3.2.2/bin/bundle:25:in `load'
  /usr/share/rvm/gems/ruby-3.2.2/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler             2.4.21
  Platforms         ruby, x86_64-linux
Ruby                3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux]
  Full Path         /usr/share/rvm/rubies/ruby-3.2.2/bin/ruby
  Config Dir        /etc
RubyGems            3.4.10
  Gem Home          /usr/share/rvm/gems/ruby-3.2.2
  Gem Path          /usr/share/rvm/gems/ruby-3.2.2:/usr/share/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0
  User Home         /home/tester
  User Path         /home/tester/.local/share/gem/ruby/3.2.0
  Bin Dir           /usr/share/rvm/gems/ruby-3.2.2/bin
OpenSSL
  Compiled          OpenSSL 3.0.2 15 Mar 2022
  Loaded            OpenSSL 3.0.2 15 Mar 2022
  Cert File         /usr/lib/ssl/cert.pem
  Cert Dir          /usr/lib/ssl/certs
Tools
  Git               2.34.1
  RVM               1.29.12 (manual)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2023-10-17
Git SHA           d10b46bd15
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

ruby '3.2.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.1.2'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.5', '>= 1.5.4'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"
gem 'devise'
gem 'devise-jwt'
gem 'jsonapi-serializer'
gem 'rack-cors'
# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.1.2)
      actionpack (= 7.1.2)
      activesupport (= 7.1.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (7.1.2)
      actionpack (= 7.1.2)
      activejob (= 7.1.2)
      activerecord (= 7.1.2)
      activestorage (= 7.1.2)
      activesupport (= 7.1.2)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.1.2)
      actionpack (= 7.1.2)
      actionview (= 7.1.2)
      activejob (= 7.1.2)
      activesupport (= 7.1.2)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.2)
    actionpack (7.1.2)
      actionview (= 7.1.2)
      activesupport (= 7.1.2)
      nokogiri (>= 1.8.5)
      racc
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    actiontext (7.1.2)
      actionpack (= 7.1.2)
      activerecord (= 7.1.2)
      activestorage (= 7.1.2)
      activesupport (= 7.1.2)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.1.2)
      activesupport (= 7.1.2)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    activejob (7.1.2)
      activesupport (= 7.1.2)
      globalid (>= 0.3.6)
    activemodel (7.1.2)
      activesupport (= 7.1.2)
    activerecord (7.1.2)
      activemodel (= 7.1.2)
      activesupport (= 7.1.2)
      timeout (>= 0.4.0)
    activestorage (7.1.2)
      actionpack (= 7.1.2)
      activejob (= 7.1.2)
      activerecord (= 7.1.2)
      activesupport (= 7.1.2)
      marcel (~> 1.0)
    activesupport (7.1.2)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    base64 (0.2.0)
    bcrypt (3.1.20)
    bigdecimal (3.1.4)
    bootsnap (1.17.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    concurrent-ruby (1.2.2)
    connection_pool (2.4.1)
    crass (1.0.6)
    date (3.3.4)
    debug (1.8.0)
      irb (>= 1.5.0)
      reline (>= 0.3.1)
    devise (4.9.3)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-jwt (0.11.0)
      devise (~> 4.0)
      warden-jwt_auth (~> 0.8)
    drb (2.2.0)
      ruby2_keywords
    dry-auto_inject (1.0.1)
      dry-core (~> 1.0)
      zeitwerk (~> 2.6)
    dry-configurable (1.1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-core (1.0.1)
      concurrent-ruby (~> 1.0)
      zeitwerk (~> 2.6)
    erubi (1.12.0)
    globalid (1.2.1)
      activesupport (>= 6.1)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    io-console (0.6.0)
    irb (1.9.1)
      rdoc
      reline (>= 0.3.8)
    jsonapi-serializer (2.2.0)
      activesupport (>= 4.2)
    jwt (2.7.1)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    mini_mime (1.1.5)
    minitest (5.20.0)
    msgpack (1.7.2)
    mutex_m (0.2.0)
    net-imap (0.4.7)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.4.0)
      net-protocol
    nio4r (2.6.1)
    nokogiri (1.15.5-x64-mingw-ucrt)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    pg (1.5.4-x64-mingw-ucrt)
    psych (5.1.1.1)
      stringio
    puma (6.4.0)
      nio4r (~> 2.0)
    racc (1.7.3)
    rack (3.0.8)
    rack-cors (2.0.1)
      rack (>= 2.0.0)
    rack-session (2.0.0)
      rack (>= 3.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (2.1.0)
      rack (>= 3)
      webrick (~> 1.8)
    rails (7.1.2)
      actioncable (= 7.1.2)
      actionmailbox (= 7.1.2)
      actionmailer (= 7.1.2)
      actionpack (= 7.1.2)
      actiontext (= 7.1.2)
      actionview (= 7.1.2)
      activejob (= 7.1.2)
      activemodel (= 7.1.2)
      activerecord (= 7.1.2)
      activestorage (= 7.1.2)
      activesupport (= 7.1.2)
      bundler (>= 1.15.0)
      railties (= 7.1.2)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.1.2)
      actionpack (= 7.1.2)
      activesupport (= 7.1.2)
      irb
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rake (13.1.0)
    rdoc (6.6.0)
      psych (>= 4.0.0)
    reline (0.4.1)
      io-console (~> 0.5)
    responders (3.1.1)
      actionpack (>= 5.2)
      railties (>= 5.2)
    ruby2_keywords (0.0.5)
    stringio (3.1.0)
    thor (1.3.0)
    timeout (0.4.1)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2024.1)
      tzinfo (>= 1.0.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    warden-jwt_auth (0.8.0)
      dry-auto_inject (>= 0.8, < 2)
      dry-configurable (>= 0.13, < 2)
      jwt (~> 2.1)
      warden (~> 1.2)
    webrick (1.8.1)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    zeitwerk (2.6.12)

PLATFORMS
  x64-mingw-ucrt

DEPENDENCIES
  bootsnap
  debug
  devise
  devise-jwt
  jsonapi-serializer
  pg (~> 1.5, >= 1.5.4)
  puma (>= 5.0)
  rack-cors
  rails (~> 7.1.2)
  tzinfo-data

RUBY VERSION
   ruby 3.2.2p53

BUNDLED WITH
   2.4.21
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by martinemde** [comment]
You don't have write permissions to the places where Ruby installs gems.

In this case `/usr/share/rvm/gems/ruby-3.2.2`.

What way did you install rvm and Ruby? If you used sudo, then you have probably created a directory owned by root.

I suggest searching the web for a solution. I found this: https://stackoverflow.com/questions/60204349/unable-to-install-rails-error-you-dont-have-write-permissions-for-the-usr-lo
