### ISSUE TITLE
NoMethodError: undefined method `parse' for #<Psych::Parser:0x00007f4db9c41a90 

### ISSUE THREAD

**Issue by aliccardo** [rubygems/rubygems#7559]
error updating bundler with:
```
$ rvm use
/home/myuser/.rvm/gems/ruby-3.1.2

$ bundle update --bundler
```
This is what  has been suggested to insert as report:
```
NoMethodError: undefined method `parse' for #<Psych::Parser:0x00007f4db9c41a90 @handler=#<Psych::Handlers::DocumentStream:0x00007f4db9c41ba8 @stack=[], @last=nil, @root=nil, @start_line=nil, @start_column=nil, @end_line=nil, @end_column=nil, @block=#<Proc:0x00007f4db9c41ae0 /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/3.1.0/psych.rb:399>>, @external_encoding=0>

      parser.parse yaml, filename
    ^^^^^^
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/3.1.0/psych.rb:455:in `parse_stream'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/3.1.0/psych.rb:399:in `parse'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/3.1.0/psych.rb:324:in `safe_load'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/safe_yaml.rb:32:in `safe_load'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:560:in `block (2 levels) in read_checksums'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:559:in `wrap'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:559:in `block in read_checksums'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package/tar_reader.rb:93:in `seek'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:558:in `read_checksums'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:618:in `block (2 levels) in verify'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package/tar_reader.rb:23:in `new'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:617:in `block in verify'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package/file_source.rb:30:in `open'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:616:in `verify'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/package.rb:597:in `spec'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/rubygems/installer.rb:288:in `spec'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/rubygems_gem_installer.rb:101:in `spec'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/source/rubygems.rb:186:in `install'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/self_manager.rb:60:in `install'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/self_manager.rb:35:in `update_bundler_and_restart_with_it_if_needed'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/cli/update.rb:16:in `run'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/cli.rb:311:in `block in update'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/settings.rb:142:in `temporary'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/cli.rb:310:in `update'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/cli.rb:34:in `dispatch'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/cli.rb:28:in `start'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/gems/3.1.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /home/myuser/.rvm/rubies/ruby-3.1.2/lib64/ruby/gems/3.1.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
  /home/myuser/.rvm/rubies/ruby-3.1.2/bin/bundle:25:in `load'
  /home/myuser/.rvm/rubies/ruby-3.1.2/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.22
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /home/myuser/.rvm/rubies/ruby-3.1.2/bin/ruby
  Config Dir  /home/myuser/.rvm/rubies/ruby-3.1.2/etc
RubyGems      3.4.22
  Gem Home    /home/myuser/.rvm/gems/ruby-3.1.2
  Gem Path    /home/myuser/.rvm/gems/ruby-3.1.2:/home/myuser/.rvm/gems/ruby-3.1.2@global
  User Home   /home/myuser
  User Path   /home/myuser/.gem/ruby/3.1.0
  Bin Dir     /home/myuser/.rvm/gems/ruby-3.1.2/bin
OpenSSL       
  Compiled    OpenSSL 3.0.7 1 Nov 2022
  Loaded      OpenSSL 3.1.4 24 Oct 2023
  Cert File   /var/lib/ca-certificates/ca-bundle.pem
  Cert Dir    /var/lib/ca-certificates/openssl
Tools         
  Git         2.44.0
  RVM         1.29.12 (latest)
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-11-09
Git SHA           ec2089640
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'http://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'bcrypt'

# JSON
gem 'oj', '~> 3.13', '>= 3.13.14'

gem 'rake'
gem 'thor', '~> 1.2', '>= 1.2.2'
gem 'require_all'
# REST call
gem 'typhoeus'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development do
  gem 'reek' # , '~> 5.5.0'
  gem 'solargraph'
end

group :development, :test do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'parallel_tests'
  gem 'irb'
  gem 'rubocop'
end
```

### Gemfile.lock

```
GEM
  remote: http://rubygems.org/
  specs:
    ast (2.4.2)
    awesome_print (1.9.2)
    backport (1.2.0)
    base64 (0.1.1)
    bcrypt (3.1.19)
    benchmark (0.2.1)
    better_errors (2.10.1)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
      rouge (>= 1.0.0)
    diff-lcs (1.5.0)
    e2mmap (0.1.0)
    erubi (1.12.0)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    ffi (1.15.5)
    io-console (0.6.0)
    irb (1.8.1)
      rdoc
      reline (>= 0.3.8)
    jaro_winkler (1.5.6)
    json (2.6.3)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    kwalify (0.7.2)
    language_server-protocol (3.17.0.3)
    nokogiri (1.15.4-x86_64-linux)
      racc (~> 1.4)
    oj (3.16.1)
    parallel (1.23.0)
    parallel_tests (4.2.2)
      parallel
    parser (3.2.2.3)
      ast (~> 2.4.1)
      racc
    psych (5.1.0)
      stringio
    racc (1.7.1)
    rack (3.0.8)
    rainbow (3.1.1)
    rake (13.0.6)
    rbs (2.8.4)
    rdoc (6.5.0)
      psych (>= 4.0.0)
    reek (6.1.4)
      kwalify (~> 0.7.0)
      parser (~> 3.2.0)
      rainbow (>= 2.0, < 4.0)
    regexp_parser (2.8.1)
    reline (0.3.8)
      io-console (~> 0.5)
    require_all (3.0.0)
    reverse_markdown (2.1.1)
      nokogiri
    rexml (3.2.6)
    rouge (4.1.3)
    rubocop (1.56.2)
      base64 (~> 0.1.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.2.2.3)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.28.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.29.0)
      parser (>= 3.2.1.0)
    ruby-progressbar (1.13.0)
    solargraph (0.49.0)
      backport (~> 1.2)
      benchmark
      bundler (~> 2.0)
      diff-lcs (~> 1.4)
      e2mmap
      jaro_winkler (~> 1.5)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.1)
      parser (~> 3.0)
      rbs (~> 2.0)
      reverse_markdown (~> 2.0)
      rubocop (~> 1.38)
      thor (~> 1.0)
      tilt (~> 2.0)
      yard (~> 0.9, >= 0.9.24)
    stringio (3.0.8)
    thor (1.2.2)
    tilt (2.2.0)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    unicode-display_width (2.4.2)
    yard (0.9.34)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  awesome_print
  bcrypt
  better_errors
  irb
  oj (~> 3.13, >= 3.13.14)
  parallel_tests
  rake
  reek
  require_all
  rubocop
  solargraph
  thor (~> 1.2, >= 1.2.2)
  typhoeus
  tzinfo-data

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.4.19
```

**Comment by hsbt** [comment]
See https://github.com/ruby/psych/discussions/607. It caused your environment mixed Psych 4 and 3 versions. You may resolve that with Bundler 2.4+.

**Comment by aliccardo** [comment]
Thank you for the time spent. I'm sorry I was not aware of this before!
