### ISSUE TITLE
wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by kalashnikovisme** [rubygems/rubygems#7606]
Just upgraded my app to Ruby-3.3.1, and received this on `bundle install`.

I use ruby with ruby-3.3.1-slim-bullseye image.

```
LoadError: /usr/local/bundle/gems/psych-5.1.2/lib/psych.so: wrong ELF class: ELFCLASS64 - /usr/local/bundle/gems/psych-5.1.2/lib/psych.so
  <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          /usr/local/bundle/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'
          <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          /usr/local/lib/ruby/3.3.0/rubygems.rb:594:in `load_yaml'
          /usr/local/lib/ruby/3.3.0/rubygems/package.rb:556:in `read_checksums'
          /usr/local/lib/ruby/3.3.0/rubygems/package.rb:618:in `block (2 levels) in verify'
          /usr/local/lib/ruby/3.3.0/rubygems/package/tar_reader.rb:25:in `new'
          /usr/local/lib/ruby/3.3.0/rubygems/package.rb:617:in `block in verify'
          /usr/local/lib/ruby/3.3.0/rubygems/package/file_source.rb:30:in `open'
          /usr/local/lib/ruby/3.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
          /usr/local/lib/ruby/3.3.0/rubygems/package.rb:616:in `verify'
          /usr/local/lib/ruby/3.3.0/rubygems/package.rb:597:in `spec'
          /usr/local/lib/ruby/3.3.0/rubygems/installer.rb:291:in `spec'
          /usr/local/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:101:in `spec'
          /usr/local/lib/ruby/3.3.0/bundler/source/rubygems.rb:186:in `install'
          /usr/local/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:54:in `install'
          /usr/local/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
          /usr/local/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:132:in `do_install'
          /usr/local/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
          /usr/local/lib/ruby/3.3.0/bundler/worker.rb:62:in `apply_func'
          /usr/local/lib/ruby/3.3.0/bundler/worker.rb:57:in `block in process_queue'
          <internal:kernel>:187:in `loop'
          /usr/local/lib/ruby/3.3.0/bundler/worker.rb:54:in `process_queue'
          /usr/local/lib/ruby/3.3.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.5.9
  Platforms   ruby, x86-linux
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [x86-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.5.9
  Gem Home    /usr/local/bundle
  Gem Path    /app/tmp/cache/gem/ruby/3.3.0:/usr/local/lib/ruby/gems/3.3.0:/usr/local/bundle
  User Home   /root
  User Path   /app/tmp/cache/gem/ruby/3.3.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 3.0.11 19 Sep 2023
  Loaded      OpenSSL 3.0.11 19 Sep 2023
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.39.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-04-23
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: ".bundle"
jobs
  Set via BUNDLE_JOBS: 4
retry
  Set via BUNDLE_RETRY: 3
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.1'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '7.1.3.2'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 6'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails', '~> 1'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]
gem 'tailwindcss-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# Dry gems for service management
gem 'dry-initializer', '~> 3.1'
gem 'dry-monads', '~> 1.6'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Configuration library
gem 'anyway_config'

# State machine
gem 'aasm'

# Swagger UI
gem 'rswag', '>= 2.11'

# Background-processing
gem 'sidekiq', '>= 7.1.6'
gem 'sidekiq-scheduler', '~> 5.0'
gem 'sidekiq-status', '~> 3.0'

# Cross-domain security for rack server
gem 'rack-cors', '~> 2.0'

# JWT encoding
gem 'jwt', '~> 2.7'

# third-party services base client
gem 'httpparty', '~> 0.2.0'

# Phone validation
gem 'phonelib', '~> 0.8.4'

# Modern and easy-to-use enumerization
gem 'enumerize', '~> 2.7'

# ActiveRecord JSON serialization
gem 'active_model_serializers', '~> 0.10.14'

# Logging every action of changing database
gem 'paper_trail', '~> 15.1.0'

# Soft-deletion for every model
gem 'acts_as_paranoid', '~> 0.9.0'

# Generation values
gem 'faker'

# User permissions management in admin panel
gem 'cancancan'
gem 'pundit'

# Authorization for admin panel
gem 'devise'

# Admin panel framework
# gem 'tramway', '0.4.4'
gem 'tramway', github: 'purple-magic/tramway', branch: 'select_fix_10.04'
gem 'view_component'

# Using HAML templates
gem 'haml-rails', '~> 2.1'

# Use PostgreSQL full text search
gem 'pg_search'

# Money management in Rails
gem 'money-rails', '~> 1.15'

# Using Google cloud functions
gem 'functions_framework', '~> 1.4'

# Using S3 compatible framework
gem 'aws-sdk-s3', require: false

# Use 3D bin packing algo
gem 'box_packer'

# Google Cloud Authorization
gem 'googleauth', '~> 1.8'

# Pagination for Rails applications
gem 'kaminari', '~> 1.2'

# Exception catcher service
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sentry-sidekiq', '~> 5.15'

# Export to Excel
gem 'caxlsx_rails'

# Static pages
gem 'high_voltage', '~> 3.1'

# Image processing for active_storage
gem 'image_processing', '~> 1.12'

# Firebase client
gem 'fcm', '>= 1.0.8'

group :development, :test do
  gem 'pry'
end

group :development do
  gem 'rubocop', '~> 1.51', require: false
  gem 'rubocop-rails', require: false
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'factory_bot_rails'
  gem 'json_api_test_helpers'
  gem 'rspec-rails'
  gem 'rspec-sidekiq'
  gem 'selenium-webdriver'
  gem 'timecop', '~> 0.9.8'
  gem 'turbo_tests', '~> 2.2'
  gem 'vcr'
  gem 'webdrivers'
  gem 'webmock'
end

gem 'data_migrate', '~> 9.2'

gem 'ransack', '~> 4.1'
```

### Gemfile.lock

```
GIT
  remote: https://github.com/purple-magic/tramway.git
  revision: 3050915622ec04dfa16b7e5e21a3efa966cd4837
  branch: select_fix_10.04
  specs:
    tramway (0.4.4)
      dry-struct
      haml-rails
      rails (~> 7)
      view_component

GEM
  remote: https://rubygems.org/
  specs:
    aasm (5.5.0)
      concurrent-ruby (~> 1.0)
    actioncable (7.1.3.2)
      actionpack (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (7.1.3.2)
      actionpack (= 7.1.3.2)
      activejob (= 7.1.3.2)
      activerecord (= 7.1.3.2)
      activestorage (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.1.3.2)
      actionpack (= 7.1.3.2)
      actionview (= 7.1.3.2)
      activejob (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.2)
    actionpack (7.1.3.2)
      actionview (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      nokogiri (>= 1.8.5)
      racc
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    actiontext (7.1.3.2)
      actionpack (= 7.1.3.2)
      activerecord (= 7.1.3.2)
      activestorage (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.1.3.2)
      activesupport (= 7.1.3.2)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    active_model_serializers (0.10.14)
      actionpack (>= 4.1)
      activemodel (>= 4.1)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    activejob (7.1.3.2)
      activesupport (= 7.1.3.2)
      globalid (>= 0.3.6)
    activemodel (7.1.3.2)
      activesupport (= 7.1.3.2)
    activerecord (7.1.3.2)
      activemodel (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      timeout (>= 0.4.0)
    activestorage (7.1.3.2)
      actionpack (= 7.1.3.2)
      activejob (= 7.1.3.2)
      activerecord (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      marcel (~> 1.0)
    activesupport (7.1.3.2)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    acts_as_paranoid (0.9.0)
      activerecord (>= 6.1, < 7.2)
      activesupport (>= 6.1, < 7.2)
    addressable (2.8.6)
      public_suffix (>= 2.0.2, < 6.0)
    anyway_config (2.6.3)
      ruby-next-core (~> 1.0)
    ast (2.4.2)
    aws-eventstream (1.3.0)
    aws-partitions (1.910.0)
    aws-sdk-core (3.191.6)
      aws-eventstream (~> 1, >= 1.3.0)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.8)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.78.0)
      aws-sdk-core (~> 3, >= 3.191.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.146.1)
      aws-sdk-core (~> 3, >= 3.191.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.8)
    aws-sigv4 (1.8.0)
      aws-eventstream (~> 1, >= 1.0.2)
    base64 (0.2.0)
    bcrypt (3.1.20)
    bigdecimal (3.1.7)
    bindex (0.8.1)
    bootsnap (1.18.3)
      msgpack (~> 1.2)
    box_packer (2.0.4)
    builder (3.2.4)
    cancancan (3.5.0)
    capybara (3.40.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.11)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    case_transform (0.2)
      activesupport
    caxlsx (4.1.0)
      htmlentities (~> 4.3, >= 4.3.4)
      marcel (~> 1.0)
      nokogiri (~> 1.10, >= 1.10.4)
      rubyzip (>= 1.3.0, < 3)
    caxlsx_rails (0.6.3)
      actionpack (>= 3.1)
      caxlsx (>= 3.0)
    chronic_duration (0.10.6)
      numerizer (~> 0.1.1)
    cloud_events (0.7.1)
    coderay (1.1.3)
    concurrent-ruby (1.2.3)
    connection_pool (2.4.1)
    crack (1.0.0)
      bigdecimal
      rexml
    crass (1.0.6)
    data_migrate (9.3.0)
      activerecord (>= 6.1)
      railties (>= 6.1)
    date (3.3.4)
    devise (4.9.3)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.5.1)
    drb (2.2.1)
    dry-core (1.0.1)
      concurrent-ruby (~> 1.0)
      zeitwerk (~> 2.6)
    dry-inflector (1.0.0)
    dry-initializer (3.1.1)
    dry-logic (1.5.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-monads (1.6.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-struct (1.6.0)
      dry-core (~> 1.0, < 2)
      dry-types (>= 1.7, < 2)
      ice_nine (~> 0.11)
      zeitwerk (~> 2.6)
    dry-types (1.7.2)
      bigdecimal (~> 3.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0)
      dry-inflector (~> 1.0)
      dry-logic (~> 1.4)
      zeitwerk (~> 2.6)
    enumerize (2.8.1)
      activesupport (>= 3.2)
    erubi (1.12.0)
    et-orbi (1.2.11)
      tzinfo
    factory_bot (6.4.6)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.4.3)
      factory_bot (~> 6.4)
      railties (>= 5.0.0)
    faker (3.3.1)
      i18n (>= 1.8.11, < 2)
    faraday (2.9.0)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-net_http (3.1.0)
      net-http
    fcm (1.0.8)
      faraday (>= 1.0.0, < 3.0)
      googleauth (~> 1)
    ffi (1.16.3)
    fugit (1.10.1)
      et-orbi (~> 1, >= 1.2.7)
      raabro (~> 1.4)
    functions_framework (1.4.1)
      cloud_events (>= 0.7.0, < 2.a)
      puma (>= 4.3.0, < 7.a)
      rack (>= 2.1, < 4.a)
    globalid (1.2.1)
      activesupport (>= 6.1)
    google-cloud-env (2.1.1)
      faraday (>= 1.0, < 3.a)
    googleauth (1.11.0)
      faraday (>= 1.0, < 3.a)
      google-cloud-env (~> 2.1)
      jwt (>= 1.4, < 3.0)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    haml (6.3.0)
      temple (>= 0.8.2)
      thor
      tilt
    haml-rails (2.1.0)
      actionpack (>= 5.1)
      activesupport (>= 5.1)
      haml (>= 4.0.6)
      railties (>= 5.1)
    hashdiff (1.1.0)
    high_voltage (3.1.2)
    htmlentities (4.3.4)
    httparty (0.21.0)
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    httpparty (0.2.0)
      httparty (> 0)
    i18n (1.14.4)
      concurrent-ruby (~> 1.0)
    ice_nine (0.11.2)
    image_processing (1.12.2)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    importmap-rails (2.0.1)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.7.2)
    irb (1.12.0)
      rdoc
      reline (>= 0.4.2)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jmespath (1.6.2)
    json (2.7.2)
    json-schema (4.3.0)
      addressable (>= 2.8)
    json_api_test_helpers (1.2.1.2)
    jsonapi-renderer (0.2.2)
    jwt (2.8.1)
      base64
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    language_server-protocol (3.17.0.3)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.4)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_magick (4.12.0)
    mini_mime (1.1.5)
    minitest (5.22.3)
    monetize (1.13.0)
      money (~> 6.12)
    money (6.19.0)
      i18n (>= 0.6.4, <= 2)
    money-rails (1.15.0)
      activesupport (>= 3.0)
      monetize (~> 1.9)
      money (~> 6.13)
      railties (>= 3.0)
    msgpack (1.7.2)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    mutex_m (0.2.0)
    net-http (0.4.1)
      uri
    net-imap (0.4.10)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.5.0)
      net-protocol
    nio4r (2.7.1)
    nokogiri (1.16.3-x86_64-linux)
      racc (~> 1.4)
    numerizer (0.1.1)
    orm_adapter (0.5.0)
    os (1.1.4)
    paper_trail (15.1.0)
      activerecord (>= 6.1)
      request_store (~> 1.4)
    parallel (1.24.0)
    parallel_tests (4.6.1)
      parallel
    parser (3.3.0.5)
      ast (~> 2.4.1)
      racc
    pg (1.5.6)
    pg_search (2.3.6)
      activerecord (>= 5.2)
      activesupport (>= 5.2)
    phonelib (0.8.8)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    psych (5.1.2)
      stringio
    public_suffix (5.0.5)
    puma (6.4.2)
      nio4r (~> 2.0)
    pundit (2.3.1)
      activesupport (>= 3.0.0)
    raabro (1.4.0)
    racc (1.7.3)
    rack (3.0.10)
    rack-cors (2.0.2)
      rack (>= 2.0.0)
    rack-session (2.0.0)
      rack (>= 3.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (2.1.0)
      rack (>= 3)
      webrick (~> 1.8)
    rails (7.1.3.2)
      actioncable (= 7.1.3.2)
      actionmailbox (= 7.1.3.2)
      actionmailer (= 7.1.3.2)
      actionpack (= 7.1.3.2)
      actiontext (= 7.1.3.2)
      actionview (= 7.1.3.2)
      activejob (= 7.1.3.2)
      activemodel (= 7.1.3.2)
      activerecord (= 7.1.3.2)
      activestorage (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      bundler (>= 1.15.0)
      railties (= 7.1.3.2)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.1.3.2)
      actionpack (= 7.1.3.2)
      activesupport (= 7.1.3.2)
      irb
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rainbow (3.1.1)
    rake (13.2.1)
    ransack (4.1.1)
      activerecord (>= 6.1.5)
      activesupport (>= 6.1.5)
      i18n
    rdoc (6.6.3.1)
      psych (>= 4.0.0)
    redis (4.8.1)
    redis-client (0.21.1)
      connection_pool
    regexp_parser (2.9.0)
    reline (0.5.0)
      io-console (~> 0.5)
    request_store (1.6.0)
      rack (>= 1.4)
    responders (3.1.1)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.2.6)
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.0)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-rails (6.1.2)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (~> 3.13)
      rspec-expectations (~> 3.13)
      rspec-mocks (~> 3.13)
      rspec-support (~> 3.13)
    rspec-sidekiq (4.1.0)
      rspec-core (~> 3.0)
      rspec-expectations (~> 3.0)
      rspec-mocks (~> 3.0)
      sidekiq (>= 5, < 8)
    rspec-support (3.13.1)
    rswag (2.13.0)
      rswag-api (= 2.13.0)
      rswag-specs (= 2.13.0)
      rswag-ui (= 2.13.0)
    rswag-api (2.13.0)
      activesupport (>= 3.1, < 7.2)
      railties (>= 3.1, < 7.2)
    rswag-specs (2.13.0)
      activesupport (>= 3.1, < 7.2)
      json-schema (>= 2.2, < 5.0)
      railties (>= 3.1, < 7.2)
      rspec-core (>= 2.14)
    rswag-ui (2.13.0)
      actionpack (>= 3.1, < 7.2)
      railties (>= 3.1, < 7.2)
    rubocop (1.63.0)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.31.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.31.2)
      parser (>= 3.3.0.4)
    rubocop-rails (2.24.1)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    ruby-next-core (1.0.2)
    ruby-progressbar (1.13.0)
    ruby-vips (2.2.1)
      ffi (~> 1.12)
    rubyzip (2.3.2)
    rufus-scheduler (3.9.1)
      fugit (~> 1.1, >= 1.1.6)
    selenium-webdriver (4.10.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sentry-rails (5.17.2)
      railties (>= 5.0)
      sentry-ruby (~> 5.17.2)
    sentry-ruby (5.17.2)
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
    sentry-sidekiq (5.17.2)
      sentry-ruby (~> 5.17.2)
      sidekiq (>= 3.0)
    sidekiq (7.2.2)
      concurrent-ruby (< 2)
      connection_pool (>= 2.3.0)
      rack (>= 2.2.4)
      redis-client (>= 0.19.0)
    sidekiq-scheduler (5.0.3)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 6, < 8)
      tilt (>= 1.4.0)
    sidekiq-status (3.0.3)
      chronic_duration
      sidekiq (>= 6.0, < 8)
    signet (0.19.0)
      addressable (~> 2.8)
      faraday (>= 0.17.5, < 3.a)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    stimulus-rails (1.3.3)
      railties (>= 6.0.0)
    stringio (3.1.0)
    tailwindcss-rails (2.4.0-x86_64-linux)
      railties (>= 6.0.0)
    temple (0.10.3)
    thor (1.3.1)
    tilt (2.3.0)
    timecop (0.9.8)
    timeout (0.4.1)
    turbo-rails (1.5.0)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    turbo_tests (2.2.1)
      json (~> 2.3)
      parallel_tests (>= 3.3.0, < 5)
      rspec (>= 3.10)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)
    uri (0.13.0)
    vcr (6.2.0)
    view_component (3.11.0)
      activesupport (>= 5.2.0, < 8.0)
      concurrent-ruby (~> 1.0)
      method_source (~> 1.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.3.1)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0, < 4.11)
    webmock (3.23.0)
      addressable (>= 2.8.0)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)
    webrick (1.8.1)
    websocket (1.2.10)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.13)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  aasm
  active_model_serializers (~> 0.10.14)
  acts_as_paranoid (~> 0.9.0)
  anyway_config
  aws-sdk-s3
  bootsnap
  box_packer
  cancancan
  capybara
  caxlsx_rails
  data_migrate (~> 9.2)
  devise
  dry-initializer (~> 3.1)
  dry-monads (~> 1.6)
  enumerize (~> 2.7)
  factory_bot_rails
  faker
  fcm (>= 1.0.8)
  functions_framework (~> 1.4)
  googleauth (~> 1.8)
  haml-rails (~> 2.1)
  high_voltage (~> 3.1)
  httpparty (~> 0.2.0)
  image_processing (~> 1.12)
  importmap-rails
  jbuilder
  json_api_test_helpers
  jwt (~> 2.7)
  kaminari (~> 1.2)
  money-rails (~> 1.15)
  paper_trail (~> 15.1.0)
  pg (~> 1.1)
  pg_search
  phonelib (~> 0.8.4)
  pry
  puma (~> 6)
  pundit
  rack-cors (~> 2.0)
  rails (= 7.1.3.2)
  ransack (~> 4.1)
  redis (~> 4.0)
  rspec-rails
  rspec-sidekiq
  rswag (>= 2.11)
  rubocop (~> 1.51)
  rubocop-rails
  selenium-webdriver
  sentry-rails
  sentry-ruby
  sentry-sidekiq (~> 5.15)
  sidekiq (>= 7.1.6)
  sidekiq-scheduler (~> 5.0)
  sidekiq-status (~> 3.0)
  sprockets-rails
  stimulus-rails
  tailwindcss-rails
  timecop (~> 0.9.8)
  tramway!
  turbo-rails (~> 1)
  turbo_tests (~> 2.2)
  tzinfo-data
  vcr
  view_component
  web-console
  webdrivers
  webmock

RUBY VERSION
   ruby 3.2.3p157

BUNDLED WITH
   2.5.6
```

**Comment by kalashnikovisme** [comment]
I mixed up the environments. Sorry.
