### ISSUE TITLE
run bundle install error

### ISSUE THREAD

**Issue by husseinbouik** [rubygems/rubygems#7635]

**Comment by husseinbouik** [comment]
bundle install
Fetching gem metadata from https://rubygems.org/.........
Installing sass 3.7.4
Installing rouge 3.30.0
Installing sass 3.7.4
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/sass.bat
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:480:in `initialize'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:480:in `open'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:480:in `generate_windows_script'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:549:in `generate_bin_script'              C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:509:in `block in generate_bin'  
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:493:in `each'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:493:in `generate_bin'
          C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/rubygems_gem_insta
ller.rb:32:in `install'                                                                                C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/source/rubygems.rb
:205:in `install'                                                                                      C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/gem_inst
aller.rb:54:in `install'                                                                               C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/gem_inst
aller.rb:16:in `install_from_spec'                                                                     C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/parallel
_installer.rb:132:in `do_install'                                                                      C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/parallel
_installer.rb:117:in `install_serially'                                                                C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/parallel
_installer.rb:93:in `call'                                                                             C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/parallel
_installer.rb:66:in `call'                                                                             C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer.rb:244:i
n `install_in_parallel'                                                                                C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer.rb:201:i
n `install'                                                                                            C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer.rb:89:in
 `block in run'                                                                                        C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/process_lock.rb:19
:in `rescue in lock'                                                                                   C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/process_lock.rb:15
:in `lock'                                                                                             C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer.rb:71:in
 `run'                                                                                                 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer.rb:23:in
 `install'                                                                                             C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/install.rb:63:
in `run'                                                                                               C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:244:in `blo
ck in install'                                                                                         C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/settings.rb:158:in
 `temporary'                                                                                           C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:243:in `ins
tall'                                                                                                  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/th
or/command.rb:28:in `run'                                                                              C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/th
or/invocation.rb:127:in `invoke_command'                                                               C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/th
or.rb:527:in `dispatch'                                                                                C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `disp
atch'                                                                                                  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/th
or/base.rb:584:in `start'                                                                              C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `star
t'                                                                                                     C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <to
p (required)>'                                                                                         C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb
:117:in `with_friendly_errors'                                                                         C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (requir
ed)>'                                                                                                  C:/Ruby32-x64/bin/bundle:25:in `load'
          C:/Ruby32-x64/bin/bundle:25:in `<main>'
Errno::EACCES: Permission denied @ rb_sysopen - C:/Ruby32-x64/bin/sass.bat
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:480:in `initialize'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:480:in `open'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:480:in `generate_windows_script'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:549:in `generate_bin_script'              C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:509:in `block in generate_bin'  
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:493:in `each'
          C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:493:in `generate_bin'
          C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/rubygems_gem_insta
ller.rb:32:in `install'                                                                                C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/source/rubygems.rb
:205:in `install'                                                                                      C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/gem_inst
aller.rb:54:in `install'                                                                               C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/gem_inst
aller.rb:16:in `install_from_spec'                                                                     C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/parallel
_installer.rb:132:in `do_install'                                                                      C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/installer/parallel
_installer.rb:123:in `block in worker_pool'                                                            C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/worker.rb:62:in `a
pply_func'                                                                                             C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/worker.rb:57:in `b
lock in process_queue'                                                                                 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/worker.rb:54:in `l
oop'                                                                                                   C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/worker.rb:54:in `p
rocess_queue'                                                                                          C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/worker.rb:90:in `b
lock (2 levels) in create_threads'                                                           
```

## Environment

```
Bundler       2.5.5
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.2.3p157 (2024-01-18 revision 52bb2ac0a6971d0391efa2275f7a66bff319087c) [x64-m
ingw-ucrt]                                                                                     Full Path   C:/Ruby32-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.4.19
  Gem Home    C:/Ruby32-x64/lib/ruby/gems/3.2.0
  Gem Path    C:/Users/Solicode/.local/share/gem/ruby/3.2.0;C:/Ruby32-x64/lib/ruby/gems/3.2.0
  User Home   C:/Users/Solicode                                                                User Path   C:/Users/Solicode/.local/share/gem/ruby/3.2.0
  Bin Dir     C:/Ruby32-x64/bin
OpenSSL
  Compiled    OpenSSL 3.2.0 23 Nov 2023
  Loaded      OpenSSL 3.2.0 23 Nov 2023
  Cert File   C:/Ruby32-x64/bin/etc/ssl/cert.pem
  Cert Dir    C:/Ruby32-x64/bin/etc/ssl/certs
Tools
  Git         2.42.0.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-01-18
Git SHA           2efa8cec93
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# gem "jekyll", "~> 4.3.3"
gem "github-pages", "~> 229", group: :jekyll_plugins

# This is the default theme for new Jekyll sites. You may change this to anything you like.  
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem      
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "webrick", "~> 1.8"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.1.3)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    addressable (2.8.6)
      public_suffix (>= 2.0.2, < 6.0)
    base64 (0.2.0)
    bigdecimal (3.1.6)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    colorator (1.1.0)
    commonmarker (0.23.10)
    concurrent-ruby (1.2.3)
    connection_pool (2.4.1)
    dnsruby (1.70.0)
      simpleidn (~> 0.2.1)
    drb (2.2.0)
      ruby2_keywords
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    eventmachine (1.2.7)
    execjs (2.9.1)
    faraday (2.9.0)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-net_http (3.1.0)
      net-http
    ffi (1.16.3-x64-mingw-ucrt)
    forwardable-extended (2.6.0)
    gemoji (4.1.0)
    github-pages (229)
      github-pages-health-check (= 1.18.2)
      jekyll (= 3.9.4)
      jekyll-avatar (= 0.8.0)
      jekyll-coffeescript (= 1.2.2)
      jekyll-commonmark-ghpages (= 0.4.0)
      jekyll-default-layout (= 0.1.5)
      jekyll-feed (= 0.17.0)
      jekyll-gist (= 1.5.0)
      jekyll-github-metadata (= 2.16.1)
      jekyll-include-cache (= 0.2.1)
      jekyll-mentions (= 1.6.0)
      jekyll-optional-front-matter (= 0.3.2)
      jekyll-paginate (= 1.1.0)
      jekyll-readme-index (= 0.3.0)
      jekyll-redirect-from (= 0.16.0)
      jekyll-relative-links (= 0.7.0)
      jekyll-remote-theme (= 0.4.3)
      jekyll-sass-converter (= 1.5.2)
      jekyll-seo-tag (= 2.8.0)
      jekyll-sitemap (= 1.4.0)
      jekyll-swiss (= 1.0.0)
      jekyll-theme-architect (= 0.2.0)
      jekyll-theme-cayman (= 0.2.0)
      jekyll-theme-dinky (= 0.2.0)
      jekyll-theme-hacker (= 0.2.0)
      jekyll-theme-leap-day (= 0.2.0)
      jekyll-theme-merlot (= 0.2.0)
      jekyll-theme-midnight (= 0.2.0)
      jekyll-theme-minimal (= 0.2.0)
      jekyll-theme-modernist (= 0.2.0)
      jekyll-theme-primer (= 0.6.0)
      jekyll-theme-slate (= 0.2.0)
      jekyll-theme-tactile (= 0.2.0)
      jekyll-theme-time-machine (= 0.2.0)
      jekyll-titles-from-headings (= 0.5.3)
      jemoji (= 0.13.0)
      kramdown (= 2.4.0)
      kramdown-parser-gfm (= 1.1.0)
      liquid (= 4.0.4)
      mercenary (~> 0.3)
      minima (= 2.5.1)
      nokogiri (>= 1.13.6, < 2.0)
      rouge (= 3.30.0)
      terminal-table (~> 1.4)
    github-pages-health-check (1.18.2)
      addressable (~> 2.3)
      dnsruby (~> 1.60)
      octokit (>= 4, < 8)
      public_suffix (>= 3.0, < 6.0)
      typhoeus (~> 1.3)
    html-pipeline (2.14.3)
      activesupport (>= 2)
      nokogiri (>= 1.4)
    http_parser.rb (0.8.0)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    jekyll (3.9.4)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (>= 0.7, < 2)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 2.0)
      kramdown (>= 1.17, < 3)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 4)
      safe_yaml (~> 1.0)
    jekyll-avatar (0.8.0)
      jekyll (>= 3.0, < 5.0)
    jekyll-coffeescript (1.2.2)
      coffee-script (~> 2.2)
      coffee-script-source (~> 1.12)
    jekyll-commonmark (1.4.0)
      commonmarker (~> 0.22)
    jekyll-commonmark-ghpages (0.4.0)
      commonmarker (~> 0.23.7)
      jekyll (~> 3.9.0)
      jekyll-commonmark (~> 1.4.0)
      rouge (>= 2.0, < 5.0)
    jekyll-default-layout (0.1.5)
      jekyll (>= 3.0, < 5.0)
    jekyll-feed (0.17.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-gist (1.5.0)
      octokit (~> 4.2)
    jekyll-github-metadata (2.16.1)
      jekyll (>= 3.4, < 5.0)
      octokit (>= 4, < 7, != 4.4.0)
    jekyll-include-cache (0.2.1)
      jekyll (>= 3.7, < 5.0)
    jekyll-mentions (1.6.0)
      html-pipeline (~> 2.3)
      jekyll (>= 3.7, < 5.0)
    jekyll-optional-front-matter (0.3.2)
      jekyll (>= 3.0, < 5.0)
    jekyll-paginate (1.1.0)
    jekyll-readme-index (0.3.0)
      jekyll (>= 3.0, < 5.0)
    jekyll-redirect-from (0.16.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-relative-links (0.7.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-remote-theme (0.4.3)
      addressable (~> 2.0)
      jekyll (>= 3.5, < 5.0)
      jekyll-sass-converter (>= 1.0, <= 3.0.0, != 2.0.0)
      rubyzip (>= 1.3.0, < 3.0)
    jekyll-sass-converter (1.5.2)
      sass (~> 3.4)
    jekyll-seo-tag (2.8.0)
      jekyll (>= 3.8, < 5.0)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-swiss (1.0.0)
    jekyll-theme-architect (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-cayman (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-dinky (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-hacker (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-leap-day (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-merlot (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-midnight (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-minimal (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-modernist (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-primer (0.6.0)
      jekyll (> 3.5, < 5.0)
      jekyll-github-metadata (~> 2.9)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-slate (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-tactile (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-theme-time-machine (0.2.0)
      jekyll (> 3.5, < 5.0)
      jekyll-seo-tag (~> 2.0)
    jekyll-titles-from-headings (0.5.3)
      jekyll (>= 3.3, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    jemoji (0.13.0)
      gemoji (>= 3, < 5)
      html-pipeline (~> 2.2)
      jekyll (>= 3.0, < 5.0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.4)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.3.6)
    minima (2.5.1)
      jekyll (>= 3.5, < 5.0)
      jekyll-feed (~> 0.9)
      jekyll-seo-tag (~> 2.1)
    minitest (5.22.2)
    mutex_m (0.2.0)
    net-http (0.4.1)
      uri
    nokogiri (1.16.2-x64-mingw-ucrt)
      racc (~> 1.4)
    octokit (4.25.1)
      faraday (>= 1, < 3)
      sawyer (~> 0.9)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (5.0.4)
    racc (1.7.3)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.6)
    rouge (3.30.0)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    safe_yaml (1.0.5)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sawyer (0.9.2)
      addressable (>= 2.3.5)
      faraday (>= 0.17.3, < 3)
    simpleidn (0.2.1)
      unf (~> 0.1.4)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    typhoeus (1.4.1)
      ethon (>= 0.9.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2024.1)
      tzinfo (>= 1.0.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.9.1-x64-mingw-ucrt)
    unicode-display_width (1.8.0)
    uri (0.13.0)
    wdm (0.1.1)
    webrick (1.8.1)

PLATFORMS
  x64-mingw-ucrt

DEPENDENCIES
  github-pages (~> 229)
  http_parser.rb (~> 0.6.0)
  jekyll-feed (~> 0.12)
  minima (~> 2.5)
  tzinfo (>= 1, < 3)
  tzinfo-data
  wdm (~> 0.1.1)
  webrick (~> 1.8)

BUNDLED WITH
   2.5.5
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+rb_sysopen+-+C+%2FRuby32-
x64%2Fbin%2Fsass.bat&type=Issues                                                             
If there aren't any reports for this error yet, please fill in the new issue form located at 
https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue
.md, and copy and paste the report template above in there.

**Comment by deivid-rodriguez** [comment]
Please rewrite the bug report filling out the template, and posting logs after upgrading to latest Bundler and RubyGems versions.

Feel free to reopen this once you do that.

Thanks!
