### ISSUE TITLE
Running `bundle exec` inside `gem exec` can't load github sources

### ISSUE THREAD

**Issue by nevans** [rubygems/rubygems#7671]
### Describe the problem as clearly as you can

The `configure_trusted_publisher` command fails when running it via `gem exec` when a Gemfile with `git` sources is present.  I found the issue with `configure_trusted_publisher`, but I assume that it's something that will need to be fixed in rubygems or bundler (or both).  _n.b: I also created an issue there: rubygems/configure_trusted_publisher#10._

The command fails when it runs `bundle exec rake release --dry-run`.  The errors (in the command output, which is pasted below) indicate that the repository URL "is not yet checked out" and "the path $GEM_HOME/gem_exec/bundler/gems/$NAME-$CHECKSUM does not exist".  It's _true_ that this specific path doesn't exist, but the gem _does_ exist at the normal path bundler path.

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

You should be able reproduce the issue by checking out `net-imap` or any of the other default or bundled ruby gems, because they all have the same `test-unit-ruby-core` with a git source in their respective Gemfiles.  The error occurs prior to any API calls, so you should be able to reproduce the error even if you don't have permissions to execute the rest of the command.

### Which command did you run?

<details><summary>gem exec configure_trusted_publisher rubygem</summary>

```
bundle exec rake release is not configured for net-imap in .:
bundler: failed to load command: rake ($GEM_BINDIR/rake)
$GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/git.rb:222:in `rescue in load_spec_files':
https://github.com/ruby/test-unit-ruby-core is not yet checked out. Run `bundle install` first. (Bundler::GitError)
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/git.rb:218:in `load_spec_files'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/path.rb:108:in `local_specs'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/git.rb:185:in `specs'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/lazy_specification.rb:97:in `materialize_for_installation'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:281:in `map!'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:281:in `specs_for_dependency'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:34:in `block in for'
        from <internal:kernel>:187:in `loop'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:22:in `for'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:121:in `materialize'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/definition.rb:584:in `materialize'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/definition.rb:207:in `specs'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/definition.rb:273:in `specs_for'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/runtime.rb:18:in `setup'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler.rb:163:in `setup'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/setup.rb:29:in `block in <top (required)>'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/ui/shell.rb:159:in `with_level'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/ui/shell.rb:111:in `silence'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/setup.rb:29:in `<top (required)>'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:56:in `require_relative'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:56:in `kernel_load'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:23:in `run'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli.rb:455:in `exec'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli.rb:35:in `dispatch'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli.rb:29:in `start'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/exe/bundle:28:in `block in <top (required)>'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/exe/bundle:20:in `<top (required)>'
        from $GEM_BINDIR/bundle:25:in `load'
        from $GEM_BINDIR/bundle:25:in `<main>'
$GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/path.rb:210:in `load_spec_files':
The path `$GEM_HOME/gem_exec/bundler/gems/test-unit-ruby-core-7b20ceb51631` does not exist. (Bundler::PathError)
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/git.rb:219:in `load_spec_files'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/path.rb:108:in `local_specs'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/source/git.rb:185:in `specs'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/lazy_specification.rb:97:in `materialize_for_installation'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:281:in `map!'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:281:in `specs_for_dependency'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:34:in `block in for'
        from <internal:kernel>:187:in `loop'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:22:in `for'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/spec_set.rb:121:in `materialize'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/definition.rb:584:in `materialize'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/definition.rb:207:in `specs'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/definition.rb:273:in `specs_for'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/runtime.rb:18:in `setup'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler.rb:163:in `setup'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/setup.rb:29:in `block in <top (required)>'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/ui/shell.rb:159:in `with_level'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/ui/shell.rb:111:in `silence'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/setup.rb:29:in `<top (required)>'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:56:in `require_relative'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:56:in `kernel_load'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli/exec.rb:23:in `run'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli.rb:455:in `exec'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli.rb:35:in `dispatch'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/cli.rb:29:in `start'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/exe/bundle:28:in `block in <top (required)>'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from $GEM_HOME/gem_exec/gems/bundler-2.5.10/exe/bundle:20:in `<top (required)>'
        from $GEM_BINDIR/bundle:25:in `load'
        from $GEM_BINDIR/bundle:25:in `<main>'
```
</details>

<details><summary>bundle info test-unit-ruby-core
</summary>

```
  * test-unit-ruby-core (1.0.5 7b20ceb)
        Summary: Additional test assertions for Ruby standard libraries.
        Homepage: https://github.com/ruby/test-unit-ruby-core
        Source Code: https://github.com/ruby/test-unit-ruby-core
        Path: /home/nick/src/.local/share/rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/bundler/gems/test-unit-ruby-core-7b20ceb51631
```
</details>

_(I lightly edited the stacktraces for clarity, mostly just substituting path prefixes with `$GEM_HOME` and `$GEM_BINDIR`)_

### What were you expecting to happen?

I expected it to behave identically to running `gem install configure_trusted_publishing` and then running `configure_trusted_publishing` directly.

### What actually happened?

Command output is pasted above (hidden inside `<details>` disclosures).

### If not included with the output of your command, run `bundle env` and paste the output below

# $ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.10
  - RUBY VERSION: 3.3.1 (2024-04-23 patchlevel 55) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/nick/.local/share/rbenv/versions/3.3.1/lib/ruby/gems/3.3.0
  - USER INSTALLATION DIRECTORY: /home/nick/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: /home/nick/.local/share/rbenv/versions/3.3.1/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/nick/.local/share/rbenv/versions/3.3.1/bin
  - SPEC CACHE DIRECTORY: /home/nick/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/nick/.local/share/rbenv/versions/3.3.1/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/nick/.local/share/rbenv/versions/3.3.1/lib/ruby/gems/3.3.0
     - /home/nick/.gem/ruby/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/nick/.local/share/rbenv/versions/3.3.1/bin
     - /home/nick/.local/share/rbenv/libexec
     - /home/nick/.local/share/rbenv/plugins/ruby-build/bin
     - /home/nick/.local/share/rbenv/plugins/rbenv-each/bin
     - /home/nick/.local/share/rbenv/plugins/rbenv-ctags/bin
     - /home/nick/bin
     - /home/nick/.local/bin
     - /home/nick/.local/share/rbenv/shims
     - /home/nick/.local/share/rbenv/shims
     - /home/nick/.local/share/rbenv/plugins/ruby-build/bin
     - /home/nick/.local/share/rbenv/bin
     - /home/nick/.yarn/bin
     - /home/nick/.local/share/npm/bin
     - /home/nick/.local/share/cargo/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /home/nick/.config/vim/pack/packager/start/fzf/bin
     - /snap/bin
     - /home/nick/src/go/bin

# $ bundle env
## Environment

```
Bundler       2.5.10
  Platforms   ruby, x86_64-linux
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [x86_64-linux]
  Full Path   /home/nick/.local/share/rbenv/versions/3.3.1/bin/ruby
  Config Dir  /home/nick/.local/share/rbenv/versions/3.3.1/etc
RubyGems      3.5.10
  Gem Home    /home/nick/.local/share/rbenv/versions/3.3.1/lib/ruby/gems/3.3.0
  Gem Path    /home/nick/.gem/ruby/3.3.0:/home/nick/.local/share/rbenv/versions/3.3.1/lib/ruby/gem
s/3.3.0
  User Home   /home/nick
  User Path   /home/nick/.gem/ruby/3.3.0
  Bin Dir     /home/nick/.local/share/rbenv/versions/3.3.1/bin
Tools         
  Git         2.40.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-03
Git SHA           24cac00613
Released Version  true
```

## Bundler settings

```
cache_all
  Set for your local app (/home/nick/src/net-imap/.bundle/config): true
gem.changelog
  Set for the current user (/home/nick/.bundle/config): true
gem.ci
  Set for the current user (/home/nick/.bundle/config): "github"
gem.coc
  Set for the current user (/home/nick/.bundle/config): true
gem.linter
  Set for the current user (/home/nick/.bundle/config): "rubocop"
gem.mit
  Set for the current user (/home/nick/.bundle/config): true
gem.test
  Set for the current user (/home/nick/.bundle/config): "rspec"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "digest"
gem "strscan"
gem "base64"

gem "rake"
gem "rdoc"
gem "test-unit"
gem "test-unit-ruby-core", git: "https://github.com/ruby/test-unit-ruby-core"

gem "benchmark-driver"
```

### Gemfile.lock

```
GIT
  remote: https://github.com/ruby/test-unit-ruby-core
  revision: 7b20ceb51631e69471684ffe242a3e3f5e56c760
  specs:
    test-unit-ruby-core (1.0.5)

PATH
  remote: .
  specs:
    net-imap (0.4.11)
      date
      net-protocol

GEM
  remote: https://rubygems.org/
  specs:
    base64 (0.2.0)
    benchmark-driver (0.1.0)
      benchmark_driver
    benchmark_driver (0.16.5)
    date (3.3.4)
    digest (3.1.1)
    net-protocol (0.2.2)
      timeout
    power_assert (2.0.3)
    psych (5.1.2)
      stringio
    rake (13.2.1)
    rdoc (6.6.3.1)
      psych (>= 4.0.0)
    stringio (3.1.0)
    strscan (3.1.0)
    test-unit (3.6.2)
      power_assert
    timeout (0.4.1)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  base64
  benchmark-driver
  digest
  net-imap!
  rake
  rdoc
  strscan
  test-unit
  test-unit-ruby-core!

BUNDLED WITH
   2.5.10
```

### net-imap.gemspec

```ruby
# frozen_string_literal: true

name = File.basename(__FILE__, ".gemspec")
version = ["lib", Array.new(name.count("-"), "..").join("/")].find do |dir|
  break File.foreach(File.join(__dir__, dir, "#{name.tr('-', '/')}.rb"), :encoding=> 'utf-8') do |line|
    /^\s*VERSION\s*=\s*"(.*)"/ =~ line and break $1
  end rescue nil
end

Gem::Specification.new do |spec|
  spec.name          = name
  spec.version       = version
  spec.authors       = ["Shugo Maeda", "nicholas a. evans"]
  spec.email         = ["shugo@ruby-lang.org", "nick@rubinick.dev"]

  spec.summary       = %q{Ruby client api for Internet Message Access Protocol}
  spec.description   = %q{Ruby client api for Internet Message Access Protocol}
  spec.homepage      = "https://github.com/ruby/net-imap"
  spec.required_ruby_version = Gem::Requirement.new(">= 2.7.3")
  spec.licenses       = ["Ruby", "BSD-2-Clause"]

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = spec.homepage
  spec.metadata["changelog_uri"] = spec.homepage + "/releases"

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files         = Dir.chdir(File.expand_path('..', __FILE__)) do
    `git ls-files -z 2>/dev/null`.split("\x0")
      .grep_v(%r{^(\.git|\.mailmap|bin|test|spec|benchmarks|features|rfcs)/})
  end
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_dependency "net-protocol"
  spec.add_dependency "date"
end
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting, I think I found the issue. `gem exec` modifies the RubyGems environment for the "on the fly" install, but it should reset it back to how it was originally before loading the just installed executable. Right now it resets it, but after the executable is already loaded.

I think https://github.com/rubygems/rubygems/pull/7956 should fix this!
