### ISSUE TITLE
Improve handling of paths with colons (allowed on Unix, disallowed on Windows)

### ISSUE THREAD

**Issue by JRice** [rubygems/rubygems#7681]
### Describe the problem as clearly as you can

...juuuuuust installed ruby, trying to bundle install. Done this a bajillion times on other OSes, this is my first time trying on Windows.

### Did you try upgrading rubygems & bundler?

Dude. I just installed them. From the web. Like... minutes ago. They had better be upgraded.

### Post steps to reproduce the problem

bundle install

### Which command did you run?

bundle install

### What were you expecting to happen?

I expected the bundle to ... install.

### What actually happened?

The bundle did not install.

It asked me to come here and paste this log, so I am obediently doing as it asked.

--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EINVAL: Invalid argument @ rb_sysopen - C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/crono-2.0.1/spec/internal/:memory
  C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:455:in `initialize'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:455:in `open'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:455:in `block (2 levels) in extract_tar_gz'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:424:in `block in extract_tar_gz'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:548:in `block in open_tar_gz'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:545:in `wrap'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:545:in `open_tar_gz'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:423:in `extract_tar_gz'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:397:in `block (2 levels) in extract_files'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:394:in `block in extract_files'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package/file_source.rb:30:in `open'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/package.rb:391:in `extract_files'
          C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/installer.rb:861:in `extract_files'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/rubygems_gem_installer.rb:26:in `install'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/source/rubygems.rb:205:in `install'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/installer/gem_installer.rb:54:in `install'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/worker.rb:62:in `apply_func'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/worker.rb:57:in `block in process_queue'
          <internal:kernel>:187:in `loop'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/worker.rb:54:in `process_queue'
          C:/Users/jrice/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.10/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.5.10
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [x64-mingw-ucrt]
  Full Path   C:/Ruby33-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.5.10
  Gem Home    C:/Users/jrice/.local/share/gem/ruby/3.3.0
  Gem Path    C:/Users/jrice/.local/share/gem/ruby/3.3.0;C:/Ruby33-x64/lib/ruby/gems/3.3.0
  User Home   C:/Users/jrice
  User Path   C:/Users/jrice/.local/share/gem/ruby/3.3.0
  Bin Dir     C:/Users/jrice/.local/share/gem/ruby/3.3.0/bin
OpenSSL
  Compiled    OpenSSL 3.3.0 9 Apr 2024
  Loaded      OpenSSL 3.3.0 9 Apr 2024
  Cert File   C:/Ruby33-x64/bin/etc/ssl/cert.pem
  Cert Dir    C:/Ruby33-x64/bin/etc/ssl/certs
Tools
  Git         2.45.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-03
Git SHA           24cac00613
Released Version  true
```

## Bundler settings

```
system_bindir
  Set via BUNDLE_SYSTEM_BINDIR: "C:/Users/jrice/AppData/Local/Microsoft/WindowsApps"
```

### Gemfile

```ruby
source "https://rubygems.org"
# The REALLY basic stuff stays at the top:

# gem 'rails', '5.2.8.1'
gem 'rails', '6.1.7.7'
gem 'base64' # REMOVE THIS WHEN YOU UPDATE TO RAILS 7.
gem 'bigdecimal' # REMOVE THIS WHEN YOU UPDATE TO RAILS 7.
gem 'mutex_m' # REMOVE THIS WHEN YOU UPDATE TO RAILS 7.
gem 'csv' # REMOVE THIS WHEN YOU UPDATE TO RAILS 7.
gem 'drb' # REMOVE THIS WHEN YOU UPDATE TO RAILS 7. This one is needed for assets.
# Use mysql2 as the database for Active Record
gem 'mysql2', '~> 0.5.6'
# Use puma as the web host
gem 'puma', '~> 6.4'

# "Internal" EOL gems:
gem 'eol_terms', git: 'https://github.com/EOL/eol_terms.git', branch: 'main'

# Asset-related gems next:
gem 'webpacker', '~> 6.0.0.beta'

# SASS
# Sass is end-of-life. Update to sassc gem: https://github.com/sass/sassc-ruby#readme
gem 'sass-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.11.5'
# Use jquery as the JavaScript library TODO ... I don't think we do, anymore?
gem 'jquery-rails', '~> 4.4'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '~> 4.2'

# Pagination with kaminari. It's out of order because the methods it uses need
# to be defined first for other classes to recognize them:
gem 'kaminari', '~> 1.2.2'

# All other non-environment-specific gems come next.
#
# ALPHABETICALLY, PLEASE.
#
# ...and with a comment above each gem (or block of related gems) explaining what it's for. Let's keep this
# maintainable!

# OGM (object graph mapper for Neo4J). Added for use with searchkick.
gem 'activegraph', '~> 10.1' # NOTE: there's at least a version 11, but I am scared of it.
gem 'activestorage', '~> 6.1.7' # TEMP! ...when you change activegraph or update gems, remove this, it's a security bump.
gem 'neo4j-ruby-driver', git: 'https://github.com/EOL/neo4j-ruby-driver.git', branch: '1.7'
# For bulk inserts:
gem 'activerecord-import', '~> 1.3'
# Acts As List simplifies ordered lists of models:
gem 'acts_as_list', '~> 1.0'
# Faster startup:
gem 'bootsnap', '~> 1.10', require: false
# Counter Culture handles cached counts of things (which we use ALL OVER):
gem 'counter_culture', '~> 2.9'
# Cron jobs:
gem 'crono', '~> 2.0'
# Run background jobs:
gem 'daemons', '~> 1.4'
# Memcached (not for development):
gem 'dalli', '~> 2.7'
# Background jobs (to be run by daemons, q.v.):
gem 'delayed_job', '~> 4.1'
gem 'delayed_job_active_record', '~> 4.1'
# Devise handles authentication and some authorization:
gem 'devise', '~> 4.9'
gem 'devise-i18n-views', '~> 0.3'
gem 'devise-encryptable', '~> 0.2'
# Discourse handles comments and chat: TODO: do we even use this anymore?!
gem 'discourse_api', '~> 0.48'
# Model decoration
gem 'draper', '~> 4.0'
# ElasticSearch via SearchKick:
gem 'elasticsearch', '~> 8.8' # Needs to stay in sync with the version of ES that we're using
gem 'searchkick', '~> 5.3' # Needs to stay in sync (ish) with the elasticsearch gem.
# url slug support
gem 'friendly_id', '~> 5.4'
# Icons
gem 'font-awesome-sass', '~> 5.15'
# This is used to locally have a copy of Open Sans. IF YOU STOP USING OPEN SANS (note the space), YOU SHOULD REMOVE THIS GEM!
gem 'font-kit-rails', '~> 1.2'
# jwt is used for JSON Web Token (JWT) standard API handshakes. ...This WAS included in Omniauth, which we removed.
gem 'jwt', '~> 2.2' # Note the gem is ruby-jwt
# Because ERB is just plain silly compared to Haml:
gem 'haml', '~> 5.2.1'
gem 'haml-rails', '~> 2.0.1'
# HTTP client
gem 'http', '~> 5.0'
# translations in JS
gem 'i18n-js', '~> 3.9' # NOTE: Version 4 is coming. There is no documentation for it as yet, but be mindful.
# JSON schema-based validation
gem 'json_schemer', '~> 0.2'
# QUIET PLEASE MAKE IT STOP! This helps us cull some of the noise in the logs:
gem 'lograge', '~> 0.14'
# This should help stop some of the warnings you'll see in the logs/console:
gem 'net-http'
# Speed up JSON, including for ElasticSearch:
gem 'oj', '~> 3.13'
# Debugging:
gem 'pry-rails' # NOT specifying a version for this; latest is best.
# Authorization:
gem 'pundit', '~> 2.1'
# CORS middleware, we need this for HW's cross-site API requests:
gem 'rack-cors'
# Turing test:
gem 'recaptcha', '~> 5.8', require: 'recaptcha/rails'
# Zip file support ; NOTE: this is almost up to version 3.0, and then it will have some interface changes that we need
# to switch to. Read https://github.com/rubyzip/rubyzip when the time comes!
gem 'redis', '~> 5.0'
gem 'rubyzip', '~> 2.3'
# Scout is an application monitoring tool:
gem 'scout_apm'
# Searchkick uses sidekiq for job processing (really, anything BUT Delayed::Job, apparently), so I've installed it:
gem 'sidekiq', '~> 6.5'
# OUT OF ORDER: Sidekiq needs AJ-TC to reduce concurrency https://github.com/ankane/searchkick?tab=readme-ov-file#filterable-fields
gem "activejob-traffic_control", ">= 0.1.3"
# Simplify Forms:
# KEEPING client_side_validations OUT OF ORDER, since they are tightly bound to simple_form;
# these are ONLY used on the user page, in the user_helper's validate: true clause...
# TODO: I am not sure these are working / used anymore. Check and remove, if not.
gem 'simple_form', '~> 5.1'
gem 'client_side_validations', '~> 18.1'
gem 'client_side_validations-simple_form', '~> 13'
#Sitemap
gem 'sitemap_generator', '~> 6.2'
# Speed up ElasticSearch ... but also good if you want to do web requests, see https://github.com/typhoeus/typhoeus
gem 'typhoeus', '~> 1.4'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3'
end
```

### Gemfile.lock

```
GIT
  remote: https://github.com/EOL/eol_terms.git
  revision: 4f14652e768f742d9ae63415e9d92c73900fdfdc
  branch: main
  specs:
    eol_terms (0.9.80)
      yaml

GIT
  remote: https://github.com/EOL/neo4j-ruby-driver.git
  revision: fe5438fb945dc0262acd8602131de830899e9bcc
  branch: 1.7
  specs:
    neo4j-ruby-driver (1.7.5.20210310150725)
      activesupport
      ffi
      recursive-open-struct
      zeitwerk (>= 2.1.10)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.7.7)
      actionpack (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.7.7)
      actionpack (= 6.1.7.7)
      activejob (= 6.1.7.7)
      activerecord (= 6.1.7.7)
      activestorage (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      mail (>= 2.7.1)
    actionmailer (6.1.7.7)
      actionpack (= 6.1.7.7)
      actionview (= 6.1.7.7)
      activejob (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.7.7)
      actionview (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.7.7)
      actionpack (= 6.1.7.7)
      activerecord (= 6.1.7.7)
      activestorage (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      nokogiri (>= 1.8.5)
    actionview (6.1.7.7)
      activesupport (= 6.1.7.7)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activegraph (10.1.1)
      activemodel (>= 4.0)
      activesupport (>= 4.0)
      i18n (!= 1.8.8)
      orm_adapter (~> 0.5.0)
      sorted_set
    activejob (6.1.7.7)
      activesupport (= 6.1.7.7)
      globalid (>= 0.3.6)
    activejob-traffic_control (0.1.3)
      activejob (>= 4.2)
      activesupport (>= 4.2)
      suo
    activemodel (6.1.7.7)
      activesupport (= 6.1.7.7)
    activemodel-serializers-xml (1.0.2)
      activemodel (> 5.x)
      activesupport (> 5.x)
      builder (~> 3.1)
    activerecord (6.1.7.7)
      activemodel (= 6.1.7.7)
      activesupport (= 6.1.7.7)
    activerecord-import (1.5.0)
      activerecord (>= 4.2)
    activestorage (6.1.7.7)
      actionpack (= 6.1.7.7)
      activejob (= 6.1.7.7)
      activerecord (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.7.7)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    acts_as_list (1.1.0)
      activerecord (>= 4.2)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    ast (2.4.2)
    base64 (0.2.0)
    bcrypt (3.1.19)
    bigdecimal (3.1.8)
    bindex (0.8.1)
    bootsnap (1.16.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    byebug (11.1.3)
    character_set (1.7.0)
    client_side_validations (18.1.0)
      js_regex (~> 3.1)
      rails (>= 5.0.0.1, < 7.0)
    client_side_validations-simple_form (13.0.0)
      client_side_validations (>= 15.0, < 19.0)
      simple_form (~> 5.0)
    coderay (1.1.3)
    concurrent-ruby (1.2.3)
    connection_pool (2.4.1)
    counter_culture (2.9.0)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
    crass (1.0.6)
    crono (2.0.1)
      rails (>= 5.2.8)
      sprockets-rails
    csv (3.3.0)
    daemons (1.4.1)
    dalli (2.7.11)
    date (3.3.4)
    delayed_job (4.1.11)
      activesupport (>= 3.0, < 8.0)
    delayed_job_active_record (4.1.7)
      activerecord (>= 3.0, < 8.0)
      delayed_job (>= 3.0, < 5)
    devise (4.9.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    devise-i18n-views (0.3.7)
    discourse_api (0.48.1)
      faraday (~> 1.0)
      faraday_middleware (~> 1.0)
      rack (>= 1.6)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    draper (4.0.2)
      actionpack (>= 5.0)
      activemodel (>= 5.0)
      activemodel-serializers-xml (>= 1.0)
      activesupport (>= 5.0)
      request_store (>= 1.0)
      ruby2_keywords
    drb (2.2.1)
    ecma-re-validator (0.4.0)
      regexp_parser (~> 2.2)
    elastic-transport (8.3.2)
      faraday (< 3)
      multi_json
    elasticsearch (8.13.0)
      elastic-transport (~> 8.3)
      elasticsearch-api (= 8.13.0)
    elasticsearch-api (8.13.0)
      multi_json
    erubi (1.12.0)
    erubis (2.7.0)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    execjs (2.9.1)
    faraday (1.10.3)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    ffi (1.16.2)
    ffi-compiler (1.0.1)
      ffi (>= 1.0.0)
      rake
    font-awesome-sass (5.15.1)
      sassc (>= 1.11)
    font-kit-rails (1.2.0)
      rails
    friendly_id (5.5.0)
      activerecord (>= 4.0.0)
    globalid (1.2.1)
      activesupport (>= 6.1)
    haml (5.2.2)
      temple (>= 0.8.0)
      tilt
    haml-rails (2.0.1)
      actionpack (>= 5.1)
      activesupport (>= 5.1)
      haml (>= 4.0.6, < 6.0)
      html2haml (>= 1.0.1)
      railties (>= 5.1)
    hana (1.3.7)
    hashie (5.0.0)
    html2haml (2.3.0)
      erubis (~> 2.7.0)
      haml (>= 4.0)
      nokogiri (>= 1.6.0)
      ruby_parser (~> 3.5)
    http (5.1.1)
      addressable (~> 2.8)
      http-cookie (~> 1.0)
      http-form_data (~> 2.2)
      llhttp-ffi (~> 0.4.0)
    http-cookie (1.0.5)
      domain_name (~> 0.5)
    http-form_data (2.3.0)
    i18n (1.14.4)
      concurrent-ruby (~> 1.0)
    i18n-js (3.9.2)
      i18n (>= 0.6.6)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jquery-rails (4.6.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    js_regex (3.11.0)
      character_set (~> 1.4)
      regexp_parser (>= 2.6.2, < 3.0.0)
      regexp_property_values (~> 1.0)
    json (2.6.3)
    json_schemer (0.2.25)
      ecma-re-validator (~> 0.3)
      hana (~> 1.3)
      regexp_parser (~> 2.0)
      simpleidn (~> 0.2)
      uri_template (~> 0.7)
    jwt (2.7.1)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    llhttp-ffi (0.4.0)
      ffi-compiler (~> 1.0)
      rake (~> 13.0)
    lograge (0.14.0)
      actionpack (>= 4)
      activesupport (>= 4)
      railties (>= 4)
      request_store (~> 1.0)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.4)
    method_source (1.0.0)
    mini_mime (1.1.5)
    mini_portile2 (2.8.5)
    minitest (5.22.3)
    msgpack (1.7.2)
    multi_json (1.15.0)
    multipart-post (2.3.0)
    mutex_m (0.2.0)
    mysql2 (0.5.6)
    net-http (0.4.1)
      uri
    net-imap (0.4.11)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.5.0)
      net-protocol
    nio4r (2.5.9)
    nokogiri (1.15.6)
      mini_portile2 (~> 2.8.2)
      racc (~> 1.4)
    oj (3.14.2)
    orm_adapter (0.5.0)
    parser (3.3.1.0)
      ast (~> 2.4.1)
      racc
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    public_suffix (5.0.3)
    puma (6.4.2)
      nio4r (~> 2.0)
    pundit (2.3.1)
      activesupport (>= 3.0.0)
    racc (1.7.3)
    rack (2.2.9)
    rack-cors (2.0.1)
      rack (>= 2.0.0)
    rack-proxy (0.7.7)
      rack
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (6.1.7.7)
      actioncable (= 6.1.7.7)
      actionmailbox (= 6.1.7.7)
      actionmailer (= 6.1.7.7)
      actionpack (= 6.1.7.7)
      actiontext (= 6.1.7.7)
      actionview (= 6.1.7.7)
      activejob (= 6.1.7.7)
      activemodel (= 6.1.7.7)
      activerecord (= 6.1.7.7)
      activestorage (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      bundler (>= 1.15.0)
      railties (= 6.1.7.7)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (6.1.7.7)
      actionpack (= 6.1.7.7)
      activesupport (= 6.1.7.7)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
    rake (13.1.0)
    rbtree (0.4.6)
    recaptcha (5.9.0)
      json
    recursive-open-struct (1.1.3)
    redis (5.1.0)
      redis-client (>= 0.17.0)
    redis-client (0.21.0)
      connection_pool
    regexp_parser (2.8.1)
    regexp_property_values (1.4.0)
    request_store (1.5.1)
      rack (>= 1.4)
    responders (3.1.0)
      actionpack (>= 5.2)
      railties (>= 5.2)
    ruby2_keywords (0.0.5)
    ruby_parser (3.20.3)
      sexp_processor (~> 4.16)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    scout_apm (5.3.8)
      parser
    searchkick (5.3.1)
      activemodel (>= 6.1)
      hashie
    semantic_range (3.0.0)
    set (1.0.3)
    sexp_processor (4.17.0)
    sidekiq (6.5.5)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.5.0)
    simple_form (5.2.0)
      actionpack (>= 5.2)
      activemodel (>= 5.2)
    simpleidn (0.2.1)
      unf (~> 0.1.4)
    sitemap_generator (6.3.0)
      builder (~> 3.0)
    sorted_set (1.0.3)
      rbtree
      set (~> 1.0)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    suo (0.4.0)
      dalli
      msgpack
      redis
    temple (0.10.2)
    thor (1.3.1)
    tilt (2.3.0)
    timeout (0.4.1)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8.2)
    uri (0.13.0)
    uri_template (0.7.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    webpacker (6.0.0.rc.5)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    yaml (0.3.0)
    zeitwerk (2.6.12)

PLATFORMS
  ruby

DEPENDENCIES
  activegraph (~> 10.1)
  activejob-traffic_control (>= 0.1.3)
  activerecord-import (~> 1.3)
  activestorage (~> 6.1.7)
  acts_as_list (~> 1.0)
  base64
  bigdecimal
  bootsnap (~> 1.10)
  byebug (~> 11)
  client_side_validations (~> 18.1)
  client_side_validations-simple_form (~> 13)
  counter_culture (~> 2.9)
  crono (~> 2.0)
  csv
  daemons (~> 1.4)
  dalli (~> 2.7)
  delayed_job (~> 4.1)
  delayed_job_active_record (~> 4.1)
  devise (~> 4.9)
  devise-encryptable (~> 0.2)
  devise-i18n-views (~> 0.3)
  discourse_api (~> 0.48)
  draper (~> 4.0)
  drb
  elasticsearch (~> 8.8)
  eol_terms!
  font-awesome-sass (~> 5.15)
  font-kit-rails (~> 1.2)
  friendly_id (~> 5.4)
  haml (~> 5.2.1)
  haml-rails (~> 2.0.1)
  http (~> 5.0)
  i18n-js (~> 3.9)
  jbuilder (~> 2.11.5)
  jquery-rails (~> 4.4)
  json_schemer (~> 0.2)
  jwt (~> 2.2)
  kaminari (~> 1.2.2)
  lograge (~> 0.14)
  mutex_m
  mysql2 (~> 0.5.6)
  neo4j-ruby-driver!
  net-http
  oj (~> 3.13)
  pry-rails
  puma (~> 6.4)
  pundit (~> 2.1)
  rack-cors
  rails (= 6.1.7.7)
  recaptcha (~> 5.8)
  redis (~> 5.0)
  rubyzip (~> 2.3)
  sass-rails
  scout_apm
  searchkick (~> 5.3)
  sidekiq (~> 6.5)
  simple_form (~> 5.1)
  sitemap_generator (~> 6.2)
  typhoeus (~> 1.4)
  uglifier (~> 4.2)
  web-console (~> 3)
  webpacker (~> 6.0.0.beta)

BUNDLED WITH
   2.5.10
```

--- TEMPLATE END ----------------------------------------------------------------

### If not included with the output of your command, run `bundle env` and paste the output below

N/A, it's included.

Good luck?

**Comment by JRice** [comment]
I am, unfortunately, going to consider this a sign from the universe that using Ruby on Windows is a Bad Idea, and will abandon the attempt.

Gotta love Windows. :|

**Comment by simi** [comment]
Thanks for the report @JRice. This is not RubyGems problem, but actually problem related to Crono gem naming file in incompatible way with Windows file system. See https://github.com/plashchynski/crono/issues/120 for more info.

**Comment by JRice** [comment]
Thanks, @simi  ...sadly, as I said, I'm not interested in ironing all of these things out in Windows, I'm just going to move on to a VM.

Thanks for looking, though!

FWIW: it strikes me as a little odd that the error tells me to report the problem here. Perhaps it should be re-worded to something more like "if you think you need additional support ... " as it's worded, it makes it sound like I'm doing you a favor by putting this here. ...which is ... weird?

**Comment by simi** [comment]
@JRice I have submitted fix to https://github.com/plashchynski/crono/pull/125. This report is still useful, we can probably catch this error and provide friendly message. Also we can do gemspec validation to warn on similar problems. @martinemde @deivid-rodriguez WDYT?

**Comment by deivid-rodriguez** [comment]
Yes, @JRice, you're right. That's for the diligence reporting this. I consider it a Bundler bug when we ask users to report an issue that's not actually a Bundler problem.

@simi Agreed, I think we can do both: 

* Catch error and give friendly message, so that users know what the problem is and are not asked to open and issue here.
* Warn at `gem build` time about files including ":" in their name.

**Comment by deivid-rodriguez** [comment]
I'll reopen this so we don't lose track of it.

**Comment by Saidbek** [comment]
Hey @deivid-rodriguez @hsbt, would you mind taking a look at https://github.com/ruby/rubygems/pull/9276/changes when you have time? Happy to make any adjustments! 🙏
