### ISSUE TITLE
bundler/inline gets confused when run in a directory with a cached bundle

### ISSUE THREAD

**Issue by ccutrer** [rubygems/rubygems#7686]
### Describe the problem as clearly as you can

When running a script that uses `bundler/inline` from inside a directory that has a bundle, and that bundle is cached, bundler seems to cross the streams between the cached gems and the system gems, resulting in a LoadError if they don't match.

### Did you try upgrading rubygems & bundler?

Yes. I'm running bundler 2.5.10, ruby gems 3.5.10, and ruby 3.3.1. 

### Post steps to reproduce the problem

```sh
git clone https://github.com/ccutrer/bundler-7686
cd bundler-7686
docker build . -t bundler_inline
docker run -it bundler_inline ./test.rb
```

Observe the failure (base64 warning is irrelevant; I've also reproduced on ruby 3.1.2):
```
/usr/local/bundle/gems/diplomat-2.6.4/lib/diplomat.rb:4: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of diplomat-2.6.4 to add base64 into its gemspec.
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- faraday (LoadError)
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/bundle/gems/diplomat-2.6.4/lib/diplomat.rb:5:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/inline.rb:66:in `block (2 levels) in gemfile'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/settings.rb:157:in `temporary'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/inline.rb:51:in `block in gemfile'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler.rb:424:in `block in with_unbundled_env'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler.rb:679:in `with_env'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler.rb:424:in `with_unbundled_env'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/inline.rb:42:in `gemfile'
	from ./test.rb:5:in `<main>'
```

You can enter the container to investigate further with `docker run -it bundler_inline /bin/bash` (be sure to `unset BUNDLE_APP_CONFIG`, since that only lasts per shell session).

### Which command did you run?

I ran my script with bundler/inline from within another bundle, with packaged gems, whose versions differ from the system installed gems.

### What were you expecting to happen?

No output (besides the base64 warning), since the script doesn't actually do anything.

### What actually happened?

I got an error that it could not load faraday 2.7.4 (because the file can't be found). I also manually modified `diplomat.rb` to just `puts $LOAD_PATH` before requiring anything, and see:

```
/usr/local/bundle/gems/diplomat-2.6.4/lib
/usr/local/bundle/gems/faraday-2.9.0/lib
/usr/local/bundle/gems/faraday-2.9.0/spec/external_adapters
/usr/local/bundle/gems/faraday-net_http-3.1.0/lib
/usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib
/usr/local/lib/ruby/gems/3.3.0/gems/uri-0.13.0/lib
/usr/local/bundle/gems/deep_merge-1.2.2/lib
/usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib
/usr/local/lib/ruby/site_ruby/3.3.0
/usr/local/lib/ruby/site_ruby/3.3.0/aarch64-linux
/usr/local/lib/ruby/site_ruby
/usr/local/lib/ruby/vendor_ruby/3.3.0
/usr/local/lib/ruby/vendor_ruby/3.3.0/aarch64-linux
/usr/local/lib/ruby/vendor_ruby
/usr/local/lib/ruby/3.3.0
/usr/local/lib/ruby/3.3.0/aarch64-linux
/usr/local/bundle/gems/diplomat-2.6.4/lib/diplomat.rb:5: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of diplomat-2.6.4 to add base64 into its gemspec.
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- faraday (LoadError)
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/bundle/gems/diplomat-2.6.4/lib/diplomat.rb:6:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/inline.rb:66:in `block (2 levels) in gemfile'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/settings.rb:157:in `temporary'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/inline.rb:51:in `block in gemfile'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler.rb:424:in `block in with_unbundled_env'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler.rb:679:in `with_env'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler.rb:424:in `with_unbundled_env'
	from /usr/local/lib/ruby/site_ruby/3.3.0/bundler/inline.rb:42:in `gemfile'
	from ./test.rb:5:in `<main>'
```

But if I list my gem directory:

```
# ls /usr/local/bundle/gems/ | grep faraday
faraday-2.7.4
faraday-net_http-3.0.2
faraday-net_http-3.1.0
```

It seems that bundler/inline read the .bundle/config and resolved the inline gemfile with what existed in the cached bundle, but when it set up load paths it used the system gems. I'm not sure what the expected behavior is for using bundler/inline from within a bundle - if it should ignore the local bundle configuration, and only use system gems, or if it should respect the local bundle configuration (including the bundle path - if present), and ignore the system gems. But it certainly should not be assuming a path exists in the system gems that does not!

## Environment

```
Bundler       2.5.10
  Platforms   ruby, aarch64-linux
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.5.10
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.3.0:/usr/local/lib/ruby/gems/3.3.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.3.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.39.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-03
Git SHA           24cac00613
Released Version  true
```

## Bundler settings

```
cache_all
  Set for your local app (/app/.bundle/config): false
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "faraday", "2.9.0"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    faraday (2.9.0)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-net_http (3.1.0)
      net-http
    net-http (0.4.1)
      uri
    uri (0.13.0)

PLATFORMS
  aarch64-linux
  ruby

DEPENDENCIES
  faraday (= 2.9.0)

BUNDLED WITH
   2.5.10
```

**Comment by deivid-rodriguez** [comment]
Interestingly, this does not reproduce on my system 🤔

**Comment by ccutrer** [comment]
I'll try to come up with a dockerfile. I found it on a production Linux system, and then reported on my Mac dev box.

**Comment by ccutrer** [comment]
Okay, I've updated the repro steps with some docker commands. It took me a minute, because it's dependent on .bundle/config being in the app directory, and the ruby docker image sets BUNDLE_APP_CONFIG redirecting it!

**Comment by deivid-rodriguez** [comment]
I just tried to reproduce this and found that https://github.com/rubygems/rubygems/pull/7680 fixed it! 🎉
