### ISSUE TITLE
ruby-core CI is failing: Failure/Error: expect(out).to match(/\A1 : rack\n2 : rack-obama\n0 : - exit -(\n>.*)?\z/)

### ISSUE THREAD

**Issue by k0kubun** [rubygems/rubygems#7713]
### Describe the problem as clearly as you can

ruby/ruby master (as well as rubygems/rubygems ruby-core) CI is failing.

https://github.com/ruby/ruby/actions/runs/9352049059/job/25739247917
https://github.com/rubygems/rubygems/actions/runs/9353249590/job/25743316156?pr=7712

### Did you try upgrading rubygems & bundler?

It's the latest versions in ruby/ruby or this repository.

### Post steps to reproduce the problem

Run the CI of ruby/ruby master or rubygems/rubygems master.

### Which command did you run?

N/A

### What were you expecting to happen?

The tests to pass.

### What actually happened?

<details>

<summary>Test failures</summary>

```
Failures:

  1) bundle show with a valid regexp for gem name presents alternatives
     Failure/Error: expect(out).to match(/\A1 : rack\n2 : rack-obama\n0 : - exit -(\n>.*)?\z/)


       Commands:
       $ /home/runner/work/ruby/ruby/build/ruby -I/home/runner/work/ruby/ruby/src/spec/bundler -r/home/runner/work/ruby/ruby/src/spec/bundler/support/artifice/fail.rb -r/home/runner/work/ruby/ruby/src/spec/bundler/support/hax.rb /home/runner/work/ruby/ruby/src/tmp/5/gems/system/bin/bundle install
       Fetching source index from file:///home/runner/work/ruby/ruby/src/tmp/5/gems/remote1/
       Resolving dependencies...
       Fetching rack 1.0.0
       Installing rack 1.0.0
       Fetching rack-obama 1.0
       Installing rack-obama 1.0
       Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
       Use `bundle info [gemname]` to see where a bundled gem is installed.
       Post-install message from rack:
       Rack's post install message
       Post-install message from rack-obama:
       Rack-obama's post install message
       # $? => 0

       $ /home/runner/work/ruby/ruby/build/ruby -I/home/runner/work/ruby/ruby/src/spec/bundler -r/home/runner/work/ruby/ruby/src/spec/bundler/support/artifice/fail.rb -r/home/runner/work/ruby/ruby/src/spec/bundler/support/hax.rb /home/runner/work/ruby/ruby/src/tmp/5/gems/system/bin/bundle show rac
       1 : rack
       2 : rack-obama
       0 : - exit -
       2004h>  >  
       2004l
       # $? => 0
       expected "1 : rack\n2 : rack-obama\n0 : - exit -\n\e[?2004h>  \e[4G\e[1G\e[K>  \n\e[1G\e[?2004l" to match /\A1 : rack\n2 : rack-obama\n0 : - exit -(\n>.*)?\z/
       Diff:
       @@ -1,5 +1,9 @@
       -/\A1 : rack\n2 : rack-obama\n0 : - exit -(\n>.*)?\z/
       +1 : rack
       +2 : rack-obama
       +0 : - exit -
       +2004h>  >  
       +2004l
     # ./spec/bundler/commands/show_spec.rb:176:in 'block (3 levels) in <top (required)>'
     # ./spec/bundler/spec_helper.rb:106:in 'block (4 levels) in <top (required)>'
     # ./spec/bundler/spec_helper.rb:106:in 'block (3 levels) in <top (required)>'
     # ./spec/bundler/support/helpers.rb:378:in 'block in Spec::Helpers#with_gem_path_as'
     # ./spec/bundler/support/helpers.rb:392:in 'Spec::Helpers#without_env_side_effects'
     # ./spec/bundler/support/helpers.rb:373:in 'Spec::Helpers#with_gem_path_as'
     # ./spec/bundler/spec_helper.rb:105:in 'block (2 levels) in <top (required)>'

Finished in 18 minutes 13 seconds (files took 1.62 seconds to load)
473 examples, 1 failure

Failed examples:

rspec ./spec/bundler/commands/show_spec.rb:168 # bundle show with a valid regexp for gem name presents alternatives

...............................................................................................................................

Finished in 19 minutes 22 seconds (files took 1.37 seconds to load)
668 examples, 0 failures, 11 pending

........................................................

Failures:

  1) bundle info with a valid regexp for gem name presents alternatives
     Failure/Error: expect(out).to match(/\A1 : rack\n2 : rack-obama\n0 : - exit -(\n>.*)?\z/)


       Commands:
       $ /home/runner/work/ruby/ruby/build/ruby -I/home/runner/work/ruby/ruby/src/spec/bundler -r/home/runner/work/ruby/ruby/src/spec/bundler/support/artifice/fail.rb -r/home/runner/work/ruby/ruby/src/spec/bundler/support/hax.rb /home/runner/work/ruby/ruby/src/tmp/3/gems/system/bin/bundle install
       Fetching source index from file:///home/runner/work/ruby/ruby/src/tmp/3/gems/remote1/
       Resolving dependencies...
       Fetching rack 1.0.0
       Installing rack 1.0.0
       Fetching rack-obama 1.0
       Installing rack-obama 1.0
       Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
       Use `bundle info [gemname]` to see where a bundled gem is installed.
       Post-install message from rack:
       Rack's post install message
       Post-install message from rack-obama:
       Rack-obama's post install message
       # $? => 0

       $ /home/runner/work/ruby/ruby/build/ruby -I/home/runner/work/ruby/ruby/src/spec/bundler -r/home/runner/work/ruby/ruby/src/spec/bundler/support/artifice/fail.rb -r/home/runner/work/ruby/ruby/src/spec/bundler/support/hax.rb /home/runner/work/ruby/ruby/src/tmp/3/gems/system/bin/bundle info rac
       1 : rack
       2 : rack-obama
       0 : - exit -
       2004h>  >  
       2004l
       # $? => 0
       expected "1 : rack\n2 : rack-obama\n0 : - exit -\n\e[?2004h>  \e[4G\e[1G\e[K>  \n\e[1G\e[?2004l" to match /\A1 : rack\n2 : rack-obama\n0 : - exit -(\n>.*)?\z/
       Diff:
       @@ -1,5 +1,9 @@
       -/\A1 : rack\n2 : rack-obama\n0 : - exit -(\n>.*)?\z/
       +1 : rack
       +2 : rack-obama
       +0 : - exit -
       +2004h>  >  
       +2004l
     # ./spec/bundler/commands/info_spec.rb:218:in 'block (3 levels) in <top (required)>'
     # ./spec/bundler/spec_helper.rb:106:in 'block (4 levels) in <top (required)>'
     # ./spec/bundler/spec_helper.rb:106:in 'block (3 levels) in <top (required)>'
     # ./spec/bundler/support/helpers.rb:378:in 'block in Spec::Helpers#with_gem_path_as'
     # ./spec/bundler/support/helpers.rb:392:in 'Spec::Helpers#without_env_side_effects'
     # ./spec/bundler/support/helpers.rb:373:in 'Spec::Helpers#with_gem_path_as'
     # ./spec/bundler/spec_helper.rb:105:in 'block (2 levels) in <top (required)>'

Finished in 20 minutes 25 seconds (files took 1.61 seconds to load)
607 examples, 1 failure, 1 pending
```

</details>

### If not included with the output of your command, run `bundle env` and paste the output below

N/A

**Comment by k0kubun** [comment]
Reverted the commit that triggered the failure for now https://github.com/ruby/ruby/commit/6e84ac2359c8fc8cb686ef4644b9cae26cd5ab9e.
