### ISSUE TITLE
Bundler hanging on acquiring lock

### ISSUE THREAD

**Issue by bdewater** [rubygems/rubygems#7732]
### Describe the problem as clearly as you can

`bundle install` was hanging with no clear indication what it was doing. Even with all the possible debug/verbose flags I could find it was not clear what was happening, until I hit ctrl+c and started reading the [source code](https://github.com/rubygems/rubygems/blob/975ee9da6db427524b5fc095be6b4d3831437bbb/bundler/lib/bundler/process_lock.rb#L10):
```sh
:   0: Starting resolution (2024-06-11 10:40:28 -0400)
:   0: User-requested dependencies: [#<Gem::Resolver::DependencyRequest:0x00000001008a63c0 @dependency=<Gem::Dependency type=:runtime name="error_highlight" requirements="= 0.6.0">, @requester=nil>, #<Gem::Resolver::DependencyRequest:0x00000001008a6320 @dependency=<Gem::Dependency type=:runtime name="did_you_mean" requirements="= 1.6.3">, @requester=nil>, #<Gem::Resolver::DependencyRequest:0x00000001008a62f8 @dependency=<Gem::Dependency type=:runtime name="syntax_suggest" requirements="= 2.0.0">, @requester=nil>, #<Gem::Resolver::DependencyRequest:0x00000001008a62d0 @dependency=<Gem::Dependency type=:runtime name="bundler" requirements="= 2.5.11">, @requester=nil>]
Resolving dependencies...:   0: Creating possibility state for error_highlight (= 0.6.0) (1 remaining)
:   1: Attempting to activate [error_highlight-0.6.0]
:   1: Activated error_highlight at [error_highlight-0.6.0]
:   1: Requiring nested dependencies ()
:   1: Creating possibility state for did_you_mean (= 1.6.3) (1 remaining)
:   2: Attempting to activate [did_you_mean-1.6.3]
:   2: Activated did_you_mean at [did_you_mean-1.6.3]
:   2: Requiring nested dependencies ()
:   2: Creating possibility state for syntax_suggest (= 2.0.0) (1 remaining)
:   3: Attempting to activate [syntax_suggest-2.0.0]
:   3: Activated syntax_suggest at [syntax_suggest-2.0.0]
:   3: Requiring nested dependencies ()
:   3: Creating possibility state for bundler (= 2.5.11) (1 remaining)
:   4: Attempting to activate [bundler-2.5.11]
:   4: Activated bundler at [bundler-2.5.11]
:   4: Requiring nested dependencies ()

:   0: Finished resolution (4 steps) (Took 0.002206 seconds) (2024-06-11 10:40:28 -0400)
:   0: Unactivated: 
:   0: Activated: error_highlight, did_you_mean, syntax_suggest, bundler
Running `bundle install --verbose` with bundler 2.5.11
load: 1.83  cmd: ruby 83729 waiting 0.14u 0.03s
^C
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/process_lock.rb:10:in `flock'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/process_lock.rb:10:in `block in lock'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/process_lock.rb:9:in `open'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/process_lock.rb:9:in `lock'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/installer.rb:71:in `run'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/installer.rb:23:in `install'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/cli/install.rb:63:in `run'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:247:in `block in install'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/settings.rb:157:in `temporary'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:246:in `install'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:29:in `start'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
/Users/bdewater/.rbenv/versions/3.3.2/bin/bundle:25:in `load'
/Users/bdewater/.rbenv/versions/3.3.2/bin/bundle:25:in `<main>'

```

### Did you try upgrading rubygems & bundler?

Yes, problem occurred both with bundler 2.5.9 and 2.5.11.

### Post steps to reproduce the problem

I'm using Ruby 3.3.2, managed via rbenv 1.2.0, on macOS Sonoma 14.5. I'm not entirely sure how I managed to not hit the `ensure` block in aforementioned source link.

I did not have any hung Ruby processes. But for what it's worth, I am using Visual Studio Code with ruby-lsp, ruby-lsp-rails and the Sorbet LSP - I believe these do run their own stuff and use  Bundler behind the scenes?

I can recreate the situation artificially by opening a new terminal, starting IRB and running the following:
```rb
require 'bundler'
Bundler::ProcessLock.lock { sleep 100 }
```
and then trying `bundle install` in another tab. 

### Which command did you run?

`DEBUG=1 DEBUG_RESOLVER=1 DEBUG_RESOLVER_TREE=1 DEBUG_COMPACT_INDEX=1 bundle install --verbose`

### What were you expecting to happen?

One of these debug/verbose flags outputting a message about trying to acquire the lock.

And maybe a timeout for acquiring this lock - while I was Googling for info on the `flock` method I found https://github.com/Shopify/shipit-engine/blob/4a7977500b9e93af93bc5d1a02593fdb5b0fde0a/lib/shipit/flock.rb which implements something like this.

### What actually happened?

No output, no timeout.

## Environment

```
Bundler       2.5.11
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.2p78 (2024-05-30 revision e5a195edf62fe1bf7146a191da13fa1c4fecbd71) [arm64-darwin-23]
  Full Path   /Users/bdewater/.rbenv/versions/3.3.2/bin/ruby
  Config Dir  /Users/bdewater/.rbenv/versions/3.3.2/etc
RubyGems      3.5.11
  Gem Home    /Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0
  Gem Path    /Users/bdewater/.gem/ruby/3.3.0:/Users/bdewater/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0
  User Home   /Users/bdewater
  User Path   /Users/bdewater/.gem/ruby/3.3.0
  Bin Dir     /Users/bdewater/.rbenv/versions/3.3.2/bin
Tools         
  Git         2.45.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-28
Git SHA           4afb2d450a
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/bdewater/.bundle/config): false
gem.ci
  Set for the current user (/Users/bdewater/.bundle/config): "github"
gem.coc
  Set for the current user (/Users/bdewater/.bundle/config): false
gem.linter
  Set for the current user (/Users/bdewater/.bundle/config): "rubocop"
gem.mit
  Set for the current user (/Users/bdewater/.bundle/config): false
gem.test
  Set for the current user (/Users/bdewater/.bundle/config): "minitest"
```
I don't believe the Gemfile is relevant so I omitted it for now.

**Comment by deivid-rodriguez** [comment]
Funny enough, this also happened to me a couple of days ago while debugging https://github.com/rubygems/rubygems/issues/7723. Somehow I managed to leave one of these infinite resolutions running in the background, and after that all my `bundle` commands would just hang with no output.

I think your suggestion of adding a timeout with some hint would definitely be an improvement!

**Comment by rubyFeedback** [comment]
> adding a timeout with some hint

This may be useful in general. Recently I called a method I named readlines(), assuming it would read a method I defined in a custom module (just as a wrapper over File.readlines()). The class hung, though, and I was confused why, until I realiased there is already a method called readlines() available by default.

**Comment by andyw8** [comment]
I ran into this too, I think it could be Ruby LSP related. https://github.com/Shopify/ruby-lsp/issues/2387

**Comment by bdewater** [comment]
I ran into this again earlier today: I rebased an old branch with VS Code open on latest main of my app, the Ruby LSP initializing message shows (from above PR) and didn't go away. After manually clearing the lock file and running `bundle` manually, I noticed I needed to wait 5-10 seconds for one native gem (AppSignal) to compile, which feels like it could be related.

I was annoyed enough to take a stab at adding a timeout to the locking: https://github.com/rubygems/rubygems/pull/8040 :)
