### ISSUE TITLE
"NoMethodError: undefined method 'name' for nil" when calling `bundle update --bundler`

### ISSUE THREAD

**Issue by dorianmariecom** [rubygems/rubygems#7789]
### Describe the problem as clearly as you can

`bundle update --bundler` fails with ruby error

### Did you try upgrading rubygems & bundler?

It happens when upgrading bundler.

### Post steps to reproduce the problem

- Clone github.com/dorianmariecom/dorian-each
- `bundle update --bundler`

### Which command did you run?

`bundle update --bundler`

### What were you expecting to happen?

Upgrading bundler to the latest version

### What actually happened?

Error

### If not included with the output of your command, run `bundle env` and paste the output below

```
NoMethodError: undefined method `name' for nil
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/spec_set.rb:241:in `block in sorted'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/spec_set.rb:241:in `each'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/spec_set.rb:241:in `find'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/spec_set.rb:241:in `sorted'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/spec_set.rb:191:in `each'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/installer.rb:83:in `block in run'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/process_lock.rb:12:in `block in lock'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/process_lock.rb:9:in `open'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/process_lock.rb:9:in `lock'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/installer.rb:71:in `run'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/installer.rb:23:in `install'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli/update.rb:79:in `run'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:277:in `block in update'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/settings.rb:158:in `temporary'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:276:in `update'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/exe/bundle:28:in `block in <top (required)>'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.14/exe/bundle:20:in `<top (required)>'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/bin/bundle:25:in `load'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.5.9
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [arm64-darwin-23]
  Full Path   /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/bin/ruby
  Config Dir  /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/etc
RubyGems      3.5.9
  Gem Home    /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0
  Gem Path    /Users/dorianmariefr/.gem/ruby/3.3.0:/Users/dorianmariefr/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0
  User Home   /Users/dorianmariefr
  User Path   /Users/dorianmariefr/.gem/ruby/3.3.0
  Bin Dir     /Users/dorianmariefr/.asdf/installs/ruby/3.3.1/bin
OpenSSL       
  Compiled    OpenSSL 3.2.1 30 Jan 2024
  Loaded      OpenSSL 3.3.1 4 Jun 2024
  Cert File   /opt/homebrew/etc/openssl@3/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@3/certs
Tools         
  Git         2.45.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-06-21
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
build.mysql2
  Set for the current user (/Users/dorianmariefr/.bundle/config): "-- --with-cflags=\\\"-Wno-error=implicit-function-declaration\\\" --with-ldflags=-L/opt/homebrew/opt/zstd/lib"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gemspec

ruby "3.3.1"

gem "dorian-times"
gem "rspec"
gem "rubocop-rails-omakase"
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    dorian-each (0.3.7)

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.1.3.4)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    ast (2.4.2)
    base64 (0.2.0)
    bigdecimal (3.1.8)
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    diff-lcs (1.5.1)
    dorian-times (0.4.4)
    drb (2.2.1)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    json (2.7.2)
    language_server-protocol (3.17.0.3)
    minitest (5.24.0)
    mutex_m (0.2.0)
    parallel (1.25.1)
    parser (3.3.3.0)
      ast (~> 2.4.1)
      racc
    racc (1.8.0)
    rack (3.1.3)
    rainbow (3.1.1)
    regexp_parser (2.9.2)
    rexml (3.3.0)
      strscan
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.0)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-support (3.13.1)
    rubocop (1.64.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.31.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.31.3)
      parser (>= 3.3.1.0)
    rubocop-minitest (0.35.0)
      rubocop (>= 1.61, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-performance (1.21.1)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails (2.25.0)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails-omakase (1.0.0)
      rubocop
      rubocop-minitest
      rubocop-performance
      rubocop-rails
    ruby-progressbar (1.13.0)
    strscan (3.1.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)

PLATFORMS
  arm64-darwin-23
  ruby

DEPENDENCIES
  dorian-each!
  dorian-times
  rspec
  rubocop-rails-omakase

RUBY VERSION
   ruby 3.3.1p55

BUNDLED WITH
   2.5.11
```

### dorian-each.gemspec

```ruby
# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name = "dorian-each"
  s.version = "0.3.7"
  s.summary = "Evaluates some code on each line of the input"
  s.description = "#{s.summary}\n\ne.g. `ls -l | each \"puts it.split.first\"`"
  s.authors = ["Dorian Marié"]
  s.email = "dorian@dorianmarie.com"
  s.files = ["bin/each"]
  s.executables << "each"
  s.homepage = "https://github.com/dorianmariecom/dorian-each"
  s.license = "MIT"
  s.metadata = { "rubygems_mfa_required" => "true" }

  s.required_ruby_version = ">= 3.3.0"
end
```

**Comment by deivid-rodriguez** [comment]
This sounds very similar to https://github.com/rubygems/rubygems/issues/7381. The error message for that was improved by https://github.com/rubygems/rubygems/pull/7642, but of course you need to upgrade Bundler to pick up that fix, so chicken and egg problem. So this time, you can upgrade Bundler manually:

* First install the latest Bundler with `gem install bundler`.
* Then update the lockfile with `bundle lock --update --bundler`.

I _believe_ that should allow you to upgrade without running into that problem.

In https://github.com/rubygems/rubygems/pull/7381, the underlying problem was a corrupt Ruby installation, so if you still run into problems, it may be something similar. Feel free to reach out for help if you still run into issues!

**Comment by dorianmariecom** [comment]
Yeah I ended up doing `gem install bundler` and `bundle update --bundler` and that worked, not sure what is wrong with my ruby installation, maybe because I was on 3.3.1
