### ISSUE TITLE
shopify admin app with app embed extension fails to start

### ISSUE THREAD

**Issue by ciricroft** [rubygems/rubygems#7791]
### Describe the problem as clearly as you can

I can't run my shopify admin app

### Did you try upgrading rubygems & bundler?
yes

### What were you expecting to happen?

app should run

### What actually happened?

```
Errno::ENOENT: No such file or directory - "E:/Program Files/Ruby33-x64/bin/ruby.exe"
  E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:77:in `exec'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:77:in `block in restart_with'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler.rb:387:in `block in with_original_env'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler.rb:659:in `with_env'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler.rb:387:in `with_original_env'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:76:in `restart_with'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:12:in `restart_with_locked_bundler_if_needed'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/cli.rb:67:in `initialize'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:523:in `new'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:523:in `dispatch'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
          E:/Program Files/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
          E:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          E:/Program Files/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
          E:/Program Files/Ruby33-x64/bin/bundle:33:in `load'
          E:/Program Files/Ruby33-x64/bin/bundle:33:in `<main>'

```

## Environment

```
Bundler       2.5.9
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.3.2p79 (2024-05-30 revision e5a195edf62fe1bf7146a191da13fa1c4fecbd71) [x64-mingw-ucrt]
  Full Path   "E:/Program Files/Ruby33-x64/bin/ruby.exe"
  Config Dir  C:/ProgramData
RubyGems      3.5.9
  Gem Home    C:/Users/PCBOMB/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.3.0
  Gem Path    C:/Users/PCBOMB/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.3.0
  User Home   C:/Users/PCBOMB
  User Path   C:/Users/PCBOMB/.local/share/gem/ruby/3.3.0
  Bin Dir     C:/Users/PCBOMB/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.3.0/bin
Tools
  Git         2.43.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-06-24
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
path
  Set via BUNDLE_PATH: "C:\\Users\\PCBOMB\\AppData\\Local\\shopify-gems-nodejs\\Cache"
user_home
  Set via BUNDLE_USER_HOME: "C:[REDACTED]"
without
  Set via BUNDLE_WITHOUT: [:development, :test]
```

### Gemfile

```ruby
# NOTE: These are development-only dependencies
source "https://rubygems.org"

gem "bugsnag", "~> 6.22"
gem "listen", "~> 3.7.0"

# None of these can actually be used in a development copy of dev
# They are all for CI and tests
# `dev` uses no gems
group :development, :test do
  gem "pry-byebug"
  gem "byebug"
  gem "rubocop-shopify", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-rake", require: false
  gem "iniparse", "~> 1.5"
  gem "colorize", "~> 0.8.1"
  gem "bundler", ">= 2.3.11"
  gem "rake", "~> 12.3", ">= 12.3.3"
  gem "minitest", "~> 5.0"
end

group :test do
  gem "mocha", require: false
  gem "minitest-reporters", require: false
  gem "minitest-fail-fast", require: false
  gem "fakefs", ">= 1.0", require: false
  gem "webmock", require: false
  gem "timecop", require: false
  gem "rack", require: false
  gem "cucumber", "~> 7.0", require: false
end
gem 'wdm', '>= 0.1.0'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.6)
      public_suffix (>= 2.0.2, < 6.0)
    ansi (1.5.0)
    ast (2.4.2)
    bigdecimal (3.1.8)
    bugsnag (6.27.1)
      concurrent-ruby (~> 1.0)
    builder (3.3.0)
    byebug (11.1.3)
    coderay (1.1.3)
    colorize (0.8.1)
    concurrent-ruby (1.3.3)
    crack (1.0.0)
      bigdecimal
      rexml
    cucumber (7.1.0)
      builder (~> 3.2, >= 3.2.4)
      cucumber-core (~> 10.1, >= 10.1.0)
      cucumber-create-meta (~> 6.0, >= 6.0.1)
      cucumber-cucumber-expressions (~> 14.0, >= 14.0.0)
      cucumber-gherkin (~> 22.0, >= 22.0.0)
      cucumber-html-formatter (~> 17.0, >= 17.0.0)
      cucumber-messages (~> 17.1, >= 17.1.1)
      cucumber-wire (~> 6.2, >= 6.2.0)
      diff-lcs (~> 1.4, >= 1.4.4)
      mime-types (~> 3.3, >= 3.3.1)
      multi_test (~> 0.1, >= 0.1.2)
      sys-uname (~> 1.2, >= 1.2.2)
    cucumber-core (10.1.1)
      cucumber-gherkin (~> 22.0, >= 22.0.0)
      cucumber-messages (~> 17.1, >= 17.1.1)
      cucumber-tag-expressions (~> 4.1, >= 4.1.0)
    cucumber-create-meta (6.0.4)
      cucumber-messages (~> 17.1, >= 17.1.1)
      sys-uname (~> 1.2, >= 1.2.2)
    cucumber-cucumber-expressions (14.0.0)
    cucumber-gherkin (22.0.0)
      cucumber-messages (~> 17.1, >= 17.1.1)
    cucumber-html-formatter (17.0.0)
      cucumber-messages (~> 17.1, >= 17.1.0)
    cucumber-messages (17.1.1)
    cucumber-tag-expressions (4.1.0)
    cucumber-wire (6.2.1)
      cucumber-core (~> 10.1, >= 10.1.0)
      cucumber-cucumber-expressions (~> 14.0, >= 14.0.0)
    diff-lcs (1.5.1)
    fakefs (2.5.0)
    ffi (1.17.0-x64-mingw-ucrt)
    hashdiff (1.1.0)
    iniparse (1.5.0)
    json (2.7.2)
    language_server-protocol (3.17.0.3)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    method_source (1.1.0)
    mime-types (3.5.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2024.0604)
    minitest (5.23.1)
    minitest-fail-fast (0.1.0)
      minitest (~> 5)
    minitest-reporters (1.6.1)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    mocha (2.4.0)
      ruby2_keywords (>= 0.0.5)
    multi_test (0.1.2)
    parallel (1.25.1)
    parser (3.3.3.0)
      ast (~> 2.4.1)
      racc
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.10.1)
      byebug (~> 11.0)
      pry (>= 0.13, < 0.15)
    public_suffix (5.1.1)
    racc (1.8.0)
    rack (3.1.3)
    rainbow (3.1.1)
    rake (12.3.3)
    rb-fsevent (0.11.2)
    rb-inotify (0.11.1)
      ffi (~> 1.0)
    regexp_parser (2.9.2)
    rexml (3.3.0)
      strscan
    rubocop (1.64.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.31.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.31.3)
      parser (>= 3.3.1.0)
    rubocop-minitest (0.35.0)
      rubocop (>= 1.61, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rake (0.6.0)
      rubocop (~> 1.0)
    rubocop-shopify (2.15.1)
      rubocop (~> 1.51)
    ruby-progressbar (1.13.0)
    ruby2_keywords (0.0.5)
    strscan (3.1.0)
    sys-uname (1.3.0)
      ffi (~> 1.1)
    timecop (0.9.10)
    unicode-display_width (2.5.0)
    wdm (0.1.1)
    webmock (3.23.1)
      addressable (>= 2.8.0)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)

PLATFORMS
  x64-mingw-ucrt

DEPENDENCIES
  bugsnag (~> 6.22)
  bundler (>= 2.3.11)
  byebug
  colorize (~> 0.8.1)
  cucumber (~> 7.0)
  fakefs (>= 1.0)
  iniparse (~> 1.5)
  listen (~> 3.7.0)
  minitest (~> 5.0)
  minitest-fail-fast
  minitest-reporters
  mocha
  pry-byebug
  rack
  rake (~> 12.3, >= 12.3.3)
  rubocop-minitest
  rubocop-rake
  rubocop-shopify
  timecop
  wdm (>= 0.1.0)
  webmock

BUNDLED WITH
   2.4.19
```

**Comment by glenxkie** [comment]
Facing the same issue :(

**Comment by deivid-rodriguez** [comment]
Hei! I guess this may be escaping related? If you edit Bundler code like this:

```diff
diff --git a/bundler/lib/bundler/self_manager.rb b/bundler/lib/bundler/self_manager.rb
index 3cef0197c0..786e9b08a9 100644
--- a/bundler/lib/bundler/self_manager.rb
+++ b/bundler/lib/bundler/self_manager.rb
@@ -71,7 +71,12 @@ def restart_with(version)
       configured_gem_path = ENV["GEM_PATH"]
 
       cmd = [$PROGRAM_NAME, *ARGV]
-      cmd.unshift(Gem.ruby) unless File.executable?($PROGRAM_NAME)
+
+      unless File.executable?($PROGRAM_NAME)
+        require "shellwords"
+
+        cmd.unshift(Shellwords.shellescape(Gem.ruby))
+      end
 
       Bundler.with_original_env do
         Kernel.exec(
```

Does it fix the problem?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by deivid-rodriguez** [comment]
Reopening since @ZhanXieXz may be interested in following up.

**Comment by hsbt** [comment]
@C-Crowd-Control-C @glenxkie @ZhanXieXz Can you try https://github.com/ruby/rubygems/issues/7791#issuecomment-2189011416 with your app?

If you have still some issues, please let me know about that.
