### ISSUE TITLE
bundler uses x86_64-linux instead of x86_64-linux-gnu which cases 403 on rubygems.org

### ISSUE THREAD

**Issue by bigon** [rubygems/rubygems#7802]
### Describe the problem as clearly as you can

When running `bundler install` in the following git repository https://github.com/voxpupuli/puppet-extlib I get the following error:

```
$ bundler install
Fetching gem metadata from https://rubygems.org/.......
Fetching ffi 1.17.0 (x86_64-linux)

Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)

Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to underlying error <bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)>
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/rubygems_integration.rb:497:in `rescue in download_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/rubygems_integration.rb:469:in `download_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:481:in `download_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:443:in `fetch_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:427:in `fetch_gem_if_possible'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:161:in `install'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:62:in `apply_func'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:54:in `loop'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:54:in `process_queue'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing ffi (1.17.0), and Bundler cannot continue.

In Gemfile:
  voxpupuli-acceptance was resolved to 3.2.0, which depends on
    winrm was resolved to 2.3.6, which depends on
      gssapi was resolved to 1.3.1, which depends on
        ffi

```

### Did you try upgrading rubygems & bundler?

Running debian unstable version: Bundler version 2.4.20

### Which command did you run?

```
$ bundler config set --local path  ./bundler
$ bundler install
```
### What were you expecting to happen?

The dependencies should be installed successfully

### What actually happened?

The ffi gem failed to download

## Environment

```
Bundler       2.4.20
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /usr/bin/ruby3.1
  Config Dir  /etc
RubyGems      3.4.20
  Gem Home    /var/lib/gems/3.1.0
  Gem Path    /home/bigon/.local/share/gem/ruby/3.1.0:/var/lib/gems/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/lib/ruby/gems/3.1.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.1.0:/usr/share/rubygems-integration/3.1.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0
  User Home   /home/bigon
  User Path   /home/bigon/.local/share/gem/ruby/3.1.0
  Bin Dir     /usr/local/bin
Tools         
  Git         2.45.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      /usr/bin/ruby3.1
bundle #!     /usr/bin/ruby

```

## Bundler Build Metadata

```
Built At          2024-06-27
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
path
  Set for your local app (/home/bigon/Development/Upstream/puppet-extlib/.bundle/config): "./bundler"
```

### Gemfile

```ruby
# Managed by modulesync - DO NOT EDIT
# https://voxpupuli.org/docs/updating-files-managed-with-modulesync/

source ENV['GEM_SOURCE'] || 'https://rubygems.org'

group :test do
  gem 'voxpupuli-test', '~> 8.0',   :require => false
  gem 'coveralls',                  :require => false
  gem 'simplecov-console',          :require => false
  gem 'puppet_metadata', '~> 4.0',  :require => false
end

group :development do
  gem 'guard-rake',               :require => false
  gem 'overcommit', '>= 0.39.1',  :require => false
end

group :system_tests do
  gem 'voxpupuli-acceptance', '~> 3.0',  :require => false
end

group :release do
  gem 'voxpupuli-release', '~> 3.0',  :require => false
end

gem 'rake', :require => false
gem 'facter', ENV['FACTER_GEM_VERSION'], :require => false, :groups => [:test]

puppetversion = ENV['PUPPET_GEM_VERSION'] || '~> 7.24'
gem 'puppet', puppetversion, :require => false, :groups => [:test]

# vim: syntax=ruby
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.1.3.4)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    ansi (1.5.0)
    ast (2.4.2)
    async (2.12.1)
      console (~> 1.25, >= 1.25.2)
      fiber-annotation
      io-event (~> 1.6, >= 1.6.5)
    async-http (0.69.0)
      async (>= 2.10.2)
      async-pool (~> 0.7)
      io-endpoint (~> 0.11)
      io-stream (~> 0.4)
      protocol-http (~> 0.26)
      protocol-http1 (~> 0.19)
      protocol-http2 (~> 0.18)
      traces (>= 0.10)
    async-http-faraday (0.14.0)
      async-http (~> 0.42)
      faraday
    async-pool (0.7.0)
      async (>= 1.25)
    base64 (0.2.0)
    bcrypt_pbkdf (1.1.1)
    beaker (6.1.0)
      bcrypt_pbkdf (>= 1.0, < 2.0)
      beaker-hostgenerator (~> 2.0)
      ed25519 (>= 1.2, < 2.0)
      hocon (~> 1.0)
      in-parallel (>= 0.1, < 2.0)
      inifile (~> 3.0)
      minitar (~> 0.6)
      minitest (~> 5.4)
      net-scp (>= 1.2, < 5.0)
      net-ssh (~> 7.1)
      rexml (~> 3.2, >= 3.2.5)
      rsync (~> 1.0.9)
      stringify-hash (~> 0.0)
      thor (>= 1.0.1, < 2.0)
    beaker-docker (2.3.0)
      beaker (>= 4, < 7)
      docker-api (~> 2.1)
      stringify-hash (~> 0.0.0)
    beaker-hiera (1.1.1)
      beaker (>= 4, < 7)
    beaker-hostgenerator (2.14.0)
      deep_merge (~> 1.0)
    beaker-rspec (8.2.0)
      beaker (>= 4.0, < 7)
      rspec (~> 3.0)
      serverspec (~> 2)
      specinfra (~> 2)
    beaker-vagrant (1.4.0)
      beaker (>= 4, < 7)
    beaker_puppet_helpers (1.4.0)
      beaker (>= 5.8.1, < 7)
      puppet-modulebuilder (>= 0.3, < 2)
    bigdecimal (3.1.8)
    builder (3.3.0)
    childprocess (5.0.0)
    coderay (1.1.3)
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    console (1.25.2)
      fiber-annotation
      fiber-local (~> 1.1)
      json
    coveralls (0.8.23)
      json (>= 1.8, < 3)
      simplecov (~> 0.16.1)
      term-ansicolor (~> 1.3)
      thor (>= 0.19.4, < 2.0)
      tins (~> 1.6)
    deep_merge (1.2.2)
    diff-lcs (1.5.1)
    docile (1.4.0)
    docker-api (2.2.0)
      excon (>= 0.47.0)
      multi_json
    domain_name (0.6.20240107)
    drb (2.2.1)
    ed25519 (1.3.0)
    erubi (1.13.0)
    excon (0.110.0)
    facter (4.7.1)
      hocon (~> 1.3)
      thor (>= 1.0.1, < 1.3)
    facterdb (2.1.0)
      facter (< 5.0.0)
      jgrep (~> 1.5, >= 1.5.4)
    faraday (2.9.2)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-http-cache (2.5.1)
      faraday (>= 0.8)
    faraday-net_http (3.1.0)
      net-http
    faraday-retry (2.2.1)
      faraday (~> 2.0)
    fast_gettext (2.4.0)
      prime
    ffi (1.17.0-x86_64-linux)
    fiber-annotation (0.2.0)
    fiber-local (1.1.0)
      fiber-storage
    fiber-storage (0.1.2)
    formatador (1.1.0)
    forwardable (1.3.3)
    github_changelog_generator (1.16.4)
      activesupport
      async (>= 1.25.0)
      async-http-faraday
      faraday-http-cache
      multi_json
      octokit (~> 4.6)
      rainbow (>= 2.2.1)
      rake (>= 10.0)
    gssapi (1.3.1)
      ffi (>= 1.0.1)
    guard (2.18.1)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (>= 1.0.12, < 2.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.13.0)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-rake (1.0.0)
      guard
      rake
    gyoku (1.4.0)
      builder (>= 2.1.2)
      rexml (~> 3.0)
    hiera (3.12.0)
    hocon (1.4.0)
    http-accept (1.7.0)
    http-cookie (1.0.6)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    in-parallel (1.0.1)
    inifile (3.0.0)
    iniparse (1.5.0)
    io-endpoint (0.11.0)
    io-event (1.6.5)
    io-stream (0.4.0)
    jgrep (1.5.4)
    json (2.7.2)
    json-schema (4.3.0)
      addressable (>= 2.8)
    listen (3.9.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    little-plugger (1.1.4)
    locale (2.1.4)
    logging (2.4.0)
      little-plugger (~> 1.1)
      multi_json (~> 1.14)
    lumberjack (1.2.10)
    metadata-json-lint (4.0.0)
      json-schema (>= 2.8, < 5.0)
      semantic_puppet (~> 1.0)
      spdx-licenses (~> 1.0)
    method_source (1.1.0)
    mime-types (3.5.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2024.0604)
    minitar (0.9)
    minitest (5.24.0)
    mize (0.4.1)
      protocol (~> 2.0)
    mocha (1.16.1)
    multi_json (1.15.0)
    mutex_m (0.2.0)
    nenv (0.3.0)
    net-http (0.4.1)
      uri
    net-scp (4.0.0)
      net-ssh (>= 2.6.5, < 8.0.0)
    net-ssh (7.2.3)
    net-telnet (0.2.0)
    netrc (0.11.0)
    nori (2.7.0)
      bigdecimal
    notiffany (0.1.3)
      nenv (~> 0.1)
      shellany (~> 0.0)
    octokit (4.25.1)
      faraday (>= 1, < 3)
      sawyer (~> 0.9)
    overcommit (0.63.0)
      childprocess (>= 0.6.3, < 6)
      iniparse (~> 1.4)
      rexml (~> 3.2)
    parallel (1.25.1)
    parallel_tests (4.7.1)
      parallel
    parser (3.3.3.0)
      ast (~> 2.4.1)
      racc
    pathspec (1.1.3)
    prime (0.1.2)
      forwardable
      singleton
    protocol (2.0.0)
      ruby_parser (~> 3.0)
    protocol-hpack (1.4.3)
    protocol-http (0.26.6)
    protocol-http1 (0.19.1)
      protocol-http (~> 0.22)
    protocol-http2 (0.18.0)
      protocol-hpack (~> 1.4)
      protocol-http (~> 0.18)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    public_suffix (6.0.0)
    puppet (7.31.0)
      concurrent-ruby (~> 1.0)
      deep_merge (~> 1.0)
      facter (> 2.0.1, < 5)
      fast_gettext (>= 1.1, < 3)
      hiera (>= 3.2.1, < 4)
      locale (~> 2.1)
      multi_json (~> 1.10)
      puppet-resource_api (~> 1.5)
      scanf (~> 1.0)
      semantic_puppet (~> 1.0)
    puppet-blacksmith (7.0.0)
      puppet-modulebuilder (~> 1.0)
      rest-client (~> 2.0)
    puppet-lint (4.2.4)
    puppet-lint-absolute_classname-check (4.0.0)
      puppet-lint (>= 3.0, < 5)
    puppet-lint-anchor-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-file_ensure-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-leading_zero-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-lookup_in_parameter-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-manifest_whitespace-check (0.3.0)
      puppet-lint (>= 1.0, < 5)
    puppet-lint-optional_default-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-param-docs (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-param-types (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-params_empty_string-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-resource_reference_syntax (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-strict_indent-check (3.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-topscope-variable-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-trailing_comma-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-unquoted_string-check (3.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-variable_contains_upcase (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-lint-version_comparison-check (2.0.0)
      puppet-lint (>= 3, < 5)
    puppet-modulebuilder (1.0.0)
      minitar (~> 0.9)
      pathspec (>= 0.2.1, < 2.0.0)
    puppet-resource_api (1.9.0)
      hocon (>= 1.0)
    puppet-strings (4.1.2)
      rgen (~> 0.9)
      yard (~> 0.9)
    puppet-syntax (4.1.1)
      puppet (>= 7, < 9)
      rake (~> 13.1)
    puppet_metadata (4.0.0)
      metadata-json-lint (>= 2.0, < 5)
      semantic_puppet (~> 1.0)
    puppetlabs_spec_helper (7.3.1)
      mocha (~> 1.0)
      pathspec (>= 0.2, < 2.0.0)
      puppet-lint (~> 4.0)
      puppet-syntax (~> 4.1, >= 4.1.1)
      rspec-github (~> 2.0)
      rspec-puppet (~> 4.0)
    racc (1.8.0)
    rainbow (3.1.1)
    rake (13.2.1)
    rb-fsevent (0.11.2)
    rb-inotify (0.11.1)
      ffi (~> 1.0)
    regexp_parser (2.9.2)
    rest-client (2.1.0)
      http-accept (>= 1.7.0, < 2.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rexml (3.3.1)
      strscan
    rgen (0.9.1)
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.0)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-github (2.4.0)
      rspec-core (~> 3.0)
    rspec-its (1.3.0)
      rspec-core (>= 3.0.0)
      rspec-expectations (>= 3.0.0)
    rspec-mocks (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-puppet (4.0.2)
      rspec (~> 3.0)
    rspec-puppet-facts (4.0.0)
      deep_merge (~> 1.2)
      facter (< 5)
      facterdb (~> 2.1)
      puppet (>= 7, < 9)
    rspec-puppet-utils (3.4.0)
      mocha
      puppet
      puppetlabs_spec_helper
      rspec
      rspec-puppet
    rspec-support (3.13.1)
    rsync (1.0.9)
    rubocop (1.50.2)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.2.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.28.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.31.3)
      parser (>= 3.3.1.0)
    rubocop-capybara (2.21.0)
      rubocop (~> 1.41)
    rubocop-rake (0.6.0)
      rubocop (~> 1.0)
    rubocop-rspec (2.20.0)
      rubocop (~> 1.33)
      rubocop-capybara (~> 2.17)
    ruby-progressbar (1.13.0)
    ruby_parser (3.21.0)
      racc (~> 1.5)
      sexp_processor (~> 4.16)
    rubyntlm (0.6.5)
      base64
    sawyer (0.9.2)
      addressable (>= 2.3.5)
      faraday (>= 0.17.3, < 3)
    scanf (1.0.0)
    semantic_puppet (1.1.0)
    serverspec (2.42.3)
      multi_json
      rspec (~> 3.0)
      rspec-its
      specinfra (~> 2.72)
    sexp_processor (4.17.1)
    sfl (2.3)
    shellany (0.0.1)
    simplecov (0.16.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-console (0.9.1)
      ansi
      simplecov
      terminal-table
    simplecov-html (0.10.2)
    singleton (0.2.0)
    spdx-licenses (1.3.0)
    specinfra (2.89.0)
      net-scp
      net-ssh (>= 2.7)
      net-telnet
      sfl
    stringify-hash (0.0.2)
    strscan (3.1.0)
    sync (0.5.0)
    term-ansicolor (1.10.2)
      mize
      tins (~> 1.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    thor (1.2.2)
    tins (1.33.0)
      bigdecimal
      sync
    traces (0.11.1)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)
    uri (0.13.0)
    voxpupuli-acceptance (3.2.0)
      bcrypt_pbkdf (~> 1.1)
      beaker (~> 6.0)
      beaker-docker (~> 2.1)
      beaker-hiera (~> 1.0)
      beaker-hostgenerator (~> 2.2)
      beaker-rspec (~> 8.0, >= 8.0.1)
      beaker-vagrant (~> 1.2)
      beaker_puppet_helpers (~> 1.3)
      puppet-modulebuilder (~> 1.0)
      rake (~> 13.0, >= 13.0.6)
      rspec-github (~> 2.0)
      serverspec (~> 2.42, >= 2.42.2)
      winrm (~> 2.3, >= 2.3.6)
    voxpupuli-puppet-lint-plugins (5.0.0)
      puppet-lint (~> 4.0)
      puppet-lint-absolute_classname-check (~> 4.0)
      puppet-lint-anchor-check (~> 2.0)
      puppet-lint-file_ensure-check (~> 2.0)
      puppet-lint-leading_zero-check (~> 2.0)
      puppet-lint-lookup_in_parameter-check (~> 2.0)
      puppet-lint-manifest_whitespace-check (~> 0.3, < 1.0.0)
      puppet-lint-optional_default-check (~> 2.0)
      puppet-lint-param-docs (~> 2.0)
      puppet-lint-param-types (~> 2.0)
      puppet-lint-params_empty_string-check (~> 2.0)
      puppet-lint-resource_reference_syntax (~> 2.0)
      puppet-lint-strict_indent-check (~> 3.0)
      puppet-lint-topscope-variable-check (~> 2.0)
      puppet-lint-trailing_comma-check (~> 2.0)
      puppet-lint-unquoted_string-check (~> 3.0)
      puppet-lint-variable_contains_upcase (~> 2.0)
      puppet-lint-version_comparison-check (~> 2.0)
    voxpupuli-release (3.0.1)
      faraday-retry (~> 2.1)
      github_changelog_generator (~> 1.16, >= 1.16.4)
      puppet-blacksmith (~> 7.0)
      puppet-strings (~> 4)
      rake (~> 13.0, >= 13.0.6)
    voxpupuli-test (8.0.0)
      facterdb (~> 2.1)
      metadata-json-lint (~> 4.0)
      parallel_tests (~> 4.2)
      puppet-strings (~> 4.0)
      puppetlabs_spec_helper (~> 7.3)
      rake (~> 13.0, >= 13.0.6)
      rspec-puppet (~> 4.0)
      rspec-puppet-facts (~> 4.0)
      rspec-puppet-utils (~> 3.4)
      rubocop (~> 1.50.0)
      rubocop-rake (~> 0.6.0)
      rubocop-rspec (~> 2.20.0)
      voxpupuli-puppet-lint-plugins (~> 5.0)
    winrm (2.3.6)
      builder (>= 2.1.2)
      erubi (~> 1.8)
      gssapi (~> 1.2)
      gyoku (~> 1.0)
      httpclient (~> 2.2, >= 2.2.0.2)
      logging (>= 1.6.1, < 3.0)
      nori (~> 2.0)
      rubyntlm (~> 0.6.0, >= 0.6.3)
    yard (0.9.36)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  coveralls
  facter
  guard-rake
  overcommit (>= 0.39.1)
  puppet (~> 7.24)
  puppet_metadata (~> 4.0)
  rake
  simplecov-console
  voxpupuli-acceptance (~> 3.0)
  voxpupuli-release (~> 3.0)
  voxpupuli-test (~> 8.0)

BUNDLED WITH
   2.4.20
```

**Comment by indirect** [comment]
Please try upgrading RubyGems and Bundler to the latest to see if your problem has been fixed already. There's a reason that question is in the template you had to fill out.

**Comment by bigon** [comment]
Well when a ruby is installed using a package manager, updating all gems would break the consistency of the system.

Anyway, this seems caused by a patch applied in debian

**Comment by deivid-rodriguez** [comment]
> Well when a ruby is installed using a package manager, updating all gems would break the consistency of the system.

That's indeed the usual recommendation of OS packagers. In that case though, since the our requirements of trying the latest versions before reporting issues cannot be met, it's best if you reach out to the maintainers of the OS package first. I assume they will have a proper environment to upgrade the packaged version safely and verify if the problem is fixed upstream, so they just need to package a fixed version, or if the problem is still present upstream, so they can report a proper issue to us.

**Comment by texpert** [comment]
@deivid-rodriguez, thanks for hard work on awesome apps and gems!

I have the same issue on macOS. 

Trying to add the `x86_64-linux-gnu` platform:

```
$ gem --version
3.6.3

$ bundle --version
Bundler version 2.6.3

$ bundle lock --add-platform x86_64-linux-gnu
Writing lockfile to /Users/Shared/dev/engie/solarhub/Gemfile.lock
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
```

Getting as a result in the `Gemfile.lock`:

```
    nokogiri (1.18.2-x86_64-linux)
      racc (~> 1.4)

...

PLATFORMS
  ...
  x86_64-linux
```
