### ISSUE TITLE
Unable to install psych using `bundle install` on JRuby-9.4, but possible with `gem install`

### ISSUE THREAD

**Issue by Burgestrand** [rubygems/rubygems#7804]
Hi! I don't know if this is the right home for this issue. It involves psych, jruby, and bundler/rubygems.

I've tried to figure out what happens, but I've hit a wall.

## How to reproduce
* Use jruby/jruby-head on github actions on ubuntu-latest.
* Have Gemfile with `gem "psych"` in it.
* Run `bundle install`

<details>
<summary>Expand for example output</summary>
<pre>
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching jar-dependencies 0.4.1
Installing jar-dependencies 0.4.1
Fetching psych 5.1.2 (java)
Installing psych 5.1.2 (java)
  jar dependencies for psych-5.1.2-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Installing gem 'ruby-maven-libs' . . .

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

Error: ] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:2)  @ line 1, column 2
 @ 
Error:  The build could not read 1 project -> [Help 1]
Error:    
Error:    The project  (/home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/gemspec_pom.rb) has 1 error
Error:      Non-parseable POM /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:2)  @ line 1, column 2 -> [Help 2]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Error:  [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::ENOENT: No such file or directory - /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/gems/shared/gems/psych-5.1.2-java/deps.lst
  org/jruby/RubyIO.java:1278:in `sysopen'
          org/jruby/RubyIO.java:4264:in `read'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/installer.rb:69:in `load_from_maven'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/installer.rb:235:in `install_dependencies'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/installer.rb:224:in `do_install'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/installer.rb:170:in `vendor_jars'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/jars/post_install_hook.rb:28:in `block in <main>'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/rubygems/installer.rb:383:in `block in run_post_install_hooks'
          org/jruby/RubyArray.java:1981:in `each'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/rubygems/installer.rb:382:in `run_post_install_hooks'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/rubygems_gem_installer.rb:46:in `install'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/source/rubygems.rb:205:in `install'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/installer/gem_installer.rb:54:in `install'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:132:in `do_install'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/worker.rb:62:in `apply_func'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/worker.rb:57:in `block in process_queue'
          org/jruby/RubyKernel.java:1722:in `loop'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/worker.rb:54:in `process_queue'
          /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/stdlib/bundler/worker.rb:90:in `block in create_threads'

```

## Environment

```
Bundler       2.5.14
  Platforms   ruby, universal-java-11
Ruby          3.1.4p0 (2024-04-29 revision 597ff08ac1e0d7f05f8f6cc836648725756dd7db) [universal-java-11]
  Full Path   /home/runner/.rubies/jruby-9.4.7.0/bin/jruby
  Config Dir  /home/runner/.rubies/jruby-9.4.7.0/etc
RubyGems      3.5.14
  Gem Home    /home/runner/.rubies/jruby-9.4.7.0/lib/ruby/gems/shared
  Gem Path    /home/runner/.local/share/gem/jruby/3.1.0:/home/runner/.rubies/jruby-9.4.7.0/lib/ruby/gems/shared
  User Home   /home/runner
  User Path   /home/runner/.local/share/gem/jruby/3.1.0
  Bin Dir     /home/runner/.rubies/jruby-9.4.7.0/bin
OpenSSL       
  Compiled    JRuby-OpenSSL 0.14.5
  Loaded      JRuby-OpenSSL 0.14.5
  Cert File   /usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
  Cert Dir    /etc/ssl/certs
Tools         
  Git         2.45.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-06-21
Git SHA           72920bc230
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org/"

gem "psych"
```

### Gemfile.lock

```
<No /home/runner/work/psych-jruby-bundler/psych-jruby-bundler/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=No+such+file+or+directory+-+%2Fhome%2Frunner%2F.rubies%2Fjruby-9.4.7.0%2Flib%2Fruby%2Fgems%2Fshared%2Fgems%2Fpsych-5.1.2-java%2Fdeps.lst&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
</pre>
</details>

Workaround by `gem install psych` before `bundle install` and it will succeed.

## Minimal repro
https://github.com/Burgestrand/psych-jruby-bundler

## Other notes
* I believe this is different from #7073 and #7064.
* I've been unable to reproduce this outside of GitHub Actions. I've tried locally on my MacOS arm64 machine, and in docker images from https://github.com/catthehacker/docker_images
* Failure and success are consistent.
* It succeeds on JRuby 9.3, fails on 9.4 and head.

**Comment by deivid-rodriguez** [comment]
Hi!

It seems the same as https://github.com/jruby/jruby/issues/7059? I think a fix is in the works! Let me close as a duplicate in favor of https://github.com/jruby/jruby/issues/7059 but do reopen if it's not the same.

**Comment by Burgestrand** [comment]
@deivid-rodriguez thank you for finding that! I hope this is indeed a duplicate. I believe I might have seen that issue two weeks ago when debugging this, but disregarded it because for me everything _works_ on JRuby-9.3, but the more recent comments do indicate this might be the same issue.

Fingers crossed!
