### ISSUE TITLE
Bad file descriptor @ rb_file_flock (…) unicode-display_width-2.5.0.gemspec

### ISSUE THREAD

**Issue by TomDobraORI** [rubygems/rubygems#7854]
Hi.

I'm attempting to install and configure Jekyll. All `bundle` commands fail; see error template below. The error message refers to `unicode-display_width-2.5.0.gemspec` but it's possible that's a red herring(?)

FYI the install directory is on an NFS share; could this be related to https://github.com/rubygems/rubygems/issues/5257 …?

Thank you

```
ruby -v
# ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

gem -v
# 3.3.5

bundle -v
Bundler version 2.3.5
```

Error template:

```
Errno::EBADF: Bad file descriptor @ rb_file_flock - /homes/REDACTED/gems/specifications/unicode-display_width-2.5.0.gemspec
  /usr/lib/ruby/vendor_ruby/rubygems.rb:786:in `flock'
  /usr/lib/ruby/vendor_ruby/rubygems.rb:786:in `block in open_with_flock'
  /usr/lib/ruby/vendor_ruby/rubygems.rb:783:in `open'
  /usr/lib/ruby/vendor_ruby/rubygems.rb:783:in `open_with_flock'
  /usr/lib/ruby/vendor_ruby/rubygems/stub_specification.rb:113:in `data'
  /usr/lib/ruby/vendor_ruby/rubygems/stub_specification.rb:200:in `valid?'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:777:in `select'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:777:in `gemspec_stubs_in'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:792:in `block in map_stubs'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:789:in `each'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:789:in `flat_map'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:789:in `map_stubs'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:782:in `installed_stubs'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:847:in `stubs_for_pattern'
  /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:810:in `stubs'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/rubygems_integration.rb:550:in `all_specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:400:in `block in installed_specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/index.rb:9:in `build'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:399:in `installed_specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:413:in `cached_specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:132:in `specs'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:167:in `index_for'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:175:in `results_for'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:112:in `search_for'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:255:in `block in verify_gemfile_dependencies_are_found!'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:252:in `each'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:252:in `verify_gemfile_dependencies_are_found!'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:48:in `start'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/resolver.rb:23:in `resolve'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/definition.rb:269:in `resolve'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/definition.rb:180:in `resolve_remotely!'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer.rb:280:in `resolve_if_needed'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer.rb:82:in `block in run'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer.rb:71:in `run'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/installer.rb:23:in `install'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/cli/update.rb:78:in `run'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/cli.rb:303:in `block in update'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/settings.rb:131:in `temporary'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/cli.rb:302:in `update'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/share/rubygems-integration/all/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
  /usr/bin/bundle:25:in `load'
  /usr/bin/bundle:25:in `<main>'
```

## Environment

```
Bundler       2.3.5
  Platforms   ruby, x86_64-linux
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby3.0
  Config Dir  /etc
RubyGems      3.3.5
  Gem Home    /homes/REDACTED/gems
  Gem Path    /homes/REDACTED/.local/share/gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0:/usr/share/rubygems-integration/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0:/homes/REDACTED/gems
  User Home   /homes/REDACTED
  User Path   /homes/REDACTED/.local/share/gem/ruby/3.0.0
  Bin Dir     /homes/REDACTED/gems/bin
OpenSSL
  Compiled    OpenSSL 3.0.2 15 Mar 2022
  Loaded      OpenSSL 3.0.2 15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.34.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      /usr/bin/ruby3.0
bundle #!     /usr/bin/ruby

```

## Bundler Build Metadata

```
Built At          2024-07-11
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
```

### Gemfile.lock

```
<No /homes/REDACTED/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by indirect** [comment]
You are using a version of Bundler that is 2.5 years old, and you ignored the section of the template that asks if you tried upgrading RubyGems and Bundler. What happens if you upgrade RubyGems and Bundler?

**Comment by deivid-rodriguez** [comment]
Yeah, @indirect is right, and you're also correct about the culprit here. The fix to https://github.com/rubygems/rubygems/issues/5257 was released as RubyGems 3.3.6 and you're on RubyGems 3.3.5, so upgrading RubyGems should fix things for you.

**Comment by TomDobraORI** [comment]
Thanks, both.

@indirect Those are the current versions in the repos for Ubuntu 20.04, unfortunately…

**Comment by deivid-rodriguez** [comment]
I see. In that case, please request an upgrade to the ubuntu package, and fell free to link to this issue 👍.
