### ISSUE TITLE
bundle install is not working

### ISSUE THREAD

**Issue by KarthikCAS109** [rubygems/rubygems#7884]
saikrishna.karthik@CALTM00650 ca-fi-invest-trade-api % rvm fix-permissions

Fixing user for saikrishna.karthik - this might take a few long minutes...
saikrishna.karthik password required for 'chown -R saikrishna.karthik /Users/saikrishna.karthik/.rvm': 
Finished fixing.
saikrishna.karthik@CALTM00650 ca-fi-invest-trade-api % bundle install
Ignoring psych-5.1.1 because its extensions are not built. Try: gem pristine psych --version 5.1.1
Ignoring stringio-3.0.8 because its extensions are not built. Try: gem pristine stringio --version 3.0.8
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
LoadError: linked to incompatible /Users/saikrishna.karthik/.asdf/installs/ruby/3.1.2/lib/libruby.3.1.dylib - /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/psych-5.1.1/lib/psych.bundle
  <internal:/Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  <internal:/Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/psych-5.1.1/lib/psych.rb:13:in `<top (required)>'
  <internal:/Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  <internal:/Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
  /Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems.rb:608:in `load_yaml'
  /Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/config_file.rb:346:in `load_file'
  /Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/config_file.rb:189:in `initialize'
  /Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems.rb:329:in `new'
  /Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems.rb:329:in `configuration'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/fetcher.rb:244:in `connection'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/fetcher.rb:90:in `initialize'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:257:in `new'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:257:in `block in fetchers'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:255:in `map'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:255:in `fetchers'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:400:in `block in remote_specs'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/index.rb:9:in `build'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:399:in `remote_specs'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/source/rubygems.rb:132:in `specs'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/spec_set.rb:205:in `map!'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/spec_set.rb:205:in `specs_for_dependency'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/spec_set.rb:34:in `block in for'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/spec_set.rb:22:in `loop'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/spec_set.rb:22:in `for'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/spec_set.rb:85:in `materialize'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/definition.rb:506:in `materialize'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/definition.rb:197:in `specs'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/installer.rb:83:in `block in run'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/process_lock.rb:9:in `open'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/process_lock.rb:9:in `lock'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/installer.rb:71:in `run'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/installer.rb:23:in `install'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/cli/install.rb:62:in `run'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/cli.rb:261:in `block in install'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/settings.rb:131:in `temporary'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/cli.rb:260:in `install'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/cli.rb:34:in `dispatch'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/cli.rb:28:in `start'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/exe/bundle:37:in `block in <top (required)>'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/gems/bundler-2.4.14/exe/bundle:29:in `<top (required)>'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/bin/bundle:25:in `load'
  /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.14
  Platforms   ruby, arm64-darwin-23
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [arm64-darwin-23]
  Full Path   /Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/bin/ruby
  Config Dir  /Users/saikrishna.karthik/.asdf/installs/ruby/3.2.2/etc
RubyGems      3.4.10
  Gem Home    /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2
  Gem Path    /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2:/Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2@global
  User Home   /Users/saikrishna.karthik
  User Path   /Users/saikrishna.karthik/.gem/ruby/3.2.0
  Bin Dir     /Users/saikrishna.karthik/.rvm/gems/ruby-2.7.2/bin
OpenSSL       
  Compiled    OpenSSL 3.3.1 4 Jun 2024
  Loaded      OpenSSL 3.3.1 4 Jun 2024
  Cert File   /opt/homebrew/etc/openssl@3/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@3/certs
Tools         
  Git         2.39.3 (Apple Git-146)
  RVM         1.29.12 (latest)
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-06-12
Git SHA           69f47cf53a
Released Version  true
```

## Bundler settings

```
build.nio4r
  Set for the current user (/Users/saikrishna.karthik/.bundle/config): "--with-cflags=-std=c99"
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.0.5'
# Use Puma as the app server
gem 'puma', '~> 5.6'
# Use postgresql as the database for Active Record
gem 'pg'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# This will help to decorate json APIs
gem 'draper'
# JWT parsing
gem 'jwt', '~> 1.5', '>= 1.5.4'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.10', '>= 1.10.3', require: false
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
# Used for pagination
gem 'pagy'
# Rails param validations
gem 'rails_param', '~> 1.3'
# Used for filters
gem 'toschas-filterable'
# Used as a redis store and cache
# gem 'redis', '~> 4.6'
# Adds a Redis::Namespace class which can be used to namespace calls to Redis.
# gem 'redis-namespace'
gem 'newrelic_rpm'

# http and RESR client
gem 'rest-client', '~> 2.0.0'
gem "faraday", "~> 1.1"

# Store config in the environment
gem 'dotenv'
# Lambda Integration with rails via rack
gem 'lamby'
# AWS lambda Runtime Interface Client to provide lambda entrypoint
gem 'aws_lambda_ric'

gem 'aasm'
gem 'after_commit_everywhere', '~> 1.0'

# To calculate time difference in custom formats
gem 'time_diff', '~> 0.3.0'

# Used for RBAC
gem 'pundit'
# To convery currency to specific formats
gem 'money'

gem 'shoryuken'
gem 'aws-sdk-sqs'

# added while upgrading to ruby > 3.0 
# `visit_Psych_Nodes_Alias': Alias parsing was not enabled. To enable it, pass `aliases: true` to `Psych::load` or `Psych::safe_load`. (Psych::AliasesNotEnabled)
gem 'psych', '~>3.0'
# Used for soft delete
gem 'acts_as_paranoid'
# gem 'wkhtmltopdf-binary'
gem 'pdfkit'
gem 'wkhtmltopdf-binary-edge-alpine'
gem 'aws-sdk-s3'

group :development, :test do
  # Call 'byebug' or 'binding.pry' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'                       # Used for debugging, differentiate class, variables, keywords, line numbers, etc,. with different colors
  gem 'brakeman'                  # Used to analyse for security vulerabilities 
  # gem 'bullet'                  # Used for increasing your application's performance by reducing the number of queries
  gem 'figaro'                    # Used for maintaining ENV vars and creds for dev and test environments
  gem 'awesome_print'             # Used for pretty printing Ruby objects in full color exposing their internal structure with proper indentation.
end

group :test do
  gem 'rspec-rails', '~> 6.0.3'     # Used for writing test cases
  gem 'faker'                     # Used to generate fake data for testing
  gem 'simplecov'                   # to track code coverage
  # gem 'json_expressions'            # Used to express the structure of JSON with very readable ruby code
  # gem 'mocha'                     # to mock objects, mainly used while writing unit test
  # gem 'webmock'                   # to mock web request i.e other eternal services
  gem 'database_cleaner-active_record'  # Used to clean the database
  gem 'shoulda-matchers', '~> 5.0'
  gem 'rails-controller-testing'
  gem 'factory_bot_rails'
  gem 'rspec-sonarqube-formatter', '~> 1.5', require: false
end

group :development do
  gem 'listen', '~> 3.1', '>= 3.1.5'
  gem 'spring', '~> 3.0.0'    # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  #gem 'overcommit'
  gem 'web-console'
  gem 'rubocop', '~> 1.25', '>= 1.25.1' # Ruby code formatter
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    aasm (5.5.0)
      concurrent-ruby (~> 1.0)
    actioncable (7.0.5.1)
      actionpack (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.5.1)
      actionpack (= 7.0.5.1)
      activejob (= 7.0.5.1)
      activerecord (= 7.0.5.1)
      activestorage (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.5.1)
      actionpack (= 7.0.5.1)
      actionview (= 7.0.5.1)
      activejob (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.5.1)
      actionview (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      rack (~> 2.0, >= 2.2.4)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.5.1)
      actionpack (= 7.0.5.1)
      activerecord (= 7.0.5.1)
      activestorage (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.5.1)
      activesupport (= 7.0.5.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.5.1)
      activesupport (= 7.0.5.1)
      globalid (>= 0.3.6)
    activemodel (7.0.5.1)
      activesupport (= 7.0.5.1)
    activemodel-serializers-xml (1.0.2)
      activemodel (> 5.x)
      activesupport (> 5.x)
      builder (~> 3.1)
    activerecord (7.0.5.1)
      activemodel (= 7.0.5.1)
      activesupport (= 7.0.5.1)
    activestorage (7.0.5.1)
      actionpack (= 7.0.5.1)
      activejob (= 7.0.5.1)
      activerecord (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.5.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    acts_as_paranoid (0.8.1)
      activerecord (>= 5.2, < 7.1)
      activesupport (>= 5.2, < 7.1)
    after_commit_everywhere (1.3.1)
      activerecord (>= 4.2)
      activesupport
    ast (2.4.2)
    awesome_print (1.9.2)
    aws-eventstream (1.2.0)
    aws-partitions (1.781.0)
    aws-sdk-core (3.175.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.5)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.67.0)
      aws-sdk-core (~> 3, >= 3.174.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.126.0)
      aws-sdk-core (~> 3, >= 3.174.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sdk-sqs (1.58.0)
      aws-sdk-core (~> 3, >= 3.174.0)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.5.2)
      aws-eventstream (~> 1, >= 1.0.2)
    aws_lambda_ric (2.0.0)
    bindex (0.8.1)
    bootsnap (1.16.0)
      msgpack (~> 1.2)
    brakeman (6.0.0)
    builder (3.2.4)
    byebug (11.1.3)
    coderay (1.1.3)
    concurrent-ruby (1.2.2)
    crass (1.0.6)
    database_cleaner-active_record (2.1.0)
      activerecord (>= 5.a)
      database_cleaner-core (~> 2.0.0)
    database_cleaner-core (2.0.1)
    date (3.3.3)
    diff-lcs (1.5.0)
    docile (1.4.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.8.1)
    draper (4.0.2)
      actionpack (>= 5.0)
      activemodel (>= 5.0)
      activemodel-serializers-xml (>= 1.0)
      activesupport (>= 5.0)
      request_store (>= 1.0)
      ruby2_keywords
    erubi (1.12.0)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    faker (3.2.0)
      i18n (>= 1.8.11, < 2)
    faraday (1.10.3)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    ffi (1.15.5)
    figaro (1.2.0)
      thor (>= 0.14.0, < 2)
    globalid (1.1.0)
      activesupport (>= 5.0)
    htmlentities (4.3.4)
    http-cookie (1.0.5)
      domain_name (~> 0.5)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jmespath (1.6.2)
    json (2.6.3)
    jwt (1.5.6)
    lambda-console-ruby (1.0.0)
    lamby (5.0.0)
      lambda-console-ruby
      rack
    language_server-protocol (3.17.0.3)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.21.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    method_source (1.0.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2023.0218.1)
    mini_mime (1.1.2)
    minitest (5.18.1)
    money (6.16.0)
      i18n (>= 0.6.4, <= 2)
    msgpack (1.7.1)
    multipart-post (2.3.0)
    net-imap (0.3.6)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-smtp (0.3.3)
      net-protocol
    netrc (0.11.0)
    newrelic_rpm (9.3.0)
    nio4r (2.5.9)
    nokogiri (1.15.2-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.15.2-x86_64-darwin)
      racc (~> 1.4)
    pagy (6.0.4)
    parallel (1.23.0)
    parser (3.2.2.3)
      ast (~> 2.4.1)
      racc
    pdfkit (0.8.7.3)
    pg (1.5.3)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    psych (3.3.4)
    puma (5.6.6)
      nio4r (~> 2.0)
    pundit (2.3.0)
      activesupport (>= 3.0.0)
    racc (1.7.1)
    rack (2.2.7)
    rack-cors (2.0.1)
      rack (>= 2.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (7.0.5.1)
      actioncable (= 7.0.5.1)
      actionmailbox (= 7.0.5.1)
      actionmailer (= 7.0.5.1)
      actionpack (= 7.0.5.1)
      actiontext (= 7.0.5.1)
      actionview (= 7.0.5.1)
      activejob (= 7.0.5.1)
      activemodel (= 7.0.5.1)
      activerecord (= 7.0.5.1)
      activestorage (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      bundler (>= 1.15.0)
      railties (= 7.0.5.1)
    rails-controller-testing (1.0.5)
      actionpack (>= 5.0.1.rc1)
      actionview (>= 5.0.1.rc1)
      activesupport (>= 5.0.1.rc1)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    rails_param (1.3.0)
      actionpack (>= 3.2.0)
      activesupport (>= 3.2.0)
    railties (7.0.5.1)
      actionpack (= 7.0.5.1)
      activesupport (= 7.0.5.1)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rainbow (3.1.1)
    rake (13.0.6)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (2.8.1)
    request_store (1.5.1)
      rack (>= 1.4)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rexml (3.2.5)
    rspec (3.12.0)
      rspec-core (~> 3.12.0)
      rspec-expectations (~> 3.12.0)
      rspec-mocks (~> 3.12.0)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.5)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-rails (6.0.3)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (~> 3.12)
      rspec-expectations (~> 3.12)
      rspec-mocks (~> 3.12)
      rspec-support (~> 3.12)
    rspec-sonarqube-formatter (1.5.0)
      htmlentities (~> 4.3.3)
      rspec (~> 3.0)
    rspec-support (3.12.1)
    rubocop (1.54.2)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.2.2.3)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.28.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.29.0)
      parser (>= 3.2.1.0)
    ruby-progressbar (1.13.0)
    ruby2_keywords (0.0.5)
    shoryuken (6.0.0)
      aws-sdk-core (>= 2)
      concurrent-ruby
      thor
    shoulda-matchers (5.3.0)
      activesupport (>= 5.2.0)
    simplecov (0.22.0)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.4)
    spring (3.0.0)
    thor (1.2.2)
    time_diff (0.3.0)
      activesupport
      i18n
    timeout (0.4.0)
    toschas-filterable (1.0.2)
      activerecord (>= 3.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8.2)
    unicode-display_width (2.4.2)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    wkhtmltopdf-binary-edge-alpine (0.12.6.3)
    zeitwerk (2.6.8)

PLATFORMS
  arm64-darwin-21
  arm64-darwin-23
  x86_64-darwin-21

DEPENDENCIES
  aasm
  acts_as_paranoid
  after_commit_everywhere (~> 1.0)
  awesome_print
  aws-sdk-s3
  aws-sdk-sqs
  aws_lambda_ric
  bootsnap (~> 1.10, >= 1.10.3)
  brakeman
  byebug
  database_cleaner-active_record
  dotenv
  draper
  factory_bot_rails
  faker
  faraday (~> 1.1)
  figaro
  jbuilder (~> 2.5)
  jwt (~> 1.5, >= 1.5.4)
  lamby
  listen (~> 3.1, >= 3.1.5)
  money
  newrelic_rpm
  pagy
  pdfkit
  pg
  pry
  psych (~> 3.0)
  puma (~> 5.6)
  pundit
  rack-cors
  rails (~> 7.0.5)
  rails-controller-testing
  rails_param (~> 1.3)
  rest-client (~> 2.0.0)
  rspec-rails (~> 6.0.3)
  rspec-sonarqube-formatter (~> 1.5)
  rubocop (~> 1.25, >= 1.25.1)
  shoryuken
  shoulda-matchers (~> 5.0)
  simplecov
  spring (~> 3.0.0)
  time_diff (~> 0.3.0)
  toschas-filterable
  tzinfo-data
  web-console
  wkhtmltopdf-binary-edge-alpine

RUBY VERSION
   ruby 3.2.2p53

BUNDLED WITH
   2.4.14
```

--- TEMPLATE END ----------------------------------------------------------------
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=linked+to+incompatible+%2FUsers%2Fsaikrishna.karthik%2F.asdf%2Finstalls%2Fruby%2F3.1.2%2Flib%2Flibruby.3.1.dylib+-+%2FUsers%2Fsaikrishna.karthik%2F.rvm%2Fgems%2Fruby-2.7.2%2Fgems%2Fpsych-5.1.1%2Flib%2Fpsych.bundle&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

**Comment by deivid-rodriguez** [comment]
Hi! It sounds like you're environment is getting two different rubies mixed up, one managed by RVM, and the other one managed by asdf. Please choose one ruby version manager and uninstall the other, and try again. Good luck!
