### ISSUE TITLE
Permission denied @ rb_file_s_symlink - (../lib/install/config/shakapacker.yml)

### ISSUE THREAD

**Issue by jillii** [rubygems/rubygems#7910]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EACCES: Permission denied @ rb_file_s_symlink - (../lib/install/config/shakapacker.yml, C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shakapacker-8.0.0/config/shakapacker.yml)
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:446:in `symlink'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:446:in `block (2 levels) in extract_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:412:in `block in extract_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:524:in `block in open_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:521:in `wrap'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:521:in `open_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:411:in `extract_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:391:in `block (2 levels) in extract_files'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:388:in `block in extract_files'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `with_read_io'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:385:in `extract_files'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:862:in `extract_files'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/source/rubygems.rb:200:in `install'  
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:54:in `process_queue'      
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_file_s_symlink - (../lib/install/config/shakapacker.yml, C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shakapacker-8.0.0/config/shakapacker.yml)
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:446:in `symlink'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:446:in `block (2 levels) in extract_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:412:in `block in extract_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:524:in `block in open_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:521:in `wrap'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:521:in `open_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:411:in `extract_tar_gz'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:391:in `block (2 levels) in extract_files'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:388:in `block in extract_files'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `with_read_io'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/package.rb:385:in `extract_files'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:862:in `extract_files'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/source/rubygems.rb:200:in `install'  
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:54:in `process_queue'      
  C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.5
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x64-mingw-ucrt]  
  Full Path   C:/Ruby31-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.3.7
  Gem Home    C:/Ruby31-x64/lib/ruby/gems/3.1.0
  Gem Path    C:/Users/jill/.local/share/gem/ruby/3.1.0;C:/Ruby31-x64/lib/ruby/gems/3.1.0
  User Home   C:/Users/jill
  User Path   C:/Users/jill/.local/share/gem/ruby/3.1.0
  Bin Dir     C:/Ruby31-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   C:/Ruby31-x64/ssl/cert.pem
  Cert Dir    C:/Ruby31-x64/ssl/certs
Tools
  Git         2.36.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-01-21
Git SHA           d8ff3b6e4a
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# User authentication
gem "devise", "4.9.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Test emails on local
gem "letter_opener", group: :development

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

# Use AWS for image storage (on prod)
gem "aws-sdk-s3", require: false

# Youtube search
gem 'httparty'

# Pagination
gem 'kaminari'

# Use Sass to process CSS
gem "sassc-rails"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem   
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

gem "react_on_rails", "= 14.0"

gem "shakapacker", "= 8.0"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.8.4)
      actionpack (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.8.4)
      actionpack (= 7.0.8.4)
      activejob (= 7.0.8.4)
      activerecord (= 7.0.8.4)
      activestorage (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.8.4)
      actionpack (= 7.0.8.4)
      actionview (= 7.0.8.4)
      activejob (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.8.4)
      actionview (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      rack (~> 2.0, >= 2.2.4)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.8.4)
      actionpack (= 7.0.8.4)
      activerecord (= 7.0.8.4)
      activestorage (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.8.4)
      activesupport (= 7.0.8.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.8.4)
      activesupport (= 7.0.8.4)
      globalid (>= 0.3.6)
    activemodel (7.0.8.4)
      activesupport (= 7.0.8.4)
    activerecord (7.0.8.4)
      activemodel (= 7.0.8.4)
      activesupport (= 7.0.8.4)
    activestorage (7.0.8.4)
      actionpack (= 7.0.8.4)
      activejob (= 7.0.8.4)
      activerecord (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.8.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    aws-eventstream (1.3.0)
    aws-partitions (1.950.0)
    aws-sdk-core (3.200.0)
      aws-eventstream (~> 1, >= 1.3.0)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.8)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.87.0)
      aws-sdk-core (~> 3, >= 3.199.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.155.0)
      aws-sdk-core (~> 3, >= 3.199.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.8)
    aws-sigv4 (1.8.0)
      aws-eventstream (~> 1, >= 1.0.2)
    bcrypt (3.1.20)
    bigdecimal (3.1.8)
    bindex (0.8.1)
    bootsnap (1.18.3)
      msgpack (~> 1.2)
    builder (3.3.0)
    capybara (3.40.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.11)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (5.0.0)
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    crass (1.0.6)
    csv (3.3.0)
    date (3.3.4)
    debug (1.9.2)
      irb (~> 1.10)
      reline (>= 0.3.8)
    devise (4.9.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    erubi (1.13.0)
    execjs (2.9.1)
    ffi (1.17.0-x64-mingw-ucrt)
    globalid (1.2.1)
      activesupport (>= 6.1)
    httparty (0.22.0)
      csv
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    image_processing (1.12.2)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    io-console (0.7.2)
    irb (1.13.2)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    jbuilder (2.12.0)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jmespath (1.6.2)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    launchy (3.0.1)
      addressable (~> 2.8)
      childprocess (~> 5.0)
    letter_opener (1.10.0)
      launchy (>= 2.2, < 4)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.4)
    matrix (0.4.2)
    method_source (1.1.0)
    mini_magick (4.13.1)
    mini_mime (1.1.5)
    minitest (5.24.1)
    msgpack (1.7.2)
    multi_xml (0.7.1)
      bigdecimal (~> 3.1)
    net-imap (0.4.14)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.5.0)
      net-protocol
    nio4r (2.7.3)
    nokogiri (1.16.6-x64-mingw-ucrt)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    package_json (0.1.0)
    psych (5.1.2)
      stringio
    public_suffix (6.0.0)
    puma (5.6.8)
      nio4r (~> 2.0)
    racc (1.8.0)
    rack (2.2.9)
    rack-proxy (0.7.7)
      rack
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (7.0.8.4)
      actioncable (= 7.0.8.4)
      actionmailbox (= 7.0.8.4)
      actionmailer (= 7.0.8.4)
      actionpack (= 7.0.8.4)
      actiontext (= 7.0.8.4)
      actionview (= 7.0.8.4)
      activejob (= 7.0.8.4)
      activemodel (= 7.0.8.4)
      activerecord (= 7.0.8.4)
      activestorage (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      bundler (>= 1.15.0)
      railties (= 7.0.8.4)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.0.8.4)
      actionpack (= 7.0.8.4)
      activesupport (= 7.0.8.4)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rainbow (3.1.1)
    rake (13.2.1)
    rdoc (6.7.0)
      psych (>= 4.0.0)
    react_on_rails (14.0.0)
      addressable
      connection_pool
      execjs (~> 2.5)
      rails (>= 5.2)
      rainbow (~> 3.0)
    regexp_parser (2.9.2)
    reline (0.5.9)
      io-console (~> 0.5)
    responders (3.1.1)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.3.1)
      strscan
    ruby-vips (2.2.1)
      ffi (~> 1.12)
    rubyzip (2.3.2)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.10.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    semantic_range (3.0.0)
    shakapacker (8.0.1)
      activesupport (>= 5.2)
      package_json
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    spring (4.2.1)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.5.1)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      sprockets (>= 3.0.0)
    sqlite3 (1.7.3-x64-mingw-ucrt)
    stimulus-rails (1.3.3)
      railties (>= 6.0.0)
    stringio (3.1.1)
    strscan (3.1.0)
    thor (1.3.1)
    tilt (2.4.0)
    timeout (0.4.1)
    turbo-rails (2.0.5)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2024.1)
      tzinfo (>= 1.0.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.3.1)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0, < 4.11)
    websocket (1.2.10)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.16)

PLATFORMS
  x64-mingw-ucrt

DEPENDENCIES
  aws-sdk-s3
  bootsnap
  capybara
  debug
  devise (= 4.9.4)
  httparty
  image_processing (~> 1.2)
  jbuilder
  kaminari
  letter_opener
  puma (~> 5.0)
  rails (~> 7.0.4)
  react_on_rails (= 14.0)
  sassc-rails
  selenium-webdriver
  shakapacker
  spring
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.4.5
```

**Comment by deivid-rodriguez** [comment]
Hi. Please upgrade Ruby, RubyGems, and Bundler, and then reopen the issue if still running into issues. It's possible that this is already fixed in more recent versions. Thanks!
