### ISSUE TITLE
Bundler does not support local git repositories with relative paths

### ISSUE THREAD

**Issue by n-rodriguez** [rubygems/rubygems#7925]
Hi there! 

We have an issue with Appraisal gem not passing CI since Bundler 2.4.0 :/

@tisba has spent some time to do some debug : https://github.com/thoughtbot/appraisal/issues/218#issuecomment-1941588561

For now we don't know which direction to choose.

From @tisba 

> IMO, btw: It should either work, or Bundler should raise an error, that local git repos are not supported, instead of trying to feed an invalid file:// URI to git.

Thanks for your help!

**Comment by deivid-rodriguez** [comment]
Hei @n-rodriguez. Indeed this was brought up already in https://github.com/rubygems/rubygems/pull/4475#issuecomment-1941604808. I'm having another look now.

**Comment by deivid-rodriguez** [comment]
I look deeper into this and indeed it was a regression from #4475. I see no reason why we shouldn't restore support for this. As a matter of fact, our own specs pass local paths to `git:` all the time, and that still works. If local full paths are supported, there's no reason to not support local relative paths. #7950 should fix this!

**Comment by n-rodriguez** [comment]
Hi @deivid-rodriguez ! Thanks for your help! I tried your patch locally but it doesn't work :

```sh
/Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git/git_proxy.rb:360:in `allowed_with_path': The git source ../build/egg is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git/git_proxy.rb:78:in `revision'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git.rb:253:in `revision'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git.rb:130:in `install_path'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/path.rb:121:in `expanded_path'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/path.rb:162:in `load_spec_files'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git.rb:230:in `load_spec_files'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/path.rb:95:in `local_specs'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git.rb:198:in `specs'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source.rb:60:in `spec_names'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source_map.rb:21:in `block in all_requirements'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source_map.rb:20:in `map'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source_map.rb:20:in `all_requirements'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:979:in `source_requirements'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:572:in `resolution_packages'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:554:in `resolver'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:635:in `start_resolution'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:305:in `resolve'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:584:in `materialize'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:193:in `specs'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:259:in `specs_for'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:18:in `setup'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler.rb:164:in `setup'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/setup.rb:32:in `block in <top (required)>'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/ui/shell.rb:159:in `with_level'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/ui/shell.rb:111:in `silence'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/setup.rb:32:in `<top (required)>'
	from <internal:/Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems.rb:1395:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
```

If I force `allowed_with_path` to return true I got this error :

```sh
/Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/path.rb:197:in `load_spec_files': The path `/Users/nicolas/PROJECTS/GITHUB/FORKS/appraisal/tmp/bundler/bundler/gems/omelette-e752361f30ce` does not exist. (Bundler::PathError)
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git.rb:230:in `load_spec_files'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/path.rb:95:in `local_specs'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/git.rb:198:in `specs'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/rubygems_aggregate.rb:35:in `block (2 levels) in build_index'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/rubygems_aggregate.rb:33:in `each'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/rubygems_aggregate.rb:33:in `block in build_index'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/index.rb:9:in `build'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/rubygems_aggregate.rb:30:in `build_index'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/rubygems_aggregate.rb:12:in `initialize'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:983:in `new'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:983:in `source_requirements'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:572:in `resolution_packages'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:554:in `resolver'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:635:in `start_resolution'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:305:in `resolve'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:584:in `materialize'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:193:in `specs'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/definition.rb:259:in `specs_for'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:18:in `setup'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler.rb:164:in `setup'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/setup.rb:32:in `block in <top (required)>'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/ui/shell.rb:159:in `with_level'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/ui/shell.rb:111:in `silence'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/setup.rb:32:in `<top (required)>'
	from <internal:/Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /Users/nicolas/.asdf/installs/ruby/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems.rb:1395:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
```

**Comment by deivid-rodriguez** [comment]
Thanks for trying. Actually I had another look and I found the issue, and I proposed a PR to Appraisals: https://github.com/thoughtbot/appraisal/pull/229.

The issue I fixed here could be considered a regression, but I don't think it was actually affecting Appraisals?

**Comment by n-rodriguez** [comment]
> but I don't think it was actually affecting Appraisals?

I've retested without your patch and it breaks :

```sh
Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
Git error: command `git clone --bare --no-hardlinks --quiet --no-tags --single-branch -- file://../build/egg /Users/nicolas/PROJECTS/GITHUB/FORKS/appraisal/tmp/bundler/cache/bundler/git/egg-95f78d756f66fd6d6c7e4bac6e136432ab838d7b` in directory
/Users/nicolas/PROJECTS/GITHUB/FORKS/appraisal/tmp/bundler/cache/bundler/git/egg-95f78d756f66fd6d6c7e4bac6e136432ab838d7b has failed.
fatal : '/build/egg' does not appear to be a git repository
fatal : Impossible de lire le dépôt distant.
```

```sh
  2) Gemfile DSL compatibility supports all Bundler DSL in Gemfile
     Failure/Error:
       raise RuntimeError, <<-error_message.strip_heredoc
         Command #{command.inspect} exited with status #{exitstatus}. Output:
         #{output.gsub(/^/, '  ')}
       error_message

     RuntimeError:
       Command "bundle install --local" exited with status 11. Output:
         Fetching ../build/egg
```

So we need your both patches 👍

**Comment by n-rodriguez** [comment]
@deivid-rodriguez  thank you!
