### ISSUE TITLE
What kind of question is that？

### ISSUE THREAD

**Issue by ZhanXieXz** [rubygems/rubygems#7934]

**Comment by ZhanXieXz** [comment]
:\shopify-my-app\multilayer-discount>shopify app dev
╭─ info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                            │
│  Using shopify.app.toml:                                                                                                   │
│                                                                                                                            │
│    • Org:             App                                                                                                  │
│    • App:             multilayer-discount                                                                                  │
│    • Dev store:       testshop0720.myshopify.com                                                                           │
│    • Update URLs:     Yes                                                                                                  │
│                                                                                                                            │
│   You can pass `--reset` to your command to reset your app configuration.                                                  │
│                                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

18:57:05 │ graphiql   │ GraphiQL server started on port 3457

── external error ────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `bundle install`

Command failed with exit code 1: bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::ENOENT: No such file or directory - "D:/Program Files/Ruby33-x64/bin/ruby.exe"
  D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:77:in `exec'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:77:in `block in restart_with'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler.rb:407:in `block in with_original_env'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler.rb:679:in `with_env'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler.rb:407:in `with_original_env'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:76:in `restart_with'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/self_manager.rb:12:in `restart_with_locked_bundler_if_needed'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/cli.rb:68:in `initialize'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:523:in `new'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:523:in `dispatch'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/cli.rb:29:in `start'
          D:/Program Files/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
          D:/Program Files/Ruby33-x64/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          D:/Program Files/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
          D:/Program Files/Ruby33-x64/bin/bundle:33:in `load'
          D:/Program Files/Ruby33-x64/bin/bundle:33:in `<main>'

```

## Environment

```
Bundler       2.5.11
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.3.4p94 (2024-07-09 revision be1089c8ec5ba40e09b1553e36b3174bf4014d9d) [x64-mingw-ucrt]
  Full Path   "D:/Program Files/Ruby33-x64/bin/ruby.exe"
  Config Dir  C:/ProgramData
RubyGems      3.5.11
  Gem Home    C:/Users/zhan.xie/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.3.0
  Gem Path    C:/Users/zhan.xie/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.3.0
  User Home   C:/Users/zhan.xie
  User Path   C:/Users/zhan.xie/.local/share/gem/ruby/3.3.0
  Bin Dir     C:/Users/zhan.xie/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.3.0/bin
Tools
  Git         2.33.0.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-08-13
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
path
  Set via BUNDLE_PATH: "C:\\Users\\zhan.xie\\AppData\\Local\\shopify-gems-nodejs\\Cache"
system_bindir
  Set via BUNDLE_SYSTEM_BINDIR: "C:/Users/zhan.xie/AppData/Local/Microsoft/WindowsApps"
user_home
  Set via BUNDLE_USER_HOME: "C:[REDACTED]"
without
  Set via BUNDLE_WITHOUT: [:development, :test]
```

## Gemfile

### Gemfile

```ruby
# NOTE: These are development-only dependencies
source "https://rubygems.org"

gem "bugsnag", "~> 6.22"
gem "listen", "~> 3.7.0"

# None of these can actually be used in a development copy of dev
# They are all for CI and tests
# `dev` uses no gems
group :development, :test do
  gem "pry-byebug"
  gem "byebug"
  gem "rubocop-shopify", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-rake", require: false
  gem "iniparse", "~> 1.5"
  gem "colorize", "~> 0.8.1"
  gem "bundler", ">= 2.3.11"
  gem "rake", "~> 12.3", ">= 12.3.3"
  gem "minitest", "~> 5.0"
end

group :test do
  gem "mocha", require: false
  gem "minitest-reporters", require: false
  gem "minitest-fail-fast", require: false
  gem "fakefs", ">= 1.0", require: false
  gem "webmock", require: false
  gem "timecop", require: false
  gem "rack", require: false
  gem "cucumber", "~> 7.0", require: false
end
gem 'wdm', '>= 0.1.0'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    ansi (1.5.0)
    ast (2.4.2)
    bugsnag (6.24.2)
      concurrent-ruby (~> 1.0)
    builder (3.2.4)
    byebug (11.1.3)
    coderay (1.1.3)
    colorize (0.8.1)
    concurrent-ruby (1.1.10)
    crack (0.4.5)
      rexml
    cucumber (7.0.0)
      builder (~> 3.2, >= 3.2.4)
      cucumber-core (~> 10.0, >= 10.0.1)
      cucumber-create-meta (~> 6.0, >= 6.0.1)
      cucumber-cucumber-expressions (~> 12.1, >= 12.1.1)
      cucumber-gherkin (~> 20.0, >= 20.0.1)
      cucumber-html-formatter (~> 16.0, >= 16.0.1)
      cucumber-messages (~> 17.0, >= 17.0.1)
      cucumber-wire (~> 6.0, >= 6.0.1)
      diff-lcs (~> 1.4, >= 1.4.4)
      mime-types (~> 3.3, >= 3.3.1)
      multi_test (~> 0.1, >= 0.1.2)
      sys-uname (~> 1.2, >= 1.2.2)
    cucumber-core (10.0.1)
      cucumber-gherkin (~> 20.0, >= 20.0.1)
      cucumber-messages (~> 17.0, >= 17.0.1)
      cucumber-tag-expressions (~> 3.0, >= 3.0.1)
    cucumber-create-meta (6.0.1)
      cucumber-messages (~> 17.0, >= 17.0.1)
      sys-uname (~> 1.2, >= 1.2.2)
    cucumber-cucumber-expressions (12.1.3)
    cucumber-gherkin (20.0.1)
      cucumber-messages (~> 17.0, >= 17.0.1)
    cucumber-html-formatter (16.0.1)
      cucumber-messages (~> 17.0, >= 17.0.1)
    cucumber-messages (17.1.1)
    cucumber-tag-expressions (3.0.1)
    cucumber-wire (6.1.1)
      cucumber-core (~> 10.0, >= 10.0.1)
      cucumber-cucumber-expressions (~> 12.1, >= 12.1.2)
      cucumber-messages (~> 17.0, >= 17.0.1)
    diff-lcs (1.4.4)
    fakefs (1.3.2)
    ffi (1.15.4)
    hashdiff (1.0.1)
    iniparse (1.5.0)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    method_source (1.0.0)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2021.0901)
    minitest (5.14.4)
    minitest-fail-fast (0.1.0)
      minitest (~> 5)
    minitest-reporters (1.4.3)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    mocha (1.13.0)
    multi_test (0.1.2)
    parallel (1.21.0)
    parser (3.2.0.0)
      ast (~> 2.4.1)
    pry (0.13.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.9.0)
      byebug (~> 11.0)
      pry (~> 0.13.0)
    public_suffix (4.0.6)
    rack (2.2.8.1)
    rainbow (3.1.1)
    rake (12.3.3)
    rb-fsevent (0.11.1)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (2.2.0)
    rexml (3.2.5)
    rubocop (1.25.1)
      parallel (~> 1.10)
      parser (>= 3.1.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.15.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.15.1)
      parser (>= 3.0.1.1)
    rubocop-minitest (0.10.1)
      rubocop (>= 0.87)
    rubocop-rake (0.5.1)
      rubocop
    rubocop-shopify (2.0.1)
      rubocop (~> 1.11)
    ruby-progressbar (1.11.0)
    sys-uname (1.2.2)
      ffi (~> 1.1)
    timecop (0.9.4)
    unicode-display_width (2.1.0)
    webmock (3.9.3)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)

PLATFORMS
  ruby

DEPENDENCIES
  bugsnag (~> 6.22)
  bundler (>= 2.3.11)
  byebug
  colorize (~> 0.8.1)
  cucumber (~> 7.0)
  fakefs (>= 1.0)
  iniparse (~> 1.5)
  listen (~> 3.7.0)
  minitest (~> 5.0)
  minitest-fail-fast
  minitest-reporters
  mocha
  pry-byebug
  rack
  rake (~> 12.3, >= 12.3.3)
  rubocop-minitest
  rubocop-rake
  rubocop-shopify
  timecop
  webmock

BUNDLED WITH
   2.3.20
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=No+such+file+or+directory+-+%22D+%2FProgram+Files%2FRuby33-x64%2Fbin%2Fruby.exe%22&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at
https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

**Comment by ZhanXieXz** [comment]
我安装了ruby3.3.4，然后执行shopify app dev以后，报了上面的错误

**Comment by deivid-rodriguez** [comment]
Closing in favor of #7791. Can you try out the patch I proposed in there to see if it fixes the issue? Thanks!
