### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/dorian-sort-csv-0.0.3

### ISSUE THREAD

**Issue by dorianmariecom** [rubygems/rubygems#7959]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/dorian-sort-csv-0.0.3
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:508:in `realpath'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:508:in `install_location'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:427:in `block (2 levels) in extract_tar_gz'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:423:in `block in extract_tar_gz'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:547:in `block in open_tar_gz'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:544:in `wrap'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:544:in `open_tar_gz'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:422:in `extract_tar_gz'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:396:in `block (2 levels) in extract_files'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:393:in `block in extract_files'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package/file_source.rb:30:in `open'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/package.rb:390:in `extract_files'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/installer.rb:861:in `extract_files'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/rubygems_gem_installer.rb:26:in `install'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/source/rubygems.rb:205:in `install'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/installer/gem_installer.rb:54:in `install'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/worker.rb:62:in `apply_func'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/worker.rb:57:in `block in process_queue'
          <internal:kernel>:187:in `loop'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/worker.rb:54:in `process_queue'
          /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.5.17
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.4p94 (2024-07-09 revision be1089c8ec5ba40e09b1553e36b3174bf4014d9d) [arm64-darwin-23]
  Full Path   /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/bin/ruby
  Config Dir  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/etc
RubyGems      3.5.11
  Gem Home    /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0
  Gem Path    /Users/dorianmariefr/.gem/ruby/3.3.0:/Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0
  User Home   /Users/dorianmariefr
  User Path   /Users/dorianmariefr/.gem/ruby/3.3.0
  Bin Dir     /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/bin
OpenSSL       
  Compiled    OpenSSL 3.3.1 4 Jun 2024
  Loaded      OpenSSL 3.3.1 4 Jun 2024
  Cert File   /opt/homebrew/etc/openssl@3/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@3/certs
Tools         
  Git         2.45.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-08-01
Git SHA           74d92b2502
Released Version  true
```

## Bundler settings

```
build.mysql2
  Set for the current user (/Users/dorianmariefr/.bundle/config): "-- --with-cflags=\\\"-Wno-error=implicit-function-declaration\\\" --with-ldflags=-L/opt/homebrew/opt/zstd/lib"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gemspec

ruby "3.3.4"

gem "rspec"
gem "rubocop-rails-omakase"
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    dorian (0.9.3)
      dorian-all
      dorian-anonymize
      dorian-anonymize-json
      dorian-anonymize-yaml
      dorian-chat
      dorian-commit
      dorian-csv-all
      dorian-csv-each
      dorian-csv-map
      dorian-csv-merge
      dorian-csv-pluck
      dorian-csv-uniq
      dorian-dir
      dorian-dir-and-self
      dorian-dot
      dorian-each
      dorian-git-ls-ruby-files
      dorian-git-tree
      dorian-json-all
      dorian-json-compare
      dorian-json-deep-each
      dorian-json-deep-map
      dorian-json-deep-pluck
      dorian-json-each
      dorian-json-map
      dorian-json-pluck
      dorian-json-read-write
      dorian-json-uniq
      dorian-parallel
      dorian-pretty
      dorian-release
      dorian-rename
      dorian-replace
      dorian-shuffle
      dorian-sort-csv
      dorian-sort-json
      dorian-sort-yaml
      dorian-times
      dorian-top
      dorian-write
      dorian-yaml-all
      dorian-yaml-compare
      dorian-yaml-deep-each
      dorian-yaml-deep-map
      dorian-yaml-deep-pluck
      dorian-yaml-each
      dorian-yaml-map
      dorian-yaml-pluck
      dorian-yaml-read-write
      dorian-yaml-uniq

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.2.0)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.3.1)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      logger (>= 1.4.2)
      minitest (>= 5.1)
      securerandom (>= 0.3)
      tzinfo (~> 2.0, >= 2.0.5)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    ast (2.4.2)
    base64 (0.2.0)
    bigdecimal (3.1.8)
    concurrent-ruby (1.3.4)
    connection_pool (2.4.1)
    csv (3.3.0)
    diff-lcs (1.5.1)
    dorian-all (0.7.2)
    dorian-anonymize (0.2.2)
    dorian-anonymize-json (0.2.2)
      json
    dorian-anonymize-yaml (0.2.2)
    dorian-arguments (0.3.1)
      activesupport
      bigdecimal
      dorian-to_struct
    dorian-chat (0.0.2)
    dorian-commit (0.4.2)
      git
    dorian-csv-all (0.1.1)
      csv
      dorian-to_struct
    dorian-csv-each (0.4.3)
      csv
      dorian-to_struct
    dorian-csv-map (0.0.2)
      csv
      dorian-to_struct
    dorian-csv-merge (0.0.2)
      csv
    dorian-csv-pluck (0.0.2)
      csv
      dorian-to_struct
    dorian-csv-uniq (0.1.1)
      csv
    dorian-dir (0.5.1)
      git
    dorian-dir-and-self (0.3.1)
      git
    dorian-dot (0.7.3)
      git
    dorian-each (0.4.2)
    dorian-git-ls-ruby-files (0.2.2)
      git
    dorian-git-tree (0.5.2)
      git
    dorian-json-all (0.1.1)
      dorian-to_struct
      json
    dorian-json-compare (0.0.2)
      json
    dorian-json-deep-each (0.0.3)
      dorian-arguments
      dorian-to_struct
      json
    dorian-json-deep-map (0.0.2)
      dorian-to_struct
      json
    dorian-json-deep-pluck (0.0.2)
      json
    dorian-json-each (0.0.2)
      dorian-to_struct
      json
    dorian-json-map (0.0.2)
      dorian-to_struct
      json
    dorian-json-pluck (0.0.2)
      json
    dorian-json-read-write (0.0.3)
      dorian-arguments
      json
    dorian-json-uniq (0.0.2)
      json
    dorian-parallel (0.2.2)
      parallel
    dorian-pretty (0.3.2)
      git
      syntax_tree
    dorian-release (0.2.2)
    dorian-rename (0.0.2)
    dorian-replace (0.5.2)
    dorian-shuffle (0.5.3)
      dorian-arguments
    dorian-sort-csv (0.0.2)
      csv
    dorian-sort-json (0.5.2)
    dorian-sort-yaml (0.4.2)
      yaml
    dorian-times (0.5.2)
    dorian-to_struct (0.5.0)
    dorian-top (0.2.2)
    dorian-write (0.1.1)
    dorian-yaml-all (0.0.2)
      dorian-to_struct
      yaml
    dorian-yaml-compare (0.4.2)
      yaml
    dorian-yaml-deep-each (0.0.3)
      dorian-arguments
      dorian-to_struct
      yaml
    dorian-yaml-deep-map (0.0.2)
      dorian-to_struct
      yaml
    dorian-yaml-deep-pluck (0.0.2)
      yaml
    dorian-yaml-each (0.0.2)
      dorian-to_struct
      yaml
    dorian-yaml-map (0.0.3)
      dorian-arguments
      dorian-to_struct
      yaml
    dorian-yaml-pluck (0.0.2)
      yaml
    dorian-yaml-read-write (0.3.3)
      dorian-arguments
      yaml
    dorian-yaml-uniq (0.0.5)
      dorian-arguments
      yaml
    drb (2.2.1)
    git (2.1.1)
      activesupport (>= 5.0)
      addressable (~> 2.8)
      process_executer (~> 1.1)
      rchardet (~> 1.8)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    json (2.7.2)
    language_server-protocol (3.17.0.3)
    logger (1.6.0)
    minitest (5.25.1)
    parallel (1.26.3)
    parser (3.3.4.2)
      ast (~> 2.4.1)
      racc
    prettier_print (1.2.1)
    process_executer (1.1.0)
    public_suffix (6.0.1)
    racc (1.8.1)
    rack (3.1.7)
    rainbow (3.1.1)
    rchardet (1.8.0)
    regexp_parser (2.9.2)
    rexml (3.3.6)
      strscan
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.0)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-support (3.13.1)
    rubocop (1.65.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 2.4, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.31.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.32.1)
      parser (>= 3.3.1.0)
    rubocop-minitest (0.35.1)
      rubocop (>= 1.61, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-performance (1.21.1)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails (2.25.1)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails-omakase (1.0.0)
      rubocop
      rubocop-minitest
      rubocop-performance
      rubocop-rails
    ruby-progressbar (1.13.0)
    securerandom (0.3.1)
    strscan (3.1.0)
    syntax_tree (6.2.0)
      prettier_print (>= 1.2.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)
    yaml (0.3.0)

PLATFORMS
  arm64-darwin-23
  ruby

DEPENDENCIES
  dorian!
  rspec
  rubocop-rails-omakase

RUBY VERSION
   ruby 3.3.4p94

BUNDLED WITH
   2.5.17
```

### dorian.gemspec

```ruby
# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name = "dorian"
  s.version = File.read("VERSION").strip
  s.summary = "a collection of gems"
  s.description = s.summary
  s.authors = ["Dorian Marié"]
  s.email = "dorian@dorianmarie.com"
  s.homepage = "https://github.com/dorianmariecom/dorian"
  s.license = "MIT"
  s.files = %w[LICENSE README.md dorian.gemspec]

  s.add_dependency "dorian-all"
  s.add_dependency "dorian-anonymize"
  s.add_dependency "dorian-anonymize-json"
  s.add_dependency "dorian-anonymize-yaml"
  s.add_dependency "dorian-chat"
  s.add_dependency "dorian-commit"
  s.add_dependency "dorian-csv-all"
  s.add_dependency "dorian-csv-each"
  s.add_dependency "dorian-csv-map"
  s.add_dependency "dorian-csv-merge"
  s.add_dependency "dorian-csv-pluck"
  s.add_dependency "dorian-csv-uniq"
  s.add_dependency "dorian-dir"
  s.add_dependency "dorian-dir-and-self"
  s.add_dependency "dorian-dot"
  s.add_dependency "dorian-each"
  s.add_dependency "dorian-git-ls-ruby-files"
  s.add_dependency "dorian-git-tree"
  s.add_dependency "dorian-json-all"
  s.add_dependency "dorian-json-compare"
  s.add_dependency "dorian-json-deep-each"
  s.add_dependency "dorian-json-deep-map"
  s.add_dependency "dorian-json-deep-pluck"
  s.add_dependency "dorian-json-each"
  s.add_dependency "dorian-json-map"
  s.add_dependency "dorian-json-pluck"
  s.add_dependency "dorian-json-read-write"
  s.add_dependency "dorian-json-uniq"
  s.add_dependency "dorian-parallel"
  s.add_dependency "dorian-pretty"
  s.add_dependency "dorian-release"
  s.add_dependency "dorian-rename"
  s.add_dependency "dorian-replace"
  s.add_dependency "dorian-shuffle"
  s.add_dependency "dorian-sort-csv"
  s.add_dependency "dorian-sort-json"
  s.add_dependency "dorian-sort-yaml"
  s.add_dependency "dorian-times"
  s.add_dependency "dorian-top"
  s.add_dependency "dorian-write"
  s.add_dependency "dorian-yaml-all"
  s.add_dependency "dorian-yaml-compare"
  s.add_dependency "dorian-yaml-deep-each"
  s.add_dependency "dorian-yaml-deep-map"
  s.add_dependency "dorian-yaml-deep-pluck"
  s.add_dependency "dorian-yaml-each"
  s.add_dependency "dorian-yaml-map"
  s.add_dependency "dorian-yaml-pluck"
  s.add_dependency "dorian-yaml-read-write"
  s.add_dependency "dorian-yaml-uniq"

  s.metadata = { "rubygems_mfa_required" => "true" }
end
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by dorianmariecom** [comment]
I was doing:

```
dir-and-self | parallel "Dir.chdir(it) { system('yarn install; yarn upgrade; bundle; bundle update; bin/importmap update; rubocop -A; prettier --write .; pretty; bundle update --bundler; git add .; commit; git push') }"
```

but i guess it's the `bundle` or `bundle update` that failed

**Comment by deivid-rodriguez** [comment]
Thank you. We've been receiving several issues about concurrent gem installations causing issues. We'll probably want to protect gem installs with a file lock for more robust behavior.

**Comment by deivid-rodriguez** [comment]
@dorianmariecom Would you be willing to help me out reproducing this? I don't know what those `dir-and-self` and `parallel` commands are. I guessed what they do and tried to setup a repro manually but could not get this to fail.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
