### ISSUE TITLE
You have already activated stringio 3.1.2.dev, but your Gemfile requires stringio 3.1.1. Since stringio is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports stringio as a default gem. (Gem::LoadError)

### ISSUE THREAD

**Issue by yahonda** [rubygems/rubygems#7996]
This issue has been originally updated to https://github.com/ruby/stringio/issues/81#issuecomment-2323847555 then discussed @hsbt and I've decided to open as a bundler issue.

### Describe the problem as clearly as you can

Running `bundler/inline` script using Ruby 3.4.0dev to install `rdoc` that depends on the `stringio` indirectly, it raises `You have already activated stringio 3.1.2.dev, but your Gemfile requires stringio 3.1.1. Since stringio is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports stringio as a default gem. (Gem::LoadError)`

### Did you try upgrading rubygems & bundler?
RubyGems and Bundler are installed by building the Ruby 3.4.0dev. Not updated after installing Ruby 3.4.0dev. 

```ruby
$ gem -v
3.6.0.dev
$ bundler -v
Bundler version 2.6.0.dev
$ ruby -v
ruby 3.4.0dev (2024-09-03T10:21:36Z master b7fa2dd0d0) [x86_64-linux]
$
```

### Post steps to reproduce the problem

* Install Ruby master branch from source
* Save the following file as `test.rb`
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rdoc"
  gem "minitest"
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert RDoc::VERSION
  end
end
```

### Which command did you run?

```
$ ruby test.rb
```
### What were you expecting to happen?
It should work successfully as it runs against Ruby 3.3.5.

```ruby
$ ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
$ ruby test.rb
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Run options: --seed 45091

# Running:

.

Finished in 0.000634s, 1576.9438 runs/s, 1576.9438 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$
```

### What actually happened?
It raises the following `Gem::LoadError`.

```ruby
$ ruby test.rb
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
/home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:310:in 'Bundler::Runtime#check_for_activated_spec!': You have already activated stringio 3.1.2.dev, but your Gemfile requires stringio 3.1.1. Since stringio is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports stringio as a default gem. (Gem::LoadError)
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:25:in 'block in Bundler::Runtime#setup'
	from <internal:array>:53:in 'Array#each'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/spec_set.rb:191:in 'Bundler::SpecSet#each'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:24:in 'Enumerable#map'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:24:in 'Bundler::Runtime#setup'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/inline.rb:66:in 'block (2 levels) in Object#gemfile'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/settings.rb:158:in 'Bundler::Settings#temporary'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/inline.rb:51:in 'block in Object#gemfile'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler.rb:430:in 'block in Bundler.with_unbundled_env'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler.rb:702:in 'Bundler.with_env'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler.rb:430:in 'Bundler.with_unbundled_env'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/inline.rb:42:in 'Object#gemfile'
	from test.rb:5:in '<main>'
$
```

### If not included with the output of your command, run `bundle env` and paste the output below

$ bundle env
## Environment

```
Bundler       2.6.0.dev
  Platforms   ruby, x86_64-linux
Ruby          3.4.0p-1 (2024-09-03 revision b7fa2dd0d0b7328f8f713b7cf0332d1e34c20fe4) [x86_64-linux]
  Full Path   /home/yahonda/.rbenv/versions/trunk/bin/ruby
  Config Dir  /home/yahonda/.rbenv/versions/trunk/etc
RubyGems      3.6.0.dev
  Gem Home    /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0
  Gem Path    /home/yahonda/.local/share/gem/ruby/3.4.0+0:/home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0
  User Home   /home/yahonda
  User Path   /home/yahonda/.local/share/gem/ruby/3.4.0+0
  Bin Dir     /home/yahonda/.rbenv/versions/trunk/bin
Tools
  Git         2.45.2
  RVM         not installed
  rbenv       rbenv 1.2.0-80-gd6bb1c6
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-09-03
Git SHA           unknown
Released Version  false
```

**Comment by yahonda** [comment]
Thanks for providing the fix. It fixes 

* Without this fix: 10 of 10 fail
https://buildkite.com/rails/rails-nightly/builds/983#0191b9b0-ea44-4009-950e-0007fd2d4e4d

* With this fix : 2 of 10 still fails
https://buildkite.com/rails/rails-nightly/builds/987#0191bed7-598b-49ee-a082-d4a082dd31cc

Let me take a look at the remaining failures.

**Comment by hsbt** [comment]
@yahonda Thank you for further details. I will investigate them.

**Comment by yahonda** [comment]
Installing gem from `stringio` to `psych` that depends on the stringio gem raises the following `Gem::LoadError`. Re-executing the same script works as expected. I am not sure if it is a repro for the current issue though.

- test.rb
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "psych"
  gem "minitest"
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert Psych::VERSION
  end
end
```

```ruby
$ ruby test.rb
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching stringio 3.1.1
Installing stringio 3.1.1 with native extensions
Fetching psych 5.1.2
Installing psych 5.1.2 with native extensions
/home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:310:in 'Bundler::Runtime#check_for_activated_spec!': You have already activated stringio 3.1.2.dev, but your Gemfile requires stringio 3.1.1. Since stringio is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports stringio as a default gem. (Gem::LoadError)
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:25:in 'block in Bundler::Runtime#setup'
	from <internal:array>:53:in 'Array#each'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/spec_set.rb:191:in 'Bundler::SpecSet#each'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:24:in 'Enumerable#map'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/runtime.rb:24:in 'Bundler::Runtime#setup'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/inline.rb:66:in 'block (2 levels) in Object#gemfile'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/settings.rb:158:in 'Bundler::Settings#temporary'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/inline.rb:51:in 'block in Object#gemfile'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler.rb:430:in 'block in Bundler.with_unbundled_env'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler.rb:702:in 'Bundler.with_env'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler.rb:430:in 'Bundler.with_unbundled_env'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.4.0+0/bundler/inline.rb:42:in 'Object#gemfile'
	from test.rb:5:in '<main>'
$ ruby test.rb
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Run options: --seed 46318

# Running:

.

Finished in 0.001136s, 880.1786 runs/s, 880.1786 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

* Environment
```
$ ruby -v
ruby 3.4.0dev (2024-09-04T14:12:50Z master 294dad22d7) [x86_64-linux]
$ gem -v
3.6.0.dev
$ bundler -v
Bundler version 2.6.0.dev
```

$ bundle env
## Environment

```
Bundler       2.6.0.dev
  Platforms   ruby, x86_64-linux
Ruby          3.4.0p-1 (2024-09-04 revision 294dad22d7ac5f307d567cff897507b9fd9d05e9) [x86_64-linux]
  Full Path   /home/yahonda/.rbenv/versions/trunk/bin/ruby
  Config Dir  /home/yahonda/.rbenv/versions/trunk/etc
RubyGems      3.6.0.dev
  Gem Home    /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0
  Gem Path    /home/yahonda/.gem/ruby/3.4.0+0:/home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0
  User Home   /home/yahonda
  User Path   /home/yahonda/.gem/ruby/3.4.0+0
  Bin Dir     /home/yahonda/.rbenv/versions/trunk/bin
Tools
  Git         2.43.0
  RVM         not installed
  rbenv       rbenv 1.2.0-87-ge8b7a27
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-09-05
Git SHA           unknown
Released Version  false
```

**Comment by hsbt** [comment]
@yahonda I submit https://github.com/rubygems/rubygems/pull/8016 for resolving CI of `rails/rails` failure. It's restriction of the current Bundler implementation, I think.

**Comment by yahonda** [comment]
Following the discussion on pull Request #8016, I found that #5535 has been rebased. I would be happy if #5535 gets merged.

**Comment by hsbt** [comment]
#5535 has been merged. But we wait to next release or to use `BUNDLE_VERSION: "global"` at `bundle config`.

**Comment by yahonda** [comment]
It looks good to me. Thanks for providing this fix.
https://gist.github.com/yahonda/4c113b812702110f68e12c2f1811ab72

**Comment by goulvench** [comment]
FWIW, I had this issue because I was running a repro script in a folder containing a Rails app. Moving the file out of the Rails app folder solved the issue.
