### ISSUE TITLE
LoadError: linked to incompatible ~/.asdf/installs/ruby/3.2.4/lib/libruby.3.2.dylib - ~/.gem/gems/stringio-3.1.1/lib/stringio.bundle

### ISSUE THREAD

**Issue by gsisson** [rubygems/rubygems#8063]
### Describe the problem as clearly as you can

I'm trying to install the [GitLab GDK](https://docs.gitlab.com/ee/development/contributing/first_contribution/configure-dev-env-gdk.html) but am getting the error in the title. I've tried on two different Mac M1 Pros but get the same error. Both Macs are running MacOS 14.6.1. One is running XCode command line tools version 15.3 and the other has 16.0.

The installation page has the user run the following installation script `curl "https://gitlab.com/gitlab-org/gitlab-development-kit/-/raw/main/support/install" | bash` and it is this script that eventually shows the error.

### Did you try upgrading rubygems & bundler?

Yes, I ran `gem update --system` and `bundle update --bundler`

### Post steps to reproduce the problem

Run the installation script `curl "https://gitlab.com/gitlab-org/gitlab-development-kit/-/raw/main/support/install" | bash` as noted at [for a local GitLab GDK install](https://docs.gitlab.com/ee/development/contributing/first_contribution/configure-dev-env-gdk.html) and take the defaults except select the "gitlab community folk" option.

### Which command did you run?

`curl "https://gitlab.com/gitlab-org/gitlab-development-kit/-/raw/main/support/install" | bash`

### What were you expecting to happen?

A lack of bundle "dylib incompatible" errors

### What actually happened?

incompatible ~/.asdf/installs/ruby/3.2.4/lib/libruby.3.2.dylib - ~/.gem/gems/stringio-3.1.1/lib/stringio.bundle

## Environment

```
Bundler       2.5.11
  Platforms   ruby, arm64-darwin-23
Ruby          3.2.4p170 (2024-04-23 revision af471c0e0127eea0cafa6f308c0425bbfab0acf5) [arm64-darwin-23]
  Full Path   ~/.asdf/installs/ruby/3.2.4/bin/ruby
  Config Dir  ~/.asdf/installs/ruby/3.2.4/etc
RubyGems      3.5.20
  Gem Home    ~/.gem
  Gem Path    ~/.gem
  User Home   ~
  User Path   ~/.gem/ruby/3.2.0
  Bin Dir     ~/.gem/bin
Tools         
  Git         2.46.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-28
Git SHA           4afb2d450a
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gemspec path: 'gem/'

group :development do
  gem 'lefthook', '~> 1.7.15', require: false
  gem 'rubocop', require: false
  gem "rubocop-rake", "~> 0.6.0", require: false
  gem 'yard', '~> 0.9.37', require: false
  gem 'pry-byebug' # See doc/howto/pry.md
end

group :test do
  gem 'gitlab-styles', '~> 12.0.1', require: false
  gem 'irb', '~> 1.14.0', require: false
  gem 'rspec', '~> 3.13.0', require: false
  gem 'rspec_junit_formatter', '~> 0.6.0', require: false
  gem 'simplecov-cobertura', '~> 2.1.0', require: false
end

group :development, :test, :danger do
  gem 'gitlab-dangerfiles', '~> 4.8.0', require: false
  gem 'resolv', '~> 0.4.0', require: false
end
```

### Gemfile.lock

```
PATH
  remote: gem
  specs:
    gitlab-development-kit (0.2.18)
      gitlab-sdk (~> 0.3.1)
      rake (~> 13.1)
      sentry-ruby (~> 5.17)
      tty-spinner (~> 0.9.3)
      zeitwerk (~> 2.6.15)

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.1.3.4)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    ast (2.4.2)
    base64 (0.2.0)
    bigdecimal (3.1.8)
    byebug (11.1.3)
    claide (1.1.0)
    claide-plugins (0.9.2)
      cork
      nap
      open4 (~> 1.3)
    coderay (1.1.3)
    colored2 (3.1.2)
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    cork (0.3.0)
      colored2 (~> 3.1)
    csv (3.3.0)
    danger (9.4.3)
      claide (~> 1.0)
      claide-plugins (>= 0.9.2)
      colored2 (~> 3.1)
      cork (~> 0.1)
      faraday (>= 0.9.0, < 3.0)
      faraday-http-cache (~> 2.0)
      git (~> 1.13)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      no_proxy_fix
      octokit (>= 4.0)
      terminal-table (>= 1, < 4)
    danger-gitlab (8.0.0)
      danger
      gitlab (~> 4.2, >= 4.2.0)
    diff-lcs (1.5.1)
    docile (1.4.0)
    drb (2.2.1)
    faraday (2.9.2)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-http-cache (2.5.1)
      faraday (>= 0.8)
    faraday-net_http (3.1.0)
      net-http
    git (1.19.1)
      addressable (~> 2.8)
      rchardet (~> 1.8)
    gitlab (4.20.1)
      httparty (~> 0.20)
      terminal-table (>= 1.5.1)
    gitlab-dangerfiles (4.8.0)
      danger (>= 9.3.0)
      danger-gitlab (>= 8.0.0)
      rake (~> 13.0)
    gitlab-sdk (0.3.1)
      activesupport (>= 5.2.0)
      rake (~> 13.0)
      snowplow-tracker (~> 0.8.0)
    gitlab-styles (12.0.1)
      rubocop (~> 1.62.1)
      rubocop-factory_bot (~> 2.25.1)
      rubocop-graphql (~> 1.5.0)
      rubocop-performance (~> 1.20.2)
      rubocop-rails (~> 2.24.0)
      rubocop-rspec (~> 2.27.1)
    httparty (0.22.0)
      csv
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    io-console (0.7.2)
    irb (1.14.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    json (2.7.2)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    language_server-protocol (3.17.0.3)
    lefthook (1.7.15)
    method_source (1.0.0)
    mini_mime (1.1.5)
    minitest (5.24.1)
    multi_xml (0.7.1)
      bigdecimal (~> 3.1)
    mutex_m (0.2.0)
    nap (1.1.0)
    net-http (0.4.1)
      uri
    no_proxy_fix (0.1.2)
    octokit (6.1.1)
      faraday (>= 1, < 3)
      sawyer (~> 0.9)
    open4 (1.3.4)
    parallel (1.25.1)
    parser (3.3.3.0)
      ast (~> 2.4.1)
      racc
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.10.1)
      byebug (~> 11.0)
      pry (>= 0.13, < 0.15)
    psych (5.1.2)
      stringio
    public_suffix (5.1.1)
    racc (1.8.0)
    rack (3.1.4)
    rainbow (3.1.1)
    rake (13.2.1)
    rchardet (1.8.0)
    rdoc (6.6.3.1)
      psych (>= 4.0.0)
    regexp_parser (2.9.2)
    reline (0.5.9)
      io-console (~> 0.5)
    resolv (0.4.0)
    rexml (3.3.1)
      strscan
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.0)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-support (3.13.0)
    rspec_junit_formatter (0.6.0)
      rspec-core (>= 2, < 4, != 2.12.0)
    rubocop (1.62.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.31.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.31.3)
      parser (>= 3.3.1.0)
    rubocop-capybara (2.21.0)
      rubocop (~> 1.41)
    rubocop-factory_bot (2.25.1)
      rubocop (~> 1.41)
    rubocop-graphql (1.5.2)
      rubocop (>= 0.90, < 2)
    rubocop-performance (1.20.2)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.30.0, < 2.0)
    rubocop-rails (2.24.1)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rake (0.6.0)
      rubocop (~> 1.0)
    rubocop-rspec (2.27.1)
      rubocop (~> 1.40)
      rubocop-capybara (~> 2.17)
      rubocop-factory_bot (~> 2.22)
    ruby-progressbar (1.13.0)
    sawyer (0.9.2)
      addressable (>= 2.3.5)
      faraday (>= 0.17.3, < 3)
    sentry-ruby (5.17.1)
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
    simplecov (0.21.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-cobertura (2.1.0)
      rexml
      simplecov (~> 0.19)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.4)
    snowplow-tracker (0.8.0)
    stringio (3.1.1)
    strscan (3.1.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    tty-cursor (0.7.1)
    tty-spinner (0.9.3)
      tty-cursor (~> 0.7)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)
    uri (0.13.0)
    yard (0.9.37)
    zeitwerk (2.6.15)

PLATFORMS
  ruby

DEPENDENCIES
  gitlab-dangerfiles (~> 4.8.0)
  gitlab-development-kit!
  gitlab-styles (~> 12.0.1)
  irb (~> 1.14.0)
  lefthook (~> 1.7.15)
  pry-byebug
  resolv (~> 0.4.0)
  rspec (~> 3.13.0)
  rspec_junit_formatter (~> 0.6.0)
  rubocop
  rubocop-rake (~> 0.6.0)
  simplecov-cobertura (~> 2.1.0)
  yard (~> 0.9.37)

BUNDLED WITH
   2.5.11
```

### gitlab-development-kit.gemspec

```ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('lib', __dir__))
require 'gitlab_development_kit'

Gem::Specification.new do |spec|
  spec.name          = 'gitlab-development-kit'
  spec.version       = GDK::GEM_VERSION
  spec.authors       = ['Jacob Vosmaer', 'GitLab']
  spec.email         = ['gitlab_rubygems@gitlab.com']

  spec.summary       = 'CLI for GitLab Development Kit'
  spec.description   = 'CLI for GitLab Development Kit.'
  spec.homepage      = 'https://gitlab.com/gitlab-org/gitlab-development-kit'
  spec.license       = 'MIT'
  spec.files         = ['lib/gitlab_development_kit.rb']
  spec.executables   = ['gdk']

  spec.required_ruby_version = '>= 3.0.5'
  spec.metadata['rubygems_mfa_required'] = 'true'

  spec.add_dependency 'gitlab-sdk', '~> 0.3.1'
  spec.add_dependency 'rake', '~> 13.1'
  spec.add_dependency 'sentry-ruby', '~> 5.17'
  spec.add_dependency 'tty-spinner', '~> 0.9.3'
  spec.add_dependency 'zeitwerk', '~> 2.6.15'
end
```

## Full output of the curl-to-bash run

````
 $ curl "https://gitlab.com/gitlab-org/gitlab-development-kit/-/raw/main/support/install" | bash                                                                    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4473  100  4473    0     0   9055      0 --:--:-- --:--:-- --:--:--  9054

INFO: This is the GDK one line installation. For more information, please visit:
INFO: https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/main/doc/index.md#one-line-installation
INFO:
INFO: The source for the installation script can be viewed at:
INFO: https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/main/support/install

Where would you like to install the GDK? [./gitlab-development-kit]


Which GitLab repo URL would you like to clone? [https://gitlab.com/gitlab-org/gitlab.git]

ATTENTION: For members of the wider community, it is recommended to use the community fork (https://gitlab.com/gitlab-community/gitlab.git).
See https://gitlab.com/gitlab-community/meta for instructions on how to join.
If you'd prefer to use your own repository, please ensure that its visibility is set to public.
https://gitlab.com/gitlab-community/gitlab.git

To improve GDK, GitLab would like to collect basic error and usage data. Please choose one of the following options:

- To send data to GitLab, enter your GitLab username.
- To send data to GitLab anonymously, leave blank.
- To avoid sending data to GitLab, enter a period ('.').

Cloning into 'gitlab-development-kit'...
From https://gitlab.com/gitlab-org/gitlab-development-kit
 * branch              main       -> FETCH_HEAD
Already on 'main'
Your branch is up to date with 'origin/main'.
INFO: Performing common preflight checks..
INFO: Setting up 'darwin' platform..
Using cmake
Using coreutils
Using docutils
Using dpkg
Using exiftool
Using fzf
Using git
Using git-lfs
Using gnupg
Using gpgme
Using graphicsmagick
Using groff
Using heimdal
Using icu4c
Using libiconv
Using libssh2
Using lychee
Using openssl@1.1
Using pkg-config
Using runit
Using sqlite
Using vault
Using yamllint
Homebrew Bundle complete! 23 Brewfile dependencies now installed.
INFO: Installing asdf..
INFO: Installing/updating asdf plugins..
Updating nodejs to master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating yarn to main
Already on 'main'
Your branch is up to date with 'origin/main'.
Updating redis to master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating minio to master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating postgres to master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating ruby to master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating shellcheck to master
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating markdownlint-cli2 to main
Already on 'main'
Your branch is up to date with 'origin/main'.
Updating vale to main
Already on 'main'
Your branch is up to date with 'origin/main'.
Updating golang to master
Already on 'master'
Your branch is up to date with 'origin/master'.
INFO: Installing asdf tools..
ruby 3.2.4 is already installed
ruby 3.2.5 is already installed
nodejs 20.12.2 is already installed
golang 1.22.6 is already installed
markdownlint-cli2 0.14.0 is already installed
minio 2022-07-15T03-44-22Z is already installed
nodejs 20.12.2 is already installed
postgres 14.9 is already installed
postgres 13.12 is already installed
redis 7.0.14 is already installed
ruby 3.2.4 is already installed
ruby 3.2.5 is already installed
shellcheck 0.10.0 is already installed
vale 3.7.1 is already installed
yarn 1.22.19 is already installed
INFO: Installing gitlab-development-kit Ruby gem..
INFO: Configuring Ruby..
Latest version already installed. Done.

INFO: Bootstrap successful!
INFO: To make sure GDK commands are available in this shell, please run the command corresponding to your shell.

sh / bash / zsh:
source "~/.asdf/asdf.sh"

fish:
source "~/.asdf/asdf.fish"

elvish:
source "~/.asdf/asdf.elv"

nushell:
source "~/.asdf/asdf.nu"
Bundle check passed.

--------------------------------------------------------------------------------
Cloning gitlab-org/gitlab
--------------------------------------------------------------------------------
Note: switching to 'v14.39.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 2ff6909 Merge branch 'ashmckenzie/gitlab-shell-release-14-39-0' into 'main'

--------------------------------------------------------------------------------
Installing asdf tools from ~/dev/gitlab-development-kit/gitlab-shell/.tool-versions
--------------------------------------------------------------------------------
golang 1.23.0 is already installed
ruby 3.3.4 is already installed

--------------------------------------------------------------------------------
Installing gitlab-org/gitlab-shell Ruby gems
--------------------------------------------------------------------------------
Bundle check failed. Installing gems using bundle install...
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
LoadError: linked to incompatible ~/.asdf/installs/ruby/3.2.4/lib/libruby.3.2.dylib - ~/.gem/gems/stringio-3.1.1/lib/stringio.bundle
  <internal:~/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          <internal:~/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          ~/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:78:in `initialize'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/fetcher.rb:211:in `new'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/fetcher.rb:211:in `gem_remote_fetcher'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/fetcher.rb:232:in `block in fetchers'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/fetcher.rb:232:in `map'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/fetcher.rb:232:in `fetchers'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/fetcher.rb:205:in `api_fetcher?'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:391:in `select'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:391:in `api_fetchers'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:396:in `block in remote_specs'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/index.rb:9:in `build'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:395:in `remote_specs'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:136:in `specs'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/lazy_specification.rb:97:in `materialize_for_installation'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/spec_set.rb:281:in `map!'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/spec_set.rb:281:in `specs_for_dependency'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/spec_set.rb:34:in `block in for'
          <internal:kernel>:187:in `loop'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/spec_set.rb:22:in `for'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/spec_set.rb:121:in `materialize'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/definition.rb:577:in `materialize'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/definition.rb:193:in `specs'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/installer.rb:83:in `block in run'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/process_lock.rb:12:in `block in lock'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/process_lock.rb:9:in `open'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/process_lock.rb:9:in `lock'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/installer.rb:71:in `run'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/installer.rb:23:in `install'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/cli/install.rb:63:in `run'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/cli.rb:247:in `block in install'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/settings.rb:157:in `temporary'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/cli.rb:246:in `install'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/cli.rb:35:in `dispatch'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/cli.rb:29:in `start'
          ~/.gem/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
          ~/.gem/gems/bundler-2.5.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          ~/.gem/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
          ~/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `load'
          ~/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.5.11
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.4p94 (2024-07-09 revision be1089c8ec5ba40e09b1553e36b3174bf4014d9d) [arm64-darwin-23]
  Full Path   ~/.asdf/installs/ruby/3.3.4/bin/ruby
  Config Dir  ~/.asdf/installs/ruby/3.3.4/etc
RubyGems      3.5.11
  Gem Home    ~/.gem
  Gem Path    ~/.gem
  User Home   ~
  User Path   ~/.gem/ruby/3.3.0
  Bin Dir     ~/.gem/bin
OpenSSL
  Compiled    OpenSSL 1.1.1w  11 Sep 2023
  Loaded      OpenSSL 1.1.1w  11 Sep 2023
  Cert File   /opt/homebrew/etc/openssl@1.1/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@1.1/certs
Tools
  Git         2.46.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-28
Git SHA           4afb2d450a
Released Version  true
```

## Bundler settings

```
jobs
  Set for the current command: 10
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'

group :development, :test do
  gem 'rspec', '~> 3.13.0'
  gem 'webrick', '~> 1.8', '>= 1.8.1'
end

group :development, :danger do
  gem 'gitlab-dangerfiles', '~> 4.8.0'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    bigdecimal (3.1.8)
    claide (1.1.0)
    claide-plugins (0.9.2)
      cork
      nap
      open4 (~> 1.3)
    colored2 (3.1.2)
    cork (0.3.0)
      colored2 (~> 3.1)
    csv (3.3.0)
    danger (9.4.3)
      claide (~> 1.0)
      claide-plugins (>= 0.9.2)
      colored2 (~> 3.1)
      cork (~> 0.1)
      faraday (>= 0.9.0, < 3.0)
      faraday-http-cache (~> 2.0)
      git (~> 1.13)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      no_proxy_fix
      octokit (>= 4.0)
      terminal-table (>= 1, < 4)
    danger-gitlab (8.0.0)
      danger
      gitlab (~> 4.2, >= 4.2.0)
    diff-lcs (1.5.1)
    faraday (2.9.2)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-http-cache (2.5.1)
      faraday (>= 0.8)
    faraday-net_http (3.1.0)
      net-http
    git (1.19.1)
      addressable (~> 2.8)
      rchardet (~> 1.8)
    gitlab (4.20.1)
      httparty (~> 0.20)
      terminal-table (>= 1.5.1)
    gitlab-dangerfiles (4.8.0)
      danger (>= 9.3.0)
      danger-gitlab (>= 8.0.0)
      rake (~> 13.0)
    httparty (0.22.0)
      csv
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    mini_mime (1.1.5)
    multi_xml (0.7.1)
      bigdecimal (~> 3.1)
    nap (1.1.0)
    net-http (0.4.1)
      uri
    no_proxy_fix (0.1.2)
    octokit (6.1.1)
      faraday (>= 1, < 3)
      sawyer (~> 0.9)
    open4 (1.3.4)
    public_suffix (5.1.1)
    rake (13.2.1)
    rchardet (1.8.0)
    rexml (3.3.1)
      strscan
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.0)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-support (3.13.0)
    sawyer (0.9.2)
      addressable (>= 2.3.5)
      faraday (>= 0.17.3, < 3)
    strscan (3.1.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    unicode-display_width (2.5.0)
    uri (0.13.0)
    webrick (1.8.1)

PLATFORMS
  ruby

DEPENDENCIES
  gitlab-dangerfiles (~> 4.8.0)
  rspec (~> 3.13.0)
  webrick (~> 1.8, >= 1.8.1)

BUNDLED WITH
   2.5.11
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error: (link deleted)

If there aren't any reports for this error yet, please fill in the new issue form located at (link deleted), and copy and paste the report template above in there.
make[1]: *** [.gitlab-shell-bundle] Error 1
make: *** [gitlab-shell-setup] Error 2
ERROR: Failed to install.
-------------------------------------------------------
You can try the following that may be of assistance:

- Run 'gdk doctor'.

- Visit the troubleshooting documentation:
  https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/main/doc/troubleshooting/index.md.
- Visit https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues to
  see if there are known issues.

- Run 'gdk reset-data' if appropriate.
- Run 'gdk pristine' which will restore your GDK to a pristine state.
-------------------------------------------------------

INFO: To make sure GDK commands are available in this shell, please run the command corresponding to your shell.

sh / bash / zsh:
source "~/.asdf/asdf.sh"

fish:
source "~/.asdf/asdf.fish"

elvish:
source "~/.asdf/asdf.elv"

nushell:
source "~/.asdf/asdf.nu"

INFO: To ensure you're in the newly installed GDK directory, please run:
cd gitlab-development-kit
```
````

**Comment by hsbt** [comment]
It caused by you mixed `~/.asdf/installs/ruby/3.2.4` and `~/.asdf/installs/ruby/3.3.4`. I suggest to remove 3.2 or 3.3 from your environment and do `gem pristine stringio`.

**Comment by deivid-rodriguez** [comment]
I'm working on providing an error message that does not suggest to open an issue in https://github.com/rubygems/rubygems [here](https://github.com/rubygems/rubygems/pull/8054), since this is generally not a problem in Bundler or RubyGems.

This suggests to me some issue in gitlab GDK where as @hsbt suggests, it's first installing `stringio` with Ruby 3.2, then trying to use it with Ruby 3.3.

I suggest to report this to Gitlab GDK, they're probably more equipped to figure out what's wrong.

**Comment by deivid-rodriguez** [comment]
Also, this particular error is actually skipped since https://github.com/rubygems/rubygems/pull/8001, so that further suggests a problem with mixed Rubies, since Gitlab GDK RubyGems version is the latest, 3.5.20, so it should not be running into the problem. Again, I'm sure people at gitlab with know what's going on better 👍.

**Comment by deivid-rodriguez** [comment]
Finally, the fundamental problem I see is that the output of `bundle env` in the error message is the following:

```
Bundler       2.5.11
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.4p94 (2024-07-09 revision be1089c8ec5ba40e09b1553e36b3174bf4014d9d) [arm64-darwin-23]
  Full Path   ~/.asdf/installs/ruby/3.3.4/bin/ruby
  Config Dir  ~/.asdf/installs/ruby/3.3.4/etc
RubyGems      3.5.11
  Gem Home    ~/.gem
  Gem Path    ~/.gem
  User Home   ~
  User Path   ~/.gem/ruby/3.3.0
  Bin Dir     ~/.gem/bin
OpenSSL
  Compiled    OpenSSL 1.1.1w  11 Sep 2023
  Loaded      OpenSSL 1.1.1w  11 Sep 2023
  Cert File   /opt/homebrew/etc/openssl@1.1/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@1.1/certs
Tools
  Git         2.46.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

In particular, `GEM_PATH` and `GEM_HOME` are set to a path that's independent from the Ruby ABI (they should instead be something like `~/.gem/ruby/3.3.0`. That means that the GDK repos using Ruby 3.2 and the GDK repos using 3.3 install to the same path, creating this problem.

Do you have `GEM_PATH` or `GEM_HOME` environment variables set?

**Comment by gsisson** [comment]
Yes, I do have both `GEM_PATH` and `GEM_HOME` set. Both set to `~/.gem/. So I will comment those env vars out of my .bashrc and unset them in my shells. Also I will uninstall ruby 3.3 and ttry the gdk install again.

Thank you all for your help with this issue.

**Comment by gsisson** [comment]
Thanks again folks. Removal of the GEM_ env vars seems to have solved the problem. Removal of ruby 3.3 didn't help... the gitlab gdk installation installs 3.3 again (as well as 3.2.4 and 3.2.5)

**Comment by gsisson** [comment]
Thanks again folks. Removal of the GEM_ env vars seems to have solved the problem. Removal of ruby 3.3 didn't help... the gitlab gdk installation installs 3.3 again (as well as 3.2.4 and 3.2.5)

**Comment by deivid-rodriguez** [comment]
Glad it's now fixed!

Yes, indeed removing Ruby 3.3 does not help because [gitlab-shell uses 3.3.5](https://gitlab.com/gitlab-org/gitlab-shell/-/blob/main/.tool-versions?ref_type=heads). As long as each Ruby has its own dedicated `GEM_HOME` (default behavior), it should be fine, and removing those ENV vars suffices.

I wonder why did you set `GEM_HOME` and `GEM_PATH` in the first place? I'm curious if you find it in some gitlab documentation, since in that case, it should be fixed. Yesterday I posted a comment in a [gitlab PR](https://gitlab.com/gitlab-org/gitlab-development-kit/-/merge_requests/3074) that could be related.

**Comment by gsisson** [comment]
Not sure why I had those env vars defined. I used to work heavily in Ruby many years ago and apparently put those env vars in my .bashrc back then for some reason, but I don't know why. They just hung around in by .bashrc until they bit me now, as I began working in Ruby on GitLab. Anyway, thanks again for the help.
