### ISSUE TITLE
bundle update fastlane command fails with error `You don't have write permissions for the /usr/bin directory.`

### ISSUE THREAD

**Issue by GowthamChintaCallsign** [rubygems/rubygems#8085]
### Describe the problem as clearly as you can

My end goal is to create fastlane profile to utilise in gitlab CICD, As a requirement I am running `sudo bundle update fastlane`, It fails with below error. 

```
Gem::FilePermissionError: You don't have write permissions for the /usr/bin directory.
  /Library/Ruby/Site/2.6.0/rubygems/installer.rb:939:in `ensure_writable_dir'
  /Library/Ruby/Site/2.6.0/rubygems/installer.rb:480:in `generate_bin'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:203:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:130:in `do_install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:121:in `block in worker_pool'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/worker.rb:62:in `apply_func'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/worker.rb:57:in `block in process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `loop'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

I checked and validated if I have privilege on /usr/bin and /Library, couldn't figure out why it is a failure.

**Comment by deivid-rodriguez** [comment]
Can you first upgrade Bundler, and try again?

**Comment by GowthamChintaCallsign** [comment]
I did try to upgrade the bundler, I am facing same issue

<img width="918" alt="image" src="https://github.com/user-attachments/assets/31ab7ac3-f3c6-4957-bcb9-e3f549dbc53d">

**Comment by deivid-rodriguez** [comment]
Oh, I see. And I guess `sudo gem install bundler` runs into a similar issue?

**Comment by deivid-rodriguez** [comment]
Good! What's your RubyGems version now (`gem -v`)?

**Comment by GowthamChintaCallsign** [comment]
RubyGems version is 3.5.18

**Comment by deivid-rodriguez** [comment]
Well, that's very recent now. It seems like that gem package got corrupted for some reason. Can you reproduce the issue consistently now?
