### ISSUE TITLE
Bundler Install Error in AWS

### ISSUE THREAD

**Issue by Nebula-Dust** [rubygems/rubygems#8102]
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Fetching aws-eventstream 1.3.0
Fetching aws-partitions 1.983.0
Installing aws-eventstream 1.3.0
Fetching jmespath 1.6.2
Installing aws-partitions 1.983.0
Using bundler 2.4.10
Fetching coderay 1.1.3
Installing jmespath 1.6.2
Fetching method_source 1.1.0
Installing method_source 1.1.0
Fetching ox 2.14.18
Installing coderay 1.1.3
Installing ox 2.14.18 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /usr/share/ruby3.2-gems directory.
  /usr/share/ruby3.2-rubygems/rubygems/installer.rb:712:in `verify_gem_home'
  /usr/share/ruby3.2-rubygems/rubygems/installer.rb:902:in `pre_install_checks'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/rubygems_gem_installer.rb:64:in `pre_install_checks'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/rubygems_gem_installer.rb:12:in `install'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/source/rubygems.rb:200:in `install'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/worker.rb:62:in `apply_func'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/worker.rb:54:in `loop'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/worker.rb:54:in `process_queue'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - /usr/share/ruby3.2-gems/bundler.lock
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/process_lock.rb:9:in `initialize'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/installer.rb:71:in `run'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/installer.rb:23:in `install'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/cli/install.rb:62:in `run'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/cli.rb:261:in `block in install'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/settings.rb:131:in `temporary'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/cli.rb:260:in `install'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/share/ruby3.2-gems/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
  /usr/bin/bundle:25:in `load'
  /usr/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.10
  Platforms   ruby, x86_64-linux
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux]
  Full Path   /usr/bin/ruby3.2
  Config Dir  /etc
RubyGems      3.4.10
  Gem Home    /usr/share/ruby3.2-gems
  Gem Path    /home/cloudshell-user/.local/share/gem/ruby:/usr/share/ruby3.2-gems:/usr/share/gems:/usr/local/share/ruby3.2-gems:/usr/local/share/gems
  User Home   /home/cloudshell-user
  User Path   /home/cloudshell-user/.local/share/gem/ruby
  Bin Dir     /usr/bin
OpenSSL       
  Compiled    OpenSSL 3.0.8 7 Feb 2023
  Loaded      OpenSSL 3.0.8 7 Feb 2023
  Cert File   /etc/pki/tls/cert.pem
  Cert Dir    /etc/pki/tls/certs
Tools         
  Git         2.40.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-10-03
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'ox'
gem 'aws-sdk-rekognition'
gem 'pry'
```

### Gemfile.lock

```
<No /home/cloudshell-user/rekognition/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
Hi! I think this has been fixed in the latest version of Bundler & RubyGems. Please upgrade first and then reopen with updated backtraces and error messages if still running into the problem. Thanks!
