### ISSUE TITLE
RubyGems 3.5.19 and later break Gem installs on Linux NFS shares

### ISSUE THREAD

**Issue by rattei** [rubygems/rubygems#8105]
Update of RubyGems from 3.5.18 to 3.5.19 or later (including 3.5.21) breaks ruby installations on Linux NFS shares (as e.g. relevant in High Performance Computing environments). Same problem was observed with freshly installed ruby 3.2.5 and with freshly installed ruby 3.3.5.

Running 'gem update --system 3.5.19' results in this output:

```
Installing RubyGems 3.5.19
  Successfully built RubyGem
  Name: bundler
  Version: 2.5.19
  File: bundler-2.5.19.gem
ERROR:  While executing gem ... (Errno::EBADF)
    Bad file descriptor @ rb_file_flock - /lisc/app/ruby/3.2.5/bin/bundle.lock
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems.rb:796:in `flock'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems.rb:796:in `block in open_file_with_flock'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems.rb:794:in `open'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems.rb:794:in `open_file_with_flock'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems.rb:782:in `open_file_with_lock'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/installer.rb:541:in `generate_bin_script'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/installer.rb:509:in `block in generate_bin'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/installer.rb:495:in `each'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/installer.rb:495:in `generate_bin'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/installer.rb:335:in `install'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/commands/setup_command.rb:414:in `block in install_default_bundler_gem'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/commands/setup_command.rb:402:in `chdir'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/commands/setup_command.rb:402:in `install_default_bundler_gem'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/commands/setup_command.rb:175:in `execute'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/command.rb:326:in `invoke_with_build_args'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/command_manager.rb:255:in `invoke_command'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/command_manager.rb:194:in `process_args'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/command_manager.rb:152:in `run'
	/lisc/app/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/rubygems-update-3.5.19/lib/rubygems/gem_runner.rb:56:in `run'
	setup.rb:36:in `<main>'
```

Afterwards, also 'gem update' commands fail, like:

```
Fetching rbs-3.6.1.gem
Building native extensions. This could take a while...
ERROR:  While executing gem ... (Errno::EBADF)
    Bad file descriptor @ rb_file_flock - /lisc/app/ruby/3.3.5/bin/rbs.lock
...
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting. This broke a couple years ago in the same way. I will try setup a NFS share to fix this and make sure we don't regress again.

**Comment by deivid-rodriguez** [comment]
Hei! Apparently I'm pretty bad at setting up NFS shares, so I can't test this myself. Can you verify if [this change](https://github.com/rubygems/rubygems/compare/deivid-rodriguez/fix-nfs-shares) fixes the issue?

**Comment by rattei** [comment]
Thanks for the quick fix!
Indeed, the change has solved the problem for us. Gem updates and installs now work again after applying the fix.
Best, Thomas

**Comment by deivid-rodriguez** [comment]
Great! May I ask one more question? If you remove lines 818 and 819, does it still work? We have code there that claims to be NFS-specific but I'm not sure if it's needed.

**Comment by rattei** [comment]
I have checked that. Have removed the lines:
`rescue Errno::ENOLCK # NFS
        raise unless Thread.main == Thread.current
`
Gem installs still worked as usual after this change.
