### ISSUE TITLE
Bundler unexpectly Kernel.exec on require 'bundler/setup' and loses all command-line flags and CWD

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#8106]
### Describe the problem as clearly as you can

This can be reproduced with:

```
$ chruby 3.3.5
$ bundle config --global path vendor/bundle
$ gem uni bundler:2.4.19

$ git clone git@github.com:eregon/yjit-bench.git
$ cd yjit-bench
$ git checkout bundler-bug
$ ruby run_benchmarks.rb --harness=warmup --chruby='ruby-3.3.5' activerecord
```

gives:
```
$ ruby run_benchmarks.rb --harness=warmup --chruby='ruby-3.3.5 --yjit' activerecord
Running benchmark "activerecord" (1/1)
+ setarch x86_64 -R taskset -c 7 /home/eregon/.rubies/ruby-3.3.5/bin/ruby --yjit -I harness-warmup /home/eregon/code/yjit-bench/benchmarks/activerecord/benchmark.rb

Starting activerecord benchmark with:
PID: 610006
$LOAD_PATH
/home/eregon/code/yjit-bench/harness-warmup
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/site_ruby/3.3.0
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/site_ruby/3.3.0/x86_64-linux
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/site_ruby
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/vendor_ruby/3.3.0
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/vendor_ruby/3.3.0/x86_64-linux
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/vendor_ruby
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/3.3.0
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/3.3.0/x86_64-linux
Dir.pwd: /home/eregon/code/yjit-bench
RUBY_DESCRIPTION: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [x86_64-linux]

ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [x86_64-linux]
Command: bundle check 2> /dev/null || bundle install
The Gemfile's dependencies are satisfied

Starting activerecord benchmark with:
PID: 610006
$LOAD_PATH
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/site_ruby/3.3.0
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/site_ruby/3.3.0/x86_64-linux
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/site_ruby
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/vendor_ruby/3.3.0
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/vendor_ruby/3.3.0/x86_64-linux
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/vendor_ruby
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/3.3.0
/home/eregon/.rubies/ruby-3.3.5/lib/ruby/3.3.0/x86_64-linux
Dir.pwd: /home/eregon/code/yjit-bench/benchmarks/activerecord
RUBY_DESCRIPTION: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]

/home/eregon/code/yjit-bench/harness/harness.rb:3:in `<top (required)>': should not reach here (RuntimeError)
	from <internal:/home/eregon/.rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/home/eregon/.rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /home/eregon/code/yjit-bench/harness/loader.rb:4:in `<top (required)>'
	from /home/eregon/code/yjit-bench/benchmarks/activerecord/benchmark.rb:9:in `require_relative'
	from /home/eregon/code/yjit-bench/benchmarks/activerecord/benchmark.rb:9:in `<main>'
Command "setarch x86_64 -R taskset -c 7 /home/eregon/.rubies/ruby-3.3.5/bin/ruby --yjit -I harness-warmup /home/eregon/code/yjit-bench/benchmarks/activerecord/benchmark.rb" failed with exit code 1 in directory /home/eregon/code/yjit-bench
...
```
So there we can see:
* The PID is the same and Bundler is calling Kernel.exec unexpectedly, which causes:
* The first $LOAD_PATH entry has been lost (`/home/eregon/code/yjit-bench/harness-warmup` from `-I harness-warmup`)
* Which means the wrong harness is loaded and we get to that `should not reach here (RuntimeError)`
* The current working dir has changed. This means relative paths are reinterpreted differently and incorrectly, hence this workaround: https://github.com/eregon/yjit-bench/commit/fb09723ca9bab9f6f4d867d7291b182014c122b9#diff-286ad695324de1cdc1615695f4f4158b17dc9da8229989a28f12b9cacc1eec64
* The second one lost the `--yjit` option and so no JIT is enabled

You can imagine how this can be a "what the hell" moment when the user runs one command but Bundler silently exec's, which means running the command a second time and loses a bunch of critical state on `require "bundler/setup"`.

Luckily this can be worked around by `gem install bundler:2.4.19`.
So part of the issue is that with the bundle config as `bundle config --global path vendor/bundle` the locked bundler version gets installed to `benchmarks/activerecord/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.19`.

But the bigger issue is I would never expect any `require` to call `Kernel.exec`.
The `Kernel.exec` call is from here https://github.com/rubygems/rubygems/blob/4968b9063e2d7d8261acc201c497197bc10b0f11/bundler/lib/bundler/self_manager.rb#L69-L97
and that acknowledges it loses all flags.
I think using `Kernel.exec` is fine on `bundle exec` as then flags are preserved and nothing is lost, and it's effectively transparent (except slightly slower to start Ruby again).
But on `require "bundler/setup"` I think Bundler should never do that.
It could warn or error that the "wrong" version of Bundler is loaded, and let the user retry.
That I think is the only way to properly preserve all that state and avoid lots of confusion.

### Did you try upgrading rubygems & bundler?

No, but https://github.com/rubygems/rubygems/blob/4968b9063e2d7d8261acc201c497197bc10b0f11/bundler/lib/bundler/self_manager.rb shows it's still present on master so I would expect that logic hasn't changed.

**Comment by eregon** [comment]
https://github.com/rubygems/rubygems/commit/076aba8b1c25291a986f9c233cb80192adbe2fcf seems to be what added this re-exec behavior for `require "bundler/setup"`.

**Comment by indirect** [comment]
I agree that exiting with an error to tell the user how to install the Bundler version that they need is probably the way to go here—we definitely don’t want to discard flags passed to commands run via binstub.

**Comment by deivid-rodriguez** [comment]
Yeah, until the Ruby feature to be able to re-exec cleanly is there, I agree it'd be best to revert this change. I can take care of this.

**Comment by eregon** [comment]
I think it's probably fine to `exec` for binstubs generated by Bundler (because they cannot be passed ruby command line options and they don't change CWD), but not for general `require 'bundler/setup'`.
So maybe we can use some different method or some other way to let Bundler know it's called from a binstub.

**Comment by indirect** [comment]
Yeah, that makes sense to me! `exec` to the right version of Bundler for binstubs was the intended outcome of the original PR, so hopefully we can keep that without always forcing an `exec` on any `require 'bundler/setup'`. :+1:

**Comment by eregon** [comment]
One more general thought on this is I expect (perhaps naively or wrongly) that `require 'bundler/setup'` basically just adds a bunch of entries to `$LOAD_PATH` and has no other visible side effect (well, except disabling to require gems dynamically).
Like the generated `vendor/bundle/bundler/setup.rb` by `bundle install --standalone` would do.
And the beauty of that file is it's independent of any Bundler version, so the concern of auto-switching is entirely removed then.

I would intuitively expect `require 'bundler/setup'` to not look at the Gemfile but only the Gemfile.lock (and error if it's not there or older than Gemfile), but IIRC that's not how it works (I'm talking non-standalone mode, where IIRC Bundler re-evals the Gemfile every time).
I'm thinking for a startup and simplicity point of view maybe it would make sense to default to `--standalone`-like behavior in Bundler at some point. That would make make it very lightweight on the loading side of things, and then all the heavy work is done during `bundle install`.

**Comment by eregon** [comment]
This seems a pretty big bug to me with high potential for confusion and very hard to find out what's going on.
In fact there are now 2 more issues linked to this one.
Is there a chance this could be fixed soon?
A concrete idea to address it is in https://github.com/rubygems/rubygems/issues/8106#issuecomment-2397700478.

**Comment by deivid-rodriguez** [comment]
Happy to take a patch improving this, otherwise we'll get to it eventually.

**Comment by mackuba** [comment]
I found this after I added a print line at the top of my script, and I was surprised why it gets printed twice, as if `require 'bundler/setup'` was relaunching my script from the beginning for some reason 😅 (thanks ChatGPT for helping me track this down)

Not a big problem for me, but this does feel like unexpected behavior (is it documented that you're not supposed to have any code above `require 'bundler/setup'`?)
