### ISSUE TITLE
Setting http endpoint in server but response is from https?

### ISSUE THREAD

**Issue by mcgurksean** [rubygems/rubygems#8192]
Hi there,

I have installed the chef-rundeck gem from https://github.com/priestjim/chef-rundeck

And am using it to pull info from my chef intra server.

Our chef infra servers are configured to run over http. It's a little crummy but it works ok.

I am executing the following command to run the Sinatra app that 'serves' the info:

`chef-rundeck2 --chef-api-admin-name MY_CHEF_CLIENT --chef-api-admin-key /etc/chef/client.pem --chef-api-endpoint http://my-chef-server.com -e development`

When I try and pull the info back via a http request, I get the following message:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=xx.xxx.xx.x:443 state=error: certificate verify failed (self-signed certificate)
        /usr/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock'
        /usr/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
        /usr/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
        /usr/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
        /usr/lib/ruby/3.0.0/net/http.rb:959:in `start'
        /var/lib/gems/3.0.0/gems/chef-api-0.10.10/lib/chef-api/connection.rb:289:in `request'
        /var/lib/gems/3.0.0/gems/chef-api-0.10.10/lib/chef-api/connection.rb:299:in `block in request'
        /usr/lib/ruby/3.0.0/net/http.rb:960:in `start'
        /var/lib/gems/3.0.0/gems/chef-api-0.10.10/lib/chef-api/connection.rb:289:in `request'
        /var/lib/gems/3.0.0/gems/chef-api-0.10.10/lib/chef-api/connection.rb:109:in `get'
        /var/lib/gems/3.0.0/gems/chef-api-0.10.10/lib/chef-api/resources/base.rb:200:in `list'
        /var/lib/gems/3.0.0/gems/chef-rundeck2-0.1.5/lib/chef-rundeck/chef.rb:56:in `list'
        /var/lib/gems/3.0.0/gems/chef-rundeck2-0.1.5/lib/chef-rundeck/api.rb:119:in `block (2 levels) in <class:API>'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /var/lib/gems/3.0.0/gems/rack-cache-1.17.0/lib/rack/cache/context.rb:141:in `forward'
        /var/lib/gems/3.0.0/gems/rack-cache-1.17.0/lib/rack/cache/context.rb:267:in `fetch'
        /var/lib/gems/3.0.0/gems/rack-cache-1.17.0/lib/rack/cache/context.rb:196:in `lookup'
        /var/lib/gems/3.0.0/gems/rack-cache-1.17.0/lib/rack/cache/context.rb:67:in `call!'
        /var/lib/gems/3.0.0/gems/rack-cache-1.17.0/lib/rack/cache/context.rb:52:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/logger.rb:15:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/commonlogger.rb:33:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/handler/webrick.rb:88:in `service'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread
```

This is despite my having specified the endpoint as http and *not* https.

The IP address for my chef server is correct but I do not have a https endpoint so I don't understand why the chef-rundeck gem is tryiing to connect over https.

**Comment by deivid-rodriguez** [comment]
Hello! This is not a RubyGems issue, so I'll close it. I recommend to ask for help over at https://github.com/priestjim/chef-rundeck.
