### ISSUE TITLE
Bundler hides the actual error when openssl fails to load

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#8229]
For example see
https://github.com/ruby/uri/actions/runs/11737031870/job/32697190779
```
Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your
Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using
RVM are available at rvm.io/packages/openssl.
```
Or https://github.com/ruby/setup-ruby/actions/runs/11718129929/job/32638979324?pr=667
```
Could not load OpenSSL.
You must recompile Ruby with OpenSSL support.
```

While the actual error looks like: https://github.com/eregon/setup-ruby/actions/runs/11724213556/job/32657603152
```
$ ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
<internal:core> core/kernel.rb:255:in `require': you may need to install the system OpenSSL library libssl - see https://github.com/oracle/truffleruby/blob/master/doc/user/installing-libssl.md (dlopen(/Users/runner/.rubies/truffleruby-24.1.1/lib/mri/openssl.bundle, 0x0009): Library not loaded: /opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib (RuntimeError)
  Referenced from: <544C5488-F84C-3FC0-A63A-965284495972> /Users/runner/.rubies/truffleruby-24.1.1/lib/mri/openssl.bundle
  Reason: tried: '/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file))
	from /Users/runner/.rubies/truffleruby-24.1.1/lib/mri/openssl.rb:13:in `<top (required)>'
	from <internal:core> core/kernel.rb:255:in `require'
```

It is necessary to have the original error to understand the problem.

It's fine if Bundler/RubyGems wants to make it nicer for the user, but should never hide the original error message.

This is notably a problem for investigating https://github.com/ruby/setup-ruby/issues/668#issuecomment-2463861096

**Comment by deivid-rodriguez** [comment]
Thank you! I created #8232 to include the original error.
