### ISSUE TITLE
Permission Error when creating a new Rails Application

### ISSUE THREAD

**Issue by jessedoka** [rubygems/rubygems#8310]
```
Gem::FilePermissionError: You don't have write permissions for the /var/lib/gems/3.2.0 directory.
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:713:in `verify_gem_home'
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:903:in `pre_install_checks'
  /usr/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:64:in `pre_install_checks'
  /usr/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:12:in `install'
  /usr/lib/ruby/3.2.0/bundler/source/rubygems.rb:202:in `install'
  /usr/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /usr/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /usr/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /usr/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'
Errno::EACCES: Permission denied @ rb_sysopen - /var/lib/gems/3.2.0/bundler.lock
  /usr/lib/ruby/3.2.0/bundler/process_lock.rb:9:in `initialize'
  /usr/lib/ruby/3.2.0/bundler/process_lock.rb:9:in `open'
  /usr/lib/ruby/3.2.0/bundler/process_lock.rb:9:in `lock'
  /usr/lib/ruby/3.2.0/bundler/installer.rb:71:in `run'
  /usr/lib/ruby/3.2.0/bundler/installer.rb:23:in `install'
  /usr/lib/ruby/3.2.0/bundler/cli/install.rb:62:in `run'
  /usr/lib/ruby/3.2.0/bundler/cli.rb:261:in `block in install'
  /usr/lib/ruby/3.2.0/bundler/settings.rb:130:in `temporary'
  /usr/lib/ruby/3.2.0/bundler/cli.rb:260:in `install'
  /usr/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
  /usr/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <main>'
  /usr/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<main>'

```

## Environment

```
Bundler       2.4.19
  Platforms   ruby, x86_64-linux-gnu
Ruby          3.2.3p157 (2024-01-18 revision 52bb2ac0a6971d0391efa2275f7a66bff319087c) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby3.2
  Config Dir  /etc
RubyGems      3.4.20
  Gem Home    /var/lib/gems/3.2.0
  Gem Path    /home/smiley/.local/share/gem/ruby/3.2.0:/var/lib/gems/3.2.0:/usr/local/lib/ruby/gems/3.2.0:/usr/lib/ruby/gems/3.2.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.2.0:/usr/share/rubygems-integration/3.2.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.2.0
  User Home   /home/smiley
  User Path   /home/smiley/.local/share/gem/ruby/3.2.0
  Bin Dir     /usr/local/bin
OpenSSL       
  Compiled    OpenSSL 3.0.13 30 Jan 2024
  Loaded      OpenSSL 3.0.13 30 Jan 2024
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.43.0
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-12-06
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
ignore_messages
  Set via BUNDLE_IGNORE_MESSAGES: true
```

### Gemfile

```ruby
source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.0"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end
```

### Gemfile.lock

```
<No /home/smiley/dev/blog/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
You are using old RubyGems, Bundler, and Ruby versions.

Please make sure to upgrade RubyGems and Bundler first, and once using the latest versions,  please reopen if this still reproduces. Also, please include which command you are running!
