### ISSUE TITLE
Bundler ArgumentError on readonly filesystem on ruby 3.4

### ISSUE THREAD

**Issue by Vasfed** [rubygems/rubygems#8369]
### Describe the problem as clearly as you can

Ruby 3.4 changed the way how tmpdir is checked for writability and now correctly produce an error on readonly filesystems (for example when in docker/kubernetes), but the error is `ArgumentError` and is not handled by bundler.

### Did you try upgrading rubygems & bundler?

Tried bundler 2.6.2 that comes with ruby 3.4.1, but the code in question was not changed for some time and other bundler versions should be affected too

### Post steps to reproduce the problem

Initially encountered the error in a k8s app that runs with readonly filesystem (security best practice) and without tmp directory. But nor the application nor the gemfile are relevant, can be reproduced with oneliner below

### Which command did you run?
Shortest cmd to reproduce the error:
```sh
docker run --rm --read-only ruby:3.4.1-alpine3.21 ruby -r'bundler/inline' -e 'gemfile {}; puts :ok'
```

More correct one (simulates an app, BUNDLE_FROZEN does not play a role, included only to illustrate a production-like setup):
```sh
echo 'source "https://rubygems.org"' > Gemfile
echo "GEM\n  remote: https://rubygems.org/\n  specs:\n\nPLATFORMS\n  arm64-darwin-23\n  ruby\n\nDEPENDENCIES\n\nBUNDLED WITH\n   2.6.2\n" > Gemfile.lock
docker run --rm --read-only -v '.:/root:ro' -w /root -e 'BUNDLE_FROZEN=true' ruby:3.4.1-alpine3.21 ruby -rbundler -e 'Bundler.require; puts :ok'
```

### What were you expecting to happen?

Expected no error and `ok` output, same as in ruby 3.3:
```sh
docker run --rm --read-only ruby:3.3.6-alpine3.21 ruby -r'bundler/inline' -e 'gemfile {}; puts :ok'
```

Workaround is to set `BUNDLE_USER_PLUGIN` env to any value (even empty). But it's natural to assume a plugin presence check not to produce any errors with default settings if some possible directory is not present/writable

### What actually happened?

```
`/root` is not writable.
system temporary path is not writable: /tmp
/tmp is not writable: /tmp
. is not writable: /root
/usr/local/lib/ruby/3.4.0/tmpdir.rb:44:in 'Dir.tmpdir': could not find a temporary directory (ArgumentError)

    end or raise ArgumentError, "could not find a temporary directory"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /usr/local/lib/ruby/3.4.0/bundler.rb:705:in 'Bundler.tmp_home_path'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:278:in 'Bundler.user_home'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:290:in 'block in Bundler.user_bundle_path'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'fetch'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'Bundler.user_bundle_path'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:296:in 'block in Bundler.user_bundle_path'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'fetch'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'Bundler.user_bundle_path'
	from /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:151:in 'Bundler::Plugin.global_root'
	from /usr/local/lib/ruby/3.4.0/bundler/plugin/index.rb:93:in 'Bundler::Plugin::Index#global_index_file'
	from /usr/local/lib/ruby/3.4.0/bundler/plugin/index.rb:33:in 'Bundler::Plugin::Index#initialize'
	from /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:130:in 'Class#new'
	from /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:130:in 'Bundler::Plugin.index'
	from /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:228:in 'Bundler::Plugin.hook'
	from /usr/local/lib/ruby/3.4.0/bundler/runtime.rb:50:in 'Bundler::Runtime#require'
	from /usr/local/lib/ruby/3.4.0/bundler.rb:216:in 'Bundler.require'
	from -e:1:in '<main>'
```

### If not included with the output of your command, run `bundle env` and paste the output below

docker run --rm --read-only ruby:3.4.1-alpine3.21 bundle env
## Environment

```
Bundler       2.6.2
  Platforms   ruby, aarch64-linux-musl
Ruby          3.4.1p0 (2024-12-25 revision 48d4efcb85000e1ebae42004e963b5d0cedddcf2) [aarch64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.6.2
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.4.0:/usr/local/lib/ruby/gems/3.4.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.4.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-12-27
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

**Comment by Vasfed** [comment]
One more way to reproduce:
```sh
docker run -it --rm --read-only ruby:3.4.1-alpine3.21 bundle plugin list
```
```
`/root` is not writable.
system temporary path is not writable: /tmp
/tmp is not writable: /tmp
. is not writable: /
...
ArgumentError: could not find a temporary directory
  /usr/local/lib/ruby/3.4.0/tmpdir.rb:44:in 'Dir.tmpdir'
          /usr/local/lib/ruby/3.4.0/bundler.rb:705:in 'Bundler.tmp_home_path'
          /usr/local/lib/ruby/3.4.0/bundler.rb:278:in 'Bundler.user_home'
          /usr/local/lib/ruby/3.4.0/bundler.rb:290:in 'block in Bundler.user_bundle_path'
          /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'fetch'
          /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'Bundler.user_bundle_path'
          /usr/local/lib/ruby/3.4.0/bundler.rb:296:in 'block in Bundler.user_bundle_path'
          /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'fetch'
          /usr/local/lib/ruby/3.4.0/bundler.rb:302:in 'Bundler.user_bundle_path'
          /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:151:in 'Bundler::Plugin.global_root'
          /usr/local/lib/ruby/3.4.0/bundler/plugin/index.rb:93:in 'Bundler::Plugin::Index#global_index_file'
          /usr/local/lib/ruby/3.4.0/bundler/plugin/index.rb:33:in 'Bundler::Plugin::Index#initialize'
          /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:130:in 'Class#new'
          /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:130:in 'Bundler::Plugin.index'
          /usr/local/lib/ruby/3.4.0/bundler/plugin.rb:81:in 'Bundler::Plugin.list'
          /usr/local/lib/ruby/3.4.0/bundler/cli/plugin.rb:32:in 'Bundler::CLI::Plugin#list'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/invocation.rb:116:in 'Bundler::Thor::Invocation#invoke'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor.rb:338:in 'block in Bundler::CLI#subcommand'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
          /usr/local/lib/ruby/3.4.0/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
          /usr/local/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
          /usr/local/lib/ruby/3.4.0/bundler/cli.rb:29:in 'Bundler::CLI.start'
          /usr/local/lib/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle:28:in 'block in <top (required)>'
          /usr/local/lib/ruby/3.4.0/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
          /usr/local/lib/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle:20:in '<top (required)>'
          /usr/local/bin/bundle:25:in 'Kernel#load'
          /usr/local/bin/bundle:25:in '<main>'

```

## Environment

```
Bundler       2.6.2
  Platforms   ruby, aarch64-linux-musl
Ruby          3.4.1p0 (2024-12-25 revision 48d4efcb85000e1ebae42004e963b5d0cedddcf2) [aarch64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.6.2
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.4.0:/usr/local/lib/ruby/gems/3.4.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.4.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-12-27
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

3.3 does not error:
```sh
docker run -it --rm --read-only ruby:3.3.6-alpine3.21 bundle plugin list
```
```
`/root` is not writable.
No plugins installed
```
