### ISSUE TITLE
RUBYGEMS_GEMDEPS throws exception when gem is not installed

### ISSUE THREAD

**Issue by michaelrkn** [rubygems/rubygems#886]
```
localhost:Code michael$ cd textbook/
/Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'httparty' (< 1.0, >= 0.6) among 373 total gem(s) (Gem::LoadError)
...
localhost:textbook michael$ gem install httparty
/Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/resolver.rb:406:in `resolve_for_zero': Unable to resolve dependency: 'rails (>= 0)' requires 'bundler (< 2.0, >= 1.3.0)' (Gem::UnsatisfiableDependencyError)
...
localhost:textbook michael$ gem install bundler
/Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/resolver.rb:406:in `resolve_for_zero': Unable to resolve dependency: 'rails (>= 0)' requires 'bundler (< 2.0, >= 1.3.0)' (Gem::UnsatisfiableDependencyError)
...
localhost:textbook michael$ gem install rails
/Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/resolver.rb:406:in `resolve_for_zero': Unable to resolve dependency: 'rails (>= 0)' requires 'bundler (< 2.0, >= 1.3.0)' (Gem::UnsatisfiableDependencyError)
```

Opening a new terminal window, running `$ gem install httparty`, and cd'ing back to the project directory fixed the problem.

**Comment by FranklinYu** [comment]
I met this again with RubyGems 2.7.6.2 under Ruby 2.5.5.
