### ISSUE TITLE
RUBYGEMS_GEMDEPS: `parse_DEPENDENCIES': undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by michaelrkn** [rubygems/rubygems#897]
```
localhost:problem michael$ bundle
/Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/request_set/lockfile.rb:255:in `parse_DEPENDENCIES': undefined method `version' for nil:NilClass (NoMethodError)
    from /Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/request_set/lockfile.rb:220:in `parse'
    from /Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/request_set.rb:228:in `load_gemdeps'
    from /Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:1031:in `use_gemdeps'
    from /Users/michael/.rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:1216:in `<top (required)>'
    from <internal:gem_prelude>:1:in `require'
    from <internal:gem_prelude>:1:in `<compiled>'
```

~/.bash_profile:

```
export RUBYGEMS_GEMDEPS=-
```

Gemfile:

```
source 'http://rubygems.org'

ruby '2.0.0'
gem 'rails', '4.0.0'

#gem 'nokogiri', :git => '/nokogiri/'

# Servers
# gem 'puma'
# gem 'unicorn'
gem 'eventmachine'

# Multi-environment configuration
# gem 'simpleconfig'

# API
# gem 'rabl'

# ORM
gem 'pg'

# Performance and Exception management
# gem 'airbrake'
# gem 'newrelic_rpm'

# Security
# gem 'secure_headers'

# Miscellanea
# gem 'google-analytics-rails'
gem 'haml'
# gem 'http_accept_language'
gem 'jquery-rails'
gem 'jquery-ui-rails'
# gem 'resque', require: 'resque/server' # Resque web interface

# Assets
gem 'coffee-rails', '~> 4.0.0'
gem 'haml_assets'
gem 'handlebars_assets'
gem 'i18n-js'
gem 'i18n-active_record',
            :git => 'git://github.com/svenfuchs/i18n-active_record.git',
            :require => 'i18n/active_record'
gem 'jquery-turbolinks'
gem 'sass-rails', '~> 4.0.0'
gem "compass-rails", "~> 1.1.3"
gem 'foundation-rails'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'sorcery', '>= 0.8.1'
gem 'oauth2', '~> 0.8.0'
gem 'ruby-drupal-hash'
gem 'redis'
gem 'carrierwave'
gem 'carrierwave-imageoptimizer'
gem 'mini_magick'
#gem 'carmen-rails'#, '~> 1.0.0', github: 'jim/carmen-rails'
gem 'nested_form'
gem 'acts_as_list'
##gem 'jcrop-rails'
##gem 'rmagick'

gem 'geocoder'
gem 'forgery'
gem 'paper_trail'


group :development, :test do
    #gem 'thin'
    gem 'debugger'
    gem 'delorean'
    gem 'factory_girl_rails'
    #gem 'faker'
    #gem 'pry'
    #gem 'pry-rails'
end

group :development do
  #gem 'perftools.rb'
  gem 'bullet'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'haml-rails'
  gem 'awesome_print'
  gem 'rails-footnotes', :github => 'josevalim/rails-footnotes'
end

group :test do
    gem 'capybara'
    gem 'coveralls', require: false
    gem 'database_cleaner'
    gem 'email_spec'
    gem 'launchy'
    gem 'rspec'
    gem 'rspec-rails'
    gem 'selenium-webdriver'
    gem 'simplecov', require: false
    gem 'webmock', require: false
end

group :staging, :production do
    gem 'rails_12factor'
end
```

Gemfile.lock:

```
GIT
  remote: git://github.com/josevalim/rails-footnotes.git
  revision: 3a6ac1971e91d822f057650cc5916ebfcbd6ee37
  specs:
    rails-footnotes (3.7.9)
      rails (>= 3.0.0)

GIT
  remote: git://github.com/svenfuchs/i18n-active_record.git
  revision: 55507cf59f8f2173d38e07e18df0e90d25b1f0f6
  specs:
    i18n-active_record (0.0.2)
      i18n (>= 0.5.0)

GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (4.0.0)
      actionpack (= 4.0.0)
      mail (~> 2.5.3)
    actionpack (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
    activerecord (4.0.0)
      activemodel (= 4.0.0)
      activerecord-deprecated_finders (~> 1.0.2)
      activesupport (= 4.0.0)
      arel (~> 4.0.0)
    activerecord-deprecated_finders (1.0.3)
    activesupport (4.0.0)
      i18n (~> 0.6, >= 0.6.4)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.37)
    acts_as_list (0.4.0)
      activerecord (>= 3.0)
    addressable (2.3.5)
    arel (4.0.2)
    atomic (1.1.14)
    awesome_print (1.2.0)
    bcrypt (3.1.7)
    bcrypt (3.1.7-x86-mingw32)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    bcrypt-ruby (3.1.5-x86-mingw32)
      bcrypt (>= 3.1.3)
    better_errors (1.1.0)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.1.4)
    bullet (4.8.0)
      activesupport
      uniform_notifier (>= 1.4.0)
    callsite (0.0.11)
    capybara (2.2.1)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    carrierwave (0.9.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
    carrierwave-imageoptimizer (1.2.1)
      carrierwave (~> 0.8)
      image_optimizer (~> 1.2)
    childprocess (0.5.1)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    chunky_png (1.3.0)
    coderay (1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.7.0)
    columnize (0.3.6)
    compass (0.12.2)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)
    compass-rails (1.1.3)
      compass (>= 0.12.2)
    coveralls (0.7.0)
      multi_json (~> 1.3)
      rest-client
      simplecov (>= 0.7)
      term-ansicolor
      thor
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    database_cleaner (1.2.0)
    debug_inspector (0.0.2)
    debugger (1.6.5)
      columnize (>= 0.3.1)
      debugger-linecache (~> 1.2.0)
      debugger-ruby_core_source (~> 1.3.1)
    debugger-linecache (1.2.0)
    debugger-ruby_core_source (1.3.1)
    delorean (2.1.0)
      chronic
    diff-lcs (1.2.5)
    docile (1.1.3)
    email_spec (1.5.0)
      launchy (~> 2.1)
      mail (~> 2.2)
    erubis (2.7.0)
    eventmachine (1.0.3-x86-mingw32)
    execjs (2.0.2)
    factory_girl (4.4.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.4.0)
      factory_girl (~> 4.4.0)
      railties (>= 3.0.0)
    faraday (0.9.0)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.3)
    ffi (1.9.3-x86-mingw32)
    forgery (0.5.0)
    foundation-rails (5.1.1.0)
      railties (>= 3.1.0)
      sass (>= 3.2.0)
    fssm (0.2.10)
    geocoder (1.1.9)
    haml (4.0.5)
      tilt
    haml-rails (0.5.1)
      actionpack (~> 4.0.0)
      activesupport (~> 4.0.0)
      haml (>= 3.1, < 5.0)
      railties (~> 4.0.0)
    haml_assets (0.2.2)
      haml
      tilt
    handlebars_assets (0.15)
      execjs (>= 1.2.9)
      multi_json
      sprockets (>= 2.0.3)
      tilt
    hike (1.2.3)
    httpauth (0.2.1)
    i18n (0.6.9)
    i18n-js (2.1.2)
      i18n
    image_optimizer (1.2.1)
    jquery-rails (3.1.0)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.0.2)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (4.2.0)
      railties (>= 3.2.16)
    json (1.8.1)
    jwt (0.1.11)
      multi_json (>= 1.5)
    launchy (2.4.2)
      addressable (~> 2.3)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    meta_request (0.2.8)
      callsite
      rack-contrib
      railties
    mime-types (1.25.1)
    mini_magick (3.7.0)
      subexec (~> 0.2.1)
    mini_portile (0.5.2)
    minitest (4.7.5)
    multi_json (1.8.4)
    multipart-post (2.0.0)
    nested_form (0.3.2)
    nokogiri (1.6.1-x86-mingw32)
      mini_portile (~> 0.5.0)
    oauth (0.4.7)
    oauth2 (0.8.1)
      faraday (~> 0.8)
      httpauth (~> 0.1)
      jwt (~> 0.1.4)
      multi_json (~> 1.0)
      rack (~> 1.2)
    paper_trail (3.0.0)
      activerecord (>= 3.0, < 5.0)
      activesupport (>= 3.0, < 5.0)
    pg (0.17.1)
    pg (0.17.1-x86-mingw32)
    polyglot (0.3.3)
    rack (1.5.2)
    rack-contrib (1.1.0)
      rack (>= 0.9.1)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.0.0)
      actionmailer (= 4.0.0)
      actionpack (= 4.0.0)
      activerecord (= 4.0.0)
      activesupport (= 4.0.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.0)
      sprockets-rails (~> 2.0.0)
    rails_12factor (0.0.2)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.2)
    rails_stdout_logging (0.0.3)
    railties (4.0.0)
      actionpack (= 4.0.0)
      activesupport (= 4.0.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.1.1)
    redis (3.0.7)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.7)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.5)
    rspec-rails (2.14.1)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    ruby-drupal-hash (0.0.3)
    rubyzip (1.1.0)
    safe_yaml (1.0.1)
    sass (3.2.14)
    sass-rails (4.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (>= 3.1.10)
      sprockets-rails (~> 2.0.0)
    selenium-webdriver (2.39.0)
      childprocess (>= 0.2.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0.4)
    simplecov (0.8.2)
      docile (~> 1.1.0)
      multi_json
      simplecov-html (~> 0.8.0)
    simplecov-html (0.8.0)
    sorcery (0.8.5)
      bcrypt-ruby (>= 3.0)
      oauth (~> 0.4.4)
      oauth2 (>= 0.8.0, < 1.0.0)
    sprockets (2.10.1)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.0.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    subexec (0.2.3)
    term-ansicolor (1.3.0)
      tins (~> 1.0)
    thor (0.18.1)
    thread_safe (0.1.3)
      atomic
    tilt (1.4.1)
    tins (1.0.0)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    turbolinks (2.2.1)
      coffee-rails
    tzinfo (0.3.38)
    uglifier (2.4.0)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    uniform_notifier (1.4.0)
    webmock (1.17.3)
      addressable (>= 2.2.7)
      crack (>= 0.3.2)
    websocket (1.0.7)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby
  x86-mingw32

DEPENDENCIES
  acts_as_list
  awesome_print
  better_errors
  binding_of_caller
  bullet
  capybara
  carrierwave
  carrierwave-imageoptimizer
  coffee-rails (~> 4.0.0)
  compass-rails (~> 1.1.3)
  coveralls
  database_cleaner
  debugger
  delorean
  email_spec
  eventmachine
  factory_girl_rails
  forgery
  foundation-rails
  geocoder
  haml
  haml-rails
  haml_assets
  handlebars_assets
  i18n-active_record!
  i18n-js
  jquery-rails
  jquery-turbolinks
  jquery-ui-rails
  launchy
  meta_request
  mini_magick
  nested_form
  oauth2 (~> 0.8.0)
  paper_trail
  pg
  rails (= 4.0.0)
  rails-footnotes!
  rails_12factor
  redis
  rspec
  rspec-rails
  ruby-drupal-hash
  sass-rails (~> 4.0.0)
  selenium-webdriver
  simplecov
  sorcery (>= 0.8.1)
  turbolinks
  uglifier (>= 1.3.0)
  webmock
```

When I remove `export RUBYGEMS_GEMDEPS=-` from my `bash_profile`, I can run `bundle` with no problems.

**Comment by Arcovion** [comment]
I'm getting this on Windows & Linux when trying `export RUBYGEMS_GEMDEPS=-`.

Here's the trace from Vagrant, just running `gem` as the simplest example:
```ruby
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ export RUBYGEMS_GEMDEPS=-
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ gem
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/request_set/lockfile.rb:520:in `pinned_requirement': undefined method `version' for nil:NilClass (NoMethodError)
        from /home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/request_set/lockfile.rb:301:in `parse_DEPENDENCIES'
        from /home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/request_set/lockfile.rb:254:in `parse'
        from /home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/request_set.rb:279:in `load_gemdeps'
        from /home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:1055:in `use_gemdeps'
        from /home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:1244:in `<top (required)>'
        from <internal:gem_prelude>:1:in `require'
        from <internal:gem_prelude>:1:in `<compiled>'
vagrant@vagrant-ubuntu-trusty-64:/vagrant$
```
`gem -v` is  `2.4.5`, `ruby -v` is `2.2.0`
I get this error for everything until I unset the env var. Am I doing something wrong?
