### ISSUE TITLE
Test Failures for Ruby 1.9.3 on Windows

### ISSUE THREAD

**Issue by luislavena** [rubygems/rubygems#984]
Note: this is a placeholder issue to workout each individual failure/exception mentioned below.

Latest commit: 379f50a5942028752963803cebcaef866e6feeca

```
C:\Users\Luis\Code\rubygems\rubygems>ruby -v
ruby 1.9.3p545 (2014-02-24) [i386-mingw32]

C:\Users\Luis\Code\rubygems\rubygems>gcc --version
gcc (tdm-1) 4.5.2
```

---

(beware, long list)

```
1781 tests, 5048 assertions, 5 failures, 6 errors, 65 skips

  1) Failure:
TestGemCommandsUninstallCommand#test_handle_options_vendor [C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_commands_uninstall_command.rb:259]:
--- expected
+++ actual
@@ -1,2 +1,3 @@
-"WARNING:  Use your OS package manager to uninstall vendor gems
+"WARNING:  Unable to use symlinks on Windows, installing wrapper
+WARNING:  Use your OS package manager to uninstall vendor gems
 "


  2) Error:
TestGemExtBuilder#test_build_extensions:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/bin/ruby.exe -r ./siteconf20140809-228-yve6ra.rb extconf.rb
creating Makefile

make  clean
Makefile:171: *** target pattern contains no `%'.  Stop.

make
Makefile:171: *** target pattern contains no `%'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/gems/a-2 for inspection.
Results logged to C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/extensions/x86-mswin32-60/1.9.1-static/a-2/gem_make.out

    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:89:in `run'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:51:in `block in make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:44:in `block in build'

    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/lib/ruby/1.9.1/tempfile.rb:320:in `open'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:19:in `build'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `chdir'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `block in build_extension'
    <internal:prelude>:10:in `synchronize'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:159:in `build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:198:in `block in build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_ext_builder.rb:124:in `block in test_build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:45:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:68:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_ext_builder.rb:123:in `test_build_extensions'

  3) Error:
TestGemExtBuilder#test_build_extensions_with_gemhome_with_space:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/bin/ruby.exe -r ./siteconf20140809-228-9dyik.rb extconf.rb
creating Makefile

make  clean
Makefile:171: *** target pattern contains no `%'.  Stop.

make
Makefile:171: *** target pattern contains no `%'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gem home/gems/a-2 for inspection.
Results logged to C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gem home/extensions/x86-mswin32-60/1.9.1-static/a-2/gem_make.out

    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:89:in `run'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:51:in `block in make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:44:in `block in build'
    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/lib/ruby/1.9.1/tempfile.rb:320:in `open'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:19:in `build'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `chdir'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `block in build_extension'
    <internal:prelude>:10:in `synchronize'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:159:in `build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:198:in `block in build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_ext_builder.rb:124:in `block in test_build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:45:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:68:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_ext_builder.rb:123:in `test_build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_ext_builder.rb:143:in `test_build_extensions_with_gemhome_with_space'

  4) Error:
TestGemExtBuilder#test_build_extensions_install_ext_only:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/bin/ruby.exe -r ./siteconf20140809-228-1orsvpo.rb extconf.rb
creating Makefile

make  clean
Makefile:171: *** target pattern contains no `%'.  Stop.

make
Makefile:171: *** target pattern contains no `%'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/gems/a-2 for inspection.
Results logged to C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/extensions/x86-mswin32-60/1.9.1-static/a-2/gem_make.out

    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:89:in `run'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:51:in `block in make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:44:in `block in build'
    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/lib/ruby/1.9.1/tempfile.rb:320:in `open'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:19:in `build'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `chdir'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `block in build_extension'
    <internal:prelude>:10:in `synchronize'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:159:in `build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:198:in `block in build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_ext_builder.rb:178:in `block in test_build_extensions_install_ext_only'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:45:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:68:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_ext_builder.rb:177:in `test_build_extensions_install_ext_only'

  5) Error:
TestGemInstaller#test_install_extension_flat:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/bin/ruby.exe -r ./siteconf20140809-228-gxa7ok.rb extconf.rb
creating Makefile

make  clean
Makefile:165: *** target pattern contains no `%'.  Stop.

make
Makefile:165: *** target pattern contains no `%'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/gems/a-2 for inspection.
Results logged to C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/extensions/x86-mswin32-60/1.9.1-static/a-2/gem_make.out

    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:89:in `run'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:51:in `block in make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:44:in `block in build'
    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/lib/ruby/1.9.1/tempfile.rb:320:in `open'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:19:in `build'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `chdir'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `block in build_extension'
    <internal:prelude>:10:in `synchronize'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:159:in `build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:198:in `block in build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/installer.rb:693:in `build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/installer.rb:242:in `install'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_installer.rb:1087:in `block in test_install_extension_flat'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:45:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:68:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_installer.rb:1083:in `test_install_extension_flat'

  6) Error:
TestGemInstaller#test_install_extension_and_script:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/bin/ruby.exe -r ./siteconf20140809-228-1th4zyi.rb extconf.rb
creating Makefile

make  clean
Makefile:171: *** target pattern contains no `%'.  Stop.

make
Makefile:171: *** target pattern contains no `%'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/gems/a-2 for inspection.
Results logged to C:/Users/Luis/AppData/Local/Temp/test_rubygems_228/gemhome/extensions/x86-mswin32-60/1.9.1-static/a-2/gem_make.out

    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:89:in `run'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:51:in `block in make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:43:in `make'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:44:in `block in build'
    C:/Users/Luis/Tools/Ruby/ruby-1.9.3-p545-i386-mingw32/lib/ruby/1.9.1/tempfile.rb:320:in `open'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/ext_conf_builder.rb:19:in `build'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `chdir'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:160:in `block in build_extension'
    <internal:prelude>:10:in `synchronize'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:159:in `build_extension'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:198:in `block in build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `each'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/ext/builder.rb:195:in `build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/installer.rb:693:in `build_extensions'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/installer.rb:242:in `install'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_installer.rb:1046:in `block in test_install_extension_and_script'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:45:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/lib/rubygems/user_interaction.rb:68:in `use_ui'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_installer.rb:1042:in `test_install_extension_and_script'

  7) Failure:
TestGemInstaller#test_check_that_user_bin_dir_is_in_path [C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_installer.rb:199]:
Expected "WARNING:  You don't have c:\\users\\luis\\appdata\\local\\temp\\test_rubygems_228\\gemhome\\bin in your PATH,\n\t  gem executables will not run.\n" to be empty.

  8) Failure:
TestGemInstaller#test_check_that_user_bin_dir_is_in_path_not_in_path [C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_installer.rb:224]:
Expected /C:\/Users\/Luis\/AppData\/Local\/Temp\/test_rubygems_228\/gemhome\/bin/ to match "WARNING:  You don't have c:\\users\\luis\\appdata\\local\\temp\\test_rubygems_228\\gemhome\\bin in your PATH,\n\t  gem executables will not run.\n".

  9) Failure:
TestGemInstaller#test_check_that_user_bin_dir_is_in_path_tilde [C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_installer.rb:214]:
Expected "WARNING:  You don't have c:\\users\\luis\\appdata\\local\\temp\\test_rubygems_228\\userhome\\bin in your PATH,\n\t  gem executables will not run.\n" to be empty.

 10) Failure:
TestGemSpecification#test_require_paths_default_ext_dir_for [C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_specification.rb:1803]:
Expected: ["/foo/ext-1", "lib"]
  Actual: ["C:/foo/ext-1", "lib"]

 11) Error:
TestGemSpecification#test_build_extensions_extensions_dir_unwritable:
NoMethodError: undefined method `base_dir' for nil:NilClass
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_specification.rb:1237:in `ensure in test_build_extensions_extensions_dir_unwritable'
    C:/Users/Luis/Code/rubygems/rubygems/test/rubygems/test_gem_specification.rb:1238:in `test_build_extensions_extensions_dir_unwritable'
```

**Comment by duckinator** [comment]
Latest commit: https://github.com/rubygems/rubygems/commit/102230953b693c77683ded2da2e0480aff845465

```
C:\Users\Marie\dev\ruby\rubygems\rubygems>ruby -v
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

C:\Users\Marie\dev\ruby\rubygems\rubygems>gcc -v
'gcc' is not recognized as an internal or external command,
```

```
1854 tests, 5238 assertions, 0 failures, 0 errors, 73 skips
```


Closing because this seems to have been resolved. If that's not the case, reply here letting me know and I'll reopen it.
